### PR TITLE
Regenerate

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @shuyangzhou,

Here it is. I didn't put an LPS on the last two commits cause I didn't know if you already had a ticket for that. Let me know if that works.

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brunobasto can you also fix the logic inside https://github.com/brunobasto/alloy-taglibs/blob/master/alloy-taglib/src/com/liferay/alloy/tools/tagbuilder/templates/init_jsp.ftl ? It is still generating code for scopedAttributes.

Thanks!

**Comment by shuyangzhou** [comment]
@brunobasto
It is in this line https://github.com/brunobasto/alloy-taglibs/blob/master/alloy-taglib/src/com/liferay/alloy/tools/tagbuilder/templates/init_jsp.ftl#L50

I think you just need to push it down to the <#if component.isAlloyComponent()> block, right?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45883

**Pull request closed without merging**
