### PR TITLE
[TECHNICAL-SUPPORT] LPS-72947 VerifyPermission

### PR DESCRIPTION
**Pull request by Preston-Crary**
I ran the VerifyPermissionTest, on MySQL with my changes and it still passes.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by holatuwol** [comment]
@Preston-Crary: Table names are limited to 30 characters on Oracle 12c Release 1, so the table rename may not work across supported platforms, even if it passes CI.

**Comment by Preston-Crary** [comment]
@holatuwol right, forgot about that.  It should fail for Oracle on the CI then.

@shuyangzhou let me know if you want me to resend after shortening the names.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5388

**Pull request closed without merging**
