### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: When you get an opportunity please take a look at these failures. All the changes in this PR made it through CI just a few days ago prior to moving all the apps from collaboration, foundation, forms-and-workflow, and web-experience. This latest PR has no merge conflicts and is basically the same. Thanks.

**Comment by jpince** [comment]
@shuyangzhou if you and Neil are comfortable with it, I have no objections moving this forward to BChan.

**Comment by jpince** [comment]
@shuyangzhou see also master-private pull https://github.com/shuyangzhou/liferay-portal-ee/pull/397

**Comment by jpince** [comment]
cc/ APIO team @ahdezma @nhpatt

**Comment by ngriffin7a** [comment]
@petershin Thanks, I'll do that right now.

**Comment by ngriffin7a** [comment]
Sent new PR, see: https://github.com/shuyangzhou/liferay-portal/pull/6106

**Pull request closed without merging**
