### PR TITLE
[TECHNICAL-SUPPORT] LPS-73238 Edge case performance improvements for URLs

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:close

**Comment by holatuwol** [comment]
Confirmed that my changes were causing the failure for CPDocumentsandmedia#MoveToRecycleBinFolder, will resend.

**Pull request closed without merging**
