### PR TITLE
LPS-52962

### PR DESCRIPTION
**Pull request by holatuwol**
Please see: https://issues.liferay.com/browse/LPS-52962

### CODE REVIEW

**Comment by holatuwol** [comment]
Hi Shuyang,

Another option was to implement this as a map wrapper around the session, which didn't actually convert to the map ever but rather just went directly against the session. If you'd prefer that from a performance perspective rather than adding more proxy classes, please let me know.

**Comment by holatuwol** [comment]
Updated to use a map wrapper instead of using proxies.

**Comment by shuyangzhou** [comment]
Can you come up to have a quick talk about this? Thanks!

**Comment by holatuwol** [comment]
Updated to throw UnsupportedOperationException for write methods, removed calling of keySet in order to iterate over attribute names and instead created an iterator.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/23495

**Pull request closed without merging**
