### PR TITLE
LPS-96210 Adds com.liferay.portlet.control-panel-entry-category and com.liferay.portlet.control-panel-entry-weight property since we need it on PortletPanelAppAdapterServiceTrackerCustomizer to register PortletPanelApp

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@ealonso if the LCS fix is merged (https://github.com/brianchandotcom/liferay-portal-ee/pull/24750), will we still need this change?

We also still need to determine where there was a regression.

**Comment by jpince** [comment]
@vicnate5 this is solving the root issue. So this PR is not a release requirement, but we should get it in to prevent this situation in the future.
from @ealonso:
> We have two ways of register portlets
> 1. The OSGI way
> 2. The xml way that we use before OSGI
> 
> For OSGI way, you need to register a class PanelApp to show your application on the right panel
> 
> also for the clients that doesn't have OSGI portlets we create a layer of compatibility that get the properties and register a PanelAPP for you
>
> this layer also should work if you don't have the PanelApp and you have those properties in your OSGI Portlet, then if you have those properties it should create the PanelApp -> this is the issue that I've fixed
>
> All of our portlets have the PanelApp class except the LCS Portlet

**Comment by jpince** [comment]
ci:test:bundle

**Comment by jpince** [comment]
@vicnate5 also, Eudaldo said "it never worked", so they're not sure why LCS showed up in GA1-build1.

**Comment by vicnate5** [comment]
Confirmed the fix in brianchandotcom/liferay-portal-ee#24750 resolves the issue for LCS.

**Comment by jpince** [comment]
@vicnate5 @brianchiu does this expose apps in the Product Menu that shouldn't be there? 
Bundle from this PR:
extra apps in product menu: OpenSocial Gadget Editor, Kaleo Forms Admin, Reports Admin
extra apps in add menu: OpenSocial Gadget, Reports Display
LPS-96210 - extra apps - 2019-05-29

Screenshot from test-6-1-2 (master: 45ae4280460cc29e4378ae293c0879c53f2f13ed)
test-6-1-2 - 2019-05-29

So if we do decide to implement this, maybe after GA1, with additional testing?

**Comment by vicnate5** [comment]
These don't sound like apps I would not expect, but they are not in my scope. @inacionery should these be showing?

**Comment by ealonso** [comment]
I'm going to close it for now, since the second commit is causing it.

**Comment by inacionery** [comment]
Yes, these should be showing.

**Pull request closed without merging**
