### PR TITLE
LPS-84580 ServiceRegistry.lookupServiceRegistrations()

### PR DESCRIPTION
**Pull request by Preston-Crary**
From Tom's testing it looks like it's faster to keep 9136fea.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
It can not generate report due to too many failures:
```
Portal log assert failure, see above log for more information: 
Exception occured on JMX Notification dispatch for event [org.osgi.framework.ServiceEvent[source={org.osgi.service.url.URLStreamHandlerService}={url.handler.protocol=jardir, service.id=1912, service.bundleid=40, service.scope=singleton}]] 
java.lang.NullPointerException
	at org.eclipse.osgi.internal.serviceregistry.ObjectClassUtil.getRequiredObjectClass(ObjectClassUtil.java:25)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.lookupServiceRegistrations(ServiceRegistry.java:995)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getServiceReferences(ServiceRegistry.java:309)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getAllServiceReferences(BundleContextImpl.java:535)
	at org.apache.aries.jmx.framework.ServiceState.getServiceIds(ServiceState.java:203)
	at org.apache.aries.jmx.framework.ServiceState.getAttributeChangeNotification(ServiceState.java:295)
	at org.apache.aries.jmx.framework.ServiceState$1.serviceChanged(ServiceState.java:262)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:917)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:482)
	at org.apache.felix.fileinstall.internal.FileInstall.start(FileInstall.java:76)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6641

**Pull request closed without merging**
