### PR TITLE
LPS-145690 Bundle util-slf4j.jar into portal-impl.jar as other util-*…

### PR DESCRIPTION
**Pull request by shuyangzhou**
….jar do for consistency

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The unique failure here must be a fluke, I cannot reproduce the UI locally. This should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112359

**Pull request closed without merging**
