### PR TITLE
LPS-111140 Add assert to workflow

### PR DESCRIPTION
**Pull request by inacionery**
Hi @shuyangzhou,

Could you please help me with this?

I'm not able to make the tests pass in the CI and I was not able to reproduce this locally.

Thank you.

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/inacionery/liferay-portal/pull/735

**Pull request closed without merging**
