### PR TITLE
Lps 176935 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:account

**Comment by vicnate5** [comment]
Integration test regressions:

1. https://testray.liferay.com/home/-/testray/case_results/2216126019
2. https://testray.liferay.com/home/-/testray/case_results/2216125141
3. https://testray.liferay.com/home/-/testray/case_results/2216125131
4. https://testray.liferay.com/home/-/testray/case_results/2216125126
5. https://testray.liferay.com/home/-/testray/case_results/2216121137
6. https://testray.liferay.com/home/-/testray/case_results/2216123142
7. https://testray.liferay.com/home/-/testray/case_results/2216121699

Also some functional tests failed, I can look into those tomorrow, but hopefully the integration results show a possible root problem.

Relevant caught all the regressions, no need to re-run the other suites.

**Comment by shuyangzhou** [comment]
Oops, the pull was based on Brian's origin which has those issue.
Rebased on top of upstream master to rerun.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by vicnate5** [comment]
ci:test:account

**Comment by vicnate5** [comment]
ci:test:tango-acceptance

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131043

**Pull request closed without merging**
