### PR TITLE
Use new Arquillian Liferay Extension

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
Hi @shuyangzhou,

   This pull use the new Arquillian Liferay Extension. Can you release the new junit bridge, so we can use the new extension.

Thank you!!!!!

**Comment by shuyangzhou** [comment]
@cgoncas please fix those failures first.

**Comment by cgoncas** [comment]
Hey @shuyangzhou,

I cant fix it, because i cant publish a new release for the Junit bridge. Can you publish the new dependency with my first commit? Then al should be fixed?

Thanks

**Comment by shuyangzhou** [comment]
I can not do that either, only Brian can. And he won't merge it until it is passing.
I am sure you can publish it locally, and manually populate the gradle cache with the new version, so that CI won't complain anything, as it will load it from gradle cache, rather than going online.

**Comment by cgoncas** [comment]
Ok, how can i populate the cache manually?

**Comment by shuyangzhou** [comment]
If you know how gradle layouts its cache folders, it will actually be very easy.

For example, use the exist 1.0.0 version cache as an example.
Under folder liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.arquillian.extension.junit.bridge/1.0.0, there are 2 sub-folders:
1)c0f5a1792f476a6ec86bde780991f7b215787f61/com.liferay.arquillian.extension.junit.bridge-1.0.0.pom
2)cf6e833d2cae2b820cc1af1d5c2f1523337aab31/com.liferay.arquillian.extension.junit.bridge-1.0.0.jar

If you run the sha1sum for the pom and jar files, you will see the folder names are exactly their sha1sum.

So that means, if you need to manually put in a new version:
1) Publish it to your local m2 repo first, so that you have the content of the new version's pom and jar.
2) Create the newer version's folder inside gradle cache folder.
3) Run sha1sum for your newer version pom and jar files, use the hash values as sub-folder names.
4) Name the pom and jar following the exist naming pattern.

Then gradle will just pick it up. Since the new version has not really published yet, you can just run it locally to check this manually populating, if you do it right gradle won't try to go online, it won't fail on resolving, the tests should run.

**Comment by brianchandotcom** [comment]
@cgoncas I can publish a newer version, I won't apply it until you send me a pull applying it.

**Comment by brianchandotcom** [comment]
@cgoncas I published it!

**Comment by brianchandotcom** [comment]
@cgoncas I also sent myself  a pull here https://github.com/brianchandotcom/liferay-portal/pull/32634

if it works, I"ll merge it in. Thx @cgoncas !

**Comment by cgoncas** [comment]
Great Brian!!! Thank you

**Comment by cgoncas** [comment]
Great @brianchandotcom !!! I will wait to see the results of the pull.

Thank you a lot!!!

**Comment by brianchandotcom** [comment]
@cgoncas it's pushed upstream! Thanks Cristina!

**Comment by cgoncas** [comment]
Great!!!!!!

**Pull request closed without merging**
