### PR TITLE
[TECHNICAL-SUPPORT]  LPS-97025 Delete and re-add page in site template

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @shuyangzhou ,

@danielkocsis has already reviewed the staging part. The commit that mostly affects the core infrastructure is this one: https://github.com/shuyangzhou/liferay-portal/commit/a1497f63ce05ed54f27c6e56e53c9c00319ba465

See details in this [JIRA comment](https://issues.liferay.com/browse/LPS-97025?focusedCommentId=1877237&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1877237)

Thanks,
Vendel

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vendeltoreki** [comment]
Hi @shuyangzhou , 

I checked the CI failures (e.g.: WorkflowCalendar#ApproveEventWithInvitedUser), they look very similar to the other ones found in another pull: https://github.com/shuyangzhou/liferay-portal/pull/7953#issuecomment-507929242

I'm starting a new CI test.

**Comment by vendeltoreki** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou test failures not related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75432

**Pull request closed without merging**
