### PR TITLE
Lps 130746

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failure not related, looks like some race issue with the upgrade.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100912

Thanks @vicnate5 !

**Pull request closed without merging**
