### PR TITLE
LPS-62555 Reduce database access during permission checking

### PR DESCRIPTION
**Pull request by Preston-Crary**
I've already had @tomwang2011 test this https://github.com/tomwang2011/liferay-portal/pull/78 it resolved the performance regression.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Rebased, no conflicts.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
This changed quite a bit since when I first sent the pull since we made some security improvements with how we check permissions.

@topolik I've separated permission validation from permission checking so that we can skip the permission checking for admins, please take a look at those changes when you get a chance.

**Comment by topolik** [comment]
Hi @Preston-Crary , looks good, thanks.

Sorry for the ongoing changes in AdvancedPermissionChecker, we had several issues there and still not everything is resolved.

Please see https://github.com/rotty3000/liferay-portal/pull/1157. I expect rebase conflicts, we both use similar logic so we should align somehow. 

I noticed that here we no longer call ResourceLocalService.hasUserPermission(). If any customer customized ResourceLocalService and expects we call it, this time it will be ignored. Maybe we should document it in some breaking changes, just and idea.

**Comment by Preston-Crary** [comment]
@shuyangzhou I've rebased the pull, no conflicts.

**Comment by shuyangzhou** [comment]
Closing old pulls, we can revisit if necessary

**Pull request closed without merging**
