### PR TITLE
LPS-50182

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/31533

**Comment by sergiogonzalez** [comment]
Hey @shuyangzhou 

The reason why we decided to use Thread.sleep is that in this particular scenario it actually makes sense because it simplifies things a lot and it shouldn't add any randomness to the test. 
This test is actually testing that when add a temporal file entry, the file and all the folders associated to that file are properly deleted after the expiration time (that is configurable). So, we just decided to configure the expiration time to 1ms and then wait 2 ms, run the code to delete the files, and check that the files are folders are deleted.

Feel free to ask us any question in case you have any doubt.

cc/ @izaera

**Comment by izaera** [comment]
The key are these two instructions:

<code>
		temporaryFileEntriesCapability.setTemporaryFileEntriesTimeout(1);

		Thread.sleep(2);
</code>

The first one sets the timeout to 1ms, while the second waits 2ms. This should not introduce any randomness as long as Thread.sleep guarantees to sleep at least the value of its argument which I think it does. The docs say:

"subject to the precision and accuracy of system timers and schedulers" 

( see https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#sleep(long) )

which in any decent desktop (as opposed to embedded) architecture should be more than milliseconds.

The only caveat would be Thread.sleep throwing an InterruptedException, but that would make the test fail so it shouldn't be a problem at all.

/cc: @sergiogonzalez @brianchandotcom @shuyangzhou

**Comment by izaera** [comment]
BTW: the good solution would be being able to mock the system clock, but we cannot do that in our current architecture as it is not enough decoupled from system primitives.

Other options could be changing the DB data created by DL in the test to fake the creation time or a similar hack, but IMHO that would be much more fragile than calling Thread.sleep().

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/31577

**Pull request closed without merging**
