### PR TITLE
LPS-84521

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou this came to me from https://github.com/brianchandotcom/liferay-portal/pull/62468

I made a few changes, but I'm afraid of boot up performance, can you have someone from your team review?

Thx.

**Comment by shuyangzhou** [comment]
@slnn @tomwang2011 please run regression tests, thanks!

**Comment by slnn** [comment]
OK, got it. @shuyangzhou

**Comment by slnn** [comment]
Here are test results, no performance regression appeared.
Login:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 75a901d | 48979 | 288 | 88.1
PR-6681 | - | 49100 | 282 | 85.9

Blog:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 75a901d | 13583 | 56.8 | 157
PR-6681 | - | 13517 | 50 | 150

Message Board:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 75a901d | 15691 | 25.6 | 60
PR-6681 | - | 15592 | 18.6 | 54.4

Asset Publisher:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 75a901d | 25834 | 474 | 207
PR-6681 | - | 25469 | 477 | 206

Wiki:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 75a901d | 16421 | 406 | 594
PR-6681 | - | 16716 | 395 | 595

Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 75a901d | 63794 | 568 | 195
PR-6681 | - | 62908 | 539 | 188'

Document Library:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 75a901d | 26777 | 328 | 402
PR-6681 | - | 26932 | 276 | 344

**Comment by topolik** [comment]
Hi @shuyangzhou,

may I ask you to finish this PR? It has very high priority.

Thank you.

**Comment by shuyangzhou** [comment]
I will try to get on to it tomorrow. Sorry, got caught up by too many things last week.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62724

**Pull request closed without merging**
