### PR TITLE
[TECHNICAL-SUPPORT] LPS-78134

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-78134

There are two problems with dynamic-data-source-spring.xml:

- It has dependencies with both 'spring.configs' and 'spring.infrastructure.configs' xml spring definitions
- It overwrites some beans of 'infrastructure-spring.xml', but it is after of dynamic-data-source-spring.xml

In order to solve them:

1.  I am splitting the current dynamic-data-source-spring.xml in two (dynamic-data-source-spring.xml and dynamic-data-source-infrastructure-spring.xml (same approach was done with counter-spring.xml on LPS-54649). See commits: https://github.com/shuyangzhou/liferay-portal/commit/7371ebe9ffdabc52ab27e4de0f11b3a78bd659a1 and https://github.com/shuyangzhou/liferay-portal/commit/819475f633e7013fb15ee0c9c5b9e004e426e1ce
2. I am also reordering spring xml in infrastructure settings. See commit: https://github.com/shuyangzhou/liferay-portal/commit/c26fe38cc5d5e27b7aaf34ad1ad6eba0449c111b

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55761

**Pull request closed without merging**
