### PR TITLE
LPS-X Avoid re-registering ContextEntityModel on RequestContextContri…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…butor changes to prevent cascaded shutdown time component reactivation.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this affects segmemts. any other tests we should run?

**Comment by vicnate5** [comment]
ci:test:tango

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121194

**Pull request closed without merging**
