### PR TITLE
LPS-136445

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull remove all dependecis on com.liferay.registry in service builder generated code for 7.3 and 7.4

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@tinatian no unique failures seems to be related to this pull (look like rare race conditions that are happening on some of the tests upstream), ill run this again to confirm just in case

**Comment by kyle-miho** [comment]
ci:reevaluate:1277401_756

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@tinatian @shuyangzhou pull should be good, no unique failures

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105265

**Pull request closed without merging**
