### PR TITLE
LPS-61258 Partially revert LPS-60137 241d1eb, the other parts of this commit are nessesary to resolve the bug but this is not and causes us to use an uncached query during sign in.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased to latest master.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34141

**Pull request closed without merging**
