### PR TITLE
LPD-X This is a workaround for the broken logic added in b4085258b87c…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…5228c77e8980e9dc44548413bf12 .That commit basically made BlankSiteInitializer requires WelcomeSiteInitializer run after it to work properly. However the WelcomeSiteInitializer has previously ran during the company creation, this change blindly deletes the layouts belong to WelcomeSiteInitializer, only hoping WelcomeSiteInitializer will rerun to fix the wrongfully deleted data. This was working because the previous bug fixed by LPD-30222. We were running the SiteInitializer 3 times for each group, which was very wasteful. After the duplicated SiteInitializer runs is fixed, now no one is fixing the deleted WelcomeSiteInitializer layouts for BlankSiteInitializer, therefore we have this issue. This work around is merely readd back the duplicated call to WelcomeSiteInitializer for BlankSiteInitializer. The real fix should be avoid doing blindly layout removal, either create the data correct from beginning or just fix the broken data without touching others.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:67437806

**Comment by vicnate5** [comment]
@shuyangzhou On this one just 2 unique failures, both about leftover data

https://testray.liferay.com/#/project/34754/routines/34756/build/67437806/case-result/67444104
https://testray.liferay.com/#/project/34754/routines/34756/build/67437806/case-result/67443512

**Comment by shuyangzhou** [comment]
Ok, those are not related, I will send this pull out, thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153494

**Pull request closed without merging**
