### PR TITLE
Fix headless builder resource test

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions. com.liferay.headless.builder.resource.test.HeadlessBuilderResourceTest passed on CI.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142542

**Pull request closed without merging**
