### PR TITLE
Lps 83456 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@arthurchan35 what is this https://github.com/shuyangzhou/liferay-portal/pull/6819/commits/ce496780184163d4d9e071c8281753c607ceee3f ?
You are adding those throws for no reasons.

**Comment by shuyangzhou** [comment]
@arthurchan35 and your commit message in https://github.com/shuyangzhou/liferay-portal/pull/6819/commits/6dff5b96e067ef3416bc5355caeb88bd5ae74b14 says "auto-gen", that can not be true, those 2 classes are not generated at all.

**Comment by hhuijser** [comment]
@shuyangzhou, we need to throw those exceptions:
```
     [exec] C:\github\liferay-portal\modules\apps\portal-configuration\portal-configuration-settings\src\main\java\com\liferay\portal\configuration\settings\internal\SettingsLocatorHelperImpl.java:193: error: unreported exception NoSuchPortletPreferencesException; must be caught or declared to be thrown
     [exec]                             return _portletPreferencesFactory.getStrictPortletSetup(
     [exec]                                                                                    ^
     [exec] 1 error
```

**Pull request closed without merging**
