### PR TITLE
LPS-120419 Directly register license inside lpkg to avoid race condit…

### PR DESCRIPTION
**Pull request by mtambara**
…ion with app resolver hook

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@shuyangzhou @mtambara I didn't get a chance to test on 7.1 yet, but this is definitely reproducible on 7.2.  Is this change cleanly backportable to 7.0?

**Comment by shuyangzhou** [comment]
@brianwulbern it should be backportable to 7.0 once support merges https://github.com/liferay/liferay-portal-ee/pull/20553

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9447

**Pull request closed without merging**
