### PR TITLE
Startup optimization 137 remove liferay display

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Two issue found

1) service-builder-jdk8/0/0
```
     [echo]  Export-Package: com.liferay.portal.instances.service
     [echo] \ No newline at end of file
     [echo] diff --git a/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalService.java b/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalService.java
     [echo] index d5f7f14e7b96..3aa981fbd029 100644
     [echo] --- a/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalService.java
     [echo] +++ b/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalService.java
     [echo] @@ -24,7 +24,6 @@ import com.liferay.portal.kernel.transaction.Transactional;
     [echo]  
     [echo]  import java.sql.SQLException;
     [echo]  
     [echo] -import javax.servlet.ServletContext;
     [echo]  import javax.servlet.http.HttpServletRequest;
     [echo]  
     [echo]  import org.osgi.annotation.versioning.ProviderType;
     [echo] diff --git a/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalServiceUtil.java b/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalServiceUtil.java
     [echo] index 5a19c7d55a96..f7402accb6e0 100644
     [echo] --- a/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalServiceUtil.java
     [echo] +++ b/modules/apps/portal-instances/portal-instances-api/src/main/java/com/liferay/portal/instances/service/PortalInstancesLocalServiceUtil.java
     [echo] @@ -74,8 +74,7 @@ public class PortalInstancesLocalServiceUtil {
     [echo]  			long companyId, String siteInitializerKey)
     [echo]  		throws PortalException {
     [echo]  
     [echo] -		getService().initializePortalInstance(
     [echo] -			companyId, siteInitializerKey);
     [echo] +		getService().initializePortalInstance(companyId, siteInitializerKey);
     [echo]  	}
     [echo]  
     [echo]  	public static boolean isAutoLoginIgnoreHost(String host) {
[stopwatch] [run.batch.test.action: 22:48.052 sec]
     [echo] .
     [echo] 
     [echo] Detected build services changes. See above build services log for more
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5871/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2) Semever issue
```
[exec] > Task :apps:portal-instances:portal-instances-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.instances.service               MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.instances.service.PortalInstancesLocalServiceUtil
     [exec] 		+   method     initializePortalInstance(long,java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		-   method     initializePortalInstance(long,java.lang.String,javax.servlet.ServletContext)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		+   method     reload()
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		-   method     reload(javax.servlet.ServletContext)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 	>   class      com.liferay.portal.instances.service.PortalInstancesLocalServiceWrapper
     [exec] 		+   method     initializePortalInstance(long,java.lang.String)
     [exec] 			+   return     void
     [exec] 		-   method     initializePortalInstance(long,java.lang.String,javax.servlet.ServletContext)
     [exec] 			-   return     void
     [exec] 		+   method     reload()
     [exec] 			+   return     void
     [exec] 		-   method     reload(javax.servlet.ServletContext)
     [exec] 			-   return     void
     [exec] 	>   interface  com.liferay.portal.instances.service.PortalInstancesLocalService
     [exec] 		+   method     initializePortalInstance(long,java.lang.String)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		-   method     initializePortalInstance(long,java.lang.String,javax.servlet.ServletContext)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		+   method     reload()
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		-   method     reload(javax.servlet.ServletContext)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 8.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.instances.api-7.1.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.instances.api/7.1.1/a02501a0ae0355a2d9392600cebf2cfe2308378f/com.liferay.portal.instances.api-7.1.1.jar
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5871/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128369

**Pull request closed without merging**
