### PR TITLE
LRQA-33560 Test with updates requested by Shuyang

### PR DESCRIPTION
**Pull request by michaelhashimoto**
The following updates have been applied:
* Fixed git hash for the portals-pluto, like what we do for the portal-ee and plugins
* In build-test-tck.xml, target "test-class-group", try to avoid calling deploy-portlet-tck-* multiple times
* Empty out the ignoredTestCases.xml, so that we see all the failing tests on CI

This pull request should also only test TCK 3.0 tests.

@shuyangzhou @vsingleton

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian for instructions of running tck tests locally, see https://github.com/shuyangzhou/liferay-portal/pull/4603#issue-245474888

**Comment by tinatian** [comment]
@shuyangzhou OK, I will ask Dante to start working on this.

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
It looks like there are about 1,205 test failures.
https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/86042/#showFailuresLink

**Pull request closed without merging**
