### PR TITLE
Lps 155482

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by catarineaguiar** [comment]
found a possible regression, can you take a look?

`SharepointConnectionTest`
```
 [exec] com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > testCopyFolder STARTED
     [exec] 
     [exec] com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > testCopyFolder FAILED
     [exec]     com.liferay.sharepoint.soap.repository.connector.SharepointResultException: Unknown: The URL 'Documents/Folder1 1654616943520/SubFile1 1654616943520.txt' is invalid.  It may refer to a nonexistent file or folder, or refer to a valid file or folder that is not in the current Web.
     [exec]         at com.liferay.sharepoint.soap.repository.connector.operation.AddOrUpdateFileOperation._processCopyIntoItemsResponseDocument(AddOrUpdateFileOperation.java:140)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.operation.AddOrUpdateFileOperation.execute(AddOrUpdateFileOperation.java:57)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionImpl.addFile(SharepointConnectionImpl.java:103)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest.addSharepointObjects(SharepointConnectionTest.java:675)
     [exec]         at com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest.testCopyFolder(SharepointConnectionTest.java:215)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-32/test-portal-acceptance-pullrequest(master)/4223/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:test

@catarineaguiar I don't think it is related, rerunning the test.

**Comment by shuyangzhou** [comment]
@catarineaguiar please check the new results, thanks!

**Comment by catarineaguiar** [comment]
Hi @shuyangzhou, in fact it is not related. The pull is good to go.

**Comment by shuyangzhou** [comment]
ci:forward

Thanks @catarineaguiar !

**Pull request closed without merging**
