### PR TITLE
LPS-91324 fix the javax.mvc-api dependency

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@ngriffin7a

**Comment by rotty3000** [comment]
ci:test:backend

**Comment by rotty3000** [comment]
@vicnate5

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou @ngriffin7a @rotty3000 Test results look good.

**Comment by ngriffin7a** [comment]
@rotty3000 Thanks for fixing!

@vicnate5 Thanks for reviewing!

@shuyangzhou This is scheduled for inclusion with 7.3, so please review at your earliest convenience. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83363

**Pull request closed without merging**
