### PR TITLE
LPS-124713 ServiceUtil injection

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the result, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The semver isssue is from this change, but otherwise this is clean.

**Comment by Preston-Crary** [comment]
Looks like build service commit it stale already.

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou Will be hard for this one to fully pass because Relevant is running a larger amount of tests than normal when SB regens all of portal. This should be manually forwarded.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99357

**Pull request closed without merging**
