### PR TITLE
[Trash Compat]LPS-89594

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:4af31cffb4ba796bc7707431292bb348b28638d1

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
Possible unique Poshi failures
1) https://testray.liferay.com/home/-/testray/case_results/931951281?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D931872041%26testrayRunId%3D931872043%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc
2) https://testray.liferay.com/home/-/testray/case_results/931951281?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D931872041%26testrayRunId%3D931872043%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by kyle-miho** [comment]
Integration tests look good, it seems like some network issues caused some random failures but, i didnt find anything unique

**Comment by tinatian** [comment]
Rerun to comfirm

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
issue with cdn right now, network issue

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 This one is also a deprecation pull, please scan test result.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@shuyangzhou Test results are good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82703

**Pull request closed without merging**
