### PR TITLE
[Startup Tuning]LPS-96830

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
cc @Preston-Crary

**Comment by shuyangzhou** [comment]
@tinatian this should be using a static Holder class to init it in inner class classloading, not by a Holder object. please resend.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/7914

**Pull request closed without merging**
