### PR TITLE
[ResourceAction]LPS-112054 rebase

### PR DESCRIPTION
**Pull request by dantewang**
Rebased https://github.com/shuyangzhou/liferay-portal/pull/9088

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by tinatian** [comment]
@dantewang Please rebase.

Tina.

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
