### PR TITLE
LPS-108239 Fix CompanyInfoLocalServiceTest mvcc failures

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 this does not look like real, what should I do now?

**Comment by vicnate5** [comment]
Resent:
https://github.com/shuyangzhou/liferay-portal/pull/8961

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
