### PR TITLE
LPS-76058 Portlet 3.0: Consolidate PortletURL property initialization in the main PortletURLImpl constructor

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jpince: This one too -- when you get a chance please verify that these failures are unrelated to this PR. Thanks so much.

**Comment by jpince** [comment]
@ngriffin7a looks good

**Comment by ngriffin7a** [comment]
Thanks @jpince -- @shuyangzhou looks like this one is ready for review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53226

**Pull request closed without merging**
