### PR TITLE
Auto deploy listener cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou I still need to check a few things manually, but the automation results are looking good

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! Take your time!

**Comment by vicnate5** [comment]
Ran additional automation tests to check deployment of automated archives on all app servers
https://github.com/vicnate5/liferay-portal/pull/1906#issuecomment-988258918
No issues found.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! See https://github.com/brianchandotcom/liferay-portal/pull/110848

**Pull request closed without merging**
