### PR TITLE
LPS-X Push down ccpp.jar to portal-web scope, and remove endorsed.lib…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…raries

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results thanks!

**Comment by vicnate5** [comment]
@koor4356 Please review results for all test suites here

**Comment by koor4356** [comment]
ci:retest:upgrade

**Comment by koor4356** [comment]
ci:retest:environments

**Comment by koor4356** [comment]
I am retesting running upgrade and environment because many upgrades are aborted and half of the environments are failing.

**Comment by shuyangzhou** [comment]
@koor4356 tests are done, please help me check the results, thanks!

**Comment by koor4356** [comment]
@shuyangzhou, I am working on them, I should give an update soon.

**Comment by koor4356** [comment]
@shuyangzhou @vicnate5,
Everything looks good except this one commerce test. I don't think it is related to this PR. But it worth mention because failure only occurs on this pull. I could have tested this locally but no enough time. Thanks!

https://testray.liferay.com/home/-/testray/case_results/1528677745?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1528676910%26testrayRunId%3D1528677260%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by shuyangzhou** [comment]
Thanks @koor4356 ! See https://github.com/shuyangzhou/liferay-portal/pull/9989

**Pull request closed without merging**
