### PR TITLE
LPS-105916 Modules sql files never use velocity template.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou This should be good, just noting a couple issues here that do not look related.

There were some issues on the HSQL integration tests
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/346275/

Also all but 1 of the App Builder functional tests failed. It is most likely a bad slave (they all ran on the same one), but I will test locally.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou App builder tests passed locally

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82302

**Pull request closed without merging**
