### PR TITLE
Update last login 2 params

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:users

**Comment by shuyangzhou** [comment]
ci:report:11643515

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login test case:

Portal Version | Hash | Session Count | Session Count Change (%) | Mean Time of Login | Error or exception in catalina.out | Meantime of Log out | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 2084305 | 12710 | - | 272 | No error | 59.8 | 1,1,1 | 5,4,6 | 94,96,95
PR2 | - | 13240 | 4.169944925 | 276 | No error | 66.5 | 4,3,2 | 0,0,0 | 95,95,96


I updated the spreadshseet with the result.
The test round on the PR https://github.com/shuyangzhou/liferay-portal/pull/11634 is still in progress.

**Comment by shuyangzhou** [comment]
@victorhcunha the DB CPU usage increase is quite unexpected. I need a runtime async cpu profile for this. The same profile you do for daily monitoring.

**Comment by victorhcunha** [comment]
For the PR https://github.com/shuyangzhou/liferay-portal/pull/11634 here are the results:

Portal Version | Hash | Session Count | Session Count Change (%) | Mean Time of Login | Error or exception in catalina.out | Meantime of Log out | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 2084305 | 12710 | - | 272 | No error | 59.8 | 1,1,1 | 5,4,6 | 94,96,95
PR1 | - | 12961 | 1.974822974 | 281 | No error | 67.5 | 2,2,1 | 7,7,7 | 96,96,97

I updated the spreadsheet with the results.

**Comment by victorhcunha** [comment]
The  async cpu [profile](https://drive.google.com/file/d/1z9lu41IRYsNmjX2QlWD7qTSvt1rRS_sX/view?usp=drive_link) for the PR UpdateLastLogin-2-params is also available in the spreadsheet.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou ! I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1e_Wu1Idijn2mWAx7Rp_IH2URFjrzinq9I1pdRygsLV4/edit?gid=1343851071#gid=1343851071) with the new [profile](https://drive.google.com/file/d/1ux02c_s4I3drkD6BL8HvQIDV7-o_F5WV/view?usp=sharing) result for  the PR UpdateLastLogin-2-params.

**Pull request closed without merging**
