### PR TITLE
LPD-X Cache PortletsBlacklistJSONArray to avoid repeatly scanning all…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… portlets in the company

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:50264662

**Comment by shuyangzhou** [comment]
@JerryAdrianoo please run a check for login case, thanks!

**Comment by JerryAdrianoo** [comment]
@shuyangzhou here are the results, see:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 4a538d2 | 14136 | - | 289 | 2,2,2 | 0,0,0 | 94,96,95
PR | - | 13447 | -4.874080362 | 283 | 2,1,1 | 0,0,0 | 96,95,96

For more details, please take a look at the [spreasheet](https://docs.google.com/spreadsheets/d/1mwzmPPFKbb5oMx3-KE-4NyAkl2XoOR19fK2SdBywvr8/edit?gid=981048633#gid=981048633).

**Comment by shuyangzhou** [comment]
@JerryAdrianoo this is quite unexpected, even this won't improve too much, it should not cause regression at least. Please rerun it, both the baseline and PR.

**Comment by shuyangzhou** [comment]
Also check the portal/configs/codebase-info.log file, you have too many local branches. Do a round of clean up to remove old unused ones. When run compare, always create 2 branches, one as baseline, the other is the PR branch which is strictly on top of the baseline. This way we can easily see which branch was used for run in the codebase-info.log files.

For the archives above, both runs were on branch "SPAHelper", although I can still see their last commits are different from the 2 runs, but still using the same branch is confusing and possibly lead to human errors when you missed the commit hash reset.

**Comment by shuyangzhou** [comment]
@JerryAdrianoo your baseline is using JDK21, while PR run is using JDK11.

**Comment by JerryAdrianoo** [comment]
@shuyangzhou I see, I'm sorry for the confusion, it's happening because I need to manually change the JDK version everytime I run the sql-log. So sometimes I forget to change to JDK21 again and it happens.
About the branches, I'll clean them and leave only the essential ones.

**Comment by JerryAdrianoo** [comment]
@shuyangzhou results updated. You can check in the same spreadsheet above.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155658

**Pull request closed without merging**
