### PR TITLE
LPS-126777

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

I made 3 changes to yesterday's PR:

1. In https://github.com/shuyangzhou/liferay-portal/pull/9745/commits/656b34f22c5c47452a6e03d3e6dbd3a3a628008e I used the configuration interface.
2. In https://github.com/shuyangzhou/liferay-portal/pull/9745/commits/192d353002680ba6002bbdb13d506f67828f7bf6 made the download URL configurable as you suggested.
3. In https://github.com/shuyangzhou/liferay-portal/pull/9745/commits/34a939f437d189861a8c2a12425f73291dd101b3 made sure that the model is resent to the daemon on every process restart.

Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1617

**Comment by 4lejandrito** [comment]
Thanks @shuyangzhou!

**Pull request closed without merging**
