### PR TITLE
Lpd 25633 optimization 11

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:acceptance-functional

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:67500178

**Comment by shuyangzhou** [comment]
ci:report:67507762

**Comment by vicnate5** [comment]
@shuyangzhou Unique failures here

headless integration tests
https://testray.liferay.com/#/project/34754/routines/34756/build/67509826/case-result/67530573
https://testray.liferay.com/#/project/34754/routines/34756/build/67509826/case-result/67530589
https://testray.liferay.com/#/project/34754/routines/34756/build/67509826/case-result/67530601

Also some uniques in the Objects functional tests, but those are a bit more complex and will take some time to figure out.

**Comment by vicnate5** [comment]
ci:test:object

**Comment by vicnate5** [comment]
ci:test:relevant

**Pull request closed without merging**
