### PR TITLE
LPS-X Due the system wide removal of "immediate = true", we have to d…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…elay the ServiceLatch's ServiceTracker closing until startup is done to avoid early releasing of the dependency target which could cause it to deactivate.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135683

**Pull request closed without merging**
