### PR TITLE
Lps 185647 redo 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by mbowerman** [comment]
@shuyangzhou I just tested this against [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771). It doesn't fix the issue. I will need to test further to confirm, but I believe that it's because the Session returned by the `LastSessionRecorderHelperUtil` is different from the Sesson that the SAPEntryPersistence is updated in.

I found the original pull request where we tried to implement this type of solution: https://github.com/mbowerman/liferay-portal/pull/151. You can see our discussion on there and specifically my comment [here](https://github.com/mbowerman/liferay-portal/pull/151#issuecomment-1590180024) about the problems with this approach arising from there being different sessions.

**Comment by shuyangzhou** [comment]
The explanation does not make sense. When acrossing tx manager boundary a new tx must be created, and upon new tx creation, it must sync the previous session state already.

@vicnate5 please try https://liferay.atlassian.net/browse/LPS-184771 and break down the steps into something that I can follow.

**Comment by vicnate5** [comment]
@kyle-miho will get you the steps

**Comment by kyle-miho** [comment]
@shuyangzhou I was able to reproduce following the Steps in https://liferay.atlassian.net/browse/LPP-49120,
Ill try to simplify it:
1) Add these to etc/hosts file
```
127.0.0.1   instance-dev.com
127.0.0.1   instance-uat.com
```
2) Move the liferay-sample-etc-cron_dev.zip downloaded from https://liferay.atlassian.net/browse/LPP-49120 to osgi/client-extensions
3) **Start portal** with these portal-ext.properties as well as your basic mysql configuration properties
`include-and-override=portal-liferay-online.properties`
4) Login to localhost:8080 with test/test user
5) create 2 virtual Instances based off the etc/hosts added
```
Web ID: instance-dev.com
Virtual Host: instance-dev.com
Mail Domain: instance-dev.com
Max Users: 10
Active: Enabled
Virtual Instance Initializer: Welcome
```
```
Web ID: instance-uat.com
Virtual Host: instance-uat.com
Mail Domain: instance-uat.com
Max Users: 10
Active: Enabled
Virtual Instance Initializer: Welcome
```
6) Sign in to instance-dev.com:8080/
7) . Go to CP > Security > Service Access Policy > (+) And create a Service access policy (just fill the minimum amount needed, any name and any title)
8) Repeat 6 and 7 for instance-uat.com:8080/
9) Try and delete the service access policy from the newly created instance-uat:8080 virtual instance using the (...) icon

Expected: Delete success
Actual: Everything but the newly creted service access policy is deleted and you can no longer interact with it

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/11127

**Pull request closed without merging**
