### PR TITLE
LPS-81861 Gain back 1.3% of 7.0% session count performance penalty in Add Wiki Page load testsLPS-81861 Gain back 1.3% of 7.0% session count performance penalty in Add Wiki Page load tests

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou I ran `ci:test` twice and I can't see how any of these failures are related. The affected code only gets hit for Portlet 3.0 portlets, and none of our out-of-the-box portlets opt-in to version 3.0 yet.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62841

**Pull request closed without merging**
