### PR TITLE
LPS-158920 Guard oauth UI entrance.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:oauth2

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

FYI @gaborlovasdotcom OAuth2 change, I ran the test suite for it and didn't see any regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131108

**Pull request closed without merging**
