### PR TITLE
LPS-157211 Sync at the end of MainServle.init() to get stable tomcat …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…startup timing.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Pull request closed without merging**
