### PR TITLE
LPS-83507 Optional data removal for deprecated modules

### PR DESCRIPTION
**Pull request by Preston-Crary**
This has already gone through automated testing here:
https://github.com/Preston-Crary/liferay-portal/pull/562

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Rebased on https://github.com/shuyangzhou/liferay-portal/pull/6504

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61659

**Pull request closed without merging**
