### PR TITLE
LPS-X Cache current schema version

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check this results, thanks!

**Comment by zhangyan0701** [comment]
Issues found:
1. Upgrade from 7310 failed with error: 
```
     [java] 2023-08-18 02:36:45.281 INFO  [main][UpgradeProcess:136] Failed upgrade process com.liferay.portal.upgrade.v7_3_x.UpgradeSchema in 2 ms
     [java] 2023-08-18 02:36:45.281 INFO  [main][PortalUpgradeProcess:193] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 3401 ms
     [java] 2023-08-18 02:36:45.287 ERROR [main][DBUpgrader:70] null
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'key_' in 'field list'
```
Failed test: [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/2408212240)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2805/functional-upgrade-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0

2. Upgrade from 7413 failed with error:
```
     [java] 2023-08-17 21:39:17.313 INFO  [main][UpgradeProcess:136] Failed upgrade process com.liferay.portal.upgrade.v7_1_x.UpgradePortalPreferences in 27 ms
     [java] 2023-08-17 21:39:17.313 INFO  [main][PortalUpgradeProcess:193] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 587 ms
     [java] 2023-08-17 21:39:17.322 ERROR [main][DBUpgrader:70] null
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'PortalPreferences.preferences' in 'field list'
```
Failed test: [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2408212433)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2805/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4/jenkins-console.txt.gz?authuser=0

3. Upgrade from 7210 failed with error:
```
     [java] 2023-08-18 03:00:14.814 WARN  [main][BaseDB:669] Duplicate column name 'headId': alter table Layout add headId bigint;
     [java] 
     [java] 2023-08-18 03:00:14.814 WARN  [main][BaseDB:669] Duplicate column name 'head': alter table Layout add head tinyint;
     [java] 
     [java] 2023-08-18 03:00:14.815 WARN  [main][BaseDB:669] Duplicate column name 'parentPlid': alter table Layout add parentPlid bigint;
     [java] 
     [java] 2023-08-18 03:00:14.815 WARN  [main][BaseDB:669] Duplicate column name 'classNameId': alter table Layout add classNameId bigint;
     [java] 
     [java] 2023-08-18 03:00:14.815 WARN  [main][BaseDB:669] Duplicate column name 'classPK': alter table Layout add classPK bigint;
     [java] 
     [java] 2023-08-18 03:00:14.815 WARN  [main][BaseDB:669] Duplicate column name 'system_': alter table Layout add system_ tinyint;
     [java] 
     [java] 2023-08-18 03:00:14.815 WARN  [main][BaseDB:669] Duplicate column name 'publishDate': alter table Layout add publishDate datetime(6) null;
     [java] 
     [java] 2023-08-18 03:00:14.817 WARN  [main][BaseDB:669] Duplicate entry 'com.liferay.portal.kernel.model.Layout' for key 'PRIMARY': insert into Counter (name, currentId)
     [java] 	select
     [java] 		'com.liferay.portal.kernel.model.Layout' as name,
     [java] 		max(plid) as currentId
     [java] 	from Layout;
     [java] 
     [java] 2023-08-18 03:00:14.817 ERROR [main][BaseDB:676] 	from Layout;
```
Failed test: [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7210](https://testray.liferay.com/home/-/testray/case_results/2408258576)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2806/functional-upgrade-tomcat90-mysql57-jdk8/2/18/jenkins-console.txt.gz?authuser=0

4. Integration test [com.liferay.portal.upgrade.test.PortalUpgradeProcessTest](https://testray.liferay.com/home/-/testray/case_results/2408214290) failed.
Error message: https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2805/modules-integration-mysql57-jdk8/3/17/com.liferay.portal.upgrade.test.PortalUpgradeProcessTest.txt.gz?authuser=0
Full console log: 
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2805/modules-integration-mysql57-jdk8/3/17/jenkins-console.txt.gz?authuser=0

5. Integration test [com.liferay.portal.upgrade.test.UpgradeRecorderTest](https://testray.liferay.com/home/-/testray/case_results/2408214266) failed with error:
```
     [exec] com.liferay.portal.upgrade.test.UpgradeRecorderTest > testFailureByPendingUpgrade FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[unresolved]> but was:<[success]>
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-25/test-portal-acceptance-pullrequest(master)/2805/modules-integration-mysql57-jdk8/3/18/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
@zhangyan0701 for 1,2,3 can you give me reproduce steps? Thanks!

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
Fixed 4 and 5, hope 1,2,3 are caused by the same reason.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Couple test failures here still

1. [com.liferay.portal.upgrade.test.ReleaseManagerTest](https://testray.liferay.com/home/-/testray/case_results/2408982072)
2. [com.liferay.portal.upgrade.test.PortalUpgradeProcessTest
](https://testray.liferay.com/home/-/testray/case_results/2408982241)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139489

**Pull request closed without merging**
