### PR TITLE
File system store

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou The functional tests failures are unrelated to this change. There is a related Semver issue and the SampleSQLBuilderTest is failing (I don't have the test history to confirm if this is related): https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/199842/AXIS_VARIABLE=3,label_exp=!master/consoleText

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will make more changes and test again later.

**Comment by vicnate5** [comment]
@shuyangzhou SampleSQLBuilderTest is not related, seen on another PR

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan this pull, if nothing real, please proceed with those additional DL tests, thanks!

**Comment by vicnate5** [comment]
Tests look good on this pull. Running additional tests at https://github.com/shuyangzhou/liferay-portal/pull/8404

**Comment by vicnate5** [comment]
Test results look good on https://github.com/shuyangzhou/liferay-portal/pull/8404

FileSystemStore functional test did not run due to Jenkins error.

AdvancedFileSystemStore and DBStore functional tests passed.

**Comment by shuyangzhou** [comment]
Great, I am going this send this out then, thanks @vicnate5 !

**Pull request closed without merging**
