### PR TITLE
LPS-155656 Create PortalCurrentSessionContext to cut off the JTA dete…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…cting logic from Spring.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
