### PR TITLE
LPS-X Always regsiter DependencyManagerSyncImpl to avoid callback mis…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…fire when dependency.manager.thread.pool.enabled is disabled.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
@shuyangzhou test results are good here, no need to wait for smoke suite since I was just double confirming it fixes https://issues.liferay.com/browse/LPS-159912. It fixes it locally for me.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121349

**Pull request closed without merging**
