### PR TITLE
LPS-78508 Since filter chaing depends on the type of dispatcher there should be a cache per InvokerFilter type.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 did you have time to take a look to the PR?
Kind regards.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56170

**Pull request closed without merging**
