### PR TITLE
[TS] LPS-130082

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
In case it's unclear from context, the versions come from here:
* https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/required-dependencies/required-dependencies/build.gradle#L19
* https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/required-dependencies/required-dependencies/build.gradle#L28

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9958

**Pull request closed without merging**
