### PR TITLE
[Integration Test]LPS-102245

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

The goal is to decouple portal-test-integration from portal-impl and util-java, so that we won't add new dependencies to portal-test after moving classes from portal-test-integration to it.

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81190

**Pull request closed without merging**
