### PR TITLE
Lpd 25633 optimization 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by shuyangzhou** [comment]
@vicnate5 I accidentally caused a new regression in a fix, re-fixing it in new pull https://github.com/shuyangzhou/liferay-portal/pull/11592

**Pull request closed without merging**
