### PR TITLE
LPS-61952 Upgrade

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Pretty confident I didn't cause the compile failure in plugins by changing the upgrade.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/2530

**Pull request closed without merging**
