### PR TITLE
[TS] LPS-138089

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-138089

Please let me know if you have any questions, thanks!

CC @ericyanlr, bakayattila

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@ChrisKian please add an integration test for this.

**Comment by shuyangzhou** [comment]
@ChrisKian please resend with a test.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/shuyangzhou/liferay-portal/pull/10320

**Pull request closed without merging**
