### PR TITLE
LPS-111049 Update dependencies

### PR DESCRIPTION
**Pull request by inacionery**
Hi @shuyangzhou, 

Could you please review this change? especially this commit https://github.com/shuyangzhou/liferay-portal/pull/8977/commits/a16001eb92de65145a7dca23a2831bb6339ce1b3 in which I am using reflection?

Thanks!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Hey @shuyangzhou,

Despite being unique, this failure, TaxonomyVocabularyResourceTest.testGraphQLPostSiteTaxonomyVocabulary is a CI flaky, in the previous relevant it passed and I tested locally again and passed.

**Comment by inacionery** [comment]
Forwarded to https://github.com/tinatian/liferay-portal/pull/1749

**Pull request closed without merging**
