### PR TITLE
[Bug Fix]LPS-134082

### PR DESCRIPTION
**Pull request by vicnate5**
@tinatian

### CODE REVIEW

**Comment by vicnate5** [comment]
@rodrigocunhaa We are making a backend change here for https://issues.liferay.com/browse/LPS-134082, but many of the calendar tests started failing due to a UI issue. The Selenium interactions are breaking/moving the iframe for editing calendar events. I cannot reproduce the issue manually, only locally with the poshi tests.

See all test failures at https://github.com/shuyangzhou/liferay-portal/pull/10252#issuecomment-910823800. I found a workaround for some of them (see https://github.com/vicnate5/liferay-portal/commit/8d140a12a8ff3089ed037a32a474676c93482d0c).

Bundle with the changes can be downloaded at https://files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/60/liferay-portal-bundle-tomcat.tar.gz

Could you take a look at this? Any idea why it is happening?

**Comment by vicnate5** [comment]
ci:test:calendar

**Comment by rodrigocunhaa** [comment]
Hey @vicnate5 ,

I think it was just a bad timing. These remaining failures are not related to this PR. I checked on our daily routine, and it started to failed 2 days ago:
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1557704263

I'll ask my team to quarantine those and dig in later.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10256

**Pull request closed without merging**
