### PR TITLE
LPS-X Set mvcPath attribute only when it is not null.

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @preston-crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
What happened to this pull? Have you guys checked with the author?
@preston-crary @mtambara

**Comment by mtambara** [comment]
I sent an email to the author on Thursday, haven't gotten a response yet. I'll ping him again tomorrow and cc you.

**Comment by shuyangzhou** [comment]
Ok, thanks @mtambara !

**Comment by mtambara** [comment]
Tested with some steps in the original tickets and did my best to break the portal. Seems like this change is safe.

**Comment by shuyangzhou** [comment]
Thanks @mtambara !

**Pull request closed without merging**
