### PR TITLE
LPS-118408

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou this came from https://github.com/ealonso/liferay-portal/pull/3052

It looks wrong to me because I thought we already have a way to show different images.

**Comment by shuyangzhou** [comment]
@ealonso I don't understand why you need to do this. Without your change, the logo and company name is already profile aware. I tried locally, it is working properly.
What's the problem you are trying to fix? Can you provide me reproduce steps?

**Comment by ealonso** [comment]
Hey @shuyangzhou,

At this moment we have the ability to change the Company Logo in the UI or using the portal.properties:

In the UI:
Instance_Configuration_-_Control_Panel_-_Liferay
In the portal.properties:
```image.default.company.logo=com/liferay/portal/dependencies/company_logo.png```

So, if we change the company logo then the result is the following:
Instance_Configuration_-_Control_Panel_-_Liferay

All the places using **/company_logo?img_id=** are going to change to the new icon.

We have the following requisite of Applications Menu: 

```
The bottom left logo and title are not the company logo and title. The expected result here is:

For DXP: DXP Logo + Liferay DXP
For DXP: Liferay Waffle Logo + Liferay
```

more details [here](https://issues.liferay.com/browse/LPS-119703?focusedCommentId=2236751&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2236751)

Hope this help, please let me know if you have any other question.

**Comment by shuyangzhou** [comment]
@ealonso see https://github.com/liferay/liferay-portal/tree/master/modules/dxp/apps/portal/portal-properties-swapper, this is handling the DXP and CE logo/name swapping. How is your requirement different?
In this pull, there 2 checked in png, for CE and DXP company logo, which they already exist in portal, why duplicating them?
Can you provide steps to show, how the DXP profile is showing CE company logo?

**Comment by ealonso** [comment]
@shuyangzhou,
For this case, the idea is to use the liferay logo or the liferay dxp logo always, we don't want to depend on company logo and name properties, since this properties can be changed by clients, and we don't want it.

It is a decision of UX Team and Angelo, they wants to have the liferay (DXP vs CE) logo and name always visible for clients in this place.

**Comment by ealonso** [comment]
Steps to reproduce it, those are valid for DXP and CE

1. Go Instance Settings -> Instance Configuration
2. Change the logo

Expected result

The bottom left logo should be DXP or CE Logo

Actual result

The bottom left logo is the logo that you selected

**Comment by shuyangzhou** [comment]
@ealonso see https://github.com/ealonso/liferay-portal/pull/3054
If I understand your requirement right, all we need is to avoid appending the "img_id" based on the company, which would automatically fallback to default.
Let me know if this is not what you need, otherwise you can just forward it to @brianchandotcom to proceed.

**Comment by ealonso** [comment]
@shuyangzhou, 

Taking a look at the code, and if I'm not wrong, the default company logo is defined by 

`PropsKeys.IMAGE_DEFAULT_COMPANY_LOGO` 

The value for this property can be modified by clients in their portal-ext.properties, and we don't want to make it possible. We want to use this logo as a branding logo, so everyone can see that the product is a Liferay.

**Comment by ealonso** [comment]
The same for the company name, maybe the problem in this case is the name of the vars, it should be liferay_logo instead of company_logo

**Comment by shuyangzhou** [comment]
@ealonso I think I am lost with what's the goal here. If you are saying this actually has nothing to do with company logo, but a new logo, sure the exist solution won't meet your need. If that's the case, you can rename the code to make it clear, then @brianchandotcom won't be mislead to think this is the same as the existing company info swapper.

**Pull request closed without merging**
