### PR TITLE
Upgrade executor

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?
Testray report at https://test-1-1.liferay.com/job/generate-testray-csv/5486/

**Comment by shuyangzhou** [comment]
@Kvale1733 any update on this?

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

Sorry, thought I remembered finishing this one.

**Pull request closed without merging**
