### PR TITLE
[Bug Fix]LPS-129546

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:environment

**Comment by tinatian** [comment]
@vicnate5 Is there any other test I need to trigger to cover this change?

Thanks.
Tina.

**Comment by tinatian** [comment]
FYI @jorgediaz-lr

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Can you review the results?

**Comment by shuyangzhou** [comment]
@vicnate5 did it break for db2 runs?

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the results of DB2 runs? Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This looks good.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
