### PR TITLE
Startup optimization 109 lazy service tracker collection

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related. This should be good now.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/brianchandotcom/liferay-portal/pull/127441

**Pull request closed without merging**
