### PR TITLE
LPS-56385 fileinstall's default log level is ERROR, make it separately configurable

### PR DESCRIPTION
**Pull request by rotty3000**
@brianchandotcom fyi

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Hmm, so there is no way to make the bundle resolvable? But changing the log level, so we won't see it?

Won't it also swallow other FileInstall logs all together?

That just does not sound like a real solution.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@shuyangzhou please note this update contains the changes we discussed.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
I don't think there is any need to retest. Can you please merge this? Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/27461

**Pull request closed without merging**
