### PR TITLE
LPS-113779 | master

### PR DESCRIPTION
**Pull request by vicnate5**
This is an FP5 Security issue that QA was able to reproduce. Forwarding this fix from @nhpatt https://github.com/liferay-headless/liferay-portal/pull/84

### CODE REVIEW

**Comment by vicnate5** [comment]
@koor4356 Please watch and review test results. The fix will also need to be manually tested.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/89111

**Comment by brianwulbern** [comment]
@vicnate5, @koor4356, @shuyangzhou it looks like we didn't forward from this pull, and sent directly to BChan on https://github.com/brianchandotcom/liferay-portal/pull/89111.  This pull caused relevant test failures, so we reverted it in https://github.com/brianchandotcom/liferay-portal/pull/89180.  I believe running ci forward here would have caught those errors.

Maybe instead of running ci forward, and potentially skip the reviewer's 'OK', we can trigger the suites that it runs, so when the reviewer is ready to forward, we can run ci forward and it will immediately forward to BChan.

**Comment by vicnate5** [comment]
@brianwulbern Yea we should have use the normal process, but the main issue here was that I checked the test results on https://github.com/liferay-headless/liferay-portal/pull/84 and gave Shuyang the OK, I missed the functional failures there. I think I had trouble getting the testray results at the time and the integration tests were all OK so I thought this was safe. This was my bad.

**Comment by brianwulbern** [comment]
@vicnate5 thanks for explaining the situation and taking ownership.  [Jocko](https://www.youtube.com/watch?v=ljqra3BcqWM) would be proud.  I guess we can use this as a precedent to say blue skies with integration tests doesn't *necessarily* forecast poshi's weather.

**Pull request closed without merging**
