### PR TITLE
Simple tag

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn please run a diff, thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyang,

As the server room of China office need to renovation this weekend, all of our servers need to be shut down early, so I have got part test results here, others will be update when I got them.

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL FIle
-- | -- | -- | -- | --
BaseLine | 225c659e | 24022 | 386 | 446
PR-7850 | - | 24831 | 368 | 431

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | 225c659e | 44825 | 280 | 83.2
PR-7850 | - | 44954 | 291 | 88.6

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 225c659e | 56368 | 679 | 213
PR-7850 | - | 56905 | 568 | 179

Sorry for the inconvenient.

Regards
Lily

**Comment by vicnate5** [comment]
@shuyangzhou functional failures not related

**Comment by slnn** [comment]
Here are rest test results:
MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 225c659e | 15963 | 41.5 | 92.5
PR-7850 | - | 16013 | 32.1 | 86.1

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 225c659e | 14226 | 429 | 603
PR-7850 | - | 14258 | 465 | 633

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 225c659e | 26702 | 462 | 203
PR-7850 | - | 26717 | 421 | 185


Regards
Lily

**Comment by shuyangzhou** [comment]
ci:test

**Pull request closed without merging**
