### PR TITLE
LPS-87108

### PR DESCRIPTION
**Pull request by topolik**
Hi Shuyang,

can you please run performance tests? I guess this has important performance impact on every request.

I didn't add any caching so far.

Thank you.

https://issues.liferay.com/browse/LPS-87108

/cc @yxingwu @samuelkong

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@slnn can you run this against login and one other test for regressions?  Thanks!

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Drop of Session Count (%)
-- | -- | -- | -- | -- | --
BaseLine | bc30ccd | 47257 | 316 | 93 | -
https://github.com/shuyangzhou/liferay-portal/pull/7210 | - | 45800 | 279 | 84.2 | -3.083141122

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Drop of Session Count (%)
-- | -- | -- | -- | -- | --
BaseLine | bc30ccd | 16287 | 420 | 603 | -
https://github.com/shuyangzhou/liferay-portal/pull/7210 | - | 15939 | 444 | 630 | -2.136673421


Regards
Lily

**Comment by shuyangzhou** [comment]
@topolik isn't this too overkilled? In very limited places we actually use the path info or request uri to do filesystem lookup. Applying this request wrapper at invoker filter level is imposing it to everyone and most time they won't even read the path info or at least not using it to retrieve a file. Why can not we just do the check at the location where we are really locating a file?

**Comment by samuelkong** [comment]
Hi @shuyangzhou 
Checking each time we use it is one way to solve this problem. But if we go down that path, than any developer that uses `getPathInfo()` needs to be aware of the potential problem and add a check. I don't really trust all developers to proactively do this.

**Comment by topolik** [comment]
Hi @shuyangzhou, is it too expensive? It's usual to have 2 layers of security protection in case one would fail or is missing. 

We can also have it different - deny requests where the normalized requestURI / pathInfo doesn't match the original one, maybe that would be better?

**Comment by shuyangzhou** [comment]
@topolik It is not too expensive, but unnecessary in many cases. Since we wrap it at InvokerFilter level, all requests will be wrapped, and for most of the requests, the getPathInfo() may never be called. But we are paying the wrapper call stacks and attributes fetching checking price.

If the getPathInfo() is the main concern, we should be able to add some sort of SF protection for it. It is a lot better to restrain developers' new changes, comparing to add blanket fallback catch to correct things for them.

Do we have a list of which locations we actually have this path traversal vulnerability?

**Comment by samuelkong** [comment]
> Do we have a list of which locations we actually have this path traversal vulnerability?

I'm running [false-positive](https://issues.liferay.com/browse/LPS-87108?focusedCommentId=1645762&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1645762) for DynamicResourceServlet with the security vendor and I'm waiting for their response. 

The other instance the security vendor found is in [PollerRequestHandlerImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/poller/PollerRequestHandlerImpl.java#L94)

**Comment by shuyangzhou** [comment]
@topolik @samuelkong I am closing this for now. Please resend to just fix the problem in PollerRequestHandlerImpl as it seems to be the only one.  If we end up with multiple appearance of this problem, we can revisit it for a general solution. Thanks!

**Pull request closed without merging**
