### PR TITLE
Sb index optimize regression checking

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@GinsonRen please run FULL runtime performance regression test.
CC @dantewang

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me watch over the CI results, thanks!

**Comment by GinsonRen** [comment]
@shuyangzhou There are the reuslts for mysql, psql is runnig and I will update psql results tomorrow.
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 47790 | 272 | -
PR-11286 | - | 47257 | 259 | -1.12%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 61699 | 460 | -
PR-11286 | - | 61647 | 471 | -0.08%

MB: 
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 10543 | 15.9 | -
PR-11286 | - | 10993 | 16 | 4.27%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 17032 | 50.6 | -
PR-11286 | - | 17038 | 51.7 | 0.04%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 32611 | 329 | -
PR-11286 | - | 31876 | 376 | -2.25%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 28752 | 414 | -
PR-11286 | - | 28918 | 406 | 0.58%

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

Appended new commit to fix UpgradeResourcePermissionTest

**Comment by zhangyan0701** [comment]
The UpgradeResourcePermissionTest is fixed.

The "Upgraded database is missing the following elements from a fresh database" error is still reproducible.
Example test: 
[LocalFile.PortalDatabaseValidationUpgrade#CompareUpgradedAndFreshDatabaseSchemas7413](https://testray.liferay.com/home/-/testray/case_results/2451555247)

Full console:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-25/test-portal-acceptance-pullrequest(master)/4122/functional-upgrade-tomcat90-mysql57-jdk8/2/4/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
@GinsonRen any update on the postgresql results?

**Comment by shuyangzhou** [comment]
@GinsonRen the psql WC case looks a bit off, please recheck. If the issue stays, @dantewang please take a look.

**Comment by GinsonRen** [comment]
@shuyangzhou I didn't rebuildDB for the pr, the results is not correct. I need re-run the test with rebuild. I am sorry for that.

**Comment by shuyangzhou** [comment]
@GinsonRen all the results are invalid? or just that WC case?

**Comment by GinsonRen** [comment]
@shuyangzhou @dantewang There are the mysql results with rebuildDB. And there is a big diff on mb, I upload the mb archive [here](https://drive.google.com/drive/u/1/folders/1aQfVUgVEDaZ5xgX9id9YA2Cdmnpx8NXv).
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 47790 | 272 | -
PR-11286 | - | 47579 | 271 | -0.44%

WC:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 61699 | 460 | -
PR-11286 | - | 62142 | 486 | 0.72%

MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 10543 | 15.9 | -
PR-11286 | - | 9413 | 3290 | -10.72%

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 17032 | 50.6 | -
PR-11286 | - | 17032 | 55.7 | 0.00%


DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 32611 | 329 | -
PR-11286 | - | 32082 | 316 | -1.62%

AP:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b1ce073 | 28752 | 414 | -
PR-11286 | - | 28245 | 410 | -1.76%

**Comment by shuyangzhou** [comment]
@dantewang we need to run this with the sample sql builder skewed data fix.

**Comment by dantewang** [comment]
@GinsonRen Added multiple group support:

SampleSQLBuilder: https://github.com/dantewang/liferay-portal/pull/2331
Benchmark: https://github.com/dantewang/liferay-benchmark-ee/pull/662

On Benchmark side, I only applied to MB, Blog, DL and Wiki, as other test cases are not database intensive.

After you finish the current PSQL tests,
- Use the SampleSQLBuilder + Benchmark change on baseline, build new database, run MB, Blog and DL;
- Use this PR + SampleSQLBuilder + Benchmark change, build new database, run MB, Blog, and DL.

**Comment by GinsonRen** [comment]
@shuyangzhou For multiple groups, DL still not work yet, MB and Blog results are here:
MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | LPS-201152 | 10995 | 15.8 | -
  | SB-Index-Optimize-regression-checking + LPS-201152 | 10993 | 15.7 | -0.02%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | LPS-201152 | 16510 | 117 | -
  | SB-Index-Optimize-regression-checking + LPS-201152 | 16782 | 83.2 | 1.65%

I finished re-run diff for this pr with rebuilding DB for mysql and psql, you can find all results here: https://docs.google.com/spreadsheets/d/15XA8601IS8z8B1Sd3NUrND_u8fr0fXm8Ft7SPF-it3A/edit#gid=0
/cc @dantewang

**Comment by shuyangzhou** [comment]
@GinsonRen the "mysql&psql" is without the multi-groups change, right?

For the multi-groups + this pull, we also need to run on psql. And add columns to show the cpu usage on db server. Upload the test archives.

**Comment by dantewang** [comment]
@shuyangzhou The DL test issue of multi-group has been resolved this evening, will finish the run tomorrow.

The PSQL diff is also in progress, should be able to finish tomorrow.

**Comment by GinsonRen** [comment]
@shuyangzhou @dantewang All results will be updated here: https://docs.google.com/spreadsheets/d/15XA8601IS8z8B1Sd3NUrND_u8fr0fXm8Ft7SPF-it3A/edit#gid=197584083

**Pull request closed without merging**
