### PR TITLE
LPS-80519 Portlet 3.0: Implement javax.portlet.supported-locale in PortletTracker

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains 1 commit that simply adds one method to PortletTracker.java that looks for "javax.portlet.supported-locale" which isn't specified by any of our out-of-the-box Declarative Services portlets registered via `@Component`. I can't see how any of these failures are related, especially since I've seen many of them in different pull requests today.

Please review when you get an opportunity. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61168

**Pull request closed without merging**
