### PR TITLE
LPS-170958 Remove leftover references

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
Need to rerun for the the release/license test since it randomly failed

**Comment by vicnate5** [comment]
@shuyangzhou This is good. No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127567

**Pull request closed without merging**
