### PR TITLE
[Hibernate Upgrade]LPS-133997

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 please check for unique failures

**Comment by zhangyan0701** [comment]
The failures are unrelated.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
