### PR TITLE
Lps 122233

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Hey @zhangyan0701, can you help me test this ticket with S3Store, also to do some basic testing for S3Store usage to make sure the cache behavior is working when not running reindex. Thanks!

CC @vicnate5

**Comment by zhangyan0701** [comment]
@shuyangzhou  Yes, will test this.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related. Summer should have the S3 results before Monday morning.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by zhangyan0701** [comment]
When test ticket LPS-122233 with the fix, I got below error in console during the re-index:
`2020-11-09 13:52:03.891 ERROR [default-7][FileImpl:482] org.apache.tika.io.TaggedIOException: Attempted read on closed stream.
org.apache.tika.io.TaggedIOException: Attempted read on closed stream.
	at org.apache.tika.io.TaggedInputStream.handleIOException(TaggedInputStream.java:133)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:82)
	at org.apache.tika.io.TikaInputStream.peek(TikaInputStream.java:548)
	at com.liferay.portal.util.FileImpl._isEmptyTikaInputStream(FileImpl.java:1199)
	at com.liferay.portal.util.FileImpl.extractText(FileImpl.java:456)
	at com.liferay.portal.kernel.util.FileUtil.extractText(FileUtil.java:165)
	at com.liferay.portal.kernel.search.DocumentImpl.addFile(DocumentImpl.java:158)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:61)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:60)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:58)
	at com.liferay.portal.search.internal.index.contributor.helper.ModelIndexerWriterDocumentHelperImpl.getDocument(ModelIndexerWriterDocumentHelperImpl.java:41)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelIndexerWriterContributor.lambda$customize$0(DLFileEntryModelIndexerWriterContributor.java:56)
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.lambda$setPerformActionMethod$0(DynamicQueryBatchIndexingActionableAdapter.java:75)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performAction(DefaultActionableDynamicQuery.java:394)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:306)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:268)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:326)
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.doPerformActions(IndexableActionableDynamicQuery.java:107)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:86)
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.performActions(IndexableActionableDynamicQuery.java:65)
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.performActions(DynamicQueryBatchIndexingActionableAdapter.java:50)
	at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:199)
	at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:267)
	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:189)
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:142)
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:133)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Attempted read on closed stream.
	at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:109)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at java.security.DigestInputStream.read(DigestInputStream.java:161)
	at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.liferay.document.library.internal.security.io.SafePNGInputStream._detectPNGSignature(SafePNGInputStream.java:102)
	at com.liferay.document.library.internal.security.io.SafePNGInputStream.read(SafePNGInputStream.java:38)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:78)
	... 32 more
2020-11-09 13:52:05.122 ERROR [default-7][FileImpl:482] org.apache.tika.io.TaggedIOException: Attempted read on closed stream.
org.apache.tika.io.TaggedIOException: Attempted read on closed stream.
	at org.apache.tika.io.TaggedInputStream.handleIOException(TaggedInputStream.java:133)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:82)
	at org.apache.tika.io.TikaInputStream.peek(TikaInputStream.java:548)
	at com.liferay.portal.util.FileImpl._isEmptyTikaInputStream(FileImpl.java:1199)
	at com.liferay.portal.util.FileImpl.extractText(FileImpl.java:456)
	at com.liferay.portal.kernel.util.FileUtil.extractText(FileUtil.java:165)
	at com.liferay.portal.kernel.search.DocumentImpl.addFile(DocumentImpl.java:158)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:61)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:60)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:58)
	at com.liferay.portal.search.internal.index.contributor.helper.ModelIndexerWriterDocumentHelperImpl.getDocument(ModelIndexerWriterDocumentHelperImpl.java:41)
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelIndexerWriterContributor.lambda$customize$0(DLFileEntryModelIndexerWriterContributor.java:56)
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.lambda$setPerformActionMethod$0(DynamicQueryBatchIndexingActionableAdapter.java:75)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performAction(DefaultActionableDynamicQuery.java:394)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:306)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:268)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:326)
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.doPerformActions(IndexableActionableDynamicQuery.java:107)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:86)
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.performActions(IndexableActionableDynamicQuery.java:65)
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.performActions(DynamicQueryBatchIndexingActionableAdapter.java:50)
	at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:199)
	at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:267)
	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:189)
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:142)
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:133)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Attempted read on closed stream.
	at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:109)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at java.security.DigestInputStream.read(DigestInputStream.java:161)
	at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.liferay.document.library.internal.security.io.SafePNGInputStream._detectPNGSignature(SafePNGInputStream.java:102)
	at com.liferay.document.library.internal.security.io.SafePNGInputStream.read(SafePNGInputStream.java:38)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.tika.io.ProxyInputStream.read(ProxyInputStream.java:78)
	... 32 more
`
These errors are not reproducible on master.

**Comment by zhangyan0701** [comment]
And there is something I am not sure, each time after restart portal, there is a temp file created in /tomcat/temp/liferay/s3 when I visit home page:
temp file in s3

Looks like it's a copy of the welcome image of home page. This is also occurs on master head. Is it expected?

/cc @vicnate5

**Comment by shuyangzhou** [comment]
The homepage image cache file is expected. Only the reindex process should not generate new cache files, if the indexing file previously had cache file generated already, it will still be used. only not to generate new ones.

@zhangyan0701 What do you mean by "These errors are not reproducible on master."? This is only supposed to be tested on master. Did you backport it to test on older branches?

**Comment by shuyangzhou** [comment]
@zhangyan0701 oh, sorry, I think you meant not reproducible on clean master without this pull, right?
@vicnate5 I will try to do one more try on blind fixing, if still not working, I will need some help to setup it properly.

**Comment by shuyangzhou** [comment]
@zhangyan0701 can you paste the full log in gist? The above one is not complete, I need to see the full stack.

**Comment by vicnate5** [comment]
Manual Testing passed. S3 cache in `tomcat/temp/s3` is the same before and after reindex.

**Comment by vicnate5** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
> @zhangyan0701 oh, sorry, I think you meant not reproducible on clean master without this pull, right?

Yes, sorry I didn't make it clear.

**Pull request closed without merging**
