### PR TITLE
LPS-149082 Remove commons-beanutils.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help us check the results, thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
I found a problem with several tests because some modules didn't start correctly due to this `Unresolved requirement: Import-Package: com.liferay.portal.kernel.test; version="2.4.0"` , running tests again.

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
No regressions in the test results.

**Comment by guilhermedcamacho** [comment]
@vicnate5 I had to fix two things, but now it's ready for your analyse. Thanks!

**Comment by guilhermedcamacho** [comment]
@shuyangzhou, this PR is ready for your review again. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117316

**Pull request closed without merging**
