### PR TITLE
Startup optimization 144 remove leftover lang bundle references

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this?

**Comment by kyle-miho** [comment]
@shuyangzhou 
```
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS   = ================================================== ========== ========== ========== ========== ========== * com.liferay.saml.runtime.configuration             MAJOR      4.0.2      4.0.2      5.0.0      VERSION INCREASE REQUIRED  >   class      com.liferay.saml.runtime.configuration.MetaTypeVirtualBundleRegistrator   -   method     requireLanguageKeys(java.lang.String)    -   access     protected    -   return     com.liferay.saml.runtime.configuration.MetaTypeVirtualBundleRegistrator 
Stacktrace
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.saml.runtime.configuration             MAJOR      4.0.2      4.0.2      5.0.0      VERSION INCREASE REQUIRED
	>   class      com.liferay.saml.runtime.configuration.MetaTypeVirtualBundleRegistrator
		-   method     requireLanguageKeys(java.lang.String)
			-   access     protected
			-   return     com.liferay.saml.runtime.configuration.MetaTypeVirtualBundleRegistrator
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128711

**Pull request closed without merging**
