### PR TITLE
Startup optimization 37 optional greedy references

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sharing

**Comment by shuyangzhou** [comment]
ci:reevaluate:1377401_3868

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
No regressions in the sharing tests, but there is a [random startup error seen in relevant](https://testray.liferay.com/reports/production/logs/2022-08/test-1-37/test-portal-acceptance-pullrequest(master)/3868/functional-tomcat90-mysql57-jdk8/9/24/jenkins-console.txt.gz?authuser=0). I am going to re-run relevant to see if it occurs again.

**Comment by vicnate5** [comment]
@shuyangzhou No more cases of the startup error on the re-run, this should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121177

**Pull request closed without merging**
