### PR TITLE
[MessageBus]LPS-102995

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me verify if there is any real failure?

Thanks
Tina.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
Some possible issues here with portal shutdown, need to take a closer look.

**Comment by vicnate5** [comment]
@tinatian There is a consistent shutdown error on this PR. This matches https://issues.liferay.com/browse/LPS-102853, but is more consistent that before. Maybe this is just further exposing an existing issue?

I can reproduce locally by just starting the[ tomcat bundle](https://files.liferay.com/private/bundles/test-1-21/jobs/test-portal-acceptance-pullrequest(master)/builds/5002/liferay-portal-bundle-tomcat.tar.gz), and then shutdown with `Ctrl+C`

```
04-Nov-2019 19:36:19.490 WARNING [Thread-26] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Framework Event Dispatcher: Equinox Container: c4ca5d83-fac3-41c6-990d-c927148d548e] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
 org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)
04-Nov-2019 19:36:19.490 WARNING [Thread-26] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Refresh Thread: Equinox Container: c4ca5d83-fac3-41c6-990d-c927148d548e] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
 org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:336)
04-Nov-2019 19:36:19.491 WARNING [Thread-26] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Framework stop] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1590)
 org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:270)
 org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:192)
 org.eclipse.osgi.container.Module.doStop(Module.java:636)
 org.eclipse.osgi.container.Module.stop(Module.java:498)
 org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
 org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:210)
 java.lang.Thread.run(Thread.java:745)
```

**Comment by tinatian** [comment]
Thanks @vicnate5! This error might not be related to this pull, I am seeing it with other changes. Let me take a deep look at it.

Tina.

**Comment by shuyangzhou** [comment]
@tinatian please rebase

**Comment by tinatian** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/8499

**Pull request closed without merging**
