### PR TITLE
Lps 76912

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mtambara this is going to conflict with https://github.com/brianchandotcom/liferay-portal/pull/54211
wait until brian merges my pull, then rebase and resend. Or just do it on top of mine and resend.

**Pull request closed without merging**
