### PR TITLE
Lps 105024 story

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @shuyangzhou ,
Is' the same pull from https://github.com/shuyangzhou/liferay-portal/pull/8682, just to clean up the message. Do you have updates on it?

cc @csierra

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@arthurchan35 no, this is still not showing the usage. You have added https://github.com/shuyangzhou/liferay-portal/pull/8704/commits/cf9ffe4b1ce519f7dd487e29c7adba4245b3dac0 to do instanceof checking for VariableLengthSaltGenerator, but nowhere in the code is ever using https://github.com/shuyangzhou/liferay-portal/pull/8704/files#diff-880c267b1a4c00f9304502b83e102ccaR25. So your new usage demo is a deadcode.

I need to see how thing are wired up and being used to understand the design in order to make necessary changes. Please update the code to make sure all usages are included with no deadcode.

**Comment by csierra** [comment]
hey @shuyangzhou,

Those static instances are [there](https://github.com/shuyangzhou/liferay-portal/pull/8704/files#diff-880c267b1a4c00f9304502b83e102ccaR25) to allow `HashGeneratorFactory` and `HashGenerator` future implementors to reuse the default implementations. 

Carlos.

**Comment by shuyangzhou** [comment]
@csierra the point is, if it is only for far future, it should not be included in this pull. It can always be added later. And it is safer that way, in case something is going to change. If it is for near future, I will need to see a real usage in order to do proper review.

**Comment by csierra** [comment]
@shuyangzhou I believe it is coming in following pulls. I guess we undesrtood that you were asking for usages on the call site instead of usages by the implementors.

**Pull request closed without merging**
