### PR TITLE
LPS-199187 Extract and cache BatchEngineUnitMetaInfo

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
No regressions found.

Test HeadlessBuilderResourceTest.testGetInDifferentCompany passed on MySQL:
`[exec] com.liferay.headless.builder.resource.test.HeadlessBuilderResourceTest > testGetInDifferentCompany PASSED`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142486

**Pull request closed without merging**
