### PR TITLE
LPS-118655

### PR DESCRIPTION
**Pull request by attilabakay**
Hi @shuyangzhou,

Could you review this for me?

https://issues.liferay.com/browse/LPS-118655

the main issue is the canonical URL-s are generated the wrong way for display page contents if the layout friendly URL is equal to the group-friendly URL or the group-friendly URL includes the layout-friendly URL.

Best,
Attila

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan the result, thanks!

**Comment by kyle-miho** [comment]
No unique failures, The Display Page Integration test is also already reported upstream, so its not caused by this pull. This pull should be good to go https://issues.liferay.com/browse/LPS-118800

**Comment by shuyangzhou** [comment]
@bakayattila I am ok with your change, but please resend with an integration test to expose the original problem and assert your expected behaviors. No need to change this current commit, just append a new commit with the test. I think the test can go into PortalImplCanonicalURLTest, or other places you think is reasonable. Thanks!

**Pull request closed without merging**
