### PR TITLE
LPS-81983 Portlet 3.0: Deprecate usage of portal-kernel StringBundler in favor of petra StringBundler for OutputData and OutputTag

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou The "Failures unique to this pull" all state "No Group exists with the primary key 0" in a test related to staging. I can't see how that is related to a change from portal-kernel StringBundler to petra StringBundler. 

Please review when you get an opportunity. This is the new #1 since it is a blocker.

Thank you, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59790

**Pull request closed without merging**
