### PR TITLE
LPS-181729 Refactor BatchEngineTaskItemDelegateRegistry to wait for ResourceImpls to become active

### PR DESCRIPTION
**Pull request by matijapetanjek**
HI @shuyangzhou  6a3b9e8d1b529ebe45b4f9ff61b90df90d123ef7 and c9d8cbb55557e63f45b681a878bbd05bdf6e6f39 are the commits that resolve the race condition in the batch engine, other commits contain updates so that component factory is able to uniquely reference a vulcan batch engine task item delegate.

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek please add acceptance test steps to the tickets for QA purpose.
And what's the purpose of adding VulcanBatchEngineTaskItemDelegate as the service type here https://github.com/shuyangzhou/liferay-portal/pull/11118/commits/f27b830726a19143e9b60c7dc4004243e14cfbf7 ? We are globally cleaning up component with more than one service type. This is going against the cleanup.
Also the only 2 locations I can see that collect "batch.engine.task.item.delegate" are ItemClassRegistryImpl/BatchEngineTaskItemDelegateRegistryImpl, none of them require the service type needs to be BatchEngineTaskItemDelegate. They only need the service object is instanceof BatchEngineTaskItemDelegate.

Like I ask in the previous message, this is considered as a preparation step (if it is needed at all). Please separate it from main change and explain why it is needed. Keeping them together will slow down the review process.

**Comment by matijapetanjek** [comment]
@shuyangzhou adding VulcanBatchEngineTaskItemDelegate as the service type here https://github.com/shuyangzhou/liferay-portal/commit/f27b830726a19143e9b60c7dc4004243e14cfbf7 is needed so that component factory can activate [BatchEngineImportTaskComponent](https://github.com/shuyangzhou/liferay-portal/pull/11118/commits/27761143ae446228709a03880680ce7b3a6d4698#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR130). I cannot put "Object" or wildcard "?" generic type there, it needs to be a specific service.

> ItemClassRegistryImpl/BatchEngineTaskItemDelegateRegistryImpl, none of them require the service type needs to be BatchEngineTaskItemDelegate. They only need the service object is instanceof BatchEngineTaskItemDelegate.

Yes, but that Registry pattern is exactly what is causing the race condition since registry gets immediately activated while the actual ItemDelegate is not yet picked up by serviceTracker. That's why we're trying to fetch the specific ItemDelegate with this [filter expression ](https://github.com/shuyangzhou/liferay-portal/pull/11118/commits/5f618259acdbfcb2d360a1feea0b932a45db529e#diff-760781d7df7391517dd77dae0b22bf2b6ddd3728eb3a47e7489d642d6f1bbec1R182), and let OSGi handle waiting for the [specific ItemDelegate.](https://github.com/shuyangzhou/liferay-portal/pull/11118/commits/5f618259acdbfcb2d360a1feea0b932a45db529e#diff-760781d7df7391517dd77dae0b22bf2b6ddd3728eb3a47e7489d642d6f1bbec1R179)

We have tried to do the cleanup to a single ItemDelegate service interface, but that is impossible if we want to remain compatible with previous Liferay versions. This is actually the main reason why all of our attempts look so "hacky" and complicated.

With this latest push I have added a [test](https://github.com/shuyangzhou/liferay-portal/pull/11118/commits/c91031892d3660a5761cad3be75664dd69a6b946) that simulates a race condition and cleaned up some unnecessary changes, please review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137445

**Pull request closed without merging**
