### PR TITLE
LPS-85870 Only forward to resources if the path does not match a servlet-mapping url-pattern from web.xml

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Hi @ngriffin7a,

when I deployed the portlet and clicked "Forward to HTML document" it says "LPS-85870 is fixed".  I'm not sure if the ticket is missing some detail or if some other fix has gone in and resolved the problem.

Please let me know, thanks!

**Comment by ngriffin7a** [comment]
@Preston-Crary The LPS-85870 portlet reproducer will say "LPS-85870 is fixed" before and after this pull request. The commits in this pull request fix regressions that were introduced by the original fix for LPS-85870.

**Comment by Preston-Crary** [comment]
I see, what are the regressions?  Can you comment here or update the ticket so I can know what this change is fixing?

Thanks

**Comment by ngriffin7a** [comment]
@Preston-Crary: I updated the ticket with a comment listing the regressions:
https://issues.liferay.com/browse/LPS-85870?focusedCommentId=1614398&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1614398

**Comment by shuyangzhou** [comment]
@ngriffin7a how is the tck CI integration going on?
Running the tck locally is just too painful, if it is getting closed, let's wait until it is up running on CI, then fix this.

**Comment by shuyangzhou** [comment]
@ngriffin7a if it still needs more time, then please upload the tck war + source on the ticket, so that @Preston-Crary can just drop in the war to test it locally.

**Comment by ngriffin7a** [comment]
@shuyangzhou The TCK integration work is ongoing but won't be ready until December at the earliest. Vernon and Kyle are working on the intermittent Selenium failures in CI which are very difficult to track down. I will upload the WARs and a LAR to the ticket for @Preston-Crary .

**Comment by ngriffin7a** [comment]
@Preston-Crary: The [LPS-85870](https://issues.liferay.com/browse/LPS-85870) ticket has been updated with the LAR, TCK WARs, and instructions. Thanks.

**Comment by Preston-Crary** [comment]
Please see https://github.com/ngriffin7a/liferay-portal/pull/32

**Pull request closed without merging**
