### PR TITLE
[Bug Fix] LPS-136753 | Regen 9-16

### PR DESCRIPTION
**Pull request by dantewang**
Regenerated to resolve conflicts. @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions in the test results

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/107379

**Pull request closed without merging**
