### PR TITLE
LPS-X CommerceMLIndexer is an inner interface. It is not possible to …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…see a runtime newly registered CommerceMLIndexer service. Removing the duplicated indexes creation attempt.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:commerce

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129800

**Pull request closed without merging**
