### PR TITLE
LPS-74714

### PR DESCRIPTION
**Pull request by lanceji92674957**
Adapt to changes for "generated" tag from https://github.com/brianchandotcom/liferay-portal/pull/52020

### CODE REVIEW

**Comment by lanceji92674957** [comment]
@tinatian

**Comment by tinatian** [comment]
Hi @hhuijser ,

With your support to avoid formatting generated xml, we have to add "`<!-- * @generated -->`" instead of "`<!-- @generated -->`" in the generated xml.

Could you please take a look at this?

Thanks.
Tina.

**Comment by hhuijser** [comment]
@tinatian, see https://github.com/brianchandotcom/liferay-portal/pull/52093

**Comment by tinatian** [comment]
@lanceji92674957 Please rebase your changes once Hugo's pull got merged.


Thanks.
Tina.

**Comment by lanceji92674957** [comment]
ok, thanks! @hhuijser @tinatian

**Pull request closed without merging**
