### PR TITLE
LPS-112984 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz remove those
```
	@Reference(
		cardinality = ReferenceCardinality.MULTIPLE,
		policy = ReferencePolicy.DYNAMIC,
		policyOption = ReferencePolicyOption.GREEDY,
		unbind = "_removeJavaScriptAwarePortalWebResources"
	)
```
switch to use service tracker list. There is rarely a good use case to use DS to do dynamic collecting. ServiceTracker based collecting is generally a better solution.
Please resend, thanks!

**Pull request closed without merging**
