### PR TITLE
Tika service extract buddy policy

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:acceptance-release

**Comment by shuyangzhou** [comment]
ci:test:dl-store

**Comment by shuyangzhou** [comment]
ci:test:document

**Comment by shuyangzhou** [comment]
@vicnate5 please help me watch out on this pull, and run other necessary tests too. This is the tika extraction pull.

**Comment by vicnate5** [comment]
@shuyangzhou See related failures:

Integration [com.liferay.resource.actions.test.ResourceActionsDefinitionTest](https://testray.liferay.com/home/-/testray/case_results/1613945844)
```
com.liferay.resource.actions.test.ResourceActionsDefinitionTest > testResourceActions FAILED
    java.lang.AssertionError: The following resource action issues are found:
    		com.liferay.portal.tika: resource action definition file should be in resource-actions/default.xml rather than META-INF/resource-actions/default.xml
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    		Portlet resource 90 is defined in bundle com.liferay.portal.tika, but the corresponding portlet is in another bundle org.eclipse.osgi_3.13.0.LIFERAY-PATCHED-11
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    		Model resources are defined in bundle com.liferay.portal.tika which is not liferay service bundle
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at com.liferay.resource.actions.test.ResourceActionsDefinitionTest.testResourceActions(ResourceActionsDefinitionTest.java:110)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:745)
 ```
 
 Integration [com.liferay.portal.crypto.hash.test.CryptoHashTest](https://testray.liferay.com/home/-/testray/case_results/1613944663)
 ```
 com.liferay.portal.crypto.hash.test.CryptoHashTest > testCryptoHashGeneratorWithConfiguration FAILED
    java.lang.AssertionError
    	at org.junit.Assert.fail(Assert.java:87)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at org.junit.Assert.assertNotNull(Assert.java:713)
    	at org.junit.Assert.assertNotNull(Assert.java:723)
    	at com.liferay.portal.crypto.hash.test.CryptoHashTest.lambda$testCryptoHashGeneratorWithConfiguration$0(CryptoHashTest.java:146)
    	at com.liferay.portal.crypto.hash.test.CryptoHashTest._callService(CryptoHashTest.java:400)
    	at com.liferay.portal.crypto.hash.test.CryptoHashTest.testCryptoHashGeneratorWithConfiguration(CryptoHashTest.java:142)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:745)
 ```
 
 Unit [com.liferay.portal.util.LayoutListUtilTest](https://testray.liferay.com/home/-/testray/case_results/1613946329)
 ```
 Testcase: testGetLayoutDescriptions(com.liferay.portal.util.LayoutListUtilTest):	Caused an ERROR
Unable to open resource com/liferay/portal/util/dependencies/layout_list_util.json in class loader sun.misc.Launcher$AppClassLoader@18b4aac2
java.io.IOException: Unable to open resource com/liferay/portal/util/dependencies/layout_list_util.json in class loader sun.misc.Launcher$AppClassLoader@18b4aac2
	at com.liferay.portal.kernel.util.StringUtil.read(StringUtil.java:2210)
	at com.liferay.portal.kernel.util.StringUtil.read(StringUtil.java:2178)
	at com.liferay.portal.util.LayoutListUtilTest.setUp(LayoutListUtilTest.java:100)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```

**Comment by shuyangzhou** [comment]
@vicnate5 please check the latest results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go, it will have a minor rebase issue on `util-java/bnd.bnd`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113785

**Pull request closed without merging**
