### PR TITLE
LPS-138796

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
fix PMD violation...

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
@shuyangzhou the smoke tests failed due to an elasticsearch issue (not related to my PR)

**Comment by rotty3000** [comment]
@vicnate5 could you help me confirm the above?

**Comment by vicnate5** [comment]
@shuyangzhou Failure is not related to this PR. 

This is the first time I have seen this story, @austinchiang @gaborlovasdotcom either of your teams aware of this or have any testing planned?

**Comment by shuyangzhou** [comment]
@rotty3000 the antivirus-async module contains a portlet https://github.com/shuyangzhou/liferay-portal/blob/39e7f0c6ae87efbd1d66887a94f452c6da86f4d2/modules/dxp/apps/antivirus/antivirus-async/src/main/java/com/liferay/antivirus/async/internal/portlet/AntivirusAsyncPortlet.java and some other web layer stuff.

This module should be splitted, maybe antivirus-async-store and antivirus-async-web?

And once you separate them, please send the them in different pulls, the backend store piece first. 

And I see quite a few unused constants in https://github.com/shuyangzhou/liferay-portal/blob/39e7f0c6ae87efbd1d66887a94f452c6da86f4d2/modules/dxp/apps/antivirus/antivirus-async/src/main/java/com/liferay/antivirus/async/constants/AntivirusAsyncConstants.java, please double check their usages, also the new language keys.

**Comment by rotty3000** [comment]
hey @shuyangzhou is that a hard requirement? because the Portlet is not visible in the UI, it's just a necessary construct in order to provide a notification handler (which never calls the portlat).

**Comment by shuyangzhou** [comment]
@rotty3000 it is not clearly required anywhere, however if you search through codebase, all portlets are in web modules. It just has been like that since the beginning, I don't want to start a new pattern. Also if it is never used, I think it is necessary to decouple it from "notification handler", no sure how do they tie to each other?

**Comment by rotty3000** [comment]
A notification handler is only found attached to a portlet. Changing this would require a much bigger architecture change which I don't wish to make in this PR.

**Comment by shuyangzhou** [comment]
Ok, then don't decouple them, but at least notification handler is still belonging to web layer, I think split the store and web still makes sense, right?

**Comment by rotty3000** [comment]
yeah, I will do that.

**Comment by austinchiang** [comment]
> @shuyangzhou Failure is not related to this PR.
> 
> This is the first time I have seen this story, @austinchiang @gaborlovasdotcom either of your teams aware of this or have any testing planned?

I haven't seen this @vicnate5 , will talk to my team to evaluate whether it needs coverage or not. Thanks!

**Comment by gaborlovasdotcom** [comment]
> @shuyangzhou Failure is not related to this PR.
> 
> This is the first time I have seen this story, @austinchiang @gaborlovasdotcom either of your teams aware of this or have any testing planned?

This is also new to me, I don't have information if we need to cover this.

**Comment by rotty3000** [comment]
Hey folks. This story comes from DXPC's need to have a more scalable way to support antivirus checking (FYI, I'm on the DXPC team). I have discussed this with @david-truong to make sure he was on board. If you need any additional information please do not hesitate to contact me.

**Pull request closed without merging**
