### PR TITLE
LPS-X Merge frontend-taglib-util-freemarker-contributor into util-tag…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…lib to avoid the repeated release publication bnd includeresource out of date issue.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me watch over this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This should be good. Some unit tests had a compile failure, but it doesn't look related
```
     [exec] > Task :apps:segments:segments-web:processResources
     [exec] > Task :apps:segments:segments-web:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:164: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$1> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 			public <T> T accept(ExpressionVisitor<T> expressionVisitor)
     [exec] 			             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:184: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$1$1> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 					public <T> T accept(ExpressionVisitor<T> expressionVisitor)
     [exec] 					             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:194: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$1$1$1> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 							public <T> T accept(
     [exec] 							             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:212: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$1$1$1$1> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 									public <T> T accept(
     [exec] 									             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:246: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$1$2> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 					public <T> T accept(ExpressionVisitor<T> expressionVisitor)
     [exec] 					             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:426: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$2> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 			public <T> T accept(ExpressionVisitor<T> expressionVisitor)
     [exec] 			             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java:458: error: <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in <anonymous com.liferay.segments.web.internal.odata.ExpressionVisitorImplTest$3> cannot implement <T>accept(com.liferay.portal.odata.filter.expression.ExpressionVisitor<T>) in com.liferay.portal.odata.filter.expression.Expression
     [exec] 			public <T> T accept(ExpressionVisitor<T> expressionVisitor)
     [exec] 			             ^
     [exec]   overridden method does not throw java.lang.Exception
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/segments/segments-web/src/test/java/com/liferay/segments/web/internal/odata/ExpressionVisitorImplTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 7 errors
     [exec] 
     [exec] > Task :apps:segments:segments-web:compileTestJava FAILED
```
https://testray.liferay.com/reports/production/logs/2023-01/test-1-31/test-portal-acceptance-pullrequest(master)/6795/modules-unit-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
yeah, those can not be related, thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129273

**Pull request closed without merging**
