### PR TITLE
Startup optimization 342 url open stream

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
Issue found:

The Headless Delivery api page (http://localhost:8080/o/api) is blank. And http://localhost:8080/o/openapi//openapi.json is also blank.
Below error in portal console when open the above pages:
```
2023-11-16 06:11:48.518 ERROR [http-nio-8080-exec-5][ExceptionMapper:59] null
java.io.IOException: Stream closed
```
Example full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7444/functional-tomcat90-mysql57-chrome100-jdk8/4/16/liferay-log.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143943

**Pull request closed without merging**
