### PR TITLE
LPS-199739 Turn off permission checking due to its DL usages.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
Verified this fix locally by running AssetsSharingUpgrade#CanViewSharedAssetsArchive73101. Also verified https://liferay.atlassian.net/browse/LPS-199492 again just in case. Lets just wait for the CI results now to make sure this doesn't cause other issues.

**Comment by zhangyan0701** [comment]
Jenkins has some issues today. No Testray links for the relevant tests, I checked the results on Jenkins, and no regressions found.

The upgrade tests had been running for a long time, but many tests were aborted, going to try to run it again.

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by brianchandotcom** [comment]
@shuyangzhou merged to master

**Comment by lucasperj** [comment]
@shuyangzhou fixed the test that upgrades from [7.3](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2446618193&testrayRunId=2446618391&testrayCaseName=ViewVirtualInstancesArchive7310), but the tests that upgrade from [6.2](https://testray.liferay.com/home/-/testray/case_results/2446619034?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2446618193%26testrayRunId%3D2446618391%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) still fail, I tested locally to confirm and reproduce.

Reiterating the steps: 
1. Import the MySQL dump ([data-archive-virtual-instances-mysql.zip](https://github.com/shuyangzhou/liferay-portal/files/13168247/data-archive-virtual-instances-mysql.zip))
2. Upgrade to master
3. Start portal

**Comment by catarineaguiar** [comment]
re-running upgrade suite to have more accurated results

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Just ran VirtualInstancesUpgrade#ViewVirtualInstancesArchive621021 and it passed

**Comment by Kvale1733** [comment]
LocalFile.AssetsSharingUpgrade#CanViewSharedAssetsArchive73101 LocalFile.AssetsSharingUpgrade#CanViewSharedAssetsArchive72101

Also passed

DatabasePartitioningUpgrade#CanUpgradePartitionedDatabase7413U33 

Passed on the last CI run.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

The upgrade tests from 73 and 62 passed.

**Pull request closed without merging**
