### PR TITLE
LPS-138761 Instance delete operation is not deleting the instance data on all database tables

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-138761

Same pull request than https://github.com/shuyangzhou/liferay-portal/pull/10315 but I have removed the autoDeleteClassNames logic, leaving a autoDelete flag to enable disable the _autoDeleteLeftovers execution.

I have added some additional code to the CompanyLocalServiceTest test to delete the ClassName_ records that are not deleted during company deletion and are detected by DataGuard as leftover data (see commit https://github.com/shuyangzhou/liferay-portal/commit/335e4800d7d560e11d03b29e0dce055a230cf8aa ) that records are added by the staging code

Let me know if you have any questions or I should do an additional modification.

Thank you,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
