### PR TITLE
Lps 185647 redo 6

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by vicnate5** [comment]
@susanchen3

**Comment by susanchen3** [comment]
Test results are unrelated :heavy_check_mark: 

Manually tested [LPS-185647](https://liferay.atlassian.net/browse/LPS-185647) and [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) and they look good :heavy_check_mark: 

----

However, testing [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) I do not see this checkpoint stated in [LPP-49120](https://liferay.atlassian.net/browse/LPP-49120) anymore. It should show up after creating the virtual instances.
```
2023-05-24 01:13:14.016 INFO  [http-nio-8080-exec-6][OAuth2ProviderApplicationHeadlessServerConfigurationFactory:184] OAuth 2 application with external reference code liferay-sample-etc-cron-oauth-application-headless-server-dev and company ID 44062 has client ID id-3a3aecac-f1b5-9159-3433-efabb4a
```

1. Add these to etc/hosts file
```
127.0.0.1   instance-dev.com
127.0.0.1   instance-uat.com
```
2. Move the liferay-sample-etc-cron_dev.zip downloaded from https://liferay.atlassian.net/browse/LPP-49120 to osgi/client-extensions
3. Start portal with these portal-ext.properties as well as your basic mysql configuration properties
`include-and-override=portal-liferay-online.properties`
4. Login to localhost:8080 with test/test user
5. create 2 virtual Instances based off the etc/hosts added
```
Web ID: instance-dev.com
Virtual Host: instance-dev.com
Mail Domain: instance-dev.com
Max Users: 10
Active: Enabled
Virtual Instance Initializer: Welcome
```
```
Web ID: instance-uat.com
Virtual Host: instance-uat.com
Mail Domain: instance-uat.com
Max Users: 10
Active: Enabled
Virtual Instance Initializer: Welcome
```

cc: @vicnate5 @shuyangzhou

**Comment by shuyangzhou** [comment]
@vicnate5 I have no idea what that checkpoint means. Can you find someone to figure out whether the thing @susanchen3 saw matters for this issue?

**Comment by vicnate5** [comment]
@shuyangzhou The oauth2 log confirmation is the expected result here. We we tested with the same steps previously it shows.

We need a way to confirm the client extension in Step #2 is actually registered correctly.

**Comment by susanchen3** [comment]
Sorry, it actually might be a testing issue for me. I can't seem to deploy the client-extension anymore. I tried on master as well. Let me try figuring this out and retesting. @shuyangzhou @vicnate5 
```
2023-07-12 17:44:04.936 ERROR [fileinstall-directory-watcher][DirectoryWatcher:687] Unable to install artifact: /home/susan/Desktop/master/bundles/osgi/client-extensions/liferay-sample-etc-cron_dev.zip
java.lang.RuntimeException: The moduleId /liferay-sample-etc-cron_dev-client-extension/7.4.13/war is not correct
	at com.liferay.portal.plugin.ModuleId.<init>(ModuleId.java:127) ~[portal-impl.jar:?]
	at com.liferay.portal.plugin.ModuleId.getInstance(ModuleId.java:36) ~[portal-impl.jar:?]
	at com.liferay.portal.plugin.PluginPackageImpl.<init>(PluginPackageImpl.java:42) ~[portal-impl.jar:?]
	at com.liferay.portal.plugin.PluginPackageUtil._readPluginPackageProperties(PluginPackageUtil.java:372) ~[portal-impl.jar:?]
	at com.liferay.portal.plugin.PluginPackageUtil.readPluginPackageProperties(PluginPackageUtil.java:88) ~[portal-impl.jar:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor._convertToClientExtensionBundleDir(WabProcessor.java:382) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.processor.WabProcessor.getProcessedFile(WabProcessor.java:131) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.WabGenerator.generate(WabGenerator.java:82) ~[?:?]
	at com.liferay.portal.osgi.web.wab.generator.internal.connection.WabURLConnection.getInputStream(WabURLConnection.java:96) ~[?:?]
	at java.net.URL.openStream(URL.java:1093) ~[?:1.8.0_362]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:674) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:703) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1008) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:247) [bundleFile:?]

```

**Comment by shuyangzhou** [comment]
@susanchen3 should be caused by https://github.com/liferay/liferay-portal/commit/3216208d
Please go back to before that point to retest.

**Comment by susanchen3** [comment]
Reverted LPS-186063 locally on this PR and [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) passes manually. 

This pull looks good to go :heavy_check_mark: @shuyangzhou

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137778

**Pull request closed without merging**
