### PR TITLE
JDK17 with sidecar testing

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:report:2529752820

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:report:2530232336

**Comment by zhangyan0701** [comment]
ci:report:2530412629

**Comment by vicnate5** [comment]
Continued on https://github.com/shuyangzhou/liferay-portal/pull/11392

**Pull request closed without merging**
