### PR TITLE
Dlurl helper impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn run a compare for DL, thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

Here are test results on DL:


Portal Version | Git Id | Session Count | Mean Time of Log in | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 8cc0bfb | 8089 | 296 | 634
BaseLine | 8cc0bfb | 7990 | 337 | 656
PR-7776 | - | 8018 | 320 | 669
PR-7776 | - | 7873 | 356 | 693

Regards
Lily

**Comment by shuyangzhou** [comment]
Thanks @slnn !

**Pull request closed without merging**
