### PR TITLE
LPS-185647 DB Partition: sync session to avoid issues with delayed Hibernate flushes

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

I've just added an additional use case to the session sync in the CompanyThreadLocal.

Regarding your comments in previous pull requests:
https://github.com/liferay-core-infra/liferay-portal/pull/4946

> _And @achaparro since when DBPartitionUtil started to do this kind of hibernate integration? As far as I could remember, db partition is a jdbc level thing, it should not spread its logic to hibernate. The CompanySynchronizerPreUpdateEventListener logic should really be kept at jdbc level or higher DB partition business logic level, rather than at hibernate level._

We implemented this two weeks ago. DBPartition is intended to work at JDBC level and somehow that's what we still do. We use Hibernate Listener to populate the CompanyThreadLocal since we lost control of it when Hibernates delays the flush. We still set the catalog at JDBC level in the Connection wrapper.

> _@mbowerman using setListeners is on purpose. This piece of code is sensitive with who are running next to it. Not to say it can not run with others, but it needs to be aware of it, basically setting all listeners as a whole to prevent weird combination issues that spread across the codebase. We don't want this hibernate level integration become our ModelListener 2nd._

I share @mbowerman concerns, with this change we are limiting the Hibernate extension points. I understand that we need to keep them under control but we may need them in the future for edge cases like this one.

Anyways, your solution looks good to me because it covers all the use cases we had in mind.

> _And please make sure all future attempts of hibernate integration goes through core. I would catch and stop it on the first sight._

We implemented a solution that affected DB Partition only and we followed existing patterns and that's why we did not send the pull request to you but you are right, better go to Core in these cases.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
Fixed unit test failures here https://github.com/shuyangzhou/liferay-portal/pull/11130

**Pull request closed without merging**
