### PR TITLE
LPS-81651 Portlet 3.0: Define new JSP page context variables for portlet:defineObjects (renderParams)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply adds the new Portlet 3.0 `renderParams` page context variable. To my knowledge none of our out-of-the-box portlet modules opt-in to the Portlet 3.0 JSP tag library. These failures must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply adds the new Portlet 3.0 `renderParams` page context variable. To my knowledge none of our out-of-the-box portlet modules opt-in to the Portlet 3.0 JSP tag library. These failures must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62064

**Pull request closed without merging**
