### PR TITLE
LPS-X Remove portal relationship framework.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, if it is clean we need to check with Dave to see if this is truly removable.

**Comment by vicnate5** [comment]
@kyle-miho will be checking this

**Comment by kyle-miho** [comment]
com.liferay.on.demand.admin.ticket.generator.test.OnDemandAdminTicketGeneratorTest and
com.liferay.commerce.product.type.virtual.test.CPDefinitionVirtualTest
had unique failures, however they both had a failure with upstream as well during the same time period, I suspect there could have been a CI failure during that time or a temporary failure. Im going to re-run relevant to double check

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou Issues above are no longer reproduceable, was a coincidence that they failed. No unique failures found on ci:test:relevant, PR is good to go

**Comment by vicnate5** [comment]
ci:test:staging

**Pull request closed without merging**
