### PR TITLE
LPS-61798 Remove findByScopeGroup finder call during sign in grinder tests

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Also sent to Tom:
https://github.com/tomwang2011/liferay-portal/pull/29

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Does not seem related.

**Comment by shuyangzhou** [comment]
Yeah, I know, it is already fixed.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34176

**Pull request closed without merging**
