### PR TITLE
LPS-115275 Proactively refresh fragment host bundles for fragment bun…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…dles attaching

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this, thanks!

**Comment by vicnate5** [comment]
Test failures is due to flakiness with the upgrade test.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
