### PR TITLE
[ArgumentsResolver]LPS-136445 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
I suppressed the sf failure, and will send you a pull of it later and revert the suppression.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures.

**Comment by shuyangzhou** [comment]
@tinatian rebase failure, please resent.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10234

**Pull request closed without merging**
