### PR TITLE
LPS-44701 7.0.x backport requested by bchan

### PR DESCRIPTION
**Pull request by ngriffin7a**
This is a backport of LPS-44701 in order to minimize diffs in PortletURLImpl.java between the master branch and 7.0.x branch. Backport commits were reviewed by @topolik and backport was requested by @brianchandotcom here: https://github.com/brianchandotcom/liferay-portal/pull/53225#issuecomment-346666765

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a can you send this to ee repo 7.0.x branch?

**Comment by ngriffin7a** [comment]
@shuyangzhou Should I send it to liferay/liferay-portal-ee or to shuyangzhou/liferay-portal-ee ?

**Comment by shuyangzhou** [comment]
To me

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal-ee/pull/348

**Pull request closed without merging**
