### PR TITLE
LPS-X Refactor OpenAPIResourceImpl to use ServiceTrackerMap

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 can I trust the results? It does not seem running many tests.

**Comment by vicnate5** [comment]
ci:test:headless

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132816

**Pull request closed without merging**
