### PR TITLE
Lps 84409 revert lifecycle

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:reopen

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
Looking into the upgrade failure on DB2, closing for now.

**Comment by tomwang2011** [comment]
Looks like the upgrade failure is on upstream, Jason already ignored it

**Comment by tomwang2011** [comment]
ci:test

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/52d09c8218...933bfeeda3

**Pull request closed without merging**
