### PR TITLE
JDK17 1/25 all

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:report:2530940005

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:report:2531131878

**Comment by dantewang** [comment]
@zhangyan0701 This result doesn't seem to be latest, https://testray.liferay.com/home/-/testray/case_results/2531145248 should be already fixed by https://github.com/shuyangzhou/liferay-portal/pull/11392/commits/01d1a870efac591f3b2d7c1a5c4ab871ab19e7c9

**Comment by tinatian** [comment]
ci:report:2531295335

**Comment by vicnate5** [comment]
ci:test:environments

quick app servers only

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:report:2531747643

**Comment by vicnate5** [comment]
New branch at https://github.com/vicnate5/liferay-portal/pull/2462

**Pull request closed without merging**
