### PR TITLE
LPS-72038

### PR DESCRIPTION
**Pull request by dantewang**
cc @tinatian

@shuyangzhou 

I applied the same change as https://github.com/migue/liferay-portal/pull/974/commits/b18efdeca4d68d3016289a9062242c3099516e43, where Miguel suggested to fix the classpath built by db-upgrade-client instead to exclude `javax.validation`.

However, Websphere ships a `j2ee.jar` which contains `javax.validation` and a lot of other `javax.*` packages. This jar needs to be in classpath, otherwise many classes will be missing (e.g. `javax.servlet.*`).

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
Same failure seems to happen here https://github.com/dantewang/liferay-portal/pull/281
which is a totally different and unrelated change.

**Comment by dantewang** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/50027

**Pull request closed without merging**
