### PR TITLE
[Akismet]LPS-113963

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is to avoid exporting packages from non api module for Akismet. I happened to see this while working on db partition message listener issue, and the db partition changes depend on this pull, please prioritize this.

**UPDATE: Just take a look at the code, db partition does not depend on this, sorry for the confusion.**

FYI @amosfong

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou Just take a look at the code, db partition does not depend on this, sorry for the confusion.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
