### PR TITLE
LPS-77306 Portlet 3.0: Remove deprecated methods and classes in package com.liferay.portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by jpince** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@jpince Thanks for reopening. Look OK for Shuyang to review?

**Comment by jpince** [comment]
SF is still an issue. I _think_ everything else is ok, but there's a lot of failures in CI rn, so I will just say go ahead and ask Shuyang to review the next iteration; if there are errors caused by this that I don't see, we'll catch them after it's merged.
```
[java] 1: Incorrect line break: ./modules/apps/foundation/portal-portlet-bridge/portal-portlet-bridge-soy-impl/src/main/java/com/liferay/portal/portlet/bridge/soy/internal/SoyPortletRequestFactory.java 167 (SourceCheck:JavaLineBreakCheck)
[java] 2: There should be a line break after '(': ./modules/apps/foundation/portal-portlet-bridge/portal-portlet-bridge-soy-impl/src/main/java/com/liferay/portal/portlet/bridge/soy/internal/SoyPortletRequestFactory.java 167 (SourceCheck:JavaLineBreakCheck)
```

**Comment by jpince** [comment]
ci:close

**Comment by ngriffin7a** [comment]
@jpince Sorry to bother you. I should have seen that. I forgot that SF sometimes fixes things, but other times simply reports that there is something wrong. Fixed it -- here's the next iteration: https://github.com/shuyangzhou/liferay-portal/pull/5950

**Pull request closed without merging**
