### PR TITLE
[TECHNICAL SUPPORT] LPS-105241

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-105241

**"xn--"** can be in the middle of the domain in case we have subdomains:

- For example `sub.ññ.example` is encoded to `sub.xn--idaa.example`

so we have to change virtualHostname.startsWith(...) to virtualHostname.contains(...)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:stable

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81665

**Pull request closed without merging**
