### PR TITLE
LPS-75948 Portlet 3.0: Detect portlet spec version found in the portlet.xml descriptor

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou I decided to keep the portlet spec version in the container runtime options since adding `getSpecVersion` and `setSpecVersion` methods to com/liferay/portal/kernel/model/PortletApp.java would cause a Semantic Versioning MINOR version bump in com.liferay.portal.kernel.model -- Such a version bump in that package would cause every module with code generated by ServiceBuilder to require an upgrade to the new MINOR version, since that is where the BaseModel.java class lives.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@shuyangzhou I also included the com.liferay.portal.kernel.portlet.*internal*.PortletAppUtil class in order to conveniently determine the portlet spec version. Note that it is in a second/separate commit: https://github.com/ngriffin7a/liferay-portal/commit/1cb2ed1daedc06d225930efd587905d922c65cca#diff-657d1c4b2790828e211d08519ac38c35R25

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince Please verify that the test failure above is unrelated to my PR. If you determine that is indeed the case, please re-open so that Shuyang can review. Thanks!

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@ngriffin7a looks good from a test perspective

**Comment by ngriffin7a** [comment]
@jpince thanks! @shuyangzhou please review when you get an opportunity. :)

**Comment by ngriffin7a** [comment]
@shuyangzhou Please let me know if you need me to clarify anything in order to help facilitate your code review. Thanks.

**Comment by shuyangzhou** [comment]
@ngriffin7a can this be done by a similar way like https://github.com/brianchandotcom/liferay-portal/pull/54102 ?

**Comment by ngriffin7a** [comment]
@shuyangzhou Yes, I can refactor if necessary. Do you expect bchan to merge the independent registry (ExtraPortletAppConfigRegistry) soon? It would need to be backported to 7.0.x so I can use it with Portlet 3.

**Comment by shuyangzhou** [comment]
Brian is very much backlog on the work, I have no idea when this will be merged. But it should be merged eventually, maybe with some refactor. But the registry will be there.

**Comment by shuyangzhou** [comment]
@ngriffin7a I am closing this pull, please resend by using that registry. Thanks!

**Comment by ngriffin7a** [comment]
See: https://github.com/shuyangzhou/liferay-portal/pull/5566

**Pull request closed without merging**
