### PR TITLE
LPS-86406 AopService

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant The internet outage in Diamond Bar has caused the previous test to fail.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/649

**Pull request closed without merging**
