### PR TITLE
[Template Engine]LPS-89200 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please take a look at the functional test failures? are they real failures? I changed something related to template engine.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Looks like a real issue with portal instances, when the user attempts to add a new instance.
```
    [exec]     LIFERAY_ERROR: Invocation of 'start' failed. 
     [exec]     LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
     [exec]     Bundle {id: 101, name: com.liferay.portal.instances.web, version: 3.0.0}
     [exec]     	Declarative Service {id: 93, name: com.liferay.portal.instances.web.internal.portlet.action.EditInstanceMVCActionCommand, unsatisfied references: 
     [exec]     		{name: _portalInstancesLocalService, target: null}
     [exec]     	}
     [exec]     Bundle {id: 163, name: com.liferay.portal.search.admin.web, version: 2.0.0}
     [exec]     	Declarative Service {id: 240, name: com.liferay.portal.search.admin.web.internal.portlet.action.EditMVCActionCommand, unsatisfied references: 
     [exec]     		{name: _portalInstancesLocalService, target: null}
     [exec]     	}
     [exec]     Bundle {id: 203, name: com.liferay.portal.security.sso.ntlm.impl, version: 2.0.0}
     [exec]     	Declarative Service {id: 619, name: com.liferay.portal.security.sso.ntlm.internal.servlet.filter.NtlmFilter, unsatisfied references: 
     [exec]     		{name: _portalInstancesLocalService, target: null}
     [exec]     	}
     [exec]     	Declarative Service {id: 620, name: com.liferay.portal.security.sso.ntlm.internal.servlet.filter.NtlmPostFilter, unsatisfied references: 
     [exec]     		{name: _ntlmFilter, target: null}
     [exec]     		{name: _portalInstancesLocalService, target: null}
     [exec]     	}
     [exec]     Bundle {id: 386, name: com.liferay.bookmarks.service, version: 3.0.0}
     [exec]     	Declarative Service {id: 1531, name: com.liferay.bookmarks.internal.verify.BookmarksServiceVerifyProcess, unsatisfied references: 
     [exec]     		{name: _portalInstancesLocalService, target: null}
     [exec]     	}
     [exec]     Checking to see if TCat is enabled...
     [exec] 22:39:19,129 ERROR [http-nio-8080-exec-7][IncludeTag:128] Current URL /group/control_panel/manage?p_p_id=com_liferay_portal_instances_web_portlet_PortalInstancesPortlet&p_p_lifecycle=0&p_p_state=maximized&p_v_l_s_g_id=20126 generates exception: java.lang.NullPointerException
     [exec] java.lang.NullPointerException
     [exec] 	at com.liferay.portal.instances.service.PortalInstancesLocalServiceUtil.getDefaultCompanyId(PortalInstancesLocalServiceUtil.java:63)
     [exec] 	at org.apache.jsp.instance_005factions_jsp._jspService(instance_005factions_jsp:336)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:321)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:332)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
     [exec] 	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67)
     [exec] 	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:202)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
     [exec] 	at com.liferay.taglib.search.JSPSearchEntry.print(JSPSearchEntry.java:76)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     [exec]     LIFERAY_ERROR: Current URL /group/control_panel/manage?p_p_id=com_liferay_portal_instances_web_portlet_PortalInstancesPortlet&p_p_lifecycle=0&p_p_state=maximized&p_v_l_s_g_id=20126 generates exception: java.lang.NullPointerException
```

**Comment by tinatian** [comment]
@vicnate5 
I will trigger another run to confirm this.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
On further analysis, looks like a bad node (all test failures from the same single server).

**Comment by tinatian** [comment]
@shuyangzhou No real failure found according to latest test result.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66919

**Pull request closed without merging**
