### PR TITLE
Lpd 253

### PR DESCRIPTION
**Pull request by olafk**
Here's my first try on adding healthchecks. As discussed:
* One commit for the API
* One commit for a few _very_ simple healthchecks (so simple that I didn't include a unit test)
* One commit with a temporary UI, which is meant to provide a means to look at the plugins, not to be included in product.

The UI commit fails source-format rules, as it is not meant to go into core anyway.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by olafk** [comment]
Looks like something went wrong with the copyright headers (no idea what - had no complaint locally), and on the "temporary UI" commit, which is not meant to be accepted anyway. I hope this organization of commits is ok, otherwise please let me know if I should work to correct something.

**Comment by shuyangzhou** [comment]
@olafk only the first complain is in web module. others are all real and need fixes.

**Comment by shuyangzhou** [comment]
@olafk please squash the SF commit into the original commit, whenever you do something from scratch, there should not be additional changes on top of your own changes. This is to make sure the history is clean.

**Pull request closed without merging**
