### PR TITLE
LPS-X Only create layouts when created groups.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
test results lost here

re-running

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Missing integration tests here still.

**Comment by shuyangzhou** [comment]
@vicnate5 what should we rerun?

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139418

**Pull request closed without merging**
