### PR TITLE
LPS-157669 ModuleServiceLifecycle should be unregistered in the rever…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…se order of regsistering, in order to deactivate components layer by layer in a peaceful way.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
