### PR TITLE
[Bug Fix]Lps 122896 lps 121537

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
@GinsonRen sorry for confusing, no need to run diff on this pull.

**Comment by tinatian** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
