### PR TITLE
LPS-102995 Extract threadlocal populate logic into separate class, pr…

### PR DESCRIPTION
**Pull request by tinatian**
…epare for next

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:stable

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by tinatian** [comment]
Hi @shuyangzhou ,
I am wondering if you comment on the wrong pull.
It seems your change to close spring context is not merged yet, I am still waiting for that to send you a new pull about the message bus change.

Tina.

**Comment by shuyangzhou** [comment]
Sorry, I meant for the other deprecation pull.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81094

**Pull request closed without merging**
