### PR TITLE
[FinderCache]LPS-118633 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please run integration test under portal-tools-service-builder-test-test you will see failed tests.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@kyle-miho Could you please verify if the unique failures are real?

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9322

**Pull request closed without merging**
