### PR TITLE
Lps 109189

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Finally got the upgrade results. No regressions found.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! See https://github.com/brianchandotcom/liferay-portal/pull/125828

**Pull request closed without merging**
