### PR TITLE
LPS-124632 Make optional DepotEntryLocalService references volatile t…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…o injected/removed them dynamically. Otherwise, many startup tasks are repeated multiple times during shutdown.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
