### PR TITLE
Lps 115016 cleanup 5

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 safe to send manually? Thanks

**Comment by vicnate5** [comment]
@shuyangzhou Unique failures in LPKG testing
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/370785/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.lpkg.deployer.controller.test/LPKGControllerVerifyTest/testLPKGController/

Will re-run the lpkg tests only.

@kyle-miho please help with this analysis today.

**Comment by vicnate5** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
@shuyangzhou Re-test passed, ok to send manually

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/92711

**Pull request closed without merging**
