### PR TITLE
[TS] LPS-114155 URLs with character outside 7-bit ASCII are not working correctly in some internal portal redirects

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-114155

To avoid problems with characters outside 7-bit ASCII, it is necessary to escape the URL in `I18nServlet.getI18nData`, see first commit: https://github.com/shuyangzhou/liferay-portal/pull/9108/commits/8ece205dac5a3f3b1e972812b7360c01dedc2a21

I am using **HttpUtil.encodePath** because slashes mustn't be encoded.

About https://github.com/shuyangzhou/liferay-portal/pull/9108/commits/368b520426e16ffe31db2b7bd64ea2f9ecb56c88 and https://github.com/shuyangzhou/liferay-portal/pull/9108/commits/8e699b0dcf23b652d19753ba96be20dfba3a47d1 I am improving **HttpUtil.encodePath** code and avoiding encoding "~" tilde character because encoding it breaks some URLs from control panel and this character is not necessary to be encoded according to RFC 2396

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Do you have any update about this PR?

Thank you

**Comment by shuyangzhou** [comment]
@jorgediaz-lr can you leave out the changes to URLCodec? Just keep doing the replacement before/after.
The concerns are:
1) This is not a very strict api exposure. Depending on what caller supplies in the char[], unexpected stuff could happen.
2) This adds performance overhead to URLCodec. URLCodec is a commonly used util, it is not fair for those who do not need this logic.
Let's keep the logic inside HttpImpl or even just inside I18nServlet, whichever makes better sense. If this turn into a common requirement by something else later, we can expose the api later.

Also please add test for it to assert the expected behavior.
Thanks!

**Comment by jorgediaz-lr** [comment]
Resent here https://github.com/shuyangzhou/liferay-portal/pull/9123

**Pull request closed without merging**
