### PR TITLE
[license bug fix]LPS-123161

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:licensing

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5 , it seems the changes on release repo did not merge, could you please take a look at it?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian License testing on master is blocked by https://issues.liferay.com/browse/LPS-123161. I am testing Dante's fix right now.

**Comment by vicnate5** [comment]
Resent here https://github.com/shuyangzhou/liferay-portal/pull/9589

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
