### PR TITLE
LPS-81651 Portlet 3.0: Define new JSP page context variables for portlet:defineObjects

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@ngriffin7a can you change the DefineObjectsTag3.java to avoid subclassing DefineObjectsTag and calling super.doStartTag(); here https://github.com/shuyangzhou/liferay-portal/pull/6253/commits/0d76971d617c1bc859a3897231c56f4ab6419c32#diff-98179e4c0ef4486cef243508b66cc5b1R42

DefineObjectsTag is a frequently used tag, and it is a heavy one due to the amount of attributes getting/setting. Calling the super.doStartTag() will just increase some unnecessary attribute accessing.

You can pull out a common base class for both of them, or just a helper class with static methods to handle the common logic, whichever makes better sense.

**Comment by ngriffin7a** [comment]
@shuyangzhou Will do. Closing this PR since it will not be merged in its current form. Great code review, thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou I started working on the refactor you requested but after a closer look, I'm not sure I understand what you want me to do.

The developer can use `<portlet:defineObjects />` from the Portlet *2.0* tag library:
```
<%@ taglib uri="http://java.sun.com/portlet_2_0"  prefix="portlet" %>
```
**OR** they can use `<portlet:defineObjects />` from the Portlet *3.0* tag library:
```
<%@ taglib uri="http://xmlns.jcp.org/portlet_3_0"  prefix="portlet" %>
```

So DefineObjectsTag3.java needs to be able to support all of the Portlet 2.0 JSP keyword variables like `portletConfig`, `portletName`, etc. as well as the new Portlet 3.0 JSP keyword variables like `resourceParams`, `mutableRenderParams`, etc.

Calling `super.doStartTag();` from DefineObjectsTag3.java satisfies this requirement.

Please let me know if I am missing something, or perhaps you could clarify what you meant when you wrote that calling `super.doStartTag();` will "increase some unnecessary attribute accessing".

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60052

**Pull request closed without merging**
