### PR TITLE
COMMERCE-1067 - headless-batch-engine - Implement ImportTaskResourceImpl

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
@shuyangzhou in the next PR I will send you centralized configuration

**Comment by shuyangzhou** [comment]
@ivicac rebase failure, please resend.
And when can we add back the test module?

**Comment by ivicac** [comment]
@shuyangzhou resent at https://github.com/shuyangzhou/liferay-portal/pull/8333

**Comment by ivicac** [comment]
I have just sent you unit tests. During the week I will try to send you integration tests

**Pull request closed without merging**
