### PR TITLE
LPD-X Remove very poor regex usage, it is just a plain chars removal.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:2571520296

**Comment by vicnate5** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:report:2571659343

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150641

**Pull request closed without merging**
