### PR TITLE
LPS-108588 DBPartition: listeners

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

@Tinatian and I were working in this pull to make the listeners work when DBPartition is enabled without affecting the current developments. We basically send the messages once per company except for those cases when they are tied to a specific company (we control that with the message.company variable and some db partition configuration we have added for global listeners)

Only one test failed in the previous pull, but it was a flaky test related to Workflow so it can be pushed to Brian manually:
https://github.com/achaparro/liferay-portal/pull/594

Let me know if you have any questions.

Thanks

cc/ @vicnate5

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@shuyangzhou, the error we are getting now is the same flaky test than before, so I think the pull is good to review.

@vicnate5 please, let us know if this is not the case.

Thanks guys.

**Comment by vicnate5** [comment]
The failure is unrelated. @shuyangzhou it is actually another random `IndexNotFoundException`
https://testray.liferay.com/reports/production/logs/test-1-3/1591207387158/test-portal-acceptance-pullrequest%28master%29/7419/functional-tomcat90-mysql57-jdk8/12/0/liferay-log.txt.gz

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9142

**Pull request closed without merging**
