### PR TITLE
LPS-61006 Patch phidias to improve jsp compilation performance

### PR DESCRIPTION
**Pull request by Preston-Crary**
See https://github.com/shuyangzhou/phidias/pull/1

The other change that I would recommend is not calling the toString methods on both the BundleJavaFileObject and the JarJavaFileObject when the logger is not enabled (when the -verbose option is not passed in) but that is a much bigger change in comparison.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
When I ran this on my own fork all tests passed. See https://github.com/Preston-Crary/liferay-portal/pull/73#issuecomment-162066311.

**Comment by shuyangzhou** [comment]
When I run it locally, I got this:
```
zsyxc@zsyxc-XPS-15-9530 /home/documents/liferay-portal/modules/third-party/org-phidias $ gw patchConfiguration on demand is an incubating feature.
:third-party:org-phidias:patch FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':third-party:org-phidias:patch'.
> Could not expand ZIP '/home/zsyxc/.liferay/mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.234 secs

```
And src jar file is indeed broken. I am not sure where it got fetched. Can you check this on your side?

**Comment by Preston-Crary** [comment]
When I run gw patch locally it works.  When I run it with the --debug option I see that it's loading it from my local machine:

    13:48:38.467 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/home/preston/.m2/repository/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6.pom
    13:48:38.467 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/home/preston/.m2/repository/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6.jar

**Comment by shuyangzhou** [comment]
Your debug output does not include the sources jar at all.

Try to remove your ~/.liferay/mirrors/repo.maven.apache.org, then run it again.

I manually dropped in the sources jar from maven, then it worked, but I really did not have to do it.

Don't worry about the patch files, I changed that already, running test at https://github.com/shuyangzhou/liferay-portal/pull/2096, if it passes, I will push it up, but I want to figure out what happened to the sources jar.

**Comment by Preston-Crary** [comment]
I deleted ~/.liferay/mirrors/repo.maven.apache.org and ran it again with the debug option:

    14:11:21.124 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'phidias.jar (com.github.rotty3000:phidias:0.3.6)' in resolver cache: /home/preston/repos/trunk/portal/.gradle/caches/modules-2/files-2.1/com.github.rotty3000/phidias/0.3.6/98c20a667795ffbf78b59a75bba7641df4cc5a6c/phidias-0.3.6.jar
    14:11:21.243 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] parsing buildfile jar:file:/home/preston/repos/trunk/portal/.gradle/wrapper/dists/gradle-2.8.LIFERAY-PATCHED-2-bin/33bkl1ge4m8u8vysfheccfuh8/gradle-2.8/lib/ant-1.9.3.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/home/preston/repos/trunk/portal/.gradle/wrapper/dists/gradle-2.8.LIFERAY-PATCHED-2-bin/33bkl1ge4m8u8vysfheccfuh8/gradle-2.8/lib/ant-1.9.3.jar!/org/apache/tools/ant/antlib.xml from a zip file
    14:11:21.277 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Getting: http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar
    14:11:21.277 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] To: /home/preston/.liferay/mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar.tmp
    14:11:26.301 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@6be8e705 pairs: {GET /repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar HTTP/1.1: null}{User-Agent: Apache Ant/1.9.3}{Host: mirrors}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
    14:11:26.321 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@11bb6ecc7 pairs: {null: HTTP/1.1 404 Not Found}{Date: Mon, 07 Dec 2015 22:11:26 GMT}{Server: Apache}{Content-Length: 344}{Keep-Alive: timeout=15, max=100}{Connection: Keep-Alive}{Content-Type: text/html; charset=iso-8859-1}
    14:11:26.322 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Error opening connection java.io.FileNotFoundException: http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar
    14:11:26.323 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Error opening connection java.io.FileNotFoundException: http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar
    14:11:26.323 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Error opening connection java.io.FileNotFoundException: http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar
    14:11:26.324 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Can't get http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar to /home/preston/.liferay/mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar.tmp
    14:11:26.328 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] Getting: http://repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar
    14:11:26.328 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] To: /home/preston/.liferay/mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar.tmp
    14:11:26.345 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1a6ff3f45 pairs: {GET /maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar HTTP/1.1: null}{User-Agent: Apache Ant/1.9.3}{Host: repo.maven.apache.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}

**Comment by shuyangzhou** [comment]
so, it still works for you?

**Comment by Preston-Crary** [comment]
Yes, it works - but it can't find the sources jar.

**Comment by shuyangzhou** [comment]
what do you mean?

**Comment by Preston-Crary** [comment]
It the debug output it says "Can't get http://mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar to /home/preston/.liferay/mirrors/repo.maven.apache.org/maven2/com/github/rotty3000/phidias/0.3.6/phidias-0.3.6-sources.jar.tmp"

**Comment by shuyangzhou** [comment]
hmm, remove that folder again, and also remove the phidias files in your local m2 repo. Then try again.

**Comment by Preston-Crary** [comment]
I removed it from both:
/home/preston/.m2/repository/com/liferay/
and
/home/preston/.liferay/mirrors/repo.maven.apache.org

I didn't find a /home/preston/.m2/repository/com/github/rotty300 file.

Still says build successful.

**Comment by shuyangzhou** [comment]
Ok, then I will check with Andrea when I get to office(hopefully tomorrow), it might be something weird on my machine. Really hate those caches.

**Comment by Preston-Crary** [comment]
Yes I agree, the caches do add a lot of complexity to building.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/33051

**Pull request closed without merging**
