### PR TITLE
[Technical-Support] LPS-90376 - Product menu and control nav menu is not rendered after login when the previous path was a portlet action URL

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-90376

Original Notes:
> I looked into this issue and found by setting the windowState to Maximum, everything works correctly because we need [the stateMax variable to be true in header_portlet.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/header_portlet.jsp#L50).  Setting the lifecycle to 1 (to reproduce the issue) and manually changing this variable to true once hit through a breakpoint is enough to resolve the issue.
> 
> My only hesitation has to do with the portlet phases and if this is the "right" solution.  I'm not sure if there is some reason we shouldn't be executing this logic if in the action lifecycle, but I haven't seen any issues, nor have any tests failed.
> 
> Please let me know what you think, thanks!

/cc @jrao @ChrisKian

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5  please scan this pull for me, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No unique functional failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68915

**Pull request closed without merging**
