### PR TITLE
LPS-X An ugly workaround for the bad design. BundleSiteInitializer._a…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ddLayoutContent() is assuming the LayoutPageTemplateStructure is ready to use. But the LayoutPageTemplateStructure is created by previous Layout creation triggered by com.liferay.layout.page.template.internal.model.listener.LayoutModelListener.onAfterCreate(). During startup time with an empty db, BundleSiteInitializer may run before the LayoutModelListener is registered. Then the layout will be created without creating its LayoutPageTemplateStructure, causing BundleSiteInitializer._addLayoutContent() throws a NPE. By design, stuff created by ModelListener must be considered "optional", since other code simply has no knowledge about whether certain ModelListener exists or not. Any assumption about a ModelListener has previous invoked for an entity is fundamentally wrong.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138689

**Pull request closed without merging**
