### PR TITLE
[License]LPS-123631

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5 ,
I would like this pull be tested for all the features of license, I am not sure how much the automatic tests covered, could you please test it manually if not covered?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Automated testing passed. Scheduled manual testing, expecting to have full results tomorrow.

**Comment by vicnate5** [comment]
@tinatian Full manual testing completed. No regressions found.

Details on https://issues.liferay.com/browse/LRQA-64196

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 I pushed one commit to the release repo pull, could you please test the expire related logic if it is not included in the automatic tests?

Thanks.
Tina

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9711

**Pull request closed without merging**
