### PR TITLE
Spa top head jsp dynamic include

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@tomwang2011 run a diff on this.

**Comment by shuyangzhou** [comment]
@tomwang2011 do you have this result yet?

**Comment by tomwang2011** [comment]
The results are at: smb://172.16.0.30/benchmark/2016/TestPulls-Shuyang/12-20-16-SPATopHeadJSPDynamic

**Pull request closed without merging**
