### PR TITLE
[Bug Fix]LPS-123818

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,

 I see a couple of problems with this approach:

1. In a rolling restart master is going to be notified, but it doesn't have the code.
2. If someone wants to deploy a new job, and its deployment process isn't correct (and only deploys on the slave), we aren't going to fail gracefully.

Kind regards.

**Comment by tinatian** [comment]
Hi @marianoalvarosaiz 
For 1. the notification is sent out by slave node, master node does not need to have this change and it can receive the notification and deploy the job.
For 2. what do you mean by "its deployment process isn't correct (and only deploys on the slave)", what kind of failure? can you explain in details?
If the job is not going to deploy on master, then we should not broadcast to master node. If it did deploy on master, then this code will make it to broadcast and deploy on master.

**Comment by tinatian** [comment]
Hi @vicnate5, 
Are the failures for ci:test:clustering real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test failures not related, I am going to remove some of those tests from the suite since they are never expected to pass at head (they test with a released fix pack)

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
