### PR TITLE
LPS-104906 Remove property and only enable it if the functionality is going to be tested.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
see also: https://issues.liferay.com/browse/LPS-89093?focusedCommentId=1992018&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1992018

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 not sure whether the default test suite is good enough for this. If anything additional tests are needed, please add them in, thanks!

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@shuyangzhou regular test results look good. @joshchong is going to check the Search suite results.

**Comment by joshchong** [comment]
@shuyangzhou @vicnate5 the search suite results look good to me! Confirmed all failures are flukes or unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81385

**Pull request closed without merging**
