### PR TITLE
[Remove Parallel Render]LPS-110359

### PR DESCRIPTION
**Pull request by tinatian**
FYI @vicnate5 @jhinkey

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou No regressions found here.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86513

**Pull request closed without merging**
