### PR TITLE
LPS-78583 UpgradeSQLServer and UpgradeSybase tries to upgrade all databases

### PR DESCRIPTION
**Pull request by Preston-Crary**
I tested UpgradeSQLServer with the VM.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@shuyangzhou why is the test failing if the assumption is false?  Shouldn't we just skip the test?

**Comment by Preston-Crary** [comment]
Pushed a small change to the test to make the assert work for more databases.  Let me know if you want me to make a separate test for SQLServer and DB2.

**Comment by Preston-Crary** [comment]
I'll try to come up with a plan.  There's a problem with the AssumeTestRule which is why I'm not using it.  I'll try to fix it and resend while using it.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6160

**Pull request closed without merging**
