### PR TITLE
LPS-86198 Add thread local to disable local cache in FinderCache and EntityCache

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @slnn,
Could you please run a diff with this change? 

cc @dantewang

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @tinatian ,
Here are test results:

Login:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Log Out
-- | -- | -- | -- | --
BaseLine | bb85b9b | 46733 | 282 | 83.7
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 47168 | 294 | 87.7

Web Content:


Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page
-- | -- | -- | -- | --
BaseLine | bb85b9b | 61820 | 551 | 191
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 61804 | 530 | 187

Message Boards:


Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add MB Thread
-- | -- | -- | -- | --
BaseLine | bb85b9b | 15475 | 56.8 | 87.8
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 15338 | 21.9 | 60.4

Blog:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | bb85b9b | 12156 | 227 | 315
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 12221 | 136 | 254

Document Library:


Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add DL File
-- | -- | -- | -- | --
BaseLine | bb85b9b | 25278 | 245 | 338
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 24961 | 252 | 335


Wiki:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | bb85b9b | 16849 | 402 | 592
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 16625 | 430 | 615

AssetPublisher:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page With Filter
-- | -- | -- | -- | --
BaseLine | bb85b9b | 24465 | 466 | 212
https://github.com/shuyangzhou/liferay-portal/pull/6895 | - | 24815 | 485 | 215

**Comment by vicnate5** [comment]
@shuyangzhou Functional test results are Good. Tested at https://github.com/vicnate5/liferay-portal-ee/pull/130.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6896

**Pull request closed without merging**
