### PR TITLE
LPS-70724

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-70724

We have a lot of customers in LESA with issues caused by LPS-65978. As a solution, I am changing default values of buffered increment settings for AssetEntry

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Do you have any update about this pull request?

Thank you

**Comment by shuyangzhou** [comment]
@jorgediaz-lr this is not necessary. They are already properties, the customer can just change the values on their end. We should not change the default settings. Those properties do not make sense to have default values, as they are system depended. The values you choose may make sense to them, but won't make sense to everyone.

**Comment by jorgediaz-lr** [comment]
@shuyangzhou you can see the comment of linked LPS: https://issues.liferay.com/browse/LPS-70724?focusedCommentId=976789&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-976789 we have a lot of customers with this issue:
  - Almost all customers that are updating to fixpack 111 or upper (that includes LPS-65978) is having those throughtput issues.
  - Only customers with "Buffered Increment" functionality deactivated has no problems.

If my idea of setting default values of buffered increment settings for AssetEntry isn't the right solution, is there any other approach to this issue?

Thank you

**Comment by shuyangzhou** [comment]
@jorgediaz-lr I get that some customers see this as an issue, but there are other seeing this as a requirement. No matter which default value you choose, someone won't be happy, that's why we don't have a default value for this. Leaving it to customers. Why having them set a default values on their side is not acceptable? The whole point to have these configurable is so that they can configure it.

And for LPS-65978, I doubt it is the right solution to index within the incrementViewCounter() method. You need to understand that incrementViewCounter is asynced, and indexing is also asynced, you are asyncing an already asynced call. That is not right.

And as far as I know, indexing is already transactionally buffered. If you are indexing the same entry more than once within the same tx, we only send one indexing request to search engine. It is because you put it into incrementViewCounter() which runs asyncly, forcing everything indexing happens in its own tx, therefore nothing can be buffered.
I suggest you redo your solution for LPS-65978, this is not really an issue in buffered increment. But a design issue about when and who should do the indexing.

**Pull request closed without merging**
