### PR TITLE
LPS-92244 Use configuration listener to ensure that bundle contains "?" as location so that every component with a matching configurationPid is elegible to be notified.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz this does not work. If you put the config file in before starting portal, then start portal. The listener won't receive the CM_UPDATED event. Therefore the location changing is not made.

And the listener is too overkilled when it does work with runtime changed configs. It should only deal with Configuration for ConfigurationBeanManagedService, not for others.

And in case the exist Configruation does have a valid location, shouldn't we preserve it and just make it multi-location?

Please resolve above issues then resend.

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 regarding your first point: I've double checked and it works since the event happens also during the start. 

I agree with your second point, so after analyzing and investigating that way I found I found that this ticket was already indirectly solved by Apache Felix Fileinstall, in https://issues.apache.org/jira/browse/FELIX-5684, added in 3.6.2, that uses (as we do in Liferay, enforced even by a rule in SF) multilocation for created configurations. In this way there's no need for the ConfigurationManager to try another location. I've patched Felix fix: https://github.com/shuyangzhou/liferay-portal/pull/7554

Kind regards.

**Pull request closed without merging**
