### PR TITLE
Vulcan context

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan the results for me, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou SF issue is unique, other test failure not related.

```
 [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: File must start with copyright: ./modules/apps/portal-vulcan/portal-vulcan-impl/src/main/java/com/liferay/portal/vulcan/internal/context/LazyProxyUtil.java (SourceCheck:CopyrightCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
[stopwatch] [run.batch.test.action: 5:48.811 sec]
```

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
