### PR TITLE
Startup optimization 298 upgrade info build number 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 the results look bad, can you give me some reproduce steps? If there are many of them, start with a couple simple ones, no need to list them out.

**Comment by vicnate5** [comment]
@shuyangzhou Failures here are not related, on the upgrade suite it is just existing race conditions upstream, but the overall failure rate was only 2% of the tests.

**Comment by shuyangzhou** [comment]
Oh, I thought I broke something causing it. Great, then can you check this one https://github.com/shuyangzhou/liferay-portal/pull/11225 ? This pull was a smaller version of that one, which I was trying to find out what the problem was. If this one is clean, likely the bigger one is good too.

**Pull request closed without merging**
