### PR TITLE
LPS-76854

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54330
@mbowerman please contact the related developers who added the H2 tests, we need to get rid of it. We don't want to over complex the test system or the db support matrix. The tests should be changed to use a db that is supported by us.

**Pull request closed without merging**
