### PR TITLE
LPS-X Avoid calling toEntityModel()/toCacheModel() in MVCCSynchronize…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…rPostUpdateEventListener which would cause service calls with db modification that further leads to ConcurrentModificationException in hibernate ActionQueue

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, this pull is meant to fix that ConcurrentModificationException we talked about yesterday. But it is a race condition that I could not reproduce locally, this is just a guess fix. And we need to run it multiple times to confirm.

The change itself is an optimization anyway, as long as it does not cause regression, even not truly fixing the ConcurrentModificationException, we will still want to have it. 

I am out today, if the previous 2 runs are clean with no regression and ConcurrentModificationException, please trigger a few more relevant runs.

Thanks

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 we have 10 relevant results now. And I wrote some code to scan the 10 jenkins-report, the ConcurrentModificationException did not show in those runs. So as long as you don't see any real regression, I will let this pull in and further monitor upstream for the ConcurrentModificationException later.

**Comment by Kvale1733** [comment]
@shuyangzhou Only thing I see in all these runs is a semver error

```
 [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 79.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/79.0.0/75e810bdf6447397d2dd77d416423921943d24a9/com.liferay.portal.kernel-79.0.0.jar
```
[Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-30/test-portal-acceptance-pullrequest(master)/4931/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
Thanks @Kvale1733 ! Regenerated the semantic version and sent at https://github.com/brianchandotcom/liferay-portal/pull/124313

**Pull request closed without merging**
