### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn please run performance regression. This change is adding overhead for jsp dispatching, choose the test case with most jsp dispatchings. and run login too. Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

When I test this pull on Blog, encountered "Unable to dispatch request: java.lang.NullPointerException" in high concurrency situation, it means that the NPE appeared when I use "all-grinder" to visit portal, however, everything worked well with "test-correctness or manually do these test steps (view homepage, login, view blog entry, add blog entry, add comment).

Detail log please see:https://mega.nz/#!Xv5DlCKA!AeYIwRYMFSJjCZKLxuSZIg-XKmhJ1X8JMqvKrf0KVjw

Here are part of the errors:
```
2019-09-06 14:34:36.735 ERROR [http-nio-127.0.0.1-8080-exec-3][PortletRequestDispatcherImpl:303] Unable to dispatch request: java.lang.NullPointerException
2019-09-06 14:34:36.737 ERROR [http-nio-127.0.0.1-8080-exec-3][PortletServlet:119] javax.portlet.PortletException: javax.servlet.ServletException: java.lang.NullPointerException
javax.portlet.PortletException: javax.servlet.ServletException: java.lang.NullPointerException
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:305)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:592)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:608)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doView(MVCPortlet.java:176)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:286)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:485)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:316)
	at com.liferay.portal.search.web.internal.search.bar.portlet.SearchBarPortlet.render(SearchBarPortlet.java:97)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:589)
	at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:682)
	at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:362)
	at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1493)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:199)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
	at com.liferay.portal.servlet.TransferHeadersHelperImpl$TransferHeadersRequestDispatcher.include(TransferHeadersHelperImpl.java:162)
	at com.liferay.portlet.internal.PortletContainerImpl._render(PortletContainerImpl.java:908)
	at com.liferay.portlet.internal.PortletContainerImpl.lambda$render$2(PortletContainerImpl.java:225)
	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:425)
	at com.liferay.portlet.internal.PortletContainerImpl.render(PortletContainerImpl.java:213)
	at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:147)
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:215)
	at com.liferay.taglib.portletext.RuntimeTag.doTag(RuntimeTag.java:337)
	at com.liferay.taglib.portletext.RuntimeTag.doTag(RuntimeTag.java:93)
	at com.liferay.taglib.portletext.RuntimeTag.doEndTag(RuntimeTag.java:371)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.endEvaluation(TagTransformModel.java:400)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.onStart(TagTransformModel.java:344)
	at freemarker.core.Environment.visitAndTransform(Environment.java:422)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:107)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Macro$Context.runMacro(Macro.java:184)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.liferay.portal.template.freemarker.internal.FreeMarkerTemplate.processTemplate(FreeMarkerTemplate.java:137)
	at com.liferay.portal.template.BaseTemplate.processTemplate(BaseTemplate.java:127)
	at com.liferay.taglib.util.ThemeUtil.doIncludeFTL(ThemeUtil.java:300)
	at com.liferay.taglib.util.ThemeUtil.include(ThemeUtil.java:116)
	at com.liferay.taglib.util.ThemeUtil.include(ThemeUtil.java:80)
	at com.liferay.taglib.theme.IncludeTag.doEndTag(IncludeTag.java:34)
	at org.apache.jsp.html.common.themes.portal_jsp._jspx_meth_liferay_002dtheme_005finclude_005f1(portal_jsp.java:712)
	at org.apache.jsp.html.common.themes.portal_jsp._jspService(portal_jsp.java:644)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.servlet.DirectRequestDispatcher.forward(DirectRequestDispatcher.java:49)
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.forward(DirectRequestDispatcherFactoryImpl.java:182)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:82)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.forward(ClassLoaderRequestDispatcherWrapper.java:45)
	at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:63)
	at com.liferay.portal.struts.PortalRequestProcessor._internalModuleRelativeForward(PortalRequestProcessor.java:364)
	at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:419)
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:155)
	at com.liferay.portal.internal.servlet.MainServlet.doGet(MainServlet.java:202)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:619)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
	at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:357)
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:397)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:379)
	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: java.lang.NullPointerException
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:950)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:885)
	at com.liferay.taglib.servlet.PageContextWrapper.handlePageException(PageContextWrapper.java:173)
	at com.liferay.taglib.servlet.AutoClosePageContextWrapper.handlePageException(AutoClosePageContextWrapper.java:162)
	at org.apache.jsp.search.bar.view_jsp._jspService(view_jsp.java:499)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:325)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:336)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:290)
	... 150 more
Caused by: java.lang.NullPointerException
	at com.liferay.portal.kernel.util.ParamUtil.getString(ParamUtil.java:2342)
	at com.liferay.frontend.taglib.soy.servlet.taglib.TemplateRendererTag.isPositionInLine(TemplateRendererTag.java:218)
	at com.liferay.frontend.taglib.soy.servlet.taglib.TemplateRendererTag.doEndTag(TemplateRendererTag.java:55)
	at org.apache.jsp.search.bar.view_jsp._jspService(view_jsp.java:443)
	... 163 more
```

**Comment by shuyangzhou** [comment]
@slnn we have tag pool enabled for benchmark, right? Try to disable it to see whether it still happens. And I need to know whether disabling the tag pool will cause any noticeable performance regression. (I guess not, but need you to confirm), since we have 2 jaspers, we need to test: 1) just disable inner jasper. 2) both tomcat Jasper and inner Jasper. Since we only have control for tomcat's Jasper, not for other appservers. Even this works it still can not be a real solution for the ticket, just trying to understand the performance diff.
@mtambara this must be some sort of race condition, please look into it deeper when you are back. So basically I think the cleanup happens after the tag has been check-in and re-checkout by another thread, the net result is resetting others' inused tags.

**Comment by slnn** [comment]
Hi @shuyangzhou 

I have tried disable the tag pool in benchmark(please see changes in: https://github.com/slnn/liferay-benchmark-ee/pull/121), but still encountered the NPE issue on this pull.

But I test the performance about disabling the tag pool, from test results, it seems that disable the tag pool make performance a bit better than baseline:

login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 4967e32 | 44732 | 272 | 78.7
Disable tag pool | - | 46424 | 257 | 76.7

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 4967e32 | 55714 | 558 | 165
Disable tag pool | - | 58847 | 559 | 168

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 4967e32 | 17798 | 31.1 | 78.9
Disable tag pool | - | 17858 | 38.8 | 83.5

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 4967e32 | 14973 | 235 | 278
Disable tag pool | - | 15283 | 84.4 | 163

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 4967e32 | 25115 | 232 | 316
Disable tag pool | - | 26082 | 211 | 297

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 4967e32 | 14635 | 218 | 420
Disable tag pool | - | 14956 | 243 | 444

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 4967e32 | 26907 | 411 | 169
Disable tag pool | - | 27544 | 431 | 177

I will test these without this pull and update test results when I got them
 1) just disable inner jasper. 
 2) both tomcat Jasper and inner Jasper

For diabling the Tomcat Jasper I do like this: https://github.com/slnn/liferay-benchmark-ee/pull/122,
but for disabling the inner Jasper, I only do not deploy the com.liferay.portal.osgi.web.servlet.jsp.compiler.jar which contains the Liferay's Jasper implementation com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.

Regards
Lily

**Comment by slnn** [comment]
Hi @shuyangzhou,

Sorry, I think I got a misunderstanding about the test, do you want test these, right?
1>Disable the tag pool in inner Jasper
2>Disable the tag pool both in inner Jasper and Tomcat Jasper

Lily

**Comment by slnn** [comment]
The NPE still appeared on this pull with these configs:
1>Only disable the tag pool in inner Jasper, see configs in https://github.com/slnn/liferay-benchmark-ee/pull/123
2>Only disable the tag pool in Tomcat Jaser, see configs in https://github.com/slnn/liferay-benchmark-ee/pull/121
2>Disable the tag pool both in inner Jasper and Tomcat Jasper 

Lily

**Comment by shuyangzhou** [comment]
@slnn don't worry about pull, @mtambara is going to redo it.

The only question right now is, on master, is disabling tag pool a good thing or bad thing?
I need a summary on these:
1) Baseline(clean master)
2) Baseline + disable tomcat jasper + disable liferay jasper
3) Baseline + disable liferay jasper

We need to know the diff between 2) and 3), because when not deploying on Tomcat, we don't really have clean ways to disable other appserver' jsp container' pooling behavior.

If your previous numbers is already showing this, please confirm, otherwise please redo it. Thanks!

**Comment by slnn** [comment]
OK, will test about disabling tag pool and update test results in:https://docs.google.com/spreadsheets/d/1FnPd1Pfyuy09TymqXbkCxnVh-uDm33JAY6BsRGi_yzc/edit?usp=sharing

**Comment by shuyangzhou** [comment]
ok, seems it is general faster when disabled. @slnn please a pull on master to disable them both.

For tomcat jasper, make it inside unzip-tomcat.

@mtambara we still need to deal the problem in the way we talked for other appservers.

**Comment by slnn** [comment]
Hi @shuyangzhou,
I got all the test results here:
https://docs.google.com/spreadsheets/d/1FnPd1Pfyuy09TymqXbkCxnVh-uDm33JAY6BsRGi_yzc/edit?usp=sharing

From test results,  the faster came from disable the tag pool of Tomcat as when only disable the tag pool of liferay jasper, results did not show faster.

But disable them both, still can see the general fater.

**Pull request closed without merging**
