### PR TITLE
[TECH-SUPPORT] LPS-55106 Too long PortletPreferences XML can cause OutOfMemoryError

### PR DESCRIPTION
**Pull request by laszlocsontos**
Hi Shuyang,

Out of our customers is facing OOMEs from time to time. From the heap dumps we saw that cache keys used in PortletPreferencesFactoryImpl were in the >1MB rage.

With Vilmos we agreed that with HashCodeCacheKeyGenerator the probability of collision is too high, thus we chose using SHA1 sums instead.

Let me know if you have an another solution in mind.

Thanks for reviewing!

Cheers,
László

/CC @vilmospapp

### CODE REVIEW

**Comment by shuyangzhou** [comment]
This looks very heavy. That cache is used too often to stand for a strong hashed key.

In most normal case, the preference XML is pretty small. But I get that in your case, you get a lot of large ones. Maybe it is better to simply adding a size threshold for the XML key to only cache the small ones, just let the big ones to miss. And make the threshold configurable.

Can you make that solution too? Then send both pulls to @dantewang to run a performance regression test. Base on the results, we choose a solution.

**Comment by laszlocsontos** [comment]
Wouldn't XML parsing become even more heavier than calculating SHA sums if we allow a cache misses?

**Comment by shuyangzhou** [comment]
It is, but like I said, it should be small in normal case. I'd rather make the rare slow case even slower, than making the fast common case slower.

**Comment by shuyangzhou** [comment]
Or we can choose some middle solution, which is, below the threshold, direct using the XML as the key, above the threshold strong hash it.

Since the hashed result should never conflict with any raw XML. It should be safe to share the same cache for both types of keys.

**Comment by laszlocsontos** [comment]
I like your middle solution.

@vilmospapp could you please adjust your changes and introduce a property for the size threshold?

Thanks!

**Pull request closed without merging**
