### PR TITLE
LPS-73947 _memoryClusteredJobs should only be deleted after being demanded to master and no exception in execution thrown.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please this over.
@marianoalvarosaiz for more scheduler related changes, please send to @tinatian  in the future.

**Comment by tinatian** [comment]
@shuyangzhou  OK, got it.

**Comment by marianoalvarosaiz** [comment]
Ok @shuyangzhou

**Comment by tinatian** [comment]
@marianoalvarosaiz Sorry for late review, could you please rebase and send, there is code conflict.

**Comment by marianoalvarosaiz** [comment]
see https://github.com/tinatian/liferay-portal/pull/685

**Pull request closed without merging**
