### PR TITLE
LPS-81861 Portlet 3.0: Refactor portlet request parameter handling and portlet URL generation (implement PortletURL getActionParameters(), getRenderParameters(), getResourceParameters(), and setBeanParameter(PortletSerializable) methods)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou This PR has one commit that annotates `@Deprecated` methods and implements the following methods that are new for Portlet 3.0:
- `PorteltURL.getActionParameters()`
- `PorteltURL.getRenderParameters()`
- `PorteltURL.getResourceParameters()`
- `setBeanParameter(PortletSerializable)`

None of these methods should be called by any part of our system at this time, it URL generation is not affected. In a subsequent PR, I will refactor the `@Deprecated` methods so that they call through to the underlying `_mutableActionParameters`, `_mutableRenderParameters`, and `_mutableResourceParameters` composition objects. I will also refactor the `generateToString()` method in a subsequent PR.

/cc @dantewang @ChiZelin

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou The "clean-up-logs" failure is the only one unique to this PR and it must be unrelated.

Please review at your earliest convenience. Thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou Do you have room in your schedule to review this PR? Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61733

**Pull request closed without merging**
