### PR TITLE
[Bug Fix]LPS-124222

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@tinatian rebase issue, please resend.

**Comment by dantewang** [comment]
@ChiZelin please rebase

**Comment by dantewang** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9697

**Pull request closed without merging**
