### PR TITLE
Make these dependencies compileOnly

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test:backend

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70427
@mtambara I merged this in, but let's push harder to make them all compileOnly, I don't know test bundles getting bnd and osgi api through the bridge bundle, that's too much unnecessary promises on our side.

**Comment by shuyangzhou** [comment]
I made the changes here https://github.com/brianchandotcom/liferay-portal/pull/70448

**Pull request closed without merging**
