### PR TITLE
LPS-129058, LPS-130886 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-129058
https://issues.liferay.com/browse/LPS-130886

Note: Quarantine the failing test StagingUsecase#ImportLARsOnStagedSite due to [LPS-130915](https://issues.liferay.com/browse/LPS-130915) and resolve the conflict of _journal-service/bnd.bnd_ and _StagingUsecase.testcase_.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
cc @Preston-Crary @vicnate5

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
