### PR TITLE
Lps 102405

### PR DESCRIPTION
**Pull request by mtambara**
cc @vicnate5

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test:staging

**Comment by pavel-savinov** [comment]
Hey @mtambara, this fix breaks http://issues.liferay.com/browse/LPS-95020 and https://issues.liferay.com/browse/LPS-82444
I think we should try to find another way to solve it.
Thanks.

/cc @jkappler @ealonso

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
@pavel-savinov is working on a proper fix for the issue

**Comment by pavel-savinov** [comment]
@mtambara Pull sent here: https://github.com/brianchandotcom/liferay-portal/pull/79010
Thanks!

**Pull request closed without merging**
