### PR TITLE
LPS-X Defer valid jsp pathes initialization

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this result, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Only 1 unique failure. Sign In link missing after upgrade on 7.1.10.
signin

Gonna re-run, but could this be related to this change since it is related to the jsps?

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this is clean now, right?

**Comment by vicnate5** [comment]
@shuyangzhou All tests passed on re-run.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9593

**Pull request closed without merging**
