### PR TITLE
LPS-74610 Simple Socks Proxy

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:retest Just in case the twitter failure isn't masking any errors and functional test error are random.

**Comment by tomwang2011** [comment]
ci:retest

**Comment by tomwang2011** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
In each of these poshi tests, the *second* test in the grouping runs into the following error when clicking Save to create a new Virtual Instance (as part of `TestCase#setUpPortalInstance`):

```
02:30:58,240 ERROR [http-nio-8080-exec-7][PortletServlet:112] javax.portlet.PortletException: com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {companyId=37051, classNameId=20038, classPK=37051}
     javax.portlet.PortletException: com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {companyId=37051, classNameId=20038, classPK=37051}
     at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:69)
```

(Not sure if this is actually thrown when saving a new Virtual Instance, but on some occasions, Virtual Instances breaks)

unavailable

Each test after the first one in the grouping then runs the risk of coming across stale content from prior tests in the grouping, invalidating assertions or preventing 'duplicate' content from being created.  These failing tests don't seem related to the new SOCKS proxy, they might be a bug with Virtual Instances.  I'm not able to reproduce the issue locally.

We have these properties set in the runs globally, over the entire grouping:
```
     [echo] 	test.skip.tear.down=true
...
     [echo] 						test.batch.run.type=sequential
```

And this property set per each test:
```
[exec] tear.down.before.test=false
```

cc/ @tomwang2011 @michaelhashimoto

**Comment by tomwang2011** [comment]
Hi @brianwulbern the issue should be fixed here https://github.com/brianchandotcom/liferay-portal/pull/52250, thanks!

**Comment by brianwulbern** [comment]
ci:retest

**Comment by tomwang2011** [comment]
Looks like LocalProcessExecutor and ClassPathUtil are both recently changed, I will update the usages and resend, thanks!

**Comment by brianwulbern** [comment]
Can you link your new pull here or on the ticket?  Thanks!

**Comment by brianwulbern** [comment]
@tomwang2011

**Pull request closed without merging**
