### PR TITLE
LPS-104760 Following LPS-104291 also look for JSPF files in JSPServlet class

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please review

**Comment by mtambara** [comment]
@shuyangzhou looks good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81189

**Pull request closed without merging**
