### PR TITLE
[Log4j]LPS-125550

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian This integration failure looks related https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467400/AXIS_VARIABLE=15,label_exp=!master/testReport/junit/com.liferay.headless.delivery.resource.v1_0.test/MessageBoardMessageResourceTest/testPutSiteMessageBoardMessageWithoutParentMessageId/ (and it is passing upstream)

Functional test failures are unrelated

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/9870

**Pull request closed without merging**
