### PR TITLE
LPS-X Optimize ASMDelegateProxyFactory concurrency

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
Issue in ASMDelegateProxyFactoryTest:
```
## com.liferay.portal.proxy.internal.ASMDelegateProxyFactoryTest > classMethod
##

	java.lang.AssertionError: com.liferay.portal.proxy.internal.ASMDelegateProxyFactory is not fully covered
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-34/test-portal-acceptance-pullrequest(master)/4819/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
No unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142245

**Pull request closed without merging**
