### PR TITLE
Module framework impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou I could not find any unique failures in this PR, everything that was reported as failing is currently already happening on upstream acceptance master, this PR should be good to go

**Comment by shuyangzhou** [comment]
Thanks @kyle-miho !

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10032

**Comment by shuyangzhou** [comment]
@kyle-miho I saw the upgrade result came back after your comment, just want to confirm, you have scanned it too, right?

**Comment by kyle-miho** [comment]
@shuyangzhou double checked the upgrade results now, they are good as well

**Comment by shuyangzhou** [comment]
Thanks @kyle-miho !

**Pull request closed without merging**
