### PR TITLE
LPS-141305 Create an optional serviceDependency to the CommerceReferencesHolder. That way, when the CommerceReferencesHolder is available it will be injected directly into the BundleSiteInitializer instance.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rafaprax looks very good :)
@vicnate5 please help me check the results, once it is in. If good, please forward this pull, thanks!

**Comment by rafaprax** [comment]
Hey guys,

I just sort the calls to `_component.setImplementation` and `_component.setInterface` here(https://github.com/shuyangzhou/liferay-portal/pull/10538/commits/663163f192c589e70f5560809dd925c7f4c1841f) without logic changes. So, the test results are still valid. 

Thx

**Comment by vicnate5** [comment]
No regressions found.

ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113036

**Pull request closed without merging**
