### PR TITLE
Lps 111193 global

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:backend

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Some unique integration failures here. We have a full upstream run at the same hash I can compare to.

1. All databases (except [Oracle](https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/392503/AXIS_VARIABLE=41,label_exp=!master/testReport/com.liferay.segments.criteria.contributor.test/UserSegmentsCriteriaContributorTest/)) [com.liferay.segments.criteria.contributor.test.UserSegmentsCriteriaContributorTest.testGetFieldsWithComplexEntity](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/378145/AXIS_VARIABLE=41,label_exp=!master/testReport/junit/com.liferay.segments.criteria.contributor.test/UserSegmentsCriteriaContributorTest/testGetFieldsWithComplexEntity/) 
2. MariaDB (failed on other databases, just not MySQL for some reason) [com.liferay.portal.util.test.PortalImplAlternateURLTest.testDefaultPortalLocaleAlternateURL](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/384177/AXIS_VARIABLE=35,label_exp=!master/testReport/junit/com.liferay.portal.util.test/PortalImplAlternateURLTest/testDefaultPortalLocaleAlternateURL/) 
3. HSQL [com.liferay.external.data.source.test.controller.test.ExternalDataSourceControllerParentTest.testExternalDataSourceTests](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314291/AXIS_VARIABLE=15,label_exp=!master/testReport/junit/com.liferay.external.data.source.test.controller.test/ExternalDataSourceControllerParentTest/testExternalDataSourceTests/)





**Upstream run** for reference: https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream-dxp(master)/builds/549/jenkins-report.html

**Comment by shuyangzhou** [comment]
ci:test:backend

**Comment by shuyangzhou** [comment]
ci:test:backend

**Pull request closed without merging**
