### PR TITLE
LPS-159566 NotificationsViewPortletProvider should reference to non-d…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…epot PanelApp only to avoid shutdown time reactivation.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou This is good, all the test suites are passing and relevant ran the Notification testing.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
