### PR TITLE
Lps 146970

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in the relevant results, other tests not run here, is this a low risk change?

**Comment by shuyangzhou** [comment]
ci:test

@vicnate5 I am not sure, let's run it to be safer.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116437

**Pull request closed without merging**
