### PR TITLE
LPS-76247

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @shuyangzhou,

Attached is an update for http://issues.liferay.com/browse/LPS-76247.

Can you review this since it affects the DynamicCSSUtil?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by jonmak08** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53569

**Pull request closed without merging**
