### PR TITLE
[TS] LPS-92842

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92842

Also resolves the issue discovered in LPS-92252.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70537

**Pull request closed without merging**
