### PR TITLE
Lps 65125 PortalCacheIndexer's PortalCacheListeners are not registered with custom ehcache settings

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I updated the versions according to the recommendation of baseline, but instead of bumping up, it decreases. I am not sure if this is how the semantic versioning goes, please let me know if I did it in a wrong way.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
In EhcachePortalCacheManager, why you collect the Listeners into removedPortalCacheListeners first, then unregister it? Why not just directly unregister it?

And also, what is considered as PortalCacheConfiguration registered PortalCacheListener, it seems you just checked for type PortalCacheReplicator and EhcachePortalCacheListenerAdapter. User can technically programatically register listeners of those types right?

Also the system.packages.extra.mf conflicts now, please clear out the questions and resend, thanks!

**Comment by tinatian** [comment]
Q: In EhcachePortalCacheManager, why you collect the Listeners into removedPortalCacheListeners first, then unregister it? Why not just directly unregister it?
A: This is because if I unregister it directly, ConcurrentModificationException would come up since both iteator and unregister are based on same map.

Q: And also, what is considered as PortalCacheConfiguration registered PortalCacheListener, it seems you just checked for type PortalCacheReplicator and EhcachePortalCacheListenerAdapter. User can technically programatically register listeners of those types right?
A: For "PortalCacheConfiguration registered PortalCacheListener", it is the listener created by "PortalCacheListenerFactory". And for ehcache's implementation, there are two types generated by "PortalCacheListenerFactory", they are "PortalCacheReplicator and EhcachePortalCacheListenerAdapter".
I do not think user would register listeners of those types. For EhcachePortalCacheListenerAdapter, it is an bridge from our listener to ehcache's listener, no one should implement it directly. For  PortalCacheReplicator, I can not think up a reason that we would want two different PortalCacheReplicator, and if we only need one, and that one should be instanced in the factory class instead of implement directly.


Tina.

**Comment by shuyangzhou** [comment]
for 1), AggregatedPortalCacheListener is using ConcurrentHashMap inside, it is not possible to throw ConcurrentModificationException

for 2), we want to be very accurate here, because how we name the method. If we can not truly identify those listener from PortalCacheConfiguration, I'd rather stay with the marker interface version, at least I know I can trust that type.

**Comment by shuyangzhou** [comment]
for 1), AggregatedPortalCacheListener is using ConcurrentHashMap inside, it is not possible to throw ConcurrentModificationException

for 2), we want to be very accurate here, because how we name the method. If we can not truly identify those listener from PortalCacheConfiguration, I'd rather stay with the marker interface version, at least I know I can trust that type.

**Comment by shuyangzhou** [comment]
for 1), AggregatedPortalCacheListener is using ConcurrentHashMap inside, it is not possible to throw ConcurrentModificationException

for 2), we want to be very accurate here, because how we name the method. If we can not truly identify those listener from PortalCacheConfiguration, I'd rather stay with the marker interface version, at least I know I can trust that type.

**Comment by shuyangzhou** [comment]
for 1), AggregatedPortalCacheListener is using ConcurrentHashMap inside, it is not possible to throw ConcurrentModificationException

for 2), we want to be very accurate here, because how we name the method. If we can not truly identify those listener from PortalCacheConfiguration, I'd rather stay with the marker interface version, at least I know I can trust that type.

**Comment by shuyangzhou** [comment]
for 1), AggregatedPortalCacheListener is using ConcurrentHashMap inside, it is not possible to throw ConcurrentModificationException

for 2), we want to be very accurate here, because how we name the method. If we can not truly identify those listener from PortalCacheConfiguration, I'd rather stay with the marker interface version, at least I know I can trust that type.

**Comment by tinatian** [comment]
For 1), I will fix it in next pull.
For 2), We can add an interface to identify listeners from PortalCacheConfiguration. What do you think?

The key problem of the old marker interface is we have to make all listeners registered programmingly as a PersistentPortalCacheListener. Even if we might describe this in an official doc, I think we might also be found to answer why a customized listener does not work from clients.

Tina.

**Comment by tinatian** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/2887.

I added a new interface to mark which kind of listener should be removed, please check.


Thanks.

**Pull request closed without merging**
