### PR TITLE
LPS-91767 Portlet 3.0 incompatibility with PropertiesParamUtil.getProperties(PortletRequest,String)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou From what I can see, I don't think any of these failures are related. This PR contains one simple commit that fixes a Portlet 3.0 incompatibility with the Configuration portlet. Please review when at your earliest convenience. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69388

**Pull request closed without merging**
