### PR TITLE
Vii api performance oauth

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Lots of unique integration test failures here. I reproduced locally. They are passing upstream.

Too many to list all here:
https://testray.liferay.com/home/-/testray/case_results/2416633899
https://testray.liferay.com/home/-/testray/case_results/2416633388
https://testray.liferay.com/home/-/testray/case_results/2416632266
https://testray.liferay.com/home/-/testray/case_results/2416631712
https://testray.liferay.com/home/-/testray/case_results/2416632362
https://testray.liferay.com/home/-/testray/case_results/2416633905

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140172

**Pull request closed without merging**
