### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou @jpince: I don't see how the "PortalLogAssertorTest.testScanXMLLog" error is related since it didn't happen last week when this PR passed CI.

The "Unresolved requirement: Import-Package: javax.portlet" errors are indeed caused by this PR, but that's because  https://github.com/liferay/com-liferay-portal-workflow-private is a subrepo. It's the same problem as with commerce and apio.

**Comment by ngriffin7a** [comment]
@shuyangzhou @jpince: At this point I recommend that this PR be reviewed. It needs to be merged soon because most all other Portlet 3.0 PRs rely on it. Thanks.

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by jpince** [comment]
@ngriffin7a you should be able to resolve the portal-workflow reference in your ee pull, since that sub repo is not active (note [portal-workflow/.gitrepo](https://github.com/liferay/liferay-portal-ee/blob/master-private/modules/private/apps/portal-workflow/.gitrepo#L9) is in "push" mode, meaning code is pushed from central into the sub repo, not the other way around)

**Comment by ngriffin7a** [comment]
@jpince: You were right, I just pushed another commit in my liferay-portal-ee branch that upgrades modules/private/apps/portal-workflow/portal-workflow-kaleo-forms-web/build.gradle to portlet-api-3.0.0 which should fix that problem. Thanks.

@jpince @shuyangzhou: I will send a PR to @marco-leo that upgrades Commerce modules to portlet-api-3.0.0 so that the commerce team can be ready for this.

**Comment by ngriffin7a** [comment]
@jpince @shuyangzhou: Done, sent https://github.com/marco-leo/com-liferay-commerce-private/pull/398 to @marco-leo

**Comment by ngriffin7a** [comment]
I will also send a PR for APIO. Standby...

**Comment by marco-leo** [comment]
Hey @ngriffin7a this commit will be included in the beta release of 7.1 ?

**Comment by ngriffin7a** [comment]
@marco-leo It all depends on how soon these *9 commits* get reviewed by Shuyang and merged in to master by Brian.

**Comment by marco-leo** [comment]
@ngriffin7a if this will be not in beta than I have to waite before merge mine :(

**Comment by ngriffin7a** [comment]
@marco-leo That's OK, we just wanted you to be aware that this was happening and try to make it as least-disruptive to your workflow as possible. You can merge it whenever you feel it is appropriate, once this PR is merged into master.

**Comment by marco-leo** [comment]
Thanks @ngriffin7a

**Comment by shuyangzhou** [comment]
I am asking @pyoo47 to disable workflow private modules copying on CE master pr runs. Same thing as what we did for commerce. That way CE master PR should pass, master-private pr should fail. At least this way we can have the confidence in this pull.

**Comment by ngriffin7a** [comment]
@shuyangzhou I added a commit to the liferay-portal-ee branch that should fix the workflow problem. In other words, I don't think @pyoo47 needs to do that. If we run "ci:test" again with this PR, will it pick up the new commit in my liferay-portal-ee branch?

**Comment by pyoo47** [comment]
@ngriffin7a Actually what you need is in liferay-portal/build.properties. Just add private/apps/portal-workflow to the property build.exclude.dirs.

Like this:
```
    #
    # Set the module directories to exclude when running "ant all".
    #
    build.exclude.dirs=private/apps/commerce,private/apps/portal-workflow
```

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou @jpince Closing this PR because master changed again and there is a rebase conflict.

**Comment by ngriffin7a** [comment]
@shuyangzhou @jpince Sent new PR, see: https://github.com/shuyangzhou/liferay-portal/pull/6119

**Pull request closed without merging**
