### PR TITLE
LPS-77391 Portlet 3.0 Action Parameters with the same name as a Public Render Parameter must contain both values

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou Even though this is technically a Portlet 3.0 requirement, it is really a qualification of requirements in Portlet 2.0 and should therefore be backported to 7.0.x.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: When you get an opportunity, please let me know if the "unit-jdk8" failure is related to this PR. I doubt it because it has a very small change to an unrelated class.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@ngriffin7a no, that type of error usually occurs while BChan is publishing, so don't worry about it if you see it in the future.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@ngriffin7a looks good. @shuyangzhou please review!

**Comment by ngriffin7a** [comment]
@jpince Thanks a bunch! :)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54782

**Pull request closed without merging**
