### PR TITLE
[Bug Fix]LPS-110849

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou ,
This is a high priory security bug reported by github, and our deadline to fix it is June 16, 2020.

Considering we also need to backport to other versions which may also take some time and effort. Please prioritize this.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @slnn @GinsonRen Please run a diff on this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please also add functional tests for it?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian One unique failure in functional tests, error occurs when importing a Site.

Functional Steps (from the test):
1. Navigate to Guest site export (http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_exportimport_web_portlet_ExportPortlet)
2. Click "Custom Export" > Export
3. Download LAR
4. Add a new Site "Site Name"
5. Navigate to New site Import (http://localhost:8080/group/site-name/~/control_panel/manage?p_p_id=com_liferay_exportimport_web_portlet_ImportPortlet)
6. Import downloaded LAR file > Continue > Import

Result: NPE 
Liferay log: https://testray.liferay.com/reports/production/logs/test-1-16/1585589587003/test-portal-acceptance-pullrequest(master)/5739/functional-tomcat90-mysql57-jdk8/80/3/liferay-log.txt.gz

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Thanks @vicnate5! it is real, I will close this pull and resend.

Tina.

**Comment by vicnate5** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 According to the log, I think it is related to my change, but I can not reproduce it locally, could you please take a look at it?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
The Site import test passed on the next run and it passed when I ran it locally.

**Comment by GinsonRen** [comment]
@tinatian I ran a diff on qa2 base on master:45882a9986b7a4002088a5df6ba6379a497db531,here is the result:

Test Case | Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | -- | --
Login | BaseLine | 45882a99 | 15657 | 242 | 58 | -
  | PR | - | 16091 | 203 | 45.3 | 2.77%
WebContent | BaseLine | 45882a99 | 20012 | 342 | 131 | -
  | PR | - | 20345 | 343 | 131 | 1.66%
MessageBoard | BaseLine | 45882a99 | 8336 | 177 | 281 | -
  | PR | - | 8135 | 201 | 295 | -2.41%
Blog | BaseLine | 45882a99 | 5816 | 104 | 311 | -
  | PR | - | 5893 | 99.3 | 303 | 1.32%
DocumentLibrary | BaseLine | 45882a99 | 9369 | 201 | 433 | -
  | PR | - | 9290 | 202 | 433 | -0.84%
Wiki | BaseLine | 45882a99 | 5735 | 171 | 509 | -
  | PR | - | 5601 | 176 | 523 | -2.34%
AssetPublisher | BaseLine | 45882a99 | 9127 | 222 | 136 | -
  | PR | - | 9275 | 217 | 135 | 1.62%

/cc @dantewang @slnn

**Comment by GinsonRen** [comment]
Re-ran the messageboard and wiki, here is the second time result:

**MessageBoard** |   |   |   |   |  
-- | -- | -- | -- | -- | --
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
BaseLine | 45882a99 | 8336 | 177 | 281 | -
PR | - | 8135 | 201 | 295 | -2.41%
Second Time | - | 8352 | 175 | 280 | 2.67%
**Wiki** |   |   |   |   |  
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
BaseLine | 45882a99 | 5735 | 171 | 509 | -
PR | - | 5601 | 176 | 523 | -2.34%
Second Time | - | 5655 | 180 | 517 | 0.96%

/cc @tinatian @dantewang @slnn

**Comment by tinatian** [comment]
Rebase at https://github.com/tinatian/liferay-portal/pull/1763

**Pull request closed without merging**
