### PR TITLE
LPS-68951 UserFinderImpl.countByC_FN_MN_LN_SN_EA_S is slow in case of using database instead index and having a lot of users

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-68951

From @jorgediaz-lr 

> Same pull than #149 but I have removed a change done in custom-sql/portal.xml that was not necessary
> 
> Sybase has some problems with select count from a union:
> select count(c) from ((select c from table1) union (select c from table2))
> 
> To avoid sybase limitation I have added following commit: 4e881b6
> 
> This approach is similar to UserFinderImpl.countByGroups added in LPS-57748: brianchandotcom#30280

/cc @jorgediaz-lr @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@pei-jung @jorgediaz-lr this is not right. If you need a count, you should create a real select count() query. Not to push down the find query as subquery then select on the temp table, that is very inefficient.
Please resend with a real select count() query without subqueries.

**Comment by jorgediaz-lr** [comment]
@shuyangzhou  the SQL that is generated is a union of  left joins of different tables (users and others) so you cannot «select count» a single table,.
Additionally, a single user can be returned by two different subselects of union so you have to count the number of records of final union

I know it is a ugly fix, but current code is worse: Liferay is retrieving all userids in order to count them

**Comment by shuyangzhou** [comment]
@jorgediaz-lr I see, that makes sense. But can you at least move the logic to a new doCountByC_FN_MN_LN_SN_EA_S() method? Having the doFindByC_FN_MN_LN_SN_EA_S() to return a count controlled by a boolean flag is confusing. The count deserves a dedicated method for clearness.
The doCountByC_FN_MN_LN_SN_EA_S() and doFindByC_FN_MN_LN_SN_EA_S() can share a common base method, if that can eliminate some duplicated code for SQL building.

**Comment by jorgediaz-lr** [comment]
sent to https://github.com/pei-jung/liferay-portal/pull/157

**Pull request closed without merging**
