### PR TITLE
LPS-119220 Archive DLFileRank API and Service

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @adolfopa, talked this over with @david-truong, since this is only used for the archived recent documents web we're going to make this archived as well instead of making it support change tracking.  If there's some reason we cannot make that change let us know, thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
