### PR TITLE
[Deprecation]LPS-106409

### PR DESCRIPTION
**Pull request by tinatian**
Hi @kyle-miho,
Please scan test result here : https://github.com/tinatian/liferay-portal/pull/1662.

Thanks.
Tina

### CODE REVIEW

**Comment by kyle-miho** [comment]
https://testray.liferay.com/reports/production/logs/test-1-23/1577690018299/test-portal-acceptance-pullrequest(master)/5193/functional-tomcat90-mysql57-jdk8/47/1/LocalFile.DisplayPageTemplatesWithFragmentConfiguration_AddCheckboxConfigurationFragmentToDisplayPageTemplate/index.html.gz

One unique poshi test failure, I dont see any other unique failures that are non-flakes

**Comment by tinatian** [comment]
Rerun to confirm.

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
issue with cdn right now, network issue

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou This looks good. Did not see the failure reported above on new run.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82704

**Pull request closed without merging**
