### PR TITLE
Lps x Fix ci failures caused by template handler changes

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
The changes in this commit + changes of journal works on my pull. Not sure if this is the reason of this failure. Will run it for the second time and let's see if this is a random failure.

**Comment by tinatian** [comment]
ci:retest

**Comment by tinatian** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/46420

**Pull request closed without merging**
