### PR TITLE
[portal-test-integration] LPS-102243 rebase

### PR DESCRIPTION
**Pull request by dantewang**
Rebase and resend https://github.com/shuyangzhou/liferay-portal/pull/8685 cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
This SF error is irrelevant.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82826

**Pull request closed without merging**
