### PR TITLE
[Deprecation]LPS-106167

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @kyle-miho, 
Could you please you scan the test result?

Thanks.
Tina.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by tinatian** [comment]
Fix issue and resend at https://github.com/shuyangzhou/liferay-portal/pull/8678.

**Pull request closed without merging**
