### PR TITLE
LPS-X PanelAppMyAccountPermissions/UserPersonalSitePermissions take c…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…are of Permisisons creation for existing company. Change PortalInstanceLifecycleListener to ModelListener to only cover new company creation to avoid duplicated permission processing on startup.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:reevaluate:1377401_8021

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Failures only due to CI instability, the license failure didn't happen on re-run.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128890

**Pull request closed without merging**
