### PR TITLE
Aop

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
this should be the complete version.

@mtambara please watch for the failing tests, if there is still any.
@Preston-Crary please get the SB part done, let's try to completely finish it tomorrow morning. I am only in office for the morning tomorrow.

Thanks guys!

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
I think https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=16,label_exp=!master/249516/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog/ is real. @mtambara first thing tomorrow is to find out which test triggered it.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@Preston-Crary weird the external datasource one failed on CI https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/272438/testReport/com.liferay.external.data.source.test.controller.test/ExternalDataSourceControllerTest/testExternalDataSourceTests/

**Comment by shuyangzhou** [comment]
@Preston-Crary ok, I forgot to do this https://github.com/shuyangzhou/liferay-portal/pull/7081/commits/1e1e1cbe13081c53d062ef2194ec2eb7aedd8ef1

**Comment by shuyangzhou** [comment]
ci:test

**Comment by mtambara** [comment]
@shuyangzhou LPKG failure unrelated

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
