### PR TITLE
LPS-96563 Remove cache bootstrap

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi guys,
This pull is going to remove the cache bootstrap feature.

@dantewang Please backport all the way to 7.0.x once this is merged
@vicnate5 Please update the related tests or test documents about this.
@jhinkey Please update the docs if needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@shuyangzhou Test results are good here. Most of the failure related to elasticsearch issues.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82976

**Comment by dantewang** [comment]
@tinatian Just to double check, we'd like to backport a breaking change?

**Pull request closed without merging**
