### PR TITLE
LPS-112770 Avoid race condition. ReindexSingleIndexerBackgroundTaskExecutor indirectly depends on BackgroundTaskManagerImpl (through IndexWriterHelperImpl). BackgroundTaskMessageListener is constructed and started in BackgroundTaskManagerImpl activate, so it can use ReindexSingleIndexerBackgroundTaskExecutor before all its dependencies are satisfied.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:search

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by shuyangzhou** [comment]
The unit test deadlock is real.
```
[beanshell] "Test worker" #11 prio=5 os_prio=0 tid=0x00007fb4455db000 nid=0x1caa waiting on condition [0x00007fb415730000]
[beanshell]    java.lang.Thread.State: WAITING (parking)
[beanshell] 	at sun.misc.Unsafe.park(Native Method)
[beanshell] 	- parking to wait for  <0x00000000fe340728> (a java.util.concurrent.CountDownLatch$Sync)
[beanshell] 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[beanshell] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[beanshell] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
[beanshell] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
[beanshell] 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
[beanshell] 	at com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor.reindex(ReindexSingleIndexerBackgroundTaskExecutor.java:84)
[beanshell] 	at com.liferay.portal.search.internal.background.task.ReindexBackgroundTaskExecutor.execute(ReindexBackgroundTaskExecutor.java:54)
[beanshell] 	at com.liferay.portal.search.test.util.background.task.BaseReindexSingleIndexerBackgroundTaskExecutorTestCase.testFieldMappings(BaseReindexSingleIndexerBackgroundTaskExecutorTestCase.java:74)
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[beanshell] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[beanshell] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[beanshell] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[beanshell] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[beanshell] 	at org.junit.runners.BlockJUnit4Class
```

**Comment by marianoalvarosaiz** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/9054

**Pull request closed without merging**
