### PR TITLE
[TS] LPS-135873

### PR DESCRIPTION
**Pull request by dacousalr**
Hi,

This PR addresses the need of stripping noscript blocks to avoid indexing non-visible content, [LPS-135873](https://issues.liferay.com/browse/LPS-135873)

The solution has been moved to the general method since all its usages are calls from methods which needs to get a summary or a short descriptions from a given asset content.

Could you please review it?

Thanks in advance

--

NOTE: This PR was sent to Core Infra due to the following comment: https://github.com/liferay-echo/liferay-portal/pull/5274#issuecomment-884128326

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:reevaluate:1287401_123

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@dacousalr please add an unit test for this.

**Comment by dacousalr** [comment]
Unit test added, @shuyangzhou

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Unique failures do not seem to be related to this PR

**Comment by laszlopap** [comment]
Thank you for adding a unit test @dacousalr !

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by laszlopap** [comment]
Hi @shuyangzhou !

I think, that the failed tests are not related to the PR.

What do you think?

Thanks!

**Comment by GezaGroma** [comment]
Hi @shuyangzhou,
I was wondering if you had a chance to take a look at Laszlo's last comment.
Thanks for your help.

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
the last test seems to be likely unrelated as a random fluke, as it only failed in once of the relevant tests i will re-run relevant to confirm, but this pr should be good to go most likely

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou results perfectly passed

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
