### PR TITLE
LPS-81670 Portlet 3.0 Async: Methods signatures needed for Liferay's async implementation

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@ngriffin7a @shuyangzhou this is merged.

**Comment by brianchandotcom** [comment]
ci:close

**Comment by ngriffin7a** [comment]
@brianchandotcom Thank you!

**Pull request closed without merging**
