### PR TITLE
Startup optimization 289 liferay service extender concurrent

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou During the startup for an integration tests, I noticed a `Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/org.apache.aries.jmx.core.jar`

CI log https://testray.liferay.com/reports/production/logs/2023-08/test-1-36/test-portal-acceptance-pullrequest(master)/4110/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0

This is the only case I found in the results here.

**Pull request closed without merging**
