### PR TITLE
LPS-109118 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Rebased on https://github.com/shuyangzhou/liferay-portal/pull/8957

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@barrosdennys @david-gutierrez-mesa @cvanut @austinchiang @john-co See https://github.com/shuyangzhou/liferay-portal/pull/8960/commits/ef72286e658dff549dbe76a4924f48c7123e4c8f

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
Need to wait for https://github.com/brianchandotcom/liferay-portal/pull/86793 to get to upstream before testing

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Hey @vicnate5 

I noticed that you added to quarantine all from CalendarUpgrade.testcase since you changed the property from the beginning of the file. Was it intentional or you meant to quarantine only specific tests?

**Comment by vicnate5** [comment]
@rodrigocunhaa This was intentional, since one assert is flaky, that applies to all tests in this file (they all run the same scripts).

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
