### PR TITLE
Embedded jasper

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@shuyangzhou 

Unique failures
1. Upgrade execute throws 
```ERROR [main][ModuleFrameworkImpl:1649] Missing /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.43/webapps/ROOT/WEB-INF/lib/com.liferay.portal.osgi.web.jasper.plugins.taglib.jar```
2. [com.liferay.portal.character.encoding.test.CharacterEncodingTest](https://testray.liferay.com/home/-/testray/case_results/1539982264)
3. [com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.AssigneeMetricResourceTest](https://testray.liferay.com/home/-/testray/case_results/1539982409)


Environment suite failed to due to CDN issues we had last night. Will re-run.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10091

**Pull request closed without merging**
