### PR TITLE
[Enterprise Search]LPS-138918

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:license

**Comment by shuyangzhou** [comment]
@kyle-miho CI did not run on this pull, can you take a look?

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
FYI the `ci:test:relevant` run will have failing elasticsearch7 modules-unit tests due to a known issue https://issues.liferay.com/browse/LPS-139530. If those tests are the only thing blocking this PR from being forwarded, I suggest manually sending to bchan.

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
ci:close

**Pull request closed without merging**
