### PR TITLE
LPS-138761 Instance delete operation is not deleting the instance data on all database tables

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-138761

When you delete a company, some tables are not correctly cleaned.

I have added an additional check to the com.liferay.company.service.test.CompanyLocalServiceTest tests that verifies the records of the deleted company were deleted in all the database tables of the database, see first commit https://github.com/jorgediaz-lr/liferay-portal/commit/478c06ddcf1d41b119360b71663a8e127c6c1f2b

You can see the output of this change in PR https://github.com/jorgediaz-lr/liferay-portal/pull/372#issuecomment-916984272 where I sent the test without the fixes, following message is written:
`java.lang.AssertionError: There are tables with invalid companyId=57871 records expected:<[]> but was:<[AccountGroup, DLStorageQuota, DispatchTrigger, OAuth2Application, OAuth2ApplicationScopeAliases, OAuth2ScopeGrant, PortalPreferences]>` for more information see https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2245/#showFailuresLink

This change will help to detect in the future any new table that is not correctly cleaned.

Let me know if you have any question.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:Sf

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jorgediaz-lr this actually is largely duplicated to DataGuard. Try to add an attribute to DataGuard to disable autodelete here https://github.com/liferay/liferay-portal/blob/master/portal-test/src/com/liferay/portal/kernel/test/rule/DataGuardTestRuleUtil.java#L155 . Once you disable it, if there are really leftovers, the following leftover asserting logic will fail the test. Try that way to see if that meets your needs.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Thank for you message, I am going to review the DataGuard code and try to implement your idea.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
New PR https://github.com/shuyangzhou/liferay-portal/pull/10307

**Pull request closed without merging**
