### PR TITLE
[Bug Fix]LPS-130105

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
FYI @jorgediaz-lr

@ericyanLr I changed the solution, this one should be simpler and easy to understand, could you please verify it on JBoss? Thanks!


Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by georgel-pop-lr** [comment]
> e should be simpler and

Hi @tinatian,

I have checked on Jboss 7.2 and the solution seems to work.

Is this ready to be delivered to the client, or we need to wait for tests to run? 

Regards.

**Comment by ericyanLr** [comment]
Hey @tinatian, 

From my testing, the issue is no longer reproduced w/ your changes.

@georgel-pop-lr , I would say questions regarding fix delivery, would be more of a support decision. I would suggest discussing with your team if you are deciding to deliver an SDH and feel uncertain about the decision.

**Comment by tinatian** [comment]
@vicnate5 Could you please check the unique failures?

Thanks
Tina

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@tinatian No unique failures in the relevant results. I would like the see test results on our app servers though (relevant only runs tomcat). Triggered the additional tests.

**Comment by marianoalvarosaiz** [comment]
@tinatian this change would bring us back to LPS-114155. We should encode in I18nServlet following the same logic as in FriendlyURLNormalizerImpl (or whatever normalizer has the higher ranking) if not the code won't be able to find the friendly urls. For example "?", "^" are characteres below 127 that should be encoded and if fact we're encoding them in FriendlyURLNormalizerImpl.

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

Can you help confirm what you mean by **this change would bring us back to LPS-114155**? 

During my testing with these new changes, I followed the steps to reproduce for LPS-114155 and wasn't able to reproduce the issue.

As for characters, such as "?" and "^", is that a different issue than LPS-114155 and do we have steps to reproduce for that?

**Comment by ericyanLr** [comment]
@georgel-pop-lr , as a sanity check, were you also able to reproduce LPS-114155 with these new changes during your testing?

**Comment by marianoalvarosaiz** [comment]
Hi @ericyanLr,

 just use the same steps as LPS-114155 but naming the page **^_^** instead of **pageÑÑ**. It works for pageÑÑ because Ñ is greater than 127, but it won't work for ^ because we're encoding it when saving the friendly url, but we aren't encoding it in I18nServlet because is smaller than 127.

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

As a sanity check, were you able to reproduce this by manually testing? I just tried using ^_^ as the page name using the same steps as LPS-114155 and everything seems to work normally. 

Can you help confirm?

**Comment by marianoalvarosaiz** [comment]
@georgel-pop-lr

**Comment by georgel-pop-lr** [comment]
> Hi @ericyanLr,
> 
> just use the same steps as LPS-114155 but naming the page **^_^** instead of **pageÑÑ**. It works for pageÑÑ because Ñ is greater than 127, but it won't work for ^ because we're encoding it when saving the friendly url, but we aren't encoding it in I18nServlet because is smaller than 127.

Hi @ericyanLr,

I confirm what @marianoalvarosaiz is saying, I used a page name  ^_^ with a friendlyURL /^_^ 
This is not getting encoded when passing through method `_hasNonasciiCode(String string) {` with URL es/web/guest/^_^ 
Now if you try the second case described in LPS-114155 and go to c/portal/xxxx you should be redirected to the last working URL and is failing because is not finding the page as is not encoded. 
Check my video below:

https://user-images.githubusercontent.com/59687465/115739569-5152da80-a38e-11eb-85a0-39f3a2fd3f45.mp4


Before the fix this log https://github.com/liferay/liferay-portal/blob/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9/portal-impl/src/com/liferay/portal/servlet/I18nServlet.java#L221 on tomcat was encoded like this:
2021-04-22 11:36:57.743 DEBUG [http-nio-8080-exec-9][I18nServlet:221] Redirect /web/guest/%5E_%5E
2021-04-22 11:37:00.636 DEBUG [http-nio-8080-exec-6][I18nServlet:144] Language ID es
now is not being encoded and looks like this:
 2021-04-22 13:47:15.064 DEBUG [default task-7][I18nServlet:225] Redirect /web/guest/^_^
2021-04-22 13:47:15.551 DEBUG [default task-5][I18nServlet:144] Language ID es
2021-04-22 13:47:15.552 DEBUG [default task-5][I18nServlet:225] Redirect /web/guest/workflow.js.map

Hope this helps.

Regards

**Comment by ericyanLr** [comment]
Hi @georgel-pop-lr ,

Thanks for the confirmation, I was testing with Firefox and the issue was not being reproduced. 

I noticed in your video you were using Chrome, so I tried testing with Chrome and was able to reproduce when using the page name ^_^

@marianoalvarosaiz to make sure things are clear, can you confirm my understanding of the situation:
- With these new changes, LPS-114155 IS NOT reproduced
- With these new changes, a new similar issue is now encountered:
  - Which involves characters within 7-bit ascii (such as '^' and '_')
  - This can be reproduced using the same steps as LPS-114155, but replace **pageÑÑ** with **^_^**

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr ,
> 
> Thanks for the confirmation, I was testing with Firefox and the issue was not being reproduced.
> 
> I noticed in your video you were using Chrome, so I tried testing with Chrome and was able to reproduce when using the page name ^_^
> 
> @marianoalvarosaiz to make sure things are clear, can you confirm my understanding of the situation:
> 
> * With these new changes, LPS-114155 IS NOT reproduced
> * With these new changes, a new similar issue is now encountered:
>   
>   * Which involves characters within 7-bit ascii (such as '^' and '_')
>   * This can be reproduced using the same steps as LPS-114155, but replace **pageÑÑ** with **^_^**

HI @ericyanLr,

It is a bit tricky to test as is getting the last URL saved in the cache, but if you clear the cache it should always fail in any browser. 

See my test in FireFox:
https://user-images.githubusercontent.com/59687465/115743474-0044e580-a392-11eb-984f-ba6665f5c9c7.mp4

Regards.

**Comment by marianoalvarosaiz** [comment]
@ericyanLr regarding

```

    With these new changes, LPS-114155 IS NOT reproduced
    With these new changes, a new similar issue is now encountered:
        Which involves characters within 7-bit ascii (such as '^' and '_')
        This can be reproduced using the same steps as LPS-114155, but replace pageÑÑ with ^_^
```

Yes, you're right. The issue described described as in LPS-114155 title isn't reproduced. But the fix applied to that LPS was inderectly solving some other issues (as encoding unsafe characters within 7-bit ascii as the ones you mention) that this change could break.

In resume, we should try to encode same characters we are encoding in FriendlyURLNormalizerImpl, everything but a-zA-Z0-9./*_

**Comment by tinatian** [comment]
Hi guys @ericyanLr @marianoalvarosaiz @georgel-pop-lr,
I send a new fix here https://github.com/shuyangzhou/liferay-portal/pull/9974.

Tina.

**Pull request closed without merging**
