### PR TITLE
[Bug Fix]LPS-132380

### PR DESCRIPTION
**Pull request by vicnate5**
@tinatian

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10033

**Pull request closed without merging**
