### PR TITLE
[License]LPS-113733

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please take a look at the failure of ci:test:license, exactly same code passed yesterday here https://github.com/tinatian/liferay-portal/pull/1890

Thanks.
Tina

**Comment by vicnate5** [comment]
The failures are different on each run, but both failures seem to be on CI or Gradle side.
FYI @yichenroy

**Comment by vicnate5** [comment]
ci:test:license

**Comment by yichenroy** [comment]
@vicnate5 
First ci:test:license timed out after 2 hours on portal startup.

Second ci:test:license looks like a problem coming from the code in `liferay-release-tool-ee`:
```
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build.xml:129: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release.xml:891: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release.xml:1423: Can't read [/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay(;;;;;;!**javax**)] (Can't process class [com/liferay/gradle/plugins/LiferayOSGiExtPlugin.class] (invalid distance too far back))
```

If the new test fails again on the same error then we should contact Chas.

**Comment by shuyangzhou** [comment]
Is this pull good now?

**Comment by vicnate5** [comment]
@shuyangzhou From the testing side it is good.

**Comment by shuyangzhou** [comment]
Pushed release-tools repo upstream, forwarding this pull here https://github.com/shuyangzhou/liferay-portal/pull/9252

**Pull request closed without merging**
