### PR TITLE
Startup optimization 57 optimize fragment collection contributor tracker impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 Can you check the unique failures here?

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found in

com.liferay.fragment.contributor.test.FragmentCollectionContributorTest
` com.liferay.fragment.contributor.test.FragmentCollectionContributorTest > testRegisterContributedFragmentEntries FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)`[Testray](https://testray.liferay.com/home/-/testray/case_results/1986670635)

**Comment by shuyangzhou** [comment]
ci:test:relevant

Appended a fix commit to the test, @Kvale1733 please help me watch out the new results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123697

**Pull request closed without merging**
