### PR TITLE
[TS] LPS-121145

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @shuyangzhou ,

Tickets: [LPS-121145](https://issues.liferay.com/browse/LPS-121145), [PTR-1911](https://issues.liferay.com/browse/PTR-1911)

**Refresher**
As discussed:
- We can no longer use: **buffered.increment.enabled[DLFileEntry]** to disable view counts for specific entities. 
- We introduced a new portal property: **view.count.enabled**, but that only allowed us to enable/disable view count globally.
- We decided that the lost ability to disable view counts for specific entities, would be considered a bug

This PR addresses the bug and re-adds the ability to disable view counts for specific entities.

**Changes**

- Add ability to disable view count for specified class names, via the new View Count OSGI configuration
- Replace **view.count.enabled** portal property by moving it to the new View Count OSGI configuration - enabled()
- Add an example to utilize the new API, I chose: DLFileEntry
- Document breaking changes, regarding the removal of **view.count.enabled** portal property

**Notes - Removal of view.count.enabled portal property**
After discussing with Preston, using the OSGI configuration to implement the ability to disable view count for specific entities, felt like the better approach, instead of implementing it using portal properties.

Since we needed to create an OSGI configuration, we figured it would make more sense to move the **view.count.enabled** portal property into the OSGI configuration as well.

----

**Note:** I'm not super familiar with removing portal properties + adding deprecations and adding breaking changes

If there's anything you would like me to change, please let me know.
Thanks!

/cc @achaparro

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@preston-crary please take a look at this pull first, if you are ok with it, I will do another round of review.

**Comment by Preston-Crary** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9477

**Pull request closed without merging**
