### PR TITLE
[TS] LPS-92393 Servlet Filter with single dispatcher causes ClassCastException

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-92393
<- https://issues.liferay.com/browse/LPS-88047

Hey Shuyang,

You can find the details on the ticket. Let us know if you have any concerns.

Regards,
Tibor

Author: @csababotos
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/71053

**Pull request closed without merging**
