### PR TITLE
[TECHNICAL-SUPPORT] LPS-73606

### PR DESCRIPTION
**Pull request by jonathanmccann**
Please see https://github.com/jonathanmccann/liferay-portal/pull/1397 for detailed description of changes.

/cc @ChrisKian

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@ChrisKian, please resend with the changes we talked about.  Thanks!

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
