### PR TITLE
TCK3 LPS-75547

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou https://issues.liferay.com/browse/LPS-75547  This is mainly to pass the TCK.

16 test failures can be avoided.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Hmm didn't fail in this pull...
https://github.com/dantewang/liferay-portal/pull/519#issuecomment-353011321

ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2017年12月21日周四
19:32写道：

**Comment by dantewang** [comment]
ci:reopen

Dante Wang <dante.wang@liferay.com> 于 2017年12月21日周四 19:40写道：

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53898

**Pull request closed without merging**
