### PR TITLE
LPS-79799 ModelWrappers

### PR DESCRIPTION
**Pull request by Preston-Crary**
Waiting to see if this passes testing before sending the EE pull.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
EE pull:
https://github.com/shuyangzhou/liferay-portal-ee/pull/395

**Comment by shuyangzhou** [comment]
@Preston-Crary please rebase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58330

**Pull request closed without merging**
