### PR TITLE
[Bug Fix] LPS-82666

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
@shuyangzhou, let me know if this commit (and whatever commit(s) you may add on top) would be safe to cherry-pick to  7.0.x where we're seeing this issue.  I can start the backport process if it's a simple blind fetch.  But I'll need your team's help if it's beyond that.

cc/ @tinatian @dantewang

**Comment by shuyangzhou** [comment]
@tinatian will redo it in a different way.

**Pull request closed without merging**
