### PR TITLE
Startup optimization 188 avoid aop service in mvc command

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou results broke build timed out, rerunning

**Comment by kyle-miho** [comment]
ci:test:elevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou this seems to have broken Portlets from being usable in general, im dling this and testing locally
`com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.LayoutImpl#18]
javax.portlet.PortletException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.LayoutImpl#18]`

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou This PR still breaks Portal#Smoke, i'm, investigating steps to repoduce locally

**Comment by kyle-miho** [comment]
@shuyangzhou If you Create a new 
Content Page from Site Builder -> Pages -> + -> Basic Templates + Blank
And try to add some widget from the sidebar and publish the content page, an error will be thrown in the console and the redirect will then fail

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho please check the new results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou PR is good to go now, no more unique failures

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132338

**Pull request closed without merging**
