### PR TITLE
Lps 104004

### PR DESCRIPTION
**Pull request by mtambara**
200ms startup regression (https://github.com/mtambara/liferay-portal/pull/936#issuecomment-557995644)

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the test result, thanks!

**Comment by vicnate5** [comment]
Looks good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81386

Thanks @vicnate5 !

**Pull request closed without merging**
