### PR TITLE
[TS] LPS-96672 portal-impl: should be false by default

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-96672

Hi @shuyangzhou ,

As discussed, we will instead fix this by changing the default value to false for the ready state. From my testing, this resolves the issue and the CI test results look the same as the others.

Feel free to let me know if you have any questions.
Thanks!

CI Test results from my test branch: https://github.com/ericyanLr/liferay-portal/pull/123#issuecomment-501432329

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan the test results, thanks!

**Comment by yunlinsun** [comment]
Hi @shuyangzhou @vicnate5,
As requested by @monicali, I had asked @felix3508 to analyzed this pull. 
All the failures are unrelated to this commits. The test results are good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74487

**Pull request closed without merging**
