### PR TITLE
[Bug Fix]LPS-92147

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for Ci result, see more details here : https://issues.liferay.com/browse/LPS-92147

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
FYI @marianoalvarosaiz, this is part of the fix of https://issues.liferay.com/browse/LPS-91938

**Comment by marianoalvarosaiz** [comment]
Thanks @tinatian

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69609

**Pull request closed without merging**
