### PR TITLE
LPS-82215

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @robertoDiaz 

https://issues.liferay.com/browse/LPS-82215

Please let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@Preston-Crary please take a look at this.

**Comment by Preston-Crary** [comment]
Since this is an API only change we need to have a test for this.  Can you resend with test coverage for this?

**Comment by Preston-Crary** [comment]
You can add a test to either DefaultActionableDynamicQueryTest or com.liferay.portal.dao.orm.hibernate.DynamicQueryTest.

**Comment by shuyangzhou** [comment]
@ChrisKian I am closing this now, please resend it to @Preston-Crary with test, thanks!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
