### PR TITLE
LPS-188217 Since it is almost impossible to not have company PortalPr…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…eferences, let's just create it during company checking to avoid concurrent runtime lazy creation caused race condition.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
There is an issue in master that slipped in due to a false positive in stable. A fix was sent but it's not in upstream yet. 

Testing here with the temp fix to get results: https://github.com/liferay/liferay-portal/pull/5510

**Comment by Kvale1733** [comment]
There were still mass failures due to an unrelated startup issue. It's fixed now. Rerunning here. Should be no more issues.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. Didn't see the issue on CI here.

**Pull request closed without merging**
