### PR TITLE
LPS-77485 - Portlet 3.0 TCK: Failure in V2PortletTests

### PR DESCRIPTION
**Pull request by vsingleton**
V2PortletTests that call portletConfig.getContainerRuntimeOptions

### CODE REVIEW

**Comment by vsingleton** [comment]
ci:test

**Comment by jpince** [comment]
@vsingleton this SF error is real, please resolve:
`     [java] 2: Avoid multiple chaining on method 'keySet'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./portal-impl/src/com/liferay/portlet/PortletConfigImpl.java 129 (CheckStyle:ChainingCheck)`
everything else looks fine

**Comment by jpince** [comment]
ci:close

**Comment by vsingleton** [comment]
Fixed the chaining issue.

**Comment by vsingleton** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54941

**Comment by jpince** [comment]
@ealonso is FragmentEntryServiceTest.testAddFragmentEntryWithVoidHTMLElements failing at head? See failures in the retest for this pull

**Comment by jkappler** [comment]
@jpince, the test was ignored by Brian in master so no error should appear in the pull requests at the moment. We are working on a fix, and will be sending it later on

**Comment by jpince** [comment]
@jkappler thank you!

**Pull request closed without merging**
