### PR TITLE
Lps 197506

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me monitor this pull, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 
No regressions found. The SF failure should be unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141485

**Pull request closed without merging**
