### PR TITLE
LPS-194074 Don't create blank PortalPreferences just for reading, thi…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…s leads to startup race condition between worker thread and liferay/asset_auto_tagger thread on permission checking

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
The environments suite should run several tests for each db, including Oracle. If this is still present I should see it there.

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. Did not find this issue in the ci results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139619

**Pull request closed without merging**
