### PR TITLE
LPS-194715 System company does not have any user.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@111Anna this is to remove the new "select userId, languageId, timeZoneId from User_ where companyId = ? and type_ = ?"

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. 

I confirmed that the existing regression from this ticket (https://liferay.atlassian.net/browse/LPS-194952) is still reproducible.
FYI @Kvale1733

**Comment by shuyangzhou** [comment]
The fix is at https://github.com/shuyangzhou/liferay-portal/pull/11210 , this pull has nothing to do with the existing failure.

**Comment by shuyangzhou** [comment]
Technically speaking the previous commits for LPS-194715 exposed issue of LPS-194952, the LPS-194952 has always been there but covered up by a leftover threadlocal value. After the leftover is removed by LPS-194715, we are running into the case where the read to the threadlocal happens before it is correctly re-populated. The fix at https://github.com/shuyangzhou/liferay-portal/pull/11210 is pushing back the early read to be after the re-populating.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140008

**Pull request closed without merging**
