### PR TITLE
[Bug Fix]LPS-123311

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen Please run a startup diff.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please verify the unique failures?

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Here is the result, more detail please check [here](https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit#gid=0&range=C3210:C3215).

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 8b082086f37d045e275f2667a67724dcf4a597b9 | 48798 | 22222 | 22407 | 22246 | 22241 | 22160 | 22056
PR-9600 | - | 47309 | 22028.4 | 21976 | 22089 | 21967 | 22226 | 21884

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
