### PR TITLE
LPS-80663 Decouple the wait()/notify() synchronized lock (shared for all methods in the class) from the lock synchronizing getNotificationEvents() as they serve a different purpose. This way, poller/send and poller/receive threads can not enter a deadlock

### PR DESCRIPTION
**Pull request by dsanz**
Hi @shuyangzhou ,

I've been digging into this issue and I believe we can decouple the synchronized lock we use in getNotificationEvents() for wait() method from the lock we may need for the rest of the logic. As a result, the object lock can be used just for the wait()/notify() mechanism. This way, getNotificationEvents() would use its own lock which won't interfere with the object lock used by the other 2 methods (all of them are syncrhonized at this moment).

With this solution, there is no way to cause a deadlock as the one described in the ticket, and lock semantics are kept.

Anyway, I'm not sure why we do a wait() inside an if instead of a while (which is the recommended practise). I believe we do this to allow the thread to move forward even if _completed is false, in other words, to make sure we wait only for the timeout period and no more. If that's not the case, I think that other possible fix would be to enclose the wait() call into a while loop, but I think this is not optimal as it would minimize the deadlock window, not elliminate it completely.

That's the reason why I came up with this solution, which is the minimal one I can think of.

Please let me know if this makes sense or there is some better alternative.

Best

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test

**Comment by dsanz** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tinatian please take this over, thank!

**Comment by tinatian** [comment]
@shuyangzhou Start working on it.

**Comment by tinatian** [comment]
@dsanz Resend the change at https://github.com/shuyangzhou/liferay-portal/pull/6173.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58949

**Pull request closed without merging**
