### PR TITLE
LPS-100998 Make DDM CT enabled.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
Another upgrade failure.  Will resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9097

**Pull request closed without merging**
