### PR TITLE
LPS-X Drop upgrade inner steps support. From semantic versioning's po…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…int of view, having inner steps breaks versioning contracts, as inner steps can change without updating versions. Inner steps are not a stable version to resume upgrade from.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 the upgrade batch seems failed a lot. If it is real, please help me get a reproduce step, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou It is real.

Steps to Reproduce
1. Download [this mysql dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip) and import
2. Set `upgrade.database.auto.run=true`
3. Start Portal to autoUpgrade

Result:
```
ERROR [main][UpgradeStepRegistratorTracker:199] Failed upgrade process for module com.liferay.portal.workflow.kaleo.service
com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'type_' in 'field list'
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:136) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:157) ~[portal-kernel.jar:?]
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:211) ~[bundleFile:?]
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) ~[bundleFile:?]
	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:120) ~[bundleFile:?]
	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:196) [bundleFile:?]
	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:138) [bundleFile:?]
...
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'type_' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql.jar:8.0.29]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql.jar:8.0.29]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335) ~[mysql.jar:8.0.29]
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2085) ~[mysql.jar:8.0.29]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246) ~[mysql.jar:8.0.29]
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[hikaricp.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:394) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:360) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.runSQL(BaseDBProcess.java:112) ~[portal-kernel.jar:?]
	at com.liferay.change.tracking.internal.upgrade.v2_7_0.CTProcessUpgradeProcess.doUpgrade(CTProcessUpgradeProcess.java:28) ~[?:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:130) ~[portal-kernel.jar:?]
	at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:126) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:337) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:387) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115) ~[portal-kernel.jar:?]
	... 175 more

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/11037

**Pull request closed without merging**
