### PR TITLE
Startup optimization 197 service snapshot no util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Major UI regression here:

Steps to Reproduce:
1. Go to Product Menu > Design > Page Templates

UI fails to render fully and Error thrown
```
ERROR [http-nio-8080-exec-7][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_layout_page_template_admin_web_portlet_LayoutPageTemplatesPortlet&p_p_lifecycle=0&p_p_state=maximized&p_v_l_s_g_id=20119&p_p_auth=5LZBLelf generates exception: org.osgi.framework.InvalidSyntaxException: Missing '(' at "resource.name=com.liferay.layout.page.template"
org.osgi.framework.InvalidSyntaxException: Missing '(' at "resource.name=com.liferay.layout.page.template"
        at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1500) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1484) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.FilterImpl$1.call(FilterImpl.java:158) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.FilterImpl$1.call(FilterImpl.java:154) ~[org.eclipse.osgi.jar:?]
        at com.liferay.portal.bootstrap.WeakCacheHookImpl.computeIfAbsent(WeakCacheHookImpl.java:38) ~[com.liferay.portal.bootstrap.jar:?]
        at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:152) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.createFilter(BundleContextImpl.java:977) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getServiceReferences(ServiceRegistry.java:312) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getServiceReferences(BundleContextImpl.java:535) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getServiceReferences(BundleContextImpl.java:1022) ~[org.eclipse.osgi.jar:?]
        at com.liferay.osgi.util.service.Snapshot._getServiceReference(Snapshot.java:109) ~[bundleFile:?]
        at com.liferay.osgi.util.service.Snapshot.lambda$new$2(Snapshot.java:84) ~[bundleFile:?]
        at com.liferay.petra.concurrent.DCLSingleton.getSingleton(DCLSingleton.java:48) ~[com.liferay.petra.concurrent.jar:?]
        at com.liferay.osgi.util.service.Snapshot.get(Snapshot.java:97) ~[bundleFile:?]
        at com.liferay.layout.page.template.admin.web.internal.security.permission.resource.LayoutPageTemplatePermission.contains(LayoutPageTemplatePermission.java:31) ~[bundleFile:?]
        at com.liferay.layout.page.template.admin.web.internal.display.context.MasterLayoutManagementToolbarDisplayContext.isShowCreationMenu(MasterLayoutManagementToolbarDisplayContext.java:189) ~[bundleFile:?]
        at com.liferay.frontend.taglib.clay.servlet.taglib.ManagementToolbarTag.isShowCreationMenu(ManagementToolbarTag.java:365) ~[bundleFile:?]
        at com.liferay.frontend.taglib.clay.servlet.taglib.ManagementToolbarTag.processStartTag(ManagementToolbarTag.java:1205) ~[bundleFile:?]
        at com.liferay.frontend.taglib.clay.internal.servlet.taglib.BaseContainerTag.doStartTag(BaseContainerTag.java:75) ~[bundleFile:?]
        at com.liferay.frontend.taglib.clay.servlet.taglib.ManagementToolbarTag.doStartTag(ManagementToolbarTag.java:80) ~[bundleFile:?]
 ```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! That was a typo where I missed "(", rerunning.

**Comment by vicnate5** [comment]
ci:reevaluate:1387401_7100

**Comment by vicnate5** [comment]
@shuyangzhou Unit test failures here:
https://testray.liferay.com/home/-/testray/case_results/2247906381
https://testray.liferay.com/home/-/testray/case_results/2247906626

No other issues found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132538

**Pull request closed without merging**
