### PR TITLE
LPS-56627 Temporarily disable 'testScanXMLLog'

### PR DESCRIPTION
**Pull request by petershin**
Hi Shuyang,

The test below is failing and preventing code in the subrepos from being merged into [`7.0.x-private`](https://github.com/liferay/liferay-portal-ee/tree/7.0.x-private).

https://github.com/liferay/liferay-portal-ee/pull/8203#issuecomment-399546611

I've sent pulls to fix the other failing test.  Would it be ok to temporarily disable this test?

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@petershin we should not disable it, more broken stuff could sneak in. If the failures are not real, we can always force merge the subrepo pulls.

**Comment by petershin** [comment]
@shuyangzhou - Would your team be able to take a look and resolve the issue?

I can take a look too.  I'll need some steps on how to reproduce the issue locally.

**Comment by shuyangzhou** [comment]
@petershin you are talking about "Newly added bundle: "admin-dxp-theme" has the same Web-ContextPath as the following bundles: [admin-theme]. This can lead to unexpected behavior when multiple bundles provide the same context path. See https://osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html#service.http.whiteboard.servletcontext ", right?

It is already fixed.

**Comment by petershin** [comment]
@shuyangzhou - Yup, thank you!

**Pull request closed without merging**
