### PR TITLE
Lpd 25633 optimization 7

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:report:65073105

**Comment by shuyangzhou** [comment]
ci:report:65104828

**Comment by shuyangzhou** [comment]
ci:report:65126684

**Comment by shuyangzhou** [comment]
ci:test:acceptance-functional

**Comment by shuyangzhou** [comment]
ci:report:65287709

**Comment by shuyangzhou** [comment]
@vicnate5 this the latest version, please help me check the results, thanks!

@victorhcunha for me the baseline is 312578ms, on this pull is 46889ms.
I am expecting your numbers should roughly meet:
`your baseline/312578 = your number on this pull/46889` it is not going to be exact, but should not be too far off either. If it is still far off, we need to do the check to run your portal jvm on mysql server to rule out the network factor here in order to understand where is this difference from.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !

Here are the new profiles, this time testing using a local mysql. The test was done on our m3database1:
[Master](https://drive.google.com/file/d/1BQt5ICvvu-pHgT2DPE9TS9z4KFjKhJ_k/view?usp=drive_link) | [PR#11596](https://drive.google.com/file/d/1mrUb40fbtUhL8fNGqvILpBtKT0Y2XP-f/view?usp=drive_link)
I used Yourkit on my local machine to generate the snapshots.

For this round of profiling these were the time results:
Master Baseline e69f21c | PR #11596 | Difference (%)
-- | -- | --
684131 | 263857 | -61.4318018

I will do more rounds, this time to get mean and standard deviation.

**Comment by shuyangzhou** [comment]
do you mean the profile was not generated on the testing machine, but your local machine?

**Pull request closed without merging**
