### PR TITLE
[TECHNICAL SUPPORT] LPS-153646 Pages with accented names exclude their names from their canonical URL

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @shuyangzhou ,

[LPS-153646](https://issues.liferay.com/browse/LPS-153646)
Previous PR: https://github.com/shuyangzhou/liferay-portal/pull/10652

I noticed we are comparing the lowercase groupFriendlyURL 2 times against the upperCase friendlyURL, so I made an additional commit to resolve that as well. I noticed this when I tried to backport the solution to 7.3.x

As I haven't started the backport yet I made an additional commit for this LPS

Please review it.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, Summer is on vacation, thanks!

**Comment by shuyangzhou** [comment]
@kyle-miho can you help me check on the results? Catarine does not have time today either. Thanks!

**Comment by catarineaguiar** [comment]
@NemethNorbert @shuyangzhou no regressions found

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
