### PR TITLE
LPS-85787

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Thanks Preston for your review, sadly this aproach doesn’t work for ussince the filtre parser and the sort parser are going to be used bu other teams, withouth the provider.

**Comment by cgoncas** [comment]
Can you keep the filterparser and the sortparser? Since this code is the one than other teams need?

**Comment by Preston-Crary** [comment]
I'll resend it tomorrow.

**Comment by Preston-Crary** [comment]
Please see https://github.com/cgoncas/liferay-portal/pull/266

**Pull request closed without merging**
