### PR TITLE
Lps 202530

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
There is a compile error:
```
     [exec] > Task :apps:object:object-rest-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/OpenAPIResourceTest.java:77: error: unreported exception java.lang.Throwable; must be caught or declared to be thrown
     [exec] 		_company = CompanyTestUtil.addCompany(true);
     [exec] 		                                     ^
     [exec] 1 error
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-12/test-1-26/test-portal-acceptance-pullrequest(master)/12172/modules-compile-jdk8/0/2/jenkins-console.txt.gz?authuser=0

This error caused some integration tests of object rest failed.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@zhangyan0701 pushed a fix. It is actually not caused by my change, it is from previous change https://github.com/shuyangzhou/liferay-portal/pull/11320/commits/742eba9e1e5a67fdcd60a6f866ad15d9216026ce . please help me watch it over. If the new results are good, please help me forward it to Brian. Thanks!

**Pull request closed without merging**
