### PR TITLE
[Bug Fix]LPS-132380

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please add a test for this? It just need to disable cluster, bootup portal and verify any error log.

Thanks
Tina.

**Comment by vicnate5** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10024

**Pull request closed without merging**
