### PR TITLE
LPS-68289 Wrap message bus and thread pool executor to shutdown slowl…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…y to avoid interupt exceptions getting caught by the LogAssertionTestRule at the end of a test.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest Rebased the changes.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/43760

**Pull request closed without merging**
