### PR TITLE
Lps 106586

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @mtambara, @shuyangzhou,

Would it be possible to add tests for this change? Escaping issues in Config Admin come and go with any change we made in the related logic and libraries so having a class that covers all use cases and reflects the expected behavior would be great to avoid future issues and help Support to understand how this should work.

Thanks.

**Comment by mtambara** [comment]
@achaparro Sure thing, I'll add a test for this change and some basic cases, we can keep adding to it as new scenarios arise

**Comment by achaparro** [comment]
@mtambara I appreciate it, it will really helpful for people working with this in the future.

Thanks!

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9114

**Pull request closed without merging**
