### PR TITLE
[TECHNICAL-SUPPORT] LPS-78980

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@dantewang can you take over this pull? Thanks!

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
@gregory-bretall 
There are several issues for this pull:

1. preparePortlet() should not be called in processEvent(); an event processing is always triggered by an action phase or an earlier event processing. The effect of preparePortlet() of a processAction() should remain in all the processEvent() following the action. Please re-consider the relationship of the portlet request processing phases.
2. This line https://github.com/shuyangzhou/liferay-portal/pull/5871/commits/8406c16984edb8794c97ae31a26dcd463d39643f#diff-317f223d1339f888fb51bcb884d06eccR225 causes a NPE when visiting a newly created `Full Page Application` page.

Also, I think some of the CI failures may actually be revealing issues of this pull.

cc @jonathanmccann @shuyangzhou

**Comment by shuyangzhou** [comment]
Thanks @dantewang !
@gregory-bretall I am closing this pull, please resend through @dantewang .

**Pull request closed without merging**
