### PR TITLE
[Bug Fix]LPS-115438

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result? The unique failures seems not related to this pull.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Confirmed. Test failure are not related.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9253

**Pull request closed without merging**
