### PR TITLE
LPS-53189

### PR DESCRIPTION
**Pull request by topolik**
Hi Shuyang,

can you please verify we didn't hit performance here? There's an new portal-wide filter here 
e809dac

Thank you.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn @tomwang2011 please run a full regression tests, thanks!

**Comment by tomwang2011** [comment]
This pull did not cause any regression towards startup time. Today's baseline is 43.9 seconds and this pull is 43.7 seconds.

**Comment by slnn** [comment]
OK, got it

**Comment by shuyangzhou** [comment]
@slnn did you update our web.xml to include this new filter? See https://github.com/shuyangzhou/liferay-portal/pull/6775/commits/e809dac4451ba00e12b848719f36781ead11e3f7#diff-bbbfb4f238bf5fb99b845be34eff9928R244

**Comment by slnn** [comment]
Hi Shuyang,

I updated our liferay-web.xml to include the new filter when running tests for this PR.

Lily

**Comment by topolik** [comment]
Sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/63321

Thank you all!

**Pull request closed without merging**
