### PR TITLE
LPS-103534 DBInitUtil

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
Please resend with the fix

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80184

**Pull request closed without merging**
