### PR TITLE
LPS-119160

### PR DESCRIPTION
**Pull request by attilabakay**
hi @shuyangzhou,

I got a regression bug in the previous pull and as we talked about it I would like to revert that on the regression LPS and create a new test case to prevent that from happening. I will fix the issue on the original LPS according to the new test case as well.

testCanonicalURLWithFriendlyURL will fail because of the rollback on the LPS as I don't want to rollback a good test case.

previous pulls: #9323 #9330 #9337 #9357

original LPS: https://issues.liferay.com/browse/LPS-118655
Regression bug: https://issues.liferay.com/browse/LPS-119160

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
Hi @shuyangzhou,
I recreated the pull and used the git revert as you asked.
Best,
Attila

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@bakayattila that failure seems caused by your change, please fix and resend. And next time, please remember to trigger the ci tests upon sending the pull to save the time.

**Comment by bakayattila** [comment]
@shuyangzhou  I mentiond it on the pull that test will fail because that test case will be fixed on the original ticket.

**Comment by shuyangzhou** [comment]
@bakayattila  You can not do it this way, CI won't allow the pull to be sent out.

**Pull request closed without merging**
