### PR TITLE
[TS] Lps 133245

### PR DESCRIPTION
**Pull request by JavierMoral**
https://issues.liferay.com/browse/LPS-133245

While updating a group after [LPS-113225](https://issues.liferay.com/browse/LPS-113225), the available languages validation is done at group level which caused a regression when adding new languages when this group does not inherit the locales from the company.

In order to fix this, I added a new method to the Language clases to be able to get the available languages for a specific company by companyId because the methods we have right now like [com.liferay.portal.language.LanguageImpl#isAvailableLocale(java.lang.String)](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L1595) ended up retrieving the company from the CompanyThreadLocal and this caused problems in [LPS-113225](https://issues.liferay.com/browse/LPS-113225)

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:sf

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@JavierMoral please add an integration test for this.

**Comment by shuyangzhou** [comment]
@JavierMoral please add integration test and resend.

**Pull request closed without merging**
