### PR TITLE
LPS-79430 Portlet 3.0: Upgrade to the Servlet 3.1 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jpince: Please verify that this failure is unrelated to this PR and if so, let Shuyang know if it's OK to review. Thanks!

**Comment by jpince** [comment]
@ngriffin7a looks good from a test perspective. Also, in case you were unaware, we are on the verge of updating to Tomcat 9.0 as the default (and release) version in master & 7.1.x. See https://github.com/brianchandotcom/liferay-portal/pull/56914. Not sure if this affects your work.

**Comment by jpince** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@jpince Thanks for the heads up about Tomcat 9.0 (Servlet 4.0). Regardless, Ray said I should keep this PR limited to Servlet 3.1.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56963

**Pull request closed without merging**
