### PR TITLE
[Bug Fix]LPS-110102

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

One known flaw of this fix is we may have unused data in ClassName table, but I do not think it will be a big issue.

Currently ClassName is always populated for each model class, so if you are using a model class, you are totally fine.
If you happen to use ClassName with a customized class (not a model class), you should create upgrade logic to remove it when your logic no longer uses it.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @Preston-Crary, thanks to the discussion with you, I found a more elegant way to fix the ClassName issue.

Tina

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@tinatian can you check whether https://github.com/liferay/liferay-portal/commit/a9e0d341dca111c6f852e2f44745fb03a88e4208 is going be a problem for this change?

**Comment by tinatian** [comment]
@shuyangzhou 
No, I do not think it would be a problem.

The protection I removed in the first commit is that ClassName_ table will not roll back automatically when there is a failure on the transaction, but you can also remove the data in ClassName_ table manually if you want.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9038

**Pull request closed without merging**
