### PR TITLE
LPS-146172 Underlying logic for createDirectories has changed and the directories won't be overwritten, so check if the parent path exists before creating them

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, unsure (again) if I should send you this PR. We found this issue with our docker images that use java11 runtime. Seems there was a change in jdk.nio.zipfs.ZipFileSystem and an error is thrown when creating the directory since it already exists. 

The proposed fix is to check if the parentPath exists, so as not to create the directory again. 

Please let me know what you think or if I should send the PR to someone else.

Thanks as always for the help!

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks to @ZoltanTakacs for figuring out that it was the java version!

**Comment by shuyangzhou** [comment]
@jkappler this does not really make sense, see https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createDirectories(java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...)  . It specifically says ```an exception is not thrown if the directory could not be created because it already exists```
JDK11 should not make this kind of silly mistake, their tck tests would catch it.
But in case this really is the reason, please create an unit test (which assume assert the required jdk version) to show this issue. If it can be confirmed this way, we can use it as a document to apply this workaround, otherwise over time we won't be able to remember and explain why this protecting check is needed.

**Comment by jkappler** [comment]
Will dig deeper and resend. Thanks @shuyangzhou!

**Comment by jkappler** [comment]
Hi @shuyangzhou, I'll fix the issue in another way for now (avoiding adding directories in the zip file) because of time constraints. I'll come back to the zipWritter once I have some time to do so

**Pull request closed without merging**
