### PR TITLE
[License]LPS-122557

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5 ,
Could you please start testing the cluster related features for portal license once it passed on ci?

Thanks.
Tina.

**Comment by vicnate5** [comment]
Testing on this iteration is completed. Only issue found is [repeated console output](https://gist.github.com/vicnate5/06128616eda02508683cfcfbd211e9a7) for max nodes are exceeded, everything else is passing.

**Comment by tinatian** [comment]
@shuyangzhou 
The issue @vicnate5 mentioned is not caused by this pull, it was an old issue exposed by one cluster related test. I will create a new ticket for it, please go ahead to review this first, once it is merged, Amos will start working on the generation part.

Thanks.
Tina

**Comment by shuyangzhou** [comment]
Merged on license repo side, thanks!

**Pull request closed without merging**
