### PR TITLE
Registry api

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 please scan this PR

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9999

**Pull request closed without merging**
