### PR TITLE
LPS-60355 Invalidate cache when adding ResourceBundle

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
Hey @dantewang @slnn, 

could you please run the performance tests on this one?. I think I might have found where I messed it up.

Thank you very much.

**Comment by juangon** [comment]
I would kindly ask to prioritize this ticket, as other critical ticket depends on this one (https://issues.liferay.com/browse/LPS-58355). The latter is needed for JSF portlets to work on Liferay 7. Thanks to everyone!

**Comment by slnn** [comment]
@csierra 
OK, got it , I will rerun this PR  and update the test results as soon as possible.

**Comment by shuyangzhou** [comment]
Close it for now, please resend once you think you get the fix. We can check it again.

**Comment by juangon** [comment]
@shuyangzhou Carlos is waiting for Lily performance tests, this is the fix AFAIK.

**Comment by shuyangzhou** [comment]
@slnn sent the results back already, this did not fix it.

**Comment by juangon** [comment]
Ok, hopefully Carlos can get the profiling ASAP so we can make some progress. Thanks.

**Comment by slnn** [comment]
Finish profile and send to Carlos, hope it helpful.
@csierra @juangon @shuyangzhou 
Thanks

**Pull request closed without merging**
