### PR TITLE
Permission cache

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:bundle

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou The only unique failure here is a startup error on PortalSmoke on Sybase. I have record of the same error from Sept 19 in upstream. It likely something very rare, but please take a quick look if you can.

https://testray.liferay.com/reports/production/logs/test-1-12/1601795303210/test-portal-acceptance-pullrequest(master)/3550/functional-smoke-tomcat90-sybase160-jdk8/0/0/liferay-log.txt.gz

**Comment by vicnate5** [comment]
Previous example from Sept 19
https://testray.liferay.com/reports/production/logs/test-1-21/1600531419922/test-portal-testsuite-upstream(master)/376/functional-smoke-tomcat90-sybase160-jdk8/9/0/liferay-log.txt.gz

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9478

**Pull request closed without merging**
