### PR TITLE
LPS-114513 Update versions files from 1.4 to 1.6.2

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this, it keeps failing.

**Comment by vicnate5** [comment]
Failures were fixed in upstream

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Failures still unrelated. Recommend manual forward.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/89598

**Pull request closed without merging**
