### PR TITLE
Lps 118633

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou the failure is a random rare fluke, you can manually forward this

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/92456

Thanks @kyle-miho !

**Pull request closed without merging**
