### PR TITLE
Ccpp ri extract

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by vicnate5** [comment]
@shuyangzhou The TCK test doesn't seem to be running (neither here nor upstream) I will need to look into this.

The rest of the test results show no regressions.

**Comment by shuyangzhou** [comment]
Ok, thanks @vicnate5 ! I will wait for you to get the TCK working, if anything can cover this usage, it must be the tck tests.

**Comment by vicnate5** [comment]
ci:test:tck:nocompile

**Comment by vicnate5** [comment]
@shuyangzhou CI sent a possible fix to run the TCK tests, I am trying to run them locally, but so far it is a lot of failures (even against master upstream), so I am not sure I am gonna get helpful results and it is taking a long time to run...

I expect we won't be able to get results until tomorrow.

**Comment by shuyangzhou** [comment]
ok, that's fine, I can wait, thanks @vicnate5 !

**Comment by vicnate5** [comment]
ci:test:tck:nocompile

**Comment by vicnate5** [comment]
@shuyangzhou Able to run some of the TCK tests but the selenium-based TCK tests are all failing. Because these tests have not been silently failing to run for a long time, I will need more time to debug them locally.

The TCK unit tests that did run are all passing both upstream and on this PR.

If this can wait until next week, I can work on the selenium tests and try to fix them before we merge, otherwise we can take the risk based on the Unit tests passing.

**Comment by vicnate5** [comment]
@shuyangzhou I was able to run the all the TCK tests locally on master and on this PR

No regressions found in TCK tests.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112489

**Pull request closed without merging**
