### PR TITLE
LPS-91772 Tags

### PR DESCRIPTION
**Pull request by Preston-Crary**
It's very likely SF will fail after rebase. Two new tags were added today, and we'll care even if a new attribute is added.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Preston-Crary this looks real?

**Comment by Preston-Crary** [comment]
@shuyangzhou yes, we have a private module using the servletContext attribute that I removed.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7532

**Pull request closed without merging**
