### PR TITLE
LPS-73908 traces showing which node is executing jobs makes easier to decipher scheduler problems.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please take this over

**Comment by almonwork** [comment]
Hi @tinatian , @shuyangzhou 

Has this PR advanced during the last week? We have a customer waiting.

Regards
  Alberto

**Comment by tinatian** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4658

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/50800

**Pull request closed without merging**
