### PR TITLE
Upgrade dm 11

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou 
The hypersonic setup wizard issue is still reproducible. 

It is NOT caused by the duplicate browser launching (cannot reproduce with custom test: https://github.com/vicnate5/liferay-portal/pull/1273)

However, on this pull I get a WARN on startup ONLY on Hypersonic setup wizard tests: `WARN  [main][ReleaseLocalServiceImpl:238] user lacks privilege or object not found: RELEASE_`
It does not occur on every run.

**Comment by vicnate5** [comment]
ci:test:bundle

**Pull request closed without merging**
