### PR TITLE
LPS-106123 - batch-engine-service - Update service gtracker filter to track BatchEngineTaskItemDelegate impls either by property “batch.engine.task.item.delegate” or by interfcae itself

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

cc @nhpatt

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ivicac can you explain why this is needed? Inside BatchEngineTaskMethodServiceTrackerCustomizer, all service objects are expected to be BatchEngineTaskItemDelegate type. When will you have a service that is type of BatchEngineTaskItemDelegate, but not registered under that type?

**Comment by ivicac** [comment]
@shuyangzhou 
Brian doesn't allow to expose generated *ResourceImpls as BatchEngineTaskItemDelegate, something like:

@Component(
	properties = "OSGI-INF/liferay/rest/v1_0/blog-posting.properties",
	scope = ServiceScope.PROTOTYPE, service = {BlogPostingResource.class, BatchEngineTaskItemDelegate.class}
)
public class BlogPostingResourceImpl
	extends BaseBlogPostingResourceImpl implements EntityModelResource {
......

because  *ResourceImp,s are generated only once, and he doesn't want to touch those files anymore, for any change.

That is why @shuyangzhou will generate the above property, that can be tracked in *properties file(that is constantly regenerated).

The truth is that, yes, all service objects are expected to be BatchEngineTaskItemDelegate type.

**Comment by shuyangzhou** [comment]
@ivicac I don't see where BlogPostingResourceImpl is made BatchEngineTaskItemDelegate. Is this change made yet?
This is a very risky behavior, by not tracking the exact type of the service, we are no longer type safe. The change in this pull does not make sense to me, if there is just part of a bigger change, please include the whole thing so that I can understand it in a better way.

**Comment by ivicac** [comment]
@shuyangzhou I know that it doesn't make sense but the issue is that Brian doesn't want to touch *ResourceImpl classes once they are generated because you can after initial generation activate batch part and that means a ResourceImpl class should be touched and added as part of @Component annotation.

Here is the PR made by @nhpatt that includes REst Builder changes: https://github.com/brianchandotcom/liferay-portal/pull/84275

Do you have a maybe better idea of how to overcome this issue?

Thank you

**Comment by shuyangzhou** [comment]
@ivicac this is not about Brian's preference, but about correctness, you said "all service objects are expected to be BatchEngineTaskItemDelegate type", but in your example, BlogPostingResourceImpl is not BatchEngineTaskItemDelegate. At runtime you will get class cast exception.

**Comment by ivicac** [comment]
@shuyangzhou BatchEngineTaskItemDelegate  will be implemented by *BaseResourcImpl, so any ResourceImpl generated by REST builder will be BatchEngineTaskItemDelegate also.

For me, there is no reason to use any property, it is enough to expose any ResourceImpl as a BatchEngineTaskItemDelegate, too but we don't know how if Javier is not allowed to add it inside @Component definition

**Comment by ivicac** [comment]
Right now everything is working even without that property that should be used only by REST builder

**Comment by shuyangzhou** [comment]
@ivicac Then this change needs to wait until "BatchEngineTaskItemDelegate will be implemented by *BaseResourcImpl," is done, otherwise it will break things for sure. Please send that change first, then this after.

**Comment by ivicac** [comment]
@shuyangzhou ,ok, the PR created by @nhpatt needs to be merged first.

**Comment by nhpatt** [comment]
Ok, will send it! :)

**Pull request closed without merging**
