### PR TITLE
[Log4j]LPS-118542

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
The goal of this pull is to check the configuration in portal-log4j.xml, making it clear what would be changed if we upgrade to log4j.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please verify if the unique failure is real?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Test failures not related.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9739

**Pull request closed without merging**
