### PR TITLE
LPS-139811 When a MessageBus message is resent, it can result in a NPE

### PR DESCRIPTION
**Pull request by rotty3000**
Signed-off-by: Raymond Augé <raymond.auge@liferay.com>

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rotty3000 can you paste the NPE stack? What is null when the failure happens? From the change I can only see you add a check for the cast, not sure how this is preventing NPE?

**Comment by rotty3000** [comment]
Apologies @shuyangzhou, it was a `ClassCastException` (I've updated the ticket with the exception as well).

```
2021-09-29 13:54:00.011 WARN  [PersistedQuartzSchedulerEngineInstance_Worker-1][LiferayJSONDeserializationWhitelist:50] Unable to deserialize com.liferay.portal.kernel.util.TransientValue due to security restrictions
Exception in thread "antivirus_destination-2" java.lang.ClassCastException: java.util.HashMap cannot be cast to com.liferay.portal.kernel.security.permission.PermissionChecker
	at com.liferay.portal.messaging.internal.MessageBusThreadLocalUtil.populateThreadLocalsFromMessage(MessageBusThreadLocalUtil.java:109)
	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10327

**Pull request closed without merging**
