### PR TITLE
LPS-109118: Fix tests that were setting _workflowHandlerMap (now removed) directly.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

Please remember to trigger a test right after you send the pull to save waiting time.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@marianoalvarosaiz @shuyangzhou Unique backend tests failures here

Unit
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/376771/

Integration
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/367910/#showFailuresLink

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz please fix and resend. And remember to trigger the ci test right after you send the pull to avoid wasting time waiting.

**Pull request closed without merging**
