### PR TITLE
LPS-64078 PortalImpl.removeRedirectParameter

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Same exact tests that failed on my other unrelated pull.

**Comment by shuyangzhou** [comment]
That's not right, I had that test fixed this morning.

ci:retest

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/d8bb971bc0...91135b913d

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/2678

**Pull request closed without merging**
