### PR TITLE
[Bug Fix]LPS-107979

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is going to fix the random shutdown error of sidecar.

FYI @arboliveira @vicnate5.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
**Test Analysis of https://github.com/shuyangzhou/liferay-portal/pull/8787**
- [LRQA-55520](https://issues.liferay.com/browse/LRQA-55520) / [LRQA-55521](https://issues.liferay.com/browse/LRQA-55521) Elasticsearch / Solr functional tests need test infrastructure improvements. Search functional test failures are related to this.
- [LPS-104802](https://issues.liferay.com/browse/LPS-104802) com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest.testGetContentStructureStructuredContentsPageWithFilterStringEquals failed with Elasticsearch circuit breaker exception. Search team still discussing fix.
- [LPS-107520](https://issues.liferay.com/browse/LPS-107520) Known comparison failure in AssetTagNamesMultiLanguageSearchTest

**Comment by shuyangzhou** [comment]
@xbrianlee do you mean I need to wait for something before merging this?

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
@xbrianlee Could you please scan the result?

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @vicnate5,
Please help me scan the test result.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Reviewed test results for relevant, no unique issues.

Search team is logging analysis for search suite results here: https://docs.google.com/document/d/194J3bw6Z6mmck5dzIZHh1YoCBeaQTBengykSg0_p9q8/edit
CC @xbrianlee

**Comment by xbrianlee** [comment]
@tinatian No unique failures. See [this doc](https://docs.google.com/document/d/194J3bw6Z6mmck5dzIZHh1YoCBeaQTBengykSg0_p9q8/edit#) for details.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

**Comment by tinatian** [comment]
Hi @shuyangzhou ,
I tried with component enable/disable, it is not work cause the enable/disable component is async, but here I need a sync invoking. 
see https://osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/component/ComponentContext.html#enableComponent-java.lang.String-.

Tina.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/8863.

**Pull request closed without merging**
