### PR TITLE
LPS-108590 DB Partition: set companyThreadLocal anytime we iterate companies

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

After some time I was able to move the code to the service layer per your request. Also, I removed unused methods.

I am almost sure that this pull passes all CI tests but it's difficult to know because it modifies the whole portal and we have a lot issues in the CI right now. I am also talking to @vicnate5 to see this.

Can you take a look at the pull?

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@achaparro @shuyangzhou Based on pull results here https://github.com/achaparro/liferay-portal/pull/849, and the fact that the same commits are here, there are no unique failures, everything is already occuring upstream

**Comment by shuyangzhou** [comment]
@achaparro https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=17,label_exp=!master/324007//testReport/com.liferay.journal.service.test/JournalArticleExpirationTest/testExpireApprovedArticle is a real failure, caused by this pull.

**Comment by shuyangzhou** [comment]
See fix at https://github.com/shuyangzhou/liferay-portal/pull/9830/commits/1ff505ee9f0c07d0c9b15323f968ef5c85574021

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99606

**Pull request closed without merging**
