### PR TITLE
[FinderCache]LPS-115420

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

To make this pull smaller, I did not do too much clean up for FinderPath, will do it in another pull.

@GinsonRen Please run a diff on main env, please run the 2 test cases you see 2% regression first if you can not finish them all by end of your day.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by GinsonRen** [comment]
Hi @tinatian , I re-run this on main environment, **wiki** still have -2.15%, and -1.9% second time. Here is the result:

### **Wiki:**
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 15322 | 237 | 453 | -
PR-9167 | - | 14992 | 278 | 494 | **-2.15%**
PR-9167 | - | 15031 | 241 | 458 | **-1.90%**

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 44,492 | 283 | 82.8 | -
PR-9167 | - | 44060 | 270 | 79.6 | -0.97%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 55,250 | 496 | 150 | -
PR-9167 | - | 54468 | 580 | 180 | -1.42%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 16782 | 27.5 | 75.1 | -
PR-9167 | - | 16758 | 42.1 | 73.6 | -0.14%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 14,655 | 843 | 595 | -
PR-9167 | - | 14558 | 680 | 530 | -0.66%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 25,318 | 241 | 335 | -
PR-9167 | - | 25015 | 194 | 298 | -1.20%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 25,289 | 426 | 178 | -
PR-9167 | - | 24969 | 410 | 174 | -1.27%

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9171

**Pull request closed without merging**
