### PR TITLE
LPS-158039 All BaseAuthVerifierPipelineConfigurator subclass should b…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…e required for configuration, because BaseAuthVerifierPipelineConfigurator.activate() has a properties level enabled checking.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reevaluate:1317401_4117

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?

**Comment by Kvale1733** [comment]
Yes I'll check it.

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120271

**Pull request closed without merging**
