### PR TITLE
LPS-77306 Portlet 3.0: Remove deprecated methods and classes in package com.liferay.portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jpince: I fixed the SF problem in the previous PR. Please let me know if I need to run ci:test again or if Shuyang can simply review at this point.

**Comment by ngriffin7a** [comment]
ci:test:sf

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: SF tests passed. Please review and let us know if Shuyang can review.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou please review

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57102

**Pull request closed without merging**
