### PR TITLE
LPS-74595

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir, can you help me out here?
CI saying `Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.0.0,8.0.0)"`, but I can't find that one anywhere...

**Comment by Ithildir** [comment]
Hi @hhuijser!
I'm sorry, I was on PTO 😞 Do you still have problems with this?

**Comment by hhuijser** [comment]
@Ithildir, no worries, not urgent at all. Hope you had a good time off!
Never got to looking into this more. Guess it's still a problem.

**Comment by Ithildir** [comment]
Hi @hhuijser,
If I understand correctly, your pull causes a major increase in the `com.liferay.portal.kernel.util` package. So I think you have to change the version of the `com.liferay.portal.kernel` dependency to `default`, for all the modules that use that package.

**Pull request closed without merging**
