### PR TITLE
Lps 172191

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128420

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by Kvale1733** [comment]
@shuyangzhou "unknown column" errors after upgrade. Similar errors seen with 6.2.10.21 , 7.0.10.6, 7.3.10 database dumps.

Steps to reproduce:
      i. Import the following 6.2.10.21 dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip
      ii. Start the upgrade process with the upgrade tool
      
      
Expected results: No issue with upgrade
Actual results:
```
 [java] 2023-01-05 18:02:24.682 INFO  [main][ModuleFrameworkImpl:281] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
     [java] 2023-01-05 18:02:30.886 ERROR [main][SqlExceptionHelper:142] Unknown column 'resourceac0_.mvccVersion' in 'field list'
     [java] 2023-01-05 18:02:30.901 ERROR [main][PortletConfigurationExtender:78] Unable to read resource actions config in resource.actions.configs
     [java] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
     [java] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:648) ~[portal-kernel.jar:?]
```
```
[java] 2023-01-05 18:02:32.267 ERROR [main][SqlExceptionHelper:142] Unknown column 'companyimp0_.mvccVersion' in 'field list'
     [java] 2023-01-05 18:02:32.270 ERROR [main][ElasticsearchSearchEngine:56] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.66 (178)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(307)] : The activate method has thrown an exception
     [java] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
     [java] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:648) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.service.persistence.impl.CompanyPersistenceImpl.findAll(CompanyPersistenceImpl.java:1246) ~[portal-impl.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7749/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

reproduced twice locally with those steps and the test is passing consistently on other CI runs so it does look related to this PR.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
I'll review the results when posted.

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128456

**Pull request closed without merging**
