### PR TITLE
LPS-78194 Remove support for WSRP

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak: This PR simply contains simple deletions from the codebase related to WSRP. I can't see how it would cause any failures in unit-jdk8. Please verify that this is the case. Thanks.

**Comment by ngriffin7a** [comment]
@timpak: Please review the test results and if the failures are not caused by this PR then please let us know so that Shuyang can review. Again, this PR simply contains simple deletions from the codebase related to WSRP. I can't see how it would cause any failures in unit-jdk8. Thanks.

**Comment by timpak** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@ngriffin7a I think we should clean up the remoteable method/parameter in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/PortletImpl.java , https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/model/Portlet.java and https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/model/PortletWrapper.java

**Comment by shuyangzhou** [comment]
Please clean them up and resend, thanks @ngriffin7a !

**Comment by ngriffin7a** [comment]
Done and squashed into one commit, see: https://github.com/shuyangzhou/liferay-portal/pull/6048

**Pull request closed without merging**
