### PR TITLE
LPS-86709 Develop the bean portlet Spring extension (REBASED)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou I rebased your shuyangzhou:LPS-86709-3 branch with master so that it now has the fix for LPS-106072 as well as all your code review commits for LPS-86709. Sending this rebased branch back to you per your request.

Please review when you can and let me know if you have any questions. Thanks, Neil

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:test:tck

**Comment by ngriffin7a** [comment]
@shuyangzhou TCK tests are passing. Please review when you can. Thank you!

**Comment by vicnate5** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@vicnate5 Please let me know if things are still good after the most recent run of `ci:test`. The commits in this branch should only affect the TCK -- nothing else in the system.

**Comment by koor4356** [comment]
@ngriffin7a @shuyangzhou @vicnate5 
This test failure looks suspicious. If it is not related, then it is good. Thanks!
`Error Message
java.lang.AssertionError: Detected split packages {name=javax.ws.rs.container, version=2.1} in org.apache.aries.javax.jax.rs-api_1.0.4 [51] and org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec_1.1.0 [237]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.liferay.portal.split.packages.test.SplitPackagesTest._processSplitPackages(SplitPackagesTest.java:158)
	at com.liferay.portal.split.packages.test.SplitPackagesTest.testSplitPackages(SplitPackagesTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
	at java.lang.Thread.run(Thread.java:745)
Stacktrace
java.lang.AssertionError: Detected split packages {name=javax.ws.rs.container, version=2.1} in org.apache.aries.javax.jax.rs-api_1.0.4 [51] and org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec_1.1.0 [237]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.liferay.portal.split.packages.test.SplitPackagesTest._processSplitPackages(SplitPackagesTest.java:158)
	at com.liferay.portal.split.packages.test.SplitPackagesTest.testSplitPackages(SplitPackagesTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@ngriffin7a This integration test failure is consistent and unique to this PR, I could not tell you how it is related though
SplitPackagesTest.testSplitPackages
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/351649/AXIS_VARIABLE=31,label_exp=!master/testReport/junit/com.liferay.portal.split.packages.test/SplitPackagesTest/testSplitPackages/

**Comment by ngriffin7a** [comment]
@koor4356 @vicnate5 I know how to fix the split packages problem -- it's just a small one-line change to a dependency in a build.gradle file. I'll rebase, fix, and send a follow-up PR shortly.

**Pull request closed without merging**
