### PR TITLE
Lps 140390

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@shuyangzhou Can you check the Upgrade results here? I already confirmed the rest of the results are good.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check the Upgrade results here? I already confirmed the rest of the results are good.

**Comment by vicnate5** [comment]
@zhangyan0701 The backend results are also new, seems we had a lot of Oracle failures, which is the risk area for this PR. Can you check that too?

**Comment by zhangyan0701** [comment]
The upgrade test failures are unrelated.

But in the backend results, the fragment and search integration tests failed on Oracle 19.3 with error like below:
```
     [exec] com.liferay.portal.search.internal.test.IndexerRegistryImplTest > classMethod FAILED
     [exec]     java.io.IOException: Broken pipe
     [exec]         at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
     [exec]         at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
     [exec]         at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
     [exec]         at sun.nio.ch.IOUtil.write(IOUtil.java:65)
     [exec]         at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
     [exec]         at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
     [exec]         at java.nio.channels.Channels.writeFully(Channels.java:98)
     [exec]         at java.nio.channels.Channels.access$000(Channels.java:61)
     [exec]         at java.nio.channels.Channels$1.write(Channels.java:174)
     [exec]         at java.io.ObjectOutputStream$BlockDataOutputStream.writeBlockHeader(ObjectOutputStream.java:1894)
     [exec]         at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1875)
     [exec]         at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1822)
     [exec]         at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.SocketState.writeUTF(SocketState.java:125)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.ClientState$1.execute(ClientState.java:127)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:123)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

Example Testray links:
[com.liferay.fragment.util.test.FragmentEntryConfigurationParserTest](https://testray.liferay.com/home/-/testray/case_results/1580758389)
Jenkins console: https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/926/modules-integration-oracle193-jdk8/0/23/jenkins-console.txt.gz

[com.liferay.portal.search.significance.test.SignificanceHeuristicsInstantiationTest](https://testray.liferay.com/home/-/testray/case_results/1580758988)
Jenkins console: https://testray.liferay.com/reports/production/logs/2021-11/test-1-2/test-portal-acceptance-pullrequest(master)/926/modules-integration-oracle193-jdk8/1/13/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
Those search issues are ci running out of memory:
```

     [exec] #
     [exec] # There is insufficient memory for the Java Runtime Environment to continue.
     [exec] # Native memory allocation (mmap) failed to map 571928576 bytes for committing reserved memory.
     [exec] # An error report file with more information is saved as:
     [exec] # /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.53/bin/hs_err_pid7568.log
```
It has nothing to do with this change.

@vicnate5 can we proceed?

**Comment by vicnate5** [comment]
@shuyangzhou I checked the tests that didn't go OOM and this looks good. We can proceed.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 @zhangyan0701 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110115

**Pull request closed without merging**
