### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on brianchandotcom#83887.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Random shutdown error when cluster is enabled, see https://gist.github.com/tinatian/6f3f1bec6a28b3fda6ec226714bf3fb8.
2. Dumping log4j.properties into temp folder
3.Clean up the configuration file, remove unused properties
4. Shutdownhook may not work for some cases on windows.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5 @joshchong,
Could you please take a look at the failed tests? I think we still have some failures caused by test logic /config itself.

Tina.

**Comment by vicnate5** [comment]
I am looking into the issues with the non-Tomcat app servers first.

**Comment by vicnate5** [comment]
@tinatian See Weblogic and Websphere issues on https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?ts=5e320f5d#gid=771578883&range=K8

I have a workaround on CI for the app servers (https://github.com/vicnate5/liferay-portal/pull/1399/commits/de01f7a5cbfc630e4cc3d881e364ee5be158a419), but I need to look into a better solution. The CI scripts should distribute the sidecar instead of re-downloading every time.

**Comment by vicnate5** [comment]
@tinatian This breaks startup if there is a `(space)` in the portal path
```
ERROR [main][Sidecar:177] Unable to start sidecar process
 java.net.URISyntaxException: Illegal character in path at index 48: file:/opt/dev/projects/github/liferay-portal/bun dles/osgi/state/org.eclipse.osgi/107/0/bundleFile
```
Full log (big): https://testray.liferay.com/reports/production/logs/test-1-11/1580252616150/test-portal-acceptance-pullrequest(master)/6289/portal-startup-space-in-path-jdk8/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
@xbrianlee @joshchong Can you guys look at the search test failures?

**Comment by tinatian** [comment]
Fix IBM JDK issue and space in portal path, see https://github.com/shuyangzhou/liferay-portal/pull/8787.

**Pull request closed without merging**
