### PR TITLE
LPS-117403 Unify the upgrade logic in one single method which is called from auto-upgrade and upgrade tool

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@shuyangzhou the test passed yesterday but I have updated the pull with the change suggested by Brian and latest changes from master

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@achaparro I am ok with everything in this pull, except https://github.com/shuyangzhou/liferay-portal/pull/9283/commits/a059c45b6498beb8f10777ab2260fa3c7afce1aa . Can you put some explanation for it? What is this for? Who is using it, why we can not force the actual user to depend on it? We should avoid unused Reference whenever possible.

**Comment by achaparro** [comment]
Hi @shuyangzhou,

I made those changes to be sure that the class _SettingsLocatorHelperImpl_ is ready when those components are started up, otherwise, we will get an exception here:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/settings/SettingsLocatorHelperUtil.java#L55

But it's true that I need those changes for an initial version of my changes where didn't register the events properly. I wasn't sure if we needed them, in fact I tested the pull without them:
https://github.com/achaparro/liferay-portal/pull/660

And I got some errors but after analyzing them now, all of them are related to the lack of this commit which I already removed for that test:
https://github.com/shuyangzhou/liferay-portal/pull/9283/commits/4a9e65fcfc6a975a4306c9b2134e6f3e5e4aeba3

So, and to summarize, you are right, we can remove https://github.com/shuyangzhou/liferay-portal/commit/a059c45b6498beb8f10777ab2260fa3c7afce1aa I will send a new pull with that.

Thanks!

**Comment by achaparro** [comment]
@shuyangzhou see https://github.com/shuyangzhou/liferay-portal/pull/9288

**Pull request closed without merging**
