### PR TITLE
LPS-92017 DDMStructure deep copy

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @linolaoj,

Could you please verify this pull?

cc @vicnate5 

Thanks!
Tina

**Comment by tinatian** [comment]
Hi @vicnate5 ,
Could you please check if there is any real failure with this pull?

Thanks.
Tina.

**Comment by linolaoj** [comment]
Hi @tinatian, it looks good to me.
Thanks!

**Comment by vicnate5** [comment]
@tinatian looks good, there is an SSO regression at head causing most of the failures.

**Comment by tinatian** [comment]
Thanks @linolaoj and @vicnate5 !

@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69540

**Pull request closed without merging**
