### PR TITLE
LRQA-41120 Futureproof expected log

### PR DESCRIPTION
**Pull request by mtambara**
@jpince

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by jpince** [comment]
ci:reopen semver failure resolved by https://github.com/liferay/liferay-portal/commit/c5dd065e53f50ae5644e7504e7b879e7222c7bab

**Comment by jpince** [comment]
@mtambara thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63860

**Pull request closed without merging**
