### PR TITLE
LPS-79168 Remove spring AOP usages from staging-spring.xml

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I tested this locally and it worked. Let's wait for CI result to see if it breaks anything.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian The failures are real.

**Comment by tinatian** [comment]
@shuyangzhou The fix we talked about this afternoon does not work since LayoutLocalServiceHelper is also using BeanReference.
I think we may need to fix this by restricting the order of spring bean post processor. I will take a deep look into it tomorrow.

Tina.

**Comment by tinatian** [comment]
@shuyangzhou i think I can try to load it at runtime, will send you a pull later

**Pull request closed without merging**
