### PR TITLE
LPS-79121 Remove spring AOP in workflow-spring.xml

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is to remove aop config in workflow-spring.xml. I tested it locally, it works. Let's wait for CI result to see if it breaks any logic.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian can you also update all spring xml to remove the aop headers, which are 
1) "xmlns:aop="http://www.springframework.org/schema/aop""
2) "http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd"
Basically not only I want to remove exist usages, I want to make sure people won't be able to add them back.

**Comment by tinatian** [comment]
Sure, sorry that I forgot it.

**Comment by tinatian** [comment]
@shuyangzhou  Updated this pull, now only staging-spring.xml has aop headers right now, will remove it once I get rid of the usages.
Do you want to add a restriction to source formatter about it? or we add a test to make sure no one will add it back?

**Comment by shuyangzhou** [comment]
Not yet, we need to get the alternative aop framework in place first, before we can SF enforce it. For now, just making it hard to be added back is good enough.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@tinatian please fix it on top of https://github.com/shuyangzhou/liferay-portal/pull/5886

**Comment by shuyangzhou** [comment]
@tinatina it is the :
```
	<bean class="com.liferay.portal.spring.aop.DynamicProxyCreator$Register">
		<constructor-arg>
			<bean class="com.liferay.portal.messaging.proxy.MessagingProxyBeanMatcher">
				<property name="beanClass" value="com.liferay.portal.kernel.messaging.proxy.BaseProxyBean" />
				<property name="beanNamePattern" value="com.liferay.portal.workflow.*ProxyBean" />
			</bean>
		</constructor-arg>
		<constructor-arg>
			<bean class="com.liferay.portal.kernel.messaging.proxy.MessagingProxyInvocationHandler" factory-method="getInvocationHandlerFactory" />
		</constructor-arg>
	</bean>
```
section causing the issue, let's convert that one into regular wrappers first. Make sure that works fine, then redo this, and make sure to read the commits from my the other pull to add in the changes I did.

**Pull request closed without merging**
