### PR TITLE
LPS-80613 PortletResponse.getCacheControl().getExpirationTime() does not contain the value configured in portlet.xml expiration-cache

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak: These failures seem like JSP compile failures that are unrelated to the small Java source change I made in the 1 commit for this PR. Is there a problem upstream? Should I run ci:retest? Thanks.

**Comment by timpak** [comment]
@ngriffin7a yes, there's currently a compile failure in upstream. i'll let you know when it's been resolved.

**Comment by timpak** [comment]
@ngriffin7a the compile failures should be resolved as of [496c0bb](https://github.com/liferay/liferay-portal/commit/496c0bb7bf5cb1139e99e6dec1d63a33beb7bcf4)

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@timpak: These failures seems unrelated. Please take a look when you get a chance so that Shuyang can review. Thanks.

**Comment by timpak** [comment]
ci:test:relevant

**Comment by timpak** [comment]
hey @ngriffin7a yeah, the tcserver failure looks non-related. running relevant tests just in case.

**Comment by timpak** [comment]
@ngriffin7a looks good. Moving forward, please contact @jpince if you need help as I will no longer be available. 

@shuyangzhou please review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58283

**Pull request closed without merging**
