### PR TITLE
LPS-172584 Fix broken ObjectResourceBundle parent delegation

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Kvale1733** [comment]
@shuyangzhou Verified the fix locally just waiting for relevant results.

**Comment by Kvale1733** [comment]
No regressions found. Manually forwarding.

**Comment by Kvale1733** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/128632

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
