### PR TITLE
[TS] LPS-108139 Return with appropriate status codes

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan the result, thanks!

**Comment by kyle-miho** [comment]
no unique functional test failures, no integration tests failed, pr should be good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84340

**Pull request closed without merging**
