### PR TITLE
[Bug Fix]LPS-105126 Sybase | master

### PR DESCRIPTION
**Pull request by vicnate5**
New revert commit to enable Sybase functional upgrades, should be safe to add now that https://issues.liferay.com/browse/LPS-95571 fixes are in progress

CC @tinatian @SamZiemer

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
This may still be blocked from getting Sybase functional results by LPS-95571

**Comment by vicnate5** [comment]
Sybase upgrade tests blocked on CI by https://issues.liferay.com/browse/LRCI-842

**Comment by vicnate5** [comment]
Sybase integration tests failed to run on this PR, but they did run on the previous PR (same code) https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/207982/

**Comment by shuyangzhou** [comment]
@vicnate5 so this pull is good?

**Comment by vicnate5** [comment]
@shuyangzhou This is good as far as we can test right now. Checked regular CI results on https://github.com/tinatian/liferay-portal/pull/1618#issuecomment-559799882.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81661

**Pull request closed without merging**
