### PR TITLE
LPS-103019 Remove spring wiring for ***Util Part 1

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please note that each change is using a different ticket number. This is part of it, will send more pulls later.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou 
I think we still need this. cause the impl will be registered as an osgi service, and it is possible that people publish one with higher ranking, and all modules can see the higher ranking one, but not these ***Util cause it is static wiring set by spring.

Tina.

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Commented on the ticket, we are not doing this, since it is not possible to apply it system wide, and we have no easy way to draw line to decide which spring beans should be changed. Customer should override core spring bean in the old ext-spring.xml way, rather that osgi service swapping.

**Pull request closed without merging**
