### PR TITLE
Startup optimization 60 default layout prototypes util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 what other tests do you think we need? This could affect search, staging and site template.

**Comment by vicnate5** [comment]
ci:test:staging

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@Kvale1733 can you check the results here?

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:staging

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@Kvale1733 @vicnate5 pushed a fix and rerunning the tests, please help me watch out the results, thanks!

**Pull request closed without merging**
