### PR TITLE
LPS-X Use DataOutput/InputStream to reduce Serialization/Deserializat…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ion overhead.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 do you think this needs more tests? It affects frontend-js-loader-modules-extender

**Comment by vicnate5** [comment]
ci:test:frontend

**Comment by vicnate5** [comment]
@shuyangzhou Looks good.

**Pull request closed without merging**
