### PR TITLE
[TECH SUPPORT] LPS-71278

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-71278

Avoid blocked threads when having a lot of concurrent XML parsing using com.liferay.portal.xml.SAXReaderImpl.read

- **java.lang.Thread.State: BLOCKED (on object monitor) at java.util.zip.ZipFile.getEntry(ZipFile.java:304)**

This blocked thread is caused because XMLParserConfiguration configuration is searched in classpath each time SAXParser object is created, but default XIncludeAwareParserConfiguration is used as we don't have configuration file at JAR level.
Solved in commit https://github.com/shuyangzhou/liferay-portal/pull/3971/commits/7f3b5f7414f6360d609dd151320ab55bb6266e84
To avoid this issue, we configure default parser in `system.properties` level to avoid extra classpath lookup.

- **java.lang.Thread.State: BLOCKED (on object monitor) at java.util.Collections$SynchronizedMap.get(Collections.java:2037)**

Dom4j can not scale well under heavy concurrent load because a synchronized weakhashmap is used in QNameCache class.
Solved in commit https://github.com/shuyangzhou/liferay-portal/pull/3971/commits/6d3a7496263a94144469a9ef81da3fc3ea3a73c3 , to avoid this blocked thread, I am changing the synchronized map to threadlocal map inside `dom4j.jar` third party library.
Applied same solution than workaround explained in https://issues.liferay.com/browse/LPS-7427

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tinatian please take it over, this does not have to be a third party patch, it can be configured to use our own DocumentFactory to provide a different QNameCache.

**Comment by tinatian** [comment]
@jorgediaz-lr Your fist commit(setting "org.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeAwareParserConfiguration" to system.properties) makes source-formatter broken.

If you have to set the value here, could you please check with Hugo how to fix this?

Thanks.

You can reproduce it by :
1) Run "ant all" with your change
2) Modify any file which can need to be formated
3) Go to portal-impl, and run "ant format-source-local-changes"
4) You will see errors like this:

liferay@liferay-Precision-5510 /home/trunks/liferay-portal/portal-impl $ ant format-source-local-changes -
Buildfile: /home/trunks/liferay-portal/portal-impl/build.xml

format-source-local-changes:

format-source:
     [java] Listening for transport dt_socket at address: 8000
     [java] Loading file:/home/trunks/liferay-portal/portal-impl/classes/system.properties
     [java] Listening for transport dt_socket at address: 8000
     [java] /home/trunks/liferay-portal/portal-impl/src/com/liferay/counter/model/CounterHolder.java
     [java] Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.xerces.parsers.XML11Configuration.getFeature0(Ljava/lang/String;)Z
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:246)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:183)
     [java] Caused by: java.lang.NoSuchMethodError: org.apache.xerces.parsers.XML11Configuration.getFeature0(Ljava/lang/String;)Z
     [java] 	at org.apache.xerces.parsers.XIncludeAwareParserConfiguration.getFeature(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.reset(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
     [java] 	at com.puppycrawl.tools.checkstyle.api.AbstractLoader.parseInputSource(AbstractLoader.java:99)
     [java] 	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:144)
     [java] 	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:128)
     [java] 	at com.liferay.source.formatter.checkstyle.util.CheckStyleUtil._getChecker(CheckStyleUtil.java:75)
     [java] 	at com.liferay.source.formatter.checkstyle.util.CheckStyleUtil.process(CheckStyleUtil.java:56)
     [java] 	at com.liferay.source.formatter.JavaSourceProcessor.processCheckStyle(JavaSourceProcessor.java:2040)
     [java] 	at com.liferay.source.formatter.JavaSourceProcessor.postFormat(JavaSourceProcessor.java:2011)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:146)
     [java] 	at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:474)
     [java] 	at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:53)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:232)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:228)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 34 seconds

**Comment by shuyangzhou** [comment]
@jorgediaz-lr I am closing this one, please resend with SF fix to @tinatian, she will try to make it not using patch.

**Comment by jorgediaz-lr** [comment]
Resent to @tinatian see: https://github.com/tinatian/liferay-portal/pull/515

**Pull request closed without merging**
