### PR TITLE
[TS] LPS-101642 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
References:
https://issues.liferay.com/browse/LPS-101642
shuyangzhou#9155
shuyangzhou#10243

Hi @shuyangzhou
As you asked for, I have added a test to the PR avoiding to deploy the test bundle as a file.

Regards,
Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
Hello, @shuyangzhou 

Could you take a look to the PR?

Regards,
 Sergio.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10281

**Pull request closed without merging**
