### PR TITLE
LPS-56638

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @shuyangzhou 

So now at least the tests are failing because of the StackOverflowError.
Unfortunately, we can't really see from the stack trace, which regex is causing this and I can't reproduce on my machine.

I'll dig into this a bit more tomorrow.

**Comment by shuyangzhou** [comment]
Try manually shrink the Xss size locally, that should expose the issue.

**Pull request closed without merging**
