### PR TITLE
Startup optimization 312 quartz schema manager

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
There is a failure in test [LocalFile.UpgradeLifecycle#UpgradeProcessAndVerifyProcessDoNotRunOnStaleDB](https://testray.liferay.com/home/-/testray/cases/2412637312) seems to be an issue.

The upgradeProcess `com.liferay.portal.scheduler.quartz.internal.upgrade.schema.SchemaCreationUpgradeProcess` is executed even when start Portal with a fresh database.

Console output:
```
2023-10-13 00:48:48.386 INFO  [main][UpgradeProcess:118] Upgrading com.liferay.portal.scheduler.quartz.internal.upgrade.schema.SchemaCreationUpgradeProcess
2023-10-13 00:48:49.327 INFO  [main][UpgradeProcess:136] Completed upgrade process com.liferay.portal.scheduler.quartz.internal.upgrade.schema.SchemaCreationUpgradeProcess in 943 ms
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142248

**Pull request closed without merging**
