### PR TITLE
COMMERCE-7738 MVCC for commerce-shop-by-diagram-service

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/COMMERCE-7738

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failure not related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109736

**Pull request closed without merging**
