### PR TITLE
[License]LPS-123631 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5,

Could you please test LCS feature on this pull if it is not covered by automatic tests.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian The automated test for LCS deploys the LCS modules to master (ant all) and activates with lcs.liferay.com.

Are these changes only applied to a Licensed bundle? If so we will need to test manually.

**Comment by tinatian** [comment]
@vicnate5 As long as we tested license validation by lcs, it should cover the changes.

**Comment by vicnate5** [comment]
@tinatian The CI test failure is not related to Licensing. Commerce did activate, but there is a bug in upstream with Commerce Speedwell theme. I reproduced this on a regular master bundle.

**Comment by vicnate5** [comment]
Finished testing. Confirmed that LCS can be used to activate a release bundle and Commerce license can also be activated with LCS as the activation method for DXP.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go, the automatic test passed on my local pull https://github.com/tinatian/liferay-portal/pull/2104

**Comment by shuyangzhou** [comment]
Merged on the license repo side.

**Pull request closed without merging**
