### PR TITLE
Lps 69644 Add snapshot class to speed up invocation to OSGi configurable proxy.

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

The snapshot class logic is changed to :

1) Each time will generate a new snapshot class and create a new instance of it
2) When return type is array, create a filed and initialize it in constructor
3) When return type is primitive type, string and enum, return constant value
4) For all other return types, throw UnsupportedOperationException.

Tina.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

@tomwang2011 run a perf diff please.

**Comment by tomwang2011** [comment]
@shuyangzhou @tinatian the test results are at: smb://172.16.0.30/benchmark/2016/TestPulls-Shuyang/12-16-16-LPS-69644

**Comment by shuyangzhou** [comment]
The number seems went down, and tons of CI failures, @tinatian please check and resend.

**Comment by tinatian** [comment]
@shuyangzhou  OK, I will check and resend.

**Comment by tinatian** [comment]
Fix ci failures in thhis pull : https://github.com/shuyangzhou/liferay-portal/pull/3576

**Pull request closed without merging**
