### PR TITLE
LPS-X No need to check version in sidecar mode, it is always going to…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… match.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142249

**Pull request closed without merging**
