### PR TITLE
[Log4j]LPS-128599

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@tinatian Failures not related, I can watch for the next results too.

**Comment by tinatian** [comment]
close, will resend.

Tina.

**Pull request closed without merging**
