### PR TITLE
COMMERCE-2475 - Dispatch Framework

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @shuyangzhou I have added new changes on top of the old ones from the first PR. After discussing with @igorbeslic, we have renamed DispatchTrigger -> DispatchTask, this entity should represents a task that will be executed according to cronExpression by Liferay scheduler engine. 
I have extracted startDate and endDate fields to be transient to avoid duplicated data in DB and reuse existing values from Triggers table.
 Unfortunately I didn't find a way to read cronExpression value using LR scheduler api, that is the only reason why there is a cronExpression column in DispatchTask. The only example I found of reading [cronExpression value from trigger](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java#L544) is not applicable for our case and [Liferay Trigger interface](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/scheduler/Trigger.java) doesn't expose that value. Is there maybe another way to fetch cronExpression other than store it in DispatchTask table?

Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek is this the resend of https://github.com/brianchandotcom/liferay-portal/pull/93547 ? Please keep the original commit history, for complex pull like this, if you squash the history, I will have to go over this from beginning again.

**Pull request closed without merging**
