### PR TITLE
LPS-78901 ServiceBuilder osgi-util dependency

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Preston-Crary this is real, right?

**Comment by Preston-Crary** [comment]
@shuyangzhou none of those failed in the last test except the semantic versioning failure.  There's no API change so I'm not sure why this would cause a semantic versioning failure.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/5880

**Pull request closed without merging**
