### PR TITLE
[TECHNICAL SUPPORT] LPS-65236 PortletSessionTracker causes memory leak and violates JSR 286 spec

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-65236

Hi Shuyang,

Can you please review Norbi's changes? It's really not my field and since you made significant changes on PST over the years, you surly know if there's anything that Norbi might have not considered.

Regards,
Tibor

/cc @NorbertKocsis, @Preston-Crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
This is not acceptable.

What you are quoting on the ticket about portlet/servlet sessions, it is saying their lives must be tied together, which is a requirement that as a portal vendor we must do. It is not something you will automatically have. And PortletSessionTracker is how we are doing it.

For the Webshpere case you described, it does not make sense, if all cluster nodes are truly doing session replicating, invalidate portal session on node, will automatically trigger all nodes do the same. There should be no leak.

No really true which piece we are againsting the spec, please explain more about it.

**Comment by lipusz** [comment]
Thank you,. Shuyang. Norbi will look into this and get back to you with his findings.

@shuyangzhou

**Comment by NorbertKocsis** [comment]
Hi Shuyang,

The I will try to explain what I meant :)

> PLT.2.1 What is a Portal?
> A portal is a web based application that –commonly- provides personalization,
> authentication, content aggregation from different sources and hosts the presentation
> layer of information systems. Aggregation is the action of integrating content from
> different sources within a web page. A portal may have sophisticated personalization
> features to provide customized content to users. Portal pages may have different set of
> portlets creating content for different users.
> 
> PLT.2.2 What is a Portlet?
> A portlet is an application that provides a specific piece of content (information or
> service) to be included as part of a portal page. It is managed by a portlet container, that
> processes requests and generates dynamic content. Portlets are used by portals as
> pluggable user interface components that provide a presentation layer to information systems.
> The content generated by a portlet is also called a fragment. A fragment is a piece of
> markup (e.g. HTML, XHTML, WML) adhering to certain rules and can be aggregated
> with other fragments to form a complete document. The content of a portlet is normally
> aggregated with the content of other portlets to form the portal page. The lifecycle of a
> portlet is managed by the portlet container.
> Web clients interact with portlets via a request/response paradigm implemented by the
> portal. Normally, users interact with content produced by portlets, for example by
> following links or submitting forms, resulting in portlet actions being received by the
> portal, which are forwarded by it to the portlets targeted by the user's interactions.
> The content generated by a portlet may vary from one user to another depending on the
> user configuration for the portlet.
> This specification will deal with Portlets as Java technology based web components.
> 
> PLT.2.3 What is a Portlet Container?
> A portlet container runs portlets and provides them with the required runtime
> environment. A portlet container contains portlets and manages their lifecycle. It also
> provides persistent storage for portlet preferences. A portlet container receives requests
> from the portal to execute requests on the portlets hosted by it.
> A portlet container is not responsible for aggregating the content produced by the
> portlets. It is the responsibility of the portal to handle the aggregation.
> A portal and a portlet container can be built together as a single component of an
> application suite or as two separate components of a portal application.

After reading this I would say we are rather in the Portal category.

> PLT.18.4 Relationship with the Web Application HttpSession
> If the HttpSession object is invalidated, the PortletSession object must also be invalidated
> by the PORTLET CONTAINER. If the PortletSession object is invalidated by a portlet, the
> PORTLET CONTAINER must invalidate the associated HttpSession object.

This section says the session invalidation is the portlet container's reponsibility not ours.

> PLT.18.2 Session Scope
> Note that the PortletSession object is only valid within the current client request and
> thus should be retrieved via getPortletSession for each client request and not stored
> by the portlet across client requests.
> 
> And the change log:
> PLT 18.2: clarified that a portlet session object is only valid within the current client request

This section -especially after reading the changelog- was written to discourage if not forbid holding on to PortletSession references across requests. 

And apart from the above in the Websphere example (and even Tomcat has similar capabilities) you can see our PortletSessionTracker interferes with app servers' memory management mechanisms, as it makes it impossible to free up memory after persisting idle sessions.

Br,
Norbert

**Comment by shuyangzhou** [comment]
There is no such thing as portlet container physically outside portal, not only us, it is true for all portal vendors. Portlet container is only a logical concept inside portal, without portal there is no portlet container.

If anything is portlet container's responsibility, it is our responsibility. If we don't do it, it won't exist magically in our system.

As for the websphere case, I still don't get what you are saying. PortletSessionTracker is helping portal to tie all portlet sessions together for management, without it then we will have some really memory issues.

**Comment by NorbertKocsis** [comment]
Sorry, got it know. We need to track portlet sessions, but I think our approach should be improved.

I'm considering something like this: https://github.com/Jasig/uPortal/blob/master/uportal-war/src/main/java/org/jasig/portal/portlet/session/PortletSessionExpirationManager.java

Our current implementation can cause problems if an app server tries to move idle sessions from memory to it's persistent store for freeing up memory. Or just moves it between nodes fro load balancing reasons.

The Websphere case is the following:

n node Websphere cluster with persisted session distributin, with session cache limit set and no overflow.

1. UserA gets a session and x portlet sessions gets registered by PST for it on nodeA
2. User (therfore session is idle).
3. Session cache limit reached.
4. Node recieves another request from a new user
5. UserA's session is moved to the persistent store and sessionRemovedFromCache event raised.
6. UserA sent another request.
7. nodeA is overloaded so nodeB gets the request and loads the session from the persistent store, and upon serving the portlet requests the portlet sessions get registered by PST on nodeB.
8. UserA logs out.
9. sessionDestoyed happens on nodeB -> PST on nodeB invalidates portlet sessions and drops the references.
10. nodeA only gets a sessionRemovedFromCache event so no invalidation there.

So nodeA still has references for the portlet sessions and they are still in memory while nodeA tried to remove them at step 5. And we got a memory leak as those sessions will never be removed.

In an approach like which I linked we could store the portlet session references in the portal session, so it wouldn't be bound to a specific node and we wouldn't have to worry about how each app server manages sessions. And it would solve the mentioned memory leak on Websphere 

bonus:
In Tomcat's case the sessionDestroy would happen on both nodes so PST invalidate would happen on nodeA eventually, but we would still prevent we would still prevent nodeA from removing those sessions from memory as long as userA's session is active somewhere in the cluster.

bonus2:
What I noticed during investigation on Tomcat is when a portlet session is invalidated the user's session remains active. Although now I'm not sure if it should work in that direction.

Br,
Norbert

**Pull request closed without merging**
