### PR TITLE
LPS-179475 Prefer putIfAbsent over computeIfAbsent on hot path to red…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…uce contention.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by GinsonRen** [comment]
@shuyangzhou The fix works, result looks good.
Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 2ed1d258 | 16433 | 378 | -
pr-11004 | - | 17025 | 42.8 | 3.60%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 2ed1d258 | 33596 | 361 | -
pr-11004 | - | 35330 | 262 | 5.16%

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132270

**Pull request closed without merging**
