### PR TITLE
LPS-89456 Mysql 8 upgrade issue

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou ,

I figured out a way to add upgrade process for powwow-portlet, and tested it locally, it works. So this pull include everything we need for the fix.

Hi @vicnate5,

Could you please keep an eye on the ci test of this pull? Let me know if there is any real failure. If there is no real failure, you can go ahead to test this with mysql 8.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by anthony-chu** [comment]
@tinatian @shuyangzhou 

the automation results here are consistent with those on upstream acceptance, so i went ahead and tested this against mysql 8.0. i was able to successfully start up portal on mysql 8.0 with no exceptions.

**Comment by shuyangzhou** [comment]
@anthony-chu I made some changes and retesting at https://github.com/shuyangzhou/liferay-portal/pull/7339, can you watch over that pull for me? Thanks!

**Comment by anthony-chu** [comment]
@shuyangzhou will do. i did a quick check for upgrades based on the changes tina made, and it looks like the upgrade process was unsuccessful. i've attached the upgrade.log and database i used:

[data-archive-portal-mysql.zip](https://github.com/shuyangzhou/liferay-portal/files/2829643/data-archive-portal-mysql.zip)
[upgrade.log](https://github.com/shuyangzhou/liferay-portal/files/2829644/upgrade.log)

**Pull request closed without merging**
