### PR TITLE
LRQA-28415 Update gatekeeper to include a blacklist and apply gatekeeper to chat modules

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-28415

@shuyangzhou, if you could look at this when you get a chance. Thanks!

cc: @michaelhashimoto, @peterfellwock

### CODE REVIEW

**Comment by kenjiheigel** [comment]
cc: @brianchiu, @jpince

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@kenjiheigel can you come over to talk to me? The logic is slightly off.

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/shuyangzhou/liferay-portal/pull/3361

**Pull request closed without merging**
