### PR TITLE
Portal equinox log bridge

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression in tests for the osgi/state 

Steps to Reproduce:
1. Set ENV variable `export LIFERAY_CLEAN_OSGI_STATE=true`
1. Start Tomcat, wait for full startup
1. Shutdown Tomcat
1. Rename Tomcat directory e.g. `mv tomcat-9.0.56/ tomcat-rename/`
1. Unset ENV variable `unset LIFERAY_CLEAN_OSGI_STATE`
1. Start Tomcat again
```
WARN  [main][ModuleReadHookImpl:92] No bundle found for location theme-fragment:admin-theme
WARN  [main][ModuleReadHookImpl:92] No bundle found for location theme-fragment:classic-theme
```

Also occurs in LPKG configuration
```
WARN  [main][ModuleReadHookImpl:92] No bundle found for location admin-theme-5.0.31.war?lpkgPath=file:/opt/dev/projects/github/liferay-portal/bun%20dles/osgi/marketplace/Liferay%20Foundation%20-%20Liferay%20Frontend%20Theme%20-%20Impl.lpkg
WARN  [main][ModuleReadHookImpl:92] No bundle found for location classic-theme-5.0.41.war?lpkgPath=file:/opt/dev/projects/github/liferay-portal/bun%20dles/osgi/marketplace/Liferay%20Foundation%20-%20Liferay%20Frontend%20Theme%20-%20Impl.lpkg
WARN  [main][ModuleReadHookImpl:92] No bundle found for location dialect-theme-5.0.31.war?lpkgPath=file:/opt/dev/projects/github/liferay-portal/bun%20dles/osgi/marketplace/Liferay%20Foundation%20-%20Liferay%20Frontend%20Theme%20-%20Impl.lpkg
WARN  [main][ModuleReadHookImpl:92] No bundle found for location minium-theme-5.0.34.war?lpkgPath=file:/opt/dev/projects/github/liferay-portal/bun%20dles/osgi/marketplace/Liferay%20Commerce%20-%20Liferay%20Commerce%20-%20Impl.lpkg
WARN  [main][ModuleReadHookImpl:92] No bundle found for location speedwell-theme-4.0.34.war?lpkgPath=file:/opt/dev/projects/github/liferay-portal/bun%20dles/osgi/marketplace/Liferay%20Commerce%20-%20Liferay%20Commerce%20-%20Impl.lpkg
```

**Comment by shuyangzhou** [comment]
I see, it is not a real issue, I lower the package logging level to INFO, which was ERROR causing those started to show, I will flip back the logging level for that logger, thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
ci:test

@vicnate5 updated logger settings, retesting.

**Comment by vicnate5** [comment]
@shuyangzhou Tests are passing now, this should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117981

**Pull request closed without merging**
