### PR TITLE
[TS] LPS-92894 List of operation systems does not load in Liferay Mobile Device Detection Portlet Lite

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-92894

Hi @shuyangzhou ,

Currently, the list of operating systems displays for CE but not DXP, when using Liferay Mobile Device Detection Lite.

The goal of this fix is to resolve that issue.

For additional details, please see the LPS ticket.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@ericyanLr this is wrong, this module is only for CE, it should never load on DXP. For DXP, we have the "com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise" to kick in for DXP profile.

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

From my understanding, **Liferay Mobile Device Detection Lite** is available for both CE and DXP:
https://web.liferay.com/marketplace/-/mp/application/92831494

And the **Liferay Mobile Device Detection Enterprise** is an optional upgrade, which also requires an additional license.
https://web.liferay.com/marketplace/-/mp/application/35419014

If this is not the case, does that mean Liferay DXP users are now allowed to use the **Lite** edition and are instead required to purchase the **Enterprise** edition?

Thanks!

**Comment by shuyangzhou** [comment]
@ericyanLr I think this requires a Product manager clarification. My understanding and the original change was making lite for CE only, and enterprise for DXP only.

CC @david-truong

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

Thanks for the insight, will confirm with Dave!

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

I reached out to @david-truong and we came to the conclusion that:
> the **Lite** version should run on DXP, since the **Enterprise** version requires it

Basically, the **Lite** version would allow DXP to run the app in **Lite** mode (no additional license required).

**Comment by shuyangzhou** [comment]
Ok, fine, if that's what we want. Then just remove the profile for CE module, having a profile that works on all cases is logically the same as not having a profile.

**Comment by ericyanLr** [comment]
resent: https://github.com/shuyangzhou/liferay-portal/pull/7604

**Pull request closed without merging**
