### PR TITLE
LPS-94297 and LPS-94440

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou I don't think any of these CI failures are related. In fact, when I visit the [main test result page](https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4945/jenkins-report.html) I see many failures, but when I click on individual reports with supposed failures ([such as the TCK report](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/160488/)), there are zero failures in the summary.

Please review at your earliest opportunity since @ctampoya is monitoring this for inclusion with 7.1 FP11/GA4. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72053

**Pull request closed without merging**
