### PR TITLE
LPS-108218 Handle null, way Oracle treats empty String.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
looking through results now

**Comment by kyle-miho** [comment]
@shuyangzhou no unique failures found in functional or integration tests, pull should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84306

**Pull request closed without merging**
