### PR TITLE
LPS-75948 Portlet 3.0: Detect portlet spec version found in the portlet.xml descriptor

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: Please verify that the CI failures are unrelated to this pull request. Thank you.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by jpince** [comment]
@ngriffin7a will take a ook at this, may need to wait for the retest to finish

**Comment by ngriffin7a** [comment]
@jpince: The retest is complete, when you can, please verify that the CI failures are unrelated to this pull request. Thank you.

**Comment by jpince** [comment]
@ngriffin7a `This pull contains no unique failures.` this one looks good :) 

@shuyangzhou please review

**Comment by shuyangzhou** [comment]
@ngriffin7a rebase error, please resend.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/5577

**Pull request closed without merging**
