### PR TITLE
LPS-84181 Apply petra StringBundler Part 1

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
This is the first part of applying petra StringBundler, will send more pulls about it.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 is the failure real?

**Comment by vicnate5** [comment]
@shuyangzhou Real failures here
@ChiZelin @dantewang 

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:4616: error: method concat in class StringBundler cannot be applied to given types;> Task :util:portal-tools-service-builder:compileJava
     [exec] 
     [exec] 				StringBundler.concat(
     [exec] 				             ^
     [exec]   required: String[]
     [exec]   found: String,String,String,int,String,String,String,String
     [exec]   reason: varargs mismatch; int cannot be converted to String
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:4639: error: method concat in class StringBundler cannot be applied to given types;
     [exec] 						StringBundler.concat(
     [exec] 						             ^
     [exec]   required: String[]
     [exec]   found: String,String,String,String,String,int,String,String,String,String,String
     [exec]   reason: varargs mismatch; int cannot be converted to String
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:4757: error: method concat in class StringBundler cannot be applied to given types;
     [exec] 				StringBundler.concat(
     [exec] 				             ^
     [exec]   required: String[]
     [exec]   found: String,String,String,int,String,String,String,String
     [exec]   reason: varargs mismatch; int cannot be converted to String
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:4779: error: method concat in class StringBundler cannot be applied to given types;
     [exec] 					StringBundler.concat(
     [exec] 					             ^
     [exec]   required: String[]
     [exec]   found: String,String,String,String,String,int,String,String,String,String,String
     [exec]   reason: varargs mismatch; int cannot be converted to String
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:6355: error: method concat in class StringBundler cannot be applied to given types;
     [exec] 					StringBundler.concat(
     [exec] 					             ^
     [exec]   required: String[]
     [exec]   found: String,CTColumnResolutionType,String,String,String,String
     [exec]   reason: varargs mismatch; CTColumnResolutionType cannot be converted to String
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java:6368: error: method concat in class StringBundler cannot be applied to given types;
     [exec] 							StringBundler.concat(
     [exec] 							             ^
     [exec]   required: String[]
     [exec]   found: String,CTColumnResolutionType,String,String,String,String
     [exec]   reason: varargs mismatch; CTColumnResolutionType cannot be converted to String
     [exec] 
     [exec] > Task :util:portal-tools-service-builder:compileJava FAILED
```
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/344469/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Pull request closed without merging**
