### PR TITLE
LPS-77835 portal-osgi-web-servlet-jsp-compiler

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Resolved the conflict.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55585

**Pull request closed without merging**
