### PR TITLE
LPS-73667 The retry must be done with a JDBC connection, not a datasource, which is pooled

### PR DESCRIPTION
**Pull request by mdelapenya**
Once reviewed and accepted I'll send the other refactors

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mdelapenya can you not do the Function change in this pull? I don't think that is the right (or at least a necessary) change for now. We can talk about it separately later if necessary, but at least don't do it right now.

And can you directly apply the jdbc connection logic? Currently you are adding RetryDataSourceFunction first, then redo it as RetryJDBCConnectionFunction. We should always avoid redoing our own commits within the same pull, that will just make the commit history messy.

Please resend.

Thanks

**Comment by mdelapenya** [comment]
Hey Shuyang, I think encapsulating the retry algorithm in a function is a good idea, as it could be reused simply passing a different function as input param.

Besides, this could define the first steps towards modularity, as we could define OSGi bundles with the retry algorithm: just defining a service representing the invocation, and implementing different retry strategies (retry algorithms): retry once, retry forever, etc.

In any case, I'll redo the commits to remove what you suggest. And I would continue with the function approach, as I see more benefits than not using it. Besides, we are in Java8, why not encourage the usage of lambda expressions?

what do you think?

**Pull request closed without merging**
