### PR TITLE
LPS-X Unplug default ImageProcessorImpl, since the replacement AMImag…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…eEntryProcessor is always present.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 do we have some tests to cover AM?

**Comment by vicnate5** [comment]
ci:test:lima-acceptance

**Comment by vicnate5** [comment]
@Kvale1733 Can you check this one? Looks like we have some regressions

**Comment by vicnate5** [comment]
@shuyangzhou Lots of AM unit tests failed here: See https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1936077229&testrayCaseTypeId=60250159&testrayComponentId=1310772261&statuses=3

Also this integration test https://testray.liferay.com/home/-/testray/case_results/1936104124

**Comment by shuyangzhou** [comment]
@vicnate5 I am not able to reproduce the unit test failures. The integration is real, and I have fixed it. Let's rerun this to confirm the unit test failures.

**Comment by shuyangzhou** [comment]
ci:test:lima-acceptance

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Looks good now!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121348

**Pull request closed without merging**
