### PR TITLE
[Hibernate]LPS-134907

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on benchmark tests and startup.

Thanks.
Tina.

**Comment by tinatian** [comment]
FYI @dantewang @yuhai

**Comment by GinsonRen** [comment]
Hi @tinatian Here is the diff result for login, I will update other tests result later. 

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 29693 | 476 | 144 | -
PR-10129 | - | 29914 | 476 | 143 | 0.74%

I updated my laptop from ubuntu to xubuntu, I cannot get the startup testing result today because some miss/wrong configuration. I will update the startup diff result tomorrow, sorry for that.

**Comment by GinsonRen** [comment]
@tinatian Here are other test result:

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 40379 | 473 | 151 | -
PR-10129 | - | 40004 | 476 | 153 | -0.93%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 16565 | 43.9 | 135 | -
PR-10129 | - | 16638 | 40.1 | 134 | 0.44%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 10464 | 32.2 | 117 | -
PR-10129 | - | 10454 | 45.2 | 184 | -0.10%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 19488 | 192 | 366 | -
PR-10129 | - | 19185 | 371 | 518 | -1.55%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 11509 | 242 | 671 | -
PR-10129 | - | 11458 | 261 | 691 | -0.44%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 167f47e46c | 19279 | 399 | 182 | -
PR-10129 | - | 18719 | 389 | 180 | -2.90%

**Comment by slnn** [comment]
Hi @tinatian 

Here are startup test results with my laptop


Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 821d682 | 50278 | 25133.4 | 24559 | 25554 | 25052 | 25223 | 25279
PR | - | 50477 | 25160.4 | 24494 | 24899 | 25207 | 25958 | 25244


By the way, these commits of LPS-134168 have been reverted for baseline and this pull to run startup test with lpkg release bundle as they caused this issue https://issues.liferay.com/browse/LPS-135020

https://github.com/liferay/liferay-portal/commit/36297bc96ec6f833a031d5c4514601295e1e8382
https://github.com/liferay/liferay-portal/commit/2692d61dba9e3b95b1b2953f0b63d6580c8d599c

Regards
Lily

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
