### PR TITLE
LPS-81861 Portlet 3.0: Refactor portlet request parameter handling and portlet URL generation (implement StateAwareResponse.getRenderParameters() and refactor deprecated methods to utilize the underlying MutableRenderParameters composition object)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou This PR has one commit that implements `StateAwareResponse.getRenderParameters()` and refactors deprecated methods to utilize the underlying MutableRenderParameters composition object.

/cc  @dantewang @ChiZelin

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:stop

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou All green! Second one today! :)

Please review at your earliest convenience. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61662

**Pull request closed without merging**
