### PR TITLE
LPS-108032

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@kyle-miho please scan for regressions.

**Comment by kyle-miho** [comment]
no unique upgrade failures found, pull should be good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84341

**Pull request closed without merging**
