### PR TITLE
Startup optimization 310 patch bundle loader sources

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me watch this pull too, thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found here.

There is one strange test failure here. https://testray.liferay.com/home/-/testray/case_results/2440305071
It also failed on https://github.com/shuyangzhou/liferay-portal/pull/11247. But looks like @zhangyan0701 and I were not able to reproduce locally.

Will monitor what happens upstream since the first part was already merged.

**Comment by shuyangzhou** [comment]
That failure is running out of jdbc connections for some reason at runtime. Can not be caused by this pull, since it only affects startup time logic, not runtime.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142178 and https://github.com/brianchandotcom/liferay-portal/pull/142179

**Pull request closed without merging**
