### PR TITLE
LPS-107917

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou looks good

**Comment by shuyangzhou** [comment]
@Preston-Crary please fix the conflict

**Comment by Preston-Crary** [comment]
Rebased off of a47318494efb203b9615234e146fd6460f65d130.

**Comment by shuyangzhou** [comment]
@Preston-Crary please rebase for the conflict, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8836

**Pull request closed without merging**
