### PR TITLE
[ResourceAction]LPS-112054

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
Resolved conflict and sent to https://github.com/shuyangzhou/liferay-portal/pull/9099
cc @tinatian

**Pull request closed without merging**
