### PR TITLE
LPS-149082 Remove commons-beanutils.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
@shuyangzhou 
Related to point 3 mentioned on this [PR](https://github.com/guilhermedcamacho/liferay-portal/pull/79#issue-1197886877):
The code on this [line 73](https://github.com/guilhermedcamacho/liferay-portal/blob/6ca528615790d4ea4304ae86fb4d5b82f3540995/portal-test/src/com/liferay/portal/kernel/test/BeanTestUtil.java#L73) guarantees that or I get the corresponding setter method with just one parameter or it raises a NoSuchMethodException. So in this part I only changed to pass the setter parameter type to _translateValue method.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho from the ftl usages I can see the hasProperty always paired with setProperty. Although I want the api to be as strict as possible, if all usages are doing this we are not really restricting anything. So the question is, must all usages do the hasProperty check? If yes, we should just move the check logic into setProperty to make it a noop for missing property.
> 
> And for the setProperty method body, do we have usecases of overloaded property? Why is this needed:
> 
> ```
> 		Method getMethod = _getMethod(clazz, name, "get");
> 
> 		Method setMethod = _getMethod(
> 			clazz, name, "set", getMethod.getReturnType());
> ```
> 
> We should be able to locate the setter method purely by name and parameter number to be 1. If we end up seeing 2 method having the same name but with parameter type, that is a overloaded property, I don't think that would work before this change, if so we don't need to check it either. Fundamentally we should not rely on getter to call setter, setter can be invoked even the class does not have a matching getter.

Hey @shuyangzhou , regarding the method hasProperty, I removed it from ftl template and used it just in the places where it was necessary (places where they are trying to set a property that doesn't exists, breaking the test).

Related to the point two, we have method overloading to set the same property. e.g. 
`public void setId(String id)` and `public void setId(UnsafeSupplier<String, Exception> idUnsafeSupplier)`

As you suggested, I changed the logic to locate the setter method purely by name and parameter number to be 1, and created a whitelist of parameter types to solve the logic of UnsafeSupplier cases.

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help us check the results, thanks!

**Comment by vicnate5** [comment]
@guilhermedcamacho No regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10641

**Pull request closed without merging**
