### PR TITLE
LPS-X Change default tx isolation level to read committed.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:acceptance-functional

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou 
This change is causing VerifyProperties to complain `ERROR [main][VerifyProperties:163] Portal property "jdbc.default.transactionIsolation" is obsolete`

Seems to be the main reason we are getting upgrade test failures here (upgrade tool is very sensitive to ERROR)

It also fails https://testray.liferay.com/home/-/testray/case_results/2440290348

No other regressions found. No need to re-run everything. I would just triggered `publications` suite after fixing (this will be component-specific and then also check upgrades)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:publications

**Comment by shuyangzhou** [comment]
@GinsonRen please run runtime regression checks for all DB heavy test cases.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions now. Upgrade working without error.

**Comment by shuyangzhou** [comment]
@GinsonRen make sure to run this regression compare with proper mysql settings, no need to wait for the new tweaked settings. The existing 16GB one is good enough for this pull.

**Comment by GinsonRen** [comment]
@shuyangzhou Here are results:
MB:

**Comment by GinsonRen** [comment]
@shuyangzhou https://drive.google.com/drive/u/1/folders/16M0nlVmjUgbxWeodJ5DIdoBu4dBXYmiB

**Comment by shuyangzhou** [comment]
@GinsonRen do you reboot DB server before each test? All test results' DB vmstat logs show the cache memory usage on this branch is about 6.6~6.9GB higher than master.

If this is not a test mistake, this is something needs to dig into.

@dantewang this may relate to your mysql config optimize too. We may want to try to change mysql default tx isolation level to see how it affects things.

**Comment by dantewang** [comment]
@shuyangzhou In the normal daily tests, the servers are not rebooted between each tests.

**Comment by shuyangzhou** [comment]
@GinsonRen rerun the compare with reboot, I need to know whether the cache memory difference is caused by this change, or just some leftover state from previous runs.

**Comment by GinsonRen** [comment]
@shuyangzhou There are the results with rebooting DB server for each test. Result archive are uploaded here: https://drive.google.com/drive/u/1/folders/1X_gTIEqsVBlSGhMq-9lgevYSXI0VSAY6
MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 48c49082 | 10771 | 15.8 | -
PR-4014 | - | 11005 | 18.3 | 2.17%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 48c49082 | 16994 | 48 | -
PR-4014 | - | 17009 | 15 | 0.09%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 48c49082 | 32417 | 257 | -
PR-4014 | - | 31631 | 331 | -2.42%

**Comment by shuyangzhou** [comment]
@GinsonRen the cache usage looks the same now. But the blogs master baseline archive shows db connection failures on portal startup, it eventually recovered and the results look fine. Be careful for future runs, look into the results to make sure nothing too obviously fails. The mb and dl results are good enough to support this change, no need to rerun.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142493

**Pull request closed without merging**
