### PR TITLE
Lps 116452 x stream cache tested

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:staging

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, if good please forward, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou no regressions found

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
