### PR TITLE
LPS-145073 with JUnit tests

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@shuyangzhou Per your request, I added two unit tests as a second commit, in order to make the intended of the first commit logic more clear. Please run any `ci` related tests you might think are necessary, e.g. `ci:test` or perhaps `ci:test:tck`

**Comment by ngriffin7a** [comment]
@shuyangzhou Note that one of the JUnit tests that I wrote logs an exception to the console, but this is intended behavior. In other words, the JUnit test is trying to make sure that an exception is thrown, and the exception handling code in HeaderRequestImp.java logs the caught exception to the console log.

**Comment by ngriffin7a** [comment]
cc @weskempa-liferay

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10527

**Pull request closed without merging**
