### PR TITLE
[Bug Fix]LPS-120753-LPS-120755

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @vicnate5,
Is there any other test required for this change except for the ci tests?

Thanks
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 Can you take a look at this? https://issues.liferay.com/browse/LRQA-61875

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Comparison with master upstream acceptance:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1286831386&testrayRunIdA=1286828319&statusB=3
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=6&testrayRunIdB=1286831386&testrayRunIdA=1286828319&statusB=3

**Failures are not related:**
lpkg-override-jdk8/0: looks more like flaky, also see this error in some other upgrade tests.
source-format-jdk8/0: errors are not related.
modules-integration-mysql57-jdk8, modules-unit-jdk8: also see the errors on master acceptance.

**Comment by shuyangzhou** [comment]
@vicnate5 should I merge this?

**Comment by zhangyan0701** [comment]
Hi guys, 

About the functional-smoke-websphere90-mysql57-jdk8 failure, it failed with error `  [waitfor] 08:27:29,903 ERROR [server.startup : 2][HikariPool:541] HikariPool-1 - Exception during pool initialization.
  [waitfor] com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
  [waitfor] 
  [waitfor] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  [waitfor] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
  [waitfor] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
  [waitfor] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
  [waitfor] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
  [waitfor] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
  [waitfor] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
  [waitfor] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:112)
  [waitfor] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:118)
  [waitfor] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
  [waitfor] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
  [waitfor] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:443)
  [waitfor] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
  [waitfor] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:111)
  [waitfor] 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
  [waitfor] 	at com.liferay.portal.dao.jdbc.util.DBInfoUtil.lambda$getDBInfo$0(DBInfoUtil.java:47)
  [waitfor] 	at com.liferay.portal.dao.jdbc.util.DBInfoUtil$$Lambda$20.0000000067FAEC90.apply(Unknown Source)
  [waitfor] 	at com.liferay.petra.concurrent.ConcurrentMapperHashMap.lambda$computeIfAbsent$1(ConcurrentMapperHashMap.java:114)
  [waitfor] 	at com.liferay.petra.concurrent.ConcurrentMapperHashMap$$Lambda$21.0000000067FAF7A0.apply(Unknown Source)
  [waitfor] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1671)
  [waitfor] 	at com.liferay.petra.concurrent.ConcurrentMapperHashMap.computeIfAbsent(ConcurrentMapperHashMap.java:111)
  [waitfor] 	at com.liferay.portal.dao.jdbc.util.DBInfoUtil.getDBInfo(DBInfoUtil.java:44)
  [waitfor] 	at com.liferay.portal.spring.hibernate.DialectDetector.getDialect(DialectDetector.java:51)
  [waitfor] 	at com.liferay.portal.dao.init.DBInitUtil.init(DBInitUtil.java:60)
  [waitfor] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:252)
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:1834)
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:442)
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
  [waitfor] 	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171)
  [waitfor] 	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904)
  [waitfor] 	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789)
  [waitfor] 	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427)
  [waitfor] 	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1248)
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1516)
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:704)
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1098)
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:800)
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2317)
  [waitfor] 	at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5466)
  [waitfor] 	at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5682)
  [waitfor] 	at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2322)
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436)
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379)
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127)
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:985)
  [waitfor] 	at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:524)
  [waitfor] 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
  [waitfor] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
  [waitfor] 
  [waitfor] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  [waitfor] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  [waitfor] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
  [waitfor] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
  [waitfor] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
  [waitfor] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
  [waitfor] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
  [waitfor] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
  [waitfor] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
  [waitfor] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:334)
  [waitfor] 	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:164)
  [waitfor] 	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1342)
  [waitfor] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
  [waitfor] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
  [waitfor] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
  [waitfor] 	... 46 more
  [waitfor] Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
  [waitfor] 	at com.ibm.jsse2.D.c(D.java:182)
  [waitfor] 	at com.ibm.jsse2.au.j(au.java:378)
  [waitfor] 	at com.ibm.jsse2.au.i(au.java:271)
  [waitfor] 	at com.ibm.jsse2.au.a(au.java:272)
  [waitfor] 	at com.ibm.jsse2.au.startHandshake(au.java:938)
  [waitfor] 	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:336)
  [waitfor] 	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
  [waitfor] 	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
  [waitfor] 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:325)
  [waitfor] 	... 51 more`

But I wasn't able to reproduce it locally on Windows 10. I thought it was an network issue, but it also failed in PR that I triggered ci test:
https://github.com/zhangyan0701/liferay-portal/pull/240

Maybe this is a Linux only issue.

Sorry about this!

**Comment by vicnate5** [comment]
I can take a look at the Websphere issue today.

**Comment by vicnate5** [comment]
Due to the DXP GA1 release, analysis of this is delayed until middle of the week.

**Comment by dantewang** [comment]
Actual cause:

```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
	at com.ibm.jsse2.D.c(D.java:182)
	at com.ibm.jsse2.au.j(au.java:378)
	at com.ibm.jsse2.au.i(au.java:271)
	at com.ibm.jsse2.au.a(au.java:272)
	at com.ibm.jsse2.au.startHandshake(au.java:938)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:336)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:325)
	... 51 more
```

So MySQL driver tries to connect to the DB server using SSL, but fails. @vicnate5 Does CI have any special configuration about SSL? Like disabling certain protocols like TLS 1.x, etc?

**Comment by vicnate5** [comment]
@dantewang 
I can reproduce this SSLHandshakeException locally on Websphere on Linux.  But the problem is not due to Websphere, it is because of the IBM J9 JDK. I also reproduced this using **Tomcat + MySQL Connector 8.0.21 + IBM JDK**. Using the `ibmjava:8-sdk` docker image (MySQL connector 8.0.16 works fine on this environment).

I am able to workaround the issue by disabling SSL in the JDBC url: `&useSSL=false`

I tried setting`-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2 -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dcom.ibm.jsse2.overrideDefaultTLS=true`, but I am still unable to use SSL.

**Comment by dantewang** [comment]
@vicnate5 Is this debug log gathered with the `-D` properties set? Could you gather another log without setting any kind of SSL related property? What's the version of MySQL server used in your local test and on CI?

MySQL driver changed the way to handle SSL in 8.0.19, see https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-19.html and https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html.

**Comment by vicnate5** [comment]
@dantewang The debug log I previously shared is without any SSL properties set. The java args are listed log as well.

My local MySQL is `5.7.31`
CI MySQL is `5.7.25`

**Comment by dantewang** [comment]
@vicnate5 I'll try to find a way to avoid this issue.

**Comment by dantewang** [comment]
ci:close

@ChiZeLin will look into the WebSphere part.
Will resend after it's resolved.

**Pull request closed without merging**
