### PR TITLE
[DL Tuning]LPS-95891

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5
Could you please help me verify the result?

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73794

**Comment by vicnate5** [comment]
functional test failures not related.

**Pull request closed without merging**
