### PR TITLE
LPS-X Remove alloy-mvc

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou This PR is good to go, there are a few unique failures found, i.e compile modules issue in dxp/apps/osb, but those changes are unrelated and occured due to a CI failure, so we can ignore those.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132154

**Pull request closed without merging**
