### PR TITLE
LPD-X Partial undo f2a26703. Prefer code level suggestion over bnd he…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ader compelling.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:jdk11

**Comment by shuyangzhou** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by shuyangzhou** [comment]
ci:test:jdk11

**Comment by shuyangzhou** [comment]
ci:report:29131699

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/154782

**Pull request closed without merging**
