### PR TITLE
LPS-100525 CTTableMapper

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Rebased, fixed conflict with portal-impl/portal-kernel bnd versions.

**Comment by vicnate5** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@Preston-Crary please rebase and resend

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8755

**Pull request closed without merging**
