### PR TITLE
Lps 115016

### PR DESCRIPTION
**Pull request by mtambara**
Haven't tested yet, but this should be the final design

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
Is ci test enough for this? Or we need Victor to do some manual test?

**Comment by mtambara** [comment]
I’ll need to check the test plan to see how much had been automated

**Comment by shuyangzhou** [comment]
The LPKG failure is real, please fix and resend.

**Pull request closed without merging**
