### PR TITLE
Lps 83240 ci compilejsp

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @tinatian

Hi Shuyang, this change copies all the JSPs from bundle to portal-web before running compile-jsp on them. This will help test compiling the compatted JSPs, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:reopen private module compile error

**Comment by tomwang2011** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61075

**Pull request closed without merging**
