### PR TITLE
LPS-75943 [TS] Support for use the last forward request in runtime taglib

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
cc/ @ricardocousolr @ChrisKian

**Comment by jcampoy** [comment]
ci:reopen

**Comment by jcampoy** [comment]
Reopening because this line was not changed in the PR

[java] > 80: ./portal-impl/src/com/liferay/portal/util/PortalImpl.java 557
[java] Exception in thread "main" java.lang.Exception: > 80: ./portal-impl/src/com/liferay/portal/util/PortalImpl.java 557

**Comment by jcampoy** [comment]
ci:retest

**Comment by jcampoy** [comment]
Hi @shuyangzhou ,

Could you take a look at this fix?

I fixed it by adding a new attribute in order to preserve the current behaviour but may be it is not necessary and we can use the last-forward-request for all the taglib usages. What do you think?

Best regards,
Jose

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53628

**Pull request closed without merging**
