### PR TITLE
Liferay service extender

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Poshi failures are random issues, not related.

the full acceptance results are not in yet.

**Comment by vicnate5** [comment]
@shuyangzhou Only failure that looks like it could be related is this startup error on the integration test run:
```
WARN  [Framework Event Dispatcher: Equinox Container: 59b18b6f-9410-4677-b1e1-b3dfafec05d8][Framework:99] FrameworkEvent WARNING 
    [junit] org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
```
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443287/AXIS_VARIABLE=27,label_exp=!master/consoleText

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9495
@vicnate5 I am not 100% sure with just this error stack, but that failure is most likely caused by the service wrapper design in ControlPanelCategoryWrapper, we had similar issues in the Depot PanelAppWrapper. But at least it should have nothing to do with changes in this pull. Please watch out for this failure, if it happens more, we should dig into it. Thanks!

**Pull request closed without merging**
