### PR TITLE
LPS-89224 Google Cloud Storage 

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@david-truong the store interface has significantly changed, can you have this rebase on top of the latest api? And provide @vicnate5 instructions for testing.

**Comment by brianchandotcom** [comment]
I just talked to @igorarouca

I'm going to assign this pull to the Lima team in Spain and squeeze this in.

**Comment by ehan** [comment]
@brianchandotcom One of our clients using this code ran into a bug a few months back. Fixed it in this repo:

https://github.com/lfr-solution-desk/f-gcp-gcs-adapter

Important notes:

1. This code includes a file name obfuscator. We should probably remove it to make it more in line with our other Store implementations. The obfuscator was a requirement for the initial implementation
2. This adapter includes configuration values for encryption keys, something different from our other Store implementations. GCP allows you to either let GCS manage the encryption keys or you provide one yourself. The config is required in the later scenario.

**Comment by adolfopa** [comment]
Hey @ehan 
We don't have access to that repo. Can you share the fix with us by other means so that we can take a look? Thanks!

**Comment by brianchandotcom** [comment]
@adolfopa I just invited you to https://github.com/lfr-solution-desk/f-gcp-gcs-adapter

**Pull request closed without merging**
