### PR TITLE
LPS-140646 Remove BlogsStatsUser

### PR DESCRIPTION
**Pull request by Preston-Crary**
This is a preparation step for making Blogs CT enabled. We decided to remove this table to avoid conflicts between different publications or needing to recalculate them after publishing.

Lily tested this for performance regressions see https://github.com/Preston-Crary/liferay-portal/pull/1524#issuecomment-956350414. Shows ~1% loss but from tracing profile it looks like it should be slightly faster to me since we don't have to update the table and we do not read from it in our test case. Maybe just noise from the 2nd run happening later in the day, otherwise maybe profile does not fully match the test case.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results, thanks!

**Comment by vicnate5** [comment]
ci:test:blogs

**Comment by vicnate5** [comment]
@shuyangzhou Failures in relevant are not related, but I want to run the blogs suite to be safe.

**Comment by shuyangzhou** [comment]
@vicnate5 it does not seem like the blogs tests are running.

**Comment by vicnate5** [comment]
ci:test:blogs

**Comment by vicnate5** [comment]
ci:test:blogs:norebase

**Comment by vicnate5** [comment]
@shuyangzhou Merge conflict preventing it from running, running it without rebase

**Comment by shuyangzhou** [comment]
Yeah, just a bnd version conflict, I can update it once it passes test. It should not affect results. Thanks @vicnate5 !

**Comment by vicnate5** [comment]
@shuyangzhou Looks good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109516

**Pull request closed without merging**
