### PR TITLE
debug

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 do you see a hit to https://github.com/shuyangzhou/liferay-portal/pull/10677/commits/e2bf92cff90d822a6e458f8219250f89e1c81779#diff-a12ca2ac9bdb4da14c536a4734ee2b1a1e407e6da713071b3b1a9bad332195e0R562

**Comment by vicnate5** [comment]
@shuyangzhou See https://testray.liferay.com/home/-/testray/case_results/1878406346

**Comment by shuyangzhou** [comment]
Oh, so it is only this integration test com.liferay.portal.osgi.web.wab.reference.support.test.WabDirTest doing the weird destination dir thing, right? No production code is affected?

**Comment by vicnate5** [comment]
@kyle-miho is checking the rest of the tests because my Testray is having issues on both my computers.

**Comment by kyle-miho** [comment]
@shuyangzhou Testray or Jenkins doesn't have a way to grep for this error on run functional tests since Liferay Errors don't cause a lot of our functional tests to fail like our Integration tests, so we would have to click into each of the ~6000 tests run in this PR to be 100% sure that this debug log is present (~1-5seconds each -> 100-500minutes of analysis is probably not worth ). However I did check all of the failing functional tests and I didn't see this error thrown so it should likely be safe,

From the integration results though, I got the same as Victor, just saw the debug log in WabDirTest

**Pull request closed without merging**
