### PR TITLE
Lps 82656 fixtest

### PR DESCRIPTION
**Pull request by tomwang2011**
This should fix the upstream integration failures such as: https://test-1-9.liferay.com/job/test-portal-acceptance-upstream-batch(master)/21938/AXIS_VARIABLE=7,label_exp=!master/testReport/junit/com.liferay.dynamic.data.mapping.form.evaluator.test/DDMFormFieldTypeSettingsEvaluatorTest/testSelectCallGetDataProviderInstanceOutputParameters/

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
CC: @Preston-Crary

**Comment by tomwang2011** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60653

**Pull request closed without merging**
