### PR TITLE
Master lps 143575

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou @amosfong This just needs a Service Builder regen
https://testray.liferay.com/reports/production/logs/2022-02/test-1-30/test-portal-acceptance-pullrequest(master)/2260/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by amosfong** [comment]
Thanks @vicnate5 , I'll regen and resend

**Comment by amosfong** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/10567

**Pull request closed without merging**
