### PR TITLE
LPS-75306 Permission checkers part 1

### PR DESCRIPTION
**Pull request by Preston-Crary**
Fixed the AssetLinkExportImportTest failure.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/e6cc4f3f14...ca0d7912b4

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5332

**Pull request closed without merging**
