### PR TITLE
LPS-78093 Improve WikiPageDisplay cache usages

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
I manually tested some of the failing functional tests on https://github.com/shuyangzhou/liferay-portal/pull/5747 and didn't see the problem.  Not sure what happened on that pull or if this will pass functional tests or not.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@jpince can you help me figure out this upgrade failure?  Where can I get the data that is being used for this functional upgrade test?

**Comment by jpince** [comment]
@Preston-Crary I'm traveling this week, so may not be able to get back to you

@brianchiu can you please help?

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5760

**Pull request closed without merging**
