### PR TITLE
Pdf processor extraction

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:document

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:online-editing

**Comment by vicnate5** [comment]
ci:test:reports

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found, ran all the test suites that had PDF related testing. The raylife tests didn't run due to unrelated issue, I think this is safe to continue.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114643

**Pull request closed without merging**
