### PR TITLE
Startup optimization 91 search proxy cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related.

**Comment by vicnate5** [comment]
FYI @xbrianlee Search impact

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124731

**Comment by shuyangzhou** [comment]
@xbrianlee this is to remove the useless messaging proxy. Since https://github.com/shuyangzhou/liferay-portal/commit/4107ff86618343e9a27c52ffbbbb3c743843861b all messaging proxy are set to sync, and it is direct sync, not even support timeout, so the only thing this proxy did is adding per index/search call overhead. I am singling this out for search, a global messaging proxy removal will shortly be after this, since this is true for all messaging proxy usages.

**Pull request closed without merging**
