### PR TITLE
LPS-138796  Implement async anti-virus scanning

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rotty3000 could you add some integration tests to demonstrate the usages? For the actually scanning activity, please mock it out to allow the test code to control whether it is a pass or fail. I basically need a way to debug through the code to make necessary adjustment. Thanks!

**Comment by rotty3000** [comment]
will do.

**Comment by rotty3000** [comment]
sorry for the delay I was on PTO last week, I'm working on this this week.

**Comment by rotty3000** [comment]
Tests added!

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
That's a very strange error from bnd. I do not get it locally. I'm hoping it's an anomaly. Re-trying

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
this is getting too noisy re-opening a new PR

**Pull request closed without merging**
