### PR TITLE
Startup optimization 284 lazy user threadlocals

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Regressions found in 2 integration tests. Tested these locally too and they don't fail on master.

1) com.liferay.account.service.test.AccountEntryUserRelLocalServiceTest
```
 [exec] com.liferay.account.service.test.AccountEntryUserRelLocalServiceTest > testAddAccountEntryUserRel2WithInvalidUserEmailAddressDomain FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
     [exec]     	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory._getInstance(FullNameDefinitionFactory.java:59)
     [exec]     	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory.getInstance(FullNameDefinitionFactory.java:24)
     [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.validateFullName(UserLocalServiceImpl.java:6929)
     [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.validate(UserLocalServiceImpl.java:6805)
     [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.addUserWithWorkflow(UserLocalServiceImpl.java:1189
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-38/test-portal-acceptance-pullrequest(master)/8744/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)


2) com.liferay.user.associated.data.anonymizer.test.UADAnonymousUserProviderTest
```
 [exec] com.liferay.user.associated.data.anonymizer.test.UADAnonymousUserProviderTest > testIsAnonymousUser FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:723)
     [exec]     	at com.liferay.user.associated.data.anonymizer.test.UADAnonymousUserProviderTest.testIsAnonymousUser(UADAnonymousUserProviderTest.java:48)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-38/test-portal-acceptance-pullrequest(master)/8744/modules-integration-mysql57-jdk8/4/8/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139837

**Pull request closed without merging**
