### PR TITLE
LPS-139708 Only load portlets belong to system company or current com…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…pany.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @shuyangzhou , I tested locally and the fix does not work.

Testcase1 :x: 
RemoteAppClonedToCreatedInstance

Testcase2 :x: fails by default

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
