### PR TITLE
LPS-101690 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-101690

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
cc: @vicnate5

**Comment by kyle-miho** [comment]
I could view the default guest site normally after running testIntegration in ServicePreActionTest.java (more info in issue comments)

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80549

**Pull request closed without merging**
