### PR TITLE
LPS-72343 Facets: decrement term count when docs are filtered out post-search

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-72343

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

Thanks @arboliveira !

@slnn please rerun the ap regression test for this pull.

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Fixed source formatting.

**Comment by arboliveira** [comment]
ci:retest

**Comment by slnn** [comment]
Test results please see email.

Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48851

**Pull request closed without merging**
