### PR TITLE
[TECHNICAL-SUPPORT] LPS-78495

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian please take this over

**Comment by tinatian** [comment]
OK, got it.

**Comment by tinatian** [comment]
Hi @shuyangzhou,

I reviewed the changes, they are OK. 
The core problem here is to make "_serviceTracker" only create once, and by removing @modified annotation we can achieve that goal, and it is OK to remove @modified cause no one is using the properties map.


Tina.

**Comment by austinskim123** [comment]
Hi @shuyangzhou and @tinatian ,

Thank you for working on this pull request. I was wondering what the time estimate would be for this pull request to be completely reviewed.

Thanks again!

Kindly,
Austin

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56319

**Pull request closed without merging**
