### PR TITLE
LPS-94811 Enable testCleanAssetCategoriesAndTags for DDLRecordStagedModelDataHandlerTest

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 
Could you please check with the DDL team if this change is going to break anything?

Thanks.
Tina

**Comment by vicnate5** [comment]
@jeyvison @alexcandidos

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72353

**Pull request closed without merging**
