### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API (add Portlet 3.0 XML Schema)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains 1 commit that [simply corrects an omission of the Portlet 3.0 XML Schema](https://github.com/shuyangzhou/liferay-portal/pull/6771/commits/1798c87ccba28b880cff3e484afeea48db49d49e#diff-e9e4837ea5f01697b3fc6aca6a3d3aa8R513). The failures reported here must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou Reopened so that it shows up in your review queue.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63413

**Pull request closed without merging**
