### PR TITLE
LPS-84756 TEMPORARY CACHE ONLY

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
Can we check this one? I've solved a couple of thread local memory leaks with https://issues.liferay.com/browse/LPS-84756 and applied https://issues.liferay.com/browse/LPS-84580.

@tomwang2011 this should solve all those thread local logs at shutdown (at least the equinox related ones)

**Comment by slnn** [comment]
Here are all test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | feb06f5 | 17870 | 207 | 51.6
PR-6671 | - | 17426 | 214 | 53.6

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | feb06f5 | 5061 | 119 | 385
PR-6671 | - | 5108 | 107 | 378


MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | feb06f5 | 8152 | 199 | 321
PR-6671 | - | 8323 | 159 | 287

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | feb06f5 | 8914 | 187 | 139
PR-6671 | - | 8754 | 188 | 140

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | feb06f5 | 5880 | 267 | 672
PR-6671 | - | 5776 | 223 | 631


WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | feb06f5 | 22944 | 375 | 137
PR-6671 | - | 22736 | 361 | 133

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | feb06f5 | 9873 | 396 | 629
PR-6671 | - | 9991 | 377 | 617

**Comment by rotty3000** [comment]
Only change after Lily's check was a source format.

ci:test

**Comment by rotty3000** [comment]
I really hate to press the issue on this, but I can't move forward with CDI/Portlet 3.0 work without this committed.

What should I do?

/cc @mhan810 @ngriffin7a

**Comment by shuyangzhou** [comment]
Don't worry @rotty3000. I will get on to this today or tomorrow.

**Comment by rotty3000** [comment]
Ok, thank you @shuyangzhou. I appreciate it!

**Comment by shuyangzhou** [comment]
@mtambara has resent at https://github.com/shuyangzhou/liferay-portal/pull/6676 with new patch applied. I am waiting on CI results, then will get onto it.

**Pull request closed without merging**
