### PR TITLE
Lps 112764

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Test failure is unrelated, fix for the failure was recently merged in https://github.com/brianchandotcom/liferay-portal/pull/88203

**Comment by jpince** [comment]
@vicnate5 @shuyangzhou is this still being reviewed? The ticket was marked as a blocker for the next release.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88309

**Pull request closed without merging**
