### PR TITLE
Revert "LPS-130662 still breaks for me"

### PR DESCRIPTION
**Pull request by rafaprax**
Hey @shuyangzhou,

This is a change that remove the obligation to set the "liferay.mode" to "test" in the system-ext.properties when executing integration tests that rely on this setting. Ex: *PortalExecutor, tests that trigger workflow and etc. I don't know if it is the best solution for this, feel free to change everything.

Thx

//cc @brianchandotcom

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
CI seems to be very unstable. The failure is not related. The ViewPortalSmokeArchive621021 test that failed on the latest run, it passed on the first run: [see](https://testray.liferay.com/home/-/testray/case_results/1556948440?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1556948233%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10247

**Pull request closed without merging**
