### PR TITLE
[Blog Performance]LPS-80526

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant

It seems the Poshi tests fail because of failing to launch Firefox...

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59708

**Pull request closed without merging**
