### PR TITLE
LPS-X Disable aries jmx State notifications.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!
And I am curious, this change should improve overall tomcat startup/shutdown, and runtime bundle installation (in this case is mainly the test bundles), can we somehow get some info about the time difference?

**Comment by vicnate5** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. But also, no significant CI performance improvement found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130101

**Pull request closed without merging**
