### PR TITLE
LPS-X Refactor BatchEngineTaskItemDelegateRegistryImpl to use Service…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…TrackerMap

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by vicnate5** [comment]
ci:test:data-integration

**Comment by vicnate5** [comment]
ci:test:headless

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132914

**Pull request closed without merging**
