### PR TITLE
LPS-89659 Fix PMD failure

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant
There was a ci-related error, re-triggering test.

**Comment by brianwulbern** [comment]
@shuyangzhou can we get a pull for this on 7.1, as well?  Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68597

@dantewang please send a backport pull, if Brian does not do it automaitically (he most likely will).

**Pull request closed without merging**
