### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**
@achaparro moved over the portlet ID upgrade in 930d9d4.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@slnn please test this for performance regressions on login and asset publisher.  If you see a regression please send me a tracing and a sampling profile for the test case. Thanks!

**Comment by Preston-Crary** [comment]
Only fails from 6.2 now... will resend.

**Comment by achaparro** [comment]
@Preston-Crary This can work, hopefully no upgrades for Core in 7.1 and above won't rely on the old portletId or the old preferences

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9572

**Comment by slnn** [comment]
Hi @Preston-Crary 

I will run test for the new pull https://github.com/shuyangzhou/liferay-portal/pull/9572 and update the results when I got them.


Lily

**Pull request closed without merging**
