### PR TITLE
LPS-X Disable audit by default.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This causes `system:check` to fail on first startup
```
 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 271, name: com.liferay.portal.security.audit.event.generators, version: 5.0.14}
	Declarative Service {id: 704, name: com.liferay.portal.security.audit.event.generators.internal.events.LogoutPostAction, unsatisfied references: 
		{name: _auditRouter, target: null}
	}
	Declarative Service {id: 707, name: com.liferay.portal.security.audit.event.generators.internal.security.auth.LoginFailure, unsatisfied references: 
		{name: _auditRouter, target: null}
	}
	Declarative Service {id: 702, name: com.liferay.portal.security.audit.event.generators.internal.events.ImpersonationAction, unsatisfied references: 
		{name: _auditRouter, target: null}
	}
	Declarative Service {id: 705, name: com.liferay.portal.security.audit.event.generators.internal.model.listener.RoleModelListener, unsatisfied references: 
		{name: _auditRouter, target: null}
	}
	Declarative Service {id: 706, name: com.liferay.portal.security.audit.event.generators.internal.model.listener.UserGroupRoleModelListener, unsatisfied references: 
		{name: _auditRouter, target: null}
	}
	Declarative Service {id: 703, name: com.liferay.portal.security.audit.event.generators.internal.events.LoginPostAction, unsatisfied references: 
		{name: _auditRouter, target: null}
		{name: _filter, target: (component.name=com.liferay.portal.security.audit.wiring.internal.servlet.filter.AuditFilter)}
	}
```
https://testray.liferay.com/reports/production/logs/2023-02/test-1-39/test-portal-acceptance-pullrequest(master)/2978/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz?authuser=0

Unique integration test failure: https://testray.liferay.com/home/-/testray/case_results/2195266512

We also have some functional tests for the Audit feature that obviously fail. If we want this off by default for sure, I can fix those tests to enable it just for those tests. Is the user expected to enable with `.config`?

**Comment by shuyangzhou** [comment]
@vicnate5 what are those auditing tests doing? I don't have to disable it. I did not know we are testing it by default.

**Comment by vicnate5** [comment]
Automation tests for Audit:
1. Checking different configuration values for Audit `com.liferay.portal.security.audit.wiring.internal.configuration.AuditLogContextConfiguration.config` and the expected results.
2. Viewing and asserting contents of the audit output file `${liferayHome}/liferay.audit.log`
3. Checking UI behavior of the portlet at Control Panel > Security > Audit

We did a full test automation pass on this component last year.

**Comment by shuyangzhou** [comment]
@vicnate5 ok, so we are testing the LoggingAuditMessageProcessor, I can keep that activated.
We also have one PersistentAuditMessageProcessor which saves stuff to DB in AuditEvent table.
The info in the log and db table are the same, just different storage. Do we need the DB one activated by default?

**Comment by vicnate5** [comment]
@shuyangzhou We have a test for the DB persistence configuration, checking for entries in `Audit_AuditEvent` table. We check result of enable and disable configuration in https://github.com/liferay/liferay-portal/blob/da7778d9f64f1e661db6b5994263335f0fb4aea0/modules/apps/portal-security-audit/portal-security-audit-router/src/main/java/com/liferay/portal/security/audit/router/configuration/PersistentAuditMessageProcessorConfiguration.java#L33

If you don't activate, will it still activate if the user tries to enable with the configuration?

**Comment by shuyangzhou** [comment]
@vicnate5 yes, it can still be enabled, I am only changing the default value. The db entry is technically duplicating the log one. It is ok to default to enable one of them, but having both of them enabled by default, seems quite wasteful.

**Comment by vicnate5** [comment]
Sounds good to me, the test should still pass regardless of the default value since the test is defining the configuration at runtime.

We can use `ci test security` to run the automation.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10953

**Pull request closed without merging**
