### PR TITLE
LPS-71925 Use mega hack to lookup the name -> db-Name mapping for eac…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…h model the first time we get the column name. We have to get the XYZModelImpl class by calling super twice since XYZBaseImpl doesn't have a default constructor and to ensure the XYZ.toString() is not overridden. We assume that all primary keys are int, long, String or a generated composite.

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou please revert https://github.com/liferay/liferay-portal/commit/725247edd8763d8c920d900c54131c02300669ef when forwarding this to BChan

**Comment by jpince** [comment]
@Preston-Crary not sure if the failure above is related to your change, see https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/100741/consoleFull

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Yeah, that's a real failure.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4142

**Pull request closed without merging**
