### PR TITLE
[TS] LPS-98789 IllegalStateException is thrown when accessing a page with a WAB using Spring MVC and while simultaneously re-deploying the same WAB

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-98789

Hi @shuyangzhou ,

This pr is for the issue we discussed, regarding the **portlet.isReady()** and **UndeployedPortlet**.

It fixes the regression of [LPS-96672 - IllegalStateException is thrown when accessing a page with a WAB using Spring MVC and while simultaneously re-deploying the same WAB](https://issues.liferay.com/browse/LPS-96672).

Note: The **Avoid NPE** commit is needed to:
- Prevent the regression of [LPS-96946 - Error in console log when going to the URL of an uncreated portlet](https://issues.liferay.com/browse/LPS-96946)
- Prevent a random error I experienced during the testing of [LPS-96672](https://issues.liferay.com/browse/LPS-96672) (probably due to some race-condition)

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by vicnate5** [comment]
@ericyanLr Semver issue here
```
[exec] > Task :baseline4
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
[exec] = ================================================== ========== ========== ========== ========== ==========
[exec] * com.liferay.portlet                                MINOR      2.1.1      2.1.1      2.2.0      VERSION INCREASE REQUIRED
[exec] 	<   class      com.liferay.portlet.UndeployedPortlet
[exec] 		+   method     getInstance()
[exec] 			+   access     static
[exec] 			+   return     com.liferay.portlet.UndeployedPortlet
[exec] [Baseline Report] Mode: diff (persisted)
[exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/4.7.2/4ac4e9663d388f51f3823c8d96e7a262547663eb/com.liferay.portal.impl-4.7.2.jar
```
https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314605/AXIS_VARIABLE=0,label_exp=!master/consoleText

@shuyangzhou Functional test failures are unrelated.

**Comment by ericyanLr** [comment]
Hi @vicnate5 ,

Thanks for catching that, commit for semver is now added.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76217

**Pull request closed without merging**
