### PR TITLE
COMMERCE-7204, 8018, 8019, 8020, 8096

### PR DESCRIPTION
**Pull request by ctang3**

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:commerce

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by shuyangzhou** [comment]
@ctang3 https://github.com/shuyangzhou/liferay-portal/pull/10571/commits/90d63e14b4c3a5494f03039a1d55a867b3b0ba0d#diff-4e8bab99798dd8b268df36251e49add4340243639fdf25ad0335c31e4324e3b3 this can be enabled at the "<service-builder>" level, right? You are changing every entity in this commit.

**Comment by ctang3** [comment]
@shuyangzhou I'll test to confirm and get back to you on this. I don't recall if it was intentional because `CPDefinitionLocalization` is excluded from change tracking by not enabling change-tracking at the <service-builder> level. I'll likely need to add a TableReferenceDefinition for it if it's fine to move to the <service-builder> level.

**Comment by ctang3** [comment]
@shuyangzhou Moved the CT enabling to the `<service-builder>` level and rebuilt services, rerunning CI tests. 

Also found a tiny bug with service builder's *CTServiceImpl generation that I fixed in this commit: https://github.com/shuyangzhou/liferay-portal/pull/10571/commits/009cf06f663869c84a0948fb21849fdd34728330

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:commerce

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:stop

**Comment by ctang3** [comment]
Pushed a fix for SF failure: https://github.com/shuyangzhou/liferay-portal/pull/10571/commits/4af5f6196b14513130274bbc0b6b6c2cbebcba50

**Comment by shuyangzhou** [comment]
@ctang3 please check this compile failures and semantic version issue.

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:commerce

**Comment by ctang3** [comment]
ci:test:publications

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@ctang3 Regression here. I reproduce on my machine.

[Post-Upgrade](https://testray.liferay.com/home/-/testray/case_results/1629662819), Steps:
1. Import [MySQL database](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip) from 7.4.13 GA1
2. Upgrade to master on this branch
3. Start Portal

```
ERROR [liferay/scheduler_dispatch-6][ParallelDestination:59] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, EXCEPTIONS_MAX_SIZE=0, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@3c3ba72c, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener}}
com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:41) ~[portal-kernel.jar:?]
    at com.liferay.portal.kernel.scheduler.messaging.SchedulerEventMessageListenerWrapper._processMessage(SchedulerEventMessageListenerWrapper.java:127) ~[portal-kernel.jar:?]
    at com.liferay.portal.kernel.scheduler.messaging.SchedulerEventMessageListenerWrapper.receive(SchedulerEventMessageListenerWrapper.java:98) ~[portal-kernel.jar:?]
    at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) ~[portal-kernel.jar:?]
    at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
    at com.liferay.commerce.product.service.persistence.impl.CPDefinitionFinderImpl.findByExpirationDate(CPDefinitionFinderImpl.java:144) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitionsByExpirationDate(CPDefinitionLocalServiceImpl.java:2227) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitions(CPDefinitionLocalServiceImpl.java:493) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
    at com.sun.proxy.$Proxy1199.checkCPDefinitions(Unknown Source) ~[?:?]
    at com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener.doReceive(CheckCPDefinitionMessageListener.java:77) ~[?:?]
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:31) ~[portal-kernel.jar:?]
    ... 7 more
Caused by: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
    at com.liferay.portal.dao.orm.hibernate.ExceptionTranslator.translate(ExceptionTranslator.java:39) ~[portal-impl.jar:?]
    at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:188) ~[portal-impl.jar:?]
    at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:168) ~[portal-impl.jar:?]
    at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:61) ~[portal-kernel.jar:?]
    at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:53) ~[portal-kernel.jar:?]
    at com.liferay.commerce.product.service.persistence.impl.CPDefinitionFinderImpl.findByExpirationDate(CPDefinitionFinderImpl.java:139) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitionsByExpirationDate(CPDefinitionLocalServiceImpl.java:2227) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitions(CPDefinitionLocalServiceImpl.java:493) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
    at com.sun.proxy.$Proxy1199.checkCPDefinitions(Unknown Source) ~[?:?]
    at com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener.doReceive(CheckCPDefinitionMessageListener.java:77) ~[?:?]
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:31) ~[portal-kernel.jar:?]
    ... 7 more
Caused by: org.hibernate.exception.SQLGrammarException: could not execute query
    at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.loader.Loader.doList(Loader.java:2545) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.loader.Loader.list(Loader.java:2271) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:316) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.impl.SessionImpl.listCustomQuery(SessionImpl.java:1842) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.impl.AbstractSessionImpl.list(AbstractSessionImpl.java:165) ~[hibernate-core.jar:3.6.10.Final]
    at org.hibernate.impl.SQLQueryImpl.list(SQLQueryImpl.java:157) ~[hibernate-core.jar:3.6.10.Final]
    at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:176) ~[portal-impl.jar:?]
    at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:168) ~[portal-impl.jar:?]
    at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:61) ~[portal-kernel.jar:?]
    at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:53) ~[portal-kernel.jar:?]
    at com.liferay.commerce.product.service.persistence.impl.CPDefinitionFinderImpl.findByExpirationDate(CPDefinitionFinderImpl.java:139) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitionsByExpirationDate(CPDefinitionLocalServiceImpl.java:2227) ~[?:?]
    at com.liferay.commerce.product.service.impl.CPDefinitionLocalServiceImpl.checkCPDefinitions(CPDefinitionLocalServiceImpl.java:493) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
    at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
    at com.sun.proxy.$Proxy1199.checkCPDefinitions(Unknown Source) ~[?:?]
    at com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener.doReceive(CheckCPDefinitionMessageListener.java:77) ~[?:?]
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:31) ~[portal-kernel.jar:?]
    ... 7 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'CPDefinitionLocalization.ctCollectionId' in 'where clause'
```

I saw some [Publications test failures](https://testray.liferay.com/home/-/testray/case_results/1629632494) but I could not reproduce them locally. Noting in case [the error](https://testray.liferay.com/reports/production/logs/2022-03/test-1-26/test-portal-acceptance-pullrequest(master)/2029/functional-tomcat90-mysql57-jdk8/0/3/liferay-log.txt.gz?authuser=0) means anything to you.

Service Builder also detected changes on regen
https://testray.liferay.com/reports/production/logs/2022-03/test-1-30/test-portal-acceptance-pullrequest(master)/2410/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by vicnate5** [comment]
ci:test:publications

**Comment by vicnate5** [comment]
ci:test:publications:norebase

**Comment by vicnate5** [comment]
@ctang3 On re-run all the publication tests are good.

**Comment by shuyangzhou** [comment]
@ctang3 please rebase this pull, if it only affects the generated code, no need to rerun the tests, thanks!

**Comment by ctang3** [comment]
@shuyangzhou Rebased and squashed the updated buildService files into previous build service/versioning commits, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114902

**Pull request closed without merging**
