### PR TITLE
LPS-83992 Implement CDI requirements in Async

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou This PR contains one commit by Leon and seven commits by me that help to implement CDI requirements with Portlet 3.0 Async.

The seventh (most recent) commit contains a refactor to use a ConcurrentLinkedDeque stack to determine when beans should be destroyed.

/cc @dantewang @ChiZelin @vsingleton @rotty3000 @stiemannkj1 @vicnate5

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou The "failures unique to this pull" seem unrelated to me, especially since they are WebSphere-specific. The commits are limited to the com.liferay.bean.portlet.cdi.extension.jar module which is not used anywhere in the system.

If you agree, please review when you an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
@ngriffin7a I am closing this one and waiting for you new pull.

**Comment by ngriffin7a** [comment]
@shuyangzhou I am working on the new pull now and hope to send it today.

**Comment by ngriffin7a** [comment]
See https://github.com/liferay/liferay-portal/pull/3211

**Pull request closed without merging**
