### PR TITLE
LPS-X Move the heavy ServiceTracker opening to an async thread.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by shuyangzhou** [comment]
ci:test:jsf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:jsf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 any failure?

**Comment by vicnate5** [comment]
@shuyangzhou One possible issue found. See TCK test portal log https://testray.liferay.com/reports/production/logs/test-1-11/1600301065146/test-portal-acceptance-pullrequest(master)/7615/tck-jdk8/0/liferay-log.txt.gz

```
ERROR [fileinstall-directory-watcher][HotDeployImpl:216] com.liferay.portal.kernel.deploy.hot.HotDeployException: Error registering portlets for tck-TestModule1
com.liferay.portal.kernel.deploy.hot.HotDeployException: Error registering portlets for tck-TestModule1
```

**Comment by shuyangzhou** [comment]
@vicnate5 this failure happens to a runtime deployment, rather than a startup deployment, should not be related.

**Comment by vicnate5** [comment]
@shuyangzhou Should be OK then, all the JSF portlets deployed at startup without issues on each run.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9449

**Pull request closed without merging**
