### PR TITLE
[TS] LPS-124261

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @noornajj:

>https://issues.liferay.com/browse/LPS-124261
>
>The issue here was that the RSS toggle for blogs configuration was not being updated. This was caused by the typeSettings not getting updated because the old settings were overridding it.
To fix the issue, I created a resetConfiguration method for ConfigurationOverrideInstance and made a call to that method in processAction() for BlogsAdminConfigurationAction when the action is "update".

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jonathanmccann this issue should go to Blogs team or whoever owns portal-configuration-module-configuration, it is not a core infra issue. Please resend it to the right team.

**Comment by jonathanmccann** [comment]
@shuyangzhou I did but they told me to send it to the Core team - https://github.com/liferay-lima/liferay-portal/pull/1196#issuecomment-742449142

@adolfopa If it's not your team or Core then who should be reviewing these changes?

**Comment by adolfopa** [comment]
@jonathanmccann Sorry, but I have no idea. I think it would be best to ask in some public Slack channel.

**Pull request closed without merging**
