### PR TITLE
LPS-73667 Support retrying the datasource if it's not present

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
I also clean up a bit the logic in DataSourceFactoryImpl class.

**Comment by mdelapenya** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See my email.

**Pull request closed without merging**
