### PR TITLE
LPS-181729 On portal startup make batch engine wait for activation of underlying ResourceImpl

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @shuyangzhou please see this comment from BC https://github.com/brianchandotcom/liferay-portal/pull/134126#issuecomment-1531283529.

The idea of the PR is to have a component factory that will [schedule an ImportTask for execution](https://github.com/shuyangzhou/liferay-portal/commit/64f001952abbc5af09934c92738b1ea767e66e3e#diff-760781d7df7391517dd77dae0b22bf2b6ddd3728eb3a47e7489d642d6f1bbec1L133) but only after the [referenced service ](https://github.com/shuyangzhou/liferay-portal/commit/64f001952abbc5af09934c92738b1ea767e66e3e#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR122)becomes active. 

To achieve this @rotty3000 had to add [-ds-felix-extensions](https://github.com/shuyangzhou/liferay-portal/commit/64f001952abbc5af09934c92738b1ea767e66e3e#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR122) instruction, but Brian wants you to take a look since it's not used in the Portal so far. Please review and let us know if you have any more questions.

Thank you!

### CODE REVIEW

**Comment by rotty3000** [comment]
Hi @shuyangzhou please let me try to explain, it's a little tricky so please bare with me, I might not be totally clear the first time.

### The problem

**A _normal_ DS component factory instance does not _wait_ for @References.**

Normally, when calling `_componentFactory.newInstance(...)` on a component factory if it contains any @Reference which cannot be _immediately_ resolved, the component factory instance fails (throwing an exception in the process).

### Why do we need component factory instances?

We need a unique component instance which has specific configuration properties created programmatically (in this case, a specific target filter; [`_vulcanBatchEngineTaskItemDelegate.target`](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-760781d7df7391517dd77dae0b22bf2b6ddd3728eb3a47e7489d642d6f1bbec1R130-R133) and other associated objects.)

The only way in DS to programmatically pass custom configuration and objects to a component instances is through DS component factory (because of the method `public ComponentInstance<S> newInstance(Dictionary<String, ? > properties);`).

However, by default component factory instances are not _normal_ DS components that activate and then persist until all @References are resolved. As I mentioned earlier, by default, component factory instances fail immediately when calling `_componentFactory.newInstance(...)` if _any_ @Reference cannot be immediately resolved.

### The solution

**Make DS component factory instances behave like _normal_ components.**

This PR is taking advantage of the _non standard_ feature of Apache Felix DS called `PersistentFactoryComponent` in order to make DS component factory instances behave like _normal_ components (activate and persist until all @References are resolved.)

### The implementation of the solution

There are actually two parts to the solution.

The first part tells the `bnd` builder to add the Felix specific XML attributes to the generated component XML using the annotation [`@DSExt.PersistentFactoryComponent`](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR48)

The second part tells the `bnd` builder to add the xml schema for the custom schema to the generated component XML using the bnd instruction [`-ds-felix-extensions: true`](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-6f78708327bd8f34300d6503dbeada20fc01d3472cd19592906fdebfb7fad821R35)

**Comment by shuyangzhou** [comment]
@rotty3000 @matijapetanjek rather than jumping into the solution, can we step back a bit to talk more about the problem you have? Better to show it with a test to let me see what is broken first.

**Comment by rotty3000** [comment]
sorry, there is something broken, the timing issue of processing BatchEngineUnits on startup.

**Comment by shuyangzhou** [comment]
@rotty3000 can you give me a way to see that race? Either a test or manual steps.

**Comment by rotty3000** [comment]
@matijapetanjek do we have a test which demonstrates this failure?

**Comment by matijapetanjek** [comment]
@rotty3000 we don't, I guess nothing is stopping me from adding a test that will demonstrate the failure but that won't be completed today.

@shuyangzhou The failure is reproduced at random, it occurs on portal startup when batch import file(or [batch client extension](https://github.com/liferay/liferay-portal/tree/master/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-batch)) is present in the {liferay_home}/deploy dir. This will start a new batch engine import task. 

The problem on portal startup is when batch engine gets activated before the headless module (.*ResourceImpl) to which batch-engine delegates data read from the import file. That can happen because there is no explicit reference between the batch-engine and headless module. We fixed this by [defining that reference dynamically](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-760781d7df7391517dd77dae0b22bf2b6ddd3728eb3a47e7489d642d6f1bbec1R130), now batch engine will wait for the underlying .*ResourceImpl to become active before scheduling a BatchEngineImportTask for execution. 

To reproduce this issue manually you deploy a [batch-client-extension](https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-batch) which will start an import of a new ObjectDefinition. Before deploying the client extension stop or undeploy [object-admin-rest-impl](https://github.com/liferay/liferay-portal/tree/master/modules/apps/object/object-admin-rest-impl) module. Before the fix, batch engine would fail with NPE. 
With this fix batch-engine will wait until you start or deploy object-admin-rest-impl, and in the end you should see a new ObjectDefinition successfully imported.

**Comment by shuyangzhou** [comment]
Ok, I get what the problem is now. But I don't think the solution is right.
The reason we need to do https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/92b2416bf7288a9b66d5bfed5f6228d1f839b8e3 is because when the target BatchEngineTaskItemDelegate is registered, it needs to go through BatchEngineTaskItemDelegateRegistry and activate your instance of BatchEngineImportTaskComponent.

The exact order of this is unpredictable, which could lead the NPE you saw.

But removing the validation is not enough, at later moment, where you call BatchEngineImportTaskExecutor.execute() it still calls BatchEngineTaskItemDelegateRegistry at a later location. You still don't know whether BatchEngineTaskItemDelegateRegistry has been populated with this newly incoming BatchEngineTaskItemDelegate yet, which means the race is still there.

Also, this whole change is assuming the missing BatchEngineTaskItemDelegate is caused by startup racing. But what if the missing BatchEngineTaskItemDelegate is a true missing one due to certain modules are not deployed. User used to get a failure right away on deploying the batch-client-extension. Now the code would just quietly queuing it without any notice. How can the user know the status of the deployment?

**Comment by matijapetanjek** [comment]
@shuyangzhou I guess since there is no synchronization it is possible that serviceTracker in BatchEngineTaskItemDelegateRegistry registers BatchEngineTaskItemDelegate after BatchEngineImportTaskComponent does and starts an execution of ImportTask.

What would you suggest in this case, is it an option to have some kind of retryable in BatchEngineTaskItemDelegateRegistry#getBatchEngineTaskItemDelegate method that would fail after a defined period?

**Comment by shuyangzhou** [comment]
@matijapetanjek there should not be any kind processing time queuing or retrying logic for this. Once the deployer decides to deploy a zip, the system should give a definite result in a synchronized way, either success or failed.

The issue here is all at the deployer.

First, just for the startup race case, you could ease the issue by deferring the deployer starting time to be after "portal startup". This won't be enough to eliminate the issue, but could reduce the unnecessary attempts.

Second, the deployer should look into the zip to understand which BatchEngineTaskItemDelegates it needs. And check their availability. If they were available at the time of checking, just proceed, whatever the result is, accept it. The system can be very dynamic, this kind of check/run style could always fail for some weird reasons. But they are very rare. If some of the required BatchEngineTaskItemDelegates were missing, just complain it in log, and abort deployment. Since the deployment did not go through, the zip file stays in deploy folder, which is subjected for automatic retry at a later time.

**Comment by rotty3000** [comment]
so is the only problem that there isn't a "timeout" like mechanism to alert the user at some time after deployment? If so, this can be easily added to the current implementation.

**Comment by shuyangzhou** [comment]
@rotty3000 that's not the problem. The problem is this kind of queuing does not really eliminate the race completely, it could still happen.
Also queuing on truly missed BatchEngineTaskItemDelegates would cause confusion. Since user does not get error on deployment, the processing logic just simply not run without any notice. Adding timeout would add another layer of async activity and even with that the error log only happens after the timeout, which is still confusing. 
But the key issue here is, the solution does not eliminate the race.

**Comment by rotty3000** [comment]
Can you explain in more detail how the solution does not eliminate the race? Because I don't understand.

**Comment by shuyangzhou** [comment]
I explained it here https://github.com/shuyangzhou/liferay-portal/pull/11048#issuecomment-1533252092

**Comment by matijapetanjek** [comment]
If I understood correctly we have two things happening in parallel after BatchEngineTaskItemDelegate gets registered in the service registry:
1. `BatchEngineTaskItemDelegateRegistry's` serviceTracker registers BatchEngineTaskItemDelegate
2. [BatchEngineImportTaskComponent @Reference](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR122) is resolved, BatchEngineImportTaskComponent is activated --> [BatchEngineImportTaskComponent submits ImportTask](https://github.com/shuyangzhou/liferay-portal/pull/11048/commits/64f001952abbc5af09934c92738b1ea767e66e3e#diff-fd38add87d8d68ea22d73569fa362d6db6638d38a4acc420bd56e4a78276089fR87) to portal's ExecutorService --> portal's ExecutorService starts [execution of ImportTask](https://github.com/liferay/liferay-portal/blob/master/modules/apps/batch-engine/batch-engine-service/src/main/java/com/liferay/batch/engine/internal/BatchEngineImportTaskExecutorImpl.java#L72) --> BatchEngineImportTaskExecutor calls `BatchEngineTaskItemDelegateRegistry` to get BatchEngineTaskItemDelegate

In this case I guess the issue is that in theory, it could happen that the whole 2. flow could be executed before 1.?

**Pull request closed without merging**
