### PR TITLE
LPD-20793 Temporary workaround by off loading all portlet default per…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…mission population to a global single thread pool to avoid race condition.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgarde

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@javalosjr96 this should prevent the random ResourcePermission startup errors.

**Comment by vicnate5** [comment]
@shuyangzhou This one does not look good. See https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2552325540

**Pull request closed without merging**
