### PR TITLE
Startup optimization 170 disable persistent audit message processor

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:security

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Audit tests passing and no regressions found. But I am checking if we need to always enable on CI: https://github.com/vicnate5/liferay-portal/pull/2267

**Comment by vicnate5** [comment]
@shuyangzhou Let's only enable for Audit tests. See https://github.com/shuyangzhou/liferay-portal/pull/10954.

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
