### PR TITLE
LPS-X Merge AuditMessageFactoryUtil/AuditMessageFactoryImpl into Audi…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…tMessageFactory

# breaking_change_report

## What
portal-kernel/src/com/liferay/portal/kernel/audit/AuditMessageFactory.java portal-kernel/src/com/liferay/portal/kernel/audit/AuditMessageFactoryUtil.java

AuditMessageFactoryUtil and AuditMessageFactoryImpl logic are merged into AuditMessageFactory

## Why

This interface/impl/util separation does not have any value. Merge it into single class to avoid the unnecessary module.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
No regressions found. But there is a semantic versioning issue:
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.audit                    MAJOR      8.0.0      8.0.0      9.0.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.portal.kernel.audit.AuditMessageFactory
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     getAuditMessage(java.lang.String)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,java.lang.String)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     getAuditMessage(java.lang.String,long,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			+   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.kernel.audit.AuditMessageFactoryUtil
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getAuditMessage(java.lang.String)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessageFactory()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessageFactory
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   interface  com.liferay.portal.kernel.audit.AuditMessageFactory
     [exec] 		-   access     abstract
     [exec] 		-   method     getAuditMessage(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] 		-   method     getAuditMessage(java.lang.String,long,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,com.liferay.portal.kernel.json.JSONObject)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.audit.AuditMessage
     [exec] [Baseline Warning] Bundle Version Change Recommended: 129.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/128.0.1/b943da48c218d637e514b38a0391f5f0cab97ac3/com.liferay.portal.kernel-128.0.1.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-30/test-portal-acceptance-pullrequest(master)/8289/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143406

**Pull request closed without merging**
