### PR TITLE
LPS-155534 Avoid unnecessary NoSuchUserException

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@shuyangzhou no regressions found

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
