### PR TITLE
Freemarker threadpool

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian This breaks the Portal UI on Wildfly and Jboss.

Wildfly

See errors here: https://testray.liferay.com/reports/production/logs/test-1-22/1607064436269/test-portal-acceptance-pullrequest(master)/7582/functional-smoke-wildfly140-mariadb102-jdk8/0/0/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
@tinatian this is most likely caused by "direct.servlet.context.enabled=true", try to disable it and test it again. If it is fixed after disabling, we will need to add logic into DirectRequestDispatcherFactoryImpl to detect whether it is safe to get direct request dispatcher or must have to get the real appserver provided RequestDispatcher base on some ThreadLocal indicator.

And if this is a jboss/wildfly only thing, make sure the threadlocal is only checked for those to avoid further performance penalties. JBoss/wildfly must have some thread local authentication info that got lost when we async the render.

I am currently working on a refactor to this pull already, do your testing first, once I am done I will send the pull back you. Then you can apply it on top.

**Comment by vicnate5** [comment]
Also seeing problems on Tomcat with dropdowns not displaying on click. This is across portal in many different portlets.

Example in Blogs:
Dropdown

Logs: https://testray.liferay.com/reports/production/logs/test-1-22/1607064436269/test-portal-acceptance-pullrequest(master)/7582/functional-tomcat90-mysql57-jdk8/4/20/liferay-log.txt.gz

You can ignore the NoSuchUserExceptions, it is due to https://issues.liferay.com/browse/LPS-123610

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/tinatian/liferay-portal/pull/2056

**Comment by vicnate5** [comment]
Wildfly issue not fixed `direct.servlet.context.enabled=false`. Still reproduced: https://gist.github.com/vicnate5/4052f9e995f52baecc525bdb0ba49031

**Pull request closed without merging**
