### PR TITLE
[Configurator]LPS-132259 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@hhuijser Could you please take a look at the SF failure? 
I run "ant format-source" on this pull, I would see some files changed, but if I run "ant format-source" another time, the changed files are gone.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by hhuijser** [comment]
I'll have a look

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@wincent `prettier` is conflicting with SF formatting for `json` files (adding empty lines at the end and other stuff). Can we have prettier ignore `json`?

@tinatian if all the other tests pass, you can send this to Brian directly

**Comment by wincent** [comment]
> @wincent `prettier` is conflicting with SF formatting for `json` files (adding empty lines at the end and other stuff). Can we have prettier ignore `json`?

I don't work for Liferay any more but @bryceosterhaus should be able to make that change.

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks
Tina

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian No regressions found in test results

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/101985

**Comment by bryceosterhaus** [comment]
@hhuijser I can take a look. Feel free to ping me on any future formatting issues with prettier or our js tools in general.

**Pull request closed without merging**
