### PR TITLE
[TECHNICAL-SUPPORT] LPS-67452 StringUtil.splitLines(String) is inefficient

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-67452

Hi Shuyang,

István's notes:

> _SpringUtil.splitLines(String)_ is inefficient when we pass huge strings to it. In corner cases it may take ~15 minutes or even more. (See [LPS-67452](https://issues.liferay.com/browse/LPS-67452) for an example.)
> 
> The improvement is obvious even if we consider the password change scenario described on the LPS using the out-of-the-box _words.txt_ file:
> 
> | Environment | Execution time |
> | --- | --- |
> | Affected | 2100ms. |
> | Fixed | 6ms. |

**Note**: using classes in a script from util-java and other packages are not allowed since https://issues.liferay.com/browse/LPS-65683 that's why I've added a different reproduction code for master.

Cheers,
Tibor

---

Author: @istvansajtos
Reviewers: @lipusz

### CODE REVIEW

**Comment by shuyangzhou** [comment]
This is wrong, it is the opposite of optimization. String.split() is using regex which is very slow.
The measurement is wrong, you can not do performance test just with a System.currentTimeMillis(), with no warmup, no jvm dead code/elimination detection protection. And more importantly, not testing in Groovy code which is adding tons of overhead.

Beside the logic is wrong too, it used to split by '\r', '\n', '\r\n', with your change, it can only do '\r' and '\n'. You can see how it is breaking the exist StringUtilTest.testSplitLines() test.

@istvansajtos @lipusz

**Comment by lipusz** [comment]
Hi Shuyang,

It's my bad... I forgot to re-deploy the portal-kernel before running the test locally so I didn't notice the failures:

```
tibusz@tibusz-E6520:~/git/liferay/ce/liferay-portal/portal-kernel{pull-request-138-LPS-67452}$ ant test-class -Dtest.class=StringUtilTest
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Buildfile: /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/build.xml

init-compile:

compile:

test-class:
    [mkdir] Created dir: /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-classes/unit
    [mkdir] Created dir: /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-results/unit
     [copy] Copying 6 files to /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-classes/unit
    [javac] Compiling 171 source files to /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-classes/unit
    [javac] Note: /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/process/local/LocalProcessExecutorTest.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [junit] Running com.liferay.portal.kernel.util.StringUtilTest
    [junit] Testsuite: com.liferay.portal.kernel.util.StringUtilTest
    [junit] Loading file:/home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-classes/unit/system-ext.properties
    [junit] Tests run: 52, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.245 sec
    [junit] Tests run: 52, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.245 sec
    [junit] 
    [junit] Testcase: testSplitLines(com.liferay.portal.kernel.util.StringUtilTest):	FAILED
    [junit] expected:<4> but was:<7>
    [junit] junit.framework.AssertionFailedError: expected:<4> but was:<7>
    [junit] 	at com.liferay.portal.kernel.util.StringUtilTest.testSplitLines(StringUtilTest.java:565)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.kernel.util.StringUtilTest FAILED

BUILD SUCCESSFUL
Total time: 7 seconds
tibusz@tibusz-E6520:~/git/liferay/ce/liferay-portal/portal-kernel{pull-request-138-LPS-67452}$
```

Sorry again.

**Comment by shuyangzhou** [comment]
No problem :)

**Comment by lipusz** [comment]
Hi Shuyang,

I've played a bit with this, updated the logic and created a simple Java project to test.

```java
package com.liferay.test;

import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.IOException;

public class LPS67452Test {

	public static void main(String[] args)
		throws IOException {

		Thread currentThread = Thread.currentThread();

		String input = StringUtil.read(
			currentThread.getContextClassLoader().getResourceAsStream(
				"words.txt"));

		// Warm-up

		System.out.println("Warm up - Invoking both methods 10 times.");

		for (int i = 1; i <= 10; i++) {
			StringUtil.splitLines(input);
		}

		for (int i = 1; i <= 10; i++) {
			improvedSplitLines(input);
		}

		// Test StringUtil.splitLines

		System.out.println("Testing StringUtil.splitLines: Invoking 5 times");

		long start;
		long end;

		for (int i = 1; i <= 5; i++) {
			start = System.currentTimeMillis();

			StringUtil.splitLines(input);

			end = System.currentTimeMillis();

			System.out.println(
				i + " run of StringUtil.splitLines took " + (end - start) +
				"ms.");
		}

		System.out.println();

		// Test improvedSplitLines

		System.out.println("Testing improvedSplitLines: Invoking 5 times");

		for (int i = 1; i <= 5; i++) {
			start = System.currentTimeMillis();

			improvedSplitLines(input);

			end = System.currentTimeMillis();

			System.out.println(
				i + " run of improvedSplitLines took " + (end - start) +
				"ms.");
		}
	}

	public static String[] improvedSplitLines(String s) {
		if (Validator.isNull(s)) {
			return _emptyStringArray;
		}

		s = s.trim();

		return s.split("(\r\n)|[\r\n]");
	}

	private static final String[] _emptyStringArray = new String[0];

}
````

It gives the following results:
````
1 run of StringUtil.splitLines took 3219ms.
2 run of StringUtil.splitLines took 3204ms.
3 run of StringUtil.splitLines took 3273ms.
4 run of StringUtil.splitLines took 3245ms.
5 run of StringUtil.splitLines took 3418ms.

1 run of improvedSplitLines took 32ms.
2 run of improvedSplitLines took 21ms.
3 run of improvedSplitLines took 14ms.
4 run of improvedSplitLines took 10ms.
5 run of improvedSplitLines took 14ms.
````

**The updated "improvedSplitLines" now passed StringUtilTest**:

````
tibusz@tibusz-E6520:~/git/liferay/ce/liferay-portal/portal-kernel{master}$ ant test-class -Dtest.class=StringUtilTest
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Buildfile: /home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/build.xml

init-compile:

compile:

test-class:
    [junit] Running com.liferay.portal.kernel.util.StringUtilTest
    [junit] Testsuite: com.liferay.portal.kernel.util.StringUtilTest
    [junit] Loading file:/home/tibusz/git/liferay/ce/liferay-portal/portal-kernel/test-classes/unit/system-ext.properties
    [junit] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.226 sec
    [junit] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.226 sec
    [junit] 

BUILD SUCCESSFUL
Total time: 2 seconds
````

What do you think? Can I reopen the LPS and send you the new fix? The Java project uses latest portal-kernel.jar. I can attach the project to the LPS.

Thank you for your time again.

Br,
Tibor

@shuyangzhou

**Comment by shuyangzhou** [comment]
@lipusz you can not do performance tests like this, that is just not going to work. JVM does tons of runtime optimization, one of many that may affect this is "Eliminate dead code", see http://docs.oracle.com/cd/E15289_01/doc.40/e15058/underst_jit.htm . Not even talking about others like GC affects, native code compilation, etc...

What you guys trying here is called marco benchmark, which is a very tough topic which countless pitfalls. Unless you really know what JVM internal does, you can make mistake in almost every turns. There are tools to ease this, like JMH http://openjdk.java.net/projects/code-tools/jmh/, but still it needs to be used with cares and understanding of JVMs, otherwise the results will not really mean anything.

**Comment by lipusz** [comment]
Hi Shuyang,

So, unless we cannot provide a "valid" measurement you cannot accept this logic, right?

What if we consider the 2nd scenario from the LPS to test the difference?

Actually, the proposal came from a customer. We were hesitating to send the change at first and we can close the report as "Won't fix", but in this case we need to provide a proper explanation why their proposed fix is not acceptable.

From their point of view, the password change takes a very long time when the dictionary is big and after their/my improved method, the performance is better, so at this point it's really hard for Support to say they're not right when they can see the difference clearly in their tests also.

Thank you for helping us to proceed either way (Won't fix, Feature Request or Bug).

Cheers,
Tibor

@shuyangzhou

**Comment by shuyangzhou** [comment]
@lipusz 
In general, we only make performance improvements in 2 cases.
1) The problem is so simple that, one can easily tell one impl is obviously better than another, then no benchmark test is required at all, just change it.
2) For any cases that one can not easily tell, a benchmark must be provided to prove one impl is better than the exist one.

In this case, it is actually the 1), as the jdk String.split() is using regex, which is obviously heavier than plain text indexing search. I am not saying our StringUtil.split() is in the best form it could be, I am just saying it is at least on the correct direction to not use regex for basic tasks like this. And most likely, by analyzing and experience, it should be better than JDK String.split().

No code is perfect, as no developer is either. It is possible that StringUtil,split() is making some silly mistake to perform poorly. However it needs to be proved first, before anyone can request a "fix" or improvement. And so far, the tests you provided is not proving the issue in the correct way.

Make sense?

**Pull request closed without merging**
