### PR TITLE
Portal preference value impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@slnn please run a check for login case, this is meant for fixing the PortalPreferenceValue cache issue. And it should not cause other regressions.

**Comment by shuyangzhou** [comment]
ci:report:12127127

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by slnn** [comment]
HI @shuyangzhou 

Here are test results on Logn, no regression appeared


Portal Version | Git Id | Session Count | Session Count Chage | Mean Time of Login | Portal CPU Usage (%) | DB CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | b61046a | 10374 | - | 289 | 94,94,94 | 3,3,3
PR | - | 10420 | 0.4434162329 | 293 | 94,95,93 | 3,3,3

From the ehcache-jmx.htm, only baseline has the item for com.liferay.portal.kernel.dao.orm.EntityCache.com.liferay.portal.model.impl.PortalPreferenceValueImpl

Portal Version | Git Id | Name | Object Count | Hit Count | Hit Percentage | Miss Count | Miss Percentage
-- | -- | -- | -- | -- | -- | -- | --
Baseline | b61046a | com.liferay.portal.kernel.dao.orm.EntityCache.com.liferay.portal.model.impl.PortalPreferenceValueImpl | 200000 | 32 | 2.28E-05 | 1405248 | 0.9999772287
PR | - | - | - | - | - | - | -

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151141

**Pull request closed without merging**
