### PR TITLE
LPS-104241 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://github.com/shuyangzhou/liferay-portal/pull/8574 with test fix

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@barrosdennys FYI https://github.com/shuyangzhou/liferay-portal/pull/8577/commits/058fc791f597558da94261fff59c35fe9ea8947f

**Comment by vicnate5** [comment]
@tinatian The Drools test ran, but the module failed to compile for the same reason I saw earlier at head, it looks like a Gradle/CI problem

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compileOnly() for arguments [{group=com.liferay.portal, name=com.liferay.portal.impl, version=default}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by vicnate5** [comment]
Added a temp fix so we can get results from the Drools test

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Drools test passed https://testray.liferay.com/home/-/testray/case_results/892326300

@shuyangzhou This is ready now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81388

**Comment by tinatian** [comment]
Hi @dantewang ,
Please note that `ci:test` does not always cover the test cases in `ci:test:relevant`. 
Like in this case, `ci:test:relevant` will trigger the drools test, while `ci:test`  won't. So please always run both of them for deprecation stuff.

Thanks.
Tina.

**Pull request closed without merging**
