### PR TITLE
[ResourceAction-Bug Fix]LPS-115508

### PR DESCRIPTION
**Pull request by tinatian**
FYI @JavierDeArcos

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
> FYI @javierdearcos

Great. Thank you very much for the catch! 😊

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
