### PR TITLE
Lps 180148 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou The only issue here was on SQL Server startup log https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/330/functional-smoke-tomcat90-sqlserver2019-jdk8/0/0/liferay-log.txt.gz

I was unable to reproduce locally after a few tries, but it could be random. I don't see it happening upstream.

If you want to try locally, you can use `ant -f build-test.xml start-docker-database-sqlserver` to generate a docker container and portal-ext

If the error seems unrelated to your changes, we can move forward and I can just keep an eye out for it again.

**Comment by vicnate5** [comment]
ci:test:setup-wizard

**Comment by vicnate5** [comment]
running another suite for quick way to see more SQL Server results on CI.

**Comment by vicnate5** [comment]
ci:test:setup-wizard

**Comment by vicnate5** [comment]
@shuyangzhou I don't see the same error again on the new results, so this should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132673

**Pull request closed without merging**
