### PR TITLE
[TS] LPS-111332

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @dacousalr,
Shuyang is out and I will take care of this pull. Please add unit test to cover the part you changed in PortalImpl, and send me a pull.

Thanks.
Tina.

**Comment by crodriguezy** [comment]
Hi @tinatian , please see the updated PR including the test: https://github.com/tinatian/liferay-portal/pull/1792
Thank you.

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/1805

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
