### PR TITLE
COMMERCE-2475 Dispatch framework

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @shuyangzhou here is a new PR with DispatchTrigger entity. Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek this https://github.com/shuyangzhou/liferay-portal/pull/9428/commits/f1c58743bd1c714b5b709ccda6e9b6045f6be0e5 is a confusing renaming. In general sense, a task is an one time only job. Once done it is done. You won't grab it out of a service tracker map to pair it with different dispatchTriggerId to execute again and again.
The "Executor" name fits better here, what's the reason you want to make this naming change?

**Comment by shuyangzhou** [comment]
@matijapetanjek this pull is taking too many rounds, can you resend it to include just enough adjustment changes from Brian's previous request? That way we can flush out the first part sooner. For all your renaming changes, send them as a follow up, with some explanations. We will at least make some progress in this way.

**Comment by matijapetanjek** [comment]
@shuyangzhou My idea was coming from Java perspective and ScheduledExecutorService - Runnable relation. Similar to that in Dispatch framework I saw DispatchMessageListener as ExecutorService which is responsible for finding and executing "tasks" based on the trigger, and I saw ScheduledTaskExecutorService as Runnable which user implements with his custom logic (and which doesn't contain any logic that deals with how or when the "task" will be executed).

No problem, I will send new PR without the rename, I should've probably sent smaller PRs which would be easier to review from the start, I'll remember that for the next time! Thank you for your patience!

**Pull request closed without merging**
