### PR TITLE
Lps 90030

### PR DESCRIPTION
**Pull request by mtambara**
Sent on top of https://github.com/brianchandotcom/liferay-portal/pull/67565

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/67721

**Pull request closed without merging**
