### PR TITLE
Lps 145063

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1337401_868

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@shuyangzhou 
Look good. No unique ffailure. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112268

**Pull request closed without merging**
