### PR TITLE
LPP-26232 Added getSiteAdminURL which returns the correct URL when the protocol is https

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
see: https://github.com/ealonso/liferay-portal/pull/1033, all test are in green

**Comment by Preston-Crary** [comment]
@joshuacords, please update your commit message to use the LPS instead of the LPP.

**Comment by joshuacords** [comment]
Sorry, I missed that. I reopened here: https://github.com/Preston-Crary/liferay-portal/pull/350

**Comment by joshuacords** [comment]
ci:close

**Pull request closed without merging**
