### PR TITLE
LPS-87997 Protect against directory traversal

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@mtambara this is a bit overkilled, right? What if my tomcat is under a path like "a..b" ?

**Comment by mtambara** [comment]
Force pushed, searching for "/../" now

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66134

**Pull request closed without merging**
