### PR TITLE
LPS-107618 Substitute % to handle to allow percentage instead of failing silently.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan this for me, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good. None of the DB2 integration tests reported results, but looks like a CI problem.

**Comment by vicnate5** [comment]
Sorry, mis-reported, it was none of the JDK11 integration tests that ran.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83891

**Pull request closed without merging**
