### PR TITLE
Npm

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan the results for me, thanks!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou Will need to wait for bundle build for me to confirm manually, but there is 1 unique failure in the functional tests:

Steps to Reproduce:
1. Navigate to Product Menu > Site Administration > Content & Data > Dynamic Data Lists
2. Add a new Data Definition with a Text field set to "Repeatable"
3. Add a new List with the created Data Definition
4. Add a 'Dynamic Data Lists Display' portlet to a page
5. Select the created List
6. Add a new record via "Dynamic Data Lists Display' portlet

Expected:
Field repeatable icon displays

Actual:
Field repeatable icon missing

after0

Testray link https://testray.liferay.com/home/-/testray/case_results/679160406

**Comment by vicnate5** [comment]
@shuyangzhou must be a fluke, cannot reproduce manually.

**Comment by shuyangzhou** [comment]
Great, thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75836

**Comment by vicnate5** [comment]
Also ran the test locally, it passed.

**Pull request closed without merging**
