### PR TITLE
COMMERCE-7701 Backoff when the incoming AccountEntryUserRel is the de…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…fault one. Otherwise it will cause circular deletion infinite loop when AccountEntryUserRel is leftover for DataGuard to do auto deletion.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
Resolves all the test hangs for me locally.

**Comment by vicnate5** [comment]
Test failure here looks to be unrelated, passes locally.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109359

Thanks @vicnate5 !

**Pull request closed without merging**
