### PR TITLE
[TECHNICAL-SUPPORT] LPS-83494 Some resource bundles cannot be overriden

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou this one is likely to require rebasing if we wait on it at all.

CC @marianoalvarosaiz

### CODE REVIEW

**Comment by Preston-Crary** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/577 for test results.  Looks okay to me.

**Comment by jcampoy** [comment]
Hi @shuyangzhou 

we need to go ahead with any kind of fix because a customer has several projects affected by the issue, and their developments, upgrade, and go live deadline depends on it. Please, Could you take a look at this PR? 

Best regards.
Jose

**Comment by shuyangzhou** [comment]
@Preston-Crary is going to redo this in a different way. This solution is way too messy, we can not fix it like this.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6658

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 why is it messy?

With the new solution:

1. We're going to use an Util class from a component which we don't recommend, which depending on the lifecycle can cause NullPointerExceptions.

2.- I guess that in the components that already have a reference to a ResourceBundleLoader we would need to call instead ResourceBundleUtil, but that means two things: in the component we would have a reference that hasn't been overridden (since it isn't changed to GREEDY and DYNAMIC) and someone can use it (resulting in being unable to retrieve the overridden keys), and if we decide to remove the reference then the component can be activated without a ResourceBundleLoader (so there isn't a reference check). In my opinion, having a reference not updated, but that can be used is messy, besides calling ResourceBundleLoaderUtil from ResourceBundleUtil doesn't seem clear from an abstraction point of view taking into account that ResourceBundleLoader is an upper layer to be able to handle different ResourceBundle.

Kind regards.

/cc @Preston-Crary, @jcampoy

**Comment by marianoalvarosaiz** [comment]
Hi @Preston-Crary,
 regarding your points:

1. Not so sure about that, the required call implies less lines for sure, but now it would be need to change not only the places where we aren't using correctly the ResourceBundleLoader, but also the ones where the reference is declared properly a change will be needed.
2. I wasn't aware of this new change in the requirements/design, and, at least, it wasn't valid when the rest of the current references (not the ones defined in this pull) were declared.
3. It could be debatable, it's easier to use, although it should be documented everywhere and, maybe, change the SF tool to avoid old use, but not always is easy to support a product where the management is done in the backdoor making difficult for beginners to follow the code, besides it's also difficult to explain the users that in some cases they should use references and in others it's better to have a main common class where by trackers we coordinate the behaviour.
4. Without empirical facts, I, at least initially, agree.

Additionally, have you done some research about if removing ResourceBundleLoader wouldn't imply modifying the version of some modules in case of protected attributes? Taking into account that the new call implies changing the current paradigm used in the portal, we believe that commiting our changes is a better approach as it's less risky (remember the customer is still waiting). Later on the framework can be reengineered in a new story following your perspective.

Kind regards.

/cc @jcampoy, @almonwork

**Comment by Preston-Crary** [comment]
1. Yes, less lines of code - that's what I mean.
2. It's not a requirement, it's just something that would be good to do - a reason to go in this direction.
3. I'm saying we want to use the Util in all cases.

We can always leave the field and deprecate it if there's a protected field we cannot remove.

I'm relaying the information that @shuyangzhou and I discussed and the reasons why he came to this choice.

**Comment by Preston-Crary** [comment]
"Improvements are restricted to development branches"
This is not true, the change can still be backported.

**Comment by shuyangzhou** [comment]
@almonwork  @marianoalvarosaiz I sent the pull to Brian at https://github.com/brianchandotcom/liferay-portal/pull/62441

This is the right solution. The previous one is not. I think @Preston-Crary has explained all the reasons why we prefer it. I am not quite getting your counter points. This change is for sure backportable. This is only an implementation change, not a breaking change. And if customer still has their own @Reference ResourceBundleLoader usage in their codebase, it will work as before, we are not changing that.

If you still think otherwise, please reorganize your points, and highlight out your concerns. We can talk about it.
Thanks!

**Comment by almonwork** [comment]
Hi,

Everything is technically backportable. But not everything has to be backported. The more changes and variations we backport, the higher the risk for unwanted behaviours, unexpected errors and custom development breakage. Now we have 2 ways to do something. It is just a matter of time until they get out of sync and we will have another problem.

Reengineering everything is an option. But it should be the very exception, not the rule. Specially when there is an alternative.

Regards
  Alberto

**Comment by shuyangzhou** [comment]
This is less change, in a more consistent way, and most importantly can be SF enforced (after a full system cleanup, which does not have to happen right away), that's why this is better not only from engineering point of view but also for backport.

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou, @Preston-Crary 
 we see your points and understand some of the reasons of your change, so we can prolong the discussion after, right now we prefer to focus on solving the LPS.

Currently the sent PR only provides a new mechanism of calling an overridden ResourceBundle, but it still is needed to call the utility method at least in the same places as ours, and it will be recommended to do a full system clean up as you point. From what we view during our rejected pull request, there is the need to change it in (hope it helps):

- Those places where we use a ResourceBundleLoader with a non greedy-dynamic configuration, since it's required to refresh the overridden module in order to make changes visible (which isn't an option in automatic containers). Files to modify (there can be more, since some days have passed by): https://github.com/Preston-Crary/liferay-portal/pull/574/commits/437b813f6fa37a5fcdab9cff97faccaeef420dda
- Optionally remove the places where we are manually aggregating the portal ResourceBundleLoader to the module one, since it's not needed due to https://github.com/Preston-Crary/liferay-portal/pull/574#issuecomment-412034585
- Optionally remove the use of ResourceBundleLoaderProvider or at least analyze its deprecation since they are, probably, no longer needed.
- Perform a clean up in those places where the reference ResourceBundleLoader was already greedy and dynamic because it's way too confuse and error prone to have a couple of implementations to perform the same functionality.
- When the previous step is completed create a SF rule to avoid the use of something different to ResourceBundleUtil
- It will also be helpful to adapt the documentation, not the one that explains how to override a Liferay module ResourceBundle, but to inform the developer how to create a module that can have its ResourceBundle overridden.

So, are you planning to implement some of this points? We're going to reopen the LPS since at least the first point is mandatory to consider it fixed.

Kind regards.

**Comment by Preston-Crary** [comment]
Hi @marianoalvarosaiz,

this is correct.  Can you send me the changes for the required part?  I'll do the other optional parts and ask Hugo and Peter to create the SF rule.

Thanks

**Comment by marianoalvarosaiz** [comment]
Hi @Preston-Crary,
 OK, we'll do the first point, and afterwards open a LPS to track the other optional parts.
Regards.

**Pull request closed without merging**
