### PR TITLE
LPS-59342 SF

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
hey @shuyangzhou 

there seems to be random tests failing... as you can see these two invocations yielded different errors. Actually, when I sent the pull to myself, there weren't any poshi tests failing. 

I have not much experience reading Poshi reports, but I can't make any sense reading the latest one. It seems to be failing because the status is not `Pending` but, at the same time, the snapshot shows the status as `Pending`. 

If you know this is caused by my pull please give me some pointers on how to further debug these. 

Thanks in advance. 

Carlos.

**Comment by shuyangzhou** [comment]
Ok, that's fine, don't worry about it, I will check it a bit later.

Sorry, it has been a very busy week, I will try to get on to this pull tomorrow or in the weekend.

Will ping you if I run into any issue.

**Comment by csierra** [comment]
It is ok @shuyangzhou, I know you have been busy...

thx for your help...

Bests.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/32191

**Pull request closed without merging**
