### PR TITLE
Lps 126920

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/33117

**Comment by vicnate5** [comment]
@shuyangzhou Did you close this with the correct link?

Testing completed, this should be good to go.

I found one other minor issue where the user can modify the UI in a virtual instance and the changes incorrectly show in the UI. However, we just need to block the user from modifying the overridden value to avoid these inconsistencies (it is also inconsistent in the main instance because the UI doesn't match the DB values).

**Comment by vicnate5** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 yeah, my bad, I meant to close a pull on the ee side, used the wrong tab. This pull should go out, we will talk to Brian tomorrow to find someone to finish off the UI part of it.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/98142

**Pull request closed without merging**
