### PR TITLE
[Commerce License]LPS-113730

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
FYI @vicnate5 Here is the commerce license support. You can start testing if no unique ci failures.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9277

**Pull request closed without merging**
