### PR TITLE
LPS-135504 portal-lang

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
@shuyangzhou one thing @jhinkey mentioned is we should have a way to easily customize the keys here. Do you have an idea for that part? I'm thinking maybe we add a bundle tracker in the new portal-lang module and a special bundle header we use to override using the same logic as the bundle activator here. My initial plan was to have them use a bundle fragment to fully override the language properties but that seems like a bad idea since it would require being updated every release/upgrade.

**Comment by shuyangzhou** [comment]
@Preston-Crary we are only talking about customizing portal lang keys, not for those already inside modules, right? Do we need to worry about double customizing of the same key which would certainly causing some ordering issue. I think it would better be a dedicated interface to contribute to portal resource bundle overwriting, and use a service tracker to collect them.

**Comment by Preston-Crary** [comment]
@shuyangzhou that's correct, only portal lang. I think we can assume they only have 1 customization. So should we create a portal-lang-api for that?

**Comment by Preston-Crary** [comment]
It really depends where we go from here. It sounds like we only want to have portal-lang. Should I add customization support in this ticket to be safe?

**Comment by shuyangzhou** [comment]
Yeah, technically we are customizing portal-lang. But I doubt we can just "assume" there is exactly 0 or 1 customization for each portal lang key. Duplication will come over time on purpose or by accident, we must define clear behavior for that, in order to be strict.

**Comment by Preston-Crary** [comment]
Makes sense, if you're fine with the changes so far I'll close this and add some customization support. I think it should be a bundle API because it would be annoying to customize multiple locales if each one needs an impl class.

**Comment by shuyangzhou** [comment]
Yeah, sure, please go for that.

**Comment by jhinkey** [comment]
That's great, guys. Yeah, we've had people ask about handling of multiple customizations of the same language key.

**Comment by Preston-Crary** [comment]
Alright, will add a layering extension point and resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/10169

**Pull request closed without merging**
