### PR TITLE
Lps 74029 Add place holder for cluster back

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@shuyangzhou I tested it locally and it works, let's wait for CI result.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by tinatian** [comment]
I will rebase and resend

**Comment by tinatian** [comment]
Hi @Ithildir,
The code you changed has conflicts and unable to merge, could you please do a rebase?

Thanks
Tina.

**Comment by tinatian** [comment]
@Ithildir Sorry, wrong pull

**Comment by tinatian** [comment]
@shuyangzhou Andrea will rebase and send a new pull about this.

**Comment by Ithildir** [comment]
Sent to https://github.com/shuyangzhou/liferay-portal/pull/4650.

**Pull request closed without merging**
