### PR TITLE
Register initial deployment upgrade steps cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou 

Semver error
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/static/portal/portal-upgrade-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.upgrade.registry                MAJOR      4.1.0      4.1.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.portal.upgrade.registry.UpgradeStepRegistrator$Registry
     [exec]     		-   method     registerInitialDeploymentUpgradeSteps(com.liferay.portal.kernel.upgrade.UpgradeStep[])
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 11.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/622/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
