### PR TITLE
LPS-147867 Making the upgrade process cluster aware

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-145867

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
Hi @shuyangzhou, I send you this pull request as indicated by @brianchandotcom in Slack. This is the new safety feature to prevent two nodes to run the database upgrade at the same time. Next I comment briefly the design of the implementation to easier you the understanding of it.

There are two new properties in the portal:
- upgrade.database.managed.startup: Defines if this new feature is going to be used or not
- upgrade.database.lock.refresh.time: Defines the period of time between lock refreshes and lock checks.

When the portal is starting, in case of the property for auto upgrade is enabled, it tries to acquire a lock before executing the upgrade via the new method _acquireLock (when the upgrade is finished the lock is released). In case it cannot get the lock, keeps waiting. If the property for auto upgrade is not enabled, the portal waits until there are no locks in the database before starting the portal via the new methods waitForLocks.

Method _acquireLock:
Checks if there is an existing lock in the database. If there is a lock, checks the expiration date, if not expired, sleep the period of time indicated in property upgrade.database.lock.refresh.time. If expired, deletes the lock and tries to acquire a new one. If there is not an existing lock, it tries to acquire a new one. When a lock is acquired, a new thread is spawned to refresh it every upgrade.database.lock.refresh.time - 1 second intervals. After that, the method returns, allowing the upgrade for being executed. When the upgrade finishes, the methods _releaseLock is called.
NOTE: It is not possible for two nodes to get a lock at the same time, as the unique constraint of the table Lock_ would be violated, so only the first node with a successful insert in the table will get the lock, and the others will keep waiting.

Method _releaseLock:
Kills the refresh lock thread and deletes the lock from the database.

Method waitForLocks:
Is an infinite loop that checks if there is an existing lock. If there is not a lock, it returns, allowing the portal to start. If there is a lock, it checks if it is expired. If it is not expired, sleep the period of time indicated in property upgrade.database.lock.refresh.time. If expired, it deletes the lock and sleeps the period of time indicated in property upgrade.database.lock.refresh.time before checking it again, just in case another node with the auto upgrade property enabled would start in that period of time. 

Please let me know what you think about the solution. Any suggested improvement or recommendation about better ways to implement this feature are welcome. Thanks!

**Comment by shuyangzhou** [comment]
@LuisOrtiz89 I was out of office most time last week, maybe I missed the slack message. Can you point me to it? The only thing I got is https://github.com/brianchandotcom/liferay-portal/pull/115475#issuecomment-1084842413

**Comment by LuisOrtiz89** [comment]
@shuyangzhou Sure! The message can be found here: https://liferay.slack.com/archives/C030N6KEK7T/p1648765712789369?thread_ts=1646838999.128359&cid=C030N6KEK7T

**Comment by shuyangzhou** [comment]
@LuisOrtiz89 By a very brief reviewing, this time management will not work. It is setting the "now + PropsValues.UPGRADE_DATABASE_LOCK_REFRESH_TIME" as the expiration time, and everything is at second level. This would not work in cluster env. First there is no guarantee that all machines in cluster are time synced. And even they do, time drifting will happen over time. Second, the  "upgrade.database.lock.refresh.time - 1" only leaves 1 second window time, if there is any kind of delay in the cluster in any node (like gc pause, network latency, etc), it could lead to a false lock removal.

Fundamentally, time based cluster coordination is brittle and should be avoid if possible.
Not talking about other parts of the system, at least this locking part, you might want to consider change it to tx based locking solution. Using "select for update" to do "mutual exclusion", in this case, if the lock "owner" dies for any reason, its jdbc connection would drop, and DBMS will release the lock to allow other nodes to compete it.

**Comment by LuisOrtiz89** [comment]
@shuyangzhou Thanks for your comments! I will check the solution to improve it according to your guidelines.

**Pull request closed without merging**
