### PR TITLE
[TS] LPS-98526 S3 cache is not properly cleaned up within the configured time frame

### PR DESCRIPTION
**Pull request by ericyanLr**
**LPS Ticket:** https://issues.liferay.com/browse/LPS-98526
**Previous pr:** https://github.com/shuyangzhou/liferay-portal/pull/8034

Hi @shuyangzhou ,

As requested, I have created a unit test to assert the current behavior of cleanUpCacheFiles(). 

The test cases were created, based on my observations/understanding of the current functionality.

I have also included a proposed fix, along with changes to the unit test, to demonstrate the behavior change.

**Additional Concern**
Since our current logic does a **CleanUp** while retrieving a cached file, there's a small chance that the returned file is deleted: [S3Store.java#L207-L211](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-store/portal-store-s3/src/main/java/com/liferay/portal/store/s3/S3Store.java#L207-L211)

For additional details regarding this fix + additional concern, please see below.

Feel free to let me know if you have any questions.
Thanks!

----

## Additional Details
**Context**
Currently, the S3 cleanup process does not consider the case, where all sub-directories have been removed during the cleanup process, which qualifies the main folder to now be deleted as well (based on my understanding of the current clean-up logic).

This leads to an incomplete clean-up of files/folders, that are expected to be deleted.

From my understanding, if all sub-directories are removed and the main folder's modified date is less than the passed-in lastModified date, our current logic would agree that the main folder should be deleted.

**Proposed Fix**
The proposed fix is to make sure to check once more, whether the folder is qualified to be deleted, after the cleanup for the folder's sub-directories has been completed.

This logic has to be done during the same call, since deleting a sub-directory would cause the original folder's modified time to be updated.

**Additional Concern**
Regarding the possibility of returning a file that's been deleted, our current strategy relies on the **time** to determine whether a cache file should be used and cleaned up.

This means that there is a small chance that if a user attempts to retrieve a file, right before the date changes to the next day (right before midnight), the cached file is deleted during the clean up (at midnight).

But, all this really means is that the user would not be provided the file for that particular request and re-trying should provide them with the newly cached file.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
**Update**
Added extra commit to resolve a redundant dependency issue in **build.gradle**

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/a76761121b...21f8dfeaf1

**Comment by ericyanLr** [comment]
resent: https://github.com/shuyangzhou/liferay-portal/pull/8084

**Pull request closed without merging**
