### PR TITLE
[ResourceAction]LPS-123838

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please check if the unique failure is real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test failure not related, the test is flaky and sometimes has this render error.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/96838

**Pull request closed without merging**
