### PR TITLE
Startup optimization 172 model impl lazy getter setter

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 high risk change, affecting all SB service modules. Please add additional tests that you see fit, thanks!

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou 

Module compile issue:
`cd modules && gw :aspectj:aspectj-hibernate-stale-object-state:compileJava`

```
> Task :aspectj:aspectj-hibernate-stale-object-state:compileJava
[ant:iajc] error at hibernateException.addSuppressed(
                   ^^^^^^^^^^
/opt/dev/projects/github/liferay-portal/modules/aspectj/aspectj-hibernate-stale-object-state/src/main/java/com/liferay/aspectj/hibernate/stale/object/state/HibernateStaleObjectStateAspect.java:102:0::0 The method addSuppressed(Exception) is undefined for the
type HibernateException
[ant:iajc] MessageHolder:  (5 info)  (1 error)
[ant:iajc] [error   0]: error at hibernateException.addSuppressed(
[ant:iajc]                    ^^^^^^^^^^
[ant:iajc] /opt/dev/projects/github/liferay-portal/modules/aspectj/aspectj-hibernate-stale-object-state/src/main/java/com/liferay/aspectj/hibernate/stale/object/state/HibernateStaleObjectStateAspect.java:102:0::0 The method addSuppressed(Exception) is undefined for the type HibernateException
```

Also, needs versions.xml update: https://testray.liferay.com/home/-/testray/case_results/2207333794

We had some other unique integration failures in the results, but even after I fully compiled, I could not reproduce locally.
Ex:
https://testray.liferay.com/home/-/testray/case_results/2207331674
https://testray.liferay.com/home/-/testray/case_results/2207331289

The default suite failed to run, but relevant ran 7000+ tests so we should be covered. If you resend after fixing the aspectj issue, we can just run ci test stable.

**Comment by shuyangzhou** [comment]
ci:test:stable

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130911

**Pull request closed without merging**
