### PR TITLE
LPS-100268 Make Group and related tables CT enabled

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
You can see backend test results on https://github.com/Preston-Crary/liferay-portal/pull/1031, went through and resolved many of the unrelated failures that were found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
