### PR TITLE
Db cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, this includes the sybase boolean index change and more other changes.

**Comment by vicnate5** [comment]
@shuyangzhou no unique failures

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 rerunning with more changes

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou no unique failures in functional or integration level

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Pull request closed without merging**
