### PR TITLE
Lps 201260

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this fixes the 2 annoying hanging integration tests.

**Comment by shuyangzhou** [comment]
Like this case https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/803991/console

**Comment by vicnate5** [comment]
@zhangyan0701 can you watch this one?

This should resolve the issue originally reported in https://liferay.atlassian.net/browse/LPS-199838

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No regressions found.
The tests in https://liferay.atlassian.net/browse/LPS-199838 passed here.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143557

**Pull request closed without merging**
