### PR TITLE
Revert LPS-97277 due to huge regression on login

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/74973

**Comment by Preston-Crary** [comment]
ci:close

**Comment by vicnate5** [comment]
I pushed this due to regression on https://github.com/brianchandotcom/liferay-portal/pull/74973

https://github.com/brianchandotcom/liferay-portal/pull/75014

**Pull request closed without merging**
