### PR TITLE
LPS-108758 EntityCache.loadResult()

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Test results are on https://github.com/Preston-Crary/liferay-portal/pull/969

**Comment by shuyangzhou** [comment]
@slnn please run a regression test, this changes the FinderCache to EntityCache loading logic a bit. Should not affect too much, but still want to be safe.

**Comment by slnn** [comment]
Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 44632 | 265 | 78.5 | -
PR | - | 45039 | 275 | 80.5 | 0.9119017745

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 56206 | 503 | 151 | -
PR | - | 55926 | 564 | 193 | -0.4981674554

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 17794 | 27.7 | 76.9 | -
PR | - | 17717 | 126 | 169 | -0.4327301338

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 14712 | 357 | 371 | -
PR | - | 14885 | 718 | 547 | 1.175910821

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 25512 | 210 | 305 | -
PR | - | 26508 | 168 | 246 | 3.904045155

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 15177 | 243 | 461 | -
PR | - | 15242 | 218 | 441 | 0.4282796337

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 25726 | 430 | 177 | -
PR | - | 26069 | 430 | 177 | 1.333281505


Regards
Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84827

**Pull request closed without merging**
