### PR TITLE
File impl.extract text cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
Waiting for full document suites. Already checked the existing results No regressions found.

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113364

**Pull request closed without merging**
