### PR TITLE
Startup optimization 124 remove eager service tracker customizer usage from fragment collection contributor registry impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by vicnate5** [comment]
ci:test:echo

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. This just needs a rebase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127701

**Pull request closed without merging**
