### PR TITLE
LPS-108525 Avoid the use of classNameId as unique ID parameter in the Service Builder API

### PR DESCRIPTION
**Pull request by achaparro**
@shuyangzhou this is the pull we were talking about a few weeks ago. I have been talking to Brian and we can do major changes in the persistence layer in the first weeks of the GA.

Please, take into account that we are changing several persistence package versions and, due to that, the pull can present conflicts with master soon.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @vicnate5, the error seems unrelated, can you verify it please?

Thanks
cc/ @shuyangzhou

**Comment by vicnate5** [comment]
@achaparro failures are unrelated.

**Comment by achaparro** [comment]
Thanks @vicnate5

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9276

**Pull request closed without merging**
