### PR TITLE
LPS-90086 | master

### PR DESCRIPTION
**Pull request by vicnate5**
MySQL Driver update for MySQL 8, also backwards compatible with MySQL 5

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn @dantewang a full regression test is needed for this. We had too many painful experience with mysql driver upgrade in the past :(

**Comment by slnn** [comment]
Hi Shuyang,

Test results please see: [Test results for LPS-90086](https://docs.google.com/spreadsheets/d/1rFM3LAXVW-KTbIeAXOp7EfKrIe0HYQ4Zfyk7puGTX4A/edit?usp=sharing)

Note: test this pull with MySQL 5.7

1. Set "jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver", the origin one is "jdbc.default.driverClassName=com.mysql.jdbc.Driver"

2. Add "&serverTimezone=Asia/Shanghai" to the value of "jdbc.default.url" to avoid the IllegalArgumentException:

> java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3
	at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2829)
	at java.util.Calendar.updateTime(Calendar.java:3393)
	at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
	at com.mysql.cj.result.SqlTimestampValueFactory.createFromTimestamp(SqlTimestampValueFactory.java:100)
	at com.mysql.cj.result.SqlTimestampValueFactory.createFromTimestamp(SqlTimestampValueFactory.java:46)
	at com.mysql.cj.result.BaseDecoratingValueFactory.createFromTimestamp(BaseDecoratingValueFactory.java:61)
	at com.mysql.cj.result.BaseDecoratingValueFactory.createFromTimestamp(BaseDecoratingValueFactory.java:61)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeTimestamp(MysqlTextValueDecoder.java:183)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:87)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:250)
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:656)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getDateOrTimestampValueFromRow(ResultSetImpl.java:679)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:1019)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:1064)
	at org.hibernate.type.descriptor.sql.TimestampTypeDescriptor$2.doExtract(TimestampTypeDescriptor.java:62)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:64)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:254)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:250)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:230)

For test case Document Library and Wiki, when visit a DL folder or select a wiki page on this pull, the IllegalArgumentException will appear with the DB SampleSQLBuilder generated.

**Comment by shuyangzhou** [comment]
This must be caused by the new java.util.Date() usage we have in sample sql builder or the DataFactory.getDateLong()/getDateString(), it needs to be fixed before we can merge this pull.

@dantewang @slnn  please dig into it.

**Comment by slnn** [comment]
OK, got it.

**Comment by dantewang** [comment]
@shuyangzhou It's due to timezone handling in the driver, I've sent my findings in the email.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68979

**Pull request closed without merging**
