### PR TITLE
LPS-94336 Fix Display page template publication failure

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
Please wait for tests to finish, thanks!

**Comment by shuyangzhou** [comment]
@Preston-Crary should I merge?

**Comment by Preston-Crary** [comment]
@shuyangzhou, yes failures look unrelated.  I'll send some pulls to clean up this noise.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72360

**Pull request closed without merging**
