### PR TITLE
LPS-83992 Portlet 3.0: Develop the bean portlet CDI portable extension (basic structure)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou I've sent this PR about 5 times, and each time CI tells me that I'm specifying the wrong values in build.grade for com.liferay.bean.portlet.api and com.liferay.petra.string. At this point I don't know what the correct values are supposed to be. If you could fix it in a code-review commit I would very much appreciate it. Note that com.liferay.bean.portlet.api-1.0.0.jar was released by Brian on Tuesday: https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.bean.portlet.api/

All other failures besides the GradleVersionCheck must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by jpince** [comment]
@petershin could you help Neil with resolving this error? Thanks! See his comment from above:
> @shuyangzhou I've sent this PR about 5 times, and each time CI tells me that I'm specifying the wrong values in build.grade for com.liferay.bean.portlet.api and com.liferay.petra.string. At this point I don't know what the correct values are supposed to be. If you could fix it in a code-review commit I would very much appreciate it. Note that com.liferay.bean.portlet.api-1.0.0.jar was released by Brian on Tuesday: https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.bean.portlet.api/
```
     [java] 1: Do not use 'default' version for 'com.liferay.bean.portlet.api', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/gradle_versioning.markdown: ./modules/apps/bean-portlet-cdi-extension/build.gradle 4 (SourceCheck:GradleVersionCheck)
     [java] 2: Do not use 'default' version for 'com.liferay.petra.string', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/gradle_versioning.markdown: ./modules/apps/bean-portlet-cdi-extension/build.gradle 5 (SourceCheck:GradleVersionCheck)
```

**Comment by ngriffin7a** [comment]
@petershin Thanks in advance for the help. One thing I'd like to mention is that the com.liferay.bean.portlet.api module us currently under modules/util:
https://github.com/liferay/liferay-portal/tree/master/modules/util/bean-portlet-api

Perhaps you could ask Brian if he wants both com.liferay.bean.portlet.api and com.liferay.bean.portlet.cdi.extension in modules/apps ?

For now, BOTH of those dependencies have to be included in WEB-INF/lib along with weld-servlet.jar in order to make CDI Bean Portlets work. In the future, we will be able to deploy both com.liferay.bean.portlet.api and com.liferay.bean.portlet.cdi.extension to $LIFERAY_HOME/modules, but I don't have a timeline for that.

**Comment by petershin** [comment]
Hi @ngriffin7a, @jpince,

I checked nexus for the latest published versions:

```
name: "com.liferay.bean.portlet.api", version: "1.0.0"
name: "com.liferay.petra.string", version: "2.0.0"
```

https://repository.liferay.com/nexus/index.html#nexus-search;quick~com.liferay.petra.string
https://repository.liferay.com/nexus/index.html#nexus-search;quick~com.liferay.bean.portlet.api

Will followup with Brian about your other question.

**Comment by ngriffin7a** [comment]
@petershin Thanks for checking with Brian -- if you could emphasize that these modules will eventually go in $LIFERAY_HOME/osgi/modules (perhaps at around 7.1 GA4) but for now they can't be deployed there.

I tried hard-coding those versions you mentioned in an earlier PR.

But for com.liferay.bean.portlet.api I got this message:
```
Artifact dependency {compileOnly group: "com.liferay", name: "com.liferay.bean.portlet.api", version: "1.0.0"} in modules/apps/bean-portlet-cdi-extension/build.gradle not permitted on master branch. Use a project dependency instead.
```

The same thing happened for com.liferay.petra.string:
```
Artifact dependency {compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.1.0"} in modules/apps/bean-portlet-cdi-extension/build.gradle not permitted on master branch. Use a project dependency instead.
```

**Comment by petershin** [comment]
@ngriffin7a - The unit test message is more accurate, a project dependency should be used.  I'll add a patch to SF to fix the warning message it displays.

```
compileOnly project(":core:petra:petra-string")
compileOnly project(":util:bean-portlet-api")
```

Brian was ok with moving `:util:bean-portlet-api` to the apps directory and having it deploy to `$LIFERAY_HOME/osgi/modules`.  Is it ok to move the project to `apps/bean-portlet-api`?

**Comment by ngriffin7a** [comment]
@petershin Thanks for the help! I'll update my branch with the project dependencies you mentioned. Also thanks for patching SF with a different warning message.

I will also send Brian a PR that moves :util:bean-portlet-api to the apps directory. Thanks for asking him about it for me.

But I will omit the .lfrbuild-portal for now so that it com.liferay.bean.portlet.api and com.liferay.bean.portlet.cdi.extension not get deployed to $LIFERAY_HOME/osgi/modules until we support that.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6576

**Pull request closed without merging**
