### PR TITLE
[Bug Fix]LPS-137041 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian Real failure here.

Steps to Reproduce:
1. Delete directory `[liferay.home]/elasticsearch7`
2. Start portal to trigger auto-download of elasticsearch

```
 [parallel] 2021-08-11 16:54:34.595 ERROR [main][SidecarManager:93] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.15 (260)[com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager(741)] : The activate method has thrown an exception 
 [parallel] java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/gzip/GzipCompressorInputStream
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.ElasticsearchInstaller.downloadAndInstallElasticsearch(ElasticsearchInstaller.java:182) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.ElasticsearchInstaller.install(ElasticsearchInstaller.java:68) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.Sidecar._installElasticsearchIfNeeded(Sidecar.java:590) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.Sidecar.start(Sidecar.java:106) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager.lambda$applyConfigurations$0(SidecarManager.java:135) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnection.connect(ElasticsearchConnection.java:61) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.addElasticsearchConnection(ElasticsearchConnectionManager.java:75) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager.applyConfigurations(SidecarManager.java:142) ~[?:?]
 [parallel] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager.activate(SidecarManager.java:77) ~[?:?]
 ```
 Full log https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=14,label_exp=!master/1387//consoleText

**Comment by tinatian** [comment]
Fix and resend at https://github.com/shuyangzhou/liferay-portal/pull/10218

**Pull request closed without merging**
