### PR TITLE
LPS-135170 Add content page portlets to the portlets list

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, again, unsure if I should have sent this PR to you. If not, please let us know who can review it.

We are a bit worried that this might cause performance regressions (mostly if a site contains lots of pages and widgets), and if we should include it in the portal. We could always treat it as a limitation.

Please let us know what you think please.

As always, thanks for the time!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn do we have tests that cover this?

@jkappler I can not review the function part since I don't know what this is. I even doubt we have test cases actually covers it on the performance part. If we do, we can do the performance review, otherwise feel free to bypass us for this pull.

**Comment by jkappler** [comment]
ok, thanks @shuyangzhou!

**Comment by slnn** [comment]
Hi @shuyangzhou 

In our login test case, the method `getExplicitlyAddedPortlets()` in the class `LayoutTypePortletImpl` will be hit, I will double-check the performance of login against this pull tomorrow since some internet issues appeared with our test envs.

Regards
Lily

**Comment by jkappler** [comment]
Hi @slnn, will reopen the PR until we know if it affects performance. Thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou @jkappler 

Here are test results on Login against this pull:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count change (%)
-- | -- | -- | -- | --
BaseLine | 0b87d05 | 29492 | 270 | -
PR | - | 28371 | 272 | -3.801030788
PR | - | 28141 | 268 | -4.580903296

CPU Tracings and detailed test results please see:https://drive.google.com/drive/folders/1RrSJBbQJuUlI8WwjSwbO1a8QOCL5siPu?usp=sharing

Lily

**Comment by shuyangzhou** [comment]
@jkappler can you look into the profile to see if anything can be improved? At least do the first round on your side, if really nothing we can take it over.

**Comment by jkappler** [comment]
We'll take a look, thanks @shuyangzhou and @slnn!

**Comment by brianikim** [comment]
hey @shuyangzhou ,

The changes were largely recommended by the echo product team. I think it would be best if you took over in terms of investigating performance.

Sincerely,
Brian Kim

**Pull request closed without merging**
