### PR TITLE
LPS-89456 Mysql8

### PR DESCRIPTION
**Pull request by tinatian**
FYI @anthony-chu @vicnate5

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @anthony-chu,
Could you please try to upgrade database of liferay on mysql 5.7, then open it with mysql 8?

We can not do the upgrade from mysql 5.7 to mysql 8 directly like you did.

Thanks.
Tina.

**Comment by tinatian** [comment]
Rebase at https://github.com/shuyangzhou/liferay-portal/pull/7350

**Pull request closed without merging**
