### PR TITLE
Master lps 143575

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test:sf

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please do one last check, if no problem I will forward this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114138

**Pull request closed without merging**
