### PR TITLE
Startup optimization 218 remove export import resources importer

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 can you look for any usage of resources-importer. Maybe [osb-faro-theme](https://github.com/liferay/liferay-portal/tree/master/modules/dxp/apps/osb/osb-faro/osb-faro-theme)? I would try deploying it here since I don't see a test using it.

**Comment by vicnate5** [comment]
ci:test:analytics-cloud

**Comment by vicnate5** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
@vicnate5 @shuyangzhou 

The resources-importer in themes should have been deprecated since 7.1: https://help.liferay.com/hc/en-us/articles/360036124511-Resources-Importer. So I could not find out any usages of it.

[osb-faro-theme](https://github.com/liferay/liferay-portal/tree/master/modules/dxp/apps/osb/osb-faro/osb-faro-theme) was just migrated to portal from https://github.com/liferay/com-liferay-osb-faro-private/tree/7.1.x/osb-faro-theme last week. Test [modules-compile-jdk8](https://testray.liferay.com/home/-/testray/case_results/2272966709) is testing the compile of it but the theme module is still building from com-liferay-osb-faro-private repo in test.

I manually deployed the theme from portal, it could be deployed and applied to a page.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133555

**Pull request closed without merging**
