### PR TITLE
LPS-91606 Portlet 3.0 incompatibility with PortalUtil.copyRequestParameters(ActionRequest,ActionResponse)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou It's difficult to say for sure, but after two runs I think that the failures are unrelated.The commit in this PR fixes the LPS-91606 issue in such a way that it should make the system more solid, not more error-prone.

This PR also needs to be backported to 7.1.x, so please review at your earliest convenience. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69167

**Pull request closed without merging**
