### PR TITLE
[Bug Fix]LPS-105037 Sybase

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @vicnate5,
The sybase upgrade is not blocked, right? so I am wondering if we have anything to test for this.

Tina

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@tinatian Sybase testing is still blocked. Briefly checked results on https://github.com/tinatian/liferay-portal/pull/1624, test results look good, though this PR is only affecting Sybase.

This will get tested at head once Sybase is unblocked.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81675

**Pull request closed without merging**
