### PR TITLE
Startup optimization 95 remove unused message status destination

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:export-import

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Just semver issue here, No other regressions in the test results
```
com.liferay.portal.kernel.messaging   MAJOR      14.0.0     12.0.0     13.0.0     EXCESSIVE VERSION INCREASE
```
https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121785//consoleText

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 , regenerating semantic version now

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125494

**Pull request closed without merging**
