### PR TITLE
LPS-96641 vulcan configuration

### PR DESCRIPTION
**Pull request by javiergamarra**
Hi!

Can you check the startup performance of the last 3 commits? 

Thank you very much :D

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn please run this on your side, I am still seeing some regression after reverting LPS-96641, I think there is more than one cause. But at least compare the master + full revert of LPS-96641 to this pull, that would let @nhpatt know whether this change fixes his problem.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results on this pull, the commit of revert LPS-96641 had een merged on the version of baseline.

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | f56de07 | 49162 | 24299.2 | 24346 | 24131 | 24055 | 24216 | 24748
PR | - | 48778 | 24462 | 24263 | 24617 | 24197 | 24368 | 24865

Similar issue on my side, full revert LPS-96641 bring partly performance of startup back, I am finding the other one that cause the another part of regression.

Regards
Lily

**Comment by nhpatt** [comment]
@slnn are these results under the regular variance in the startup time or I should search for a performance issue in the PR?

**Comment by shuyangzhou** [comment]
@slnn please let @nhpatt know whether he can go with his fix, thanks!

**Comment by slnn** [comment]
Hi @nhpatt,

This pull fixed the origin regression, thanks!

Regards
Lily

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
