### PR TITLE
Lps 68627

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
Pushed SF commit

**Comment by mtambara** [comment]
ci:retest

**Comment by mtambara** [comment]
I'm just gonna make a new pull

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/43864

**Pull request closed without merging**
