### PR TITLE
LPS-106966 Don't use bookmarks in tests

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @shuyangzhou 

Here we're trying to move Bookmarks and Microblogs into the archived app. The problem is that these apps contain test modules, so the CI tries to run them; as its dependencies are not deployed the build fails.

Is there any way to move a test module into 'archived' in a way that prevents it from being run? We'd really like to keep these tests around, as they still provide value.

Thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mtambara we need to create a new "archived" batch for CI, which deploys all archived modules and run tests for them. Please send me a pull for it on top of this pull.

**Comment by mtambara** [comment]
@adolfopa We do have a test batch for archived apps, but looks like you need to manually add the archived test batch to the normal excludes list (https://github.com/liferay/liferay-portal/blob/master/test.properties#L1120). I'll see if I can update the excludes to include all archived tests by default

**Comment by mtambara** [comment]
ci:close

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8717

**Pull request closed without merging**
