### PR TITLE
Company group

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou I am seeing unique exception here when creating a company. [Example](https://ffe6855a419109d0264f2eb116bb65026104b65d3d2fd09c816a910-apidata.googleusercontent.com/download/storage/v1/b/testray-results/o/2024-10%2Ftest-1-30%2Ftest-portal-acceptance-pullrequest(master)%2F10304%2Ffunctional-smoke-tomcat90-mysql57_stable%2F0%2F0%2Fjenkins-console.txt.gz?jk=AdvOr8so5Lyp936kTPEudzdyGqFuhmDNgIzdZhCOvz0gWuKzui-dABzmkwTxdNcJh3oasb5UoCBBRTtxFv5lNIJy4sHhjk7jDeEX27nuJ_5ss3mUzooB6LNi4tN0iy1Ux6N9Jz4sj-Lb6tez_vlZ_YVOWcDujBDmKbb_Ukiz3VPDnYMyQdqbYoX3R9KcDhB4qa2CQ8QB9pmtQpy2f_m76ycP56i_7TLQ2FQ0xE2ZVTNofym9GfGZaOMdlfwPLfVsr_6g2pyUSv3ctc4qkk9Qsm4_83yTzXfsW4COJgNDcwEGVZdBGcjD9cpv6G4dxBVRWheit3i-1jSnOJkg0KQrcHQFLly9Pcb82kF5UGOxSeMaiT1dS9PLSz3CPrrNLKPzRQ5YVlxJ6AriU5P5IADsiTb39PywQti3gUVu_tITNak3vAzyqC1vkOtpxL_m6eL0RR4rNgKA6FWbnYaEDUiRqPkXGlYnae5yTQb-9bS2YTd7Yjs47NXT5niplaprA0yYz0Mozc2RCzHNQADGhE_qrXFXQTwsjWYAoK6n7m8eJWdqAPIrAT_58GF_kdo1x2vad2TXYef2q3iHFuEA45u68wIzaIQ7dG76L7saWYUbyVRxnxHZT16r9YAh4OxfZ8nLZAngR0llFJctDHJW230vlqH8M_RbG0x1ZN9RMPuioYUE0sV4yd4xWklYYMrZ33KJwWJc2HxXzq5xB_3YtFbgZJmYum6g0YzlbqPbKkCwoIdK8V9L7UO_uwxzMLeUJLbLnmymAM0_LwXUbOT-hhP9v8MYRxnuw3hZd_s4z1dZ4h7JhSMrYBKrtkjxrjg9boI9YmFGdwhRuon1ad3dRhuALqAiRabil2UaDwtYF7EF4hdXFWkSmTG_uRv9Z1QuXEE8u7FwcFG6Uamp14zd9zGzeS6al0nXmGYTbzdKM-caCZrCoPpCIj-CK8bLdB2xP5FMse95Nd-dw882ez76Fk-WmknyofLNjisbWgjKjmWI5R8GW510mV1vHZieF4hx_H0TeOL6E6EHRnodFdUsyPCt6D-OPZxGFOFxFjCVIPDwvMDaJaSxRuihlHjarNu2u9EBwpJo6gw6GKZ3vZPa_11QLRYZAMETvDHRFTq88vd7YkVCsxF50_xtZRWjvEXzEQmv4SLRTRVc4a2rXnkmY8bbpGVSeC5KzubGbRw-KNYiluJtPgpmcDnW6qp494LoHSYfPxL6_3-HOB62aNjTXKyuABFUZsDrQy5VijRfJ_8evlifPJAaxoD2er2Oc8a2EhwWhUF6-z5kYDaXJo2NiZRQJ9b9y4wIfVGXGSIwkardZHNMbw&isca=1)
`ERROR [http-nio-8080-exec-8][PortalImpl:6766] No Company exists with the primary key`

See other examples: https://testray.liferay.com/#/project/35392/routines/45357/build/47154137?filter=%7B%22error%22%3A%22primary%22%7D&filterSchema=buildResults&page=1

Not sure the manual steps, this is occurring across different tests without known functional error.

**Comment by shuyangzhou** [comment]
ci:test:relevant

Pushed a fix, rerunning, thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
ci:report:48237430

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou nothing unique

**Comment by shuyangzhou** [comment]
ci:test:relevant

Pushed a fix to reduce startup impact.

@JerryAdrianoo please check for startup, it is expected to increase one query of 
`SELECT groupimpl0_.groupId AS groupid1_27_, groupimpl0_.mvccVersion AS mvccvers2_27_, groupimpl0_.ctCollectionId AS ctcollec3_27_, groupimpl0_.uuid_ AS uuid_4_27_, groupimpl0_.externalReferenceCode AS external5_27_, groupimpl0_.companyId AS companyi6_27_, groupimpl0_.creatorUserId AS creatoru7_27_, groupimpl0_.modifiedDate AS modified8_27_, groupimpl0_.classNameId AS classnam9_27_, groupimpl0_.classPK AS classpk10_27_, groupimpl0_.parentGroupId AS parentg11_27_, groupimpl0_.liveGroupId AS livegro12_27_, groupimpl0_.treePath AS treepat13_27_, groupimpl0_.groupKey AS groupke14_27_, groupimpl0_.name AS name15_27_, groupimpl0_.description AS descrip16_27_, groupimpl0_.type_ AS type_17_27_, groupimpl0_.typeSettings AS typeset18_27_, groupimpl0_.manualMembership AS manualm19_27_, groupimpl0_.membershipRestriction AS members20_27_, groupimpl0_.friendlyURL AS friendl21_27_, groupimpl0_.site AS site22_27_, groupimpl0_.remoteStagingGroupCount AS remotes23_27_, groupimpl0_.inheritContent AS inherit24_27_, groupimpl0_.active_ AS active_25_27_ FROM Group_ groupimpl0_ WHERE (groupimpl0_.companyId = ?) AND (groupimpl0_.classNameId = ?) AND (groupimpl0_.classPK = ?) AND groupimpl0_.ctCollectionId = 0` note this query already exist, this change increase its count by 1.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hi @shuyangzhou   for more details, see: [results](https://docs.google.com/spreadsheets/d/1imhu0B61tZACjSlsg63T_Y8h5I4Boe-tl0cDP--X9jc/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before CompanyGroup | **43,132** | | 16,241 | | | **2,524** | 1,939
|  | | | 16,294 | | | | 1,921
|  | | | 15,853 | | | | 1,913
 | | | | 16,031 | | | | 2,017
 | | | | 16,343|**16,189** | | | 1,998 | **1,953**
-- | -- | -- | -- | -- | -- | -- | --
After CompanyGroup | **44,073** | | 15,534 | | | **2,480** | 1,942
|  | | | 15,824 | | | | 1,897
|  | | | 16,644 | | | | 1,947
|  | | | 16,663 | | | | 1,957
| | |  2.18% | 16,798 |**16.593** |  **1.16%** | | 1,863 | **1,929**

This variation in the Cold Startup is under control and is expected. Except for the increase you mentioned, no other changes were noticed.

**Comment by shuyangzhou** [comment]
ci:report:49874841

**Comment by shuyangzhou** [comment]
@vicnate5 sorry, please check one more time, if still clean this pull will be ready to go. Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou no unique failures

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155516

**Pull request closed without merging**
