### PR TITLE
Lps 159081

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me watch on this pull, Brian asked for this change to improve stability of long slow upgrades.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found here. The upgrade test results look good.

**Pull request closed without merging**
