### PR TITLE
LPS-120626 Replace buffered.increment.enabled property with view.counts.enabled property

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@Preston-Crary the failure is real, CI must be still using the old properties somewhere, please fix and resend, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9429

**Pull request closed without merging**
