### PR TITLE
[TECHNICAL SUPPORT] LPS-91059

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-91059

FileUtil.extractText is not correctly working for Documents in docx format (Word 2007+) files:

1. The docx format is not indexed correctly because "org.apache.tika.parser.microsoft.ooxml.OOXMLParser" parser is missing in tika.xml (added in first commit https://github.com/shuyangzhou/liferay-portal/pull/7415/commits/39abd04becc00406e2f4cb58fd1a3f0eccd6d693 )
2. After adding that parser to tika.xml, FileUtil.extractText starts throwing exceptions: 
`java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.ooxml.POIXMLTypeLoader`
To avoid that error, we have to update XMLBeans jar to 3.0.2 version (see second commit https://github.com/shuyangzhou/liferay-portal/pull/7415/commits/bd0313081b4bda3ad862281cdfd49dc57c08bdbb)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
That ci:test errors are produced in other pull requests, for example see: https://github.com/brianchandotcom/liferay-portal/pull/68765#issuecomment-468304420

So they seem to be unrelated to my changes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68833

**Pull request closed without merging**
