### PR TITLE
LPS-X Remove the unused reference which causes shutdown time reactiva…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…tion for WikiAttachmentsItemSelectorViewReturnTypeProvider

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou 

Startup errors on JDK11 (reproduced locally with HSQL)
`java.util.ConcurrentModificationException: null`
[Portal log from CI](https://testray.liferay.com/reports/production/logs/2023-06/test-1-39/test-portal-acceptance-pullrequest(master)/5116/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/liferay-log.txt.gz?authuser=0)

No other issues found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135840

**Pull request closed without merging**
