### PR TITLE
Startup optimization 364 model summary contributor

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me to check the results, thanks!
I tried to use the https://test-1-1.liferay.com/job/generate-testray-csv/ , but it always fails with some IOException that not being able to connect to certain ci URLs.

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No regressions found.

There might be something wrong with the tool. I am now using Kyle's custom branch https://github.com/kyle-miho/liferay-jenkins-ee/tree/testray-test which is the Testray Analysis tool 2.0, it hasn't been merged yet, so need to manually add it to JENKINS_GITHUB_URL.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145349

**Pull request closed without merging**
