### PR TITLE
[TS] LPS-92402

### PR DESCRIPTION
**Pull request by jcampoy**
Hi @shuyangzhou 
as part of our professional services in a customer performing load tests, we noticed that after https://github.com/rotty3000/liferay-portal/pull/1351/commits/0c697da61e969855c5bb99ee8a23f4b8e84e9404 the createInvokerFilterChain is accumulating a lot of CPU time.
This simple fix would avoid to calculate the same chain for the same URLs. Could you take a look? 
Thx!

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
Hi @shuyangzhou 
GS has checked the same stress test with the patch for 7.1 and the CPU consumption is around a 10% better.
BR,

**Comment by shuyangzhou** [comment]
@slnn a regression test please, thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 15699 | 333 | 87.4 |  | 97
PR-7493 | - | 15850 | 275 | 69 | 0.9618447035 | 97

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 20435 | 416 | 155 |   | 97
PR-7493 | - | 20304 | 406 | 152 | -0.64105701 | 97

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 7718 | 170 | 336 |   | 93
PR-7493 | - | 7765 | 149 | 310 | 0.6089660534 | 91

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 5206 | 69.7 | 292 |   | 94
PR-7493 | - | 5205 | 90.5 | 333 | -0.01920860546 | 93

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 8567 | 437 | 760 |   | 90
PR-7493 | - | 8459 | 326 | 651 | -1.260651337 | 92

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of VIew Page with Filter | Session Count Changes | Portal Server CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 5f88de0 | 9145 | 128 | 152 |   | 88
PR-7493 | - | 9341 | 136 | 155 | 2.143247676 | 88

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70138

**Pull request closed without merging**
