### PR TITLE
Lps 130594

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 @martamedio please help me to check whether this blind fix is working or not, thanks!

**Comment by vicnate5** [comment]
@gaborlovasdotcom @JoyceWang08211 I don't have enough understanding of SAML to fully test this, can one of you test the solution?

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Comment by shuyangzhou** [comment]
Pushed SF fix, no logic change.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:saml

**Comment by martamedio** [comment]
@shuyangzhou @vicnate5 @gaborlovasdotcom @JoyceWang08211 I have just tested it and it works correctly.
Thank you all for your help!

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou !

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
