### PR TITLE
LPS-76502 Only shortcut null string

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou 

This pull avoids 5 test failures.

As described in https://issues.liferay.com/browse/LPS-76502, when calling `CacheControl.setETag` with `null`, the current ETag should be removed.

The Liferay logic before this pull will throw an `IllegalArgumentException` from the `_mimeResponseImpl.setProperty` call chain.

Although we can pass the 5 related tests by this pull, obviously this fix is not complete.

If `CacheControl.setETag(null)` is called, the ETag value that has already been set into the response's header should also be removed. However, there's no direct API allowing us to do it; there's no API requirement for methods like `PortletResponse.setProperty` or `HttpServletResponse.setHeader` to do the removal when having a null value, either (Tomcat's implementation does nothing when value is `null`).

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@dantewang isn't this the remove you need https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/PortletResponseImpl.java#L413 ?

**Comment by dantewang** [comment]
@shuyangzhou In our case the `_mimeResponseImpl` is actually an instance of `ResourceResponseImpl` which overrides `setHeader` method to set the header into the underlying servlet response: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/ResourceResponseImpl.java#L121

**Comment by shuyangzhou** [comment]
@dantewang I see, so the headers are already inside the underneath servlet response. The only way to remove it is to copy out all exist headers, by HttpServletResponse.getHeaderNames() and HttpServletResponse.getHeaders(). Then remove the one you want to remove, then call response.reset(), then re-apply back the header map.

Can you try to see if that works?

**Comment by dantewang** [comment]
OK

Shuyang Zhou <notifications@github.com> 于 2017年12月15日周五 08:04写道：

**Comment by shuyangzhou** [comment]
Any update?

**Comment by dantewang** [comment]
Leon is on it. The previous attempts didn't pass CI.

**Comment by dantewang** [comment]
@shuyangzhou Resent, see https://github.com/shuyangzhou/liferay-portal/pull/5449

**Pull request closed without merging**
