### PR TITLE
LPS-X System company does not have any preferences

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Functional tests are looking good here, but CI still had the issue of not running the integration tests. if this is risky for the backend, we should wait and re-run.

I can trigger once I have confirmed the backend tests are working on CI again.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139419

**Pull request closed without merging**
