### PR TITLE
Lps 61952 imagegallerydisplay

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
This worked fine yesterday, but it couldn't hurt to let it test while the CI load is still light

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
The compile jsp failure is real, please fix and resend.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34496

**Pull request closed without merging**
