### PR TITLE
[FinderCache]LPS-122225

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
close, will resend

**Comment by tinatian** [comment]
@vicnate5 Could you please verify if the unique failures are real?

Thanks
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures are real and should be simple to reproduce.

#### 1. Errors thrown on portal login (test@liferay.com):
```
ERROR [http-nio-8080-exec-4][DynamicCSSFilter:181] Unable to replace tokens in CSS /o/product-navigation-simulation-theme-contributor/css/simulation_panel.css
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.37/work/Catalina/localhost/ROOT/css/http___o_product-navigation-control-menu-theme-contributor_product_navigation_control_menu.css_o_product-navigation-simulation-theme-contributor_css_simulation_panel.csshttp__o_product-navigation-product-menu-theme-contributor_product_navigation_product_menu.cssEvIVODWtyBUZxhLu0qlSI-ddHNZRTqmUNHqpjphRxOM_EvIVODWtyBUZxhLu0qlSI-ddHNZRTqmUNHqpjphRxOM__E_CTYPE (File name too long)
```
[Full log](https://testray.liferay.com/reports/production/logs/test-1-9/1603254366897/test-portal-acceptance-pullrequest(master)/3834/functional-tomcat90-mysql57-jdk8/7/0/liferay-log.txt.gz)

#### 2. Error during upgrade tool execution. 
Will send you the db dump on Slack
```
     [java] 2020-10-21 07:03:52.507 INFO  [main][BaseDB:99] create index IX_6E4C09BA on WorkflowInstanceLink (groupId, companyId, classNameId, ctCollectionId);
     [java] java.lang.NullPointerException
     [java] 	at com.liferay.portal.cache.internal.dao.orm.FinderCacheImpl._encodeCacheKey(FinderCacheImpl.java:445)
     [java] 	at com.liferay.portal.cache.internal.dao.orm.FinderCacheImpl.getResult(FinderCacheImpl.java:134)
     [java] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.getResult(FinderCacheUtil.java:55)
     [java] 	at com.liferay.portal.service.persistence.impl.ClassNamePersistenceImpl.findAll(ClassNamePersistenceImpl.java:688)
     [java] 	at com.liferay.portal.service.persistence.impl.ClassNamePersistenceImpl.findAll(ClassNamePersistenceImpl.java:648)
     [java] 	at com.liferay.portal.service.persistence.impl.ClassNamePersistenceImpl.findAll(ClassNamePersistenceImpl.java:613)
     [java] 	at com.liferay.portal.service.impl.ClassNameLocalServiceImpl.checkClassNames(ClassNameLocalServiceImpl.java:59)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [java] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [java] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [java] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [java] 	at com.sun.proxy.$Proxy122.checkClassNames(Unknown Source)
     [java] 	at com.liferay.portal.kernel.service.ClassNameLocalServiceUtil.checkClassNames(ClassNameLocalServiceUtil.java:62)
     [java] 	at com.liferay.portal.tools.DBUpgrader._checkClassNamesAndResourceActions(DBUpgrader.java:181)
     [java] 	at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:368)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:152)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:144)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:124)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
```
[Full log](https://testray.liferay.com/reports/production/logs/test-1-9/1603254366897/test-portal-acceptance-pullrequest(master)/3834/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)

**Pull request closed without merging**
