### PR TITLE
LPS-88903 apply new version

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a and @stiemannkj1 please verify the fix against the tickets before I start making changes.
If this https://github.com/shuyangzhou/liferay-portal/pull/7208#issuecomment-452432955 is true, please fix the test war and update it on the ticket.
Please let me know when I can start review this.

**Comment by rotty3000** [comment]
@shuyangzhou this is not for them. This is just for you to review. I'll send the other stuff about CDI later.

**Comment by shuyangzhou** [comment]
@rotty3000 ah, sorry, I thought this was the resend of the previous pull. I will be on it soon. Thanks!

**Pull request closed without merging**
