### PR TITLE
LPS-76927 Tracking every small upgrade process in Core with a unique SchemaVersion and simplifying the release process

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

I have rebased the previous pull to avoid conflicts:
https://github.com/shuyangzhou/liferay-portal/pull/5921

Could you review this one?

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
Hi @shuyangzhou,

The failures same unrelated because they are also failing here:
https://github.com/ealonso/liferay-portal/pull/1556

Apart from that, this pull already passed the tests here in the previous pull (without the rebase):
#5921

Cheers.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57020

**Pull request closed without merging**
