### PR TITLE
Lps 98312

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@mtambara https://github.com/shuyangzhou/liferay-portal/pull/8039/commits/38e86a3256386107d5c14cc89e41f008f8ec4d00 is an empty file.

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
Pushed fix

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76082

**Pull request closed without merging**
