### PR TITLE
[Deprecation]LPS-103868 

### PR DESCRIPTION
**Pull request by yuhai**
@shuyangzhou, the pr is from https://github.com/shuyangzhou/liferay-portal/pull/8488. I remove the autobox codes.

cc @tinatian, @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Looks good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80771

**Pull request closed without merging**
