### PR TITLE
Lps 129881

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Failed manual testing on:

**Oracle 19c**
```
WARNING [Thread-96] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [oracle.jdbc.driver.BlockSource.ThreadedCachingBlockSource.BlockReleaser] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser.run(BlockSource.java:331)
 ```
 
Oracle Docker image: https://docs.google.com/document/d/1gTqqemvzg0ibiAZ7FPe1jPUSML1xWhmdCkkrvLWFKRo/edit#heading=h.prd8gvugtoeo
 
 
Passed testing on:
- PostgreSQL 12.6
- MySQL 5.7
- MariaDB 10.2
- SQL Server 2017

**Comment by vicnate5** [comment]
@zhangyan0701 if Shuyang sends another PR tonight, please test.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Force pushed for oracle driver fix. Please test again, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 No need to retest this

**Comment by shuyangzhou** [comment]
Force pushed again to go back to previous version. Talked to @vicnate5, the oracle issue has always been there when deploy to global ext folder, not a regression. Fixing it could be overstepping to interrupt other webapps on the same server. 
As long as we keep the oracle driver jar under the new location, WEB-INF/lib, the problem will go away.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
