### PR TITLE
[TS] LPS-116218 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
References:
https://issues.liferay.com/browse/LPS-116218

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please take this over.

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9218

**Comment by mtambara** [comment]
ci:close

**Pull request closed without merging**
