### PR TITLE
[TECHNICAL-SUPPORT] LPS-96103

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-96103
> 
> Previous pr: https://github.com/liferay/liferay-portal-ee/pull/14378 not acceptable as mentioned [here](https://github.com/brianchandotcom/liferay-portal-ee/pull/24876#issuecomment-499616688).
> 
> https://github.com/brianchandotcom/liferay-portal/pull/64962/ is used as reference on how to update third party library.
> 
> https://github.com/liferay/liferay-portal/commit/5ff324be271b7d08759381fffa265155c9216166 needs to be reverted because json-schema-validator library needs to be updated and used in 71x. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/05168a755c459921b63eb55cb93a719235f5fe69 excludes the jackson package. This will direct the classloader to use the latest version of jackson that is set in https://github.com/liferay/liferay-portal-ee/pull/13609/commits/fb0fc95b48cb85e4d12350099134ced5b9868524 instead of the transitive dependency version from json-schema-validator which does not contain the required method.  
> 
> Note: This library is currently not used in master but is required for 71x and 70x.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Preston-Crary please take this over

**Comment by Preston-Crary** [comment]
Please see https://github.com/knchau/liferay-portal-ee/pull/14

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
