### PR TITLE
LPS-135694

### PR DESCRIPTION
**Pull request by attilabakay**
Hi @shuyangzhou,

Could you please review this pull request?
I fixed PMD failure and slightly modified the integration test.
https://issues.liferay.com/browse/LPS-135694
Thank you and best regards,
Attila

previous pull: #10177

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi @shuyangzhou ,

I was wondering if you had the opportunity to check this PR. Could you please update me at your convenience?

Best,

Attila

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by bakayattila** [comment]
Hi @shuyangzhou,
Seems like the ci stuck can we do something about it?

**Comment by GezaGroma** [comment]
Hi @shuyangzhou,
I was wondering if you could give a hand to us with the mentioned CI issue above.
Thanks in advance.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105090

**Pull request closed without merging**
