### PR TITLE
Lps 194952

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
Asked Summer to monitor the results since this is still running.

**Comment by zhangyan0701** [comment]
@shuyangzhou 
No regressions found. And manual testing for https://liferay.atlassian.net/browse/LPS-194952 passed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140021

**Pull request closed without merging**
