### PR TITLE
Lps 58267 Add month/year interval support to repeated jobs by interval and apply to right scenario

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

While I was working on this issue, I found some code about scheduler need to do refactor, so I did not do too much SF in this pull, will send you another pull later.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Send me your plugins side change too.

**Comment by tinatian** [comment]
Sorry that I forgot, please see https://github.com/shuyangzhou/liferay-plugins/pull/82.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/29915

**Pull request closed without merging**
