### PR TITLE
LPS-80310 Support <meta> and <style>, plus misc improvements to error detection

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @vsingleton

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou: The `UpgradeException` failures must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62253

**Pull request closed without merging**
