### PR TITLE
LPS-78194 Remove support for WSRP

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This is exactly the same as the previous PR except that `isRemoteable()` and `setRemotable(boolean)` have been removed from Portlet.java, PortletWrapper.java, and PortletImpl.java. Since master compiles without failures it should be fine for review. Please let me know if you have any questions. Thanks.

/cc @timpak

**Comment by shuyangzhou** [comment]
@ngriffin7a I did a global search, there are still some wsrp appearance
```
./util-taglib/src/com/liferay/taglib/ui/IconDeleteTag.java:		if (url.startsWith("wsrp_rewrite?")) {
./util-taglib/src/com/liferay/taglib/ui/IconDeleteTag.java:				url, "/wsrp_rewrite",
./util-taglib/src/com/liferay/taglib/ui/IconDeleteTag.java:				"&wsrp-extensions=encodeURL/wsrp_rewrite");
./util-taglib/src/com/liferay/taglib/portlet/RenderURLParamsTag.java:		if (ParamUtil.getBoolean(request, "wsrp")) {
./util-taglib/src/com/liferay/taglib/portlet/RenderURLParamsTag.java:			int x = url.indexOf("/wsrp_rewrite");
./.gitignore:/portal-web/docroot/wsrp
./modules/apps/foundation/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/internal/category/WSRPConfigurationCategory.java:	private static final String _CATEGORY_KEY = "wsrp";
./modules/apps/foundation/portal/portal-init-servlet-filter/src/main/java/com/liferay/portal/init/servlet/filter/internal/InitFilter.java:		if (GetterUtil.getBoolean(request.getParameter("wsrp"))) {
./modules/third-party/oasis-names-tc-wsrp
./portal-impl/src/content/Language.properties:category.wsrp=WSRP
./portal-impl/src/content/Language.properties:url-does-not-point-to-a-valid-wsrp-producer=URL does not point to a valid WSRP producer.
./test.properties:        marketplace-plugins-wsrp-portlet,\
```
I think they should be wiped clean too.

**Comment by ngriffin7a** [comment]
Done, see: https://github.com/shuyangzhou/liferay-portal/pull/6062

**Pull request closed without merging**
