### PR TITLE
LPS-X Merge UpgradeStepRegistrator to ensure per bundle there could b…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…e at most one UpgradeStepRegistrator.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 can you check this one?

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@shuyangzhou I was able to reproduce both issues in one single upgrade from 7413

Steps to reproduce:
1. Import this 7413 database [dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip)
2. Add upgrade.database.auto.run=true to portal-ext.properties
3. Start Portal

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10799

**Pull request closed without merging**
