### PR TITLE
Lpd 42697

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:77269201

**Comment by shuyangzhou** [comment]
ci:report:77282530

**Comment by vicnate5** [comment]
@shuyangzhou no unique failures

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/156482

**Pull request closed without merging**
