### PR TITLE
LPS-103534 DBInitUtil

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @vicnate5

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
@Preston-Crary Test results look good!

**Comment by Preston-Crary** [comment]
Fixed the hash in aa2443f4d854a959487dd27dbf8caa4a57321579

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80574

**Pull request closed without merging**
