### PR TITLE
LPS-84093 Petra Stringbundler P to Z

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:test the previous run was aborted by jenkins

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by tomwang2011** [comment]
ci:reopen, the modules unit failure is not due to this pull, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62435

**Pull request closed without merging**
