### PR TITLE
LPS-83992 Portlet 3.0: Develop the bean portlet CDI portable extension (basic structure)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou I moved the new com.liferay.bean.portlet.cdi.extension module to liferay-portal/modules/core

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a I am not really sure where it should go, but it can not be in core. I am thinking maybe modules/apps/portal-bean-portlet-cdi-extension ?

**Comment by ngriffin7a** [comment]
@shuyangzhou OK I'll move it to modules/apps. Closing this PR.

**Comment by ngriffin7a** [comment]
ci:stop

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6543

**Pull request closed without merging**
