### PR TITLE
Lps 129271

### PR DESCRIPTION
**Pull request by SamZiemer**
**Ticket:**
<https://issues.liferay.com/browse/LPS-129271>

tests passed here: https://github.com/SamZiemer/liferay-portal/pull/793

Notes from @kevhlee:
> The issue is that the S3 object where the file input stream comes from is being closed before the input stream is consumed. Hence, the portal throws the exception `java.io.IOException: Attempted read on closed stream`. We still need to close the S3 object to avoid leaking HTTP connections ([LPS-127589](https://issues.liferay.com/browse/LPS-127589)). Thus, my solution is to consume the input stream and create a new one from it before the S3 object is closed. This may not be ideal, but at least this allows us to not worry about closing the S3 object too early.
> 
> Let me know if you have any questions or thoughts.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@SamZiemer you can not just hold the data in memory, it is too much, if the file is big or there are too many concurrent servings, you might get oom. There must be a better way to fix it at the import/export layer. The ticket is only containing an incompleted stack strace, I can not see what caused it.

**Comment by SamZiemer** [comment]
@kevhlee, please see The comment above

**Comment by kevhlee** [comment]
Hi @shuyangzhou,

Thanks for taking a look at this pull request! I do agree that my solution may lead to an out-of-memory error and needs revising. However, I also believe that the issue cannot be fixed in export/import layer. The `S3Object` where the input stream is being prematurely closed before we use the input stream. IMO, the way the portal is using the `S3Object` is incorrect. I can reproduce the issue with this example:

```java
String key = "[INSERT FILE NAME]";
String bucketName = "[INSERT BUCKET NAME]";

S3ObjectInputStream s3ObjectInputStream = null;

try (S3Object s3Object = amazonS3.getObject(bucketName, key)) {
    s3ObjectInputStream = s3Object.getObjectContent();
}
catch (IOException ioException) {
    ioException.printStackTrace(System.err);
}

if (s3ObjectInputStream == null) {
    return;
}

try {
    char[] buffer = new char[1024];

    InputStreamReader inputStreamReader = new InputStreamReader(s3ObjectInputStream, StandardCharsets.UTF_8);

    StringBuilder sb = new StringBuilder();

    for (int read; (read = inputStreamReader.read(buffer, 0, buffer.length)) > 0; ) {
        sb.append(buffer, 0, read);
    }

    System.out.println(sb.toString());
}
catch (IOException ioException) {
    ioException.printStackTrace(System.err);
}
```

However, please let me know your thoughts. Also, I can provide a full stack trace if that will help.

**Comment by kevhlee** [comment]
Here is the full stack trace: <https://issues.liferay.com/secure/attachment/399728/s3_error.log>.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9906

**Pull request closed without merging**
