### PR TITLE
LPS-86394 Move modules com.liferay.bean.portlet.api and com.liferay.bean.portlet.cdi.extension to modules/apps/bean-portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a just to be clear. Both bean-portlet-api and bean-portlet-cdi-extension are not having build trigger, which means ant all won't deploy them. And bean-portlet-cdi-extension has only .lfrbuild-releng-ignore, while bean-portlet-api has only .lfrbuild-semantic-versioning.

Are these all on purpose? It seems a bit weird.

**Comment by ngriffin7a** [comment]
@shuyangzhou Bean Portlets must include com.liferay.bean.portlet.api.jar and com.liferay.bean.portlet.cdi.extension.jar in WEB-INF/lib until https://issues.liferay.com/browse/LPS-85319 is fully merged and skinny bean portlets are fully tested. That's why the .lfrbuild-portal build triggers are missing right now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64275

**Pull request closed without merging**
