### PR TITLE
LPS-202911 Implement onAfterUpdate

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
Manual test passed following the bug steps.

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the CI results, thanks!

**Comment by catarineaguiar** [comment]
@shuyangzhou no regressions found.

**Comment by shuyangzhou** [comment]
Thanks @catarineaguiar !
See https://github.com/brianchandotcom/liferay-portal/pull/144662

**Pull request closed without merging**
