### PR TITLE
Lps 138126 track services 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Real backend test failures here. I can reproduce these locally too.

`./modules/test/persistence-test/src/testIntegration/java/com/liferay/portal/service/persistence/test/LayoutFriendlyURLPersistenceTest.java`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-33/test-portal-acceptance-pullrequest(master)/27/modules-integration-mysql57-jdk8/2/5/jenkins-console.txt.gz

`./modules/test/persistence-test/src/testIntegration/java/com/liferay/portal/service/persistence/test/GroupPersistenceTest.java`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-33/test-portal-acceptance-pullrequest(master)/27/modules-integration-mysql57-jdk8/2/5/jenkins-console.txt.gz

`./modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/service/persistence/test/FragmentEntryLinkPersistenceTest.java`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-33/test-portal-acceptance-pullrequest(master)/27/modules-integration-mysql57-jdk8/0/22/jenkins-console.txt.gz

`./modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/persistence/test/CommerceChannelPersistenceTest.java`
https://testray.liferay.com/reports/production/logs/2021-09/test-1-33/test-portal-acceptance-pullrequest(master)/27/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will look into them!

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10295

**Pull request closed without merging**
