### PR TITLE
Lps 148397

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me confirm this pull fixes the issue described in the ticket. Also check the test results once they are in to make sure there is no regression.

This is a workaround for a jdk bug, please test it on both jdk8 and jdk11.

Thanks!

**Comment by zhangyan0701** [comment]
Hi @shuyangzhou 

The testing of [LPS-148397](https://issues.liferay.com/browse/LPS-148397) passed on Windows10 + Jdk8.

On Jdk11, the parent folder (which is called 日本語フォルダ1 in the ticket) can not be downloaded, after clicking Download, page redirected to a blank page, but the sub folder can be downloaded. Please see the gif:
jdk11

No other regressions found from the automation tests.

**Comment by shuyangzhou** [comment]
@zhangyan0701 see https://github.com/shuyangzhou/liferay-portal/pull/10692/commits/071de7acb394364fbe924ecdbdf54f758c2b2054 
 if you are unzipping tomcat, it should work. If you are using existing tomcat, you need to copy that line into your setenv.bat/setenv.sh. Please try it again.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me to finish off the jdk11 checking, thanks!

**Comment by vicnate5** [comment]
See
https://github.com/shuyangzhou/liferay-portal/pull/10694

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
This can be reopened. We are going to use this original solution instead.

**Comment by vicnate5** [comment]
PASSED Manual Testing following the steps in https://issues.liferay.com/browse/LPS-148397 on:
Windows 10 + HSQL + JDK 8
Windows 10 + HSQL + JDK 11

**Comment by vicnate5** [comment]
See https://github.com/liferay/liferay-portal/pull/4835

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
