### PR TITLE
[Bug Fix]LPS-140103

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Trigger CCR test at https://github.com/tinatian/liferay-portal/pull/2414

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Tina

**Comment by vicnate5** [comment]
@tinatian This is good now, tested passed on CCR change as well (https://github.com/tinatian/liferay-portal/pull/2414)
CC @xbrianlee

**Comment by tinatian** [comment]
Rebase and resend at https://github.com/tinatian/liferay-portal/pull/2415

**Pull request closed without merging**
