### PR TITLE
LPS-69778 Logger performance

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Preston-Crary they are real failures.

**Comment by Preston-Crary** [comment]
Sorry forgot to rebuild the manifest:
https://github.com/shuyangzhou/liferay-portal/pull/3580

**Pull request closed without merging**
