### PR TITLE
LPS-71601 Update alloy-taglibs to 1.1.12

### PR DESCRIPTION
**Pull request by brunobasto**
Hey, @shuyangzhou 

Other than these files changed [here](https://github.com/shuyangzhou/liferay-portal/pull/4151/commits/b5341ef48da6134c19551683718ef3da61d9be2b), looks like it's generating other tags that were probably removed, but not removed from the generator's input file, like PanelTag, ComponentTag and SpacerTag. Do you know anything about that?

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@brunobasto sounds like a problem with the util-taglib-compat module.  I'll try to look into that soon.

Thanks for your help

**Comment by brunobasto** [comment]
No problem! Let me know if you need anything. Thx!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48558

**Comment by shuyangzhou** [comment]
Thanks @brunobasto ! We will find a way to prevent removed tags being generated again sometime later.

**Pull request closed without merging**
