### PR TITLE
[Multi Company Startup Tuning]LPS-135423

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Unique integration test failure. I reproduced locally with ` gw testIntegration --tests JournalTestUtilTest`
```
com.liferay.journal.util.test.JournalTestUtilTest > classMethod FAILED
    com.liferay.portal.kernel.search.SearchException: java.lang.NullPointerException
        at com.liferay.portal.kernel.search.BaseIndexer.getDocument(BaseIndexer.java:180)
        at com.liferay.journal.internal.search.JournalArticleIndexer._reindexEveryVersionOfResourcePrimKey(JournalArticleIndexer.java:1024)
        at com.liferay.journal.internal.search.JournalArticleIndexer.doDelete(JournalArticleIndexer.java:422)
        at com.liferay.journal.internal.search.JournalArticleIndexer.doDelete(JournalArticleIndexer.java:119)
        at com.liferay.portal.kernel.search.BaseIndexer.delete(BaseIndexer.java:124)
        at com.liferay.portal.kernel.test.rule.DataGuardTestRule._smartDelete(DataGuardTestRule.java:600)
        at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteLeftovers(DataGuardTestRule.java:293)
        at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteAndAssert(DataGuardTestRule.java:193)
        at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:115)
        at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:73)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:66)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException
        at com.liferay.portal.util.LocalizationImpl._getRootAttributeValue(LocalizationImpl.java:1439)
        at com.liferay.portal.util.LocalizationImpl.getAvailableLanguageIds(LocalizationImpl.java:97)
        at com.liferay.journal.internal.search.JournalArticleIndexer.doGetDocument(JournalArticleIndexer.java:449)
        at com.liferay.journal.internal.search.JournalArticleIndexer.doGetDocument(JournalArticleIndexer.java:119)
        at com.liferay.portal.kernel.search.BaseIndexer.getDocument(BaseIndexer.java:152)
        ... 16 more
```
Full CI log https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/2736/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz

I think we should run this change through the default ci test suite once this is fixed.

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian Full test results show the same issue on multiple integration tests (the issue in https://github.com/shuyangzhou/liferay-portal/pull/10158#issuecomment-878451792)

Failing test classes:
[com.liferay.journal.util.test.JournalTestUtilTest](https://testray.liferay.com/home/-/testray/case_results/1546674351)
[com.liferay.journal.service.test.JournalArticleServiceTest](https://testray.liferay.com/home/-/testray/case_results/1546674114)
[com.liferay.exportimport.internal.content.processor.test.DefaultExportImportContentProcessorTest](https://testray.liferay.com/home/-/testray/case_results/1546673921)
[com.liferay.asset.publisher.lar.test.AssetPublisherExportImportTest](https://testray.liferay.com/home/-/testray/case_results/1546673331)

No other regressions found.

**Pull request closed without merging**
