### PR TITLE
LPS-62786 Remove org.apache.commons.beanutils.PropertyUtils from ItemSelectorCriterionSerializer 

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased, minor conflicts.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Same tests that are failing in my other pulls to you, I doubt I broke the same thing in all of them.

**Pull request closed without merging**
