### PR TITLE
Lps 178829 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:tango

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou No unique failures found, PR should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132239

**Comment by kyle-miho** [comment]
ci:forward

**Comment by kyle-miho** [comment]
ci:stop

**Pull request closed without merging**
