### PR TITLE
LPS-75087 Company - Auto

### PR DESCRIPTION
**Pull request by ealonso**
Hey @shuyangzhou,

I've extracted some more tests. I sent it to me self and everything seems to be working fine, but if you find some broken test related with this one please let me know to fix it before sending to Brian.

Thanks!!,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest
@ealonso I think the unique index failures are real. but testing it again to be sure.

**Pull request closed without merging**
