### PR TITLE
LPS-X Move expired lock clearing logic into a verify process.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found, just needs version bump
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.lock                     MAJOR      8.0.0      8.0.0      9.0.0      VERSION INCREASE REQUIRED
     [exec]     >   class      com.liferay.portal.kernel.lock.LockManagerUtil
     [exec]             -   method     clear()
     [exec]                     -   access     static
     [exec]                     -   return     void
     [exec]     >   interface  com.liferay.portal.kernel.lock.LockManager
     [exec]             -   method     clear()
     [exec]                     -   access     abstract
     [exec]                     -   return     void
     [exec] [Baseline Report] Mode: diff (persisted)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130605

**Pull request closed without merging**
