### PR TITLE
Revert lps 90058

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
Hi Shuyang,

Please hold this pull as Eudaldo send me a pull about fix the regression to verify.

Lily

**Comment by slnn** [comment]
This one still be needed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68902

**Comment by brianchiu** [comment]
@slnn What was the performance regression that this caused?

**Comment by brianchiu** [comment]
@slnn nevermind. There was an email I wasn't part of that Kyle forwarded to me.

**Pull request closed without merging**
