### PR TITLE
[Log4j]LPS-125550

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian I think this failure is related: https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429403/AXIS_VARIABLE=11,label_exp=!master/testReport/junit/com.liferay.portal.remote.cors.client.test/PortalConfigurationCORSClientTest/testNoCORSUsingPortalSession/. Passes upstream.

No other unique issues found.

**Comment by tinatian** [comment]
Thanks @vicnate5 ! Just checked it locally, it is a real failure, I will send out a new pull.

Tina.

**Comment by tinatian** [comment]
Reopen as the unique failure is not caused by this pull, it is a bug on master

**Comment by vicnate5** [comment]
@shuyangzhou This is ready to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100200

**Pull request closed without merging**
