### PR TITLE
LPS-87729

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 I included your fix for functional test, could you please trigger the cluster test to make sure I did not break anything?

Thanks.
Tina

**Comment by tinatian** [comment]
@lanceji92674957 Could you please check the startup performance?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please check the functional test failures?

Thanks.
Tina

**Comment by lanceji92674957** [comment]
Hi @tinatian @vicnate5 @shuyangzhou ,

FYI, today's baseline of startup performance: 
avg: 40.55

with this pull:
avg: 40.86

**Comment by vicnate5** [comment]
Needs test fix https://github.com/tinatian/liferay-portal/pull/1123

**Comment by shuyangzhou** [comment]
This is all merged already, right?

**Comment by tinatian** [comment]
@shuyangzhou Yes, it is merged.

**Pull request closed without merging**
