### PR TITLE
LPS-129058 Move JournalArticle content to DDMField tables

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Hey @david-gutierrez-mesa, @Tim-Cao, @liulukiwi,

Could you please take a look to poshi failures?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @Preston-Crary @shuyangzhou,

The QAs of Echo team are going to take a look to the tests results, to check if the failures under test:echo are related with your changes or not.

Regards,
Eudaldo

**Comment by Tim-Cao** [comment]
One of regression issues.
Step to reproduce
1. Add a web content structure with a Text field > Save
2. Edit Default Values for new structure
3. Type default content in Text field
4. Change to es-ES locale
5. Type localized content in Text field
6. Save
7. Add a web content based on new structure
8. Assert the default content is shown in Text field
9. Change to es-ES locale

**Actual Result:**
The default content is shown in Text field

**Expect Result:**
The localized content should be shown in Text field

**Comment by Preston-Crary** [comment]
Thanks guys, I'll fix and resend!

**Comment by Preston-Crary** [comment]
When manually testing the steps I got the expected result.  @Tim-Cao, please double check to make sure I'm following the steps correctly

Please see https://github.com/shuyangzhou/liferay-portal/pull/9935

**Pull request closed without merging**
