### PR TITLE
LPS-155278 Use root path to indicate spring this is not an URL to avo…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…id the unnecessary MalformedURLException

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, Summer is on vacation, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

Thanks @zhangyan0701 !

**Pull request closed without merging**
