### PR TITLE
Commons collection removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
Additional test failure:
[com.liferay.search.experiences.rest.resource.v1_0.test.SXPBlueprintResourceTest](https://testray.liferay.com/home/-/testray/case_results/1799491987)

no other regressions found.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check this again, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Still a couple failing backend tests

https://testray.liferay.com/home/-/testray/case_results/1828422581
```
     [exec] com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest > testExportCsv FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
     [exec]     	at net.sf.jasperreports.engine.data.JRAbstractTextDataSource.getConvertBean(JRAbstractTextDataSource.java:158)
     [exec]     	at net.sf.jasperreports.engine.data.JRAbstractTextDataSource.convertStringValue(JRAbstractTextDataSource.java:78)
     [exec]     	at net.sf.jasperreports.engine.data.JRCsvDataSource.getFieldValue(JRCsvDataSource.java:356)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFillDataset.setOldValues(JRFillDataset.java:1501)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1402)
     [exec]     	at net.sf.jasperreports.engine.fill.SortFillDatasetRun.advanceDataset(DatasetSortUtil.java:371)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFillDatasetRun.iterate(JRFillDatasetRun.java:300)
     [exec]     	at net.sf.jasperreports.engine.fill.SortFillDatasetRun.sort(DatasetSortUtil.java:319)
     [exec]     	at net.sf.jasperreports.engine.fill.DatasetSortUtil.getSortedDataSource(DatasetSortUtil.java:112)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFillDataset.initDatasource(JRFillDataset.java:733)
     [exec]     	at net.sf.jasperreports.engine.fill.BaseReportFiller.setParameters(BaseReportFiller.java:457)
     [exec]     	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:578)
     [exec]     	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:433)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:162)
     [exec]     	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
     [exec]     	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
     [exec]     	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
     [exec]     	at com.liferay.portal.reports.engine.console.jasper.internal.fill.manager.BaseReportFillManager.fillReport(BaseReportFillManager.java:99)
     [exec]     	at com.liferay.portal.reports.engine.console.jasper.internal.ReportEngineImpl.execute(ReportEngineImpl.java:108)
     [exec]     	at com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest._export(ReportEngineImplTest.java:154)
     [exec]     	at com.liferay.portal.reports.engine.console.jasper.internal.test.ReportEngineImplTest.testExportCsv(ReportEngineImplTest.java:89)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.FastHashMap
     [exec]     	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407)
     [exec]     	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
     [exec]     	at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:79)
     [exec]     	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec]     	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]     	... 50 more
```
https://testray.liferay.com/home/-/testray/case_results/1828420995
```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.ContentElementResourceTest > testGetAssetLibraryContentElementsPageWithSortDouble FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/collections/FastHashMap
     [exec]     	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyDescriptor(PropertyUtilsBean.java:964)
     [exec]     	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:935)
     [exec]     	at org.apache.commons.beanutils.BeanUtils.setProperty(BeanUtils.java:454)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.ContentElementResourceTest.lambda$_getUnsafeTriConsumer$0(ContentElementResourceTest.java:166)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseContentElementResourceTestCase.testGetAssetLibraryContentElementsPageWithSort(BaseContentElementResourceTestCase.java:535)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.ContentElementResourceTest.testGetAssetLibraryContentElementsPageWithSortDouble(ContentElementResourceTest.java:49)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.FastHashMap
     [exec]     	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407)
     [exec]     	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
     [exec]     	at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:79)
     [exec]     	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec]     	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]     	... 37 more
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found on new results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117832

**Pull request closed without merging**
