### PR TITLE
LPS-112857 BasePersistence.dslQuery() part 3

### PR DESCRIPTION
**Pull request by Preston-Crary**
No rush on this part, just removing the remaining CT service FinderImpls so there's some more usages of the new API. Not sure what kind usage pattern we want to make with this.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

@Preston-Crary this should be fine, just if you are planning to remove other finderimpl, make sure to only deprecated them rather than really removing them. Some customers customize our finder at the xml/sql and finderimpl.java level. Developer tools will be able to scan and warn them for that cases, but at least we need to keep their code can be compiled by not removing our finders.

**Pull request closed without merging**
