### PR TITLE
[Bug Fix]LPS-107979

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @vicnate5,
Please scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian There were 2 unique failures on the clustering suite, they do not look like regressions, but re-running to be certain. Other test runs show no regressions.

**Comment by shuyangzhou** [comment]
@vicnate5 any real failures here?

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go on the testing side.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84884

**Pull request closed without merging**
