### PR TITLE
LPS-88547 Cache configuration

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is going to simplify the cache configuration for modules. Please see https://issues.liferay.com/browse/LPS-88547 for more details.

FYI @jhinkey @vicnate5

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@tinatian rebase failure, please resend. Thanks!

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/7228

**Pull request closed without merging**
