### PR TITLE
Startup optimization 302 configuration screen

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou 
Just Semver here: https://testray.liferay.com/reports/production/logs/2023-10/test-1-26/test-portal-acceptance-pullrequest(master)/11345/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141910

**Pull request closed without merging**
