### PR TITLE
CI AspectJ

### PR DESCRIPTION
**Pull request by Ithildir**
The [`aijc`](https://eclipse.org/aspectj/doc/next/devguide/antTasks-iajc.html) task has a million arguments, I hope the ones I set are enough!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:stop

Thanks @Ithildir !

**Comment by Ithildir** [comment]
No problem! 😊 I added https://github.com/shuyangzhou/liferay-portal/pull/3397/commits/e4bac974cd440ec8352634880e51d966e522258f, just to keep things sorted. Unfortunately, I have to leave the `configurations` block at the beginning of the file, even if it's out of order.

**Comment by Ithildir** [comment]
Sorry, yesterday I was wrong: it is actually possible to sort all the blocks 😅 If you're still interested, I force-pushed the only commit that you need to use AJC in your module.

**Comment by shuyangzhou** [comment]
Yes, please, thanks @Ithildir !

**Comment by Ithildir** [comment]
Perfect, sorry again for the confusion! Here is the final commit: https://github.com/shuyangzhou/liferay-portal/pull/3397/commits/821d98dd03f27f46abc13838e7122768722ed678

**Comment by shuyangzhou** [comment]
What are you sorry about! You have been nothing but helpful! Thanks @Ithildir !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/44515 Thanks @Ithildir !

**Pull request closed without merging**
