### PR TITLE
[ResourceAction]LPS-115506

### PR DESCRIPTION
**Pull request by tinatian**
FYI @Preston-Crary

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
@tinatian, so the map put had the wrong key. But why not pass in the portlet still?  I'm not sure what makes this way better by only looking at it.

**Comment by tinatian** [comment]
@Preston-Crary We are simplify the ResourceActions now, so this will help to clean the logic. Anyway adding an extra API which is only used once is not a good idea.

**Comment by Preston-Crary** [comment]
I think I understand, you just don't want the API.

**Comment by tinatian** [comment]
@Preston-Crary Yes, you are right. Another reason is this fixed it in the root while the original one covered the root cause.

**Comment by tinatian** [comment]
@vicnate5 The unique failures seemed not related to this pull, could you please take a look?

Thanks.
Tina.

**Comment by vicnate5** [comment]
Regression on master upstream with LCS, fix is being worked on. Will update when it is fixed so this can be re-run.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
