### PR TITLE
LPS-75807 WSRP fix and optimize for the human brain

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: When you get an opportunity, please verify that these failures are unrelated to the PR. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54469

**Comment by jpince** [comment]
@ngriffin7a looks ok

**Comment by ngriffin7a** [comment]
Thanks @jpince

**Pull request closed without merging**
