### PR TITLE
LPS-72541 Support env vars configuration

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mdelapenya it is better. But we still have the :
```
private static final Map<String, String> _systemEnvironment =
		System.getenv();
```
This should go away too. We should save all related env variables into _componentConfiguration during initialization, then we just need to read from _componentConfiguration at runtime.

And I think we should simplify the naming rules for env variables. We could simply just ask for a prefix, then chop off the prefix to take the rest name exactly as the key for overwriting.

**Comment by mdelapenya** [comment]
For the systemEnv map, I created it as a static final variable to have the environment initialised on startup, instead of calling it on every get* method. If you prefer it, I could remove it and invoke the System.getEnv().get(key) method on each get* method.

For the naming conventions, if we just add a prefix, then the env variable name will be illegal: no dots on the name (see http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html). That's why  we uppercase and replace separators with underscores.

**Comment by shuyangzhou** [comment]
@mdelapenya we should not have the systemEnv map or using System.getEnv().get(key), because that means layered reads. And when you do the ConfigrationImpl.set(), you will have to save it somewhere else or put them into the systemEnv map, which will be really weird. Everything should go into the _componentConfiguration, that's the simplest way to do this.

For the naming, if that's os level requirements, then it is fine. But I think we should remove this "if and only if the property does not start with LIFERAY_ (i.e. liferay.home)", just let it to be LIFERAY_LIFERAY_HOME.
This is necessary because when you scan env variables to populate the _componentConfiguration, it can be as simple as, remove the prefix, replace '_' to '.', lower case the name, then just do a put. Otherwise you won't know when to remove the prefix, when to preserve it.

Make sense?

**Comment by mdelapenya** [comment]
Ok, for the prefix, makes sense to be consistent about naming, always adding the prefix 😃 

And for the env var read, I'm storing the value of the envVar into the _componentConfiguration, please see https://github.com/shuyangzhou/liferay-portal/pull/4290/commits/c16b9a71582023527b4d377cac0e58f14ad83c61. Is that enough?

Thanks!

**Comment by shuyangzhou** [comment]
@mdelapenya the save in https://github.com/shuyangzhou/liferay-portal/commit/c16b9a71582023527b4d377cac0e58f14ad83c61 is per-read based, not all at once during initialization. That's why you need to keep the _systemEnvironment.

What we should do is scan all System.getenv() during initialization, save all variables whose name starts with LIFERAY_ into _componentConfiguration. Then we can just read _componentConfiguration at runtime.

**Comment by mdelapenya** [comment]
Got it, let me resend going back to the initial approach, getting the env and filtering by LIFERAY_ vars just on initialisation.

**Comment by shuyangzhou** [comment]
Thanks @mdelapenya !

**Pull request closed without merging**
