### PR TITLE
LPS-66285 Add pagination support to sitemap generation to avoid OOM

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Everything looks good, except this commit. https://github.com/shuyangzhou/liferay-portal/pull/2975/commits/91b424fe12d87496cc02dd2f8d79f469de015c34

DateFormat is not threadsafe, we should not pull it out as a static field.

**Comment by Preston-Crary** [comment]
Okay, I'll drop off that commit and update the pull sometime today.

**Comment by Preston-Crary** [comment]
ci:retest Dropped off the commit and rebased.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/2993

**Pull request closed without merging**
