### PR TITLE
Lpd 25633 optimization

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is a draft version I want to use as a milestone to stabilize things. I have made many aggressive db side optimizations, which is very likely causing many regressions already.

@vicnate5 please help me monitoring and check CI results, collect the integration test failures first, after they are cleared then move to functional tests.

@victorhcunha please rerun your test on this pull https://liferay.atlassian.net/browse/LPD-25633 , but since this is just a draft version, as I fix regressions, performance is likely to drop back a bit. This round time is just trying to get us a general idea about the improvement. Once this is stabilized, I may go further on the optimization, we will need more rounds of testing. 

Thank you guys!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:report:62716875

**Comment by vicnate5** [comment]
ci:report:62505888

**Comment by shuyangzhou** [comment]
Newer version https://github.com/shuyangzhou/liferay-portal/pull/11590 which should fix a bunch of search test failures.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the partial results of importing with this PR:

Round | Master Baseline fe5dd72 | PR1 #11589 | Difference (%)
-- | -- | -- | --
1 | 1421883 | 836687 | -41.1564102
2 | 1441309 | 770926 | -46.51209421
3 | 1424921 | 819755 | -42.47014396
4 | 1421783 | 696497 | -51.01242595
5 |   | 712292 | 
6 |   | 780255 |
| |  | 
Average (ms) | 1427474 | 769402 | -46.10045437
Standard Deviation (ms) | 9337.590624 | 56141.77971 | 501.2448175

More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1PBtCQXwEi5dWI6AkHIgnufchuIm648xJHEzcF_dIchU/edit?gid=361924969#gid=361924969)
I am waiting for the results of 2 more rounds on the master baseline before testing the new PR.

**Comment by shuyangzhou** [comment]
@victorhcunha for me, I am seeing the time changed from 300+s down to 90+s

Comparing to yours, before the change 1400/300=4.7, after the change 800/90=8.9

The scaling factor is quite off. That means your system is facing different bottlenecks as mine.

I need you to run a async CPU profile on this pull in your test env.

1) Start tomcat with yourkit agent.
2) Do all your setup on browser.
3) Start async CPU profile with CPU Sampling Settings to "time=cpu"
4) Run the curl command to start import.
5) Save the yourkit snapshot as soon as the tomcat console prints import is finished.

Then send the profile to me.

**Comment by victorhcunha** [comment]
Here are the snapshots:

[master-baseline-fe5dd72](https://drive.google.com/file/d/1AIEMb5SAKAERMSzjdn9zFHl7cM4kr664/view?usp=sharing) | [pr](https://drive.google.com/file/d/1xNDiPHScWrwjzkc71TzOQV91bKmEwup0/view?usp=sharing)
-- | --

**Pull request closed without merging**
