### PR TITLE
Lps 58449 Refactor scheduler related classes

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

With these changes, a NumberFormatException would come up while starting portal, it is caused by an old bug(see https://issues.liferay.com/browse/LPS-58479), will send pull request to Micheal Han who made those changes before.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
It is ok, the build failure is not caused by you. I just did not have time to review it yet, will try to get on to it tomorrow.

**Comment by shuyangzhou** [comment]
I don't really like the TriggerContent design, that is technically the same as what we currently have with TriggerType, after all in the end you still have to instance of to test the actual TriggerContent type to behave differently.

I think we should create our own TriggerBuilder interface/impl, bridge it to Quartz's TriggerBuilder at impl level. At least this way we don't have to do instance of any more.

If you think otherwise, please resend, then we can talk about it.

**Comment by tinatian** [comment]
Em....I will think about your suggestion, will resend pull request about this.

**Pull request closed without merging**
