### PR TITLE
Lps 107195

### PR DESCRIPTION
**Pull request by shuyangzhou**
@slnn please re-check performance regression, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull once CI is done, thanks!

**Comment by slnn** [comment]
OK, got it

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in test results

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 44465 | 267 | 80 | -
PR | - | 44691 | 264 | 79.2 | 0.5082649275


WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 55473 | 519 | 157 | -
PR | - | 56181 | 566 | 176 | 1.276296577

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 17721 | 208 | 203 | -
PR | - | 17680 | 177 | 204 | -0.2313639185

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 26154 | 187 | 255 | -
PR | - | 26182 | 182 | 249 | 0.1070581938

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 15588 | 294 | 502 | -
PR | - | 15568 | 259 | 475 | -0.1283038235

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 712e317 | 26602 | 437 | 179 | -
PR | - | 26523 | 407 | 170 | -0.2969701526



Regards
Lily

**Comment by arthurchan35** [comment]
Hi @shuyangzhou ,
Just a small note:
LPS-107195 Use regionMatches to avoid unnecessary substring    64007de
LPS-107195 SF                                                                                 d2ad544
LPS-107195 Expose getURI() method                                              f074925
LPS-107195 Semantic versioning                                                     5456e5d
These 4 commits should probably be under LPS-107404

**Comment by csierra** [comment]
hey @shuyangzhou, 
do you want us to rebase the pull and separate the commits in the different LPS?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85445

**Pull request closed without merging**
