### PR TITLE
Startup optimization 247 log service enabled logger concurrency

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
No additional issues here beyond https://github.com/shuyangzhou/liferay-portal/pull/11083#issuecomment-1569360155

**Pull request closed without merging**
