### PR TITLE
[Performance] LPS-82275

### PR DESCRIPTION
**Pull request by tinatian**
Hi @dantewang,
I think this solution should have same performance improvement as yours, please verify.

Hi Shuyang,
Please wait for Dante's verification and CI result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by slnn** [comment]
Test results on Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | c089801 | 5157 | 101 | 374
PR | - | 5274 | 61.5 | 273

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60300

**Pull request closed without merging**
