### PR TITLE
LPS-105035 Upgrade Fix | master

### PR DESCRIPTION
**Pull request by vicnate5**
Manually tested by QA, both the fix and the new exception

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Test results look good here too.

**Comment by achaparro** [comment]
Hi @mtambara,

I took a quick look at the pull and I want to ask you for a few questions:
- We allow to not execute micro schema version changes. This means that a module can work if the schema version in the database is 1.0.0 and the required schema version is 1.0.1. I think there is no problem with your pull because once we execute the upgrades for a module we execute all of them so [this verification](https://github.com/shuyangzhou/liferay-portal/pull/8600/files#diff-6a1ae3845f854526f44b03d27ac4f7d1R130) is not problematic but, can you confirm that it won't be any issue with it?
- Since we rely on require-schema-version label this will only work for service builder modules, are we ok with it?

Thanks.

**Comment by mtambara** [comment]
@achaparro 

- This will be fine as long as the upgrade step to the required micro version actually exists. This seems like a reasonable assumption because I can't think of a reason to bump up the micro schema version unless you need to upgrade
- It's fine if this only works for service builder modules, this is only to inform that a service will not start because it has not upgraded to the required schema. If there is no required schema, then the service will start no matter what.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81677

**Pull request closed without merging**
