### PR TITLE
Lps 185647 redo 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by kyle-miho** [comment]
[LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) and https://liferay.atlassian.net/browse/LPS-185647 should not be reproduceable with these changes, I tested manually by compiling the bundle

**Comment by kyle-miho** [comment]
LocalFile.DatabasePartitioning#CanSetVirtualHostViaPages failure for db-partition is flakey, NOT UNIQUE
LocalFile.DatabasePartitioning#NewCompanyStillAccessibleAfterRestart failure is flakey, NOT UNIQUE
Other tests passed or already are failing upstream already

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/11127

**Pull request closed without merging**
