### PR TITLE
LPS-X Change default isolation level to portal.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this is fixing some issues @david-truong found during CT developing. But it may have a much bigger impact system wide. We need a through test, please add more batches that you think is necessary.

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
Changed to a different approach to cover all jdbc connections, not just hibernate usages.
See https://github.com/shuyangzhou/liferay-portal/pull/11246

**Pull request closed without merging**
