### PR TITLE
[TECHNICAL-SUPPORT] LPS-56346 plus commit: backward compatibility

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-56346

Hi Shuyang,

I've added lipusz@b92cdd4 and lipusz@8147582 because of liferay@f4ab9a63911a4fc1b93404b053682255688f9315

Cheers,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
I'm looking into it to find out what to update to fully cover MICSR.

On Tue, Sep 15, 2015 at 4:03 PM, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 1 hour 11 seconds
> Job Results:
>
> 15 Jobs Passed.
> 1 Job Failed.
> See the following links for more information.
>
>    - test-portal-acceptance-pullrequest(master)
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/41/>
>
>    Completed with the status of FAILURE.
>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/0
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-db2
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/634/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-oracle
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/434/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-postgresql
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-sybase
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-db2
>    <https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-oracle
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/438/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-sybase
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440/>
>    - test-portal-acceptance-pullrequest-batch(master)/modules-unit
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/635/>
>    - test-portal-acceptance-pullrequest-batch(master)/plugins
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/435/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441/>
>    - test-portal-acceptance-pullrequest-batch(master)/service-builder
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442/>
>    - test-portal-acceptance-pullrequest-batch(master)/tck
>    <https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/426/>
>    - test-portal-acceptance-pullrequest-batch(master)/unit
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442/> Job
>    Results:
>
>    2271 Tests Passed.
>    1 Test Failed.
>    -
>       TestSuite.com.liferay.portal.kernel.servlet.MetaInfoCacheServletResponseTest
>       <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/442//testReport/junit.framework/TestSuite/com.liferay.portal.kernel.servlet.MetaInfoCacheServletResponseTest>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/33/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shuyangzhou/liferay-portal/pull/1794#issuecomment-140403581>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer

Team Lead, Platform TS, EMEA
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by lipusz** [comment]
Pushed lipusz@b299659

**Comment by lipusz** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/30180

**Pull request closed without merging**
