### PR TITLE
Mbowerman lps 79012

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mbowerman why is https://github.com/shuyangzhou/liferay-portal/pull/5916/commits/127be32bdd4f9d1daace7710b136adf5b1d7ed63 need? Do you see any deadlock somewhere?
That timeout is only read by oracle 9i+, no other dbs support that.
I don't want to provide this switch to customers which makes them believe they have control over it, while in most cases they don't.

On the other hand, this is for counter only, which has very very tiny transactions. You can hardly generate enough load to actually see the lock blocks for a long time. And even you do see it under crazy load, we should prefer forever waiting, because this is not a deadlock. If you are blocked, it could only mean you have too much load. Rollback the counter tx is not going to make thing any better. We should block there to wait until DB returns. This way we hold on the appserver thread to prevent it from trying again which will only make things worse.

**Comment by holatuwol** [comment]
@shuyangzhou: Yes, one of our customers is currently seeing something that looks like classic database deadlock on MySQL, where all application server threads are blocked behind the latch that updates the Counter table, and the server is not accessible until the server is restarted.

If the method we're switching to won't fix the issue, do you have another suggestion?

**Comment by shuyangzhou** [comment]
This fix makes no difference for MySQL, mysql hibernate dialect simply ignores the timeout parameter.
Get a portal side thread dump, plus DB side ```SHOW ENGINE INNODB STATUS```, see https://dev.mysql.com/doc/refman/5.7/en/innodb-standard-monitor.html . We will need to understand how do they get the deadlock first, before we can fix it.

**Comment by shuyangzhou** [comment]
@SamZiemer @holatuwol @mbowerman 
I merged this without https://github.com/shuyangzhou/liferay-portal/commit/127be32bdd4f9d1daace7710b136adf5b1d7ed63 . Please provide the customer side deadlock info once you have it, we can look into it to find out what is happening to them.

See https://github.com/brianchandotcom/liferay-portal/pull/56962

**Pull request closed without merging**
