### PR TITLE
[TS] LPS-106908

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-106908

When attempting to access certain portlet URLs from a blogs portlet which has been embedded onto a fragment, many params are lost and therefore portlet navigation does not work properly.  The cause of this problem is a combination or two aspects:

1. Portlets embedded in fragments are namespaced with their unique instance ID (portets added to a widget page are not).
2. Pages do not include render params if they are implicit.  Implicit params can be seen on the routes.xml files.
This causes this bug because the portal is searching for the namespaced params, however they have been scrubbed due to the routes.xml file.  Only the non-namespaced params exist.

So, in order to resolve this issue, we simply remove the matching entries in the routes.xml file, and thus the portal will explicitly add the params instead.  Once this is done, the namespaced params now appear in the URL and can be accessed when needed.

Please let me know if you have any questions, or if this PR should be forwarded to someone else.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please scan the ci results for me.

@slnn please run a regression test for blogs.

**Comment by vicnate5** [comment]
ci:test:blogs

**Comment by holatuwol** [comment]
@ChrisKian : Wwe were originally running into the problem with a custom portlet, not for blogs, but I was able to reproduce the issue in a clean bundle simply by choosing a portlet with friendly URL routes.

Doesn't the solution that we've chosen imply that people can't add a portlet to a content page if it uses friendly URL routes?

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results on Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 58f1f01 | 14496 | 470 | 416
PR- | - | 14526 | 809 | 558

Regards
Lily

**Comment by ChrisKian** [comment]
Hey @holatuwol,

To answer your question, yes and no.  The "yes" is because there could be other portlets out there which suffer from this same issue, and obviously the solution only resolve this exact scenario.  The "no" is because a similar solution can be made for any new portlets.  It's not an ideal situation, as we are plugging the holes as they appear, but this solution (to me) made the least impact on the portal as a whole, and I was treading as lightly as I could.

A more "complete" solution (although much more intrusive) would be to include a non-namespaced param search within ParamUtil.  In the case of blogs, [we search for the MVCRenderCommandName using the given portletID](https://github.com/liferay/liferay-portal/blob/master/modules/apps/adaptive-media/adaptive-media-blogs-web/src/main/java/com/liferay/adaptive/media/blogs/web/internal/portlet/filter/BlogsPortletFilter.java#L66).  For portlets embedded within fragments, they are always namespaced with an instanceId, however when adding the params, they aren't namespaced (when the routes are enabled), so there is never a match here.  If we could include a search for the namespace at the ParamUtil level, this would resolve the issue for all cases, I just didn't want to create a large impact on the portal unless it was the right way to go.

We can discuss this issue further, just let me know if you have any questions.  Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou High failure rate for blogs testing, will need to investigate further.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@ChrisKian the performance regression is real, and @holatuwol 's concern is right too, we can not just fix it for blogs. Plus there is possible function regressions that @vicnate5 is verifying now.

This is really something should go through fragment team to get a general solution, rather than fixing it case by case. Please work with fragment team first, then come back to me to verify performance regressions for the new solution.

**Comment by koor4356** [comment]
Hey @ChrisKian 
We are seeing virtual Instances is temporarily unavailable. You can download the portal-bundle from this pr. Start it up and navigate to control panel -> configuration -> Virtual Instances.  You should see "Virtual Instances is temporarily unavailable." Also, an exception error is thrown. Thanks!

https://testray.liferay.com/reports/production/logs/test-1-14/1578705788327/test-portal-acceptance-pullrequest(master)/5350/functional-tomcat90-mysql57-jdk8/3/1/jenkins-console.txt.gz

`2020-01-13 19:41:35.113 ERROR [http-nio-8080-exec-10][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
2020-01-13 19:41:35.115 ERROR [http-nio-8080-exec-10][PortletServlet:119] javax.portlet.PortletException: org.apache.jasper.JasperException: com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
javax.portlet.PortletException: org.apache.jasper.JasperException: com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:306)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:572)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:588)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:462)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:304)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)`

**Pull request closed without merging**
