### PR TITLE
Lps 101084 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou Upgrades fail
```
com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.ViewCountEntry' doesn't exist
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:101)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:173)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:140)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:122)
	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:154)
	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:85)
	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:174)
	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:55)
Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.ViewCountEntry' doesn't exist
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:101)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:141)
	at com.liferay.portal.upgrade.PortalUpgradeProcess.doUpgrade(PortalUpgradeProcess.java:129)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96)
	... 12 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'lportal.ViewCountEntry' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1094)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1042)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1345)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1027)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.liferay.portal.kernel.upgrade.UpgradeViewCount.doUpgrade(UpgradeViewCount.java:54)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96)
	... 15 more
```
Full log https://testray.liferay.com/reports/production/logs/test-1-11/1571289179228/test-portal-acceptance-pullrequest(master)/5863/functional-upgrade-tomcat90-mysql57-jdk8/2/0/jenkins-console.txt.gz

Will continue looking into the other results.

**Comment by vicnate5** [comment]
@shuyangzhou Service builder test failure also unique https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/326567/AXIS_VARIABLE=0,label_exp=!master/consoleText

Everything else looks good.

**Comment by vicnate5** [comment]
7.1 database used for upgrade test: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.1.10/data-archive/data-archive-portal-mysql.zip

**Comment by shuyangzhou** [comment]
@stsquared99 can you fix that upgrade failure? and do the global regen.
Fix it on top of this pull.

**Comment by shuyangzhou** [comment]
ci:reopen

**Pull request closed without merging**
