### PR TITLE
LPS-18897 Postpone logo update to avoid racing with BundleSiteInitial…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…izer's LayoutSet's lookAndFeel update.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. Did not see this issue in these CI results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137205

**Pull request closed without merging**
