### PR TITLE
Startup optimization 50 release renaming new

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@shuyangzhou Manaual testing passes now and there is no issue upgrading with the SAML dump I sent you. However there is a high rate of tests that failed prior to running in the ci results so I'm going to rerun them.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@shuyangzhou Actually I can't rerun relevant and upgrade due to merge conflicts. Can you rebase? Thanks.

**Comment by Kvale1733** [comment]
@shuyangzhou Actually it looks like there are compile issue for a lot of the modules integration tests as they fail locally too compileTestIntegrationJava. All the failing tests have errors like

'com.liferay.journal.upgrade.v1_1_6.test.UpgradeAssetDisplayPageEntryTest$1> is not abstract and does not override abstract method registerReleaseCreationUpgradeSteps(UpgradeStep...) in Registry
     [exec] 			new UpgradeStepRegistrator.Registry() {'

**Comment by shuyangzhou** [comment]
Ouch, this pull is completely conflicted with https://issues.liferay.com/browse/LPS-155604. I think we were working on the same thing, although using different solutions. @Kvale1733 can you re-verify the saml issue on master, since LPS-155604 has been merged already.

CC @vicnate5

**Comment by Kvale1733** [comment]
@shuyangzhou The SAML upgrade fails on master using the dump. Gist: https://gist.github.com/Kvale1733/8ba2edfe56a913a6f9e9f7a2a7b845fe

**Comment by shuyangzhou** [comment]
@vicnate5 please give this issue to upgrade team. With LPS-155604 change in master, my fix can no longer apply. So either they fix the saml upgrade issue, or we have to revert LPS-155604 to go with my solution.

**Pull request closed without merging**
