### PR TITLE
[Deprecation]LPS-106324

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian There's a CI network issue (see Slack/CI channel). Will re-trigger the tests when it's resolved.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
Results of ci:test:stable and relevant: failures are fluke or also failed on upstream or unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82619

**Pull request closed without merging**
