### PR TITLE
Lps 81869

### PR DESCRIPTION
**Pull request by mtambara**
Fix for lpkg-controller test

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:lpkg

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
ci:test:lpkg

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59803

**Pull request closed without merging**
