### PR TITLE
LPS-71203 Improve performance of AdvancedPermissionChecker.doGetRoleIds()

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@shuyangzhou, this one should be ready for review.  It passed everything but the SF test last week when I tested it on the CI.  I have two new tests for the changes that passed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47655

**Pull request closed without merging**
