### PR TITLE
LPS-107396 Alter column type: allow nullable condition and make it more robust

### PR DESCRIPTION
**Pull request by achaparro**
Hey @shuyangzhou,

I have added the unit tests for all databases to show what we are looking for with these changes.

Let me know if you have any questions.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/achaparro/liferay-portal/pull/456

**Pull request closed without merging**
