### PR TITLE
LPS-107396 Allow alter column type with nullable condition

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan this for me, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you take a look?

**Comment by kyle-miho** [comment]
No unique failures found as a result to these changes
https://testray.liferay.com/reports/production/logs/test-1-23/1580176814929/test-portal-acceptance-pullrequest(master)/5384/functional-tomcat90-mysql57-jdk8/79/0/jenkins-console.txt.gz
Tere were some unique functional failures, but due to cleanup issues from other tests + elastic search flakiness

**Comment by shuyangzhou** [comment]
@achaparro can you add tests to all XYZDBTest to cover the XYZDB.reword()'s "line.startsWith(ALTER_COLUMN_TYPE)" branch (in case there are multiple inner branches, make sure to cover them all.)? So that we can clearly see the intention of this change for each db. Thanks!

**Comment by achaparro** [comment]
Understood, I will do that @shuyangzhou 

Thanks.

**Pull request closed without merging**
