### PR TITLE
LPS-91709 Test added

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @shuyangzhou,

The unique errors detected seem to be unrelated to this pull request. Could you review it?

Thanks in advance

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70622

**Pull request closed without merging**
