### PR TITLE
[Bug Fix]LPS-129966

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@tinatian the failure looks like is caused by this pull.

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Will look into it.

**Comment by dantewang** [comment]
@shuyangzhou It's caused by https://github.com/shuyangzhou/liferay-portal/pull/10268/commits/56ba18fa1aa7c5bbceeb8e3a235df0e751cd3dfd, the `jobScriptPathString` is a file path, should not read it with `UnsyncStringReader`. I think we can just drop the last commit as explained below.

@tinatian The file on file system is not created here. The Util is provided with an inputstream of a zip file, so it creates the zip file on the file system and extracts it. Then other operations are performed on the extracted files -- they are already there. The unzip behavior should be addressed by the commerce ticket you created.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/10285

**Pull request closed without merging**
