### PR TITLE
LPS-117974 Avoid locking to prevent jsqlparser from failing to parse queries for SQLServer and DB2

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou removing and adding back the locking clauses for DB2 and SQLServer is pretty ugly.  SQLServer uses table hints ` select * from T with (updlock, rowlock) where tId = ?` and DB2 has [read only](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/sqlref/src/tpc/db2z_sql_readonlyclause.html) and [isolation clauses](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/db2/rbafzisocl.htm) and they show up in different parts `select * from T where tId = ? for read only with rs use and keep exclusive locks`.  I'm hoping I went a little overboard when making the mvccVersion changes and we can simply remove this usage - only other usages are for Counter and ViewCountEntry.

@slnn please run this against the message boards test case.  Mostly just wanting to make sure we don't see mvcc failures caused from removing the lock.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @Preston-Crary

Here are test results on MessageBorads, I did not see any errors on portal side.

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU | Portal CPU
-- | -- | -- | -- | -- | -- | --
BaseLine | 35ac9609 | 8329 | 192 | 263 | 18,21,24 | 94,92,93
PR | - | 9498 | 170 | 242 | 19,21,24 | 93,92,93

Regards
Lily

**Comment by slnn** [comment]
Hi @Preston-Crary

Here are test results on MessageBorads, I did not see any errors on portal side.

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU | Portal CPU
-- | -- | -- | -- | -- | -- | --
BaseLine | 35ac9609 | 8329 | 192 | 263 | 18,21,24 | 94,92,93
PR | - | 8498 | 170 | 242 | 19,21,24 | 93,92,93

Regards
Lily

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
