### PR TITLE
[Deprecation] LPS-106103

### PR DESCRIPTION
**Pull request by yuhai**
@shuyangzhou, the pr is based on https://github.com/shuyangzhou/liferay-portal/pull/8671#issuecomment-569844590, I add the last commit to solve the test errors.

cc @dantewang, @tinatian, @kyle-miho

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82705

**Pull request closed without merging**
