### PR TITLE
Startup optimization 246 service registry read write lock 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou Unique issue here is all these errors found in the osgi log file
https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2327212032&testrayRunId=2327212100&errors=OSGi+

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
ci:test:startup:norebase

**Pull request closed without merging**
