### PR TITLE
LPS-194820 Capture the default company id during activation time to a…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…void unreadable default company id during setup wizard webid swapping

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions were found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139964

**Pull request closed without merging**
