### PR TITLE
LPS-107804 Use original http servlet request populated with the current parameters to keep portlet-specific parameters

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
Hey @shuyangzhou,
I fixed the resource bundle issue and also one more - portlet navigation was broken because of lack of portlet parameters in the original servlet request. Could you please take a look if it makes sense?
Thanks!

/cc @ealonso

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The limited testing here are good, the previous failures are a CI issue.

This looks like it only applies to the modules/apps/layout/layout-type-controller/layout-type-controller-portlet, but this is enabled now? We might want to run more tests.

**Comment by shuyangzhou** [comment]
@vicnate5 Yeah, this is enabling it. Please run whichever tests you feel necessary, thanks!

**Comment by shuyangzhou** [comment]
@slnn we should run a performance regression for this too.

**Comment by vicnate5** [comment]
ci:test:wem-msb

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@david-gutierrez-mesa The WEM test suite for modern site building is missing needed configuration in `ci:properties` so it will not run. Let me know if you need help fixing this.

**Comment by slnn** [comment]
OK, got it,

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | e914e3 | 44987 | 261 | 77.2
PR | - | 45740 | 282 | 84.4

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | e914e3 | 56927 | 529 | 160
PR | - | 57668 | 494 | 151

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | e914e3 | 17860 | 39,3 | 86.7
PR | - | 17672 | 31.4 | 79.2

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | e914e3 | 14910 | 543 | 446
PR | - | 14619 | 577 | 486

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | e914e3 | 26037 | 180 | 251
PR | - | 26800 | 179 | 253

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | e914e3 | 15155 | 251 | 468
PR | - | 15343 | 259 | 471

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | e914e3 | 26808 | 425 | 175
PR | - | 26901 | 428 | 175

**Comment by vicnate5** [comment]
@kyle-miho I have meetings this morning, can you check the test results here for regressions?

**Comment by kyle-miho** [comment]
no regressions found in modules-integration or functional tests

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84141

**Pull request closed without merging**
