### PR TITLE
[Technical Support] LPS-77891 Apply logic of removing LOWER function to other databases instead of just MySQL

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket:
https://issues.liferay.com/browse/LPS-77891

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by rodrigopaulino** [comment]
Hello, @shuyangzhou. Looking at the CI's report, I don't believe that this failure has anything to do with the implemented fix.
If you need some more info, let me know. I'll be happy to help.
Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55760

**Pull request closed without merging**
