### PR TITLE
[TS] LPS-98526 S3 cache is not properly cleaned up within the configured time frame

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-98526

Hi @shuyangzhou ,

**Context**
Currently, the S3 cleanup process does not consider the case, where all sub-directories have been removed during the cleanup process, which qualifies the main folder to now be deleted as well.

This leads to an incomplete clean-up of files/folders, that are expected to be deleted.

From my understanding, if all sub-directories are removed and the main folder's modified date is less than the passed-in lastModified date, our current logic would agree that the main folder should be deleted.

**Proposed Fix**
The proposed fix is to make sure to check once more, whether the folder is qualified to be deleted, after the cleanup for the folder's sub-directories has been completed.

This logic has to be done during the same call, since deleting a sub-directory would cause the original folder's modified time to be updated.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@ericyanLr  can you create an unit test to assert the expected behavior of cleanUpCacheFiles()? The current logic is pretty messed up, once you give me the expected behavior assertion, I can rewrite it in a cleaner way.

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

Sure, I'll write the unit test, based on my interpretation of the current logic.

**Comment by shuyangzhou** [comment]
Please resend when you have the unit test ready.

**Comment by ericyanLr** [comment]
resent to: https://github.com/shuyangzhou/liferay-portal/pull/8067

**Pull request closed without merging**
