### PR TITLE
[TS] LPS-114146 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-114146

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9211

**Pull request closed without merging**
