### PR TITLE
Lps x freemarker async 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please keep an eye on this pull? I tested it locally and everything seems fine.

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou This PR is not showing any regressions. I triggered some additional tests on all app servers to look for anything else funny.

I would like to test the timeout behavior (error page?). Do you have a suggestion on how to do this?

**Comment by shuyangzhou** [comment]
@vicnate5 reduce the timeout time in that osgi config file, it is by ms, reduce it to a small number, it will time out.

**Comment by vicnate5** [comment]
Automation testing is done and passing. Talking to Tina about some of the timeout behavior I am seeing when testing locally.

**Pull request closed without merging**
