### PR TITLE
LPS-122025 Reduce the cache size

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @shuyangzhou and @slnn!!

We have tried to minimize the cache, returning all the segments of a user (this way we won't store a cache entry per segment/user, just for every user).

We have not found any way to avoid this query (without deleting some features).

This solution could improve if we create a custom query that returns only the segmentIds, so we won't return the full objects (but we will need to create a Custom Cache the same way that we did in https://github.com/shuyangzhou/liferay-portal/pull/9496).

Could you test this pull @slnn?
 
Thanks!

Continuation of https://github.com/shuyangzhou/liferay-portal/pull/9493

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@slnn any update on the test results?

**Comment by slnn** [comment]
Hi @shuyangzhou 

I did not get any remind from GitHub even though I was mentioned in the origin comment. I get to know this pull exists by your comment which mentioned me.

I will test this pull today and update the test results


Regards
Lily

**Comment by slnn** [comment]
Other pulls are running with our envs, I will start this pull this afternoon.

**Comment by slnn** [comment]
Hi @shuyangzhou @cgoncas 

Test results please see this doc:https://docs.google.com/spreadsheets/d/163CDSA1SIyLgdcKCBJvSHe5PhEDWt7iyHdu9p-FMsos/edit?usp=sharing

Test 12 means test ran only with this pull with 100 segments
Test 13 means test ran with this pull and  https://github.com/shuyangzhou/liferay-portal/pull/9496

From Test 13, the DB CPU usage decreased to 0, but the throughout is still bad.

Detailed test results and CPU tracing for Test 13 please see: https://drive.google.com/drive/folders/1nwkL4y4VQ5dWddnr28CVoFHVzkFc3Z2S?usp=sharing

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9520
No worries @slnn 

@cgoncas now you can see the db side issues are completely gone. Although the numbers are still awful. Read the profile and focusing on the portal side optimization, but leave the cache solution you did previously as the last step. Normally as you clean things up, it will change the way how you would want the cache or even eliminate it.

I made an obvious change here https://github.com/shuyangzhou/liferay-portal/pull/9521/commits/2beb53dc9805cc86bcb7cfca016368b2370c4d21 which shows as a bottleneck in the profile, @slnn please rerun the test on my pull. Thanks!

**Comment by shuyangzhou** [comment]
Actually @slnn you don't have to run the test, the diff is going to be small. I misread something, the heavy caller is from search, we won't be able to touch that.

**Pull request closed without merging**
