### PR TITLE
Lps 96252

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn please run a diff, thanks!

**Comment by slnn** [comment]
OK, will update test results when I got them.

**Comment by vicnate5** [comment]
@shuyangzhou Semver failure is real. But functional and integration test failures are not related to this change.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73916

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results:
 
DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL FIle
-- | -- | -- | -- | --
BaseLine | 225c659e | 24022 | 386 | 446
PR-7845 | - | 23824 | 375 | 429

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | 225c659e | 44825 | 280 | 83.2
PR-7845 | - | 44412 | 291 | 88.7

MB:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 225c659e | 15963 | 41.5 | 92.5
PR-7845 | - | 16210 | 50.2 | 102


Wiki:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 225c659e | 14226 | 429 | 603
PR-7845 | - | 14415 | 397 | 579

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 225c659e | 56368 | 679 | 213
PR-7845 | - | 56401 | 551 | 174


AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 225c659e | 26702 | 462 | 203
PR-7845 | - | 26990 | 421 | 189


Lily

**Pull request closed without merging**
