### PR TITLE
Startup optimization 58 configurator

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 do you think this needs more tests? This affects how those configurations.json files are handled.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in current results. I also ran all the related tests from `SystemSettings.testcase` locally against this change and they passed. Relevant ran broad backend testing for the components that are using configurations.json, but I cannot find any tests specifically for the configurations.json files parsing.

@kyle-miho can you look into if it is worth creating some tests specifically for `configurations.json` usage, I am surprised I couldn't find existing backend tests.

I do not think we need to hold this PR while we explore this.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122602

**Pull request closed without merging**
