### PR TITLE
[Bug Fix]LPS-97116

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please check if the failures about cluster real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Unrelated. It is a known issue we are currently working on: https://issues.liferay.com/browse/LRQA-51050

**Comment by tinatian** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76993

**Pull request closed without merging**
