### PR TITLE
Lps 69510

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Hey @shuyangzhou ,

Can you please review this PR as we need this for the Digital Enterprise Fix-pack.

Thank you in advance,
Zoltán

**Comment by ZoltanTakacs** [comment]
@mtambara can you fwd this one line code to Brian? We need this one for the next fix-pack and it's not a portal wide fix which requires a thorogh review. thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45364

Sorry for the delay.

**Comment by ZoltanTakacs** [comment]
Thank you very much

**Pull request closed without merging**
