### PR TITLE
LPS-103465 We cannot use PortletFileRepositoryUtil because of LPS-103720, so we create repository and folder by hand

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, I have added the last commit because of LPS-103720. During upgrade process we got an UndeployedExternalRepositoryException, because PortletRepositoryDefiner isn't define when we call PortletFileRepositoryUtil. We thought that the cause was the upgrade process, but when starting the portal, we get the exception too. 

So BChan wanted me to mention it to you. Please let me know what you think. Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by shuyangzhou** [comment]
@jkappler this is missing a lot of context, I don't really know what race condition you are talking about. But a wild guess could be in LayoutPageTemplateAdminWebUpgrade, it was waiting for 
```
	@Reference(
		target = "(repository.target.class.name=com.liferay.portal.repository.portletrepository.PortletRepository)"
	)
	private RepositoryFactory _repositoryFactory;
```

This is the instance before the RepositoryDefiner processing, try to switch to do:
```
	@Reference(
		target = "(class.name=com.liferay.portal.repository.portletrepository.PortletRepository)"
	)
	private RepositoryFactory _repositoryFactory;
```
which is after the processing.

if still not working, I will need more context, at least an error stack from you.

**Comment by jkappler** [comment]
Hi @shuyangzhou, sorry for the lack of context.  I already tried the first approach that you mentioned. But yes, PortletRepositoryDefiner is not present when calling PortletFileRepositoryUtil.

And thanks for the answer, will try the second approach

**Pull request closed without merging**
