### PR TITLE
LPS-156214 Tx wrapping for late PortalInstanceLifecycleListener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@shuyangzhou Regression here after upgrading a partitioned database.

Steps to Reproduce:
1. Import [partitioned database](https://github.com/liferay/liferay-qa-portal-legacy-ee/raw/master/7.4.1/data-archive/data-archive-portal-partition-mysql.zip) to MySQL (will import lportal, lpartition_39134, lpartition_41246)
1. Execute upgrade (no errors during upgrade)
1. Start portal

`ERROR [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:47] bundle com.liferay.portal.instance.lifecycle.impl:4.0.9 (274)[com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl(797)] : The addPortalInstanceLifecycleListener method has thrown an exception
org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [1]; actual row count: 0; expected: 1; statement executed: update DLFileEntryType set mvccVersion=?, modifiedDate=?, name=? where fileEntryTypeId=? and mvccVersion=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [1]; actual row count: 0; expected: 1; statement executed: update DLFileEntryType set mvccVersion=?, modifiedDate=?, name=? where fileEntryTypeId=? and mvccVersion=?`

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
@vicnate5 did not try it locally, but I have a guess on what the issue is about, just rerun on CI to test it. If still not working, I will look it deeper locally tomorrow.

**Comment by vicnate5** [comment]
Fix worked. re-running the full testing.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119355

**Pull request closed without merging**
