### PR TITLE
[TS] LPS-104696

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@dacousalr you need to 
1) Apply the patch
2) Generate the fake gradle cache
3) Apply the usages to the new patches.

Otherwise the test is still running against the current version, not testing your changes.
Please resend.

**Comment by dacousalr** [comment]
Resent in #8543

**Pull request closed without merging**
