### PR TITLE
[Log4j]LPS-127067

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found in the test results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99048

**Pull request closed without merging**
