### PR TITLE
LPS-104365 Simplify

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull's results, thanks!

**Comment by vicnate5** [comment]
@koor4356 can you review?

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@shuyangzhou, Look goods. No unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83356

**Pull request closed without merging**
