### PR TITLE
[Log4j]LPS-128599

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Resent at #9837 to fix modules-semantic-versioning failure: https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/381271/

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
