### PR TITLE
[Log Issue]LPS-132506 This property file is going to be read by log4j2 before po…

### PR DESCRIPTION
**Pull request by tinatian**
…rtal-log4j.xml, we need the root logger at WARN level to avoid unnecessary logging like "ClassLoaderAggregatePropertiesUtil"

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please add test to cover this?

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@tinatian Even without this change, the logging from `ClassLoaderAggregatePropertiesUtil` does not show in the Liferay log files (.log or .xml). Because of this I have no existing method to test this in automation. I don't think this issue is high enough risk to pursue a unique automation solution for it.

**Comment by tinatian** [comment]
@vicnate5 Do we have special configs for this on Ci?

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
