### PR TITLE
LPD-25633

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou this came from https://github.com/brianchandotcom/liferay-portal/pull/153267

Please review. Thx.

**Comment by shuyangzhou** [comment]
I rejected this solution from very beginning https://liferay.slack.com/archives/C01FP01V5L0/p1717623841323909 @matijapetanjek @4lejandrito how come you guys still continue on this path? Since the follow commits are all building on top this wrong single tx precondition, the whole change won't be acceptable.

**Comment by vicnate5** [comment]
CC @BryanEngler @gustavolimav

**Comment by shuyangzhou** [comment]
Going back to single tx model is not acceptable, we were having deadlock issue on HSQL, that's what we were dealing with in https://liferay.atlassian.net/browse/LPD-4332 and @4lejandrito check this group chat https://liferay.slack.com/archives/C0628K6K6Q1/p1697841326061349 you @brianchandotcom @ccorreagg and I had back in Oct 2023 , this was fixing the HeadlessBuilderResourceTest.

Also the performance issue you are facing here is not caused by the transaction mode, but data accessing pattern.

When dealing with large amount batch processing data, accessing data by their business logic relationship is very inefficient. business logic relationship is always cascaded, forcing you to go back and forward on tables for different entries, which results in tons of db queries, and very bad cache usages.

Regarding search indexing, it natively has a one to one mapping relationship with data accessing pattern. Every time you have a insert/update/delete db access, a search indexing request is needed. Although buffering all search indexing requests to send them out as a bulk request can reduce network traffic, but it is still very inefficient. Your focus should be on optimizing data accessing pattern first. The goal is to do bulk data process per table wise. With shifting to that data accessing pattern you are reducing the amount of db access, and it will automatically reduce the amount of search indexing request too, since they pretty much have an one to one mapping relationship.

Please rework on this to refactor the import process' data accessing pattern.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you set up a meeting with @4lejandrito they'll need your insight to move away from the data accessing problem.

**Comment by shuyangzhou** [comment]
Since I have not look into this problem yet, I can not say anything about specific optimization details.
I am aware of this ticket only because @marco-leo wanted to use this issue as an exercise for delegating performance issues to each team, and letting us doing the final acceptance check. It was quite unexpected to me for this pull came from you @brianchandotcom . It should be the opposite direction.

If we need to provide actionable insights, we need to spend time on profiling the issue first.

CC @vicnate5

**Comment by 4lejandrito** [comment]
Hey guys, to be honest we were desperate to solve the performance issue (coming from [a support ticket](https://liferay-support.zendesk.com/agent/tickets/110646)) and found that going back to 1TX per batch made sense as we were doing 1 elastic search query per TX and having 1TX per element. The [performance gains](https://liferay.atlassian.net/browse/LPD-25633?focusedCommentId=2703288) are huge ( ~50%). You can check [PTR-5108](https://liferay.atlassian.net/browse/PTR-5108) to learn more about our though process.

I had no time to check if the issue fixed by [the TX code](https://github.com/brianchandotcom/liferay-portal/pull/142542/commits/498411dd0d8ceea18b744d704d90bfdffc1b48ef) is still reproducible or not, and that is my mistake. In any case, if I remember correctly it only affected HSQL which is not really a production DB.

### Regarding the data access issue... 

REST Builder is generating APIs integrated with the batch framework by default and delegating the data access to their implementations. From batch we have no control whatsoever on how the data is handled. We just reuse the same code from the `POST`, `PUT` & `PATCH` endpoints.

The logic in the REST and Service layers is huge and creating another data path could introduce tons of inconsistencies on how batch works with respect to the REST layer, which I believe was the whole point of reusing the REST layer for batch. Ideally we should find a solution that allows us to keep reusing the same code for the REST layer and for batch.

@marco-leo, as you know we are also in the middle of rethinking staging to be built on top of batch and having to go back to rethink batch would definitely delay this initiative.

**Comment by vicnate5** [comment]
We believe we can increase the performance even more significantly without returning to single transaction. @shuyangzhou will be reviewing the code in detail.

**Pull request closed without merging**
