### PR TITLE
[ArgumentsResolver]LPS-136445

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10227

**Comment by tinatian** [comment]
Hi @vicnate5,
Is the unique funtional failure real? 

Tina.

**Comment by vicnate5** [comment]
@koor4356 please check

**Comment by koor4356** [comment]
This PR is already closed. Thanks!

**Comment by tinatian** [comment]
@koor4356 This pull has same content expect the source formatter change with https://github.com/shuyangzhou/liferay-portal/pull/10227. But the other pull did not finish the ci test, could you please check the failures in this pull? I would like to know if there any unique failure caused by the changed logic. No need to check SF failure as it is a known issue.

Thanks.
Tina.

**Comment by koor4356** [comment]
Okay, I am currently checking this PR. Thanks @tinatian

**Comment by koor4356** [comment]
@tinatian @vicnate5, No unique failures. 
So this looks good except that most of the modules integration tests failed prior to running the test.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Pull request closed without merging**
