### PR TITLE
Startup optimization 198 x stream configurator registry util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:export-import

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by kyle-miho** [comment]
yea i got this one

**Comment by kyle-miho** [comment]
@shuyangzhou Regressions found:
Steps: 
1) Create a New Site
Result: 
`2023-03-29 19:56:46.310 ERROR [http-nio-8080-exec-1][PortletServlet:118] Unable to process portlet com_liferay_site_admin_web_portlet_SiteAdminPortlet: java.lang.Exception: java.lang.ExceptionInInitializerError
javax.portlet.PortletException: java.lang.Exception: java.lang.ExceptionInInitializerError
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65)`

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Investigating results

**Comment by kyle-miho** [comment]
@shuyangzhou regression for semVar, no other unique failures found, should be good to forward after we bump the version
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/xstream/xstream-configurator-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.xstream.configurator                   MAJOR      1.2.3      1.2.3      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.xstream.configurator.XStreamConfiguratorRegistryUtil
     [exec]     		-   method     activate(org.osgi.framework.BundleContext)
     [exec]     			-   access     protected
     [exec]     			-   annotated  org.osgi.service.component.annotations.Activate
     [exec]     			-   return     void
     [exec]     		-   method     deactivate()
     [exec]     			-   access     protected
     [exec]     			-   annotated  org.osgi.service.component.annotations.Deactivate
     [exec]     			-   return     void
     [exec]     		>   method     getXStreamConfigurators()
     [exec]     			+   return     java.util.List
     [exec]     			-   return     java.util.Set
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132674

**Pull request closed without merging**
