### PR TITLE
LPS-92017 DDMStructure Deep Copy

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou ,

This pass ci test on this pull https://github.com/tinatian/liferay-portal/pull/1265, but I did some source formatting on it.

Hi @marcellustavares,
This performance issue is caused by your change here : https://issues.liferay.com/browse/LPS-52144, we found it when tuning liferay.com and according to our local test, this fix doubled the performance at least, so we need this to be merged as soon as possible.

It has passed ci test according to @vicnate5 comment on this pull https://github.com/tinatian/liferay-portal/pull/1265. I tried to keep the logic same as before, but still changed some of them, to play safe before releasing, could you please check if I break anything?

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@alexcandidos Can you share this with the current DDM team?

**Comment by alexcandidos** [comment]
Yes @vicnate5 , the team will take a look!

**Comment by linolaoj** [comment]
Hi @tinatian ,
I found only one issue with this pr.

Steps to reproduce:
1. go to _Content & Data_ -> _Web Content_  -> _Structures_;
2. add a new structure called _str 1_ with a text field labeled as _text 1_;
3. add a new structure called _str 2_ with a text field labeled as _text 2_, and choose _str 1_ as the parent structure;
4. go to _Tamplates_ tab and try to add a new template for _str 2_.

Expected result:
Template is added

Actual result:
Exception on logs and message on screen "New Template for Structure: str 2 is temporarily unavailable."

Please let me know if you need any more details.
Thanks!

**Comment by tinatian** [comment]
Thanks @linolaoj! I fixed in this pull https://github.com/shuyangzhou/liferay-portal/pull/7475, could you please verify that pull also?

Thanks.
Tina.

**Pull request closed without merging**
