### PR TITLE
LPS-84599 Adding a timeout for the counter

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up of https://github.com/brianchandotcom/liferay-portal/pull/61609#issuecomment-407795150.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
