### PR TITLE
[FinderCache]LPS-121770

### PR DESCRIPTION
**Pull request by tinatian**
This is a resend of https://github.com/shuyangzhou/liferay-portal/pull/9480

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
No unique failures on previous test runs on https://github.com/shuyangzhou/liferay-portal/pull/9480

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
@vicnate5 Could you please take a look at the forwarding failures?

Thanks
Tina.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
