### PR TITLE
LPS-86709 Develop the bean portlet Spring extension (REBASE#11)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou @koor4356 @vicnate5

This PR moves us from the Geronimo version of the JAX-RS API to the Apache Aries version. It's something to try and to test until we get confirmation from @rotty3000 as to whether or not this is the best way to go.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by rotty3000** [comment]
This PR replaces https://github.com/shuyangzhou/liferay-portal/pull/8712

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
