### PR TITLE
Startup optimization 175 persistent portal instance lifecycle listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Large amount of tests ran with virtual instances.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130909

**Pull request closed without merging**
