### PR TITLE
Startup optimization 245 concurrent spring bean osgi service registration

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@shuyangzhou Regression on this PR (also affecting the additional PRs). I confirmed this is not reproducible on master upstream.

Steps to Reproduce:
1. Add a new site and select the "Minium" type

Result:
```
ERROR [http-nio-8080-exec-4][MiniumSiteInitializer:274] null
com.liferay.dynamic.data.mapping.validator.DDMFormValidationException$MustSetFieldsForForm: At least one field must be set
	at com.liferay.dynamic.data.mapping.validator.internal.DDMFormValidatorImpl.validate(DDMFormValidatorImpl.java:90) ~[?:?]
	at com.liferay.dynamic.data.mapping.service.impl.DDMStructureLocalServiceImpl._validate(DDMStructureLocalServiceImpl.java:2058) ~[?:?]
	at com.liferay.dynamic.data.mapping.service.impl.DDMStructureLocalServiceImpl._validate(DDMStructureLocalServiceImpl.java:2117) ~[?:?]
	at com.liferay.dynamic.data.mapping.service.impl.DDMStructureLocalServiceImpl._validate(DDMStructureLocalServiceImpl.java:2104) ~[?:?]
	at com.liferay.dynamic.data.mapping.service.impl.DDMStructureLocalServiceImpl.addStructure(DDMStructureLocalServiceImpl.java:203) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1181.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:64) ~[portal-kernel.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy1230.addStructure(Unknown Source) ~[?:?]
	at com.liferay.commerce.product.internal.importer.CPFileImporterImpl._fetchOrAddDDMStructure(CPFileImporterImpl.java:549) ~[?:?]
	at com.liferay.commerce.product.internal.importer.CPFileImporterImpl._createJournalArticle(CPFileImporterImpl.java:322) ~[?:?]
	at com.liferay.commerce.product.internal.importer.CPFileImporterImpl.createJournalArticles(CPFileImporterImpl.java:140) ~[?:?]
	at com.liferay.commerce.theme.minium.site.initializer.internal.MiniumSiteInitializer._importJournalArticles(MiniumSiteInitializer.java:777) ~[?:?]
	at com.liferay.commerce.theme.minium.site.initializer.internal.MiniumSiteInitializer.initialize(MiniumSiteInitializer.java:245) ~[?:?]
	at com.liferay.site.admin.web.internal.portlet.action.AddGroupMVCActionCommand._updateGroup(AddGroupMVCActionCommand.java:510) ~[bundleFile:?]
	at com.liferay.site.admin.web.internal.portlet.action.AddGroupMVCActionCommand.access$100(AddGroupMVCActionCommand.java:93) ~[bundleFile:?]
	at com.liferay.site.admin.web.internal.portlet.action.AddGroupMVCActionCommand$GroupCallable.call(AddGroupMVCActionCommand.java:597) ~[bundleFile:?]
	at com.liferay.site.admin.web.internal.portlet.action.AddGroupMVCActionCommand$GroupCallable.call(AddGroupMVCActionCommand.java:592) ~[bundleFile:?]
	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:36) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28) ~[portal-kernel.jar:?]
	at com.liferay.site.admin.web.internal.portlet.action.AddGroupMVCActionCommand.doProcessAction(AddGroupMVCActionCommand.java:105) ~[bundleFile:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:57) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:83) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:256) ~[portal-kernel.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:114) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
```
CI Log https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/9483/functional-tomcat90-mysql57-chrome100-jdk8/0/7/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135685

**Pull request closed without merging**
