### PR TITLE
LPS-107626 - headless-batch-engine-impl - Propgate path prameters to batch execution

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@kyle-miho

**Comment by kyle-miho** [comment]
waiting on testray importer to import results, integration tests look good, need to confirm if functional failures are unique

**Comment by shuyangzhou** [comment]
@kyle-miho any updates?

**Comment by kyle-miho** [comment]
nothing unique found

**Comment by kyle-miho** [comment]
pull should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84193

**Pull request closed without merging**
