### PR TITLE
LPS-X Convert unnecessary ConcurrentReferenceKeyHashMap.mapKey() to C…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…oncurrentReferenceKeyHashMap.mapKeyForQuery() to reduce FinalizeManager.register()

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139770

**Pull request closed without merging**
