### PR TITLE
LPS-56115 fix SampleSQLBuilder classpath

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Why did you pull up "<path refid="project.classpath" />" to be the first one? Does the order matter?

**Comment by dantewang** [comment]
The order matters, or there will be an error complaining about log4j.dtd missing. With `com.liferay.wiki.*` we includes some wiki engine jars, which requires that dtd.

Tina's fix that we were waiting for fixes the bug that prevents `project.classpath` from being moved to the first one..

**Comment by shuyangzhou** [comment]
Hmm, how do I see the missing log4j.dtd error? I moved the project.classpath back to the last one, simply run build-sample-sql, I don't see it.

However, on top of exactly your pull, the output is like this:

```
build-sample-sql:
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/system.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-service/test-classes/unit/system-ext.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/com/liferay/portal/tools/dependencies/portal-tools.properties
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
```
After moving project.classpath to the end, the output is like this:
```
build-sample-sql:
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/system.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-service/test-classes/unit/system-ext.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
     [java] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/com/liferay/portal/tools/dependencies/portal-tools.properties
     [java] 15:24:31,747 INFO  [ClassLoaderComponentConfiguration:?] Properties for service loaded from [jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties]
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
     [java] 15:24:31,821 INFO  [ClassLoaderComponentConfiguration:?] Properties for service loaded from [jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties]
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
     [java] 15:24:32,149 INFO  [ClassLoaderComponentConfiguration:?] Properties for service loaded from [jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties]
     [java] Loading jar:file:/home/trunks/git/liferay-portal/tools/sdk/dist/com.liferay.wiki.service-1.0.0.jar!/service.properties
```

Not sure how does this affect the output results.

Please recheck, if it still breaks for you, let me know how to reproduce it.

**Comment by dantewang** [comment]
hmm I tried with project.classpath at the end and it worked. Same output as yours, and same content generated. Will resend.

**Pull request closed without merging**
