### PR TITLE
LPS-77306 Portlet 3.0: Remove deprecated methods and classes in package com.liferay.portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince When you can, please take a look and let Shuyang know if it's OK for review.

**Comment by jpince** [comment]
@ngriffin7a sorry, there's a lot of noise in CI rn, will need to retest on Monday once some of the fixes have been merged

**Comment by jpince** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince Thanks for pointing that out. I fixed some bnd.bnd files and I'll retest now.

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince Please advise -- not sure what to make of the "1 Job Failed" error that happened pretty fast on the retest, thanks.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@yichenroy @michaelhashimoto @kenjiheigel
```
[beanshell] java.lang.RuntimeException: Unable to create local branch cache-shuyangzhou-365fa7c8a3efd868af774446c3aec9d58b37fcb9-ngriffin7a-08e981d6989be5fe2855a30c151cf2534b93ea8a at 08e981d6989be5fe2855a30c151cf2534b93ea8a
[beanshell] fatal: Not a valid branch point: '08e981d6989be5fe2855a30c151cf2534b93ea8a'.
```

**Comment by yichenroy** [comment]
@jpince @ngriffin7a 
Hello, it looks like you may have force-pushed a commit while this pull-request was in a closed state. You may have to re-send a new pull-request and re-test on there. The pull has to remain open if you wish to force-push anything onto your branch and have it be reflected in the pull.

The latest SHA in this pull request does not match the latest SHA on your branch:

In this pull-request:
https://github.com/shuyangzhou/liferay-portal/pull/5931/commits/08e981d6989be5fe2855a30c151cf2534b93ea8a

In your branch:
https://github.com/ngriffin7a/liferay-portal/commit/345e8454ec097bf60616729a2f05ca6db3699d7c

**Comment by ngriffin7a** [comment]
@yichenroy OK thanks for letting me know. I'll send s separate PR.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/5940

**Pull request closed without merging**
