### PR TITLE
LPS-84115 BundlePortletApp.isWarFile() and BundlePortletApp.setWarFile(boolean) must not decorate/wrap the underlying portlet app

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou Yes, the failures look real, which very much surprises me. I will investigate and send you another PR if necessary.

**Comment by shuyangzhou** [comment]
Ok, @ngriffin7a I am closing this for now.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6577

**Pull request closed without merging**
