### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I did not include the clean up of current embedded impl into this pull, only disabled EmbeddedElasticsearchConnection, search team will take care of the clean up once sidecar is in.

If you think this pull is too big, you can ignore the commit with prefix portal-search-elasticsearch7-impl: clustering.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder
2.Random java.lang.InterruptedException on shutdown (https://github.com/shuyangzhou/liferay-portal/pull/8794)

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please scan test result and do manual tests.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 I disabled remote search for rolling restart test, will rerun clustering test.

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @slnn ,
Please run a diff on startup with this pull, we would like to know if sidecar is going to bring any regression on startup performance.

cc @dantewang

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
@tinatian rebase failure, please resend.

**Comment by tinatian** [comment]
Rebase and resend here : https://github.com/shuyangzhou/liferay-portal/pull/8858.

**Pull request closed without merging**
