### PR TITLE
Startup optimization 214 batch engine task item delegate

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression here with the import/export batch functionality.

Steps to Reproduce Export:
1. Go to Control Panel > Applications > Import/Export Center
2. Add new "Export File"
3. Select Entity Type: "Account (v1_0 - Liferay Headless Admin User)"
4. Click "Export"

Result: Export fails:
https://gist.githubusercontent.com/vicnate5/dca1432da7d68a14cac3f77a5fe580f4/raw/1552f61f95a7cc80a69f9e176ffdabdc78733b9c/gistfile1.txt

Steps to Reproduce import:
1. Go to Control Panel > Applications > Import/Export Center
2. Add new "Import File"
3. Choose file and upload [csv_account_import.csv](https://raw.githubusercontent.com/liferay/liferay-portal/b7c813ccdb35b07256a6a7108ff3abdc64084f1d/modules/apps/batch-planner/batch-planner-test/src/testFunctional/tests/dependencies/csv_account_import.csv)
4. Configure with Entity Type: "Account (v1_0 - Liferay Headless Admin User)" and map the fields as in the image
Configuration
5. Click "Next" button

Result: Import fails:
https://gist.githubusercontent.com/vicnate5/5b5995bc00ce6cf2a117d5b94370c97a/raw/f37a2e5f2c1835d15b1cf2973f39bb54557e0d36/gistfile1.txt

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133395

**Pull request closed without merging**
