### PR TITLE
LPS-80724 Portlet 3.0: Implement Javadoc requirements for PortletMode.UNDEFINED and WindowState.UNDEFINED

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince: The POSHI console for these failures show a "Caused by ModelListenerException" in stack traces. Since model listeners are at the business-layer (or perhaps the persistence-layer) and this PR deals with the UI, I tend to think that these POSHI failures are unrelated. Do you agree? If so, please let us know so that @shuyangzhou can review. Thanks.

**Comment by jpince** [comment]
@ngriffin7a that's correct, it's a different issue. @shuyangzhou please review

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58940

**Pull request closed without merging**
