### PR TITLE
Lps 73947 Scheduler jobs are lost if master token released transition fails

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I have not tested this pull on CI, please wait for CI result.

cc @marianoalvarosaiz @achaparro

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian, I only had time to take a quick look to this code, but what will happen if _initMemoryClusteredJobs_ fails during start? I mean:

1. Node1 is master.
2. Node2 starts and fails to retrieve jobs from master.
3. During node2 retries node1 is stopped.
4. Node2 is raised as master, but without __memoryClusteredJobs_ to schedule.

With old code if during start synchronization was impossible node failed to start.

**Comment by tinatian** [comment]
Hi @marianoalvarosaiz,
In that case, you are having no node running in cluster (Node1 stopped, Node2 is starting), at this moment, production environment is already crashed, thus it won't hurt if you do a restart.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/51198

**Pull request closed without merging**
