### PR TITLE
Lps 141790

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, this is a high risk change, affecting all spring extender modules, like those commerce service modules. And it has impact on upgrade too. Thanks!

**Comment by vicnate5** [comment]
Finishing up release testing this morning, will check this in the afternoon.

**Comment by vicnate5** [comment]
@kyle-miho could you do analysis on this?

**Comment by kyle-miho** [comment]
ci:test
running more tests since this is a high risk change, no unique failures seen so far

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
@shuyangzhou this pr should be good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110247

**Pull request closed without merging**
