### PR TITLE
Startup optimization 290 initial upgrade step

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:stable:norebase

**Comment by vicnate5** [comment]
@shuyangzhou This is looking good, just need to confirm the startup error on the release bundle here is a fluke by re-running stable. I didn't get the full upgrade results into testray, but I can tell failure rate is really low, so unlikely a regression.

**Comment by shuyangzhou** [comment]
Ok, thanks @vicnate5 ! I will wait for your confirm, this pull is a "redo" for https://github.com/shuyangzhou/liferay-portal/pull/11186, it is serving the same goal but in a much less intrusive way. Hope it is clean, then we can finally get over this change.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139900

**Pull request closed without merging**
