### PR TITLE
[Deprecation]LPS-104613

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @kyle-miho,
Please help us scan the test result.

Thanks.
Tina.

**Comment by dantewang** [comment]
@ChiZelin Please rebase and resend to Shuyang.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
