### PR TITLE
Lps 169889

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
`search` test suite results look good. All failures are unrelated to this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127058

Thanks @xbrianlee !

**Pull request closed without merging**
