### PR TITLE
LPS-108438 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@mtambara please take this over.

**Comment by mtambara** [comment]
@marianoalvarosaiz I'm working on a fix that'll only touch bundle installation

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8851

**Pull request closed without merging**
