### PR TITLE
LPS-X Tweak ES RestClient HttpAsyncClient threadpool.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@111Anna please check startup performance difference.

@slnn this may have an impact to search runtime too. Please pick a search heavy test case to run a compare.
If it causes noticeable dropping try to bring up this number https://github.com/shuyangzhou/liferay-portal/pull/10911/commits/caec9c39956656128a199b10caaf9b4d8f2405c7#diff-9fd62615e2fede041830d6d74e5770477584e771a5e1fef3012095094bd112faR219 it was default to CPU count, basically if you bring it up back to match the cpu number ```Runtime.getRuntime().availableProcessors()```, this pull should not cause any runtime performance regression, but the goal is try to find the smallest number that is not causing noticeable regression.

**Comment by slnn** [comment]
> @111Anna please check startup performance difference.
> 
> @slnn this may have an impact to search runtime too. Please pick a search heavy test case to run a compare. If it causes noticeable dropping try to bring up this number [caec9c3#diff-9fd62615e2fede041830d6d74e5770477584e771a5e1fef3012095094bd112faR219](https://github.com/shuyangzhou/liferay-portal/commit/caec9c39956656128a199b10caaf9b4d8f2405c7#diff-9fd62615e2fede041830d6d74e5770477584e771a5e1fef3012095094bd112faR219) it was default to CPU count, basically if you bring it up back to match the cpu number `Runtime.getRuntime().availableProcessors()`, this pull should not cause any runtime performance regression, but the goal is try to find the smallest number that is not causing noticeable regression.

OK, got it

**Comment by 111Anna** [comment]
Hi @shuyangzhou, I tested the PR on DXP-Profile today, before that I ran test on CE.
here is the test result :

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| f7d0be5| 28211 |- |6158.3|-| 1978 | 114 | 708 | 1157 |
Baseline + PR-10911| - | 28753 |-1.8%| 6562.3|-6.1%| 1982 | 102 | 714 | 1156 |

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
@111Anna @slnn please rerun your tests, this is a different solution, thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are the test results on AssetPublisher with the new changes, huge performance regression appeared.

main3:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count change (%) | Portal Server CPU (%) | ES Server CPU (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 923f924e | 20414 | 373 | 172 | - | 95,95,95 | 12,12,12
PR | - | 8566 | 1150 | 521 | -58.03860096 | 23,25,28 | 6,7,7

main2:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count change (%) | Portal Server CPU (%) | ES Server CPU (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 923f924e | 30507 | 426 | 178 | - | 87,87,87 | 10,10,10
PR | - | 13764 | 1180 | 468 | -54.88248599 | 33,35,34 | 4,4,4


CPU Tracings uploaded in https://drive.google.com/drive/folders/1r48FBCYw9ZvMPXNk166YNJ30n7onWKAz?usp=share_link

Regards
Lily

**Comment by shuyangzhou** [comment]
@slnn can you check the portal and es server network usage difference before / after the change? it might be the content compression change causing it.

**Comment by shuyangzhou** [comment]
@slnn I think I know what is going on. Please rerun the test. There are 2 commits in the pull. Run the baseline, run a data point with just the first commit, run a data point with both commits.

If the result with just the first commit is already worse than the baseline, no need to run the other data point.

If the result with just the first commit is same or better than baseline, try to set 
https://github.com/shuyangzhou/liferay-portal/pull/10911/commits/a3a5eeef1d48e939188e810c8b2cd07afe0e01fd#diff-9fd62615e2fede041830d6d74e5770477584e771a5e1fef3012095094bd112faR229
https://github.com/shuyangzhou/liferay-portal/pull/10911/commits/a3a5eeef1d48e939188e810c8b2cd07afe0e01fd#diff-9fd62615e2fede041830d6d74e5770477584e771a5e1fef3012095094bd112faR231
to match your tomcat thread pool size. To see if it is better, if so we will make these numbers configurable.

Use the best version of the first commit result, add in the second commit, rerun the test. This commit is disabling content compression, which is basically asking ES not to gzip the json response. Since portal and ES are in the same local network, the expectation is, network traffic between portal and ES is increasing, but saving both side's cpu time.

**Comment by shuyangzhou** [comment]
@slnn @111Anna please get me an update on this, thanks!

**Comment by 111Anna** [comment]
Hi @shuyangzhou, I rerun the test on test machine. Lily is on vacation, she will come back next week
Here are  test results:

DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 8fe911ae| 27870.6 |- |4709|-| 1984 | 114 | 720| 1132 |
Baseline + PR-10911| - | 27583 |1.0%| 4749.6|-0.85%| 1984 | 101 |560 |1091 |  

CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 8fe911ae| 24663.6 |- |3877.3|-| 1827 | 101 | 506| 1001 |
Baseline + PR-10911| - | 24755.6 |-0.4%| 3763.3|3.0%| 1828 | 87 | 500 | 1001 |

**Comment by slnn** [comment]
> @slnn can you check the portal and es server network usage difference before / after the change? it might be the content compression change causing it.

Hi @shuyangzhou 

From the ifstat log of portal and es server, both network usages will be decreased after the change.

**Pull request closed without merging**
