### PR TITLE
[Bug Fix]LPS-96877

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou, 

@lipusz Could you please verify my fix?

@slnn please run a diff on Login and webcontent once @lipusz confirmed that it works and no ci failures caused by this fix.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74542

**Comment by slnn** [comment]
Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | c0c1343 | 15897 | 207 | 47.2
PR-7933 | - | 15738 | 200 | 45.5


Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | c0c1343 | 20455 | 340 | 130
PR-7933 | - | 20113 | 325 | 125


Regards
Lily

**Comment by lipusz** [comment]
Thank you, Lily! @slnn :+1:

**Pull request closed without merging**
