### PR TITLE
Lps 77989

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mtambara see https://issues.liferay.com/browse/LPS-77177 I have done that already. Please check whether we have any difference. And ping @tomwang2011 for the status. Brian wanted it to be backport it first before he can merge it. @tomwang2011 knows where is the backport pull, ping Brian to move this forward.

**Comment by tomwang2011** [comment]
@shuyangzhou That pull had a merge conflict, I have resent it at: https://github.com/brianchandotcom/liferay-portal-ee/pull/19395

**Comment by shuyangzhou** [comment]
@mtambara my changes are in master now, please compare to see the difference, if anything is still needed, please send a follow up.
And for LPS-77989 you can modify its description for a different module.

**Comment by mtambara** [comment]
@shuyangzhou Doesn't look like there are any major differences

**Pull request closed without merging**
