### PR TITLE
Remove count by finder path unique finder

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:47205144

**Comment by vicnate5** [comment]
@shuyangzhou These 2 look unique
https://testray.liferay.com/#/project/35392/routines/45357/build/47205144/case-result/47205552
https://testray.liferay.com/#/project/35392/routines/45357/build/47205144/case-result/47215920

**Comment by shuyangzhou** [comment]
ci:test:relevant

I can not reproduce those 2 failures locally. Rerunning to confirm.

**Comment by shuyangzhou** [comment]
ci:report:48479229

**Comment by vicnate5** [comment]
only unique on this run
https://testray.liferay.com/#/project/35392/routines/45357/build/48479229/case-result/48491115

**Comment by shuyangzhou** [comment]
ci:test:relevant

I can not reproduce this one either.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:49908514

**Comment by vicnate5** [comment]
@shuyangzhou no unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155535

**Pull request closed without merging**
