### PR TITLE
Startup optimization 325 persisted model local service registry

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No regressions found the ci tests.

Also checked service builder on backwards compatibility. No issue found on 7.3.x and 7.2.x.

On 7.1.x and 7.0.x, below error occurred, testing with journal-service as example:
7.1.x:
```
> Task :apps:journal:journal-api:baseline
  PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.journal.service                        CHANGED    2.9.0      2.9.0      2.9.1      VERSION INCREASE REQUIRED
	~   interface  com.liferay.journal.service.JournalArticleLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalArticle'
	~   interface  com.liferay.journal.service.JournalArticleResourceLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalArticleResource'
	~   interface  com.liferay.journal.service.JournalContentSearchLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalContentSearch'
	~   interface  com.liferay.journal.service.JournalFeedLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalFeed'
	~   interface  com.liferay.journal.service.JournalFolderLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalFolder'
[Baseline Report] Mode: diff (persisted)
Semantic versioning is incorrect while checking /home/liferay/summer/git/portal/7.1.x/tools/sdk/dist/com.liferay.journal.api-3.16.2.jar against /home/liferay/summer/git/portal/7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.journal.api/3.16.1/6ff14b591143e08b5a1d059f702cadb2285d1dfa/com.liferay.journal.api-3.16.1.jar
```
7.0.x:
```
> Task :apps:web-experience:journal:journal-api:baseline
  PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.journal.service                        CHANGED    1.5.0      1.5.0      1.5.1      VERSION INCREASE REQUIRED
	~   interface  com.liferay.journal.service.JournalArticleImageLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalArticleImage'
	~   interface  com.liferay.journal.service.JournalArticleLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalArticle'
	~   interface  com.liferay.journal.service.JournalArticleResourceLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalArticleResource'
	~   interface  com.liferay.journal.service.JournalContentSearchLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalContentSearch'
	~   interface  com.liferay.journal.service.JournalFeedLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalFeed'
	~   interface  com.liferay.journal.service.JournalFolderLocalService
		+   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
			+   property   property.0='model.class.name=com.liferay.journal.model.JournalFolder'
[Baseline Report] Mode: diff (persisted)
Semantic versioning is incorrect while checking /home/liferay/summer/git/portal/7.0.x/tools/sdk/dist/com.liferay.journal.api-2.16.1.jar against /home/liferay/summer/git/portal/7.0.x/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.journal.api/2.16.0/ff473f62db36c07222198ed3491b536ab74a9e6/com.liferay.journal.api-2.16.0.jar
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142490
7.1.x and 7.0.x just need to rerun baseline once SB is released, not a real issue.

**Pull request closed without merging**
