### PR TITLE
LPS-86709 Develop the bean portlet Spring extension (REBASE#10)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou Fixed split package.
```
Error Message java.lang.AssertionError: Detected split packages {name=javax.ws.rs.container, version=2.1} in org.apache.aries.javax.jax.rs-api_1.0.4 [51] and org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec_1.1.0 [237] at 
```

Also, I upgraded from Spring Framework 5.1.5 to 5.2.2 since that is the current version bundled with the core.

/cc @koor4356 @vicnate5

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@koor4356 and/or @vicnate5 Please run whatever tests you feel are necessary.

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@koor4356 Please review the results here, they don't look good...

**Comment by koor4356** [comment]
@ngriffin7a @shuyangzhou @vicnate5 
There is an unresolved requirement(s) error on startup. Can you take a look, please?

https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/297840/AXIS_VARIABLE=0,label_exp=!master/consoleFull

` 10-Jan-2020 01:18:46.255 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [com.liferay.portal.spring.context.PortalContextLoaderListener]
     [exec]  java.lang.RuntimeException: org.osgi.framework.BundleException: Could not resolve module: javax.mvc-api [41]
     [exec]   Unresolved requirement: Import-Package: javax.ws.rs; version="[2.1.0,3.0.0)"
     [exec]     -> Export-Package: javax.ws.rs; bundle-symbolic-name="org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec"; bundle-version="1.1.0"; version="2.1.0"; uses:="javax.ws.rs.core"
     [exec]        org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec [63]
     [exec]          Unresolved requirement: Require-Capability: osgi.serviceloader; filter:="(osgi.serviceloader=javax.ws.rs.client.ClientBuilder)"; cardinality:="multiple"
     [exec]   Unresolved requirement: Import-Package: javax.ws.rs.container; version="[2.1.0,3.0.0)"
     [exec]     -> Export-Package: javax.ws.rs.container; bundle-symbolic-name="org.apache.geronimo.specs.geronimo-jaxrs_2.1_spec"; bundle-version="1.1.0"; version="2.1.0"; uses:="javax.ws.rs.core"`

Thanks!

**Comment by ngriffin7a** [comment]
@ngriffin7a @shuyangzhou @vicnate5 OK I'll ask @rotty3000 about it

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8711

**Pull request closed without merging**
