### PR TITLE
LPS-139169 If the classloader is unable to load the class, log a WARN message and call the superclass.getClassFromHint method, similar to how we do if the classloader couldn't be found.

### PR DESCRIPTION
**Pull request by rafaprax**
https://issues.liferay.com/browse/LPS-139169

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@rafaprax @mbowerman please add a test for this.

**Comment by mbowerman** [comment]
@rafaprax @shuyangzhou Re-sent at https://github.com/shuyangzhou/liferay-portal/pull/10293

**Pull request closed without merging**
