### PR TITLE
[Log4j]LPS-127067

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please check if any of the unique failure real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Please the test results for regressions.

**Comment by zhangyan0701** [comment]
No unique failures. These failures are happening in other PR or upstream as well and some are flaky.

**Comment by tinatian** [comment]
Will rename variables and resend.

Tina.

**Pull request closed without merging**
