### PR TITLE
LPS-79002 Get the requestURI from the original request, rather than t…

### PR DESCRIPTION
**Pull request by SamZiemer**
When accessing a localized url that is not the default language of the user when a virtual host is set /web is re added to the url incorrectly. To resolve this we can use the request URI from the original request instead of the wrapped request.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by SamZiemer** [comment]
any update on this?

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@SamZiemer have you tried to just use PortalImpl.getOriginalServletRequest()? Is any of those PersistentHttpServletRequestWrapper causing a trouble for you?

**Comment by SamZiemer** [comment]
Hi @shuyangzhou Sorry for the delay in responding to you, I was out of the office. I tried using PortalImpl.getOriginalServeletRequest() initially, but that was causing some weird behavior with displaying the full url, rather than the friendly url we need when the page displays which url we were redirected to. I have not noticed any trouble from the PersistentHttpServletRequestWrappers.

**Comment by shuyangzhou** [comment]
@SamZiemer the only real difference between your way and PortalImpl.getOriginalServletRequest() is the PersistentHttpServletRequestWrappers. So what you said is self conflicting. Please switch to use PortalImpl.getOriginalServletRequest(), if you still see the wrong behavior, make sure you find out which PersistentHttpServletRequestWrapper is causing it. I don't want to duplicate the logic without a good reason/

**Comment by SamZiemer** [comment]
@shuyangzhou Thank you for your advice, I am not sure what issue I was seeing originally, but I don't seem to be experiencing it after testing again. I have updated the commit to use getOriginalServletRequest(request); instead of duplicating the logic as you suggested.

**Pull request closed without merging**
