### PR TITLE
COMMERCE-1067 - batch-engine-service - Rename writer tests

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ivicac isn't BatchEngineTaskOperation, BatchEngineTaskItemResourceDelegate and BatchEngineTaskItemResourceDelegateFactory all for import? If so, they should be renamed.
And what about BatchEngineTaskConfiguration ?

**Comment by ivicac** [comment]
hi @shuyangzhou  BatchEngineTaskOperation, BatchEngineTaskItemResourceDelegate and BatchEngineTaskItemResourceDelegateFactory  are for both as they will contain methods for export in the registry, too. BatchEngineTaskOperation will have READ operation. I renamed BatchEngineTaskConfiguration into BatchEngineImportTaskConfiguration so we can have separate configurations for import/export

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ivicvc is something wrong? Can you rebate it normally locally?

**Comment by ivicac** [comment]
I force pushed as one key in Language properties was wrong

**Comment by ivicac** [comment]
yes, there is an issue, I will rebase it

**Comment by ivicac** [comment]
force pushed

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80619

**Pull request closed without merging**
