### PR TITLE
LPS-129058 Move JournalArticle content to DDMField tables

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @Preston-Crary, there is a regression issue caused by your changes. The web content Image field shows **The selected image was deleted.** that is defined by Edit Default Values
**Step to reproduce:**
1. Add a web content structure with an Image field
2. Click the ellipsis button of structure > Edit Default Values
3. Select > Web Content Images tab
4. Select an image > Add
5. Save
6. Add a web content based on new structure

**Expected Results:**
The **The selected image was deleted.** shouldn't be shown. The web content could be published successfully.

**Actual Results:**
The **The selected image was deleted.** is shown below the Image field. The web content cannot be published successfully.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9951

**Pull request closed without merging**
