### PR TITLE
Lps 108588

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this, thanks!

**Comment by vicnate5** [comment]
Failure unrelated. This can be forwarded.

There was a big rework of the UI for control panel, there are some test fixes still needed for this, it explains most of the failures on this and other PRs today.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/89601

**Pull request closed without merging**
