### PR TITLE
[Bug Fix]LPS-133613

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Using felix configurator causes 1 second regression on startup as it generates thread for each run, this is to fix the thread generation issue.

@GinsonRen please run a diff with this pull for startup.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@tinatian Here is the result:

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | e06bc300 | 44658 | 23257 | 23199 | 22442 | 23237 | 22760 | 22979 | -
PR-10047 | - | 45687 | 22193 | 22533 | 22752 | 22969 | 23031 | 22695.6 | -1.23%

BTW, the Thread/Create Count in profile is down from 2680 to 110.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
