### PR TITLE
[Bug Fix]Lps 122896 lps 121537 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
Rebase and resent at https://github.com/shuyangzhou/liferay-portal/pull/9576.

**Pull request closed without merging**
