### PR TITLE
Lps 67565 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
cc @topolik

test result:
https://github.com/yxingwu/liferay-portal/pull/126

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by topolik** [comment]
Hi @shuyangzhou, not sure who should review, I guess you or @rotty3000. 

Other way to fix c039989 is to change PortletTracker and support that property. But it's still default value so I don't see a need to declare it explicitly.

Thanks.

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
> Tests run: 1866, Failures: 1, Errors: 0, Skipped: 75
>
> Test case V3RenderStateTests_SPEC1_12_RenderState_getPortletMode2: Details: If the portlet mode is not available, PortletMode.UNDEFINED is returned. The portlet mode would not be available in a resource request invoked with a resource URL having FULL cacheability. Failed because portlet mode is not UNDEFINED but view

cc @arthurchan35 @topolik

**Comment by topolik** [comment]
Thanks @dantewang. Resent here (also fixed the NPE from the Portlet V3 TCK tests): https://github.com/shuyangzhou/liferay-portal/pull/8032

**Comment by topolik** [comment]
ci:close

**Pull request closed without merging**
