### PR TITLE
Skip all

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn please run a startup diff on this pull. Only for the last commit, not for the diff of the revert commits.

@vicnate5 please help me scan the ci results, thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are startup test results:


Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | e5792c2 | 47403 | 24778 | 23945 | 24621 | 25086 | 25009 | 25229
PR | - | 50563 | 24252.8 | 23241 | 24155 | 24419 | 24659 | 24790


Lily

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in test results.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9650

**Pull request closed without merging**
