### PR TITLE
Startup optimization 294 default service account user

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:users

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Only one regression found in integration test

com.liferay.user.service.test.UserLocalServiceTest > testSearch
```
 [exec] com.liferay.user.service.test.UserLocalServiceTest > testSearch FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.user.service.test.UserLocalServiceTest.testSearch(UserLocalServiceTest.java:562)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14372/modules-integration-mysql57-jdk8/4/10/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
Fixed and tested locally
See https://github.com/brianchandotcom/liferay-portal/pull/140511

**Pull request closed without merging**
