### PR TITLE
LPS-85956 Refactor AnnotationChainableMethodAdvices to centralize registration

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Had to drop fc55dfb744414e84abe88c66342079c757cde841 since we've now published.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Rebased and added bf8eaf5.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63810

**Pull request closed without merging**
