### PR TITLE
LPS-121090 Move the heavy ServiceTracker opening to an async thread.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@slnn I need data points before/after this pull in the daily startup monitoring, thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by slnn** [comment]
Hi @shuyangzhou 

Update test results in the startup performance monitor doc, this pull reduced the average startup time from 3011ms to 25436ms

Regards
Lily

**Comment by shuyangzhou** [comment]
Thanks @slnn !

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
