### PR TITLE
[Deprecation] LPS-104613

### PR DESCRIPTION
**Pull request by ChiZelin**
cc @dantewang

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
No unique integration / poshi failures, pull should be good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82656

**Pull request closed without merging**
