### PR TITLE
[Clustering] LPS-88022 Log more info when cluster is connected to our own logger

### PR DESCRIPTION
**Pull request by tinatian**
cc @vicnate5  @GinsonRen @dantewang

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Thanks @tinatian!

**Comment by tinatian** [comment]
Hi @vicnate5,
I create a copy of current clustering test plan, and modify the test steps according to my new logging, see https://docs.google.com/document/d/1PdnRq_Ik73x1uUI5FvBXmXJql0TQTZVjsNyBnulnoZQ/edit?usp=sharing.

I did not change the original one cause I am not sure if shuyang or Brian would like to do any change about the logging.

Could you please follow up the pull and do corresponding change to our test steps?

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/65513

**Pull request closed without merging**
