### PR TITLE
[TECHNICAL-SUPPORT] LPS-76494

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
Here are the changes I made:

https://github.com/jonathanmccann/liferay-portal/commit/05a321d4a3b464c9711c4b636833246588a74498

The end result is the same though, at least on my system (Ubuntu 16.04, JDK 1.8.0_144):

**lastModified** (https://github.com/jonathanmccann/liferay-portal/commit/05a321d4a3b464c9711c4b636833246588a74498#diff-09cc5514ae97695bd02a0b3915319d3bR293) = 1513183604939
**cachedFileLastModified** (https://github.com/jonathanmccann/liferay-portal/commit/05a321d4a3b464c9711c4b636833246588a74498#diff-09cc5514ae97695bd02a0b3915319d3bR296) = 1513183604000 (The FileTime returned here is in units of seconds, not milliseconds like the one created later does)
**fileTime** (https://github.com/jonathanmccann/liferay-portal/commit/05a321d4a3b464c9711c4b636833246588a74498#diff-09cc5514ae97695bd02a0b3915319d3bR324) = 2017-12-13T16:46:44.939Z

Doing a stat on the local file system returns the correct time with milliseconds intact:

Modify: 2017-12-13 08:46:44.939000000 -0800

Let me know what your thoughts are and if you'd like me to test anything else.

**Comment by jonathanmccann** [comment]
Is there any update on the above?

**Comment by shuyangzhou** [comment]
Sorry for the delay, busy year end.
Basically, if we just round down the milliseconds, we could potentially serve out of date cached results.

Can we try to use the first line of the file to record its last modified time? And make it a js comment line, so it is harmless to be sent back to browser.

**Comment by holatuwol** [comment]
@shuyangzhou: Couldn't we make the assumption that in development environments where people are actively modifying a Javascript file in a way where millisecond precision might matter, people will set `javascript.fast.load=false` and bypass AggregateFilter? It seems to be an unnecessary amount of code complexity for such an edge case.

**Comment by shuyangzhou** [comment]
@holatuwol I would prefer a strict cache validation, just in case. Otherwise there could be some unreproducible race conditions happen to production. This little extra work could buy us the peace in mind.

**Pull request closed without merging**
