### PR TITLE
[Deprecation] LPS-106103

### PR DESCRIPTION
**Pull request by yuhai**
@shuyangzhou, the pr is based on https://github.com/shuyangzhou/liferay-portal/pull/8667 to solve the compile error.

cc @tinatian, @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
@tinatian https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/349458/#showFailuresLink
Unusual amount of unique integration failures, see the staging related ones, BackgroundTaskException was thrown, could be related to the deprecated methods

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@kyle-miho, thanks, I will check this.

**Pull request closed without merging**
