### PR TITLE
Lps 102798

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou I reviewed the results from the first run. Only a few tests did not run, and the results are good. I do not think we need to wait for the new results.

All Content Page test passed: https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=921159708&testrayComponentId=865153655

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

See https://github.com/brianchandotcom/liferay-portal/pull/82358

**Pull request closed without merging**
