### PR TITLE
[Log4j] LPS-128599 | resend

### PR DESCRIPTION
**Pull request by dantewang**
Fix sem ver in portal-search-test-util. cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures not related.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9839

**Pull request closed without merging**
