### PR TITLE
[Bug Fix]LPS-86682

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

The value of MetaspaceSize was 512m and was changed by you in https://issues.liferay.com/browse/LPS-85007, I am not sure if you have any reason to drop it.

It is causing out of memory now, so I bring it back to 512m.

cc @dantewang @caixiangyue

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Before we bring it back to 512m, we should exam what is taking over this much space in meta space, this could be a sign of some kind of leaking. @dantewang do the first round exam on your side, let us know what you can find.

**Comment by shuyangzhou** [comment]
Is this still needed? Please resend if so.

**Comment by brianwulbern** [comment]
Yes, I'm talking with @dantewang about it.  Will make sure it gets resent.  Thanks.

**Pull request closed without merging**
