### PR TITLE
COMMERCE-7204, 8018, 8019, 8020, 8096

### PR DESCRIPTION
**Pull request by ctang3**

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:commerce

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by shuyangzhou** [comment]
@ctang3 please rebase in order to run the ci tests.

**Comment by ctang3** [comment]
@shuyangzhou Rebased and resent here: https://github.com/shuyangzhou/liferay-portal/pull/10571, thanks!

**Pull request closed without merging**
