### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull disabled sidecar by default, I test it locally and it works fine.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
Enable sidecar and test at https://github.com/vicnate5/liferay-portal/pull/1419.

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
@shuyangzhou @tinatian @vicnate5 The test results look good. There was one functional test failure `Elasticsearch7EE#XPackSmokeTest` within the `search-es7` suite that looked concerning, but I wasn't able to reproduce the issue locally so it may just require a test fix from us. We don't need to hold back this PR because of it.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85123

**Pull request closed without merging**
