### PR TITLE
[Bug Fix]LPS-129982 Sort classpath to ensure portal provided classes get loade…

### PR DESCRIPTION
**Pull request by tinatian**
…d first by URLClassLoader in DBUpgraderLauncher

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:upgrade-client

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by vicnate5** [comment]
@tinatian The test results we have are good, no regressions found. Waiting on the upgrade client tests that I needed to re-run due to a CI problem.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
I will also test this manually on Windows, since you are changing the classpath

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou This is good to go. Automation passed and manual test on Windows also passed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100622

**Pull request closed without merging**
