### PR TITLE
LPS-61888

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou hm so when I tried to do a more generic way here, it bombed out, but:
https://github.com/shuyangzhou/liferay-portal/pull/2253#issuecomment-170184239

is fine.  Do you want to just use the specific one for now?

**Comment by shuyangzhou** [comment]
yeah, let's make ci stable first. I will check the previous pull a bit later:)

**Comment by mhan810** [comment]
K if u can just change the commit LPS to LPS-61888  J

**Comment by shuyangzhou** [comment]
Yeah, will do that.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34124

**Pull request closed without merging**
