### PR TITLE
LPS-84479 HeaderResponse.addDependency() does not preserve the order in which dependences are added	

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou The `UpgradeException` failures are unrelated. The `StagingOrganizations` failure was not present in the first run -- it only appears in the second run so it must be unrelated. The `ViewPortalSmokeArchive70106` test fails in a different PR just now so that is unrelated as well.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62249

**Pull request closed without merging**
