### PR TITLE
[License]LPS-126664 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 This pull is going to fix the "3 occurrences of max node error during startup" issue in this pull, please verify.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian The hiding of the messages might be a bit aggressive as I no longer see any messages about exceeding the total nodes allowed:
https://gist.github.com/vicnate5/d71fe7ac680f2550c5caf8105e580521

Tested 1b

**Comment by tinatian** [comment]
@vicnate5 Did you apply this pull while testing https://github.com/shuyangzhou/liferay-portal-ee/pull/529

**Comment by vicnate5** [comment]
@tinatian Yes, I replaced `com.liferay.portal.license.enterprise.app.jar` with the one compiled from shuyangzhou/liferay-portal-ee#529

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/9735

**Pull request closed without merging**
