### PR TITLE
Get folders and file entries and file shortcuts count

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@lanceji92674957 a new sql log and compare.

**Comment by shuyangzhou** [comment]
@vicnate5 please watch out for DL related test failure, this might cause regression. Thanks!

**Comment by vicnate5** [comment]
@austinchiang @patriciajeanperez

**Comment by vicnate5** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:documents

**Comment by patriciajeanperez** [comment]
ci:test:documents

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73318

**Pull request closed without merging**
