### PR TITLE
[Bug] LPS-84318

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
We still have :
```
modules/sdk/project-templates/project-templates/src/main/java/com/liferay/project/templates/internal/util/ReflectionUtil.java:		if (!field.isAccessible()) {
modules/core/petra/petra-reflect/src/test/java/com/liferay/petra/reflect/ReflectionUtilTest.java:		Assert.assertTrue(field.isAccessible());
modules/core/petra/petra-reflect/src/test/java/com/liferay/petra/reflect/ReflectionUtilTest.java:			Assert.assertTrue(field.isAccessible());
modules/core/petra/petra-reflect/src/test/java/com/liferay/petra/reflect/ReflectionUtilTest.java:		Assert.assertTrue(method.isAccessible());
portal-impl/src/com/liferay/portal/json/jabsorb/serializer/LiferaySerializer.java:					if (!field.isAccessible()) {
portal-impl/src/com/liferay/portal/json/jabsorb/serializer/LiferaySerializer.java:					if (!field.isAccessible()) {
portal-impl/src/com/liferay/portal/spring/aop/ServiceBeanMethodInvocation.java:		if (!_method.isAccessible()) {
portal-kernel/src/com/liferay/portal/kernel/util/ReferenceEntry.java:		if (!_field.isAccessible()) {
```
Make sure to go over them and clean up all necessary ones, and talk to @hhuijser to make a SF rule for it.
Please resend with all appropriate usages fixed, the SF rule can be deferred, does not need to send together in next pull.
Thanks

**Comment by tinatian** [comment]
@shuyangzhou Yes, I saw that, was supposed to ask them to do it in a separate ticket. Thought this was to prepare for unit test.

**Comment by tinatian** [comment]
@dantewang Could you please fix all the usages like this? And ask @hhuijser to add rule for this.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
@tinatian it is a simple change, I'd rather do them all at once.

**Comment by tinatian** [comment]
@shuyangzhou Yes, it is better to do it together.
@dantewang Could you please also check ee repository and fix all the usages?

Thanks.
Tina.

**Comment by hhuijser** [comment]
It took a while before I got to looking into this one.

Couple of things

1.  Why is this a bug? Seems like a performance issue to me. Nothing would break with that extra if statement?

2. Is it really always a redundant if statement?

When the call `setAccessible` directly followed by the retrieval of the method/field from the class like we do [here](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/MethodCache.java#L43-L46), it's obvious that it's redundant.

However, for a case like [here](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/ReferenceEntry.java#L34), we could potentially have a field where `accessible` was set to `true` already?
I am sure that for this one, there would not be such a use case, but just saying that it's possible to have cases where the if statement is not redundant.

Please correct me if I am completely wrong on this one.

**Pull request closed without merging**
