### PR TITLE
LPS-85191 Create Shared With Me app

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Fixed the compile error from SharingPortletKeys moving since I sent the pull. Only change is 6f83fc6.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Preston-Crary seems like real jspc failure, please fix and resend.

**Comment by sergiogonzalez** [comment]
Hey @shuyangzhou I have resent it here https://github.com/shuyangzhou/liferay-portal/pull/6774

**Pull request closed without merging**
