### PR TITLE
LPS-106526 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-106526

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @vicnate5 fyi bc risky

**Comment by kyle-miho** [comment]
Tested here: https://github.com/kyle-miho/liferay-portal/pull/319
failures all seem to be unrelated, fixed the SF failure after

**Comment by shuyangzhou** [comment]
@vicnate5 should we run a bigger scope test?

**Comment by shuyangzhou** [comment]
@kyle-miho can you update the test to cover the changed logic?

**Comment by vicnate5** [comment]
@kyle-miho After you update, we should re-run ci-test because I just added more coverage to acceptance that applies. This should be enough test scope.

**Comment by kyle-miho** [comment]
ci:close i'll cover the changed logic in a test

**Pull request closed without merging**
