### PR TITLE
LPS-X Lazy loading ResourceBundle

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Unique failure in integration test. I can reproduce locally.
https://testray.liferay.com/home/-/testray/case_results/2172671413

**Comment by shuyangzhou** [comment]
@vicnate5 see https://github.com/shuyangzhou/liferay-portal/pull/10919/commits/9fd5d2a313c8f97dfd29444bd0ea9724c6d7f90e it is actually just a bad test. The test has this race since it was created. But due to that nearly 2s language resource bundle loading, it was completely covered up. After the optimization, the race got exposed.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129272

**Pull request closed without merging**
