### PR TITLE
[Bug Fix]LPS-120753

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is going to fix both https://issues.liferay.com/browse/LPS-120755 and https://issues.liferay.com/browse/LPS-120753.

FYI @vicnate5

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by tinatian** [comment]
@vicnate5 Are the unique failures real?

Thanks.
Tina.

**Comment by tinatian** [comment]
close, will resend

**Pull request closed without merging**
