### PR TITLE
LPS-124261 RSS Toggle Not Saving User Selection in Blogs Configuration

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-124261](https://issues.liferay.com/browse/LPS-124261).<br/><br/>Hey @shuyangzhou, this clears map entries on both Configuration updates and PortletPreferences updates. I believe this covers all cases where map entries would be removed.

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @noornajj @jonathanmccann

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@drewbrokke failures are real, please fix and resend.

**Comment by drewbrokke** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9684

**Pull request closed without merging**
