### PR TITLE
LPS-105177 Use correct servlet context name instead (this is needed for many Liferay services because the correct property value is only determined at run time where as the service properties are defined at compile time)

### PR DESCRIPTION
**Pull request by cleydyr**

### CODE REVIEW

**Comment by cleydyr** [comment]
Hey, @shuyangzhou . Only now I've had the time to take care of this issue again. I'm afraid the proper property can't be attached to most of the services (as you suggested) as the properties are defined by annotations and the portal servlet context is defined at runtime. This is the same reason for a fix like https://github.com/brianchandotcom/liferay-portal/commit/bce4e0c1d567723ba0d3428876e63765ca7df264.

So I'm sending a less naïve solution, but that still has to deal with issues like LPS-74219 and LPS-98360.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 this is for websphere, (I guess weblogic could be affected too?) can we run some additional tests for it?

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@koor4356 can you look at these test results? Specifically for weblogic and websphere

**Comment by koor4356** [comment]
@shuyangzhou, The pull looks good. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83478

**Pull request closed without merging**
