### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1. Dumping log4j.properties into temp folder
2. Clean up the configuration file, remove unused properties

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @vicnate5,
Please scan the test result.
Could you please rerun the manual tests on this pull?

Thanks.
Tina.

**Comment by vicnate5** [comment]
Manual Test execution: https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?userstoinvite=169342701%40liferay.com&ts=5e2a3128#gid=1206555946&range=B5

@xbrianlee skipping Test Group 3 until Search team can help with the steps.

**Comment by tinatian** [comment]
Fix random shutdown error here : https://github.com/shuyangzhou/liferay-portal/pull/8794

**Pull request closed without merging**
