### PR TITLE
[TEMP] working version for portlet session issue

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou This is a working version using the ugly way for the portlet session issue related to the TCKs. Both V2EnvironmentTests_PortletSession_ApiRender_isNew1 and the test cases Neil mentioned in https://issues.liferay.com/browse/LPS-77746 pass on this branch. The Equinox side change is in this branch: https://github.com/dantewang/rt.equinox.bundles/commits/LPS-78581.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please help dante on this one, I won't have time for it this week.

**Comment by tinatian** [comment]
OK, I will

**Comment by tinatian** [comment]
See https://github.com/dantewang/liferay-portal/pull/612

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
