### PR TITLE
LPS-109118 Fix way to replace by setting a higher ranking service.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
pull should be good, nothing looks related/unique

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8957

**Pull request closed without merging**
