### PR TITLE
LPS-91578 Adds refererPlid parameter to the URL without namespace

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @shuyangzhou!
Could you please take a look if InputPermissionsTag changes [here](https://github.com/shuyangzhou/liferay-portal/pull/7509/commits/3adb5bed90bc248f1082737dcbe3d2ff309ec090) are ok?

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@pavel-savinov I actually have no idea what this is doing. It is better to find someone who knows this to double check. Sorry.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
