### PR TITLE
LPS-113460 CT friendly-url-service

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@Preston-Crary this looks real?

**Comment by Preston-Crary** [comment]
@shuyangzhou yes, will resend after fixing the failure.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9069

**Pull request closed without merging**
