### PR TITLE
Lps 129668

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou There is 1 unique failure on startup with the LPKG base test. I have no record of the failure at head, but I do not think it is related to these changes either.
```
ERROR [com.liferay.portal.osgi.web.wab.extender.internal.WabFactory-BundleTrackerOpener][JDBCExceptionReporter:234] Duplicate entry '20011-37134-0' for key 'IX_7BF8337B'
```
Full log: https://testray.liferay.com/reports/production/logs/2021-03/test-1-19/test-portal-acceptance-pullrequest(master)/8020/lpkg-base-jdk8/0/0/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
@vicnate5 yeah, it can not be related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100419

**Pull request closed without merging**
