### PR TITLE
LPS-64261 GroupFinderImpl

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
These tests are failing on some of your other pulls.  After looking into it they don't seem related to my changes.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Talked to @Preston-Crary, he will resend with more changes.

CC @lipusz

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/2935

**Pull request closed without merging**
