### PR TITLE
LPS-82215 Set the property for all the databases in our CI and avoid conditional ignore the test if they do not exist

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@robertoDiaz not like this, the test should not be affected by portal-test.properties, it needs to set the size by code to be immune from env changes.
@Preston-Crary please help @robertoDiaz on this.

**Comment by robertoDiaz** [comment]
Hey @shuyangzhou 

You mean change the property value in the setUp method or something like this. Is it right??

**Comment by Preston-Crary** [comment]
@robertoDiaz you shouldn't even need to change the property value.  You can reflect the RestrictionsFactoryImpl._databaseInMaxParameters field.

**Comment by robertoDiaz** [comment]
Hey @Preston-Crary 

Do you have an example of this??

I'd like to finish this this week since I'm starting my holidays this Friday, and I have to finish other tasks either.

Thanks in advance!

**Comment by Preston-Crary** [comment]
@robertoDiaz Use the ReflectionTestUtil.getAndSetFieldValue(Object, String, String) method.

**Pull request closed without merging**
