### PR TITLE
[Bug Fix]LPS-129966

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
@shuyangzhou and @dantewang I did review this once again and I think that provided fix is not good:
com.liferay.dispatch.talend.archive.TalendArchiveParserUtil#updateUnicodeProperties method should not be responsible for deleting TEMP directory.
Please can you rollback this update because this test class causes issue at CI environment:
com.liferay.dispatch.talend.archive.TalendArchiveParserUtilTest#testUpdateUnicodeProperties
that method should delete temp folder.

Also please look that this methods properly delete temp folder:
com.liferay.dispatch.talend.web.internal.portlet.action.EditDispatchTalendJobArchiveMVCActionCommand#doProcessAction
com.liferay.commerce.salesforce.connector.internal.instance.lifecycle.AddCommerceSalesforceConnectorPortalInstanceLifecycleListener#_createDispatchTrigger

What is good fix is to update test to delete temporary folders.

@shuyangzhou and @dantewang can you please skip merging https://github.com/shuyangzhou/liferay-portal/pull/10214/commits/676b60c11567855af1dc584699d58888eed28450 and let me fix the test. That way we keep updateUnicodeProperties method have only one responsibility - update unicode properties.

If you merge this it may end-up that you will cause regressions because other classes will try to delete folder that does not exist.

**Comment by dantewang** [comment]
@igorbeslic `TalendArchiveParserUtil#parse` has a side effect that it leaves a temp dir after execution. If we directly call it, we can know the dir from the returned `TalendArchive` and manually delete it. Tina created a ticket about this behavior, see https://issues.liferay.com/browse/COMMERCE-7055.

However, the method we modified is `TalendArchiveParserUtil#updateUnicodeProperties`, which doesn't even give caller the chance to manually clean up the side effect of its execution, as it doesn't return the `TalendArchive`. So we can't move the delete logic to the caller.

For example, `AddCommerceSalesforceConnectorPortalInstanceLifecycleListener#_createDispatchTrigger` writes a zip file into the `tomcat-x.x.x/temp` from the class loader stream, and then calls `updateUnicodeProperties` to `parse` the zip, which unzips the zip file into a temp dir. It will only delete the **"temp zip file"**, not the **"temp dir to unzip the zip file"**:

```
		File connectorArchiveFile = FileUtil.createTempFile(
			clazz.getResourceAsStream("/" + name));

......

		finally {
			FileUtil.delete(connectorArchiveFile);
		}
```

**Comment by tinatian** [comment]
Hi @igorbeslic ,
The root cause of this issue is TalendArchiveParserUtil#parse. It created a temp folder and returned it as a attribute of TalendArchive. You can not delete the temp folder inside this method as the folder may be used later by execution. Thus, you have to manually delete each time you use it like what TalendDispatchTaskExecutor#doExecute does at https://github.com/liferay/liferay-portal/blob/386c1052195181db5f6b83076f81fc89a34e733a/modules/apps/dispatch/dispatch-talend-web/src/main/java/com/liferay/dispatch/talend/web/internal/executor/TalendDispatchTaskExecutor.java#L110.

It is the bad design that causing this weird manually removal of temp folder. Generally you should always create and delete the temp folder in the same place(like same method or class) to make sure no leaking. No like this to create temp folder in one method, pass the folder around to another method to use, and delete it.

The best way is to store a folder and avoid unzipping to temp folder each time you read, that's why I created https://issues.liferay.com/browse/COMMERCE-7055. As this fix may take a while, and we are cleaning up our bug tickets, we submit this temp fix for it.


Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
