### PR TITLE
LPS-136729 Enable CT for repository

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-136729

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by vicnate5** [comment]
@ctang3 There is a regression here when upgrading a database that uses partitioning.

Steps to Reproduce:
1. Download [7.4.1 partitioned database](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.1/data-archive/data-archive-portal-partition-mysql.zip)
2. Import into MySQL (will create databases `lportal`, `lpartition_39134`, and `lpartition_41246`)
3. Set property in portal-ext `database.partition.enabled=true`
4. Also set property same property in `portal-upgrade-ext.properties` (inside of tools/portal-tools-db-upgrade-client/)
3. Upgrade to master
4. Start Portal

Error on startup
```
ERROR [Portal Dependency Manager Component Executor--1][JDBCExceptionReporter:234] Unknown column 'repository0_.ctCollectionId' in 'field list'
2021-12-07 23:19:59.546 WARN  [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:162] Unable to register portal instance {"mvccVersion":
1, "companyId": 39134, "userId": 0, "userName": "", "createDate": null, "modifiedDate": null, "webId": "www.able.com", "mx": "www.able.com", "homeURL": "", "logoId": 0, "system":
false, "maxUsers": 0, "active": true, "name": "", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not load an entity: [com.liferay.portal.model.impl.RepositoryImpl#39162]
        at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:634) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.fetchByPrimaryKey(BasePersistenceImpl.java:340) ~[portal-kernel.jar:?]
        at com.liferay.portal.service.persistence.impl.RepositoryPersistenceImpl.fetchByPrimaryKey(RepositoryPersistenceImpl.java:2710) ~[portal-impl.jar:?]
        at com.liferay.portal.service.persistence.impl.RepositoryPersistenceImpl.fetchByPrimaryKey(RepositoryPersistenceImpl.java:2745) ~[portal-impl.jar:?]
        at com.liferay.portal.service.base.RepositoryLocalServiceBaseImpl.fetchRepository(RepositoryLocalServiceBaseImpl.java:251) ~[portal-impl.jar:?]
```

Functional impact:
Navigate to second virtual host (www.able.com:8080) and go to Documents and Media - Portlet will fail to render.

**Comment by ctang3** [comment]
Thanks for looking into this @vicnate5 

Will fix and resend.

**Comment by ctang3** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/10541

Thanks!

**Pull request closed without merging**
