### PR TITLE
Lps 86709 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please watch over this pull for me, hopefully we can get it out today, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/brianchandotcom/liferay-portal/pull/83363

**Pull request closed without merging**
