### PR TITLE
Startup optimization 317 defer resource proxy class generation

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
The failure in test [com.liferay.portal.tools.rest.builder.RESTBuilderTest](https://testray.liferay.com/home/-/testray/case_results/2441476313) seems related:
```
[beanshell]      [exec] com.liferay.portal.tools.rest.builder.RESTBuilderTest > testCreateRESTBuilder FAILED
[beanshell]      [exec]     org.junit.ComparisonFailure: Error comparing sample-impl/src/main/java/com/example/sample/internal/resource/v1_0_0/factory/FolderResourceFactoryImpl.java
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-26/test-portal-acceptance-pullrequest(master)/11500/modules-unit-jdk8/0/11/jenkins-console.txt.gz?authuser=0

But I tested the test in another pull: https://github.com/zhangyan0701/liferay-portal/pull/557. There error is:
```
[beanshell]      [exec] com.liferay.portal.tools.rest.builder.RESTBuilderTest > testCreateRESTBuilder FAILED
[beanshell]      [exec]     org.junit.ComparisonFailure: Error comparing sample-impl/src/main/java/com/example/sample/internal/resource/v1_0_0/factory/DocumentResourceFactoryImpl.java
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7913/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, I think @catarineaguiar is already off for the day. Thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142288

**Pull request closed without merging**
