### PR TITLE
TCK3 LPS-75370 Resend

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou
This is according to PLT 8.4

The portlet can find out which container runtime options are supported by the portlet container through the PortletContext.getContainerRuntimeOptions method. This method returns an enumeration of type String containing the keys of all container runtime options that the current portlet container supports.
This issue was causing some test portlets unable to be rendered. 40 failures can be fixed as counted on CI.

I tried to add the Set to LiferayPortletConfig but it caused minor version increasing, failing commerce tests on CI. I'm thinking of adding a unit test to make sure developer update the Set when a new supported runtime option is added, any suggestion?

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@dantewang can you update the tck test google doc with the new test fixes? So that I can see how much progress we have made so far. Thanks!

**Comment by dantewang** [comment]
@shuyangzhou 
I updated the doc with the latest status.

The current google doc is a bit messed up since some of the issues are added without analysis and some are actually issues revealed by other fixes.

Since there are not so many test cases left, I'll create a new page and record fixes by test cases - ticket. I'll also keep the main page updated.

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2017年11月20日周一
17:20写道：

**Comment by shuyangzhou** [comment]
@dantewang what really sure what do you mean by "I tried to add the Set to LiferayPortletConfig but it caused minor version increasing", why you need to add it there? Are you talking about a different issue?
Is this pull good enough to be merged, or it needs something else?

**Comment by dantewang** [comment]
@shuyangzhou Sorry I didn't include the full context in the description. 

In this pull, the runtime options in the enumeration returned by `PortletContextImpl.getContainerRuntimeOptions()` are hardcoded in the static block. However, the concern is, when a developer adds support for a new runtime option, how to ensure the option also to be added to the enumeration.

I mentioned `LiferayPortletConfig` because the runtime option constants are declared there.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53167

Ok, I see what you meant now. We don't need worry about this right now. We can deal with this when we really need to add a new option.
The worst case is, create a new constants class, and copy exist ones/adding new ones to it, deprecate the current ones.

**Pull request closed without merging**
