### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak I have analyzed the failures as best I can:

1) I can confirm that the first failure is not caused by this PR because I rebuilt master (without my PR commits) and it happens when clicking on "Documents and Media" in the Control Panel:
```
[exec] Caused by: java.lang.NullPointerException
[exec] 	at com.liferay.document.library.web.internal.display.context.logic.DLPortletInstanceSettingsHelper.getEntryColumns(DLPortletInstanceSettingsHelper.java:130)
```

2) I was not able to try the Liferay Forms POSHI failure.

3) All other failures seem to be POSHI test failures and, although I could be wrong, I don't think that they are related to the commits in this PR. I manually tested the functionality of "Site Memberships" and "Site Teams" in the control panel and everything seemed to work fine. Perhaps the POSHI tests have a different sequence of steps than what I tried, but I can't see any problems in the UI or in the server log.

Please let me know if you think this PR can be review by Shuyang. This PR is fundamental to all subsequent PRs related to Portlet 3.0. Thanks.

**Comment by timpak** [comment]
@ngriffin7a looking into them now

**Comment by ngriffin7a** [comment]
Thanks @timpak ! Looking forward to your analysis.

**Comment by timpak** [comment]
hey @ngriffin7a the functional and lpkg are also seen on the acceptance run and aren't related to your changes. They shouldn't have been listed as failures unique to this pull. The only failure that is unique is semantic versioning. From what I understand, this isn't something your pull should be modifying right?

>      [exec] :apps:collaboration:document-library:document-library-api:baseline
>      [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
>      [exec] = ================================================== ========== ========== ========== ========== ==========
>      [exec]   com.liferay.document.library.display.context       UNCHANGED  2.3.0      2.2.0      2.2.0      EXCESSIVE VERSION INCREASE
>      [exec] 	-   version    2.2.0
>      [exec] 	+   version    2.3.0
>      [exec] :apps:collaboration:document-library:document-library-api:baseline FAILED
>      [exec] :apps:collaboration:document-library:document-library-api:syncVersions

**Comment by ngriffin7a** [comment]
@timpak Checking now, standby...

**Comment by ngriffin7a** [comment]
@timpak The only thing related to document-library-api that I changed was an upgrade to the portlet-api-3.0.0 dependency: modules/apps/collaboration/document-library/document-library-api/build.gradle

So I'm not sure why the Semantic Versioning error is unique to the PR. I don't see that happening locally when I run `ant all`

**Comment by timpak** [comment]
@ngriffin7a makes sense. Thanks for being so patient!

@shuyangzhou please review.

**Comment by ngriffin7a** [comment]
Thanks @timpak !

**Comment by shuyangzhou** [comment]
@ngriffin7a please rebase this pull, thanks!

**Comment by ngriffin7a** [comment]
Rebased, see: https://github.com/shuyangzhou/liferay-portal/pull/6102

**Pull request closed without merging**
