### PR TITLE
Startup optimization 89 searchengine

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 pushed fix for ElasticsearchEngineConfiguratorTest failure

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10809

**Pull request closed without merging**
