### PR TITLE
[Remove  portal-kernel-*-compat]LPS-103653

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this is one of the pulls that needs all the tests we have.

**Comment by shuyangzhou** [comment]
ci:test:gauntlet

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in the test results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80727

**Pull request closed without merging**
