### PR TITLE
Startup optimization 184 expando column model listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:tango

**Comment by shuyangzhou** [comment]
@vicnate5 this changes segments-service and portal-odata-api/impl, anything else we should run?

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by kyle-miho** [comment]
Some builds were aborted for both suites, re-running suites

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:tango

**Comment by kyle-miho** [comment]
@shuyangzhou There are some unique failures such as com.liferay.segments.security.permission.contributor.test.SegmentsEntryRoleContributorTest 
I am testing these locally right now

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:tango

**Comment by shuyangzhou** [comment]
@kyle-miho fixed the failure, please monitor the new results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou okay i will check the results tomorrow morning since they are still running

**Comment by kyle-miho** [comment]
No unique failures found, PR should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131857

**Pull request closed without merging**
