### PR TITLE
Lps 176935 new

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Additional test coverage: https://github.com/shuyangzhou/liferay-portal/pull/10975

**Comment by vicnate5** [comment]
@gaborlovasdotcom @JoyceWang08211 @melodywu This PR fixes a major bug with virtual instances under clustering but I see unique failures in some of the AppSec tests. Could your team review the possible test regressions here? I don't know how to run these tests locally. 

https://testray.liferay.com/home/-/testray/case_results/2225394237
https://testray.liferay.com/home/-/testray/case_results/2225399512
https://testray.liferay.com/home/-/testray/case_results/2225400514

Would you be able to provide steps to reproduce if there is a regression?

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@JoyceWang08211 We have a possible fix for the LDAP failure running at https://github.com/shuyangzhou/liferay-portal/pull/10976

The test result there and here will include the bundle download link under "Test bundle downloads:"

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 We have a possible fix for the LDAP failure running at #10976
> 
> The test result there and here will include the bundle download link under "Test bundle downloads:"

@vicnate5 Thx for the info. After a quick look, the LDAP failure is that the imported LDAP user missing after restarting the portal.

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10976

**Comment by vicnate5** [comment]
@JoyceWang08211 Even though it is NLR in our future PRs, would you be able to provide the manual steps to reproduce the OpenID failure at https://testray.liferay.com/home/-/testray/case_results/2225400514?

Using the bundle here: https://files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/7219/liferay-portal-bundle-tomcat.tar.gz

**Comment by JoyceWang08211** [comment]
> would you be able to provide the manual steps to reproduce the OpenID failure at

Hi @vicnate5, here are the manual steps for this OIDC testcase:
https://issues.liferay.com/browse/LPS-157664?focusedCommentId=2718885&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2718885  

TC-1: Users could login using OAuth client.

1. Navigate to OAuth Client Administration
2. Add a configuration entry as following:
 a. Authorization Server Well-known URI: [https://dev-5081331.okta.com/.well-known/openid-configuration]
 b. OAuth Client Information： \{ "client_id": "0oa2f6ikwu8bYgkyq5d7", "client_secret": "yyabDVfpgIJfEFiHIeLBmd4l7VhBbIZBg5tksLtS", "redirect_uris": [ "" ], "client_name": "OKTA", "scope": "openid email profile", "subject_type": "public", "grant_types": [ "authorization_code", "refresh_token" ], "response_types": [ "code" ] }
 c. OAuth Client Default Authorization Request Parameters： \{ "response_type": "code", "scope": "openid email profile" }
 d. OAuth Client Default Token Request Parameters： \{ "grant_type": "authorization_code", "scope": "openid email profile" }
 3. Navigate to Instance Settings > SSO > OpenID Connect
 4. Check enabled
 5. Sign out
 6. Click “Sign In”
 7. Click “OpenID Connect”
 8. Login using OKTA
 9. Assert OIDC user is able to log in portal.

**Pull request closed without merging**
