### PR TITLE
Leftover 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by mtambara** [comment]
NPE
```     [exec] com.liferay.journal.service.test.JournalArticleLocalServiceTest > testUpdateDDMStructurePredefinedValues FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at java.util.ArrayList.<init>(ArrayList.java:177)
     [exec]         at com.liferay.portal.test.rule.callback.LeftoverDataTestCallback.afterClass(LeftoverDataTestCallback.java:85)
     [exec]         at com.liferay.portal.test.rule.callback.LeftoverDataTestCallback.afterClass(LeftoverDataTestCallback.java:40)
     [exec]         at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:116)
     [exec]         at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:155)
     [exec]         at com.liferay.portal.kernel.test.rule.BaseTestRule$3.evaluate(BaseTestRule.java:110)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.observer.JUnitBridgeObserver.evaluateWithClassRule(JUnitBridgeObserver.java:153)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.observer.JUnitBridgeObserver.aroundTest(JUnitBridgeObserver.java:118)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)```

**Comment by shuyangzhou** [comment]
ok, I will check on it after current work

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@mtambara fixed, retesting.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
Fixed DDMCleanupPortalInstanceLifecycleListener issue, testing again

**Comment by shuyangzhou** [comment]
@mtambara this is the parent ticket https://issues.liferay.com/browse/LPS-87986

**Comment by shuyangzhou** [comment]
Updated blacklist

**Comment by shuyangzhou** [comment]
@mtambara we need to resume this at some point.

**Pull request closed without merging**
