### PR TITLE
Lps 76494 Properly timestamp css cache file

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I tested it locally and it works well, but have not tested it on CI, please wait for CI result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by tinatian** [comment]
@shuyangzhou Seems the failed tests are not related to my change.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56167

**Pull request closed without merging**
