### PR TITLE
[BREAKING_CHANGES.markdown]LPS-106008 

### PR DESCRIPTION
**Pull request by tinatian**
FYI @jhinkey @vicnate5

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@achaparro @ericyanLr @david-truong

**Comment by achaparro** [comment]
This is what customers need to know. Thanks @tinatian @dantewang @vicnate5

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83419

**Pull request closed without merging**
