### PR TITLE
Embedded jasper

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@GinsonRen I need a regression check on login and MB for this pull, can you get it done today?
Thanks!

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the result:

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 03db323fd | 29605 | 499 | 152 | -
PR-10093 | - | 28139 | 798 | 251 | -4.95%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 03db323fd | 15489 | 3500 | 2280 | -
PR-10093 | - | 15789 | 3210 | 2230 | 1.94%

There is maybe a regression on MB cause such high meantime recently, I am still working on figure it out.

**Comment by shuyangzhou** [comment]
Thanks @GinsonRen  ! please get me login cpu tracing profiles on baseline and this pull.

**Comment by vicnate5** [comment]
@kyle-miho can you scan this PR?

**Comment by kyle-miho** [comment]
Unique failures: 
1. Executing upgrade causes error:
[com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query](https://gist.github.com/kyle-miho/12d7c23256c008d43278461ecff4374d)
[(Testray Link)](https://testray.liferay.com/home/-/testray/case_results/1540116933?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D101949%26testrayBuildId%3D1540114374%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
2. Executing upgrade causes error:
[java.io.IOException: Exception in opening zip file: /opt/dev/projects/github/liferay-portal/bundles/osgi/state/org.eclipse.osgi/1329/0/bundleFile](https://gist.github.com/kyle-miho/b797c57d56e3af178b12014fbd864dc1)
[(Testray Link)](https://testray.liferay.com/home/-/testray/case_results/1540116929?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D101949%26testrayBuildId%3D1540114374%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by shuyangzhou** [comment]
@kyle-miho those failures should not be caused by this change. This pull changes how jsps are rendered and how classes are loaded, not how db is accessed.
Can you rerun those tests, and also try it locally? If you can reproduce it locally, let me know the steps, I will try it too.
Thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou everything else should be good, ill check the upgrade issues locally real quick

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Comment by kyle-miho** [comment]
@shuyangzhou i couldnt reproduce the upgrade issue locally, it might be a race condition, ill investigate it more seperately

**Comment by shuyangzhou** [comment]
Oh, sorry @kyle-miho I pushed some incompleted changes on this pull, the build will break for sure with the current state.
I will rerun the full test once I have everything in place.

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by GinsonRen** [comment]
@shuyangzhou Do you still need  login cpu tracing profiles  for this pull? I noticed there is a new pull https://github.com/shuyangzhou/liferay-portal/pull/10099.

**Comment by shuyangzhou** [comment]
@GinsonRen run the compare on the new pull, if there is still noticeable difference, run a cpu tracing profiles on the new pull, thanks!

**Pull request closed without merging**
