### PR TITLE
Lps 97609

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by vicnate5** [comment]
@xbrianlee @joshchong

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
@shuyangzhou @mtambara @vicnate5 @xbrianlee The one `functional-tomcat90-mysql57-jdk8` failure in the `ci:test:search-solr` test run above is a known issue. Besides that the results for that test run look good!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76016

**Comment by vicnate5** [comment]
@mtambara Could this affect the blacklist? The `bundle-blacklist-restart-jdk8` test failed here.

**Comment by mtambara** [comment]
@vicnate5 It shouldn't, I tested it on a local branch and didn't see the blacklist test fail there

**Pull request closed without merging**
