### PR TITLE
[READ INSIDE] LPS-53765 Dedupes list to avoid duplicate portlet ids

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @shuyangzhou, I'm sending this over because for some reason, **the `ChatPortlet` id is being printed twice** in [top_js.jspf](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/themes/top_js.jspf#L441-L451). This is the content of the list after printing it looping the `Portlets` list:

```
0 : "com_liferay_chat_web_portlet_ChatPortlet"
1 : "com_liferay_hello_world_web_portlet_HelloWorldPortlet"
2 : "com_liferay_chat_web_portlet_ChatPortlet"
3 : "com_liferay_product_navigation_user_personal_bar_web_portlet_ProductNavigationUserPersonalBarPortlet"
4 : "com_liferay_portal_search_web_portlet_SearchPortlet"
5 : "com_liferay_site_navigation_menu_web_portlet_SiteNavigationMenuPortlet"
6 : "com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet"
```

Could you take a look to see if you can figure out why?

I've simply deduped the list to avoid future issues, but if you can make sure the list from the server is accurate, then we can just revert it and simply trust the info that gets printed.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:close

**Comment by Robert-Frampton** [comment]
@shuyangzhou 

I'm planning on addressing this issue in my changes for LPS-73899.

**Pull request closed without merging**
