### PR TITLE
LPS-116551 Refactor TableReferenceDefinition to remove auto parent / child detection

### PR DESCRIPTION
**Pull request by Preston-Crary**
Considered adding TableReferenceDefinition.defineOptionalTableReferences(...) method for the userId column.  But that can be added later if we find another case where it is needed.

Several incorrect parent/child relationships were fixed by this including DDMStructure being a child of JournalArticle which is what c32a18d is about.

For a normal module, if there's a model listener used to cascade deletes then that's a parent reference and if the local service has logic to cascade deletes then that's a child reference.

Once this is in we can do the API / SPI split.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
Functional test failures should be unrelated, only change was the versioning commit cfecf28.

**Comment by shuyangzhou** [comment]
ci:forwarding

**Comment by shuyangzhou** [comment]
@vicnate5 please check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou failures are not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91207

**Pull request closed without merging**
