### PR TITLE
Lps 123727

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Hi @mtambara,

 I don't understand your change. According to specifications having a dash in the SymbolicName is valid (maybe not recomendable, but valid):

```
Bundle-SymbolicName ::= symbolic-name 
                        ( ';' parameter ) *    // See 1.3.2
symbolic-name   ::= token ( '.' token )*
token           ::= ( alphanum | '_' | '-' )+
```

Kind regards.

**Comment by mtambara** [comment]
@marianoalvarosaiz That's true, but all of Liferay's symbolic names will follow the reverse domain name convention and as far as I know, a customer would only need to override a jar from an ootb bundle. The problem with only searching for the word "hotfix" in the version piece is that the version qualifier is much more likely to contain other words (like "snapshot"), so I believe this will catch the most cases

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9623. @marianoalvarosaiz I came up with a regex that should be able to handle all symbolic names and qualifiers

**Pull request closed without merging**
