### PR TITLE
LPS-X Inline simple end.jsp

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@tomwang2011 run a diff please.

**Comment by tomwang2011** [comment]
Hi @shuyangzhou the results for this pull is at: smb://172.16.0.30/benchmark/2016/TestPulls-Shuyang/12-19-16-SPATopHeadJSPDynamicIncludes

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@tomwang2011 have you run this yet?

**Comment by tomwang2011** [comment]
not yet, this is next on my queue, currently running https://github.com/shuyangzhou/liferay-portal/pull/3574 and https://github.com/tomwang2011/liferay-portal/pull/263

**Comment by tomwang2011** [comment]
The results for this pull is at: smb://172.16.0.30/benchmark/2016/TestPulls-Shuyang/12-20-16-InlineEndJsp

**Pull request closed without merging**
