### PR TITLE
[TECHNICAL-SUPPORT] LPS-73150

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@Preston-Crary please take this over, looks related to our previous virtualhost changes.

**Comment by Preston-Crary** [comment]
@mbowerman, please resend with the changes we discussed.  Thanks!

**Comment by Preston-Crary** [comment]
ci:close

**Comment by mbowerman** [comment]
@Preston-Crary Please see https://github.com/Preston-Crary/liferay-portal/pull/336.

**Pull request closed without merging**
