### PR TITLE
Pushdown petra

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou 

### Regression found
When the user starts Websphere after an upgrade, there is always an error thrown
```
ERROR [SoapConnectorThreadPool : 0][ModuleFrameworkAdapterHelper:123] Unable to load the module framework
```
No functional impact found.
Logs at https://testray.liferay.com/home/-/testray/case_results/1530109409

This does **not** occur when starting Websphere on a blank database:
https://testray.liferay.com/reports/production/logs/2021-05/test-1-9/test-portal-acceptance-pullrequest(master)/4717/functional-websphere90-mysql57-jdk8/0/16/jenkins-console.txt.gz

Reproducing this locally will take some time since it is Websphere + an upgrade, we should probably just rely on CI to test this.

### Concern
`PropsKeys.LIFERAY_LIB_GLOBAL_DIR` returns the portal lib directory now, are we denying access to the app server global directory?

**Comment by shuyangzhou** [comment]
@vicnate5 after this pull, the only thing left in global is the support-xxx , so yes, the previous need for global lib dir is no longer there. if we can get rid of those support-xxx, we can even remove the property. I will look into the upgrade problem. it only exists for websphere? that's a bit strange.

**Comment by vicnate5** [comment]
@shuyangzhou Upgrade issue is Websphere only.

What does LIFERAY_LIB_GLOBAL_DIR do for the `support-*`? It doesn't return the global dir, it is just a duplicate of LIFERAY_LIB_PORTAL_DIR now.

**Comment by shuyangzhou** [comment]
it does not do anything for support-xxx, actually no one really needs global lib dir anymore after this pull. However the global lib dir still exist due to the support-xxx. that's why I did not remove it in this pull. But it should not break anything, since no one really reads the content in global lib dir.

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 can you find the error log in the new result? I don't know how to search it in testray, thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 I found the log, but it seems very unreasonable.
So when it fails, this is the cause:
```
2021-05-04 23:51:32.182 ERROR [SoapConnectorThreadPool : 0][ModuleFrameworkAdapterHelper:127] Unable to load the module framework
java.lang.IllegalStateException: Missing /opt/dev/projects/github/liferay-portal/bundles/osgi/core
	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.getClassLoader(ModuleFrameworkAdapterHelper.java:64) ~[portal-impl.jar:?]
	at com.liferay.portal.module.framework.ModuleFrameworkAdapterHelper.<init>(ModuleFrameworkAdapterHelper.java:124) [portal-impl.jar:?]
	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.<clinit>(ModuleFrameworkUtilAdapter.java:145) [portal-impl.jar:?]
	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:261) [portal-impl.jar:?]
```

Somehow /opt/dev/projects/github/liferay-portal/bundles/osgi/core is not populated.

When it works, it is loading :
```
2021-05-05 00:53:03.936 ERROR [main][ModuleFrameworkAdapterHelper:103] #########ModuleFrameworkClassLoader urls : [file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.portal.app.license.api.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.portal.equinox.log.bridge.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.registry.impl.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.portal.bootstrap.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.portal.app.license.resolver.hook.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/org.eclipse.osgi.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.osgi.service.tracker.collections.jar, file:/opt/dev/projects/github/liferay-portal/bundles/osgi/core/com.liferay.jaxws.osgi.bridge.jar]
```
All those jars are there.

The major difference I can see is, the executing thread. When it fails, it is executed by ```SoapConnectorThreadPool``` not sure what that is, but for sure not our thread. When it works, it is executed by ```main``` thread which is from us.

Does this mean anything to you? And this is only happening on this pull, not on upstream, right?

**Pull request closed without merging**
