### PR TITLE
[Bug Fix]LPS-81754

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

We have classloader leaking when undeploying a module. The root cause is field with "@Reference" annotation will not be set to null if the target service is gone.

Two options to fix it:
1) set "unbind" explicitly to every filed with "@Reference", it does not matter what value we set, as long as it is not null, felix scr will invoke its update logic and set the filed to null
2) patch felix scr

I chose 2) because I think this should be a bug of felix, according to OSGi spec below, the field must be modified when unbinding the service, but felix scr does not modify the filed if you did not set unbind method explicitly.

> When using the field strategy, SCR must modify fields in the component instance at the appropriate
time. SCR must modify the fields on the following events:
>     bind - The field is modified to bind a new service to the component that matches the selection
criteria.
>     updated - For certain field types, the field is modified when the service properties of a bound ser-
vices are modified and the resulting properties do not cause the service to become unbound be-
cause it is no longer selected by the target property.
>     unbind - The field is modified when SCR needs to unbind the service.

Tina.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian should I wait for CI?

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou Yes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60937

**Pull request closed without merging**
