### PR TITLE
LPS-91970 DB column name

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for Ci result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
cc @Preston-Crary @epgarcia

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69536

**Pull request closed without merging**
