### PR TITLE
LPS-104901 Wait for CounterLocalService to be available since it's needed by ReleaseDAO

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@Preston-Crary why these must stay as bundle activators? After deferring the execution to wait for counter local service, it is not much different from SCR component on the lifecycle side. Can they just be changed to SCR components to simplify the dependency declaring?

**Comment by Preston-Crary** [comment]
@shuyangzhou, I think they need to run before upgrades since they rename the release.  I didn't move them because I'm not 100% sure it won't cause a new problem and this is a release blocker.  If you want I can resend or send a follow up change in a couple weeks as a separate ticket.

**Comment by shuyangzhou** [comment]
@Preston-Crary if they need to run early, adding the service tracker waiting will defer its execution. Won't that be a problem?

**Comment by Preston-Crary** [comment]
These had the service tracker before waiting on ModuleLifecycle, I guess we don't really know for sure if there'll be another problem for these either way - maybe we might as well clean them up.

**Comment by Preston-Crary** [comment]
I'll move these into their UpgradeStepRegistrators and resend. That's how all the other ones extending the base class are working,

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9418

**Pull request closed without merging**
