### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull includes the build process of sidecar and all functions of sidecar.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.5.1)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Will include sidecar zip into elasticsearch impl bundle
2.Warning logging on startup
[2020-01-14T11:22:29,405][WARN ][o.e.d.b.Bootstrap ] [liferay]future versions of Elasticsearch will require Java 11; your Java version from [/opt/java/jdk-8u222/jre] does not meet this requirement
Dumping log4j.properties into temp folder
3.Clean up the configuration file, remove unused properties
4. Shutdownhook may not work for some cases on windows.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by dantewang** [comment]
Fetched

**Comment by tinatian** [comment]
resend at https://github.com/shuyangzhou/liferay-portal/pull/8761

**Pull request closed without merging**
