### PR TITLE
LPS-72701 Fix EditorConfigContributor exceptions

### PR DESCRIPTION
**Pull request by Preston-Crary**
In a1e3970 I'm fixing two different problems, that's why it's two classes. One is for the EditorConfigContributors (FrontendEditorLangResourceBundleLoader) the other is for the SocialActivityInterpreters (LanguageExtender).

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

See this [loop post](https://loop.liferay.com/home/-/loop/feed/5474610) for more details.

**Comment by michaelhashimoto** [comment]
ci:retest

Sorry for any inconvenience.

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49222

**Pull request closed without merging**
