### PR TITLE
[Resource Action][7.4 only]LPS-117531 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

As https://issues.liferay.com/browse/COMMERCE-4874 has finished and there's no portlet 90 resource actions in Commerce. I mark 7.4-only in title because the Commerce changes are not backported.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevent

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevent

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
