### PR TITLE
LPS-64821 SF rename after parameter

### PR DESCRIPTION
**Pull request by csierra**
this is a fix for FP5 https://issues.liferay.com/browse/LPS-83798

and FP4 https://issues.liferay.com/browse/LPS-64821

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61938

**Pull request closed without merging**
