### PR TITLE
[Deprecation]LPS-106333

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82706

**Pull request closed without merging**
