### PR TITLE
LPS-145073 Unable to add data template script to the <head/> section …

### PR DESCRIPTION
**Pull request by ngriffin7a**
…of a portal page via HeaderResponse.addDepency(name,scope,version,xml)

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou FYI, this is a very simple, one-commit fix. 

cc @drewbrokke

**Comment by shuyangzhou** [comment]
@ngriffin7a can you update the unit test for this to make the intended logic clear?

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10525

**Pull request closed without merging**
