### PR TITLE
[Bug Fix]LPS-102853

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I had run full ci test on my branch with this fix and did not see the deadlock issue. Let's wait for ci test here to confirm it is fixed.

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me verify the test result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian possible failure here with Elasticsearch6 in a cluster. Going to run more search tests.

**Comment by vicnate5** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 is the search results clean?

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou Results look good. No issues.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80765

**Pull request closed without merging**
