### PR TITLE
LPS-68619

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Hey guys, @jonathanmccann @mbowerman @mtambara @holatuwol

This is such a big pull, please break it into smaller pieces. Otherwise I could never find a big chunk of time to review it.

And also, I will need a way to reproduce the slowness. Please get me some test data for this issue. And coordinate with @tomwang2011 to have it loaded on our test server in sybase db.

Thanks

**Comment by holatuwol** [comment]
@shuyangzhou, we didn't try to reproduce the problem out of box, but rather we used a customer database for it. However, this was done 8 months ago, so we no longer have the customer data for it due to data retention policies.

**Comment by shuyangzhou** [comment]
@holatuwol is it possible to fake some data for this problem?

**Comment by holatuwol** [comment]
@shuyangzhou, no harm in trying, though we don't know the data characteristics that raise this problem so we don't know how long it'll be before we have the right data. I've asked @mbowerman to try having a lot of pages and portlet preferences (user personal sites) and see if that alone is enough.

**Comment by shuyangzhou** [comment]
@holatuwol Although it would be nice to have it, but if it is not easy, no need to create a large amount of data to prove the slowness. But at least try to create enough data to make sure the modified code paths can be covered during the upgrade process. And please try to break down this pull into smaller pieces, that way I can make sure we are making some progress.

**Comment by shuyangzhou** [comment]
Closing old pulls, we can revisit if necessary

**Pull request closed without merging**
