### PR TITLE
LPS-81343 Portlet 3.0: Support deployment of CDI bean portlets

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains 1 commit that modifies PortletHotDeployListener.java with some loggers (and an early `return` if the new "com.liferay.beanPortletIds" ServletContext attribute is found), and PortletAutoDeployListener.java with one small change if a META-INF/beans.xml file is detected (CDI). Because of this, I can't see how any of these failures are related.

Please review when you get an opportunity. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61227

**Pull request closed without merging**
