### PR TITLE
LPS-71745 Apply UnsafeConsumer and add CI test

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:retest

**Comment by tomwang2011** [comment]
ci:reopen I don't think the mail server failure is caused by this pull, thanks

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:stop
You are right, that's not related.
See https://github.com/brianchandotcom/liferay-portal/pull/49625

**Pull request closed without merging**
