### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a compile failures, please fix and resend, thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou Already done, see: https://github.com/shuyangzhou/liferay-portal-ee/pull/389
Because of the system-wide scope of the change from portlet-api-2.0 to portlet-api-3.0.0 I am expecting these types of failures. I'll take care of them one-at-a-time until they are all fixed.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6064

**Pull request closed without merging**
