### PR TITLE
Commerce 2475 Dispatch framework

### PR DESCRIPTION
**Pull request by matijapetanjek**
@shuyangzhou In agreement with @igorbeslic I have renamed and extracted ScheduledTaskExecutor to _executor_ package if that is not ok please let us know. Thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by jpince** [comment]
@matijapetanjek in the future, the process will go faster if you run both `ci:test:sf` and `ci:test:relevant` in your pulls to Shuyang.

**Comment by matijapetanjek** [comment]
@jpince  Got it!

**Comment by jpince** [comment]
@matijapetanjek upgrade test failures
```
 [parallel] You must first upgrade the portal to the required schema version 8.18.0
 [parallel] 22:33:06,451 ERROR [main][MainServlet:299] java.lang.RuntimeException: You must first upgrade the portal to the required schema version 8.18.0
 [parallel] java.lang.RuntimeException: You must first upgrade the portal to the required schema version 8.18.0
```
You can contact Alberto Chaparro or devs on other product teams for help with this.

**Comment by jpince** [comment]
I think you can ignore the other failures, caused by Brian Chan publishing

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
