### PR TITLE
[MessageBus]LPS-102995

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me verify the result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian This looks good with one note.

Unique failure with Post-upgrade, from 6.2, Oracle DB
`ORA-00001: unique constraint (LPORTAL.IX_A9FF4B2C) violated`
https://testray.liferay.com/reports/production/logs/test-1-18/1573795063285/test-portal-acceptance-pullrequest(master)/2420/functional-upgrade-tomcat90-oracle122-jdk8/0/0/liferay-log.txt.gz

Does not look related to these changes, but wanted to note since I don't see this other places.

**Comment by tinatian** [comment]
I do not think this is related to my changes either. Let's run ci again to see if this is random.

Tina.

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please verify the result again? I take a quick look, and did not see the error you listed above.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian New run is clean

**Comment by shuyangzhou** [comment]
@tinatian please rebase and resend.

**Pull request closed without merging**
