### PR TITLE
Startup optimization 142 language resources cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Unit tests failures here. I can reproduce locally.
https://testray.liferay.com/home/-/testray/case_results/2152696021
https://testray.liferay.com/home/-/testray/case_results/2152696115
https://testray.liferay.com/home/-/testray/case_results/2152696075
https://testray.liferay.com/home/-/testray/case_results/2152696054

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10905

**Pull request closed without merging**
