### PR TITLE
Ext plugins removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results. Please ignore the sf issue, I will take care of it.

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
Still waiting for Testray import of the default test suite results (asked CI team about it since it is taking so long), there is one unique failure on the relevant results, but it might be unrelated, running `stable` to confirm.

**Comment by vicnate5** [comment]
@shuyangzhou Just need to see the new results for the licensing test, but no other issues found.

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109612

**Pull request closed without merging**
