### PR TITLE
LPS-100436,LPS-99915

### PR DESCRIPTION
**Pull request by Preston-Crary**
The test in 324f15daa9f346b1af6db8fc496bbbe1c72cea71 won't pass without the changes in https://github.com/shuyangzhou/liferay-portal/pull/8216

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Fixed generated service interface to match the CTService transaction rollback from exception -> throwable.

**Comment by Preston-Crary** [comment]
Rebase on LPS-97125.

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/78485

**Pull request closed without merging**
