### PR TITLE
LPS-57979

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @shuyangzhou 

Sending this to you first, as I'd like you to double check some changes SF is making in your files.
I usually break stuff whenever I touch your files, so I assume that's the case this time as well...

The classes you might want to double check:
IntrabandProxyUtilTest
SelectorIntrabandTest
FileServerTestUtil

**Comment by shuyangzhou** [comment]
@hhuijser The only exception case is IntrabandProxyUtilTest, can we ignore this one? Everyone else is correct.

**Comment by hhuijser** [comment]
Yah, I'll add exception and resend

**Comment by hhuijser** [comment]
Hey @juliocamarero 

Can you have a look at this and let us know if it looks okay to you?
It's an issue that is 6.2 specific.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/29422

**Pull request closed without merging**
