### PR TITLE
Startup optimization 318 elasticsearch search engine activation 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
@shuyangzhou  Issue found: Component System Checker failure with property "index.on.startup=true".

Steps to reproduce:
1. Start Portal, make sure the property "index.on.startup" is not set.
2. Add a new Web Content, Blog Entry, Document and a page with Asset Publisher portlet.
3. Execute curl command:
`curl -X POST -H 'Content-Type: application/json' -d '{"query": {"match": {"_type": "_doc"}}}' http://localhost:9201/liferay-20095/_delete_by_query?pretty`
4. Shut down portal.
5. Add property "index.on.startup=true" to portal-ext.properties.
6. Start portal again.

Actual Results:
WARN in portal console:
```
23-10-17 04:52:07.544 WARN  [main][DependencyManagerSyncUtil:73] Spring Extender Unavailable Component System Checker check result: 
Bundle {id: 329, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
	Component with ID 0 is unavailable due to missing required dependencies:
		service dependency [com.liferay.portal.kernel.service.persistence.change.tracking.helper.CTPersistenceHelper]
```
Sometimes I also got Declarative Service Unsatisfied Component System Checker check failures like below:
```
2023-10-17 05:34:55.917 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component System Checker check result: 
Bundle {id: 91, name: com.liferay.portal.workflow.kaleo.runtime.scripting.impl, version: 5.0.19}
	Declarative Service {id: 31, name: com.liferay.portal.workflow.kaleo.runtime.scripting.internal.notification.recipient.script.GroovyNotificationRecipientEvaluator, unsatisfied references: 
		{name: _kaleoScriptingEvaluator, target: null}
	}
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142614

**Pull request closed without merging**
