### PR TITLE
[TECHNICAL SUPPORT] LPS-70046 6.2 to DXP upgrade: com.liferay.portal.verify.VerifyPermission.fixUserDefaultRolePermissionsMySQL is very slow

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-70046

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@preston-crary please take this over, thanks!

**Comment by Preston-Crary** [comment]
Hi @NorbertKocsis,

this looks wrong, ResourcePermission.primKey like '%_LAYOUT_%' is not the same as ResourcePermission.primKey like replace('[$PLID$]_LAYOUT_%', '[$PLID$]', cast_text(Layout.plid)).  The inner join has to be on the plid.

Why did you add an index on the primKeyId when it's not used in the update?

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4727

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
