### PR TITLE
[FinderCache]LPS-121770

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 The unique failures seem to be unrelated to this pull, could you please confirm?

Thanks.
Tina.

**Comment by tinatian** [comment]
Wrong ticket number, resend at https://github.com/shuyangzhou/liferay-portal/pull/9482

**Pull request closed without merging**
