### PR TITLE
Db apply max string index length limitation

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou 

**Unique failures**

Sybase DB test https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/360705/AXIS_VARIABLE=1,label_exp=!master/testReport/junit/com.liferay.portal.dao.db/SybaseDBTest/testApplyMaxStringIndexLengthLimitation/

archives modules smoke
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/227654/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84574

**Pull request closed without merging**
