### PR TITLE
LPS-X Avoid creating release for service bundle. Service bundle's rel…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ease entry is created when InitialUpgradeStep is executed.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/achaparro/liferay-portal/pull/1064

**Pull request closed without merging**
