### PR TITLE
[Deprecation]LPS-106325

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Though this is deprecation is set as of 7.2, but we are sure that no one is using it since beginning, then we remove all of it, see more here : https://issues.liferay.com/browse/LPS-97774.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai will fix compile and resend.

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Sorry, closed the wrong pull..

**Comment by dantewang** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
One unique Poshi failure: https://testray.liferay.com/home/-/testray/case_results/931917302?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D931868866%26testrayRunId%3D931868869%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc
see exception thrown, but possibly a fluke since we are removing deprecated clustering methods

**Comment by dantewang** [comment]
This failure doesn't seem to be related. The errors are either from DB connection pool or ES. Removal of ClusterGroup should not affect these.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82660

**Pull request closed without merging**
