### PR TITLE
[Log4j]LPS-127067

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Just starting reviewing.

**Comment by zhangyan0701** [comment]
No related failures.

Most are happening on upsteam as well, others are flaky or Jenking issue.

**Comment by shuyangzhou** [comment]
@tinatian this will invalid the PrintableLoggingEvent logic, in case of failures, we are now printing a list of the new LogEvent, not the original PrintableLoggingEvent. Please fix and resend.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9814

**Pull request closed without merging**
