### PR TITLE
[Deprecation]LPS-103951 portal kernel part 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please scan the result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Test results look good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81091

**Pull request closed without merging**
