### PR TITLE
[multi company startup tuning]LPS-135489

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Tina

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian No regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10165

**Pull request closed without merging**
