### PR TITLE
LPS-84543 Improve performance of ContextController.visibleContextHelper()

### PR DESCRIPTION
**Pull request by Preston-Crary**
See https://github.com/shuyangzhou/rt.equinox.bundles/pull/21

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62293

**Pull request closed without merging**
