### PR TITLE
[Bug Fix] LPS-130140 Fix ERROR: duplicate key value violates unique constraint

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-130140 Fix ERROR: duplicate key value violates unique constraint "ix_4f0315b8" when deploying a Service Build with a new buildNumber in a cluster with more than one node

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9936

**Pull request closed without merging**
