### PR TITLE
LPS-X Optimize AopInvocationHandler concurrency

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results once they are in, thanks!

**Comment by zhangyan0701** [comment]
Issue in AopCacheManagerTest:
```
    [junit] Testcase: testConcurrentRegistrationAndInvocations(com.liferay.portal.spring.aop.AopCacheManagerTest):	Caused an ERROR
    [junit] java.lang.AssertionError: [com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice3@33c773a7, com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice4@5c182cfe, com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice6@262aa879, com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice6@4d99f5a5, com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice6@293f9f6c, com.liferay.portal.spring.aop.AopCacheManagerTest$TestChainableMethodAdvice8@64886f3b]
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3763/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142244

**Pull request closed without merging**
