### PR TITLE
Lps 162507

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Passed local testing.

**Tests ran:**
PortalSmokeUpgrade#ViewPortalSmokeArchive7413
PortalContinuousUpgrade#AutoUpgradeFromLatest7413Update - U42 baseline
PortalContinuousUpgrade#AutoUpgradeFromLatest7413Update - U30 baseline (Covers https://issues.liferay.com/browse/LPS-163271)

Manually confirmed that `com.liferay.client.extension.service` schemaVersion is at `3.5.0` after upgrades.

If relevant passes we should push this forward since it is a blocker. We can check the full upgrade suite results after. 

@zhangyan0701 can you watch the results?

**Comment by zhangyan0701** [comment]
No regressions found in relevant and upgrade test suites.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123709

**Pull request closed without merging**
