### PR TITLE
spring 4.1.19 test

### PR DESCRIPTION
**Pull request by kenjiheigel**
@shuyangzhou, this is the update that @david-truong made yesterday for the Spring 4.1.19 update. It needs to run on JDK8 to avoid compile issues.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@dantewang @slnn, this is high priority, we need a full performance regression against this pull on all test cases.

Send me updates one by one once you get them. Try to get it done by the end of the day your time.

Thanks!

**Comment by shuyangzhou** [comment]
@michaelhashimoto CI is not picking up this pull. Is it just because it is under load?

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@david-truong @Ithildir please fix the compile failure. I am out of office this afternoon. @brianchandotcom wants the benchmark results asap, @dantewang won't be able to run it until it compiles at least.

**Comment by Ithildir** [comment]
Don't we need a JDK8 on CI in order to compile the modules with this compatibility? https://github.com/shuyangzhou/liferay-portal/pull/2738/commits/61834795691ddcc8f3e6852dfa4a99aba1334bb4#diff-89e7d247cc0f5793c63a4c97fd643cbaR42

**Comment by kenjiheigel** [comment]
@Ithildir, yeah we do. I'm going to make some updates so the functional tests will run, but we can anticipate having to change everything over to JDK8.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
I think this should allow the tests in the PR tester to run without compile errors.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
There's some issues with the functional tests. It looks like the integration/unit tests are running though, but there's compile errors for the tests:

```jar:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/portal-kernel/test-results/unit
     [copy] Copying 3 files to /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [javac] Compiling 166 source files to /opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit
    [javac] /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/security/SecureRandomUtilTest.java:100: error: reference to assertEquals is ambiguous
    [javac] 		Assert.assertEquals(
    [javac] 		      ^
    [javac]   both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
    [javac] /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/util/StringBundlerTest.java:754: error: reference to assertEquals is ambiguous
    [javac] 			Assert.assertEquals(
    [javac] 			      ^
    [javac]   both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
    [javac] /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/util/StringBundlerTest.java:837: error: reference to assertEquals is ambiguous
    [javac] 			Assert.assertEquals(
    [javac] 			      ^
    [javac]   both method assertEquals(Object,Object) in Assert and method assertEquals(long,long) in Assert match
    [javac] Note: /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/process/local/LocalProcessExecutorTest.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
     [echo] env.TEST_BATCH_NAME = portal-web-jdk8
```

I would suggest fetching my branch, fixing the compile errors, then resend it somewhere to test with CI.

**Comment by slnn** [comment]
On this PR, error appeared on portal side when portal startup with JDK8, and portal can not visit by browser . please see the error log here : https://mega.nz/#F!VkFwyJpC!pHeHEvPXLuX-6ZDL2pr6tQ

**Pull request closed without merging**
