### PR TITLE
[Bug Fix]LPS-86852

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I upgraded the version we used for scr to fix some bugs, to make sure everything is fine, let's wait for a full ci test result.

cc @danielreuther

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@lanceji92674957 please verify the bootup performance for this change.

**Comment by lanceji92674957** [comment]
Today's baseline: 
ave time: 42.5758, stand deviation: 324.7894361

with this pull: 
ave time: 42.243375, stand deviation:523.9443639

CC @shuyangzhou @tinatian

Thanks
Lance

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/65318

**Pull request closed without merging**
