### PR TITLE
LPS-100525 CTTableMapper

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
@Preston-Crary 1 more

DB2
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/299767/AXIS_VARIABLE=33,label_exp=!master/testReport/junit/com.liferay.portal.upgrade.test/UpgradeCTModelTest/testUpgradeCTModel/

**Comment by Preston-Crary** [comment]
@vicnate5 thanks!

**Comment by vicnate5** [comment]
@Preston-Crary Also affects upgrades on DB2
https://testray.liferay.com/reports/production/logs/test-1-10/1579287359493/test-portal-acceptance-pullrequest(master)/2587/functional-upgrade-tomcat90-db2111-jdk8/3/0/jenkins-console.txt.gz

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8749

**Pull request closed without merging**
