### PR TITLE
LPS-X Shortcut for SYSTEM company and DEFAULT user.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:publications

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results once it is in, thanks!

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@shuyangzhou no unique failures

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142282

**Pull request closed without merging**
