### PR TITLE
LPS-84130 ServletContextClassLoaderPool

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for CI result.

Thanks
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou @dantewang 
The random failure on ci caused by this issue: https://issues.liferay.com/browse/LPS-87102
Already sent a pull (https://github.com/gamerson/liferay-portal/pull/235) to @gamerson to verify if my fix is OK, will resend this pull after that is merged.

Tina.

**Comment by tinatian** [comment]
@dantewang could you please rebase my change and send Shuyang a pull? Please remember to trigger ci test to verify everything is ok.

Thanks!
Tina

**Comment by dantewang** [comment]
Got it.

Tina Tian <notifications@github.com> 于 2018年11月15日周四 13:42写道：

**Comment by dantewang** [comment]
Sent to https://github.com/shuyangzhou/liferay-portal/pull/7046

**Pull request closed without merging**
