### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
I did not include the clean up of current embedded impl into this pull, only disabled EmbeddedElasticsearchConnection, will send out the clean up logic in later pulls.

If you think this pull is too big, you can ignore the commit with prefix portal-search-elasticsearch7-impl: clustering.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder
2.Clean up of embedded impl (will send in another pull)
3.Random java.lang.InterruptedException on shutdown (https://github.com/shuyangzhou/liferay-portal/pull/8794)
4.circuit-breaker issue shown on ci test ( LPS-104802)
5. Dxp modules are not working when cluster is enabled, see `test case 2b` here https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit#gid=1206555946
6. Random exception according to upgrade test case on ci, see `Test Case 6a` on https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit#gid=1206555946.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by dantewang** [comment]
Fetched

**Comment by xbrianlee** [comment]
ci:test:search:norebase

**Comment by tinatian** [comment]
Fix dxp bundles issue, and resend at https://github.com/shuyangzhou/liferay-portal/pull/8825.


Tina.

**Pull request closed without merging**
