### PR TITLE
Startup optimization 246 service registry read write lock

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
No additional issues here beyond https://github.com/shuyangzhou/liferay-portal/pull/11083#issuecomment-1569360155

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/11090 with more changes

**Pull request closed without merging**
