### PR TITLE
Startup optimization 242 initial upgrade step 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results. This pull has one more change on top of https://github.com/shuyangzhou/liferay-portal/pull/11080 . If this pull is clean, no need to look into the other, otherwise please check the other one too, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression with one of the update databases:

Steps to Reproduce:
1. Import [7.1.3 dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.1.3/data-archive/data-archive-portal-mysql.zip) into MySQL
2. Run upgrade tool
3. Start portal

Result:
```
WARN  [main][QuartzSchedulerEngine:671] Scheduler job com.liferay.portal.security.ldap.internal.scheduler.UserImportSchedulerJobConfiguration.com.liferay.portal.security.ldap.internal.scheduler.UserImportSchedulerJobConfiguration already exists
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'com.liferay.portal.security.ldap.internal.scheduler.UserImportSchedulerJobConfiguration.com.liferay.portal.security.ldap.internal.scheduler.UserImportSchedulerJobConfiguration', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:277) ~[bundleFile:?]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:249) ~[bundleFile:?]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:840) ~[bundleFile:?]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:250) ~[bundleFile:?]
	at com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine.schedule(QuartzSchedulerEngine.java:667) [bundleFile:?]
	at com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine.schedule(QuartzSchedulerEngine.java:343) [bundleFile:?]
	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl.schedule(SchedulerEngineHelperImpl.java:293) [bundleFile:?]
	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationServiceTrackerCustomizer.addingService(SchedulerEngineHelperImpl.java:584) [bundleFile:?]
	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationServiceTrackerCustomizer.addingService(SchedulerEngineHelperImpl.java:550) [bundleFile:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264) [org.eclipse.osgi.jar:?]
	at com.liferay.osgi.util.ServiceTrackerFactory.open(ServiceTrackerFactory.java:104) [bundleFile:?]
	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl.activate(SchedulerEngineHelperImpl.java:368) [bundleFile:?]
```
CI full log https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/9458/functional-upgrade-tomcat90-mariadb102-jdk8/0/20/jenkins-console.txt.gz

I reproduced this locally, though this might be a race, because it does not always happen on CI.
Here is a passing result: https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/9458/functional-upgrade-tomcat90-mysql57-jdk8/1/21/jenkins-console.txt.gz

Not seen on https://github.com/shuyangzhou/liferay-portal/pull/11080, but since it isn't consistent, would need to re-run the tests multiple times to confirm.

**Comment by shuyangzhou** [comment]
@tinatian can you look into this? It does not really make sense unless there is a duplicated UserImportSchedulerJobConfiguration.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
Still seeing a race condition on the 6.2.10 multi-company dump, not sure if it is related to the one you are trying to fix here.

Example on PostgreSQL
```
   [java] 2023-05-31 19:02:13.200 INFO  [main][UpgradeProcess:145] Failed upgrade process com.liferay.portal.upgrade.v7_4_x.UpgradeCompanyId in 19 ms
     [java] 2023-05-31 19:02:13.200 INFO  [main][PortalUpgradeProcess:190] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 2099 ms
     [java] 2023-05-31 19:02:13.201 ERROR [main][DBUpgrader:79] null
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: aggregate functions are not allowed in UPDATE
     [java]   Position: 54
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.upgrade(PortalUpgradeProcess.java:184) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:181) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:157) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:145) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgradePortal(DBUpgrader.java:277) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:151) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: aggregate functions are not allowed in UPDATE
     [java]   Position: 54
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:136) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:154) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.doUpgrade(PortalUpgradeProcess.java:205) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.upgrade(PortalUpgradeProcess.java:179) ~[portal-impl.jar:?]
     [java] 	... 10 more
     [java] Caused by: org.postgresql.util.PSQLException: ERROR: aggregate functions are not allowed in UPDATE
     [java]   Position: 54
     [java] 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) ~[postgresql.jar:42.4.3]
     [java] 	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:268) ~[postgresql.jar:42.4.3]
     [java] 	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[hikaricp.jar:?]
     [java] 	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[hikaricp.jar:?]
     [java] 	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:473) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:439) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.runSQL(BaseDBProcess.java:87) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.BaseCompanyIdUpgradeProcess$TableUpdater.update(BaseCompanyIdUpgradeProcess.java:85) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.BaseCompanyIdUpgradeProcess._addCompanyIdColumn(BaseCompanyIdUpgradeProcess.java:148) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.BaseCompanyIdUpgradeProcess.lambda$doUpgrade$0(BaseCompanyIdUpgradeProcess.java:48) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.lambda$_processConcurrently$4(BaseDBProcess.java:587) ~[portal-kernel.jar:?]
     [java] 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) ~[?:1.8.0_121]
     [java] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_121]
     [java] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_121]
     [java] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_121]
     [java] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_121]
     [java] 2023-05-31 19:02:13.208 INFO  [main][UpgradeRecorder:162] Major upgrade finished with result failure
```
In the log the error happens, but then the test re-runs and the error does not occur again
https://testray.liferay.com/reports/production/logs/2023-05/test-1-39/test-portal-acceptance-pullrequest(master)/5025/functional-upgrade-tomcat90-postgresql144-jdk8/1/5/jenkins-console.txt.gz

Here is the PSQL dump 
https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-virtual-instances-postgresql.zip

[Import instructions](https://liferay.atlassian.net/wiki/spaces/QA/pages/2168031601/PostgreSQL+Database)

**Comment by vicnate5** [comment]
No other issues found in results.

**Comment by shuyangzhou** [comment]
I don't think this is related to this pull, it seems like a very specific psql error, even it is a race somehow. I am forwarding this to Alberto, let him check this.

**Comment by shuyangzhou** [comment]
See https://github.com/achaparro/liferay-portal/pull/1057

**Pull request closed without merging**
