### PR TITLE
Lps 53070

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
EhcacheConfigurationUtilTest is breaking, make sure you run the whole set of unit tests.

**Comment by tinatian** [comment]
I did run all the unit tests, some tests failed, but I was sure it was not caused by this change.

I just rerun EhcacheConfigurationUtilTest, it worked. Do you have any error log about it? Which version of master do you merge it to?

**Comment by shuyangzhou** [comment]
test-class:
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/trunks/git/liferay-portal/ivy-settings.xml
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/system.properties
    [junit] Running com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest
    [junit] Testsuite: com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/git/liferay-portal/portal-impl/test-classes/unit/portal-test-ext.properties
    [junit] 
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil is not fully covered.
    [junit] [Cobertura]Branch coverage rate : 0.91, line coverage rate : 0.97.
    [junit] [Cobertura]Please rerun test with -Djunit.code.coverage=true to see coverage report.
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil line 132 is not covered 
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil line 138 is not covered 
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil line 148 is not covered 
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil line 150 is not covered 
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil line 172 is not covered 
    [junit] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.717 sec
    [junit] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.717 sec
    [junit] 
    [junit] Testcase: com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest:	Caused an ERROR
    [junit] null
    [junit] java.lang.reflect.InvocationTargetException
    [junit] 	at com.liferay.portal.kernel.test.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:72)
    [junit] 	at com.liferay.portal.kernel.test.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:36)
    [junit] 	at com.liferay.portal.kernel.test.BaseTestRule$1.evaluate(BaseTestRule.java:58)
    [junit] Caused by: java.lang.AssertionError: com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil is not fully covered
    [junit] 	at com.liferay.cobertura.instrument.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:318)
    [junit] 	at com.liferay.cobertura.instrument.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:59)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest FAILED

**Comment by shuyangzhou** [comment]
All unit tests should pass on clean master.

**Comment by tinatian** [comment]
I still can not reproduce it.

I updated to current master, run "ant all", and then "ant test-unit", EhcacheConfigurationUtilTest passed.

See my log below. Compared with yours, it seems you are using "portal-test-ext.properties", do you have any config might cuase this?


test-class:
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/trunks/liferay-portal/ivy-settings.xml
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/system.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/system-ext.properties
    [junit] Running com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest
    [junit] Testsuite: com.liferay.portal.cache.ehcache.EhcacheConfigurationUtilTest
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/classes/portal-ext.properties
    [junit] Loading file:/home/trunks/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] [Cobertura] com.liferay.portal.cache.ehcache.EhcacheConfigurationUtil is fully covered.
    [junit] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.018 sec
    [junit] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.018 sec
    [junit] 

BUILD SUCCESSFUL
Total time: 10 seconds

**Comment by shuyangzhou** [comment]
Ugh, I have cluster.link.enabled=true in my portal-ext.

I thought in all cluster tests you are using advice to control on/off switch, nothing should depend on properties.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/23577

**Comment by tinatian** [comment]
Oh, I see. I am using "cluster.link.enabled=false" as default value. I will improve it in this round cluster unit tests refactoring.

**Pull request closed without merging**
