### PR TITLE
Pdf box extraction

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:document

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:document

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check this pull too, it is built on top of https://github.com/shuyangzhou/liferay-portal/pull/10586, should be treated the same, plus all additional tests for tika, if there is any.

**Comment by vicnate5** [comment]
ci:test:depot

**Comment by vicnate5** [comment]
ci:test:depot:norebase

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:stable:norebase

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic:norebase

**Comment by vicnate5** [comment]
@shuyangzhou There is a tika/pdfbox startup error logged in one of the lpkg tests
```
 [parallel] Caused by: java.lang.NoClassDefFoundError: org/apache/pdfbox/pdmodel/fixup/PDDocumentFixup
 [parallel] 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
 [parallel] 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
 [parallel] 	at org.apache.tika.config.ServiceLoader.getServiceClass(ServiceLoader.java:235) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig$XmlLoader.loadOne(TikaConfig.java:628) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig$XmlLoader.loadOverall(TikaConfig.java:589) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:198) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:182) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:157) ~[?:?]
 [parallel] 	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:153) ~[?:?]
 [parallel] 	at com.liferay.portal.tika.internal.util.TikaConfigUtil.<clinit>(TikaConfigUtil.java:33) ~[?:?]
 [parallel] 	at com.liferay.portal.tika.internal.metadata.TikaRawMetadataProcessor.<init>(TikaRawMetadataProcessor.java:91) ~[?:?]
 [parallel] 	... 247 more
 [parallel] Caused by: java.lang.ClassNotFoundException: org.apache.pdfbox.pdmodel.fixup.PDDocumentFixup cannot be found by com.liferay.portal.tika_1.0.6
 ```
https://testray.liferay.com/reports/production/logs/2022-03/test-1-36/test-portal-acceptance-pullrequest(master)/657/release-osgi-state-lpkg-test-jdk8/0/0/jenkins-console.txt.gz

I compiled this branch and ran the test locally multiple times and was not able to reproduce. I am re-running on CI.

I noticed that the test is incorrectly using MySQL 5.6 on CI, but it is using that upstream too and passing. [Passing log for compare](https://testray.liferay.com/reports/production/logs/2022-03/test-1-1/test-portal-acceptance-upstream-dxp(master)/3029/release-osgi-state-lpkg-test-jdk8/0/0/jenkins-console.txt.gz)

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@shuyangzhou This looks good now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114745

**Pull request closed without merging**
