### PR TITLE
[TS] LPS-127840 | Sitemap does not contain page names

### PR DESCRIPTION
**Pull request by attilabakay**
Hi @shuyangzhou,

I checked again and I can reproduce the expected results. I slightly modified the reproduction steps the make it easier to reproduce. The two main changes are that I created a new step to log out as the canonical URL-s are only generated for guest users and added another page to the site. This was required in the case the test was done on a new site as in that case the page1 will be the first layout (home layout which does not contain the layoutFriendlyURL in the canonical URL. 
https://issues.liferay.com/browse/LPS-127840
Thank you and best regards,
Attila
previous pull request:  #9815

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
@vicnate5 Could you double check it?
thanks in advance.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@bakayattila with the new steps I am able to get to the expected result without the fix in this pull. There must be something got mixed up. @vicnate5 please check it on your side, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou I was able to reproduce the issue in the current description of https://issues.liferay.com/browse/LPS-127840 at head on master (built yesterday afternoon)

I also confirmed that the issue is no longer reproducible using the CI build for this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9820

**Pull request closed without merging**
