### PR TITLE
LPS-94003 Upgrade to version 5.2.2.RELEASE of the Spring Framework

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou Per your request, I rebased this branch and only had to fix one small thing in the build.gradle file in the "FAKE GRADLE CACHE" top (most recent) commit. So I don't think it needs to go through the full CI testing again. It should be good for final review by you and/or merge by bchan.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@ngriffin7a can you show me which test is failing on this https://github.com/shuyangzhou/liferay-portal/pull/8698/commits/6355d1ffb49e5b3983da03cb3b9873b2bf02aeb1 ?

**Comment by ngriffin7a** [comment]
@shuyangzhou This commit was authored a long time ago, so I can't remember the exact JUnit test that was failing. However I think it is associated with the use-case of a "skinny" Spring-WAR.

Background: Historically, if a WAR based module wants to use the Spring Framework for IoC, it must include all of the Spring jars (spring-beans.jar, spring-context.jar, etc) in WEB-INF lib (fat Spring WAR).

In the future, we want to make it possible for WAR-based modules to use the Spring Framework that is included with Liferay's global classpath.

The commits in the branch associated with this pull request upgrades Liferay's global classpath from Spring Framework 4.3.x to Spring Framework 5.2.x.

In the near future, we want to make our modules/sdk/project-templates/project-templates-spring-mvc-portlet be able to support both "fat" and "skinny" Spring-based WARs. Since PortletMVC4Spring (our new fork of Spring Portlet MVC) is based on Spring Framework 5.2, our project-templates-spring-mvc-portlet "skinny" option would be able to rely on the Spring Framework provided by Liferay's global classpath.

As I recall, when I was prototyping the project-templates-spring-mvc-portlet "skinny" option for PortletMVC4Spring, there was a JUnit test that was executing in CI (testing to make sure that we could generate a skinny Spring WAR) that had a JUnit test that was failing silently. Again, I can't remember which one. Hope that's good enough to answer your question.

**Comment by shuyangzhou** [comment]
Is it an unit within our test suite? If so, please just take off this commit and let CI run without it. I need to see the issue.

**Comment by ngriffin7a** [comment]
@shuyangzhou Feel free to revert the commit in your review. I can't show you the failing test at this time because "skinny" Spring WARs are not yet supported. @rotty3000 and I need to do more work in order to support that feature. I can include this commit in a future PR when the "skinny" Spring WAR is supported.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82902

I removed that commit.

**Pull request closed without merging**
