### PR TITLE
Lps 53537 As a developer, I would like to make the default value of replicatePutsViaCopy same for both RMI replicator and cluster replicator

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Hmm, I am confused, you said before your change, the RMI one was default to true for replicatePutsViaCopy and ClusterLink one was default to false.

I don't see that. They are all default to false. The properties reading logic are identical in ClusterLinkCacheReplicator and EhcachePortalCacheClusterReplicator's constructors before your change.

Please point out which part you meant that is causing the inconsistent behavior.

**Comment by tinatian** [comment]
Both ClusterLinkCacheReplicator and EhcachePortalCacheClusterReplicator are using cluster link to do replication, they are both set to false by default. The RMI one is from ehcache and set to true by default, it is generated by :
ehcache.cache.event.listener.factory=net.sf.ehcache.distribution.RMICacheReplicatorFactory

You might be wondering if we have two replicator using cluster link, in fact, we only need one, but since there is some legacy code depends on EhcachePortalCacheClusterReplicator, so I have to keep it.

Since we can not change the logic of RMI one, so I make all the properties extract logic consistent with RMI one, which is if you do not set it, it would be true by default. And then to make our ehcache config it as false by default, I modified the configuration file.


Tina.

**Comment by shuyangzhou** [comment]
Who is using the EhcachePortalCacheClusterReplicator? Why can not we remove it for 7?

And for the RMICacheReplicatorFactory, we should be able to subclass it to "fix" its default value behavior, right? That will be easier comparing to massively changing settings in configurable files.

**Comment by shuyangzhou** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/24068, make sure your following changes are on top of that, so that at least we can avoid the annoying _extractPropertyValue() method.

**Comment by tinatian** [comment]
EhcachePortalCacheClusterReplicator is used by hibernate's second level cache, which is using ehcache. While I was refactoring cache, I asked if we can remove the support of this since we disable the second level cache of hibernate by default, while Micheal said we should keep it.

Yes, we can wrap RMICacheReplicatorFactory to fix it, that would be cleaner. Will do it soon.

**Comment by shuyangzhou** [comment]
ok, then let's keep EhcachePortalCacheClusterReplicator, but is that possible to delegate the logic to ClusterLinkCacheReplicator? They are just too similar, not a good thing to actually having 2 pieces of almost identical logic.

**Comment by tinatian** [comment]
That's true. I will see what I can do. Will send you pull request later.

**Pull request closed without merging**
