### PR TITLE
LPS-135245_master

### PR DESCRIPTION
**Pull request by davidtellolr**
Make sync-asynchronous mode in index write operations configurable.

After analyzing the changes made in the index operations from an asynchronous to the synchronous mode in [PTR-2496](https://issues.liferay.com/browse/PTR-2496), it was decided to make this behavior configurable by a portal property. 

The changes in the index write operations were made in:

- LPS-127843 (Flip IndexableAdvice to do sync indexing by default, and add a manual switch to allow override. ) already released in 7.3 FP1
- LPS-130001 (Change the default value of ProxyModeThreadLocal#forceSync to TRUE) committed to 7.3.x but not released yet in an FP1

En master, by default, we selected the synchronous mode, but, as Tibor Lipusz told in the [PTR](https://issues.liferay.com/browse/PTR-2496), this selection could be changed during the PR review.
To add the new portal.property, I added a new section too (Proxy Thread). After a research of the existing sections, I didn't find any appropriated for the new property. I Thought in the "Search" section but the changes made in this LPS effect to other components, not only to Search. You can check that by executing the following:

```
git grep -lw ProxyModeThreadLocal.isForceSync
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/IndexWriterHelperImpl.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/buffer/IndexerRequest.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/index/UpdateDocumentIndexWriterImpl.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/reindexer/ReindexerImpl.java
portal-impl/src/com/liferay/portal/messaging/proxy/MultiDestinationMessagingProxyInvocationHandler.java
portal-kernel/src/com/liferay/portal/kernel/messaging/proxy/MessagingProxyInvocationHandler.java
portal-kernel/src/com/liferay/portal/kernel/messaging/proxy/ProxyModeThreadLocalCloseable.java

```
As you can see, MultiDestinationMessagingProxyInvocationHandler and MessagingProxyInvocationHandler are also implicated. If you think that a new section is no necesary, please let me know.

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:sf:norebase

**Comment by davidtellolr** [comment]
ci:test:stable

**Comment by davidtellolr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@davidtellolr this is against the original goal of the change. When @drewbrokke made the change, the original requirement is, we are forcing sync by default. Only open exceptions by code via tangling the thread local flag to make certain use cases async. For all sync or async is fixed by design, not via configuration. This kind of global configuration is not easy to be covered by CI. Please talk to @drewbrokke for more details.

**Comment by davidtellolr** [comment]
Hi @shuyangzhou ,

In the [PTR](https://issues.liferay.com/browse/PTR-2496) which produced this change, Tibor, Jorge Diaz and @drewbrokke were talking about the change. In a @drewbrokke message, he gave us the idea of making the behavior configurable. He wrote the following:

"Perhaps a solution for this would be to make the default behavior configurable, so that the customer can determine for themselves which scenario they prefer."

I'll ask @drewbrokke if we must discard this change.

Thanks!

Regards,

**Pull request closed without merging**
