### PR TITLE
LPS-74899 Convert to a file to remove leading slash on Windows. Cause…

### PR DESCRIPTION
**Pull request by mtambara**
…d by 9f00c707171becedac884a2664787d99ef4c2786

### CODE REVIEW

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:retest

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/51847

**Pull request closed without merging**
