### PR TITLE
[TS] LPS-140788

### PR DESCRIPTION
**Pull request by jonathanmccann**
Here the portlet name is escaped and changes from "my-greeter-portlet" to "mygreeterportlet" - https://github.com/jonathanmccann/liferay-portal/blob/d256407d149e064caba35369e820036a95039502/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-tracker/src/main/java/com/liferay/portal/osgi/web/portlet/tracker/internal/PortletTracker.java#L149

However, the service registered in OSGi still has the portlet name "my-greeter-portlet".

When the service is fetched it is done so via the portlet name - https://github.com/jonathanmccann/liferay-portal/blob/c1e417111c005565e5d02bae31ce89fc44f809a7/portal-kernel/src/com/liferay/portal/kernel/portlet/bridges/mvc/MVCCommandCache.java#L51

The name used is already escaped so the registered services are not found. The changes in this pull make it so that the name used is not escaped and distinct from the ID so it will now search for services with the escaped and unescaped portlet name. These changes are modeled after https://issues.liferay.com/browse/LPS-92557 where the name is passed in instead of the ID.

Please let me know if there are any questions or if you see any potential issues with this change.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jonathanmccann please fix and resend.

**Pull request closed without merging**
