### PR TITLE
LPS-178815 Catch up for misfired SystemObjectDefinitionMetadata and u…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…se opening threadlocal to prevent double registration

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:upgrade

**Comment by susanchen3** [comment]
Reviewed, test failures are unrelated :heavy_check_mark:

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131895

**Pull request closed without merging**
