### PR TITLE
Startup optimization 238 initial table creator new 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 besides that known issue https://github.com/shuyangzhou/liferay-portal/pull/11071#issuecomment-1560106742 , any other failures here?

**Comment by vicnate5** [comment]
@shuyangzhou Upgrade Results:

Issue from https://github.com/shuyangzhou/liferay-portal/pull/11071#issuecomment-1560106742 is not occurring here on mysql. I still have the test failing on [Oracle](https://testray.liferay.com/reports/production/logs/2023-05/test-1-38/test-portal-acceptance-pullrequest(master)/7712/functional-upgrade-tomcat90-oracle193-jdk8/0/23/jenkins-console.txt.gz?authuser=0) and [PostgreSQL](https://testray.liferay.com/reports/production/logs/2023-05/test-1-38/test-portal-acceptance-pullrequest(master)/7712/functional-upgrade-tomcat90-postgresql144-jdk8/1/5/jenkins-console.txt.gz?authuser=0)

I do have another 6.2 dump failing here on MySQL. I can reproduce this locally.
Steps:
1. Import [6.2 dump ](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip)
2. Run upgrade tool
3. Start portal
```
WARN  [com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][PortalInstanceLifecycleListenerManagerImpl:204] Unable to register portal instance {"mvccVersion": 0, "companyId": 10155, "userId": 0, "userName": "", "createDate": "Tue Jun 12 00:00:00 GMT 2018", "modifiedDate": "Tue Jun 12 00:00:00 GMT 2018", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
com.liferay.portal.kernel.workflow.WorkflowException: com.liferay.portal.kernel.exception.DuplicateRoleException: Role already exists with name Account Administrator
	at com.liferay.portal.workflow.kaleo.runtime.internal.DefaultWorkflowEngineImpl.deployWorkflowDefinition(DefaultWorkflowEngineImpl.java:177) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy1248.deployWorkflowDefinition(Unknown Source) ~[?:?]
	at com.liferay.portal.workflow.kaleo.runtime.integration.internal.WorkflowDefinitionManagerImpl.deployWorkflowDefinition(WorkflowDefinitionManagerImpl.java:82) ~[?:?]
	at com.liferay.portal.workflow.kaleo.runtime.integration.internal.WorkflowDefinitionManagerImpl.deployWorkflowDefinition(WorkflowDefinitionManagerImpl.java:66) ~[?:?]
	at com.liferay.portal.workflow.kaleo.runtime.internal.manager.DefaultPortalKaleoManager.deployDefaultDefinitions(DefaultPortalKaleoManager.java:187) ~[?:?]
	at com.liferay.portal.workflow.kaleo.runtime.internal.manager.DefaultPortalKaleoManager.deployKaleoDefaults(DefaultPortalKaleoManager.java:239) ~[?:?]
	at com.liferay.portal.workflow.kaleo.runtime.internal.instance.lifecycle.KaleoPortalInstanceLifecycleListener.portalInstanceRegistered(KaleoPortalInstanceLifecycleListener.java:41) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$registerCompany$1(PortalInstanceLifecycleListenerManagerImpl.java:199) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl._runIfNeeded(PortalInstanceLifecycleListenerManagerImpl.java:304) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:183) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$null$1(PortalInstanceLifecycleListenerManagerImpl.java:430) ~[?:?]
	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:36) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28) ~[portal-kernel.jar:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$addingService$2(PortalInstanceLifecycleListenerManagerImpl.java:423) ~[?:?]
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:498) ~[portal-impl.jar:?]
```

**Comment by vicnate5** [comment]
Must be a race, the previous known issue showing here on relevant on mysql
https://testray.liferay.com/reports/production/logs/2023-05/test-1-29/test-portal-acceptance-pullrequest(master)/7276/functional-upgrade-tomcat90-mysql57-jdk8/2/0/jenkins-console.txt.gz?authuser=0

**Comment by vicnate5** [comment]
In relevant results we have a regression with some missing default content

**Account Roles** - Steps to Reproduce:
1. Go to Control Panel > Accounts
2. Add a new account, input "name" field and save
3. Go to "Roles" tab on the account

Expected Result: Default roles are present "Account Adminstrator", "Buyer", "Order Manager".
Actual Result: No default roles present.

**Objects** - Steps to Reproduce (seems to be what is happening)
1. Go to Control Panel > Objects

Expected Result: All Default objects are present "Commerce Product", "Commerce Order", Account, User
Actual Result: Sometimes default objects are not present for some tests, though I cannot reproduce locally. Might be random.

**Comment by vicnate5** [comment]
Lastly, There is a few unique integration failures here, though I was not able to reproduce locally. Could be some other race.
https://testray.liferay.com/home/-/testray/case_results/2317867578
https://testray.liferay.com/home/-/testray/case_results/2317867547
https://testray.liferay.com/home/-/testray/case_results/2317868391
https://testray.liferay.com/home/-/testray/case_results/2317868447

**Pull request closed without merging**
