### PR TITLE
[TS] LPS-91709

### PR DESCRIPTION
**Pull request by dacousalr**
\cc @ealonso @robertoDiaz

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:stop

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@dacousalr I asked QA to reproduce the issue. They can not reproduce it by using the ticket steps. Please work with QA to get the ticket verified first. Then resend this pull after it. Thanks!

CC @vicnate5 @kyle-miho

**Comment by robertoDiaz** [comment]
Please see the attached images in the LPS.

If with this images QA needs help to reproduce it, please tell me.

Thanks!!

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by kyle-miho** [comment]
Hey @robertoDiaz even with your images, i could not reproduce this. Are you testing this on master? or on 7.1.x (im wondering because in the screenshots the product menu doesnt have the most recent master updates). It could be also be 7.1.x / 7.0.x issue and not a master issue.

**Comment by robertoDiaz** [comment]
Hi, I test it in master branch updated this week. 

I've also test it in 7.1.x

I'll test it tomorrow in a fresh master.

**Comment by robertoDiaz** [comment]
Hi, I've test it again in 2d6d860b8dcae0c13cdf8579d18ea89ceda2dd46 and I was able to reproduce it following the described steps.

It is also reproducible in all branches.

No need to change the friendly urls, just create a hidden page and navigate to a non existing page.

**Comment by shuyangzhou** [comment]
@kyle-miho can you verify it again? Thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou I still cant reproduce. Maybe have someone else check?
1) Create a hidden page
2) Navigate to a non-existing page
3) Hidden pages don't show, but I am redirected to "My Sites"

**Comment by vicnate5** [comment]
@kyle-miho @robertoDiaz I found more consistent steps to reproduce.

This is easily reproducible when logged out (guest user), but not consistently reproducible when logged in as Test Test.

Confirmed at master HASH 411ddb5d65768d9a2c39aaeb7bad99ecace9800f
Screenshot 2019-03-18 09 40 25

@shuyangzhou I think we can move forward with this fix.

**Comment by shuyangzhou** [comment]
@dacousalr can you update ServicePreActionTest to reflect this problem? Thanks!

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @shuyangzhou,

I have added an integration test for this in #7515 although it may be better to cover this kind of cases with functional tests.

Best,
Daniel

**Pull request closed without merging**
