### PR TITLE
LPD-X Defer the IPInfo lookup until there really is a segment looking…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… up with key "ipGeocoderCountry".

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:echo

**Comment by shuyangzhou** [comment]
ci:report:2569207588

**Comment by vicnate5** [comment]
@shuyangzhou Segments test passed locally

**Comment by shuyangzhou** [comment]
thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
ci:report:2569409721

**Comment by shuyangzhou** [comment]
ci:report:2569409721

**Comment by shuyangzhou** [comment]
ci:report:2569409721

**Comment by shuyangzhou** [comment]
ci:report:2569409721

**Comment by shuyangzhou** [comment]
@vicnate5 not sure why the relevant batch can not generate report. I guess I need to rerun it? 
But the echo batch is reported here https://github.com/shuyangzhou/liferay-portal/pull/11500#issuecomment-2115748179 , could you help me check it?

**Comment by vicnate5** [comment]
@shuyangzhou The relevant test run didn't have any failures. The echo test suite failures were also seen upstream, so they are not related. This looks good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150426

**Pull request closed without merging**
