### PR TITLE
LPS-83452 Semantic Versioning

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Maybe dc68aeb is not worth it because it implies using reflection and only fixing one level wrappers, so it doesn't apply, for example, to com.liferay.portlet.PortalPreferencesWrapper

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz the problem described on the ticket does not exist, it is covered by MVCCSynchronizerPostUpdateEventListener. The problem on the ticket is a bug in the actual service impl. https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/AddressLocalServiceImpl.java#L153 is throwing away the persistence layer return value, you should fix it there.

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 now that that we can continue with this issue, sorry if my example wasn't enough clarifying, I only wanted some easy steps so that QA could reproduce the issue and test the fix, but anyway we shouldn't trust the developer good criteria in using the persistence API.

The problem is that currently we cannot return an object that has been retrieved from the cache if the object is going to be modified after the transaction gets committed. We do have the _MVCCSynchronizerPostUpdateEventListener_ but this listener only updates the cache, but not the objects that have been retrieved from it. I mean the cache update is later in time.

If we have a simplified stack or sequence like the following one:

```
ServiceMethod that returns cached entity Entity1 with mvcc = 2
MVCCSynchronizerPostUpdateEventListener updates cached Entity1 to a mvcc = 3
DefaultTransactionExecutor.commit 
```
The returned object will be obsolete. In the case I pointed in the description it can easily be fixed by assigning the returned object, but what if:

1. The developer wants to return an object from a find method, it's totally plausible and not forbidden by design or documented against it.
2. Our proper workflow framework makes, depending on the implementation, impossible to “follow” the transformed object, for example the [com.liferay.portal.kernel.workflow.WorkflowHandler.startWorkflowInstance(long, long, long, long, T, Map<String, Serializable>) ](https://github.com/liferay/liferay-portal/blob/128f1c42de68b228367b425681144131ca8dbb93/portal-kernel/src/com/liferay/portal/kernel/workflow/WorkflowHandler.java#L106) doesn't return the modified object, neither does some of the public methods of the utility WorkflowHandlerRegistryUtil. So the only way you can retrieve the modified model and not trust in the changes are going to be performed in the passed parameter (which also is a debatable approach), as well as in the database, is to query the object.
3. Nothing prevents an intermediate called method with an API that includes a method that modifies an object from having a void return:
```
Object ServiceImpl.updateObject()
	void updateMethod(Field field1, Field2)
	return modifiedObjectInUpdateMethod
```
So, again, if you need to return the modified object, the only way is to query it.
	
So the _MVCCSynchronizerPostUpdateEventListener_ is correct, but insufficient since it fixes future calls to the EntityCache, but not the ones that have been done when the method returns just before the transaction is committed.

Kind regards.

**Comment by shuyangzhou** [comment]
> The problem is that currently we cannot return an object that has been retrieved from the cache if the object is going to be modified after the transaction gets committed

This statement is very confusing. What modified after tx committed? Why it has anything to do with this tx? A follow up modification belongs to another tx.

> We do have the MVCCSynchronizerPostUpdateEventListener but this listener only updates the cache, but not the objects that have been retrieved from it.

As long as you use persistence api correctly, it is the same object, we have no problem here.

We have no framework problem here, the problems are at the usage. When we see a problem, we fix it, we don't build a solution to cover it. 

> we shouldn't trust the developer good criteria in using the persistence API.

This could not be more wrong, if we can not trust our developers to do this kind of basic things right, I don't who can ever trust our code for anything. It is true, developers will always make mistakes, the right thing to do is to improve our tooling chain to help developers to catch issues like this more easily, not to over complex the framework to make their wrong code run correctly.

If I misunderstand the problem here, please create a test to show it, it will be a lot easier comparing to use words. But don't pick something like your previous example, I already pointed out we should fix the bad return for cases like that. And I bet Hugo could totally SF it.

**Pull request closed without merging**
