### PR TITLE
[TS] LPS-73210 No REST and CXF endpoints are created

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-73210

Hi Shuyang,

Regarding Tina's concern on https://github.com/tinatian/liferay-portal/pull/838#issuecomment-344329410: I talked to @csierra and we think that those should be addressed under a separate ticket and not within the scope of this bug fix.

Regarding the root cause: based on @csababotos' investigation, the behavior change (endpoints configurations are added vs. not added) was introduced between FP29 and FP30 and we found 2 possible fixes that could impact this:
- https://issues.liferay.com/browse/LPS-73562
- https://issues.liferay.com/browse/LPS-53235

If you have doubts about the solution, it would be great if you could provide some hints so we can continue the investigation.

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Shuyang,

I think these failures are not related to this pull.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53221

**Pull request closed without merging**
