### PR TITLE
COMMERCE-1067 - batch-engine-service - Add tests

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

Restarting test, error unrelated to pull request.

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79862

**Pull request closed without merging**
