### PR TITLE
[Freemarker Aysnc]LPS-124751 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks
Tina

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian Test failures are unrelated, No regressions found in automation.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9672

**Pull request closed without merging**
