### PR TITLE
LPS-74738

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend? See SF error:

```
     [java] SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JavaVerifyUpgradeConnectionCheck.java 45
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JavaVerifyUpgradeConnectionCheck.java 54
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./portal-impl/src/com/liferay/portal/verify/VerifyGroupedModel.java 151
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./portal-impl/src/com/liferay/portal/verify/VerifyResourcePermissions.java 185
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./portal-impl/src/com/liferay/portal/verify/VerifyResourcePermissions.java 210
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./portal-impl/src/com/liferay/portal/verify/VerifyUUID.java 90
     [java] Use existing connection field instead of DataAccess.getUpgradeOptimizedConnection: ./portal-impl/src/com/liferay/portal/verify/VerifyAuditedModel.java 281

```

**Comment by shuyangzhou** [comment]
@brianchandotcom  you got the SF error locally, not on CI right?

I changed the SF class here https://github.com/shuyangzhou/liferay-portal/pull/4882/commits/61bdba0f4451c58c6e518ebbccd6de5f90cf9655, you need to redeploy it before running SF locally.

On CI, we already do deploy first before running SF, so CI should be fine.

After merge, you need to publish a new version of SF, then everyone will be fine.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
