### PR TITLE
Lps 176031 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:mfa

**Comment by vicnate5** [comment]
ci:test:security

**Comment by vicnate5** [comment]
In the relevant results there is no regressions, but I want to run the security suite to check the affected tests.

**Comment by vicnate5** [comment]
@shuyangzhou No issues found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135187

**Pull request closed without merging**
