### PR TITLE
[Web-ContextPath]LPS-119928

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Could you please run a diff of startup? 

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian I did not know there are so many missing ones. Do they really need the header? Why did they not cause any issue?
And this will noticeable reorder the startup sequence for those modules, we need a startup regression test.

CC @slnn @GinsonRen

**Comment by slnn** [comment]
Will run the startup test for this pull.

**Comment by slnn** [comment]
Hi @shuyangzhou @tinatian 

Update test results in here:https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit?usp=sharing

Detailed test results and cpu tracings please see here:https://drive.google.com/drive/folders/1fDYlxJ55YFfuitRMyfPDIkNKUWLFI_x9?usp=sharing



Lily

**Comment by shuyangzhou** [comment]
Thanks @slnn !
@tinatian seems like a full second delay, please look into it to try to reduce it. And also I need to understand why they did not cause any issue, and what is pushing us to fix it now?

**Comment by dantewang** [comment]
@shuyangzhou @tinatian There's a fallback. If the module is indeed a web module but Web-ContextPath is not declared, `"/" + bundle.getSymbolicName()` will be used as its actual web context path.

**On the other hand, it's not safe to SF all modules ending with `-web`.**

For example, [adaptive-media-blogs-web](https://github.com/shuyangzhou/liferay-portal/pull/9382/commits/5ef07ff25ea67bc545a1904f1b936f0cfd6c8e55#diff-77bb3e10223ed1d52c1f54829f01e3cd) does not contain any jsp/servlet/portlet, doesn't require/provide web-related capability in its manifest, doesn't have servlet context in runtime.

**Comment by shuyangzhou** [comment]
We will leave this alone for now.

**Pull request closed without merging**
