### PR TITLE
LPS-83616 No needed exceptions

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @shuyangzhou,

This is the branch for the Content Pages performance tests. As I understand, the idea is to run normal tests first(with existing sample-sql-builder), then run the same tests with this branch and compare the results. I tried to create more or less equal data (Content Pages with the same widgets as we have in Widget Pages in master). We have an Epic in JIRA to work on the Content Pages performance - https://issues.liferay.com/browse/LPS-83615, could you please create a Task to be able to track all the activity related to our performance issues? 

Thanks!

cc @ealonso @JorgeFerrer

**Comment by shuyangzhou** [comment]
@dantewang @slnn please take this pull over.
The goal is to help @pavel-savinov have performance tests running against content pages, and providing him results and profiles for tuning.

Ideally we could use the exist test cases from grinder side, only flipping the page type of the server side, so the urls does not really change. Please check on @pavel-savinov 's sample sql builder to verify whether this is giving us that, if not, explain what is missing.

Once the sample sql builder logic is working, make sure we can merge it in without generating additional data in our normal tests yet, we can flip it on after the tuning is completed and add the additional tests into our regression monitoring list.

**Comment by dantewang** [comment]
@shuyangzhou @pavel-savinov Lily has started checking it. If there's no problem we'll get back with results.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

The changes in this pull can not  pass the unit test of SampleSQLBuilder, I have fixed some typo and NPE in this pull https://github.com/pavel-savinov/liferay-portal/pull/197, but the unit test still be failed by the genetated sql can not be inserted into Hsqldb

@pavel-savinov please check my changes and make these generated sql be inserted into DB successfully and then we can startup portal.

Thanks
Lily

**Comment by shuyangzhou** [comment]
@pavel-savinov I am closing this pull now, please work with @slnn to have your SampleSQLBuilder logic fixed.

**Pull request closed without merging**
