### PR TITLE
Commerce 7127 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
The usage of this property is in com.liferay.portal.license.enterprise.app whose code is in 7.1.x branch.

Also, the description of the property has been reviewed by legal team.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou Please prioritize this as it is required to be done before the release on next Tuesday.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/106547

**Pull request closed without merging**
