### PR TITLE
LPS-70586 SF

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 did you have time to take a look to this pull?
Thanks.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz sorry for the delay, I have been busy.
I took a brief look at your change, without looking into the details, just focusing on the net outputs. I see you want to remove the duplicated mysql B-Tree indexes.

Although it is a good thing to do for mysql, it is no necessary a good thing for all db vendors. Those indexes are only considered duplicated due to the nature of how B-Tree indexes work. And not all DBs are using B-Tree indexes. So removing it in general is not what we would like to do.

So technically we can make this a mysql only change. But it will add a lot complexity to the SB indexing handling logic. We would only want to do that if it actually solves some real performance problems. I can hardly imagine anyone really running into a performance issue due those those "duplicated" indexes on mysql.

They only slow down inserting/deleting, (we don't update mapping tables). They are harmless for querying. And considering our TableMapper is pretty much caching all operations to mapping tables, it is just very hard to think about a case that this is a real issue.

Please let me know if it is really causing any harm, if not, we should not make this change. We are willing to pay this harmless performance overhead to keep things simple.

**Pull request closed without merging**
