### PR TITLE
LPS-88170

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Resent from https://github.com/shuyangzhou/liferay-portal/pull/7186

https://issues.liferay.com/browse/LPS-88170

Let me know if anything needs to be changed or if we should go a different direction with this fix.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@fortunatomaldonado see the SB batch failed. And don't commit jar and properties files. only java files.

**Comment by fortunatomaldonado** [comment]
Hello @shuyangzhou,

It seems that the failure comes from [build-test-batch.xml](https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L5539L5544) detecting changes in build services. The error can be found here: https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/268293/console 

Is it possible to add changes to the template without triggering this error? Any advice on how to move forward is much appreciated.

Thank you.

**Comment by fortunatomaldonado** [comment]
Hello @shuyangzhou,

I believe I will have to build the services again. Last time I ran `ant build-services` in portal-impl and was wondering if this is how I can rebuild all the services or if there are more places I need to rebuild services.
Thank you for your help.

**Pull request closed without merging**
