### PR TITLE
LPS-X Remove all bad DDMStructure.getFieldProperty() usages, these ar…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…e all static properties, no need to use BeanPropertiesUtil to dynamically get them which is very very slow.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @tinatian this is getting rid of all the BeanPropertiesUtil usage for the liferay com issue. If it passes the test, please pack it in your patched jar for testing.

**Comment by vicnate5** [comment]
ci:test:relevant:norebase

**Comment by vicnate5** [comment]
ci:test:upgrade:norebase

**Comment by vicnate5** [comment]
Running on known working commit on master https://github.com/vicnate5/liferay-portal/pull/1130

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian Some issues here.

Service Builder
```
     [echo] diff --git a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceHttp.java b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceHttp.java
     [echo] index 80751c4..7ba8324 100644
     [echo] --- a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceHttp.java
     [echo] +++ b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceHttp.java
     [echo] @@ -56,13 +56,14 @@ public class DDMStructureServiceHttp {
     [echo]  
     [echo]  	public static com.liferay.dynamic.data.mapping.model.DDMStructure
     [echo]  			addStructure(
     [echo] -				HttpPrincipal httpPrincipal, long groupId, long classNameId,
     [echo] +				HttpPrincipal httpPrincipal, long groupId,
     [echo] +				long parentStructureId, long classNameId, String structureKey,
     [echo]  				java.util.Map<java.util.Locale, String> nameMap,
     [echo]  				java.util.Map<java.util.Locale, String> descriptionMap,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMForm ddmForm,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMFormLayout
     [echo]  					ddmFormLayout,
     [echo] -				String storageType,
     [echo] +				String storageType, int type,
     [echo]  				com.liferay.portal.kernel.service.ServiceContext serviceContext)
     [echo]  		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  
     [echo] @@ -72,8 +73,9 @@ public class DDMStructureServiceHttp {
     [echo]  				_addStructureParameterTypes0);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo] -				methodKey, groupId, classNameId, nameMap, descriptionMap,
     [echo] -				ddmForm, ddmFormLayout, storageType, serviceContext);
     [echo] +				methodKey, groupId, parentStructureId, classNameId,
     [echo] +				structureKey, nameMap, descriptionMap, ddmForm, ddmFormLayout,
     [echo] +				storageType, type, serviceContext);
     [echo]  
     [echo]  			Object returnObj = null;
     [echo]  
     [echo] @@ -104,14 +106,13 @@ public class DDMStructureServiceHttp {
     [echo]  
     [echo]  	public static com.liferay.dynamic.data.mapping.model.DDMStructure
     [echo]  			addStructure(
     [echo] -				HttpPrincipal httpPrincipal, long groupId,
     [echo] -				long parentStructureId, long classNameId, String structureKey,
     [echo] +				HttpPrincipal httpPrincipal, long groupId, long classNameId,
     [echo]  				java.util.Map<java.util.Locale, String> nameMap,
     [echo]  				java.util.Map<java.util.Locale, String> descriptionMap,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMForm ddmForm,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMFormLayout
     [echo]  					ddmFormLayout,
     [echo] -				String storageType, int type,
     [echo] +				String storageType,
     [echo]  				com.liferay.portal.kernel.service.ServiceContext serviceContext)
     [echo]  		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  
     [echo] @@ -121,9 +122,8 @@ public class DDMStructureServiceHttp {
     [echo]  				_addStructureParameterTypes1);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo] -				methodKey, groupId, parentStructureId, classNameId,
     [echo] -				structureKey, nameMap, descriptionMap, ddmForm, ddmFormLayout,
     [echo] -				storageType, type, serviceContext);
     [echo] +				methodKey, groupId, classNameId, nameMap, descriptionMap,
     [echo] +				ddmForm, ddmFormLayout, storageType, serviceContext);
     [echo]  
     [echo]  			Object returnObj = null;
     [echo]  
     [echo] @@ -1012,12 +1012,6 @@ public class DDMStructureServiceHttp {
     [echo]  		DDMStructureServiceHttp.class);
     [echo]  
     [echo]  	private static final Class<?>[] _addStructureParameterTypes0 = new Class[] {
     [echo] -		long.class, long.class, java.util.Map.class, java.util.Map.class,
     [echo] -		com.liferay.dynamic.data.mapping.model.DDMForm.class,
     [echo] -		com.liferay.dynamic.data.mapping.model.DDMFormLayout.class,
     [echo] -		String.class, com.liferay.portal.kernel.service.ServiceContext.class
     [echo] -	};
     [echo] -	private static final Class<?>[] _addStructureParameterTypes1 = new Class[] {
     [echo]  		long.class, long.class, long.class, String.class, java.util.Map.class,
     [echo]  		java.util.Map.class,
     [echo]  		com.liferay.dynamic.data.mapping.model.DDMForm.class,
     [echo] @@ -1025,6 +1019,12 @@ public class DDMStructureServiceHttp {
     [echo]  		String.class, int.class,
     [echo]  		com.liferay.portal.kernel.service.ServiceContext.class
     [echo]  	};
     [echo] +	private static final Class<?>[] _addStructureParameterTypes1 = new Class[] {
     [echo] +		long.class, long.class, java.util.Map.class, java.util.Map.class,
     [echo] +		com.liferay.dynamic.data.mapping.model.DDMForm.class,
     [echo] +		com.liferay.dynamic.data.mapping.model.DDMFormLayout.class,
     [echo] +		String.class, com.liferay.portal.kernel.service.ServiceContext.class
     [echo] +	};
     [echo]  	private static final Class<?>[] _addStructureParameterTypes2 = new Class[] {
     [echo]  		long.class, String.class, long.class, String.class, java.util.Map.class,
     [echo]  		java.util.Map.class,
     [echo] diff --git a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceSoap.java b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceSoap.java
     [echo] index a2d29c6..ce90282 100644
     [echo] --- a/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceSoap.java
     [echo] +++ b/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMStructureServiceSoap.java
     [echo] @@ -70,13 +70,14 @@ public class DDMStructureServiceSoap {
     [echo]  
     [echo]  	public static com.liferay.dynamic.data.mapping.model.DDMStructureSoap
     [echo]  			addStructure(
     [echo] -				long groupId, long classNameId, String[] nameMapLanguageIds,
     [echo] +				long groupId, long parentStructureId, long classNameId,
     [echo] +				String structureKey, String[] nameMapLanguageIds,
     [echo]  				String[] nameMapValues, String[] descriptionMapLanguageIds,
     [echo]  				String[] descriptionMapValues,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMForm ddmForm,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMFormLayout
     [echo]  					ddmFormLayout,
     [echo] -				String storageType,
     [echo] +				String storageType, int type,
     [echo]  				com.liferay.portal.kernel.service.ServiceContext serviceContext)
     [echo]  		throws RemoteException {
     [echo]  
     [echo] @@ -89,8 +90,9 @@ public class DDMStructureServiceSoap {
     [echo]  
     [echo]  			com.liferay.dynamic.data.mapping.model.DDMStructure returnValue =
     [echo]  				DDMStructureServiceUtil.addStructure(
     [echo] -					groupId, classNameId, nameMap, descriptionMap, ddmForm,
     [echo] -					ddmFormLayout, storageType, serviceContext);
     [echo] +					groupId, parentStructureId, classNameId, structureKey,
     [echo] +					nameMap, descriptionMap, ddmForm, ddmFormLayout,
     [echo] +					storageType, type, serviceContext);
     [echo]  
     [echo]  			return com.liferay.dynamic.data.mapping.model.DDMStructureSoap.
     [echo]  				toSoapModel(returnValue);
     [echo] @@ -104,14 +106,13 @@ public class DDMStructureServiceSoap {
     [echo]  
     [echo]  	public static com.liferay.dynamic.data.mapping.model.DDMStructureSoap
     [echo]  			addStructure(
     [echo] -				long groupId, long parentStructureId, long classNameId,
     [echo] -				String structureKey, String[] nameMapLanguageIds,
     [echo] +				long groupId, long classNameId, String[] nameMapLanguageIds,
     [echo]  				String[] nameMapValues, String[] descriptionMapLanguageIds,
     [echo]  				String[] descriptionMapValues,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMForm ddmForm,
     [echo]  				com.liferay.dynamic.data.mapping.model.DDMFormLayout
     [echo]  					ddmFormLayout,
     [echo] -				String storageType, int type,
     [echo] +				String storageType,
     [echo]  				com.liferay.portal.kernel.service.ServiceContext serviceContext)
     [echo]  		throws RemoteException {
     [echo]  
     [echo] @@ -124,9 +125,8 @@ public class DDMStructureServiceSoap {
     [echo]  
     [echo]  			com.liferay.dynamic.data.mapping.model.DDMStructure returnValue =
     [echo]  				DDMStructureServiceUtil.addStructure(
     [echo] -					groupId, parentStructureId, classNameId, structureKey,
     [echo] -					nameMap, descriptionMap, ddmForm, ddmFormLayout,
     [echo] -					storageType, type, serviceContext);
     [echo] +					groupId, classNameId, nameMap, descriptionMap, ddmForm,
     [echo] +					ddmFormLayout, storageType, serviceContext);
     [echo]  
     [echo]  			return com.liferay.dynamic.data.mapping.model.DDMStructureSoap.
     [echo]  				toSoapModel(returnValue);
     [echo] .
     [echo] 
     [echo] Detected build services changes. See above build services log for more
```

Modules compile
```
  [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-form-web:assemble
     [exec] 688 actionable tasks: 688 executed
     [exec] Gradle build finished at 2019-03-08 23:13:23.845.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Failed to capture fingerprint of input files for task ':apps:dynamic-data-mapping:dynamic-data-mapping-test:jar' property 'rootSpec$2$1' during up-to-date check.
     [exec] > Could not copy MANIFEST.MF to '/opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/build/tmp/jar/MANIFEST.MF'.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.UncheckedIOException: Failed to capture fingerprint of input files for task ':apps:dynamic-data-mapping:dynamic-data-mapping-test:jar' property 'rootSpec$2$1' during up-to-date check.
     [exec] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.fingerprintTaskFiles(CacheBackedTaskHistoryRepository.java:360)
     [exec] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:163)
     [exec] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:76)
     [exec] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:123)
     [exec] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:200)
     [exec] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:94)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:50)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     [exec] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
     [exec] 	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
     [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
     [exec] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
     [exec] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
     [exec] Caused by: org.gradle.api.GradleException: Could not copy MANIFEST.MF to '/opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/build/tmp/jar/MANIFEST.MF'.
     [exec] 	at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:79)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.getFile(MapFileTree.java:172)
     [exec] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$4.visitFile(DefaultFileSystemSnapshotter.java:231)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$Visit.visit(MapFileTree.java:135)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree.visit(MapFileTree.java:88)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree.visitTreeOrBackingFile(MapFileTree.java:252)
     [exec] 	at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:132)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visitTreeOrBackingFile(AbstractFileTree.java:213)
     [exec] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshotTree(DefaultFileSystemSnapshotter.java:223)
     [exec] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.access$900(DefaultFileSystemSnapshotter.java:65)
     [exec] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$FileCollectionVisitorImpl.visitTree(DefaultFileSystemSnapshotter.java:265)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTree.visitRootElements(AbstractFileTree.java:166)
     [exec] 	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:206)
     [exec] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:142)
     [exec] 	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:54)
     [exec] 	at org.gradle.internal.fingerprint.impl.AbstractPathOnlyFileCollectionFingerprinter.fingerprint(AbstractPathOnlyFileCollectionFingerprinter.java:37)
     [exec] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.fingerprintTaskFiles(CacheBackedTaskHistoryRepository.java:358)
     [exec] 	... 34 more
     [exec] Caused by: org.gradle.api.GradleException: Build has errors
     [exec] 	at org.dm.gradle.plugins.bundle.JarBuilder.build(JarBuilder.groovy:138)
     [exec] 	at org.dm.gradle.plugins.bundle.JarBuilder.writeManifestTo(JarBuilder.groovy:87)
     [exec] 	at com.liferay.gradle.plugins.LiferayOSGiPlugin$LiferayJarBuilder.writeManifestTo(LiferayOSGiPlugin.java:1215)
     [exec] 	at org.dm.gradle.plugins.bundle.ManifestSubstitute.writeTo(ManifestSubstitute.groovy:40)
     [exec] 	at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:76)
     [exec] 	at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:63)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.copyTo(MapFileTree.java:184)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTreeElement.copyFile(AbstractFileTreeElement.java:93)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:74)
     [exec] 	... 50 more```

functional results look good.

**Pull request closed without merging**
