### PR TITLE
LPS-135170 - API implementation for layoutTypePortlet that considers Content Pages

### PR DESCRIPTION
**Pull request by ethib137**
@shuyangzhou and @david-truong this is related to [this conversation in Slack](https://liferay.slack.com/archives/CL9RTSZ52/p1646237560784609?thread_ts=1646200473.599819&cid=CL9RTSZ52) almost two months ago now. This will end up fixing many commerce bugs on content pages. It took a while to get here since there where a few dependencies on Echo that had be figured out first. 

It's been a while since this was initially discussed, so let me know if you would like me to handle this differently.

cc: @riccardo-alberti, @corbinmurakami

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@GinsonRen @slnn please run a regression test for this pull, thanks!

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the result of login, other cases are still running, I will update the results later.

Login  



Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 51300 | 274 | -
PR-10617 | - | 51575 | 273 | 0.54%

**Comment by GinsonRen** [comment]
@shuyangzhou Here are result:
WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 69529 | 462 | -
PR-10617 | - | 68678 | 497 | -1.22%

MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 10587 | 36.7 | -
PR-10617 | - | 10668 | 22.4 | 0.77%

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 5635 | 304 | -
PR-10617 | - | 5483 | 226 | -2.70%

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 21097 | 623 | -
PR-10617 | - | 20403 | 565 | -3.29%

Wiki::

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 14286 | 214 | -
PR-10617 | - | 14443 | 217 | 1.10%

AP:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb110 | 24395 | 386 | -
PR-10617 | - | 25166 | 396 | 3.16%

**Comment by shuyangzhou** [comment]
@ethib137 the DL and Blogs regression will need to be addressed.
@GinsonRen please generate profiles for those 2 testcase for @ethib137 to investigate.

@ethib137 for your new pulls please send to liferay-core-infra repo and tag @GinsonRen to rerun performance regression tests or generate profiles, once cleared I can take it over.

**Comment by ethib137** [comment]
@shuyangzhou will do. I'll be waiting on the profiles from @GinsonRen.

**Comment by GinsonRen** [comment]
@ethib137 I already shared profiles through google driver, could you check your email to get the link?

**Comment by ethib137** [comment]
@shuyangzhou do we have any internal docs for how to go about investigating using these profiles? @GinsonRen pointed me towards using YourKit, but still, after opening up a profile I have no clue where to start or what I should be looking for.

**Comment by shuyangzhou** [comment]
@ethib137 we don't, but yourkit has very good document on their site, you need to read it through to be able to get started. If you need further help ping @dantewang.

**Comment by shuyangzhou** [comment]
@dantewang please take this over and add it to your task queue.

**Comment by dantewang** [comment]
@GinsonRen Could you re-verify Blog and DL on QA env? These cases suffer from unstable results on main env.

**Comment by 111Anna** [comment]
@dantewang  Here are result, I ran on QA env.

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb1 | 4339 | 218 | -
PR-10617 | - | 4217 | 230 | -2.81%

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 8383cb1 | 7125 | 314 | -
PR-10617 | - | 6766 | 885 |  -5.04%

**Comment by dantewang** [comment]
@111Anna Thanks!

@ethib137 We can almost confirm that there are regressions. For profiles, basically you can search for the methods you modified in the "method list" as a start. If you have profiles before & after the change, you can open both in Yourkit and compare them to see the diff in invocation count and (not-precise) time consumption. Please feel free to let me know if you have any question.

**Comment by ethib137** [comment]
Hey @dantewang, I would expect that there should be "regressions", since this is adding functionality that should have been included for content pages but never was. The question is, is this a reasonable degree for it to slow down or do we need to find a better way to account for content pages that is more performant?

**Comment by david-truong** [comment]
@dantewang I spoke to @shuyangzhou and we have decided to take care of the performance regressions internally.  Can you take over the ticket from here?

**Comment by dantewang** [comment]
@david-truong Sure, I'll look into it. @ethib137

**Comment by ethib137** [comment]
@dantewang is there any update on this? I see this PR is closed, but I don't see another PR linked?

**Pull request closed without merging**
