### PR TITLE
LPS-70284 PortletConfigImpl.getResourceBundle

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/4b04b8bc15...47133ea7e2

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/3725

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/4b04b8bc15...358259dcdb

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/4b04b8bc15...358259dcdb

**Pull request closed without merging**
