### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Updated accd0b27233862337f89a332addc82afec639871

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by vicnate5** [comment]
@Preston-Crary lots of new unique integration test failures https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287598/#showFailuresLink

These classes have known issues at head:
```
PermissionCheckerTest
BatchEngineImportTaskExecutorTest
```

The rest might be related.

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8764

**Pull request closed without merging**
