### PR TITLE
LPS-89170 LayoutSet versioned

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @slnn,

Can you run this against the login and one other grinder test?  Just want to make sure this doesn't cause too big of a performance penalty.  Please note a5080c4 changes the Sample SQL Builder.

Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Here are test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Log In | Mean Time of Log Out | Session Cout Drop (%)
-- | -- | -- | -- | -- | --
BaseLine | 6e11c79 | 46444 | 289 | 87.5 | -
PR-7370 | - | 46093 | 290 | 84.5 | -0.7557488588

Document Library:

Portal Version | Git Id | Session Count | Mean Time of Log In | Mean Time of Add DL File | Session Cout Drop (%)
-- | -- | -- | -- | -- | --
BaseLine | 6e11c79 | 24255 | 349 | 410 | -
PR-7370 | - | 23676 | 327 | 395 | -2.387136673

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68260

Thanks @slnn ! We will have to take a small regression for now, it is small enough we can get it back somewhere else later.

**Pull request closed without merging**
