### PR TITLE
LPS-97897 Upgrade JGroups

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please check if the failures are real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures are not related to this change. 2 of the clustering functional tests are currently blocked due to some unrelated UI changes.

**Comment by tinatian** [comment]
Thanks @vicnate5!

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76173#issuecomment-515246825

**Pull request closed without merging**
