### PR TITLE
COMMERCE-7814 MVCC for commerce-tax-engine-fixed-service

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/COMMERCE-7814

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by kyle-miho** [comment]
@shuyangzhou unique failure from this PR, upgrade from 7.4.13, warnings/exceptions thrown after upgrade, example
`2021-11-15 08:11:58.123 WARN  [Portal Dependency Manager Component Executor--1][ModuleApplicationContext:185] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.commerce.tax.engine.fixed.service.CommerceTaxFixedRateService' defined in URL 
[bundleentry://760.fwk1329504187/META-INF/spring/module-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.commerce.tax.engine.fixed.service.CommerceTaxFixedRateAddressRelService' defined in URL [bundleentry://760.fwk1329504187/META-INF/spring/module-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.commerce.tax.engine.fixed.service.impl.CommerceTaxFixedRateAddressRelServiceImpl': Unable to inject bean reference fields; nested exception is java.lang.NullPointerException: A null service reference is not allowed.
2021-11-15 08:11:58.125 ERROR [Portal Dependency Manager Component Executor--1][LogService:93] [Portal Dependency Manager Component Executor--1] Invocation of 'start' failed. 
java.lang.Exception: Unable to start com.liferay.commerce.tax.engine.fixed.service
	at com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator.start(ModuleApplicationContextRegistrator.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:157) ~[bundleFile:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:112) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:638) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:1783) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeStart(ComponentImpl.java:1281) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1232) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1337) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.lambda$handleEvent$6(ComponentImpl.java:565) ~[bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182) [bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by shuyangzhou** [comment]
@ctang3 please fix and resend.

**Comment by ctang3** [comment]
Failing test might be caused by or related to this issue: https://issues.liferay.com/browse/COMMERCE-7987

Will resolve COMMERCE-7987 before resending this PR.

**Comment by ctang3** [comment]
Trying again here: https://github.com/shuyangzhou/liferay-portal/pull/10499

**Pull request closed without merging**
