### PR TITLE
LPS-81285 Portlet 3.0: Implement new methods in javax.portlet.ResourceResponse

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply implements methods in ResourceResponseImp.java that previously threw `UnsupportedOperationException`. The failures that are unique to this PR are not unique, I have seen them with other PRs today.

Please review when you get a chance, thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59805

**Pull request closed without merging**
