### PR TITLE
[Log4j]LPS-125550

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@tinatian CI can still only fetch from `liferay-plugins-ee`

**Comment by tinatian** [comment]
Close, please see https://github.com/shuyangzhou/liferay-portal/pull/9859

**Pull request closed without merging**
