### PR TITLE
[Startup Tuning]LPS-96755 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @vicnate5 
Could you please check the test result?

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
@tinatian please rebase

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7912

**Pull request closed without merging**
