### PR TITLE
Layout version workaround

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by anthony-chu** [comment]
Staging fails when adding multiple documents through Documents and Media portlet on a page:

1. Create site
1. Add page to site
1. Add Documents and Media portlet to page
1. Configure portlet to show actions
1. Upload multiple documents
1. Activate local live staging
    - enable page versioning on public pages
    - enable all assets to be staged
    - save staging configuration
Exceptions are thrown: https://gist.github.com/anthony-chu/4a05b40db6be29091d6629fa59a7490b

---

Publishing display page with fragments mapped to web content articles fails

1. Create a site
1. Activate local live staging on the site
1. Import test fragments from dependencies folder (portal-web/test/functional/com/liferay/portalweb/dependencies/fragment-collection.zip)
    1. Navigate to Site Administration > Site Builder > Page Fragments
    1. Click New > Import
    1. Upload above file
1. Add a display page with fragments mapped to basic web content
    1. Navigate to Site Builder > Pages
    1. Navigate to Display Page Templates tab
    1. Add display page
    1. Add fragments "Title" and "Rich Text"
    1. Select Web Content as the asset type, and Basic Web Content as the structure to map
    1. Map "Title" fragment to Basic Web Content title field
    1. Map "Rich Text" fragment to Basic Web Content content field
    1. Publish display page
1. Mark the display page as default
1. Add a web content article
1. Publish to live

Exceptions are thrown: https://gist.github.com/anthony-chu/1cbb5a02f05bd4cd85bf347ea3587784

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Pull request closed without merging**
