### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
No regressions. just needs some service builder and SF changes

```
     [echo] +++ b/modules/apps/layout/layout-api/bnd.bnd
     [echo] @@ -1,6 +1,6 @@
     [echo]  Bundle-Name: Liferay Layout API
     [echo]  Bundle-SymbolicName: com.liferay.layout.api
     [echo] -Bundle-Version: 3.1.1
     [echo] +Bundle-Version: 3.2.0
     [echo]  Export-Package:\
     [echo]  	com.liferay.layout.exception,\
     [echo]  	com.liferay.layout.model,\
```

```
     [java] java.lang.Exception: Found 9 formatting issues:
     [java] 1: Use 'LinkedHashMapBuilder' (178, 180). See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/builders.markdown: ./modules/apps/site/site-memberships-web/src/main/java/com/liferay/site/memberships/web/internal/display/context/SelectUsersDisplayContext.java 178 (Checkstyle:BuilderCheck)
     [java] 2: Rename exception variable 'cnse' to 'cloneNotSupportedException': ./modules/core/petra/petra-sql-dsl/src/main/java/com/liferay/petra/sql/dsl/ast/impl/BaseASTNode.java 71 (Checkstyle:ExceptionVariableNameCheck)
     [java] 3: Rename exception variable 're' to 'runtimeException': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 178 (Checkstyle:ExceptionVariableNameCheck)
     [java] 4: Rename exception variable 'e' to 'exception': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 352 (Checkstyle:ExceptionVariableNameCheck)
     [java] 5: Rename exception variable 'e' to 'exception': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 435 (Checkstyle:ExceptionVariableNameCheck)
     [java] 6: Rename exception variable 'e' to 'exception': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 519 (Checkstyle:ExceptionVariableNameCheck)
     [java] 7: Rename exception variable 'iae' to 'illegalArgumentException': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 573 (Checkstyle:ExceptionVariableNameCheck)
     [java] 8: Rename exception variable 'e' to 'exception': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 634 (Checkstyle:ExceptionVariableNameCheck)
     [java] 9: Rename exception variable 'e' to 'exception': ./modules/core/petra/petra-sql-dsl/src/test/java/com/liferay/petra/sql/dsl/ast/SQLDSLTest.java 941 (Checkstyle:ExceptionVariableNameCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
```

**Comment by Preston-Crary** [comment]
One thing we could consider is changing the InlineSQLHelper to return a Predicate instead of rewriting the query.  This could be kept pretty simple if we allowed null instead of rejecting them in the *Step interfaces like this:

```
public GroupByStep where(Predicate predicate) {
    if (predicate == null) {
        return this;
    }

    return new Where(predicate);
}
```

**Comment by shuyangzhou** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/957

**Pull request closed without merging**
