### PR TITLE
Use system out

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
error here because we bounced testray

**Comment by vicnate5** [comment]
ci:test:environments

**Pull request closed without merging**
