### PR TITLE
LPS-73667 Support retrying the JDBC connection before datasource infrastructure

### PR DESCRIPTION
**Pull request by mdelapenya**
Let's see then. Thank you for your feedback @shuyangzhou

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mdelapenya no way this can be right https://github.com/shuyangzhou/liferay-portal/pull/4676/commits/c44ece8090dacb504357e7bf68f18847136fd21a#diff-10a79b6f7e1509b220a2c1265f9c1097R116, you meant `if (PropsValues.RETRY_JDBC_ON_STARTUP_MAX_RETRIES > 0) {`, right?

Please run the basic test locally first, and at least run SF which would at least catch this https://github.com/shuyangzhou/liferay-portal/pull/4676/commits/c44ece8090dacb504357e7bf68f18847136fd21a#diff-70e7a8b9586d2a3f809fcc9e9e22e2b3R7038 . You use tab which needs to be 4 spaces. Every CI build takes a lot of resources, which could be reduced if we just pay a bit more attention.

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by mdelapenya** [comment]
@shuyangzhou I pushed force before that

**Comment by shuyangzhou** [comment]
Then why am I still seeing these on this pull?
Please send a new one rather than force push. It will mess up the CI test results.

**Comment by mdelapenya** [comment]
Related to the SF: `ant format-source-current-branch` (which is the target I **always** run) does not catch that. I use that command because `ant format-source` takes way too much time 😢

**Comment by shuyangzhou** [comment]
Can you ping @hhuijser for this? It will be the best if you can send him a pull that he can use for reproducing this problem. I ran into this issue too, but it was for jsps.

**Comment by hhuijser** [comment]
@mdelapenya @shuyangzhou I will do some testing with ant format-source-current-branch on this pull. Hopefully I can reproduce and get a fix in this time.

**Comment by hhuijser** [comment]
@mdelapenya 

I see you fixed your branch already since this failure.
I rebuild your branch on my end and source-format-current-branch was working fine on my end (previously when Shuyang experienced this, I wasn't able to reproduce as well).

1. You are now on Windows, right?

Somehow, I got a hunch it might have to do with the fact that the branch has commits with commit messages that go over multiple lines.

2. Can you test my theory on your machine?

Rebuild the branch that failed.
First with the same commit as you used before and secondly with shorter single line messages.

Thanks!

**Comment by hhuijser** [comment]
If that doesn't prove to make a difference, can you do the following (assuming ant format-source-current-branch is still failing)?

1. Run ```git merge-base HEAD master```
2. Take the commit id that you get from this and run ```git diff --diff-filter=AM --name-only id-from-step-1```

What does the output look like?

**Pull request closed without merging**
