### PR TITLE
Ant removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 fixed the WabDirTest failure, rerunning.

**Comment by vicnate5** [comment]
@shuyangzhou This looks good now.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111174

**Pull request closed without merging**
