### PR TITLE
LPS-83456

### PR DESCRIPTION
**Pull request by danielkocsis**
Hi @shuyangzhou,

I received this change from @hhuijser, but I think you also need to take a look on it. As the original method and the refactor is also pretty complex, I would suggest to write a few test cases just to make sure we won't introduce any bugs.

What do you think @hhuijser?

thanks,
Daniel

### CODE REVIEW

**Comment by shuyangzhou** [comment]
I am having a hard time on understanding what the ticket description is saying.
Please at least create some tests to show the problem first. Then fix it.
Try not to make big changes all at once, it is not easy to follow, especially I barely know anything about this method.

**Comment by danielkocsis** [comment]
@hhuijser could you please write some test and resend the change to @shuyangzhou? 

thanks,
Daniel

**Comment by hhuijser** [comment]
@arthurchan35

**Comment by arthurchan35** [comment]
@hhuijser,
Forgot to attach latest PR: https://github.com/shuyangzhou/liferay-portal/pull/6651

**Pull request closed without merging**
