### PR TITLE
[TS] LPS-145658

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thank!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Both JDK8 and JDK11 is passing.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
