### PR TITLE
LPS-77276 Portlet 3.0: Extract the private PortletResponseImpl.LiferayPortletURLPrivilegedAction into separate "internal" class

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak: Please take a look and if none of the failures are related to this PR then please let us know so that Shuyang can review. Thanks.

**Comment by timpak** [comment]
ci:test

**Comment by timpak** [comment]
@ngriffin7a looks like something went wrong with the previous test. I'm retesting it now and I'll take a look at the results.

**Comment by ngriffin7a** [comment]
@timpak Thanks for re-running the tests. Please let us know if it's OK for Shuyang to review.

**Comment by timpak** [comment]
@ngriffin7a looks good. The failures are unrelated to the PR.

@shuyangzhou please review.

**Comment by ngriffin7a** [comment]
@timpak Thanks! :)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57415

**Pull request closed without merging**
