### PR TITLE
[ArgumentsResolver]LPS-136445 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@zhangyan0701 Can you look into the 6.2 upgrade failures here? I suspect that `ViewPortalSmokeArchive621021` might have also failed if it had ran here.

**Comment by zhangyan0701** [comment]
I could reproduce the same error locally with our [data-archive-portal dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip) of 6.2.10.21.

I got below error during the upgrade:
```
2021-08-13 06:07:06.979 ERROR [ForkJoinPool-1-worker-11][VerifyResourcePermissions:228] Unable to add resource for {10155, com.liferay.portal.kernel.model.Group, 4, 10192, 10164}
java.lang.NullPointerException: null
```
After the upgrade, no error in console during portal startup, but `java.lang.IllegalArgumentException: ` occurs when I open http://localhost:8080:
```
2021-08-13 06:15:11.690 ERROR [http-nio-8080-exec-1][DynamicIncludeUtil:81] java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=10155, name=com.liferay.portal.kernel.model.Group, primKey=10182, scope=4}
java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=10155, name=com.liferay.portal.kernel.model.Group, primKey=10182, scope=4}
```
Attached the full logs:
[upgrade.log](https://github.com/shuyangzhou/liferay-portal/files/6980353/upgrade.log)
[liferay.2021-08-13.log](https://github.com/shuyangzhou/liferay-portal/files/6980351/liferay.2021-08-13.log)

**Comment by vicnate5** [comment]
@tinatian See the regression in the comment above.

**Comment by shuyangzhou** [comment]
@tinatian any update on this?

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10226

**Pull request closed without merging**
