### PR TITLE
LPS-113059 Fix DisplayPageTemplateServiceTest failures

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Didn't spend too much time investigating this one, just cleaned up the test.  Might be related to the recent ClassNameLocalServiceImpl changes so sending through you in case you want me to investigate more or fix it in another way.

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

This is fine, the test was just doing something really weird.

**Pull request closed without merging**
