### PR TITLE
LPS-121537 Apply groupIds cache to improve performance.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz this is too hacky. You can solve this in 2 ways.
1) Just get rid of the finder, switch to persistence, pay the extra hibernate deserialization overhead. It should not be that bad.
2) Wait for @tinatian to finish the FinderCache DSL integration, then the cache can be enabled for regular finders.

@tinatian this can be a good example usage for the finder integration, it is very simple.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

We cannot move back to use `groupPersistence.findByC_A` because this finder was added to avoid some throughput issues in https://issues.liferay.com/browse/LPS-110846 in case you have many Inactive Groups.

The problem with current **GroupLocalServiceImpl.getGroupIds**, it is executed before the Elasticsearch queries are executed, so it can cause a lot of unnecessary SQLs to the database.

Is there any estimation about when "FinderCache DSL" will be available? Is there any other alternative?

Thank you,
Jorge

/cc @lipusz

**Comment by shuyangzhou** [comment]
@jorgediaz-lr what is the problem for "groupPersistence.findByC_A" ? is it the hibernate deserialization too heavy?
If that's the case, then the best thing to do is just to leave this alone to wait for @tinatian 's findercache dsl integration to solve it.

**Comment by jorgediaz-lr** [comment]
I don't have all the details about https://issues.liferay.com/browse/LPS-110846 where that change was applied.
It seems if a customer has lots of inactive users, retrieving all the inactive Groups objects was too expensive and slow (for example the customer in LPP-36736 had 500000 inactive groups).

@ericyanLr and @lipusz were involved in the implemented solution for that LPS, they changed the code to just retrieving only the groupIds of the inactive groups.

Executing the SQL for retrieving only the groupIds seems to improve the extreme case of 500000 inactive groups, but it hurts those customers that executes lots of queries because returned data from database now is not cached.

Can we send this code to our customer as a workaround until findercache dsl integration is implemented?

Is there any LPS created to track the development of that new "findercache dsl" functionality?

Thank you,
Jorge

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,

 in addition to what @jorgediaz-lr pointed I guess that the reason of https://issues.liferay.com/browse/LPS-110846 change was mainly due to memory performance reasons. Since the number of groups retrieved can be huge they preferred to retrieve only the id instead of loading in memory all Group objects information.

Kind regards.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz the best thing to do now is to stay put to wait for @tinatian . If you want to deliver a temp fix to customer, that's fine.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Thank you for your response, for now, we will deliver this code to our customer.

Is there any LPS created to follow the development of that new "findercache dsl" functionality?
Is there any estimation when this functionality will be implemented?

Regards,
Jorge

**Comment by shuyangzhou** [comment]
@jorgediaz-lr please check with Tina for the progress details.

**Comment by tinatian** [comment]
Hi @jorgediaz-lr @marianoalvarosaiz ,

After taking a look at the related tickets, I guess your goal is to fix the performance issue of segments. This GroupLocalService.getGroupIds issue is just happen to be part of it, but not the root of it, right?

For https://issues.liferay.com/browse/LPS-110846, it focuses on the inactivate groups, but here you only cares for the activate groups, so I think you can go back to use the old groupLocalService#getActiveGroups() which uses persistence. This is an safe and simple change, and you can send it as a temp workaround to customer if needed.

For the dsl cache support, here is story ticket for dsl cache support, https://issues.liferay.com/browse/LPS-121768. I am going to add more sub tickets if needed while working on it. Hopefully everything can be merged into master in one month if I was not blocked by other high priory tasks.


Tina.

**Comment by tinatian** [comment]
Hi @marianoalvarosaiz @jorgediaz-lr ,
I just figured out a solution to fix this, I will send out a pull soon and will cc you.

Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

Thanks for taking care of it!

Let us know if you need help

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9484

**Pull request closed without merging**
