### PR TITLE
LPS-63229 Match com.liferay.portal.json.transformer.ObjectTransformer

### PR DESCRIPTION
**Pull request by csierra**
requested by @brianchandotcom here: https://github.com/brianchandotcom/liferay-portal/pull/62021

/cc @stian-sigvartsen @topolik

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Too many failures, most are real.

**Pull request closed without merging**
