### PR TITLE
LPS-151342 Move JSONWebServiceServlet and its JSPs to a web bundle

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @shuyangzhou, 

@vicnate5 has already validated the results of the ci test suites that ran here https://github.com/rafaprax/liferay-portal/pull/1154

PS: @vicnate5 If you want to run some additional test suites, feel free to do that.

Thx guys

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you please help scan these test results? Thx

**Comment by vicnate5** [comment]
@rafaprax No regressions found. This should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117245

**Pull request closed without merging**
