### PR TITLE
[Session Replicate]LPS-135570 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dantewang Please verify that I did not break anything.

Thanks.
Tina

**Comment by tinatian** [comment]
Enable it to run ci test at https://github.com/tinatian/liferay-portal/pull/2347.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@dantewang @tinatian Isn't PersistentHttpServletRequestWrapper enough to overcome the unwrapping issue for https://github.com/shuyangzhou/liferay-portal/pull/10220/commits/1e3e9c76da50406883110643d3bf07ff4fe575ff ?

**Comment by dantewang** [comment]
@shuyangzhou It's just a sub class of `HttpServletRequestWrapper` with override `clone()` method?

**Comment by zhangyan0701** [comment]
Manual testing of [LPS-135570](https://issues.liferay.com/browse/LPS-135570) and [LPS-72911](https://issues.liferay.com/browse/LPS-72911) Passed.

No error in cluster log.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Comment by shuyangzhou** [comment]
@dantewang it is used here https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L3767 Please confirm whether it is enough to prevent the unwrapping, if it is, we should avoid the directly impl of servlet request interface.

**Comment by tinatian** [comment]
@shuyangzhou The part you mentioned is not enough to prevent the unwrapping, please see the following two unwrapping logic:
https://github.com/tinatian/liferay-portal/blob/e13af4f77824d6dfba40392afb81423b13a83552/portal-impl/src/com/liferay/portal/security/auth/SessionAuthToken.java#L223

**Comment by shuyangzhou** [comment]
@tinatian ok, in that case, we should at least be able to make it a ASMWrapper proxy, right? I just want to avoid the future issues when we upgrade servlet api version.

**Comment by tinatian** [comment]
@shuyangzhou If you are worried about upgrade, we can inline this class as a private class. I prefer to inline as it would be more friendly to read than ASM.

**Comment by shuyangzhou** [comment]
Not that kind of upgrade issue. In case of servlet api version bump, they may add new method to HttpServletRequest interface. Since we directly implements that interface, we will have compile issue. Directly implementing it is forcing us to be in the provider role, although we are actually just consumer.

**Comment by tinatian** [comment]
@shuyangzhou I see your point. Ok, let's go with ASMWrapper, I will send you a new pull

**Pull request closed without merging**
