### PR TITLE
LPS-63529 Freemarker patch

### PR DESCRIPTION
**Pull request by Preston-Crary**
I added methods to their StringUtil to avoid additional changes in TextBlock and reduce the overall changes. Let me know if you'd rather remove all of the StringUtil.isTrimmableToEmpty calls in TextBlock instead.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased, minor conflicts.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Please rebase and resend.

**Pull request closed without merging**
