### PR TITLE
LPS-75306 Permission checkers part 1

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Will resend with the new baseline.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5336

**Pull request closed without merging**
