### PR TITLE
[TECHNICAL SUPPORT] LPS-79262 Timestamp

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Please check on the ftl blank lines, then resend, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6141

**Pull request closed without merging**
