### PR TITLE
Startup optimization 93 remove messaging proxy

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:reevaluate:1397401_1210

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:help

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by shuyangzhou** [comment]
ci:test:drools

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:workflow

**Comment by vicnate5** [comment]
@shuyangzhou Test compile failure:

`cd modules`
`gw :apps:portal-workflow:portal-workflow-task-web:compileTestJava`

```
> Task :apps:portal-workflow:portal-workflow-task-web:compileTestJava FAILED
/opt/dev/projects/github/liferay-portal/modules/apps/portal-workflow/portal-workflow-task-web/src/test/java/com/liferay/portal/workflow/task/web/internal/notifications/WorkflowTaskUserNotificationHandlerTest.java:40:
error: cannot find symbol
import com.liferay.portal.workflow.WorkflowTaskManagerProxyBean;
                                  ^
  symbol:   class WorkflowTaskManagerProxyBean
  location: package com.liferay.portal.workflow
/opt/dev/projects/github/liferay-portal/modules/apps/portal-workflow/portal-workflow-task-web/src/test/java/com/liferay/portal/workflow/task/web/internal/notifications/WorkflowTaskUserNotificationHandlerTest.java:262: error: cannot find symbol
                        new WorkflowTaskManagerProxyBean() {
                            ^
  symbol:   class WorkflowTaskManagerProxyBean
  location: class com.liferay.portal.workflow.task.web.internal.notifications.WorkflowTaskUserNotificationHandlerTest
Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-workflow/portal-workflow-task-web/src/test/java/com/liferay/portal/workflow/task/web/internal/permission/WorkflowTaskPermissionCheckerTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

Only need to re-run relevant, rest of the suites are good.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou New results are good

**Pull request closed without merging**
