### PR TITLE
LPS-104319 Optimize for weblogic.

### PR DESCRIPTION
**Pull request by shuyangzhou**
@vicnate5 this needs a weblogic regression check, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
Our automation for Weblogic is weak, going to do some additional checks manually.

**Comment by vicnate5** [comment]
Manual Test ticket https://issues.liferay.com/browse/LRQA-53509

**Comment by koor4356** [comment]
Hey @shuyangzhou @vicnate5 
Hey
This fix had breaks some portlet themes and UI in the portal configuration

Steps to reproduce:
# In your app.server.properties, Comment out tomcat and uncomment weblogic
# Run "ant -f build-dist.xml build-dist-weblogic" if portal is already compile, (otherwise, run "ant all")
# Start weblogic (weblogic-12.2.1/domains/liferay/bin/startWebLogic.sh)
# Go to Control Panel > Configuration > System Settings
## Note the UI is broken
# Go to Content & Data > Web Content or Blogs
## The theme is broken.
Screen Shot 2019-11-11 at 9 52 08 AM

Screen Shot 2019-11-11 at 10 02 02 AM

I was unable to reproduce this issue on the master head.

**Comment by vicnate5** [comment]
@shuyangzhou
rebuild/retest shows this change did **not** cause the UI issues above.

We also ran the JMeter test from the ticket and the portal runs fine during execution.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 and @koor4356 !

**Pull request closed without merging**
