### PR TITLE
LPS-148692 Enforce adding transitive false on all the ones in third-party

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Shuyang,

Can help to review the changes on `build.gradle` files? Thanks.

_SF issue:_
https://issues.liferay.com/browse/LPS-148692

https://github.com/brianchandotcom/liferay-portal/pull/113837#issuecomment-1050364667

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
