### PR TITLE
Startup optimization 36 property key casesensitive

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, this is a risky pull which affects all osgi service property key and bundle header usages. Please include additional tests as you see fit, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in the test results. Aside from running ALL the functional tests, I cannot think of any other targeted testing. We can move forward, worst case we will catch something on the next release build and fix then.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121033

**Pull request closed without merging**
