### PR TITLE
LPS-120586 Prevent publishing with missing parents

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou @david-truong @xbrianlee This has a high chance of causing regressions for publishing. If one of the references is incorrect then it may block the user from publishing by saying something is missing, 7dae00984329...d7792d3b33cb is fixing the ones of these I found.

This is based on LPS-121235 which has already been merged into Brian's origin. That one was a data problem instead of a reference problem which prevented publishing after these changes.

@xbrianlee can you download the bundle from this one and go through our use case doc to double check?

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:change-list

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:change-list

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
Analysis results updated on [here](https://docs.google.com/document/d/1rXrqzN0Z41UsCtVpnlQfUBHkCmek355laQZXbjY8JzU/edit#)
@Preston-Crary @xbrianlee

**Comment by Preston-Crary** [comment]
Will resolve issues from QA and resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9462

**Pull request closed without merging**
