### PR TITLE
LRQA-71684 Prevent the layout from adding the same friendly url in different locales since its not supposed to be allowed, exposed by 1826c9639ba6d079ae745260f088f0d8591426be

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Passed locally

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
