### PR TITLE
LPS-53265

### PR DESCRIPTION
**Pull request by dantewang**
The zip file contained in this pull is based on https://github.com/shuyangzhou/liferay-plugins/pull/28

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn and @dantewang

Hey guys,

Sorry for the late response, I have been very busy in the passed a few days.

I get what you are trying to do in this pull, but we should do it in a better way.

In the current solution, deploy target for module is merging sqls, what if a module got deployed multiple times? Its sqls will be merged multiple times, right?
After the merging, it is still the generic type sqls, you need to call build-module-sql in root build.xml to translate it before it can be really used. What if someone directly calls build-module-sql without deploying the modules first? Then it will fail because of missing inputs, right?

And even assume everything is used by the way you want, we are merging and translating sql from every modules, which we might not need them all, for a given test case.

So here are what I think we should do:
1) Create a new ant target in plugins build-common.xml which does the sql translation for current module, if there is any sql to translate at all. (Then the portal/plugins side of job is done)
2) From benchmark project, we add a support including modules' sql during build-database. For each sample-sql-builder-XYZ.properties, we tell the build-database which module it needs to include. So that the ant target in 1) is only called from benchmark project when it is really needed.

**Comment by slnn** [comment]
OK, got it

2015-02-12 1:56 GMT+08:00 Shuyang Zhou <notifications@github.com>:

**Comment by dantewang** [comment]
@shuyangzhou @slnn 
 
Hi Shuyang,

Is this sql translation thing only used by us? Since the translation happens within `ant all`, I think there may be others who also need it, but not sure.

What about just adding a target in portal/sql/build-parent.xml to translate sqls from modules defined in sql.properties instead of changing plugins?

Both ways we need to change DBBuilder in portal because many things (filenames & output paths) are hardcoded.

**Comment by shuyangzhou** [comment]
Yes, it is only needed by us.
Portal's sql translation happens in ant all at build time. Module/plugins' sql translation happens at deployment time (the war file deployment to a running portal), where they call DBFactoryUtil.getDB() to get the current using DB to translate the sql at runtime.

This works fine for normal use case, as before deploying a module/plugins, portal does not need their tables at all. But for us, since we need to pre-populate db with test data, we have to pull up the module/plugins sql generation logic to build time.

For this reason, other people won't need to use our logic at all, we should reduce the changes on portal to minimum, keep most logic in benchmark project side.

**Pull request closed without merging**
