### PR TITLE
[ResourceAction]LPS-112054

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian The `relevant` failures are unrelated. The `upgrade` failures are low enough count I am not worried, but I will not be able to easily review in detail because Testray backed up on importing results. Since this such a big change should we also run the `backend` suite too? It will cover the other databases.

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:test:backend

**Comment by dantewang** [comment]
It seems the backend integration failures are not unique, though they are showing NoSuchResourceActionException. I can see such failures in build 589 of test-portal-acceptance-upstream-dxp(master).

**Comment by vicnate5** [comment]
This looks good, the `NoSuchResourceActionException` failures @dantewang mentioned are a recent regression also showing at head.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88639

**Pull request closed without merging**
