### PR TITLE
[Freemarker readonly]LPS-124940

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull has passed benchmark test, no regression.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
