### PR TITLE
File system store cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:documents

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou looks like some real Documents and Media failures in the functional tests. Will test manually and get steps once the bundle compiles.

**Comment by vicnate5** [comment]
ci:test:documents

**Comment by vicnate5** [comment]
Cannot reproduce locally, even with the test. Re-running automation.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79198

**Pull request closed without merging**
