### PR TITLE
Lps 135286

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reevaluate:1257401_2633

**Comment by shuyangzhou** [comment]
ci:reevaluate:1257401_2633

**Comment by shuyangzhou** [comment]
@vicnate5 there is a commerce search issue on upstream that is causing all the circular dependencies issue, https://github.com/shuyangzhou/liferay-portal/pull/10155/commits/67efac001c024e68b4e6fa749fc2bd57b05ea31f should have that fixed. Rerunning all tests.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Looks good. The circular reference issue is fixed and no other regressions found in any of the test results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/104092

**Pull request closed without merging**
