### PR TITLE
LPS-75096 Reusing the same matcher

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4998

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
