### PR TITLE
LPS-70301 GroupImpl.hasStagingGroup

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Failure isn't related to my changes, pretty sure this has been fixed in master.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/af43248cbd...1dbfd33ed5

**Pull request closed without merging**
