### PR TITLE
LPS-107917 UserGroupRole & UserGroupGroupRole

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@Preston-Crary I have been thinking about this. We should do the full table scan. The priority should be on the quality of the output data. Only on top of that we may need to optimize it in case some database needs it. Once we have to optimize it for each db, we can use DBMS specific sequence support to speed things up.

**Comment by Preston-Crary** [comment]
Alright, I'll update the upgrade.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8848

**Pull request closed without merging**
