### PR TITLE
Pr 266 lps 78209 perf fix

### PR DESCRIPTION
**Pull request by slnn**
Come from https://github.com/slnn/liferay-portal/pull/266 which fixed the regression that caused by LPS-78209.

Sorry for the late, I mistook that Sergio had sent it.

Lily

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn do we still need https://github.com/shuyangzhou/liferay-portal/pull/5927/commits/58028ffebef49cf5ec49c7e33da560dd9b4d0dac ? I thought LPS-78251 fixed it.
Can you run a compare with and without that commit?

**Comment by shuyangzhou** [comment]
@slnn have you seen my question in previous comment?

**Comment by slnn** [comment]
Yes, tests are running, will update when I got them.

**Comment by slnn** [comment]
Hi Shuyang,

Here are test results on blog with qa env:

Portal Version | Session Count | MeanTime of Login | MeanTime of Blog
-- | -- | -- | --
PR-266-with-last-commit | 5921 | 155 | 367
PR-266-with-last-commit | 5821 | 169 | 371
PR-266-without-last-commit | 5504 | 339 | 585
PR-266-without-last-commit | 5547 | 206 | 434

From test results, we need this commit https://github.com/shuyangzhou/liferay-portal/commit/58028ffebef49cf5ec49c7e33da560dd9b4d0dac

**Comment by shuyangzhou** [comment]
@jbalsas I thought we cleaned this when fixing the soy template serialization. I am not sure whether this is still soy's bottleneck or it is the <clay:icon> itself is doing something bad. Can you take another look at this? In the mean time, I will merge this svg version for now. 

See https://github.com/brianchandotcom/liferay-portal/pull/57009

**Comment by jbalsas** [comment]
The soy serialization is still to be merged. Currently on Brian queue for the second attempt -> https://github.com/brianchandotcom/liferay-portal/pull/56988

**Comment by shuyangzhou** [comment]
Oh, ok, I did not know that. I took back my pull to Brian. @slnn please rerun the compare on top of https://github.com/brianchandotcom/liferay-portal/pull/56988

**Comment by slnn** [comment]
OK,got it.

**Comment by slnn** [comment]
Hi Shuyang,

Here are test results:

Portal Version | Session Count | MeanTime of Login | MeanTime of Blog
-- | -- | -- | --
PR-266-with-last-commit (contain LPS-79379) | 5918 | 168 | 384
PR-266-with-last-commit (contain LPS-79379) | 5802 | 189 | 395
PR-266-without-last-commit (contain LPS-79379) | 5972 | 237 | 465
PR-266-without-last-commit (contain LPS-79379) | 5928 | 161 | 363


Resend please see https://github.com/shuyangzhou/liferay-portal/pull/5945

**Pull request closed without merging**
