### PR TITLE
LPS-81271 Portlet 3.0: Implement new methods in javax.portlet.PortletConfig

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince These failures must be unrelated since the PR simply implements some methods that formerly threw `UnsupportedOperationException`. Please take a look and if you agree, let us know so that @shuyangzhou can review. Thanks.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply implements the new Portlet 3.0 methods in PortletConfigImpl that used to throw `UnsupportedOperationException`.

Most of these failures are the same that occurred in the FileUpload pull request, which I judged to be unrelated there as well. 

The "DLFileEntryPermissionCheckerTest.testContains" failure is unique to this PR, but I can't see how it is related since it seems to be testing something at the JDBC level of things.

Please review when you have time. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59005

**Pull request closed without merging**
