### PR TITLE
LPS-95208 Check needs to be stricter because friendlyURLs will be checked initially.

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, got this PR today, but I prefer to run this through you first. Let me know what you think. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @shuyangzhou ,

This PR is a continuation of https://github.com/brianchandotcom/liferay-portal/pull/72213

I made the check stricter because the initial check can be circumvented to be forwarded instead if you name friendlyURL with anything that starts with letter C.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hello @shuyangzhou ,

Please let me know if you have any questions in regards to this PR.

Sincerely,
Brian Kim

**Comment by Preston-Crary** [comment]
@brianikim can you add tests for LPS-93973 and LPS-95208 to FriendlyURLServletTest (one for impersonated user and one for this ticket)? These changes are not very clear without debugging and looking through the history of the code, we need test coverage to ensure this continues to work.

**Comment by brianikim** [comment]
Hello @Preston-Crary ,

Thank you for the updates. I will be looking at implementing tests for LPS-93973 and LPS-95208.

I will re-send a new PR with the necessary changes.

Sincerely,
Brian Kim

**Comment by Preston-Crary** [comment]
Thanks!

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
