### PR TITLE
Startup optimization 106 indexer registry

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
No regressions found in Search, waiting for relevant results.

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127211

**Pull request closed without merging**
