### PR TITLE
LPS-72939 and LPS-79508

### PR DESCRIPTION
**Pull request by arthurchan35**
@tinatian, @shuyangzhou 
@samuelkong asked me to open a new PR since he cant add new commits to the current branch.

I also did a test that compares regex vs loop & if for parsing protocols, it turns out regex is only bit slower(averaging 80 mill-seconds slower over 210k test cases) but with much readable code, because it's a regex that always starts with beginiing of a string.
 I think it's fine to use regex here, but if you think it's still a problem, I can switch to use loop and if.

From: https://github.com/shuyangzhou/liferay-portal/pull/5866

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:stop

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by tinatian** [comment]
Hi @arthurchan35 @samuelkong,
Your change breaks LPS-59425. Basically what LPS-59425 complains is "//www.google.com" should not be allowed to redirect. But after your change, it is allowed. 
I did:
1) Go to Product Menu - Control Panel - Configuration - Server Admin - Script
2) Run 
`com.liferay.portal.kernel.io.unsync.UnsyncPrintWriter

import com.liferay.portal.kernel.util.PortalUtil
import com.liferay.portal.kernel.util.Validator

out.println("Redirect to @www.example.com is allowed? " + Validator.isNotNull(PortalUtil.escapeRedirect("@www.example.com")));
out.println("Redirect to :@www.example.com is allowed? " + Validator.isNotNull(PortalUtil.escapeRedirect(":@www.example.com")));

out.println("Redirect to //www.example.com is allowed? " + Validator.isNotNull(PortalUtil.escapeRedirect("//www.example.com")));
out.println("Redirect to http://http://www.example.com is allowed? " + Validator.isNotNull(PortalUtil.escapeRedirect("http://http://www.example.com")));
out.println("Redirect to http:////www.example.com is allowed? " + Validator.isNotNull(PortalUtil.escapeRedirect("http:////www.example.com")));`
3) Result is 
`Redirect to @www.example.com is allowed? false
Redirect to :@www.example.com is allowed? false
**Redirect to //www.example.com is allowed? true**
Redirect to http://http://www.example.com is allowed? false
Redirect to http:////www.example.com is allowed? false`

Could you please fix it?

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @arthurchan35 @samuelkong ,
We do not like regex because of performance issue, if you see the change log of LPS-59425, we did a lot to remove it.

Tina.

**Comment by arthurchan35** [comment]
@tinatian 
I did a rebase and your comments are somehow gone missing, but to your comment:
1. Thanks for pointing out, I have corrected it
2. I understand there would be potential performence issue with regex but that was why I did a test comparing using regex vs use non-regex for parsing protocols, I have given the result in the descpriton of this pull request. I believe the impact is at minimal.
However I have also attached another commit that switches to use non-regex. Please give it a look.

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by tinatian** [comment]
@arthurchan35 Yes, please send me a pull request. 
Could you also please clean up your commit log by merging related changes (like merging all the changes for test and merging changes for one method into one commit expect you want to highlight the change) and removing unnecessary commits (like the revert and its previous one) so that it would highlight what you want to change, this way it would also help me understand what you are doing more quickly and more clearly.

And thanks for doing performance test for this, I know according to your test, it did not show too much difference, but when it comes to our benchmark test case which has lots of concurrent session running at the same time and the difference would show up (though I did not know how much, but according to our experience with regex, it is true it would hurt performance). The reason you want to use regex is readability, but this class is one of the core classes which won't be read by general developers and clients, it would only be maintained by core engineers in our company, or in other words, it is internal, in this case we prefer performance rather than readability, and we do and will do a lot of this kind of changes for internal classes for performance reason.


Thanks.
Tina.

**Comment by arthurchan35** [comment]
See https://github.com/tinatian/liferay-portal/pull/879

**Pull request closed without merging**
