### PR TITLE
[Startup Tuning]LPS-96755 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
See test result here : https://github.com/shuyangzhou/liferay-portal/pull/7901

**Comment by vicnate5** [comment]
@tinatian test failures from https://github.com/shuyangzhou/liferay-portal/pull/7901 are not related.

**Comment by tinatian** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74453

**Pull request closed without merging**
