### PR TITLE
LPS-132713

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by istvangergely** [comment]
Hi @shuyangzhou,

I was wondering if you had the chance to proceed with this PR?

Any input would be much appreciated.

Best,
István

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10111

**Pull request closed without merging**
