### PR TITLE
Startup optimization 254 null package source

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression here:

Steps to Reproduce:
1. Go to Control Panel > Users and Organizations
1. Add a new user > Save
1. Go to user Memberships > Assign to default Liferay site
1. Go to user Roles > Assign to "Publication User" role
1. Go to Global Menu > Applications > Publications
1. Enable publications
1. Go to publications dropdown menu > Templates 
1. Go to Add new template 
1. Open "Publication Collaborations" section > Add Users 
1. Type in User name

Expected Result: User shows up in dropdown menu and can be selected.
Actual Result: No users found

Caught by 
https://testray.liferay.com/home/-/testray/case_results/2345506661
https://testray.liferay.com/home/-/testray/case_results/2345506708

**Comment by shuyangzhou** [comment]
@vicnate5 I am not able to reproduce this locally. Can you try it on your side? Thanks!

**Comment by shuyangzhou** [comment]
This is very likely to be some kind of search indexing issue, I really doubt it is caused by this. I am rerunning the tests.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found on re-run.
Confirmed the publications regression previously was an unrelated regression upstream that is no longer occurring. I can also no longer reproduce locally.

**Pull request closed without merging**
