### PR TITLE
Startup optimization 359 json web service

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:echo

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou failures in backend tests for JSONWS
https://testray.liferay.com/home/-/testray/case_results/2473121908
https://testray.liferay.com/home/-/testray/case_results/2473121864
https://testray.liferay.com/home/-/testray/case_results/2473121848
https://testray.liferay.com/home/-/testray/case_results/2473121832
https://testray.liferay.com/home/-/testray/case_results/2473121808
https://testray.liferay.com/home/-/testray/case_results/2473121879

There is also an upgrade test catching an error post-upgrade during navigation
```
ERROR [http-nio-8080-exec-7][JSONWebServiceServiceAction:123] No JSON web service action with path /assettag/search and method null for null
```
https://testray.liferay.com/home/-/testray/case_results/2473170923
I reproduced locally but it will take me a bit to figure out the manual steps. I will investigate after lunch.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou Steps to Reproduce the upgrade issue:

1. Import 7.3 [mysql database](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.3.10.1/data-archive/data-archive-collection-display-mysql.zip)
2. Set `upgrade.database.auto.run=true` in portal-ext
3. Start portal to upgrade
4. Navigate to http://localhost:8080/group/test-site-name/~/control_panel/manage?p_p_id=com_liferay_asset_list_web_portlet_AssetListPortlet
5. Click on "Dynamic Collection" entry. Error thrown on this navigation

```
ERROR [http-nio-8080-exec-5][JSONWebServiceServiceAction:123] No JSON web service action with path /assettag/search and method null for null
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 force pushed the upgrade failure fix. Please help me watch over the new results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Previous upgrade test that failed is now passing.

**Pull request closed without merging**
