### PR TITLE
DB2 Anti time drift testing without debug

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Keeping the debug for AntiTimeDriftDataSourceWrapper for now.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou This looks good to me.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121691

**Pull request closed without merging**
