### PR TITLE
Lps 190491

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @vicnate5

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@JoyceWang08211 Could you test this for resolution to https://liferay.atlassian.net/browse/LPS-190491? I was not able to reproduce the original issue, so I need help verifying the fix.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 Could you test this for resolution to https://liferay.atlassian.net/browse/LPS-190491? I was not able to reproduce the original issue, so I need help verifying the fix.

I triggered the poshi test here: https://github.com/JoyceWang08211/liferay-portal/pull/218

**Comment by JoyceWang08211** [comment]
> > @JoyceWang08211 Could you test this for resolution to https://liferay.atlassian.net/browse/LPS-190491? I was not able to reproduce the original issue, so I need help verifying the fix.
> 
> I triggered the poshi test here: [JoyceWang08211#218](https://github.com/JoyceWang08211/liferay-portal/pull/218) cc @vicnate5

Liferay.Headless.Admin.User Client Extension scopes are lost in a clustered env. The same result with Stian's [fix](https://github.com/brianchandotcom/liferay-portal/pull/138393).

I reported this bug in [LPS-192126](https://liferay.atlassian.net/browse/LPS-192126)
cc @vicnate5, @stian-sigvartsen and @gaborlovasdotcom

**Comment by vicnate5** [comment]
@shuyangzhou Based on the testing showing the known issue also occurs on the original fix, and no other regressions found in the tests here, I think this can proceed (with a rebase).

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138605

**Pull request closed without merging**
