### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on #8794.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Real failure, will fix and resend

**Comment by tinatian** [comment]
Hi @vicnate5 ,
I added a new warning like what we did for embedded mode, but test failed, could you please take a look at it?

`[exec] 07:54:45,060 WARN  [main][SidecarElasticsearchConnectionManager:82] Liferay is configured to use Elasticsearch engine running in a child process of current process named as sidecar. Do NOT use sidecar in production. Sidecar is useful for development and demonstration purposes. Refer to the documentation for details on the limitations of sidecar. Remote Elasticsearch connections can be configured in the Control Panel.`

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian We just need to update the custom test log4j since WARNs will be caught by the log assertor

https://github.com/liferay/liferay-portal/blob/c4d3094cea7b87db0d77a5ef9dc45f361a1428de/build-test.xml#L7530-L7532

**Comment by tinatian** [comment]
Thanks @vicnate5 ! Fix and resend at https://github.com/shuyangzhou/liferay-portal/pull/8799

**Pull request closed without merging**
