### PR TITLE
LPS-81541 Portlet 3.0: Support <portlet:param type="render" />

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply adds support for a new `<portlet:param type="render" />` attribute which is not used anywhere in the system yet. I ran `ci:test` three times and got different failures each time. The most recent is simply 1 failure in scr-reference-dynamic-greedy-test-test which seems unrelated.

Please review when you get an opportunity. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59874

**Pull request closed without merging**
