### PR TITLE
LPS-80310 Portlet 3.0: Implement HeaderResponse.addDependency() methods

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou I re-ran the tests and now there is only 1 "failure unique to this pull" which is a Poshi/Selenium failure that did not appear in the previous run. In addition, none of the code in the PR commit actually gets executed during the request/response lifecycle since it is all `HEADER_PHASE` functionality that is currently disabled.

**Please review as soon as you can**, since this has API changes and roadblocks another API change that I'd like to send. Thank you, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60057

**Pull request closed without merging**
