### PR TITLE
LPS-83456

### PR DESCRIPTION
**Pull request by arthurchan35**
From: https://github.com/shuyangzhou/liferay-portal/pull/9451#issuecomment-695756872
Hi @shuyangzhou, to your comments:

1. Rebasing conflicts have been resovled, I also made a saprate commit for it: https://github.com/shuyangzhou/liferay-portal/pull/9453/commits/64625975feb1d90e83c149102aeb514a9f7b0c11
2. Exception message has been added, as a saperate commit as well: https://github.com/shuyangzhou/liferay-portal/pull/9453/commits/94fd24e1ce706689dccf9e8fab3c8209067ed5d9
3. The previous regression has been handled, I also tested it again just now(it's just need enabling local staging). It's bit difficult to reach QA to test for a pull.

Quote from original PR message:
Let me try to explain what's the change about:
So for the **export-import** feature, there is this **data level setting in PortletDataHandler** that determines if a portlet's data belong to **SITE or Portlet_Instance**, however there is also this **portlet attribute of portletPreference** that can be set to **unique per layout and/or owned by group**. What I found out 2 years ago was that:

If you set **portletPreference to uniquePerLayout=true** and also set your **Data Level to Site**, or
If you set **portletPreference to uniquePerLayout=false** and also set your **Date Level to Portlet_Instance**
The export import logic eventually will use these information and invoke `PortletPreferenceFactoryImpl` to genereate wrong PortletPreference.
The `PortletPreferenceFactoryImpl` will generate an invalid set of `portletPreferenceIds`(ie: **ownerId=0, ownerType=3, plid=0**) because of its defaulting stragegy(meaning, if input arguments are invalid, then generate this set of `portletPreferenceIds`).

After some diggings:
1. I understood that **a portlet that belong to group, like those admin portlets, cannot have uniquePerLayout=true, as uniquePerLayout=true only applies to portlet that can be added to pages, like those display portlets. And these sort of control panel portlets can only set Data Level to Site.**
2. I understood that **a portlet that can be added to page must set uniquePerLayout=true, and Data Level to Portlet Instance**

Unfortunately this is not enforced anywhere, which resulted many existing portlets having wrong portletPreference or Data Level. These existing portlets have been fixed by myself in other child tickets.(you can find them in **LPS-86233**).

So in this pull, what I did was force `PortletPreferenceFactoryImpl` not to generate invalid set of `portletPreferenceIds` by default, instead, throw exceptions.
And the reason it has to have new API is that, `PortletImportControllerImpl` uses default wrong info to generate `portletPreferenceIds` as well, so I created a new API to unify `portletPreferenceIds` generation.

TBH, I have to say the whole portletPreference related code base is not very elegant, it also has tons of other problems...

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9458

**Pull request closed without merging**
