### PR TITLE
LPS-89456 Mysql8

### PR DESCRIPTION
**Pull request by tinatian**
FYI @anthony-chu @vicnate5

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @anthony-chu @vicnate5,
Could you please check if there is any real failure? 

Thanks.
Tina

**Comment by anthony-chu** [comment]
@tinatian there was only functional failure unique to changes in this pull (Search#SearchGlobalTemplateSmoke), but I was not able to reproduce the failure manually or locally though automation.

**Comment by tinatian** [comment]
@anthony-chu 
It seems this failure is random. I am wondering if you see this on other pulls.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/67785

**Pull request closed without merging**
