### PR TITLE
Anti time drift data source wrapper

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
No causes of `SQLCODE=-204` found here. High pass rate for integration tests, no functional tests uniquely failed.

See https://github.com/shuyangzhou/liferay-portal/pull/10746

**Pull request closed without merging**
