### PR TITLE
Revert LPS-136498

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
I reverted the fix for LPS-136498 because:
1) it causes 8% regression on startup
2) it fixed some of the issues exposed by SplitPackagesTest, not all.

I will resend a fix later.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @GinsonRen

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109649

**Pull request closed without merging**
