### PR TITLE
LPS-X Fix for JSF

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou CI shows that the JSF deployment issue is fixed. This can be commited under LPS-123938.

**Comment by shuyangzhou** [comment]
@CAustin582 please take the jars in this pull to upload, we need it for a jsf regression fix, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Artifact uploaded https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/org.eclipse.equinox.http.servlet/1.2.2-LIFERAY-CACHED-1/

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9649

**Pull request closed without merging**
