### PR TITLE
LPS-128171

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is rebased from https://github.com/shuyangzhou/liferay-portal/pull/9799

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the result, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The only concern here is the aborted test runs due to timeout. Only 1 of the 3 has any portal errors. I would prefer we re-run this to be sure we are good.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found, would recommend manual forward.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99204

**Pull request closed without merging**
