### PR TITLE
Startup optimization 50 release renaming

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
I tested with the SAML module using a 6.2 dumb and the upgrade still failed for com.liferay.saml.persistence.service. Gist: https://gist.github.com/Kvale1733/780981a0752625573fa056cc0d223d5c. Checking the test results for regressions.

**Comment by Kvale1733** [comment]
Regressions found:

**Unsatisfied references for**
PortalSmokeUpgrade#ViewPortalSmokeArchive70106
PortalSmokeUpgrade#ViewPortalSmokeArchive7110
PortalSmokeUpgrade#ViewPortalSmokeArchive71103

`LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
     [exec]     Bundle {id: 258, name: com.liferay.portal.security.audit.router, version: 6.0.12}
     [exec]     	Declarative Service {id: 947, name: com.liferay.portal.security.audit.router.internal.PersistentAuditMessageProcessor, unsatisfied references: 
     [exec]     		{name: _auditEventManager, target: null}
     [exec]     	}
     [exec]     Bundle {id: 290, name: com.liferay.portal.security.audit.storage.service, version: 6.0.26}
     [exec]     	Declarative Service {id: 1069, name: com.liferay.portal.security.audit.storage.service.persistence.impl.AuditEventPersistenceImpl, unsatisfied references: 
     [exec]     		{name: Configuration, target: (&(origin.bundle.symbolic.name=com.liferay.portal.security.audit.storage.service)(name=service))}`

**Unsatisfied references for**
PortalSmokeUpgrade#ViewPortalSmokeArchive7310
`LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
     [exec]     Bundle {id: 382, name: com.liferay.saml.addon.keep.alive.web, version: 5.0.18}
     [exec]     	Declarative Service {id: 6899, name: com.liferay.saml.addon.keep.alive.web.internal.servlet.taglib.KeepAliveSamlWebDynamicInclude, unsatisfied references: 
     [exec]     		{name: _samlIdpSpConnectionLocalService, target: null}
     [exec]     		{name: _samlSpIdpConnectionLocalService, target: null}
     [exec]     		{name: _samlSpSessionLocalService, target: null}`
     
 Steps to Reproduce:

1.  Import the data-archive-portal database dump from the given portal test version
2. Start the upgrade process using that database dump

**Pull request closed without merging**
