### PR TITLE
LPS-52817 Register/unregister ImageIO plugins using activator

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @shuyangzhou 

This pull fixes some issues with the current implementations of ImageTool not handling correctly certain images. The fix is pretty simple and it works.

We created the fix in a module inside collaboration/document-library to test it, but we don't think 
that this fix should be in collaboration module. We don't know if it should be in modules/core or modules/third-party or modules/apps/foundation. 

I'm not familiar with modules/core or modules/third-party and I don't know how they are deployed (they don't have a .lfrbuild-portal file and some of them have a .lfrbuild-static file that I don't know what is it for and others don't have any) so I'd appreciate if you can move this module to a better place and ensure that it's deployed. 

Thanks

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @Preston-Crary

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@sergiogonzalez I don't have a reasonable location for this either. If I understand what you said right, these plugins although are for ImageIO in general, the real consumer is only inside ImageTool.
If that's the case, the best location to put this is, extract ImageTool as a module first, then put this inside that module.

**Comment by sergiogonzalez** [comment]
@shuyangzhou right now ImageTool is the only one operating with images, so it would be the only consumer, but as you said, it applies to ImageIO in general. 
The thing is that we are not planning to extract ImageTool for now, so I'd rather have this fix committed before we do the ImageTool extraction. 
If we were to extract ImageTool, where would you put that module? Because we could include this libraries in that module for now until we extract ImageTool (right now we are extracting services from DL and MB).
Thanks!

**Comment by sergiogonzalez** [comment]
Resent here https://github.com/shuyangzhou/liferay-portal/pull/5080

**Pull request closed without merging**
