### PR TITLE
Lps 92139 Use @Reference on field instead of method in module group adaptive-media

### PR DESCRIPTION
**Pull request by lanceji92674957**
Hi Shuyang,

This pull is to use 'Reference' annotation on a field instead of a method. This pull only modified classes in modules group adaptive-media for quick initial checks.

For classes not modified, please refer to https://drive.google.com/open?id=174x3v-fVeiCnxzuG4yn5WbGY3g4gBubxvBgqQCCzKg0

CC @Preston-Crary

Thanks.
Lance

### CODE REVIEW

**Comment by lanceji92674957** [comment]
ci:test:relevant

**Comment by lanceji92674957** [comment]
ci:stop

**Comment by lanceji92674957** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69605

**Pull request closed without merging**
