### PR TITLE
Nested field support

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
I have done analysis and found no unique failures. We are rerunning the relevant because the failures there are not unique to this pr. Thanks!

**Comment by shuyangzhou** [comment]
Thanks @koor4356 ! Please leave a comment if all cleared after the rerun. I will create a ticket to send it out.

**Comment by vicnate5** [comment]
@shuyangzhou This is ready to go

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9606

**Pull request closed without merging**
