### PR TITLE
LPS-75096 Moving the lazy attribute

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @shuyangzhou,

I haven't been able to test this locally because I could not manage to make `gradle` pick up my changes in `service builder`. I tried `gradle installCache` and `gradle commitCache` inside `portal-tools-service-builder` with no luck. 

Could you please verify it works?

Thanks a lot

PS: It would be nice if you could tell me how to install service builder locally so I can test it myself next time.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
I managed to run it locally but the source formatter will alphabetically sort the xml attributes rendering this fix useless.

I am afraid the logic inside service builder must be changed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/52046

Deploy the SB module locally and add the following property to your build.${user.name}.properties
```
com.liferay.portal.tools.service.builder.ignore.local=false
```
Then you will be able to use the last deployed SB to regenerate.

**Comment by 4lejandrito** [comment]
Thanks @shuyangzhou!

**Pull request closed without merging**
