### PR TITLE
[DS] LPS-101881 & LPS-101968 Rebase after private -> dxp change and Resend

### PR DESCRIPTION
**Pull request by dantewang**
cc @Preston-Crary

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80097

**Pull request closed without merging**
