### PR TITLE
LPS-107255 Fix FR storage.size.suffix translations

### PR DESCRIPTION
**Pull request by achaparro**
Hey @shuyangzhou,

This is a small change for the localization framework. We need to localize the units (bytes, kbs, etc.) because in some languages like french they have other names for the same unit.

Thanks.

cc/@rolandpakai @ericyanLr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Please fix the TextFormatterTest and resend.

**Comment by achaparro** [comment]
Hi @rolandpakai,

Can you fix it?

Thanks

**Comment by rolandpakai** [comment]
Hi @achaparro 

could you please help me out fixing the TextFormatterTest ?
I dont see what should i fix there.
The testformatStorageSize is testing the Spain and US LocaleUtil.
There is no tests for French.

Thanks, Roland

**Comment by achaparro** [comment]
Hi @rolandpakai,

I don't know why but it seems that we are getting a null pointer exception when doing getLanguage()

It doesn't matter if the test are in Spanish or English, it seems that they worked before the changes  and you should ensure that the test still works after your changes. In these cases I usually debug it locally to know what is happening. If it's an error in the CI, please, explain the reason behind that.

Cheers.

**Comment by rolandpakai** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/8793

**Pull request closed without merging**
