### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is disabled sidecar by default, currently no ci test should be affected.

Tina.

### CODE REVIEW

**Comment by vicnate5** [comment]
@xbrianlee @joshchong Here sidecar is disabled for ES7. Neither ci test nor ci test elasticsearch7 will should use the sidecar.

We want to send another PR after to enable sidecar with all the test related changes, so with that pull, ci:test:elasticesearch7 will trigger sidecar, but all other tests are going to use ES6 with embedded by default.

**Comment by joshchong** [comment]
@vicnate5 just to be clear, you are planning to push this PR upstream first before pushing another PR that actually enables sidecar?

**Comment by tinatian** [comment]
@joshchong Yes, you are right.

**Comment by joshchong** [comment]
Got it. We'll run our search tests here and analyze the results. Thanks!

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
@joshchong Please scan the test results.

Thanks.
Tina

**Comment by joshchong** [comment]
@shuyangzhou @tinatian @vicnate5 The only unique failure from the test results is the `ModulesStructureTest.testScanGradleFiles` test within the central-requirements batch:

> Redundant dependency detected in modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/build.gradle expected:<compileOnly project(":core:petra:petra-concurrent")> but was:<testCompile project(":core:petra:petra-concurrent")>	

All other failures are unrelated.

**Comment by tinatian** [comment]
@joshchong  @vicnate5 I just pushed one commit to fix `ModulesStructureTest`, please run corresponding test to confirm.

Thanks.
Tina.

**Comment by joshchong** [comment]
@tinatian rerunning ES7 backend tests here: https://github.com/joshchong/liferay-portal/pull/238#issuecomment-588387159

**Comment by joshchong** [comment]
@tinatian The test results look good https://github.com/joshchong/liferay-portal/pull/238#issuecomment-588470722. This PR should be good to go.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Add cluster support and resend at https://github.com/shuyangzhou/liferay-portal/pull/8871

**Pull request closed without merging**
