### PR TITLE
LPS-123509 Use render as lifecycle in embedded portlet if it was call from different portlet action phase.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
For more information see https://issues.liferay.com/browse/PTR-2068

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
