### PR TITLE
Lps 65862

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:stop

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by pyoo47** [comment]
TempMap failure. ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/40095

**Pull request closed without merging**
