### PR TITLE
LPS-X Refactor BatchEngineTaskMethodRegistryImpl to use ServiceTracke…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…rMap

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:data-integration

**Comment by shuyangzhou** [comment]
ci:test:headless

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression here.

Steps to Reproduce:
1. Go to http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_batch_planner_web_internal_portlet_BatchPlannerPortlet
(I have no idea how to navigate to it in the UI...)
2. Click Plus icon > Export File
3. Select "Entity Type" BlogPosting
4. Click "Export"

Expected Result:
User able to export successfully

Actual Result:
Export fails.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:data-integration

**Comment by shuyangzhou** [comment]
ci:test:headless

**Comment by shuyangzhou** [comment]
ci:test:headless

**Comment by shuyangzhou** [comment]
ci:test:headless

**Comment by shuyangzhou** [comment]
@vicnate5 the headless batch seems unstable, I ran it 3 times, the last one passed. Can you check if this is normal? Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Normal variation here. No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132974

**Pull request closed without merging**
