### PR TITLE
LPS-100525 CTTableMapper

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan this pull for me, thanks!

**Comment by vicnate5** [comment]
@Preston-Crary DB-specific Integration test failures

DB2
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/360635/AXIS_VARIABLE=6,label_exp=!master/testReport/junit/com.liferay.change.tracking.internal.test/LayoutCTTest/testPublishLayoutWithAssetTag/
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/360635/AXIS_VARIABLE=33,label_exp=!master/testReport/junit/com.liferay.portal.upgrade.test/UpgradeCTModelTest/testUpgradeCTModel/

HSQL
https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372524/AXIS_VARIABLE=6,label_exp=!master/testReport/junit/com.liferay.change.tracking.service.test/CTCollectionLocalServiceTest/testUndoCTCollection/

PostgreSQL
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287490/AXIS_VARIABLE=6,label_exp=!master/testReport/junit/com.liferay.change.tracking.internal.test/LayoutCTTest/testPublishLayoutWithAssetTag/
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287490/AXIS_VARIABLE=6,label_exp=!master/testReport/junit/com.liferay.change.tracking.service.test/CTCollectionLocalServiceTest/testUndoCTCollection/

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8747

**Pull request closed without merging**
