### PR TITLE
[ResourceAction]LPS-112054 rebase 05-27

### PR DESCRIPTION
**Pull request by dantewang**
Rebased https://github.com/shuyangzhou/liferay-portal/pull/9099 and fixed a new violation merged on May 22.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
cc @tinatian

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
