### PR TITLE
Startup optimization 306 lazy aop service

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou  

1. There are many integration tests failed with error like below:
`java.lang.NoSuchFieldException: No field on null with name _target`

Examples:

- [com.liferay.headless.commerce.delivery.order.resource.v1_0.test.PlacedOrderItemShipmentResourceTest](https://testray.liferay.com/home/-/testray/case_results/2441627980).

Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3798/modules-integration-mysql57-jdk8/1/6/jenkins-console.txt.gz?authuser=0

- [com.liferay.portlet.test.PortletBagFactoryTest](https://testray.liferay.com/home/-/testray/case_results/2441629425).

Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3798/modules-integration-mysql57-jdk8/3/23/jenkins-console.txt.gz?authuser=0

2. Some integration tests failed with error like below:
`java.lang.NoSuchFieldException: No field on null with name _service`

Example:
[com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest](https://testray.liferay.com/home/-/testray/case_results/2441630610)

Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3798/modules-unit-jdk8/0/14/com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest.txt.gz?authuser=0

**Pull request closed without merging**
