### PR TITLE
LPS-84115 BundlePortletApp.isWarFile() and BundlePortletApp.setWarFile(boolean) must not decorate/wrap the underlying portlet appLPS-84115 BundlePortletApp.isWarFile() and BundlePortletApp.setWarFile(boolean) must not decorate/wrap the underlying portlet app

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply modifies `BundlePortletApp.isWARFile()` and `BundlePortletApp.setWARFile(boolean warFile)` to use a private class-level instance variable. With the exception of the `LocalFile.ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration -` failure, I have seen all of these failures in other PRs today. However, I don't think it is related. In addition, this PR does not contain the legitimate failures associated with a previous try.

Please review when you get an opportunity. Thanks, Neil.

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR simply modifies `BundlePortletApp.isWARFile()` and `BundlePortletApp.setWARFile(boolean warFile)` to use a private class-level instance variable. With the exception of the `LocalFile.ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration -` failure, I have seen all of these failures in other PRs today. However, I don't think it is related. In addition, this PR does not contain the legitimate failures associated with a previous try.

Please review when you get an opportunity. Thanks, Neil.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62065

**Pull request closed without merging**
