### PR TITLE
[Factory Configuration]LPS-139670

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Please note I added integration test to cover "_".

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou This looks good. I tested manually as well. I think we can rely on the new integration tests for regression coverage.

**Comment by shuyangzhou** [comment]
@tinatian please rebase and resend.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/10328

**Pull request closed without merging**
