### PR TITLE
LRQA-33560 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Hey @shuyangzhou

This replaces the current Portlet 2.0 TCK with the new TCK for Portlet 3.0. This new test group contains over 6000 tests (compared to a few hundred before).

53 of the tests are currently failing, but they are ignored with LPS ticket references. 

It is possible the new tests are missing a handful of what we had for the old TCK, but there is also a runtime benefit to the new tests - the new TCK batch runs faster on the CI (30 minutes vs 50 minutes).

 
This does not cleanly backport to 7.1

### CODE REVIEW

**Comment by vicnate5** [comment]
CC @stiemannkj1 @ngriffin7a

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by vicnate5** [comment]
Added fix for theme build, theme changes at head this week.

**Comment by shuyangzhou** [comment]
@vicnate5 can you give me some instructions on how to run this locally? Thanks!

**Comment by vicnate5** [comment]
Steps to run locally:

1. git clone https://github.com/apache/portals-pluto.git
1. git remote add liferay https://github.com/liferay/portals-pluto.git
1. git fetch liferay tck3 && git checkout tck3
1. Navigate to master source
1. ant -f build-test-tck.xml prepare-tck-app-server -Dtck.home=PATH_TO_PORTALS_PLUTO/portlet-tck_3.0
1. Start app server manually after setup is completed
1. ant -f build-test-tck.xml run-tck-tests -Dtck.home=PATH_TO_PORTALS_PLUTO/portlet-tck_3.0 -Dtck.browser.bin.file="PATH_TO_CHROME_BIN"

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70869

**Pull request closed without merging**
