### PR TITLE
Lps 149082

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117065

@guilhermedcamacho please continue on the jar removal.

**Comment by guilhermedcamacho** [comment]
Ok, thanks @shuyangzhou :+1: 
I think the PR you opened in Brian's repo has conflicts.

**Pull request closed without merging**
