### PR TITLE
Embedded portal web peter

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@petershin can you take a look at this https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/475863/consoleFull
```
     [exec] > Task :apps:account:account-rest-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountRoleResourceTestCase.java:31: error: package com.liferay.petra.function does not exist
     [exec] import com.liferay.petra.function.UnsafeTriConsumer;
     [exec]                                  ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountRoleResourceTestCase.java:32: error: package com.liferay.petra.reflect does not exist
     [exec] import com.liferay.petra.reflect.ReflectionUtil;
```
Apparently the module was relying on the hidden petra jars on classpath to compile.
So either we somehow force all modules to declare what they need, or add back those hidden petra jars to new classpath to keep the behavior same.

What do you think?

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 are those upgrade failures real? If so, please help me find a way to reproduce them.

**Comment by vicnate5** [comment]
@shuyangzhou Upgrade failures are real. I reproduced locally.

Steps to Reproduce
1. Go to `bundles/tools/portal-tools-db-upgrade-client`
2. Run `./db_upgrade.sh` 
3. Use default app server directories in the upgrade tool prompts

Upgrade will fail to start.
```
JVM arguments: -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.timezone=GMT -Xmx2048m -Dexternal-properties=portal-upgrade.properties -Dserver.detector.server.id=tomcat -Dliferay.shielded.container.lib.portal.dir=/opt/dev/projects/github/bundles/tomcat-9.0.43/webapps/ROOT/WEB-INF/shielded-container-lib
Exception in thread "main" java.lang.ClassNotFoundException: com.liferay.portal.tools.DBUpgrader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:42)
```

Maybe we just need to update the app server properties for your changes? 
Default app.server.properties for the upgrade client:
```
dir=/opt/dev/projects/github/bundles/tomcat-9.0.43
extra.lib.dirs=/bin
global.lib.dir=/lib
portal.dir=/webapps/ROOT
server.detector.server.id=tomcat
```

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! Just pushed a fix to retest.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:reevaluate:1197401_8507

**Comment by shuyangzhou** [comment]
ci:reevaluate:1197401_8507

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou The failures here are not related.

**Comment by shuyangzhou** [comment]
ci:test

Thanks @vicnate5 ! Let's try a bigger set now :)

**Comment by vicnate5** [comment]
@shuyangzhou 

Unique failures:
1. Websphere startup errors
`Caused by: java.lang.NoClassDefFoundError: org.apache.axis.AxisProperties (initialization failure)`
https://testray.liferay.com/reports/production/logs/2021-06/test-1-8/test-portal-acceptance-pullrequest(master)/7578/functional-smoke-websphere90-mysql57-jdk8/0/0/jenkins-console.txt.gz
2. JNDI tests all failed, could just need an updated configuration.  `ERROR [main][DataSourceFactoryImpl:179] Unable to lookup jdbc/LiferayPool
 [parallel] javax.naming.NameNotFoundException: Name [java:comp/env/jdbc/LiferayPool] is not bound in this Context. Unable to find [java:comp].`
https://testray.liferay.com/reports/production/logs/2021-06/test-1-8/test-portal-acceptance-pullrequest(master)/7578/functional-tomcat90-mysql57-jdk8/11/9/jenkins-console.txt.gz
3. Setup Wizard tests all failed. Only 3 of them ran though (Configuring setup wizard for both SQL Server versions and Oracle). No errors in the logs, but the user was unable to login after changing the database connection, completing the setup wizard, and restarting. I can look more into this one tomorrow.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will look into them.

**Comment by vicnate5** [comment]
@shuyangzhou JNDI config
https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L2022-L2078
+
`jdbc.default.jndi.name=jdbc/LiferayPool` in portal-ext

I reproduced the issue locally
```
ERROR [main][DataSourceFactoryImpl:179] Unable to lookup jdbc/LiferayPool
 [parallel] javax.naming.NameNotFoundException: Name [java:comp/env/jdbc/LiferayPool] is not bound in this Context. Unable to find [java:comp].
 [parallel]     at org.apache.naming.NamingContext.lookup(NamingContext.java:833) ~[catalina.jar:9.0.43]
 [parallel]     at org.apache.naming.NamingContext.lookup(NamingContext.java:174) ~[catalina.jar:9.0.43]
 [parallel]     at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_265]
 [parallel]     at com.liferay.portal.kernel.jndi.JNDIUtil._lookup(JNDIUtil.java:134) ~[portal-kernel.jar:?]
 [parallel]     at com.liferay.portal.kernel.jndi.JNDIUtil.lookup(JNDIUtil.java:33) ~[portal-kernel.jar:?]
 [parallel]     at com.liferay.portal.dao.jdbc.DataSourceFactoryImpl.initDataSource(DataSourceFactoryImpl.java:176) [portal-impl.jar:?]
 [parallel]     at com.liferay.portal.kernel.dao.jdbc.DataSourceFactoryUtil.initDataSource(DataSourceFactoryUtil.java:39) [portal-kernel.jar:?]
 [parallel]     at com.liferay.portal.dao.init.DBInitUtil._initDataSource(DBInitUtil.java:231) [portal-impl.jar:?]
 [parallel]     at com.liferay.portal.dao.init.DBInitUtil.init(DBInitUtil.java:71) [portal-impl.jar:?]
 [parallel]     at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:260) [portal-impl.jar:?]
 ```

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by vicnate5** [comment]
@kyle-miho Can you look into the SetupWizard failures here?

It can be reproduced locally with SetupWizardHSQL#HSQLtoMySQLSampleDataEnabled. It seems to have something to do with the login not persisting on server restart.

**Comment by kyle-miho** [comment]
@vicnate5 ill create a ticket and have it re-login, if login persisting on server restart is something important we want to test, we can add a test for it (since this is a db upgrade test i assume its fine to just do the safest method of logging in)

**Comment by vicnate5** [comment]
@shuyangzhou @kyle-miho  I am still a little concerned about the login issue since it is an unexpected change of behavior on this PR. I also tested at head. I am also concerned this might impact users in a cluster scenario.

Steps to Reproduce:
1. Start Portal
2. Login to Test Test user
3. Restart Portal
4. Refresh home page after restart

Result
HEAD: User is still logged in
This PR: User is no longer logged in

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will look into the session persistent issue. So this does not really related to setup wizard, right? Just setup wizard test is relying on session persistent?

**Comment by vicnate5** [comment]
Yea, the setup wizard test just reveals the issue since it does a restart.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 I should have fixed the jndi and persist session issues. Have not worked on the websphere problem yet. Let's re-run the test to confirm that's the only problem left. Thanks!

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 https://github.com/shuyangzhou/liferay-portal/pull/10119/commits/64f6e5219188ce73bbcea0da95a87a09b16edf8a fix the websphere problem for me locally, let's see if it also fixes it on CI.

**Comment by vicnate5** [comment]
@shuyangzhou Running some targeted testing at https://github.com/shuyangzhou/liferay-portal/pull/10142. When you make further changes, cherry pick https://github.com/shuyangzhou/liferay-portal/pull/10142/commits/9b5005e8ef87c89f70725e3e9af11d748d2379c7 to here.

Remaining issues
1. Websphere looks like it started, but the test itself crashed. Re-running on my PR.
2. lpkg-startup-jdk8 caught an error, but it is a complex test, so I am still trying to narrow down the steps. Maybe the error is enough to tell you something. [Full log.](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390768/AXIS_VARIABLE=0,label_exp=!master/consoleText)
```
     [exec] 2021-07-02 12:14:31.936 ERROR [Catalina-utility-2][BasePortalLifecycle:69] java.lang.ClassCastException: [B cannot be cast to com.liferay.portal.kernel.model.User
     [exec] java.lang.ClassCastException: [B cannot be cast to com.liferay.portal.kernel.model.User
     [exec] 	at com.liferay.portal.events.ChannelSessionDestroyAction.run(ChannelSessionDestroyAction.java:40) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.events.SessionAction.processLifecycleEvent(SessionAction.java:28) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:87) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:68) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.servlet.PortalSessionDestroyer.doPortalInit(PortalSessionDestroyer.java:126) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.util.BasePortalLifecycle.portalInit(BasePortalLifecycle.java:44) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.util.PortalLifecycleUtil.register(PortalLifecycleUtil.java:75) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.util.BasePortalLifecycle.registerPortalLifecycle(BasePortalLifecycle.java:59) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.servlet.PortalSessionDestroyer.<init>(PortalSessionDestroyer.java:47) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.servlet.PortalSessionListener.sessionDestroyed(PortalSessionListener.java:74) [portal-impl.jar:?]
     [exec] 	at sun.reflect.GeneratedMethodAccessor355.invoke(Unknown Source) ~[?:?]
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [exec] 	at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:43) [com.liferay.shielded.container.impl.jar:?]
     [exec] 	at com.sun.proxy.$Proxy3.sessionDestroyed(Unknown Source) [?:?]
     [exec] 	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:798) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:656) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:606) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5574) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357) [catalina.jar:9.0.43]
     [exec] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335) [catalina.jar:9.0.43]
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
     [exec] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
     [exec] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
     [exec] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.43]
     [exec] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
     ````

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
