### PR TITLE
Lps 60415 Unable to stop scheduler engine caused by incomplete service dependencies

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi Shuyang,

I have a bug fix which depends on this one, several support tickets are waiting for that fix, could you please review this pull while you have time?


Thanks.
Tina.

**Comment by shuyangzhou** [comment]
Yeah, I will get on to this a moment later (today).

**Comment by shuyangzhou** [comment]
Ping me on Skype when you get back.

**Comment by shuyangzhou** [comment]
Please resend with an answer to the question we talked about.

**Pull request closed without merging**
