### PR TITLE
LPS-72939

### PR DESCRIPTION
**Pull request by samuelkong**
@shuyangzhou This is for security, but I also want someone on the Core Infrastructure to take a look at the change. Thanks.

cc @arthurchan35

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hi @shuyangzhou 

Do we have any update?

**Comment by shuyangzhou** [comment]
I am out of office this week. @tinatian please take this over, but first have @slnn run a regression test. This one seems risky.

**Comment by arthurchan35** [comment]
Thanks

**Comment by tinatian** [comment]
OK, I will take a look at it.

**Comment by slnn** [comment]
Test results for this pull please see [Test Results for LPS-72939](https://docs.google.com/spreadsheets/d/1KmRHRVjRQH_Ine8vPxoCbeoL9C0M9XQxRrr1BoYtW0Y/edit?usp=sharing)

**Comment by tinatian** [comment]
Thanks @slnn.

**Comment by samuelkong** [comment]
@tinatian or @shuyangzhou 
Any update on this?

**Comment by tinatian** [comment]
@samuelkong Sorry Sam, busy with some other stuff recently. I will try to take a look at it next week.

**Comment by tinatian** [comment]
@samuelkong @arthurchan35 
After your change, "http://///foo.com" will return "", but it should return "foo.com", could you please fix it.

Thanks.
Tina.

**Comment by samuelkong** [comment]
@tinatian 
This is working as expected. `http://///foo.com` is not a valid URL so it should _not_ return a domain.

**Comment by tinatian** [comment]
@samuelkong @arthurchan35 
The behavior of getDomain() is changed after your fix. Before with "http://///foo.com", it can return "foo.com", but after it return "". 
I am wondering if this is what you want. I am not sure from security's point of view, if the url is invalid, should we return a reasonable result or not? Before we did, but after your change, we do not. If you go to HttpImplTest.testRemoveProtocol(), you would see we handled invalid url too.

If you think invalid url should not be handled, I think you should also modify other methods (for example removeProtocol()) in HttpImpl to make the behavior consistent. 


Thanks.
Tina.

**Comment by arthurchan35** [comment]
Hi @tinatian 
I  dont have code with me right now but for the best coding practice, I would argue that a function named getDomain(String url) should fail to output a result for an invalid input, either throwing an exception or returning an empty string, or something.
And we actually have thought about changing other methods in httpImpl class, since I believe java's URI class provides better and more accurate parsing(if we want to strictly follow the standard and syntax). Maybe we should consider switching to use it for all the possible impl methods.
However the problem is that, these are not the task for this pull request. This pull request is solely for a security issue caused by wrong parsing impl from getDomain().
I will talk to Sam tomorrow to see what we can do, and please let us know what you think as well.

Thanks

**Comment by tinatian** [comment]
Hi @arthurchan35 ,
I think the issue was getDomain() did not handle reserved characters like "@", right? If your change only  fix this part, I can accept it.
The thing is you changed how it handled url like "http://///foo.com", and make it inconsistent with other method. It's better you did not change it or change all of them, either way it makes sense to me, just do not leave a inconsistent status here, since it would make people confused, suppose I have a invalid url like "http://///foo.com", I try to getDomain(), I will fail. But if I do removeProtocol() first, then getDomain(), I will pass. 

Thanks.
Tina.

**Comment by arthurchan35** [comment]
Hi @tinatian 
After discussing with Sam, we still believe removeProtocol() should not give "foo.com" with an input of "http://////foo.com". To give "foo.com", we are basically  saying http:///// is a protocol, which is obviously not correct.
And I understand that you mentioned removeProtocol() is handling invalid inputs such as "http://///foo.com" by outputting a valid result, but there are tons of other invalid inputs, why do we output valid result for only some of them?
I believe we need a standard handling method for all invalid inputs, like I mentioned earlier, either throwing exception or returning empty string.

To make removeProtocol() work as expect, we can create a different ticket.

Thanks

**Comment by shuyangzhou** [comment]
@samuelkong @arthurchan35 
I think @tinatian has a point. Bottom line, we should keep this:
By given the same url as input, getDomain() should return something that is a prefix(or the same) of removeProtocol()'s return value. Otherwise we will have a very inconsistent behavior. And if we want to make this change, they need to be changed together, not in a separated ticket.

**Comment by arthurchan35** [comment]
@shuyangzhou, @tinatian,
So I spent some time yesterday and found out that the code of removing leading slashes was added in LPS-59425 to prevent bypassing domain check by having leading slashes.
I did a quick test and saw that my fix in LPS-72939 was able to do the same thing, so I removed the code.
I did have full test environment, but as far as I can it's fine to remove the code. Let me if I was missing somethig.

Thanks

**Comment by samuelkong** [comment]
ci:reopen

**Comment by tinatian** [comment]
@arthurchan35 @samuelkong 
I do not think the behavior is consistent after your change. It may only handled the "http://////foo.com", what about "http://http://foo.com"?

Could you please take a look at it?

Thanks.
Tina.

**Comment by arthurchan35** [comment]
ci:close

**Pull request closed without merging**
