### PR TITLE
[TECHNICAL-SUPPORT] LPS-79309 Another Friendly URL bug

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@shuyangzhou can we ask Brian to hold off on backporting this one.  We have a lot of issues with friendly URLs and this is only a problem when not using the default configuration.

**Comment by shuyangzhou** [comment]
If this can not be backported, then it should not be sent at this phase. It should only happen after the release.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61068

**Pull request closed without merging**
