### PR TITLE
LPS-86378 Remove if the bundle has been uninstalled

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

GitHub seems to be throwing some strange errors..

```
prepare-release-tool-repository:
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-release-tool-ee/git/refs/heads/master in 5 seconds
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-release-tool-ee/git/refs/heads/master in 5 seconds
     [echo] Generating Jenkins report.
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20190528232144199
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-release-tool-ee/git/refs/tags/master in 5 seconds
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-release-tool-ee/git/refs/tags/master in 5 seconds
[beanshell] 4227 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 12 minutes 37 seconds 2 ms.
[beanshell]     https://api.github.com/repos/liferay/liferay-release-tool-ee/git/refs/tags/master
[beanshell] 4226 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 12 minutes 36 seconds 565 ms.
[beanshell]     https://api.github.com/repos/shuyangzhou/liferay-portal/pulls/7835
[beanshell] Executing commands: cat /tmp/-2021525246.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:10813: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:10830: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:775: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:402: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5898: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:1556: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : TargetError : at Line: 40 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : throw new FileNotFoundException ( "Unable to find reference " + ref + " within " + username + "/" + repository ) ; 

Target exception: java.io.FileNotFoundException: Unable to find reference master within liferay/liferay-release-tool-ee
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73866

**Pull request closed without merging**
