### PR TITLE
LPS-69532 Add a integration test for GroovyExecutor

### PR DESCRIPTION
**Pull request by inacionery**
Hi @shuyangzhou,

I'm creating an integration test for the issue https://issues.liferay.com/browse/LPS-69532, but I'm facing "java.lang.OutOfMemoryError: Java heap space" on CI (https://github.com/marcellustavares/liferay-portal/pull/1796). I managed to isolate the problem, it occur in GroovyExecutor, so I created this PR with an integration test for GroovyExecutor to reproduce the issue.

Could you please help me with it? 

Thanks advanced!

/cc @marcellustavares  @pyoo47

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Preston-Crary please help @inacionery on this, thanks!

**Comment by Preston-Crary** [comment]
Sure, I'll make sure to take a look at this sometime tomorrow.

**Comment by marcellustavares** [comment]
thanks @Preston-Crary

**Comment by Preston-Crary** [comment]
Hey @inacionery,

how did you isolate the problem to GroovyExecutor?  The pull you linked doesn't seem related to me, but I'm not very familiar with Kaleo.

From looking at this pull groovy consumes an additional 3.3 MB of the heap after being run.  Since the failure is too old to view I'm doing some additional testing and will comment here if I find something.

**Comment by marcellustavares** [comment]
@Preston-Crary, Inacio logged every line of code to get the to this conclusion. The OOM happened when the groovy engine was triggered.

The problem is not related to Kaleo. Every integration tests with the Groovy engine should fail due lack of heap.

Thanks for the help.

**Comment by Preston-Crary** [comment]
I was able to get the GroovyExecutor test in this pull to pass after some changes, see:
https://github.com/Preston-Crary/liferay-portal/pull/246

**Comment by inacionery** [comment]
I'll close this to continues on https://github.com/Preston-Crary/liferay-portal/pull/253

Thanks a lot!!

**Pull request closed without merging**
