### PR TITLE
LPS-101084 Apply view count service to AssetEntry

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
There is a post-upgrade startup issue now. It occurs only on 7.1 databases, and on 4 out of the 7 test runs. Possible race issue due to inconsistent results, but it is unique to this PR.

```
02:16:57,098 INFO  [main][SystemCheckOSGiCommands:114] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
02:17:04,057 WARN  [main][SystemCheckOSGiCommands:137] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 76, name: com.liferay.portal.workflow.web, version: 3.0.0}
	Declarative Service {id: 38, name: com.liferay.portal.workflow.web.internal.portlet.action.SaveWorkflowDefinitionMVCActionCommand, unsatisfied references: 
		{name: unproxiedWorkflowDefinitionManager, target: (proxy.bean=false)}
	}
	Declarative Service {id: 37, name: com.liferay.portal.workflow.web.internal.portlet.action.RevertWorkflowDefinitionMVCActionCommand, unsatisfied references: 
		{name: unproxiedWorkflowDefinitionManager, target: (proxy.bean=false)}
	}
	Declarative Service {id: 35, name: com.liferay.portal.workflow.web.internal.portlet.action.DuplicateWorkflowDefinitionMVCActionCommand, unsatisfied references: 
		{name: unproxiedWorkflowDefinitionManager, target: (proxy.bean=false)}
	}
	Declarative Service {id: 34, name: com.liferay.portal.workflow.web.internal.portlet.action.DeployWorkflowDefinitionMVCActionCommand, unsatisfied references: 
		{name: unproxiedWorkflowDefinitionManager, target: (proxy.bean=false)}
	}
Bundle {id: 80, name: com.liferay.portal.workflow.metrics.rest.impl, version: 2.0.0}
	Declarative Service {id: 68, name: com.liferay.portal.workflow.metrics.rest.internal.resource.v1_0.SLAResourceImpl, unsatisfied references: 
		{name: _workflowMetricsSLADefinitionLocalService, target: null}
	}
	Declarative Service {id: 51, name: com.liferay.portal.workflow.metrics.rest.internal.graphql.servlet.v1_0.ServletDataImpl, unsatisfied references: 
		{name: _instanceResourceComponentServiceObjects, target: null}
		{name: _slaResourceComponentServiceObjects, target: null}
	}
	Declarative Service {id: 62, name: com.liferay.portal.workflow.metrics.rest.internal.resource.v1_0.InstanceResourceImpl, unsatisfied references: 
		{name: _workflowMetricsSLADefinitionLocalService, target: null}
	}
...
```

Full Liferay startup log
https://testray.liferay.com/reports/production/logs/test-1-16/1571358294988/test-portal-acceptance-pullrequest(master)/4900/functional-upgrade-tomcat90-mysql57-jdk8/2/0/liferay-log.txt.gz

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
Additional issues:

Unit test failure: `com.liferay.portal.tools.PortalClientBuilderTest.testPortalClientBuilder`
https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/348511/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.tools/PortalClientBuilderTest/testPortalClientBuilder/

Modules Integration startup on DB2 only
```
bundle com.liferay.portal.upgrade.impl:4.0.0 (299)[com.liferay.portal.upgrade.internal.release.osgi.commands.ReleaseManagerOSGiCommands(1193)] : The activate method has thrown an exception 
com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
```
https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/85491/AXIS_VARIABLE=9,label_exp=!master/consoleText

**Comment by shuyangzhou** [comment]
@stsquared99 this pull is not on top of https://github.com/shuyangzhou/liferay-portal/pull/8401quite a few commits are missing. Plus these current issues. Please fix and resend.

**Comment by stsquared99** [comment]
@shuyangzhou My bad, I rebased on the PR you sent me which I thought was the same as this. Resent as https://github.com/shuyangzhou/liferay-portal/pull/8407

**Pull request closed without merging**
