### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**
@achaparro thanks for the reminder to check, see 665b71c.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
@vicnate5 test failures don't look related to the changes to me, can you confirm?

**Comment by vicnate5** [comment]
@Preston-Crary Confirmed, failures not related.

Probably worth running the full upgrade suite on this now, will trigger.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
Hi @Preston-Crary 

With this pull, NPE appeared when invoking SampleSQLBuilder to generate sample data for AssetPublisher.

I fix the test to expose this issue please see the last commit in this pull:https://github.com/slnn/liferay-portal/pull/511

Here is the stack trace:

```
2020-11-06 12:39:37.827 ERROR [Thread-4][runtime:59] Error executing FreeMarker template
    FreeMarker template error:
    Java method "com.liferay.portal.tools.sample.sql.builder.DataFactory.newAssetPublisherPortletPreferenceValueModels(com.liferay.portal.kernel.model.PortletPreferencesModel, long, int)" threw an exception when invoked on com.liferay.portal.tools.sample.sql.builder.DataFactory object "com.liferay.portal.tools.sample.sql.builder.DataFactory@70d91d1c"; see cause exception in the Java stack trace.

    ----
    FTL stack trace ("~" means nesting-related):
    	- Failed at: #assign assetPublisherPortletPreferen...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/asset_publisher.ftl" at line 24, column 9]
    	- Reached through: #include "asset_publisher.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/groups.ftl" at line 16, column 9]
    	- Reached through: #include "groups.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/sample.ftl" at line 15, column 1]
    ----

    Java stack trace (for programmers):
    ----
    freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
    	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
    	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
    	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
    	at freemarker.core.MethodCall._eval(MethodCall.java:62)
    	at freemarker.core.Expression.eval(Expression.java:101)
    	at freemarker.core.Assignment.accept(Assignment.java:134)
    	at freemarker.core.Environment.visit(Environment.java:367)
    	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
    	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
    	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
    	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
    	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
    	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.include(Environment.java:2694)
    	at freemarker.core.Include.accept(Include.java:171)
    	at freemarker.core.Environment.visit(Environment.java:367)
    	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
    	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
    	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
    	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
    	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
    	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.include(Environment.java:2694)
    	at freemarker.core.Include.accept(Include.java:171)
    	at freemarker.core.Environment.visit(Environment.java:331)
    	at freemarker.core.Environment.visit(Environment.java:337)
    	at freemarker.core.Environment.process(Environment.java:310)
    	at freemarker.template.Template.process(Template.java:383)
    	at com.liferay.portal.freemarker.FreeMarkerUtil.process(FreeMarkerUtil.java:47)
    	at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder.lambda$generateSQL$0(SampleSQLBuilder.java:249)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException
    	at com.liferay.portal.tools.sample.sql.builder.DataFactory.newAssetPublisherPortletPreferenceValueModels(DataFactory.java:1145)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
    	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
    	... 32 more

com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderTest > testGenerateAndInsertSampleSQL FAILED
    java.lang.Exception: Unable to process FreeMarker template 
        at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder.compressSQL(SampleSQLBuilder.java:196)
        at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder.<init>(SampleSQLBuilder.java:80)
        at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderTest.testGenerateAndInsertSampleSQL(SampleSQLBuilderTest.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        freemarker.core._TemplateModelException: Java method "com.liferay.portal.tools.sample.sql.builder.DataFactory.newAssetPublisherPortletPreferenceValueModels(com.liferay.portal.kernel.model.PortletPreferencesModel, long, int)" threw an exception when invoked on com.liferay.portal.tools.sample.sql.builder.DataFactory object "com.liferay.portal.tools.sample.sql.builder.DataFactory@70d91d1c"; see cause exception in the Java stack trace.

        ----
        FTL stack trace ("~" means nesting-related):
        	- Failed at: #assign assetPublisherPortletPreferen...  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/asset_publisher.ftl" at line 24, column 9]
        	- Reached through: #include "asset_publisher.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/groups.ftl" at line 16, column 9]
        	- Reached through: #include "groups.ftl"  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/sample.ftl" at line 15, column 1]
        ----
            at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
            at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
            at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
            at freemarker.core.MethodCall._eval(MethodCall.java:62)
            at freemarker.core.Expression.eval(Expression.java:101)
            at freemarker.core.Assignment.accept(Assignment.java:134)
            at freemarker.core.Environment.visit(Environment.java:367)
            at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
            at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
            at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
            at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
            at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
            at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
            at freemarker.core.Environment.visit(Environment.java:331)
            at freemarker.core.Environment.visit(Environment.java:337)
            at freemarker.core.Environment.include(Environment.java:2694)
            at freemarker.core.Include.accept(Include.java:171)
            at freemarker.core.Environment.visit(Environment.java:367)
            at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
            at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
            at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
            at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
            at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
            at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
            at freemarker.core.Environment.visit(Environment.java:331)
            at freemarker.core.Environment.visit(Environment.java:337)
            at freemarker.core.Environment.include(Environment.java:2694)
            at freemarker.core.Include.accept(Include.java:171)
            at freemarker.core.Environment.visit(Environment.java:331)
            at freemarker.core.Environment.visit(Environment.java:337)
            at freemarker.core.Environment.process(Environment.java:310)
            at freemarker.template.Template.process(Template.java:383)
            at com.liferay.portal.freemarker.FreeMarkerUtil.process(FreeMarkerUtil.java:47)
            at com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilder.lambda$generateSQL$0(SampleSQLBuilder.java:249)
            ... 1 more

            Caused by:
            java.lang.NullPointerException
                at com.liferay.portal.tools.sample.sql.builder.DataFactory.newAssetPublisherPortletPreferenceValueModels(DataFactory.java:1145)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
                at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
                ... 32 more
```

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9577

**Pull request closed without merging**
