### PR TITLE
Lps 103581

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@shuyangzhou please review, failures look unrelated

@mtambara `lpkg-controller` is still failing for [LPS-103476](https://issues.liferay.com/browse/LPS-103476)
```
init-build-app:

get-osgi-static-modules:

dist-module-artifacts-lpkg:
 [loadfile] /opt/dev/projects/github/liferay-portal/modules/apps/opensocial/opensocial-portlet/build.gradle doesn't exist

get-artifact-properties-bnd:

get-artifact-properties-json:

get-artifact-properties-legacy:

get-artifact-properties:

move-artifact:
[stopwatch] [run.batch.test.action: 38.655 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:368: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1765: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:2738: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:183: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:185: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:442: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:463: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/opensocial-portlet-7.2.0.1.war to copy.
```
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/329539//consoleText

**Comment by mtambara** [comment]
@jpince https://github.com/brianchandotcom/liferay-portal/pull/80096 hadn't been merged yet when this test started, should be fixed in upstream now

**Comment by jpince** [comment]
@mtambara got it, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80128

**Pull request closed without merging**
