### PR TITLE
LPS-93265

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@slnn upgraded ehcache, regression tests required, thanks!
CC @tinatian

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou 
Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 15610 | 311 | 79.3 | -
PR-7589 | - | 15766 | 309 | 79.5 | 0.999359385

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 20709 | 378 | 155 | -
PR-7589 | - | 20060 | 393 | 155 | -3.133903134

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 7456 | 176 | 339 | -
PR-7589 | - | 7671 | 192 | 351 | 2.883583691

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 5201 | 81.6 | 316 | -
PR-7589 | - | 5153 | 95.8 | 325 | -0.9228994424

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 8085 | 345 | 673 | -
PR-7589 | - | 8098 | 425 | 750 | 0.1607915894

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 9171 | 142 | 158 | -
PR-7589 | - | 9015 | 133 | 157 | -1.701014066

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | e7d0563 | 5656 | 339 | 716 | -
PR-7589 | - | 5700 | 382 | 751 | 0.7779349364

Lily

**Comment by dantewang** [comment]
@shuyangzhou Is it possible to turn off baseline specifically for `portal-cache-ehcache-provider`? If not, we may need to find another way to deploy ehcache to avoid SemVer failure.

**Comment by shuyangzhou** [comment]
@petershin can you help on this? We should disable baseline for portal-cache-ehcache-provider. It is better to be able to specify which packages we want to ignore.

@samuelkong please resend after the semantic versioning issue is fixed. The perf numbers are ok, we just need to solve this CI test failure.

**Comment by shuyangzhou** [comment]
@petershin can you help on this? We should disable baseline for portal-cache-ehcache-provider. It is better to be able to specify which packages we want to ignore.

@samuelkong please resend after the semantic versioning issue is fixed. The perf numbers are ok, we just need to solve this CI test failure.

**Comment by yxingwu** [comment]
@petershin 
Can you let us know after it's fixed so that we can resend. Thanks.

**Comment by petershin** [comment]
@shuyangzhou @yxingwu - Sent a patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/71604

**Pull request closed without merging**
