### PR TITLE
LPS-132600 Missing DDMFieldAttribute references

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
I know this is a complex problem, and the solution is also very complex, I am just worrying the future maintaining overhead for those query structures, although I don't know how can we do better.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@shuyangzhou me too. I think maybe we can do something to simplify the DDMFieldAttribute table so that we don't need the DSLFunctions... but I'm not sure what way to change it.  The whole problem will get more complex with import, because then my plan is rewrite the same queries for update - setting values instead of joining on columns.

**Pull request closed without merging**
