### PR TITLE
[Bug Fix]LPS-119196 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang, 

Please see here for the detailed reason we made this change https://issues.liferay.com/browse/LPS-119196?focusedCommentId=2272803&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2272803.

FYI @marianoalvarosaiz

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9465

**Pull request closed without merging**
