### PR TITLE
LPS-165371 Prepare for previously cached missing results.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
@vicnate5 I found the root cause to the issue and it's not related to this one. We can forward this if there aren't any other failures

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures in the test results, just some of the tests were aborted as you already knew. This should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124483

**Pull request closed without merging**
