### PR TITLE
LPS-92940 DS calendar-service

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@lanceji92674957, sent before we had test results. Please fix the two test failures and resend, most likely it's just an issue with the tests themselves, thanks!

**Comment by lanceji92674957** [comment]
@Preston-Crary the test failures are related to workflow, which I've seen all over upstream as well. I'm not sure it is caused by our changes, I'll retest it once the workflow issue disappears on upstream.

**Comment by Preston-Crary** [comment]
@lanceji92674957 okay, I'll leave it up to @shuyangzhou

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70428

**Pull request closed without merging**
