### PR TITLE
[Bug Fix]LPS-141792

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@dantewang can you add an integration test to assert there is no duplicated entries? For future protection.

**Comment by dantewang** [comment]
@shuyangzhou Got it.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
