### PR TITLE
LPS-81342 Portlet 3.0: Add portlet_3_0 taglib to web.xml during WAR deployment

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR has 1 commit that simply adds the following to WEB-INF/web.xml when a WAR is deployed:
```
<taglib>
	<taglib-uri>http://xmlns.jcp.org/portlet_3_0</taglib-uri>
	<taglib-location>/WEB-INF/tld/liferay-portlet.tld</taglib-location>
</taglib>
```
Since this taglib URI is never referenced by any of our out-of-the-box JSPs, I can't see how any of these failures are related. In addition, I've seen most (if not all) of these same failures with other pull requests today.

Please review when you get an opportunity. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61226

**Pull request closed without merging**
