### PR TITLE
Lps 122561

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara this can be very heavy on startup, right?

@slnn please run a diff on this, do it after the current regression finding, thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou @mtambara 

I have checked the startup performance against this pull https://github.com/mtambara/liferay-portal/pull/1019, please see test results on the origin pull:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 18b99e456 | 42822 | 22613 | 22422 | 22585 | 22248 | 22730 | 23080
PR | - | 53525 | 23610.2 | 23000 | 23836 | 23497 | 23728 | 23990


Will double check the new pull later.
Lily

**Comment by shuyangzhou** [comment]
@mtambara this is too heavy, I don't think we should make this feature change. Let's keep the old simple checksum, even it is not strong enough to prevent meaningless updating, but it is still cheaper that way.

**Comment by slnn** [comment]
Hi @shuyangzhou  @mtambara 

Please see test results for 2020-11-10  in this doc:https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit?usp=sharing

We can see the slowly with different machines.

Lily

**Pull request closed without merging**
