### PR TITLE
LPS-65125 PortalCacheIndexer's PortalCacheListeners are not registered with custom ehcache settings

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@shuyangzhou this should be ready to go. The same test failures are occurring on other pulls to Brian.

**Comment by shuyangzhou** [comment]
How is the semantic versioning still failing?
ci:retest

**Comment by shuyangzhou** [comment]
Oh, right, Tina just removed portal-cache-memory last night, should be an easy fix. Can you resend?

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/2864

**Pull request closed without merging**
