### PR TITLE
LPS-83801 Cache class restriction computation

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @tinatian @slnn

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by slnn** [comment]
Hi all,

We have checked the performance for LPS-83801 with this pull: https://github.com/slnn/liferay-portal/pull/324

@csierra If you make different changes in this pull I think I need rerun tests for it.

Lily

**Comment by csierra** [comment]
hi @slnn,
I assumed the change I made would not affect performance (I only changed the cached value) but maybe I am wrong. 
I am sending the pull to you again so you can test it if needed (https://github.com/slnn/liferay-portal/pull/325)
Thx.

**Comment by slnn** [comment]
Here are test results for this pull:https://github.com/slnn/liferay-portal/pull/325
No noticeable performance regression.

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 75a901d | 48979 | 288 | 88.1
PR-325 | - | 48211 | 274 | 83

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 75a901d | 13583 | 56.8 | 157
PR-325 | - | 13523 | 85.8 | 187


MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 75a901d | 15691 | 25.6 | 60
PR-325 | - | 15619 | 23.9 | 60.9

Asset Publisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 75a901d | 25834 | 474 | 207
PR-325 | - | 25153 | 495 | 216

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 75a901d | 16421 | 406 | 594
PR-325 | - | 16654 | 395 | 576

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 75a901d | 63794 | 568 | 195
PR-325 | - | 62733 | 561 | 196

Document Library:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 75a901d | 26777 | 328 | 402
PR-325 | - | 26593 | 256 | 340

**Comment by csierra** [comment]
thx @slnn!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62602

**Pull request closed without merging**
