### PR TITLE
LPS-72742 prepare all portlets on layout te be sure that public render parameters are available for all portlets

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @shuyangzhou, we need this change in order to pass https://issues.liferay.com/browse/LPS-72482. Could you please take a look and pass it in case if it make sense? Thanks!

cc @ealonso

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49232

**Pull request closed without merging**
