### PR TITLE
[FinderCache]Lps 119013 lps 118633 lps 108614 3

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on https://github.com/shuyangzhou/liferay-portal/pull/9338.

I need to send LPS-118633 and LPS-108614 together to avoid performance regression see performance test result here: https://github.com/tinatian/liferay-portal/pull/1940#issuecomment-674815026.

FYI @GinsonRen @dantewang @slnn @vicnate5

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test result of ci:test?

Thanks
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found in the test results.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9344

**Pull request closed without merging**
