### PR TITLE
Template portlet preferences

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian Please see https://github.com/shuyangzhou/liferay-portal/commit/4024ad80a345e4c4e820710eb9cd1d284e95b3a2

**Comment by shuyangzhou** [comment]
@tinatian one more change https://github.com/shuyangzhou/liferay-portal/pull/3984/commits/a078232d5c515df75e1006486f296376adb22b3f
CI is not working now, please review to make sure I did not break anything.

**Comment by shuyangzhou** [comment]
@tinatian I think we have a problem here, if someone actually pass in a non String/String[]/null value, we will end up having <name> tag without <value> tag, which could be a problem, right?

**Comment by tinatian** [comment]
Yes, that might be a problem for passing in a non-string/string[] value, we can add another else to throw an exception or just convert that object to string, which one do you think is better?

**Comment by shuyangzhou** [comment]
@tinatian See https://github.com/shuyangzhou/liferay-portal/pull/3984/commits/bf51173b54b176876315da2e3f929c9a084c8239

I just realized there is no reason to do the NULL_VALUE placeholder, simply throw away nulls, on getting we will return null anyway. And for other data types, we just don't handle them, same as before.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47724

**Pull request closed without merging**
