### PR TITLE
Push down portlet jar

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, especially for jboss/wildfly and websphere as this has more impact to them.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The biggest issue here is on Websphere startup
```
  [waitfor] 2021-04-09 09:01:21.063 WARN  [WebContainer : 0][code_jsp:143] {code="500", msg="JSPG0049E: /html/portal/render_portlet.jsp failed to compile : 
  [waitfor] 
  [waitfor] JSPG0091E: An error occurred at line: 663 in the file: /html/portal/render_portlet.jsp
  [waitfor] JSPG0093E: Generated servlet error from file: /html/portal/render_portlet.jsp 
  [waitfor] 
  [waitfor] /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/temp/liferay-node/server1/liferay-portal/liferay-portal.war/html/portal/_render_5F_portlet.java : 1067 : The method getRenderParameters&#40;&#41; is undefined for the type LiferayPortletURL
  [waitfor] ", uri=/html/common/themes/portal.jsp}
  [waitfor] com.ibm.ws.jsp.JspCoreException: JSPG0049E: /html/portal/render_portlet.jsp failed to compile : 
  [waitfor] 
  [waitfor] JSPG0091E: An error occurred at line: 663 in the file: /html/portal/render_portlet.jsp
  [waitfor] JSPG0093E: Generated servlet error from file: /html/portal/render_portlet.jsp 
  [waitfor] 
  [waitfor] /opt/dev/projects/github/liferay-portal/bundles/websphere-9.0.0.0/profiles/liferay/temp/liferay-node/server1/liferay-portal/liferay-portal.war/html/portal/_render_5F_portlet.java : 1067 : The method getRenderParameters() is undefined for the type LiferayPortletURL
  [waitfor] 
  [waitfor] 	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:616) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:477) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:298) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.findWrapper(AbstractJSPExtensionProcessor.java:498) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.getServletWrapper(AbstractJSPExtensionProcessor.java:338) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1012) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1408) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.include(WebAppRequestDispatcher.java:553) ~[com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
  [waitfor] 	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
  [waitfor] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
  [waitfor] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
  [waitfor] 	at com.liferay.portal.servlet.TransferHeadersHelperImpl$TransferHeadersRequestDispatcher.include(TransferHeadersHelperImpl.java:162) ~[portal-impl.jar:?]
  ```

Full log https://testray.liferay.com/reports/production/logs/2021-04/test-1-7/test-portal-acceptance-pullrequest(master)/6986/functional-smoke-websphere90-mysql57-jdk8/0/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@dantewang can you try to set liferay installation's classloader mode to parent last on websphere? See if it can fix this problem. I suspect it won't be this simple, otherwise we would deploying the jar globally first. But better to test it to confirm.
@vicnate5 in the worst case scenario, we will have to keep doing the same deployment for websphere until it upgrades to portlet 3.

**Comment by dantewang** [comment]
@shuyangzhou I'll try, but parent last in the past causes other problems I remember.

**Comment by dantewang** [comment]
@shuyangzhou Hai helped testing on Websphere:

1. Setting Websphere Application Server "server1" classloading mode as "Parent Last"
2. Setting "server1" classloading policy as "Multiple" (each deployed application has its own class loader) and setting application "liferay-portal" classloading mode as "Parent Last"

In both scenarios there are a lot of exceptions during portal startup and visting portal pages. For example, https://gist.github.com/yuhai/68c8f8f5bcbcaf514cdd895ba89cba74

I think "Parent Last" mode introduces some extra problems.

**Comment by shuyangzhou** [comment]
Alright, thanks for confirming @dantewang @yuhai !
@vicnate5 I think we should give up on pushing down portlet jar for websphere. I will adjust this pull and retest.

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This looks good now. No regressions in the test results. I also checked the upgrade results we ran previously.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9937

**Pull request closed without merging**
