### PR TITLE
LPS-X Push down activation and mail to portal-web scope.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9996

**Pull request closed without merging**
