### PR TITLE
Startup optimization 47 faster page count checking

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 this is actually just on top of https://github.com/shuyangzhou/liferay-portal/pull/10748 with one more commit, if that matters.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found, the unique failures must be flaky since I did not reproduce them locally.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122083

**Pull request closed without merging**
