### PR TITLE
LPS-84138 Cache Reload

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63384

**Comment by shuyangzhou** [comment]
See the failures at https://github.com/brianchandotcom/liferay-portal/pull/63384#issuecomment-424160600

Please fix and resend.

**Comment by tinatian** [comment]
@shuyangzhou Seems I need to rebase, will send a pull to Brian directly later.

Tina.

**Comment by tinatian** [comment]
@shuyangzhou See https://github.com/brianchandotcom/liferay-portal/pull/63415

**Pull request closed without merging**
