### PR TITLE
ContextResourcePathsUtil

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please scan the results for me, thanks!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou Errors in log after upgrading (startup and then login).
```
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/web/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/web/fragment/internal/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/web/fragment/internal/content/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/web/fragment/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/web/fragment/internal/content/transformer/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /OSGI-INF/l10n/ is null
ERROR [http-nio-8080-exec-7][FileTimestampUtil:86] Resource URL for /com/liferay/adaptive/media/blogs/ is null
```
Will send you the database.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou test failures not related

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76120

**Pull request closed without merging**
