### PR TITLE
LPS-128098 Add support for generic methods with type parameters in Service Builder

### PR DESCRIPTION
**Pull request by achaparro**
Hey @shuyangzhou, I figured out how to add to support for generic methods in Service Builder. I executed build-services locally and it worked :tada:

I need this change to move the methods regarding companies to the service as you told me.

Let me know if you have any questions.

Thanks

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@achaparro Please resend without using Stream. Stream is generally a bad thing to do in terms of performance. Also I get why you need to make this change, but try to not use Stream in the company local service methods too. It is ok to keep the "forEach" style, just do not use stream unless it is absolutely necessary (in example like using a lib which only has Steam as API).

**Comment by achaparro** [comment]
ci:stop

**Pull request closed without merging**
