### PR TITLE
LPS-86076 Extract executor lifecycle control from BufferedIncrementAdvice

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Seeing the same failure on some of Brian's pulls.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64173

**Pull request closed without merging**
