### PR TITLE
LPS-X Merge FFBalloonEditorConfigurationUtil into CKEditorBalloonEdit…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…orConfigContributor

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. `PortalSmokeUpgrade#ViewPortalSmokeArchive621021` failed here, but it passed locally.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130819

**Pull request closed without merging**
