### PR TITLE
Jaxrs resource

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@koor4356 can you analyze this? At minimum, the Commerce failures look real. Can you reproduce locally and provide manual steps to reproduce?

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
I changed to a different solution, please see https://github.com/shuyangzhou/liferay-portal/pull/9604

**Comment by koor4356** [comment]
Okay, thank you.

**Pull request closed without merging**
