### PR TITLE
[TECHNICAL-SUPPORT] LPS-104291

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please review.

**Comment by mtambara** [comment]
@shuyangzhou looks good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80625

**Pull request closed without merging**
