### PR TITLE
LPS-83992 Register from scanned annotations, implement CDI scopes and bean producers

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains several commits that fortify the cdi-bean-portlet-extension. The two failures reported in the test results are unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
@ngriffin7a will we ever call this at runtime after construction ? https://github.com/shuyangzhou/liferay-portal/blob/c35f810da47d814a7ff7e4b49d2ec198ee99acf4/modules/apps/bean-portlet-cdi-extension/src/main/java/com/liferay/bean/portlet/cdi/extension/internal/BeanApp.java#L40

**Comment by ngriffin7a** [comment]
@shuyangzhou Yes, when scanning for the `@PortletApplication` annotation, or when parsing WEB-INF/portlet.xml, then the `BeanApp.setDefaultNamespace(String)` method will get called. Even though BeanApp.java is an interface, it exists in the "internal" sub-package so it's not really API. It's just that we have to implementations of it: One for annotation scanning and another for portlet.xml parsing.

**Comment by shuyangzhou** [comment]
@ngriffin7a this doesn't sound right. If we have to modify it, it will be at implement level with a real instance where we know the concrete type. This should not exist at interface level, even for an internal one. Internal or external only matters for OSGi, does not really change the design practice. 

I am going to remove this, as right now there is no need of it. If later it is really needed, we can add it back at implementation level.

**Comment by ngriffin7a** [comment]
@shuyangzhou Right now you are seeing BeanAppAnnotationImpl.java, but in the next pull request I will send BeanAppDescriptorImpl.java -- I will just have to add it back if you remove it. Perhaps I didn't answer your question correctly -- not sure why this doesn't sound right.

**Comment by ngriffin7a** [comment]
@shuyangzhou Also in the future I might consider moving BeanApp.java and BeanPortlet.java to an API in a separate JAR, in an effort to support both CDI bean portlets and Spring bean portlets. In that case, there could be a BeanAppSpringImpl.java as well.

**Comment by shuyangzhou** [comment]
@ngriffin7a that's ok, it is very hard for me to make decisions without seeing the whole thing. So I am only going to do what is right base on what is inside this pull. And I think most likely it will still be right with your following changes, but of course you will need to adjust it. But if it does not fit anymore, we can go back against it.

**Comment by shuyangzhou** [comment]
@ngriffin7a that's ok, let's stay with current workflow, the worst case is we go back and forth a bit, still better than not making progress at all.

**Comment by ngriffin7a** [comment]
@shuyangzhou Do you think that you might be able to complete this code review today? I'm working on fixing some bugs in the codebase that might cause diffs with the changes you plan on making. I'd prefer to work with your code review commits instead.

**Comment by shuyangzhou** [comment]
I am working on it now. I have made many changes, and there will be more. I can try, but I can not guarantee it will be finished today.

**Comment by ngriffin7a** [comment]
@shuyangzhou OK I'll work on something else for now. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62867

Sorry, @ngriffin7a . I made many changes, which will make your rebase a lot harder. I was actually trying to make more changes, but without seeing the reset commits from you, it is just too hard to decide. So I left them alone. I will do a final rescan in the end to catch up those missed ones.
Please test my changes, as I have no way to test it, most likely I might have broke something already.

**Comment by ngriffin7a** [comment]
@shuyangzhou Your code review commits ROCK! And my rebase was painless, not a single conflict. I will test all the changes before sending another PR with the XML parsing. Thanks for working so late into the night to get this done. :)

/cc @brianchandotcom

**Pull request closed without merging**
