### PR TITLE
LPS-117190 By default Liferay should assume that osgi configuration files are encoded in UTF-8

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @shuyangzhou 

Could you please review this pull request?

Please see the explanation in the [LPS](https://issues.liferay.com/browse/LPS-117190).

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
Hi @shuyangzhou 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by shuyangzhou** [comment]
@IstvanD this is wrong, it won't work, there is no more fileinstall in our system, it has been inlined into our codebase, and I pretty much that property won't do anything.

@mtambara please take this over and make sure to add an unit test for it. And please follow up with @IstvanD to update him with your progress, thanks!

**Comment by IstvanD** [comment]
Hi @shuyangzhou 

I have sent @mtambara a new [pull](https://github.com/mtambara/liferay-portal/pull/994) with the corrected changes. They are working on master as expected.

**Pull request closed without merging**
