### PR TITLE
Startup optimization 45 group type

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:echo-acceptance

**Comment by vicnate5** [comment]
@shuyangzhou Unique failure in upgrade integration test, I was able to reproduce locally.
https://testray.liferay.com/home/-/testray/case_results/1950951920

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 my bad, it should be "type_" rather than "type". Rerunning upgrade tests

**Comment by shuyangzhou** [comment]
@vicnate5 are the new results ok?

**Comment by vicnate5** [comment]
@shuyangzhou No results are good, this branch will need a rebase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122007

**Pull request closed without merging**
