### PR TITLE
[TS] LPS-138089

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-138089

With the relatively minimal functional changes done, the PortalImpl test classes still cover all the cases I need.  Specifically for the scenario of the SiteActionDropdownItemsProvider and RecentGroups, I felt tests were not needed, since it would be hard to unintentionally regress either of these two cases.

The commit regarding the [deprecation and moving away from the existing PortalImpl.getGroupFriendlyURL() method](https://github.com/shuyangzhou/liferay-portal/commit/6dec44a54a1f211d050ce3917d636ed9a5e2eea3) can be dropped if needed, in order to make the changes a bit smaller.

The commits leading up to the inclusion of the integration tests resolve the issue described in LPS-138089.  The integration test and subsequent commit test and resolve a small edge-case when dealing with a publicLayoutSet with a virtual hostname defined which is the same as the current domain.  I also added a test for privateLayoutSets, which tests for regressions with the fix introduced with LPS-70980.

Please let me know if you have any questions, thanks!

CC @Ericyanlr

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi @shuyangzhou,
I would like to inquire if you had the opportunity to check this pull request?

**Comment by shuyangzhou** [comment]
ci:reevaluate:1257401_394

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou failure not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/108124

**Pull request closed without merging**
