### PR TITLE
[FinderCache]LPS-118633

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
On 66f3c3a5e7bad8fc9e21fe3172394dc3025a59fb, regenerated for account-service, ran AccountEntryOrganizationRelPersistenceTest. Nothing is failing.

Please resend by putting the *PersistenceTest regenerate right after the test ftl change, and explain what to do to see a failure.

**Comment by tinatian** [comment]
@shuyangzhou It will fail with lazy blob column only, cause it is flush the session right after save. If  you run service-builder-test-test, you will see it fail.

**Comment by shuyangzhou** [comment]
@tinatian ok, put this info in the commit message, otherwise overtime no one will remember what is this for. And regenerate the test right after the ftl change, so that the test failure can be reproduced.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9320

**Pull request closed without merging**
