### PR TITLE
LPS-81420 Portlet 3.0: Hub action and partial-action need WindowState and PortletMode correctly generated in JSON render state

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains 1 commit with a very, very minor 1-line change.

Regarding the CI failures:

- I saw the `NoClassDefFoundError` in two other pull requests today, so it must be unrelated.

- I also saw the functional-tomcat90-mysql57-jdk8/1 `NoSuchResourcePermissionException` in another pull request, so I can't see how it is related.

- The modules-integration-db2105-jdk8 test failure is a [Meris asset category demo portlet tester)(https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/237976/) that seems to be an unrelated failure as well.

- There is one failure listed earlier on (before the "failures unique to this pull" section) that reports a problem with a Portlet Hub client-side test:

```
hubA.removeEventListener(handle);
```

But 1) I saw this in another pull request today
-and-
2) Honestly we can't rely on any Portlet Hub client-side test results until 100% of the Portlet 3.0 implementation is merged.

If you agree, then please review when you get an opportunity, thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61428

**Pull request closed without merging**
