### PR TITLE
Pushdown osgi core

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Errors during database upgrade

6.2.10.21 database
https://testray.liferay.com/reports/production/logs/2021-07/test-1-21/test-portal-acceptance-pullrequest(master)/8276/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

7.0.10 database
https://testray.liferay.com/reports/production/logs/2021-07/test-1-21/test-portal-acceptance-pullrequest(master)/8276/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
@vicnate5 do I need an old db dump to reproduce it?

**Comment by shuyangzhou** [comment]
@vicnate5 I think I got it

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

Running a bigger set

**Comment by vicnate5** [comment]
@shuyangzhou Unique failures

1. [com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest
](https://testray.liferay.com/home/-/testray/case_results/1547185764)

2. [com.liferay.portal.bootstrap.FrameworkRestartTest](https://testray.liferay.com/home/-/testray/case_results/1547185301) - Almost for sure related to this PR since it last failed on https://github.com/shuyangzhou/liferay-portal/pull/10016

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Upgrade suite is good. So the only issues found are in https://github.com/shuyangzhou/liferay-portal/pull/10166#issuecomment-880321846

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will take care of them.

**Comment by shuyangzhou** [comment]
@vicnate5 I don't think the CharPipeTest failure is related.
Rerunning it.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@zhangyan0701 can you scan this? We previously only had issues here https://github.com/shuyangzhou/liferay-portal/pull/10166#issuecomment-880321846

**Comment by zhangyan0701** [comment]
No unique failures.

The previously failed tests passed this time.
[com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest](https://testray.liferay.com/home/-/testray/case_results/1547541795)
[com.liferay.portal.bootstrap.FrameworkRestartTest](https://testray.liferay.com/home/-/testray/case_results/1547541400)

**Comment by vicnate5** [comment]
@shuyangzhou This is looking good, we still probably want to hold merge since we are trying to build the release right now.

**Comment by shuyangzhou** [comment]
Yeah, I will hold it for now

**Pull request closed without merging**
