### PR TITLE
LPS-196186 Use seconds precision since during the packaging process the lastModified may lose the milliseconds precision. See discussion here https://liferay.slack.com/archives/C01FP01V5L0/p1694521696961269

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@rafaprax startup error here. See log https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14483/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz?authuser=0

**Comment by rafaprax** [comment]
@vicnate5 I'm on it.

**Comment by rafaprax** [comment]
ci:test:stable

**Comment by rafaprax** [comment]
The last commit is just to avoid the checksum calculation duplication.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you please scan these test results when they are ready? Thx

**Comment by vicnate5** [comment]
@shuyangzhou @rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, I removed the last commit.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@rafaprax @shuyangzhou No regressions found.

**Comment by vicnate5** [comment]
PASSED Manual Testing following the steps in https://liferay.atlassian.net/browse/LPS-196186

Tested with both vanilla environment and generating the initial state with `LIFERAY_CLEAN_OSGI_STATE=true`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140883

**Pull request closed without merging**
