### PR TITLE
Startup optimization 134 remove executor spring xml

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Upgrade regression here:

Steps to Reproduce
1. Import [this database dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/raw/master/7.4.13/data-archive/data-archive-portal-mysql.zip)
2. Execute upgrade with upgrade client (not reproducible with autoUpgrade)

```
ERROR [main][ElasticsearchSearchEngine:56] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.66 (210)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(377)] : The activate method has thrown an exception
com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionNotInitializedException: Elasticsearch connection not found. Production Mode Enabled: false, Connection ID: null, Prefer Local Cluster: true, Cross-Cluster Replication Enabled: false. Enable INFO logs on class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager for more information
	at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.getRestHighLevelClient(ElasticsearchConnectionManager.java:192) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl._getClusterHealthResponse(HealthClusterRequestExecutorImpl.java:91) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl.execute(HealthClusterRequestExecutorImpl.java:49) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.executeClusterRequest(ElasticsearchClusterRequestExecutor.java:53) ~[?:?]
	at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:40) ~[?:?]
	at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:22) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.execute(ElasticsearchClusterRequestExecutor.java:46) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:69) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine._waitForYellowStatus(ElasticsearchSearchEngine.java:396) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.initialize(ElasticsearchSearchEngine.java:134) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.activate(ElasticsearchSearchEngine.java:234) ~[?:?]
```
CI Log https://testray.liferay.com/reports/production/logs/2022-12/test-1-25/test-portal-acceptance-pullrequest(master)/5790/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/brianchandotcom/liferay-portal/pull/128075

**Pull request closed without merging**
