### PR TITLE
Lps 111972

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this. and if necessary, run more staging tests. this is heavily impacting export/import.

**Comment by kyle-miho** [comment]
com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest.testStagingGroup 
com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest.testStagingLayoutScope
com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest.testStagingTrashDisabled

@shuyangzhou these are the only tests i found that could be possible issues. Its hard to check on the new test site Spira for the history of these backend tests (functional tests are still doable) upstream like on Testray, im asking for help to find the history of backend tests to see if this is supported, otherwise i can try running a dummy ci run

Other than these tests, there should not be any potential unique failures

**Comment by shuyangzhou** [comment]
Thanks @kyle-miho ! The TrashEntryLocalServiceCheckEntriesTest ones have nothing to do with this change.

I will just forward it, please keep an eye on upstream for any zip related failures.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
