### PR TITLE
LPS-X Async ES connection connecting

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results once they are in, thanks!

**Comment by zhangyan0701** [comment]
There are some search integration tests failed with NPE error:

1. [com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineReconnectTest](https://testray.liferay.com/home/-/testray/case_results/2467274104)
```
## com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineReconnectTest > testInitializeAfterReconnect
##

	java.lang.NullPointerException
		at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl._getClusterHealthResponse(HealthClusterRequestExecutorImpl.java:86)
		at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl.execute(HealthClusterRequestExecutorImpl.java:40)
		at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.executeClusterRequest(ElasticsearchClusterRequestExecutor.java:44)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8434/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2. [com.liferay.portal.search.elasticsearch7.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutorTest](https://testray.liferay.com/home/-/testray/case_results/2467273682)
```
## com.liferay.portal.search.elasticsearch7.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutorTest > testFieldMappings
##

	java.lang.NullPointerException
		at com.liferay.portal.search.elasticsearch7.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutorTest.assertFieldType(ReindexSingleIndexerBackgroundTaskExecutorTest.java:58)
		at com.liferay.portal.search.test.util.background.task.BaseReindexSingleIndexerBackgroundTaskExecutorTestCase.testFieldMappings(BaseReindexSingleIndexerBackgroundTaskExecutorTestCase.java:94)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8434/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

3. [com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManagerTest](https://testray.liferay.com/home/-/testray/case_results/2467273725)
```
## com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManagerTest > testGetExplicitElasticsearchConnectionWhenConnectionDoesNotExist
##

	java.lang.NullPointerException
		at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.getElasticsearchConnection(ElasticsearchConnectionManager.java:153)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8434/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

4. [com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineBackupTest](https://testray.liferay.com/home/-/testray/case_results/2467274085)
```
## com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineBackupTest > testRestore
##

	java.lang.NullPointerException
		at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl._getClusterHealthResponse(HealthClusterRequestExecutorImpl.java:86)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8434/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou One integration test class is still failing
https://testray.liferay.com/home/-/testray/case_results/2467766288

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Many search tests failed to run on CI, so re-run tests.

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
@shuyangzhou  No regressions.

**Pull request closed without merging**
