### PR TITLE
LPS-94003 Upgrade to version 5.2.2.RELEASE of the Spring Framework

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou The results of `ci:test` have already been reviewed by @vicnate5 in the following pull request and he said it was OK to forward the branch on to you for review:
https://github.com/ngriffin7a/liferay-portal/pull/81

Thanks,

Neil

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn please run startup performance regression and regular runtime performance regression.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are startup performance test results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 91225d4 | 39623 | 20589.4 | 21069 | 20202 | 20298 | 20169 | 21209
PR | - | 41114 | 20645.8 | 20488 | 21310 | 20557 | 20361 | 20513

Runtime performance regression test results are on the way, will update when I got them.

Lily

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are runtime performance test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log out | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 47982 | 263 | 77.7 | -
PR | - | 47772 | 262 | 79 | -0.437664124

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 60359 | 715 | 227 | -
PR | - | 59918 | 555 | 172 | -0.7306284067


MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 17656 | 27.1 | 74.2 | -
PR | - | 17784 | 26.7 | 71.5 | 0.7249660172

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 15213 | 75.4 | 163 | -
PR | - | 14716 | 494 | 427 | -3.266942746
PR | - | 15054 | 137 | 215 | -1.045158746

DocumentLibrary:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 26684 | 209 | 301 | -
PR | - | 25841 | 241 | 323 | -3.159196522
PR | - | 26473 | 203 | 296 | -0.7907360216


Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 15681 | 275 | 491 | -
PR | - | 15711 | 223 | 436 | 0.1913143294


AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Changes (%)
-- | -- | -- | -- | -- | --
BaseLine | 33a090a | 27637 | 432 | 179 | -
PR | - | 27588 | 427 | 174 | -0.177298549


Regards
Lily

**Comment by shuyangzhou** [comment]
@ngriffin7a this looks fine, can you fix the rebase failure and send it back to me, thanks!

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8698

**Pull request closed without merging**
