### PR TITLE
Startup optimization 62 http servlet

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou I had issues locally starting this branch on JDK11.

https://gist.githubusercontent.com/vicnate5/53bf57dceb6883011e04c2274dae5cf1/raw/f45a2ceda051ee8390b218f3180966a1f7dde3bc/gistfile1.txt

I also get an error locally on JDK8 (not seen on CI)
```
2022-09-13 19:17:42.905 DEBUG [Start Level: Equinox Container: 8a855a34-9e60-4306-b76c-3348f200beac][BundleStartStopLogger:86] STARTED com.liferay.headless.admin.taxonomy.impl_5.0.41 [444]
2022-09-13 19:17:42.897 ERROR [Apache Felix Configurator Worker Thread][LogService:56] Error processing tasknull
java.lang.NullPointerException: null
	at org.apache.felix.scr.impl.ComponentRegistry.getComponentHolders(ComponentRegistry.java:360) ~[?:?]
	at org.apache.felix.scr.impl.runtime.ServiceComponentRuntimeImpl.getComponentDescriptionDTOs(ServiceComponentRuntimeImpl.java:76) ~[?:?]
	at com.liferay.portal.vulcan.internal.configuration.persistence.listener.VulcanConfigurationModelListener.onAfterSave(VulcanConfigurationModelListener.java:52) ~[?:?]
	at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager.lambda$store$7(ConfigurationPersistenceManager.java:316) ~[?:?]
	at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:42) ~[com.liferay.petra.function.jar:?]
	at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager._visitConfigurationModelListeners(ConfigurationPersistenceManager.java:657) ~[?:?]
	at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager.store(ConfigurationPersistenceManager.java:313) ~[?:?]
	at org.apache.felix.cm.impl.persistence.PersistenceManagerProxy.store(PersistenceManagerProxy.java:203) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationImpl.update(ConfigurationImpl.java:461) ~[?:?]
	at org.apache.felix.cm.impl.ConfigurationAdapter.updateIfDifferent(ConfigurationAdapter.java:204) ~[?:?]
	at org.apache.felix.configurator.impl.Configurator.activate(Configurator.java:601) ~[bundleFile:?]
	at org.apache.felix.configurator.impl.Configurator.process(Configurator.java:474) ~[bundleFile:?]
	at org.apache.felix.configurator.impl.Configurator.process(Configurator.java:396) ~[bundleFile:?]
	at org.apache.felix.configurator.impl.Configurator$1$1.run(Configurator.java:113) ~[bundleFile:?]
	at org.apache.felix.configurator.impl.WorkerQueue.run(WorkerQueue.java:74) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```
[Full log](https://gist.githubusercontent.com/vicnate5/8a82b7cd80e0aa2a21ef356e53e0704a/raw/3690eb2c4f441f251d62863fbfca4c201f4be5b4/gistfile1.txt)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in the new results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123138

**Pull request closed without merging**
