### PR TITLE
Spring shrinking

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check this one when the results come in? Looks like the testray import is backed up.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Triggered some jobs in publish-testray-report, but all failed, so re-run the test.

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar

Could you check the results when the tests finish?

**Comment by zhangyan0701** [comment]
ci:test:acceptance

**Comment by zhangyan0701** [comment]
No regressions found. All failures are unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116284

**Pull request closed without merging**
