### PR TITLE
LPS-179237 Skip cache on seeing new db, this happens during setup wiz…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ard db switching

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/132077

**Comment by shuyangzhou** [comment]
Thanks @Kvale1733 !

**Pull request closed without merging**
