### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@slnn one more try. Can you run the blogs and login with the following configurations:

1. Baseline
2. This pull with tomcat and jasper tagpools disabled
3. This pull with both tagpools enabled
4. This pull with tomcat enabled but jasper disabled

Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara & @shuyangzhou 

Here are test results on Login & Blog, I can see a noticeable drop on session count with this pull.

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper | 44c1be7 | 48115 | 263 | 79.4 |  
PR-8249 (disable tag pool both tomcat and liferay jasper) | - | 46439 | 282 | 85.4 | -3.48332121
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-8249 (enable tag pool both tomcat and liferay jasper) | - | 44159 | 279 | 83.4 | -2.707764167
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-8249 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44584 | 286 | 86.9 | -2.273075996

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper | 44c1be7 | 15314 | 55 | 136 |  
PR-8249 (disable tag pool both tomcat and liferay jasper) | - | 15129 | 123 | 205 | -1.208044926
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-8249 (enable tag pool both tomcat and liferay jasper) | - | 14846 | 375 | 368 | -2.514938604
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-8249 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 14624 | 564 | 456 | -4.299456842


Regards
Lily

**Pull request closed without merging**
