### PR TITLE
LPS-108239  | master

### PR DESCRIPTION
**Pull request by vicnate5**
Rebased on https://github.com/shuyangzhou/liferay-portal/pull/8959

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
Need to wait for https://github.com/brianchandotcom/liferay-portal/pull/86793 to get to upstream before testing

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Ugh more unstable tests

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@vicnate5 can you have someone ignore those CP * errors?

I"m manually merging  in just 3eeaff40605b821ab44bfe91d3d80f7e73fc8e80

**Pull request closed without merging**
