### PR TITLE
LPS-79799 ModelWrappers

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@slnn please test this for performance regressions.  I think login and blogs should be enough.

**Comment by slnn** [comment]
OK, got it. @Preston-Crary

**Comment by slnn** [comment]
Hi @Preston-Crary ,

Test results please see:https://docs.google.com/spreadsheets/d/1417wMp9OWLHBsSwIe6RT5N_yV1HO7d_4Dxy24tH1YiE/edit?usp=sharing

No regression appeared on this pull.

Regards
Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57505

**Pull request closed without merging**
