### PR TITLE
[Sidecar]LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Steps to test:

1. Run ant -f build-test-elasticsearch7.xml start-elasticsearch to build ES manually, will see a folder created in tomcat bundle home folder.
2. Rename the folder to elasticsearch7, and remove osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config.
3. Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.4.1)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1. Warning logging on startup
[2020-01-14T11:22:29,405][WARN ][o.e.d.b.Bootstrap ] [liferay]future versions of Elasticsearch will require Java 11; your Java version from [/opt/java/jdk-8u222/jre] does not meet this requirement
2. Dumping log4j.properties into temp folder
3. Clean up the configuration file, remove unused properties
4. Test on different OS.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @dantewang @slnn,
Please run a diff about ES with this pull, we would like to compare:
1. master head + current embedded ES6
2. master head + manually start ES7 in remote mode
3. master head + changes in this pull (This pull will use ES7 sidecar as embedded mode, and also root user issue has been fixed)

Please finish this up before spring festival.

Thanks.
Tina.

**Comment by tinatian** [comment]
Mark build trigger change as temp as search team would like to delay this change, resend at https://github.com/shuyangzhou/liferay-portal/pull/8741.

Tina

**Comment by vicnate5** [comment]
@tinatian Portal startup is successful on **Windows 10** when I add the Windows ES7 binary.

I am still going to do more testing on behavior.

Something else of note, the "Search" admin portlet info message reads:
```
Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.4.1)]
```

**Comment by vicnate5** [comment]
@joshchong

**Comment by tinatian** [comment]
@vicnate5 Can you try liunx build on windows one more time? The failure you had earlier is also same as yesterday which is related to config file.

Tina.

**Comment by vicnate5** [comment]
@tinatian Happy to report that the linux ES7 binary works on Windows

**Comment by joshchong** [comment]
@tinatian @vicnate5 I took a look at all of the failing search functional tests on both test runs in this PR and confirmed they just need test fixes to account for the changes in the pull. We can start work on those once development for this is more finalized.

I'm not sure if you're already looking into the other non-functional failures, but I took a quick look and noticed a few things:

1. `ModulesStructureTest.testScanGradleFiles` is failing with `Redundant dependency detected in modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/build.gradle`
2. The non-tomcat batches are failing to start up sidecar `java.lang.IllegalArgumentException: Sidecar home elasticsearch7 does not exist`
3. There's a `source-format-jdk8` failure on `ElasticsearchFixture.java`
4. There are also a lot more `modules-integration` failures compared to upstream

**Comment by vicnate5** [comment]
Test Plan execution results will be logged here:
https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit#gid=771578883&range=B5

**Pull request closed without merging**
