### PR TITLE
LPS-100264 CT search

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@Preston-Crary that CTSQLTransformerTest failure is real. Please fix and resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9230

**Pull request closed without merging**
