### PR TITLE
[Deprecation]LPS-104913

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @kyle-miho,
Please help us scan the test result.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
ci:test:4af31cffb4ba796bc7707431292bb348b28638d1

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
Results of ci:test:stable and relevant: failures are fluke or also failed on upstream or unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82616

**Pull request closed without merging**
