### PR TITLE
Startup optimization 285 kaleo portal instance lifecycle listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:workflow

**Comment by shuyangzhou** [comment]
@kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found just a semver issue

```
   [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 121.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/121.0.0/55c0cd4bf8ef67ed35d7e345322e111a0dd25daf/com.liferay.portal.kernel-121.0.0.jar
     [exec] Gradle build finished at 2023-08-25 16:12:44.739.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-39/test-portal-acceptance-pullrequest(master)/6951/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139759

**Pull request closed without merging**
