### PR TITLE
Tika raw metadata processor cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 this is a preparing cleanup for Tika extraction. It only touches TikaRawMetadataProcessor which is used for DL file meta info generation. Please help me to see whether there is some additional tests that can cover this.

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Ran all the tests I could find related to Documents and Tika, including one from security team that I ran locally.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/brianchandotcom/liferay-portal/pull/113048

**Pull request closed without merging**
