### PR TITLE
Pushdown jdbc

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results.
```
/opt/dev/projects/github/liferay-portal/build-test.xml:13128: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:2644: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:7259: /opt/dev/projects/github/liferay-portal/bundles/poshi is not a directory.
```
There happens a lot, it does not seem to be related to my changes.

**Comment by vicnate5** [comment]
@shuyangzhou Looks good

**Pull request closed without merging**
