### PR TITLE
LPS-134888 Check if nested properties are JSONObjects or JSONArrays

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi @shuyangzhou!

I have tried using `JSONUtil.getValue()` and seen that it might cause issues if we try to access nested JSONArrays (like in this change https://github.com/liferay-echo/liferay-portal/pull/5016/commits/d5d734ee81b924511e0dd61f5a5f58e43a4288db#diff-a6a71d62cd53d471cc198abd760c8aa49e948e80a4b3fd2cbf4ccfd0fe06bb8bR300-R302).

I have created a technical task to improve it's behavior by typechecking nested values before casting (similar thing that we do when "Object" is specified as type https://github.com/shuyangzhou/liferay-portal/pull/10127/commits/78b2adcd9959d6033b95f8d7c651457843396174#diff-e5d047350993ad2e10ec1bb84c7f5c07bd9c2632ba8b4decf13389205c8cb86cR138-R149): 

https://issues.liferay.com/browse/LPS-134888

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@p2kmgcl please add some unit tests to show the expected behavior.

**Comment by p2kmgcl** [comment]
Sure :smile:

**Comment by p2kmgcl** [comment]
Done :)

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
