### PR TITLE
[Bug Fix]LPS-119013

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is a bug found while working on finder cache, please see https://issues.liferay.com/browse/LPS-119013 for more details.

This fix will suffer same issue when backporting to other versions as the fix of adding hibernate call back listeners, so I keep this only for 7.3.

FYI @Preston-Crary I think this is probably the edge case you mentioned when I asked you why you retrieve first then evict.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
Why is this considered as a bug? It is exactly what is expected. That's how hibernate works, and the reason why we have the Session.get() before evict call in the generated persistence impl.
Are you trying to use Session.evict() in another context? Why it can not do the Session.get() in the same way?

**Comment by tinatian** [comment]
@shuyangzhou 
We do have another usage of session.evict() without the protection of get for table with lazy blob column, for example https://github.com/liferay/liferay-portal/blob/017df2f5eac8345f1ca13403db9ecd5209ec32d2/modules/util/portal-tools-service-builder-test-service/src/main/java/com/liferay/portal/tools/service/builder/test/service/persistence/impl/LazyBlobEntityPersistenceImpl.java#L1164.

This is an edge case, and we did not notice it for a long time. To fix it, I have two options:
1) Session.get first then evict to make sure evict the right one
2) My current solution.

To me 1) is kind of a waste, Session.evict() actually only cares session cache, if there is nothing in session cache, then you can do nothing, while Session.get() will load the entity if it is not in the cache, with 1), we may end up loading an entity and then removing it right after that.

Yes, I know this is kind of different than the hibernate API. But the reason we have this issue is our entity cache logic, another way I can do is not to modify current Session.evict(), provide another API method instead, I can also do this if you prefer.

Also this get first then evict logic causes another issue with my resetOriginalValues() in call back listener. With this fix, I can fix both issues together.


Tina.

**Comment by shuyangzhou** [comment]
You can call Session.contains() on the object to test whether it is associated with the session first, only evict it if it is associated. You can avoid the unconditional get this way.

**Comment by tinatian** [comment]
@shuyangzhou Session.contains() will only return true if the object is exactly same object in cache, same as Session.evict().

**Comment by shuyangzhou** [comment]
Ok, so what you really want is to check "associated id", right? Can you add a Session.contains(Serializable id) to do this?

**Comment by tinatian** [comment]
OK, I will do that.

**Pull request closed without merging**
