### PR TITLE
[Template Engine API]LPS-93847 and LPS-92343

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull does not depend on anything.

Please wait for ci result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@tinatian, there are a lot of issues with pr. Can you look at this please?

**Comment by tinatian** [comment]
Thanks @koor4356 ! I am fixing it, will resend.

Tina

**Comment by koor4356** [comment]
Thank you.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/7606

**Pull request closed without merging**
