### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull includes the support for clustering, sidecar is also disabled in this pull.

Known issue:
Random error when shutting down master node when cluster is enabled, example of errors:https://gist.github.com/tinatian/60184861dcdf7265f4b161d88e6dcffc and https://gist.github.com/tinatian/7a04bb4fd6435fe5825139842b5b65a7.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Enable sidecar and test here : https://github.com/vicnate5/liferay-portal/pull/1415

**Comment by tinatian** [comment]
@joshchong Please scan test results.

Thanks.
Tina

**Comment by joshchong** [comment]
@tinatian unfortunately there are now even more modules-unit failures in the `search-es7` run. [See test results here](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/361005/#showFailuresLink).

**Comment by shuyangzhou** [comment]
See https://github.com/tinatian/liferay-portal/pull/1722

**Pull request closed without merging**
