### PR TITLE
Startup optimization 183 panel app registry

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this affects PanelApp and Depot, please help me add more necessary tests, thanks!

**Comment by vicnate5** [comment]
ci:test:depot

**Comment by vicnate5** [comment]
ci:test:depot

**Comment by vicnate5** [comment]
@shuyangzhou The relevant results are good, but the Depot suite didn't run any functional tests, even though it picks them when I run the CI job simulator, trying again and will watch it.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131663

**Pull request closed without merging**
