### PR TITLE
LPS-73544 add a compatibility layer for old clients that don't know about new protocol= parameter

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retet

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
👍  Hey @shuyangzhou  I hope this compatibility path is acceptable.  We decided it would be much easier for us.  Hopefully this will make it into GA5 and SP5

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/51141

**Pull request closed without merging**
