### PR TITLE
Lps 169817

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:oauth2

**Comment by shuyangzhou** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. Tested the related issues and all passed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139708

**Pull request closed without merging**
