### PR TITLE
LPS-71993 Improve performance of SearchPermissionChecker for guests

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
This should be ready, from the profile this is 15% of the asset publisher test case.

**Comment by tomwang2011** [comment]
From grinder test, we are noticing a 2%-2.5% session increase with this change.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48502

**Pull request closed without merging**
