### PR TITLE
[Deprecation]LPS-106167

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by zhangyan0701** [comment]
Just started reviewing.

**Comment by zhangyan0701** [comment]
There are two unique failures that might related:
1. modules-semantic-versioning-jdk8 failed with error:
`     [exec] > Task :apps:adaptive-media:adaptive-media-image-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.adaptive.media.image.validator         MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   interface  com.liferay.adaptive.media.image.validator.AMImageValidator
     [exec] 		+   method     isProcessingSupported(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     abstract
     [exec] 			+   return     boolean
     [exec] [Baseline Report] Mode: diff (persisted)`

Full console log:
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/314013//consoleText

2. portal-license-jdk8 failed with compile error:
`build-common-java.compile:
    [javac] Compiling 2607 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/LCSLicenseManager.java:36: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.util.StringPool;
    [javac]                                      ^
    [javac]   symbol:   class StringPool
    [javac]   location: package com.liferay.portal.kernel.util`

Full console log:
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/295369/consoleFull

Other failures are flaky or unrelated.

**Comment by dantewang** [comment]
Thanks @zhangyan0701 
The first one is not related and should have been fixed on current upstream. The major version bump is caused by LPS-106247.

The second one is related, as we removed kernel `StringPool`. I'll try to send a fix for liferay-release-tool-ee later.

**Comment by vicnate5** [comment]
@shuyangzhou Ready to go, see discussion above.

**Comment by shuyangzhou** [comment]
@vicnate5 I am waiting for the liferay-release-tool-ee fix first, to avoid CI breakage.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-release-tool-ee/pull/3. @vicnate5 is verifying.

**Comment by vicnate5** [comment]
Testing at https://github.com/vicnate5/liferay-portal/pull/1370

**Comment by vicnate5** [comment]
@shuyangzhou Testing passed on this PR + fix from https://github.com/shuyangzhou/liferay-release-tool-ee/pull/5

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82825

**Pull request closed without merging**
