### PR TITLE
Startup optimization 141 cached introspection results patch

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failure in LibraryReferenceTest
```
##
## com.liferay.portal.library.LibraryReferenceTest > testLibDependencyJarsInVersionsExt
##

	junit.framework.AssertionFailedError: Wrong version for lib/portal/spring-beans.jar in lib/versions-ext.xml expected:<5.2.22[.LIFERAY-PATCHED-1]> but was:<5.2.22[]>
		at com.liferay.portal.library.LibraryReferenceTest.testLibDependencyJarsInVersionsExt(LibraryReferenceTest.java:162)
```
Full log https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6810/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128449

**Pull request closed without merging**
