### PR TITLE
LPS-147867 Making the upgrade process cluster aware

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-145867

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
Hi @shuyangzhou, did you have time to take a look at this PR? Let me know if you need anything from me. Thanks!

**Comment by shuyangzhou** [comment]
We had a meeting with Brian last Friday, he does not want to continue this cluster wide upgrade support. I am waiting for the next meeting we have together to have this sorted out on the business requirement level first before reviewing it.

**Comment by LuisOrtiz89** [comment]
Thanks for the update @shuyangzhou, we will talk tomorrow then. @achaparro is already back, so he will be able to provide more information on this.

**Comment by shuyangzhou** [comment]
@LuisOrtiz89 @achaparro I am closing this pull for now. I think you should keep your branch just in case we change plans in the future.

**Pull request closed without merging**
