### PR TITLE
Lps 174821

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are the runtime performance test results on AssetPublisher, no noticeable regression appeared.

main3

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count change (%) | Portal Server CPU (%) | ES Server CPU (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 631b009 | 20624 | 353 | 165 | - | 95,95,95 | 13,13,13
PR | - | 20800 | 345 | 168 | 0.8533747091 | 94,95,95 | 14,13,13


main2

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count change (%) | Portal Server CPU (%) | ES Server CPU (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 631b009 | 30412 | 412 | 173 | - | 88,87,87 | 10,10,10
PR | - | 29282 | 407 | 175 | -3.715638564 | 84,83,83 | 10,10,10



Regards
Lily

**Comment by 111Anna** [comment]
Hi @shuyangzhou, I rerun the startup on CE and DXP, here are test results.

CE

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 631b009| 22740.3 |- |3274.3|-| 1833 | 101 | 504| 1008 |
Baseline + PR-10940| - |  22966.3 |-1.0%| 3300.3|-0.8%| 1834 | 87 | 498 | 1008 |



DXP

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 631b009| 25050 |- |3865|-| 1989 | 115| 556| 1097 |
Baseline + PR-10940| - |  24985 | 0.3%| 3767|2.6%| 1990 | 101 | 564 | 1097 |

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129846

**Pull request closed without merging**
