### PR TITLE
[TECHNICAL-SUPPORT] LPS-88170

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@fortunatomaldonado @jonathanmccann have you regenerated? There are tons of changes.
This is too aggressive, it is not only changing variables, but also changing method names. We should not make those changes.
Not merging. Please fix it in a different way.

**Comment by fortunatomaldonado** [comment]
Hello @shuyangzhou,

Thank you for reviewing. Can you give me some insight on how to go about fixing this issue? 

Some of my previous ideas involved creating a blacklist that will prevent users from selecting the variables that will cause this syntax error. The downside to this is that it will require customers to upgrade their database if they are using these variables. I also thought about changing the template variables but then that would require to rebuild all the services.

Any suggestion would be much appreciated.
Thank you.

**Comment by shuyangzhou** [comment]
The issue on the ticket can be fixed by just renaming the for loop var name without changing any user supplied column names. But I guess you want to cover more "bad" names than just that "value".

The column name escaping is not the issue here. The issue is you need to check on the regenerated changes from your ftl changes, then you will see how big the change is, and it is changing many things in an unwanted way. The bottomline is you need to restrict the changes to only the necessary parts.

**Comment by fortunatomaldonado** [comment]
So changing the ftl template, as long as it is not causing unnecessary changes, seems to be the way we want to fix this. Let me know if this is correct.

**Comment by shuyangzhou** [comment]
Let's try that first, as there are too many changes in this pull, too much noise to see whether it is good.

**Comment by fortunatomaldonado** [comment]
I added the change here: https://github.com/fortunatomaldonado/liferay-portal/tree/LPS-88170
Would sending a new pull be better for testing?

I deployed the changes and tested by adjusting the service.xml for counter and building the services. Let me know if this is correct way to be testing and looking at the changes.

**Comment by shuyangzhou** [comment]
You need to send your pull with the full regen, otherwise it will never pass CI. Make sure to run ci test in your new pull.

**Comment by shuyangzhou** [comment]
ant build-services, yes commits the changes, make sure you run ci test.

**Comment by fortunatomaldonado** [comment]
Okay, I'll run it in portal-impl, commit, send the pull and run ci test.
Thank you for your help and will send out the new pull shortly.

**Pull request closed without merging**
