### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: This failure seems unrelated. Please review when you can and let us know so that @shuyangzhou can review. Thanks!

**Comment by jpince** [comment]
@ngriffin7a I pinged Shuyang earlier to ask him to review this. It's gone through enough testing in other pulls, and CI had a major outage this morning https://loop.liferay.com/home/-/loop/feed/11568730.

**Comment by ngriffin7a** [comment]
@jpince Thanks!

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
CI is up running now, I need to see a full build on this.

**Comment by jpince** [comment]
SB failure unrelated, Peter Shin is working on it.

**Comment by ngriffin7a** [comment]
@shuyangzhou master is a moving target right now. Could you please simply fix https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-uad/build.gradle#L3 in a code review commit?

**Comment by shuyangzhou** [comment]
Rerunning at https://github.com/shuyangzhou/liferay-portal/pull/6132

**Pull request closed without merging**
