### PR TITLE
LPS-84682 Fix test by avoiding introducing unnecessary brackets when there's no permissionSQLContributor query

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@sergiogonzalez rebase failure, please resend.

**Pull request closed without merging**
