### PR TITLE
LPS-76383 Separate portal-search-web-api module

### PR DESCRIPTION
**Pull request by arboliveira**
This is the second `portal-search-*-api` module extracted from a currently existing `portal-search-*` module. It's also the last.

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@arboliveira we still have one left, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-search/portal-search-elasticsearch/bnd.bnd#L4

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53796

**Comment by arboliveira** [comment]
@shuyangzhou We will remove `portal-search-elasticsearch` from master for 7.1, sometime after we publish the new `portal-search-elasticsearch6` (with its own `portal-search-elasticsearch6-api`.) Is it okay to leave `portal-search-elasticsearch` in 7.0.x as is, without a separate API?

**Comment by shuyangzhou** [comment]
Sure, as long as it is eventually going to be taken care of. We don't need this to happen right away.
But it is better to have it before Jan.

**Comment by arboliveira** [comment]
Just to make sure I understand correctly: we should then go ahead and separate `portal-search-elasticsearch-api` in `7.0.x` even though this module won't exist in `master`, is that right? (`portal-search-elasticsearch` is Elasticsearch 2 and will be present at `7.0.x` only, `portal-search-elasticsearch6` is Elasticsearch 6 and will be present at both `7.0.x` and `master`.)

**Comment by shuyangzhou** [comment]
I think that's right. I can not remember clearly what we talked about last time.
To me I care the 7.1 most, as that 's where this lpkg refactor goes into. For 7.0.x, you can do anything you feel reasonable. That won't be a problem for lpkg refactor.

**Comment by arboliveira** [comment]
Thanks @shuyangzhou!  😃

**Pull request closed without merging**
