### PR TITLE
LPS-155437 Avoid unnecessary NoSuchTableException

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by catarineaguiar** [comment]
@shuyangzhou semver error:

```
[exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/41.0.3/9eb5037e14e8d61f8478c71ab50832f06a9858c8/com.liferay.portal.impl-41.0.3.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-37/test-portal-acceptance-pullrequest(master)/2617/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:forward

@catarineaguiar it can not be from this pull, it did not change portal-impl code. Must be from some other upstream changes.

**Pull request closed without merging**
