### PR TITLE
[Bug Fix]LPS-136753

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
FYI @marianoalvarosaiz

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Rebased/regenerated at https://github.com/shuyangzhou/liferay-portal/pull/10287

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
