### PR TITLE
Lps 78973 service builder addback

### PR DESCRIPTION
**Pull request by tomwang2011**
cc @Preston-Crary

Hi Shuyang, this is the resend of https://github.com/shuyangzhou/liferay-portal/pull/5869 after squashing all regens into 1 commit, no logic change from previous pull. The service-builder failure will still occur as I didn't commit the line that is going to be modified by the source-formatter. It will be the same failure happening on upstream, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56481

**Pull request closed without merging**
