### PR TITLE
[TS] LPS-74615 - License manager is not available after the upgrade

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
@shuyangzhou 

this is caused by "LPS-61718 Apply upgrade pattern"
in ee-6.2.x, "173": the display name is "Summary" for asset publisher. "176": the display name is "License Manager". so in this situation, the right portletId is "176"

**Comment by daviddotzhang** [comment]
CC @samuelkong

**Comment by achaparro** [comment]
Hi @daviddotzhang,

This modification solves the issue for new customers upgrading to DXP but not for those ones which are already in DXP and they can't use the license manager. I have sent the this pull to Brian:
https://github.com/brianchandotcom/liferay-portal/pull/55569

But please, send me another one with the required changes.

Thanks.

cc/@shuyangzhou

**Comment by achaparro** [comment]
@shuyangzhou you can close this pull

**Pull request closed without merging**
