### PR TITLE
LPS-X Switch to use SimpleURLPatternMapper. DynamicSizeTrieURLPattern…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…Mapper/StaticSizeTrieURLPatternMapper are way over designed. Out of box we only have 483 URL patterns, they wasted about 70MB heap for empty long arrays.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
Test [com.liferay.petra.url.pattern.mapper.URLPatternMapperFactoryTest](https://testray.liferay.com/home/-/testray/case_results/2461962685) failed with error:
```
##
## com.liferay.petra.url.pattern.mapper.URLPatternMapperFactoryTest > testCreate
##

	java.lang.AssertionError
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/12005/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144094

**Pull request closed without merging**
