### PR TITLE
LPS-57377

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
So this one passed because of downgrade to 0.9.5 ?

**Comment by shuyangzhou** [comment]
I am going to retest it again, to be safe.

ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/28804

**Comment by hhuijser** [comment]
@shuyangzhou 

Yes, it passed because of the downgrade.
0.9.5.1 uses java.sql.SQLType which is only supported by jdk 1.8
0.9.5 is not using that.

**Pull request closed without merging**
