### PR TITLE
Fix LP-77775

### PR DESCRIPTION
**Pull request by stiemannkj1**
Following instructions here to revert the revert commit and add the fix under LPS-77775: https://issues.liferay.com/browse/LPS-77775?focusedCommentId=1245270&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1245270. I also added a unit regression test.

Also, I had to make an API change for the sake of my `7.0.x` PR: https://github.com/liferay/liferay-portal-ee/pull/5202

### CODE REVIEW

**Comment by stiemannkj1** [comment]
ci:test

**Comment by stiemannkj1** [comment]
Seems like the PR tester failures have nothing to do with my changes. @jpince, please verify that the failure is unrelated to the PR so that it can go into review.

**Comment by timpak** [comment]
ci:retest

**Comment by timpak** [comment]
@stiemannkj1 I think the modules-integration failures are flukes but I'm not certain. I know for sure the other failures aren't related to your changes. 

For now, I'll retest your pull. If the modules-integration failures aren't see again, you're good to go. If they are, please take another look and double check to make sure the failures aren't related.

**Comment by stiemannkj1** [comment]
@timpak, thanks. Looks like the modules-integration tests didn't fail the second time. Is there anything further I need to do to get the PR into review?

**Comment by timpak** [comment]
@stiemannkj1 no, you're good. None of the failures are related to your changes.

**Comment by timpak** [comment]
@shuyangzhou please review this pull

**Comment by shuyangzhou** [comment]
@stiemannkj1 this looks weird, the second commit is undoing the first commit. If this is really intended, you should just leave the 1st one out, only do the change you are trying to do.
Please clean up and resend.

**Comment by stiemannkj1** [comment]
@shuyangzhou, I was asked to do that by @lipusz since the commit message for the original commit was wrong (as I mentioned in the first comment on this PR):

> Following instructions here to revert the revert commit and add the fix under LPS-77775: https://issues.liferay.com/browse/LPS-77775?focusedCommentId=1245270&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1245270. I also added a unit regression test.

> Also, I had to make an API change for the sake of my 7.0.x PR: liferay/liferay-portal-ee#5202

Note that the first commit (reverting the revert) was already done on `7.0.x`.

**Comment by shuyangzhou** [comment]
@stiemannkj1 I don't really get what is the goal here. Your second commit, is almost undoing the 1st one, however there are a few SF level differences, which made this very confusing. If you really just want to revert it, it should be a clean revert commit by itself with no additional changes. And you can add up more follow up commits to do the SF changes. At least this way I can see you are on purposely reverting it.
And for the your follow up changes, break it into commits, modifying the taglib, applying it and test it. They need to be separated, not mixing into one commit.

**Comment by stiemannkj1** [comment]
@shuyangzhou, sent an updated PR: https://github.com/shuyangzhou/liferay-portal/pull/5789

**Pull request closed without merging**
