### PR TITLE
LPS-128599

### PR DESCRIPTION
**Pull request by yuhai**
Hi @shuyangzhou, I only add one change in CheckAssetEntryMessageListenerTest.java (merge it to the [commit](https://github.com/liferay/liferay-portal/commit/d84feca3813228a6071058bb04e332e4a4ae75b0)). The class should add the usage after we sent the pr.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99840

**Pull request closed without merging**
