### PR TITLE
Startup optimization 396 service registry filtered service listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:2564450139

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
ci:report:2564474474

**Comment by JerryAdrianoo** [comment]
@shuyangzhou, I tested using this PR and the Master version as comparison parameters. The results are in this [spreadsheet](https://docs.google.com/spreadsheets/d/1HST_RyRX1YUAddPYbKmZpjmTnOzkvi_35zL3X0Qd_VE/edit#gid=0).
The improvement in Startup/Shutdown Cold and Hot was significant.
Please let me know if you want anything else.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149806

**Pull request closed without merging**
