### PR TITLE
LPS-X Optimize ContextController's TrackerCustomizers

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures found. Most of the integration failures were due to ES sidecar crashing during one of the test runs, not likely related to this change.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/shuyangzhou/liferay-portal/pull/9610

**Pull request closed without merging**
