### PR TITLE
Commerce-2475 - Move Data Integration Admin to liferay-portal repository master branch

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hello @shuyangzhou I have continued to work on the port of data integration admin from 7.1.x to master (@igorbeslic did initial commits). Here are fully ported api/service/web modules, if everything is OK I will continue to port data-integration-talend modules in the same way. Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
Closing until I resolve SF errors

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek please fix the SF issues and resend.

**Pull request closed without merging**
