### PR TITLE
LPS-62628 Log errors instead of throwing the exception when URL encoding contains parameters with %

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
For the View623Upgrade#View623DataArchive error:
```
[exec] 09:03:25,986 ERROR [http-nio-8080-exec-8][GoogleJavaScriptMinifier:108] (/o/frontend-js-metal-web-1.0.0/metal-promise/src/promise/Promise.js:281): @define variable  assignment must be global
     [exec] 09:03:25,988 ERROR [http-nio-8080-exec-8][GoogleJavaScriptMinifier:123] {0} error(s), {1} warning(s)
```
And for the PGTags#DisplayTagCloud one:
```
[exec] 09:05:59,177 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:108] (/o/frontend-js-metal-web-1.0.0/metal-promise/src/promise/Promise.js:281): @define variable  assignment must be global
     [exec] 09:05:59,180 ERROR [http-nio-8080-exec-3][GoogleJavaScriptMinifier:123] {0} error(s), {1} warning(s)
```

So they don't seem related :disappointed:

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mdelapenya I don't agree with this solution. In general we should always throw for broken URL encoding/decoding, in the certain cases that we don't care the exception, and only want to log and swallow it, it should be done at the invoker level, not in side URLCodec. By doing it inside, there is no easy way the invoker can know something is broken for the input, in case some invoker does want to know that. Basically throwing exception for broken URL leaves us more options, you can always catch and log at the HttpImpl level or higher which ever makes better sense.

**Comment by mdelapenya** [comment]
I tried to code what @samuelkong proposed in the ticket

**Pull request closed without merging**
