### PR TITLE
LPS-96154 | Remove deprecated CMIS Store

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @shuyangzhou, 

This pull request is analogous to the one removing the deprecated JCR Store since both stores have been deprecated for a while. The intention is for Liferay 7.2 not to include CMIS Store anymore. 

Please see [LPS-95312](https://issues.liferay.com/browse/LPS-95321) for the case of JCR Store, along with [PTR-875](https://issues.liferay.com/browse/PTR-875) for context. 

Please let me know if you have any questions. Thanks! 

cc @mhan810

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
What about "modules/apps/document-library/document-library-repository-cmis-api" and "modules/apps/document-library/document-library-repository-cmis-impl" should we remove them too?

**Comment by robertoDiaz** [comment]
Hi @shuyangzhou 

This bundles are not related with stores.

This are the implementation and the API of an external repository of DM (similar to sharepoint or documentum) and should not be deleted.

Thanks!!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73869

**Pull request closed without merging**
