### PR TITLE
LPS-114384 PortalInstance API

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@shuyangzhou this pull with the same code changes passed the CI tests previously in case you want to take a look first:
https://github.com/nhpatt/liferay-portal/pull/308

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9158

**Pull request closed without merging**
