### PR TITLE
[TS] LPS-111076

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-111076

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @shuyangzhou, are there any updates for this issue?  Thanks!

**Comment by ChrisKian** [comment]
Sent to https://github.com/tinatian/liferay-portal/pull/1751

**Pull request closed without merging**
