### PR TITLE
[TECHNICAL SUPPORT] LPS-91329

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-91329

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
That ci:test errors are produced in other pull requests, for example see: https://github.com/brianchandotcom/liferay-portal/pull/68782#issuecomment-468398674

So they seem to be unrelated to my changes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68841

**Pull request closed without merging**
