### PR TITLE
LPS-104539 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-104539

### CODE REVIEW

**Comment by kyle-miho** [comment]
@shuyangzhou Tested the fix for oracle through an integration test before & after changes.

Tested here https://github.com/kyle-miho/liferay-portal/pull/291
There was a service builder failure caused by https://github.com/brianchandotcom/liferay-portal/pull/81222
And one from analytics, but i regened

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81281

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/81284

**Pull request closed without merging**
