### PR TITLE
[Bug Fix]LPS-129172 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test result?

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian These JSON unit test failures look to be related, occurred in both test runs here, but is passing upstream.
`com.liferay.batch.engine.internal.writer.JSONBatchEngineExportTaskItemWriterTest`
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464556/

**Comment by yuhai** [comment]
@vicnate5, thanks for your check. The issue is related with the PR.
@tinatian, @dantewang, @shuyangzhou, I will solve the issue and resend. Thanks.

**Comment by shuyangzhou** [comment]
I am closing this pull, waiting on the new one.

**Pull request closed without merging**
