### PR TITLE
[SampleSQLBuilder]LPS-136758 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@tinatian Upgrade failure is not related. [SampleSQLBuilderTest](https://testray.liferay.com/home/-/testray/case_results/1552757312) also fails, but matches the failure seen in upstream.

**Comment by vicnate5** [comment]
@tinatian Issue at head with SampleSQLBuilderTest https://issues.liferay.com/browse/LPS-137312

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105525

**Pull request closed without merging**
