### PR TITLE
[TECHNICAL-SUPPORT] LPS-71458 Preliminary clean up of ResourceActionsImpl

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Real test failure I caused, I asked @mbowerman to make some changes to the pull after taking another look at our changes with him.

**Pull request closed without merging**
