### PR TITLE
[Bug Fix]LPS-134082

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

The original fix for this issue is wrong, thus we reverted it in the first commit.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:calendar

**Comment by vicnate5** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10255

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
