### PR TITLE
LPS-91394 Exception on CDI bundle redeploy

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn @dantewang please run a regression tests, run this after the mysql driver upgrade (Once you fix the benchmark blocker issue). These 2 are high priority ones, others can wait.

**Comment by slnn** [comment]
Hi @shuyangzhou 
Test results please see: [Test results for LPS-91394](https://docs.google.com/spreadsheets/d/18tv_b3pjGm5QNtD2SQbtjGQGv4jGuxxLU4YfmNcgMgU/edit?usp=sharing)

Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68932

**Pull request closed without merging**
