### PR TITLE
LPS-86622 Shouldn't we be delegating this to the portlet request?

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

Can you give me a hand with this?

As I describe in 77c9ecb25c79a48d71eda64eb98f1243b53acc3f, the file uploader [is sending](https://github.com/liferay/liferay-portal/blob/655835d729c4cc42f36a3542c63ec0c7d7244085/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/edit_page_attachment.jsp#L87-L93) the nodeId parameter as a `public render parameter`:

    p_r_p_http://www.liferay.com/public-render-parameters/wiki_nodeId

And the `uploadPortletRequest` returns null when queried for "nodeId". The same returns the right value when called on the `portletRequest`.

I am not familiar with `public render parameters` and I am not sure if the issue here is that the file uploader shouldn't be sending public render parameters in the first place or if `UploadPortletRequest` is not parsing them properly (which is what I tried to solve in the last 2 commits).

Thanks in advance.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

It's been a busy day today. I will take a look at those failures and hopefully fix them tomorrow.

Thanks!

**Comment by 4lejandrito** [comment]
I have created https://issues.liferay.com/browse/LPS-86811 to track this. I've [sent the first commit](https://github.com/brianchandotcom/liferay-portal/pull/64652/commits/a81fa637a2766f81d6335fa06e7ec45157a1718b) as a temporary fix for now to unblock [the original issue](https://issues.liferay.com/browse/LPS-86622).

**Pull request closed without merging**
