### PR TITLE
LPS-113455 Social mvcc

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
Hi @vicnate5 @xbrianlee,

can one of you help with the functional test failures? Not sure if this is caused by the change or how to test these locally.

**Comment by xbrianlee** [comment]
@Preston-Crary Upgrade tests are throwing this unknown column exception during startup. The error looks version agnostic so upgrades across multiple versions are failing.
```
ERROR [main][JDBCExceptionReporter:234] Unknown column 'dlfileentr0_.ctCollectionId' in 'field list'
```

Full console: https://testray.liferay.com/reports/production/logs/test-1-4/1589307661802/test-portal-acceptance-pullrequest%28master%29/5818/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
@xbrianlee thanks!

**Comment by Preston-Crary** [comment]
@shuyangzhou when I rebased I left the version as the old value, this meant I squashed the previous upgrade.  Do you think we should add something to prevent a similar mistake?  Could cause a totally silent failure if the schema doesn't change.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@xbrianlee, can you check this failure too?

**Comment by xbrianlee** [comment]
@Preston-Crary Sorry for the late reply. Upgrades from 6.2 are failing with the following error. Looks unique to the changes from this PR.
```
     [java] 00:35:05,878 INFO  [main][UpgradeProcess:115] Failed upgrade process com.liferay.portal.upgrade.v7_0_0.UpgradeSocial in 1 ms
     [java] 00:35:05,878 INFO  [main][UpgradeProcess:115] Failed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_0 in 60823 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLException: Column count doesn't match value count at row 1
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:173)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:140)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:122)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:175)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:204)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:130)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLException: Column count doesn't match value count at row 1
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:131)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:114)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 11 more
     [java] Caused by: java.sql.SQLException: Column count doesn't match value count at row 1
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
     [java] 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:92)
     [java] 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeSocial.addSocialActivitySets(UpgradeSocial.java:42)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeSocial.doUpgrade(UpgradeSocial.java:70)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 14 more
```

**Comment by Preston-Crary** [comment]
@xbrianlee thanks!  I'll take a look and resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9078

**Pull request closed without merging**
