### PR TITLE
LPS-78477 BigDecimal

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Needed the changes from LPS-77425.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Preston-Crary I reviewed it, everything looks fine. Please rebase and resend, then I can forward it to Brian right away.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5865

**Pull request closed without merging**
