### PR TITLE
LPS-X Fix broken version string parsing. Caused by ae37276e . toSchem…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…aVersion.substring(0, 5) is assuming major, minor and micro versions are always 1 digit "d.d.d", which is not true. This is why AssetVocabularyUpgradeProcess runs on empty database startup, since its version 1.0.17 got chopped into 1.0.1 which is lower than its previous step 1.0.2 which is fooling upgrade framework to continue execution.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139502

**Pull request closed without merging**
