### PR TITLE
Startup optimization 154 object resourcebundle

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 is there any object localization related tests that I could run for this pull?

**Comment by vicnate5** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129210

**Pull request closed without merging**
