### PR TITLE
LPS-X Shrink quartz thread pool size to 1. Quartz only runs MessageSe…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…nderJob which is just sending a message to an async messagebus destination. The main work load is handled by the message bus thread, not quartz thread. Having one thread per storge type is enough.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125413

**Pull request closed without merging**
