### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Fixed a couple non-functional issues:
Wrong ticket number one of the commits.
Squashed a change I meant to squash.

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Test results are good!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83819

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/83868

**Pull request closed without merging**
