### PR TITLE
[Finder Cache]LPS-122225-LPS-122032

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on https://github.com/brianchandotcom/liferay-portal/pull/95248 which has been merged into Brian's origin, but have not merged into master.

FYI @Preston-Crary

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please verify if the unique failures are real?

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
@tinatian When will we ever evict from BasePersistenceImpl._dslQueryFinderPathMap? In the past the FinderPath are generated by SB with a predictable footprint, but now it is dynamically generated based on incoming sqls, we could grow very large on this map. At minimum we should change this to a PortalCache to prevent unlimited growing and orphan entries.

Please make this change and resend.

**Comment by tinatian** [comment]
@shuyangzhou Yes, you are right, I should have used portal cache rather than a map. I will resend.

**Pull request closed without merging**
