### PR TITLE
[TECHNICAL-SUPPORT] LPS-76994 Remove ResourcePermission count from LayoutPermissionImpl.java

### PR DESCRIPTION
**Pull request by Preston-Crary**
@slnn can you test this to see if there's a performance improvement for login and message boards test cases?

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @Preston-Crary 
Here are test results on Login and Message Boards: https://docs.google.com/spreadsheets/d/1lqzuGpvfdM33S5mP0Yy8X_GmE2roX4umi3W2byk4Izg/edit?usp=sharing

From test results, I do not see any obviously improvement.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54333

**Pull request closed without merging**
