### PR TITLE
[TS] LPS-127658 

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @shuyangzhou ,

It seems like the case of [LPS-127658](https://issues.liferay.com/browse/LPS-127658) was working this way since the beginning of page versioning. However, this behavior is incorrect: the portlet preferences gets deleted before `LayoutLocalServiceStagingAdvice` can detect the deletion and create a new `LayoutRevision`, which does not contain the deleted portlets.

I've added one commit to @bakayattila 's PR to fix the NestedPortlet case, but I'm not sure whether storing the deleted protletIds in ServiceContext is the right solution from core infra perspective.

Please review the changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the test results.
@vendeltoreki @bakayattila please add an integration test to assert the behavior. I will be using your new test to drive the review. Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures on the relevant results.

**Comment by vendeltoreki** [comment]
Hi @shuyangzhou ,

I've added @bakayattila 's integration test to the pull request (commit https://github.com/shuyangzhou/liferay-portal/pull/9836/commits/d465adcf0279f172f8375c43e8ab21f577e587b9).

Thanks,
Vendel

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me verify this pull, I ran the new test class locally with a clean ant all. It breaks for me, although CI was fine.
```
com.liferay.staging.service.test.StagingLocalServiceTest > testEnableLocalStagingWithStagedParentGroup STARTED

com.liferay.staging.service.test.StagingLocalServiceTest > testEnableLocalStagingWithStagedParentGroup PASSED

com.liferay.staging.service.test.StagingLocalServiceTest > testPageVersioningPortletRemoval STARTED

com.liferay.staging.service.test.StagingLocalServiceTest > testPageVersioningPortletRemoval FAILED
    java.lang.AssertionError
    	at org.junit.Assert.fail(Assert.java:87)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at org.junit.Assert.assertTrue(Assert.java:53)
    	at com.liferay.staging.service.test.StagingLocalServiceTest.testPageVersioningPortletRemoval(StagingLocalServiceTest.java:317)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:748)

8 tests completed, 1 failed
```
Can you run it on your side to double check? Thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 never mind, it is caused by the tomcat upgrade from yesterday. My terminal was still pointing to the older one. It works now. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/bakayattila/liferay-portal/pull/51, please send it back after adding in the missing test coverage.

**Pull request closed without merging**
