### PR TITLE
Lps 185647 redo 5

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
CC @susanchen3 @kyle-miho @vicnate5

**Comment by achaparro** [comment]
hey guys please see:
https://github.com/shuyangzhou/liferay-portal/pull/11129

**Comment by achaparro** [comment]
I proceed to close this one but @shuyangzhou, feel free to reopen it if you consider it neccessary

**Comment by achaparro** [comment]
ci:close

**Pull request closed without merging**
