### PR TITLE
COMMERCE-2475 Dispatch framework - rename

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @shuyangzhou here is a rename suggestion for class ScheduledTaskExecutor -> ScheduledJob. Please review, thank you! /cc @igorbeslic

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Please see my email and proceed with the current naming style.

**Pull request closed without merging**
