### PR TITLE
LPS-159239: The HEADER_PHASE of the Portlet 3.0 lifecycle is not invoked when a portlet is rendered on a Content Page

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
cc @weskempa-liferay

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by ngriffin7a** [comment]
Thank you @shuyangzhou and @vicnate5 ! :-)

**Pull request closed without merging**
