### PR TITLE
[Finder Cache]LPS-122190

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please verify the unique failures?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures not related.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou Failures are not related. This is a heavy relevant run because changes were made across modules. This should be manually forwarded.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/95131

**Pull request closed without merging**
