### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I did not include the clean up of current embedded impl into this pull, only disabled EmbeddedElasticsearchConnection, search team will take care of the clean up once sidecar is in.

If you think this pull is too big, you can ignore the commit with prefix portal-search-elasticsearch7-impl: clustering.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder
2.Random java.lang.InterruptedException on shutdown (https://github.com/shuyangzhou/liferay-portal/pull/8794)
3.[Test Case 4g - Network disconnection](https://docs.google.com/document/d/1hWodi6XIHnElZ-YYvElAZwYdK_7eheG7NNqZmzypgf8/edit#heading=h.lef6wd3v2ivu) failed

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Fix 3.Test Case 4g - Network disconnection and resend at https://github.com/shuyangzhou/liferay-portal/pull/8852

**Pull request closed without merging**
