### PR TITLE
[TECHNICAL-SUPPORT] LPS-64664 JournalArticleIndexer

### PR DESCRIPTION
**Pull request by Preston-Crary**
This improves article indexing time by about 15%.  When indexing all articles for a structure the time is improved by about 93%.  Garbage objects are drastically reduced as well.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Dropped 196763b since it caused a test failure.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest Fixed semantic version failure.

**Comment by shuyangzhou** [comment]
Closing old pulls, we can revisit if necessary

**Pull request closed without merging**
