### PR TITLE
LPS-96553 Avoid enabling components for cache replication when cluster is disabled

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @vicnate5 
Could you please help me check the test result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian the tests that failed, are the ones also failing elsewhere at head. One of the runs had strange behavior, but it did not show up on the second run:
```
21:55:33,975 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.exportimport.internal.messaging.CheckSystemEventMessageListener.com.liferay.exportimport.internal.messaging.CheckSystemEventMessageListener is not yet deployed on master
21:55:33,992 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.exportimport.web.internal.messaging.DraftExportImportConfigurationMessageListener.com.liferay.exportimport.web.internal.messaging.DraftExportImportConfigurationMessageListener is not yet deployed on master
21:55:34,001 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.announcements.web.internal.messaging.CheckEntryMessageListener.com.liferay.announcements.web.internal.messaging.CheckEntryMessageListener is not yet deployed on master
21:55:34,023 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.server.admin.web.internal.messaging.PluginRepositoriesMessageListener.com.liferay.server.admin.web.internal.messaging.PluginRepositoriesMessageListener is not yet deployed on master
21:55:34,034 WARN  [main][ClusterSchedulerEngine:602] Property "scheduler.enabled" is disabled in the master node. To ensure consistent behavior, this property must have the same value in all cluster nodes. If scheduler needs to be enabled, please stop all nodes and restart them in an ordered way.
21:55:35,716 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.recent.documents.web.internal.messaging.RecentDocumentsMessageListener.com.liferay.recent.documents.web.internal.messaging.RecentDocumentsMessageListener is not yet deployed on master
21:55:35,723 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.subscription.web.internal.messaging.DeleteExpiredTicketsMessageListener.com.liferay.subscription.web.internal.messaging.DeleteExpiredTicketsMessageListener is not yet deployed on master
21:55:36,629 INFO  [main][ClusterSchedulerEngine:359] Memory clustered job com.liferay.portal.security.ldap.internal.messaging.UserImportMessageListener.com.liferay.portal.security.ldap.internal.messaging.UserImportMessageListener is not yet deployed on master
```
Full log: https://testray.liferay.com/reports/production/logs/test-1-19/1559855650484/test-portal-acceptance-pullrequest(master)/4571/functional-tomcat90-mysql57-jdk8/8/0/jenkins-console.txt.gz

if this doesn't look related to your changes, it should be OK, I can look into the tests that are failing at head.

**Comment by tinatian** [comment]
Thanks @vicnate5 ! It should not be related to this change.

@shuyangzhou  This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74372

**Pull request closed without merging**
