### PR TITLE
COMMERCE-4880

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @shuyangzhou this pull originally came to me via https://github.com/brianchandotcom/liferay-portal/pull/95660

As I looked at it some more, it smelled fishy to me because I've seen your ProcessBuilder etc.. and this looks almost the same but slightly different.

Can you work with @igorbeslic to send this back to me? Thx.

**Comment by shuyangzhou** [comment]
@igorbeslic this needs to be changed to use ProcessExecutor. It was using ProcessUtil, because it was invoking local sh file. Now you are changing it to use java client. It should be using ProcessExecutor which provides much more support and control comparing to ProcessUtil. Just grep "ProcessExecutor", you can find example usages of it in "document-library-asset-auto-tagger-tensorflow", "portal-search-elasticsearch7-impl" for Sidecar, and AudioProcessorImpl/PDFProcessorImpl/VideoProcessorImpl.

Let me know if you need any help on applying it.

**Comment by igorbeslic** [comment]
@matijapetanjek

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9657

**Pull request closed without merging**
