### PR TITLE
LPS-138706 Fail to publish the publication with deletion folder when the document deleted on production

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-138706

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
@suilin Could you please take a look at this branch and test results when you're back re: the issues in [this ticket](https://issues.liferay.com/browse/LPS-138706)? The scenario in the ticket description should not cause a merge conflict anymore. Thanks a bunch!

**Comment by suilin** [comment]
ci:test:publications-environments

**Comment by suilin** [comment]
Hi @ctang3, I still can reproduce the issue with your commits, I updated on the ticket, could you look at it again? Thank you!

**Pull request closed without merging**
