### PR TITLE
LPS-81993 Portlet 3.0: Improve performance of top_head.jsp by inspecting portlets on the page for a portlet hub requirement

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@slnn have you already verified this?

**Comment by ngriffin7a** [comment]
@shuyangzhou I doubt @slnn has had an opportunity to verify the performance improvement. But I would think that a simple iteration through all the com.liferay.portal.kernel.model.Portlet objects on a portal page would be faster than executing all the code in RenderStateUtil for those portlet objects.

**Comment by shuyangzhou** [comment]
Ok, thanks @ngriffin7a ! Let's wait for @slnn to verify it first, it should be done within a day.

**Comment by ngriffin7a** [comment]
@shuyangzhou sounds good, thanks.

**Comment by ngriffin7a** [comment]
@shuyangzhou While we wait for @slnn to verify, I just wanted to mention that I analyzed the test results from CI and I don't think that the LocalFile.PGStaging#ActivateRemoteStaging failure is related.

**Comment by shuyangzhou** [comment]
Thanks @ngriffin7a ! Once @slnn clears it, this is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61398

**Pull request closed without merging**
