### PR TITLE
Lps 67565 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:tck

**Comment by arthurchan35** [comment]
@shuyangzhou 
I have ran failed test locally without the fix, and it was also failing, so it's not related to the fix.
@dantewang 
tck test failure has been fixed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/77166

**Pull request closed without merging**
