### PR TITLE
Aop debug

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@vicnate5 can you take a look at the functional failures?  Can you post the steps here to test them manually?  Interested in the ContentPages test failures. 

Thanks!

**Comment by vicnate5** [comment]
@Preston-Crary All the failures on this pull are also occurring at head on master. not related to your change.

**Comment by Preston-Crary** [comment]
@vicnate5 thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/65337

**Pull request closed without merging**
