### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Rebased and fixed service builder failure.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 are we running out of jdbc connections randomly? or this is a real issue?
@Preston-Crary please rebase.

**Comment by vicnate5** [comment]
Likely a random failures, 2 occurrences, we should re-run on the rebase.

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Test results are good. Failures not related. Single "unique" failure is just a flaky test.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
