### PR TITLE
[SampleSQLBuilder]LPS-112939

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @dantewang @slnn @GinsonRen @vicnate5

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9037

**Comment by slnn** [comment]
Closed this one https://github.com/dantewang/liferay-portal/pull/1602 as @tinatian fixed it here.

**Pull request closed without merging**
