### PR TITLE
LPS-95442 fix arquillian tests regression

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop (need to regen)

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
@petershin sent this to bchan already.

**Comment by rotty3000** [comment]
Sorry @petershin asked me to keep this open.

**Comment by shuyangzhou** [comment]
This issue is finished, right? I am closing it now, thanks @rotty3000 !

**Pull request closed without merging**
