### PR TITLE
LPS-65481 Cacheless TableMapper property inversion

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
I updated the test incorrectly, I've pushed up the changes. ci:stop

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/39292

**Pull request closed without merging**
