### PR TITLE
Lps 176935 new3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@shuyangzhou Looks good!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131450

**Pull request closed without merging**
