### PR TITLE
Lps 136673

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho it should not be related. But yeah, we can wait for the next run, please watch it for me, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou it passed this time, pull should be good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105127

**Pull request closed without merging**
