### PR TITLE
[TECHNICAL-SUPPORT] LPS-86482

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Hi @gregory-bretall,

can you give a full explanation for 4b8d801?

What do you mean, what is the problem exactly?  Also this commit leaves behind dead code.  Can you resend to me without the dead code and a better explanation of the changes?

Thanks

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
