### PR TITLE
LPS-77364 Portlet 3.0 TCK: PortletURL.removePublicRenderParameter(String name) should remove the public render parameter when the URL is invoked

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: These failures happened quickly and seem unrelated to this PR. I think that the majority of the tests were not executed. When you get an opportunity, please take a look. Thanks.

**Comment by jpince** [comment]
@ngriffin7a probably a compile error at head. No discussion on slack because it's a private module, so doesn't build with master + ant all, but CI pulls in the private modules for all pulls. Will look into it further when I get in.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by jpince** [comment]
@ngriffin7a looks ok. @shuyangzhou please review!

**Comment by ngriffin7a** [comment]
@jpince: Thanks! :)

**Comment by ngriffin7a** [comment]
@shuyangzhou I forgot to add "LPS-77364" in the commit message so I just updated the last commit message and pushed the branch. No code changes though -- just the commit message change.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54783

**Pull request closed without merging**
