### PR TITLE
LPS-147069 When the company default site has set a virtual host the URLs without /web/guest don't work using the company virtual hostname.

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-147069

Hi Team,

Trying to fix a bug from an Echo Component we have discovered this that blocks us from the solution of the other since its solution would amplify the occurrence of this.

That's because we want to contribute to the fix. The fix I've applied is simple and doesn't seem to break anything. I've added integration tests to make sure.

Please could you review it?

Thank you very much!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Sorry for the integration test failures. It has cost me to fix it because in my local it works well. I have already found the problem, in my portal-ext.properties I do not have the property "virtual.hosts.default.site.name" set, so it takes its default value "Guest", but in the CI environment it seems that it is set to "". I have already fixed the test so that it works correctly. Please apologize for the inconvenience.

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_1665

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found and this passes the manual steps in the ticket description.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10546

**Pull request closed without merging**
