### PR TITLE
LPS-X Refactor GraphQLServletExtender to use ServiceTrackerList

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@vicnate5 how is this pull?

**Comment by vicnate5** [comment]
@shuyangzhou Sorry for the delay, no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132873

**Pull request closed without merging**
