### PR TITLE
LPS-69916 Move logic to check valid app server type from BaseDeployer to ServerDetector

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69916

Related to https://github.com/shuyangzhou/liferay-portal-ee/pull/210

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48047

**Pull request closed without merging**
