### PR TITLE
[TS] LPS-104319 Massive performance problems with DXP on Weblogic

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-104319

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@NorbertKocsis this was explicitly disabled for weblogic at e1be4765bff353d5f43967acd02ded882e0b50cb, are you sure it is not an issue anymore?

@dantewang please review.

**Comment by NorbertKocsis** [comment]
Hi,

Apparently it doesn't cause any issues and I didn't know about any issues before it was disabled either. On the other hand the performance implications are clear and measurable.

Br,
Norbert

**Comment by shuyangzhou** [comment]
This is not right, last time I check, weblogic has strict rule on checking HttpServletResponse.getOutputStream() and HttpServletResponse.getWriter(). On the same HttpServletResponse object, if you call both methods, the 2nd will be rejected with a IllegalStateException.

By having the "JspWriter jspWriter = pageContext.getOut();" it implies the "HttpServletResponse.getWriter()" has been called already, without wrapping PipingServletResponse for another time, if this HttpServletResponse is called for getOutputStream(), it will fail.

I am trying to fix this problem in a different way, since I don't know how to test it, I am purely doing it by "guessing", please test my fix https://github.com/shuyangzhou/liferay-portal/pull/8496 on your side.

**Pull request closed without merging**
