### PR TITLE
[TS] LPS-117619

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-117619

/cc @holatuwol

### CODE REVIEW

**Comment by ericyanLr** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/9293

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9297

**Pull request closed without merging**
