### PR TITLE
Lps 100518

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 this is the Store CT support, please help me scan the CI results once it is done, thanks!

@slnn this needs a DL regression test, thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results on DocumentLibrary:


Portal Version | Git Id | Session Count | Mean TIme of Log In | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 6439321 | 25577 | 198 | 290
PR | - | 25768 | 212 | 300



Regards
Lily

**Comment by vicnate5** [comment]
@shuyangzhou Startup errors post upgrade
https://testray.liferay.com/reports/production/logs/test-1-5/1573605942896/test-portal-acceptance-pullrequest(master)/5815/functional-upgrade-tomcat90-mysql57-jdk8/3/0/liferay-log.txt.gz

Database: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.1.10/data-archive/data-archive-portal-mysql.zip

**Comment by vicnate5** [comment]
This is also going to need a regen on Service Builder
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230518/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
New results are good.

Unique failures here on MariaDB https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230709/#showFailuresLink, likely a flaky test, but would be worth a quick check.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80958

**Pull request closed without merging**
