### PR TITLE
Lps 148703 fix

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou I no longer see the shutdown issue.

FYI
There is a new issue upstream, but it is not caused by this PR as I see it on others.
Random `ERROR [Catalina-utility-1][HikariPool:541] HikariPool-10 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure`
This is happening at a 4% rate on this PR. At least 1 case in every suite here. 
0 cases of this on the previous PR https://github.com/shuyangzhou/liferay-portal/pull/10583 

e.g. https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2878/functional-upgrade-tomcat90-oracle193-jdk8/0/6/liferay-log.txt.gz?authuser=0

https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2134/functional-upgrade-tomcat90-mariadb102-jdk8/0/6/liferay-log.txt.gz?authuser=0
[Jenkins log](https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2134/functional-upgrade-tomcat90-mariadb102-jdk8/0/6/jenkins-console.txt.gz?authuser=0) (hard to tell when the error is happening)

**Comment by shuyangzhou** [comment]
@vicnate5 I have seen this "com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure" at least 2 years ago, it is most likely due to mysql server got shutdown, crashed or disconnected from network, it is an CI environment issue. CI team should look into mysql server logs to get some hints.

**Comment by vicnate5** [comment]
@shuyangzhou Yea, will treat this as a test issue for now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114490

**Pull request closed without merging**
