### PR TITLE
Spring4.1 jdk8

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang @slnn try on this pull.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@kenjiheigel it does not look like CI is jdk8 ready. It seems being compiled under jdk8. But we are still using jdk7 to run the tests, therefore all those UnsupportedClassVersionError. Can you take a look?

**Comment by shuyangzhou** [comment]
@dantewang @slnn try to regression tests anyway, I think it should work for benchmark tests. Just record the numbers for now, we won't do anything not until CI is cleared out.

**Comment by slnn** [comment]
@shuyangzhou 
yes, I am testing this PR with JDK8, it looks worked well for benchmark test.I will update test results as soon as possible.

**Comment by kenjiheigel** [comment]
The first issue that @shuyangzhou described was due to junit still using JDK7, since we only export JAVA_HOME to JDK8 and junit was using whatever was set in build.properties by junit.java

The solution was to update jenkins to update build.HOSTNAME.properties to set the junit.java property to use the local JDK8. This has resulted in another issue...
```
test-class-group:
   [delete] Deleting directory /opt/dev/projects/github/liferay-portal/bundles/data
    [junit] Testsuite: com.liferay.portlet.usersadmin.util.Batch-With-Multiple-Tests
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: com.liferay.portlet.usersadmin.util.Batch-With-Multiple-Tests:null: Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit]   at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
    [junit]   at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
    [junit]   at net.sf.antcontrib.logic.TryCatchTask.execute(TryCatchTask.java:207)
    [junit]   at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
    [junit]   at net.sf.antcontrib.logic.TryCatchTask.execute(TryCatchTask.java:207)
    [junit] 
    [junit] 
    [junit] Running com.liferay.portlet.usersadmin.util.Batch-With-Multiple-Tests
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:233: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:642: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:2010: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1392: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:943: Process fork failed.
      [get] Getting: http://test-1-17/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/29137//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20160325114035201.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160325114035201.txt
```

Shuyang suggested to test the JDK8 update in isolation so I'm doing that here:
https://github.com/kenjiheigel/liferay-portal/pull/182

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Pull request closed without merging**
