### PR TITLE
[Finder Cache]LPS-122032 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
@shuyangzhou Performance test result is here https://docs.google.com/spreadsheets/d/1MRZ0WwxvMtnkoJxAzOhwR5yrx1d8f3Vs6dI7p5ecFqk/edit#gid=0.

Login | 0.1%
WebContent | -0.5%
MB | -1.3%
Blog | -0.1%
DL | -0.6%
Wiki | -1.2%
AP | -0.2%

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
