### PR TITLE
LPS-60670

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
@arbetts - looks like tests are failing. can you take a look?

**Comment by arbetts** [comment]
taking a second look at the test failures

**Comment by arbetts** [comment]
i think we can't parallelize the calls from inside a transaction since we would be doing more DB calls outside of the thread that is holding the transaction ... i'm going to simplify the pull and just send the first commit ... i'll leave it for the component owners to decide if they want to parallelize their ADQ's

**Comment by arbetts** [comment]
@BryanEngler @shuyangzhou 
new pull request https://github.com/shuyangzhou/liferay-portal/pull/2084

**Pull request closed without merging**
