### PR TITLE
LPS-181729 Update batch engine import on portal startup (without client-extension fix)

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @shuyangzhou, following [your hints](https://github.com/shuyangzhou/liferay-portal/pull/11048#issuecomment-1534850381) here this is the latest attempt at resolving race condition in batch engine on portal startup. Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek what is this version trying to fix? I still get this error using the test you provided here https://github.com/shuyangzhou/liferay-portal/pull/11048#issuecomment-1533032208
```2023-06-13 16:46:38.547 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:221] Processing liferay-sample-batch.zip
Listening for transport dt_socket at address: 8000
2023-06-13 16:47:19.156 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:77] STARTED liferay-sample-batch_1.0.0 [1473]
2023-06-13 16:47:19.159 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.oauth2.provider.configuration.OAuth2ProviderApplicationHeadlessServerConfiguration~liferay-sample-batch-oauth-application-headless-server)][InterpolationConfigurationPlugin:135] Replaced value of configuration property 'homePageURL' for PID com.liferay.oauth2.provider.configuration.OAuth2ProviderApplicationHeadlessServerConfiguration~liferay-sample-batch-oauth-application-headless-server
2023-06-13 16:47:19.162 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.oauth2.provider.configuration.OAuth2ProviderApplicationHeadlessServerConfiguration~liferay-sample-batch-oauth-application-headless-server)][OAuth2ProviderApplicationHeadlessServerConfigurationFactory:185] OAuth 2 application with external reference code liferay-sample-batch-oauth-application-headless-server and company ID 20096 has client ID id-21ac342a-b754-2c96-7233-e1f99ac46ec
2023-06-13 16:47:19.160 WARN  [fileinstall-directory-watcher][BatchEngineUnitProcessorImpl:78] null
java.lang.NullPointerException: null
	at com.liferay.batch.engine.service.impl.BatchEngineImportTaskLocalServiceImpl._validateStrategies(BatchEngineImportTaskLocalServiceImpl.java:179) ~[?:?]
	at com.liferay.batch.engine.service.impl.BatchEngineImportTaskLocalServiceImpl.addBatchEngineImportTask(BatchEngineImportTaskLocalServiceImpl.java:67) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:79) ~[?:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy688.addBatchEngineImportTask(Unknown Source) ~[?:?]
	at com.liferay.batch.engine.internal.unit.BatchEngineUnitProcessorImpl._processBatchEngineUnit(BatchEngineUnitProcessorImpl.java:138) ~[bundleFile:?]
	at com.liferay.batch.engine.internal.unit.BatchEngineUnitProcessorImpl.processBatchEngineUnits(BatchEngineUnitProcessorImpl.java:66) [bundleFile:?]
	at com.liferay.batch.engine.internal.bundle.BatchEngineBundleTracker._processBatchEngineBundle(BatchEngineBundleTracker.java:195) [bundleFile:?]
	at com.liferay.batch.engine.internal.bundle.BatchEngineBundleTracker.access$100(BatchEngineBundleTracker.java:52) [bundleFile:?]
	at com.liferay.batch.engine.internal.bundle.BatchEngineBundleTracker$BatchEngineBundleTrackerCustomizer.addingBundle(BatchEngineBundleTracker.java:210) [bundleFile:?]
	at com.liferay.batch.engine.internal.bundle.BatchEngineBundleTracker$BatchEngineBundleTrackerCustomizer.addingBundle(BatchEngineBundleTracker.java:205) [bundleFile:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:467) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) [org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1046) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:247) [bundleFile:?]
```
The zip file is transformed into a osgi bundle by WarArtifactUrlTransformer and lead to this massive failure. It does not get a chance to reach to BatchEngineFileInstaller

**Comment by matijapetanjek** [comment]
I've pushed the latest WIP to demonstrate the issue I have encountered: `portal-osgi-web-wab-generator-impl` module (from osgi/static) cannot depend on a `batch-engine-api` module (from osgi/modules). At the time of portal startup `portal-osgi-web-wab-generator-impl` activation fails with message ```Unable to resolve import-package: com.liferay.batch.engine...``` and consequentially portal fails to start.

I'm unable to apply the same approach from `BatchEngineFileInstaller` in `WarArtifactUrlTransformer`.

**Pull request closed without merging**
