### PR TITLE
LPS-136729 Enable CT for repository

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/LPS-136729

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113389

**Pull request closed without merging**
