### PR TITLE
[Startup Tuning]LPS-84054

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou @Preston-Crary I will put this class in our list to add more tests for it.

**Comment by Preston-Crary** [comment]
Thanks @tinatian !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61885

**Pull request closed without merging**
