### PR TITLE
LPS-71925 ServiceBuilder db-name

### PR DESCRIPTION
**Pull request by Preston-Crary**
Already passed the CI without the regenerate here:
https://github.com/Preston-Crary/liferay-portal/pull/296

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou please review this pull, thanks!

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
errors unrelated, these should be fixed at head now, per BChan

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Had to update the build.gradle files that got reset with the release of portal-kernel.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4125

**Pull request closed without merging**
