### PR TITLE
[Bug Fix]LPS-102853 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @slnn,

Could you please run a diff for the shutdown performance? we would like to know if this is going to cause any noticeable regression.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80563

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @tinatian ,

Here are test results for shutdown, use the same machine that for daily startup test.

Compared with baseline, the shutdown on this pull is slowly.

Portal Version | Git Id | Startup total times | max shutdown (ms) | mix shutdown (ms) | shutdown average (ms) | shutdown STD (ms)
-- | -- | -- | -- | -- | -- | --
BaseLine | ba1032d | 5 | 4468 | 4329 | 4409.666 | 16.75974012
PR | - | 5 | 7492 | 4432 | 5459.666 | 1430.712954


Regards
Lily

**Pull request closed without merging**
