### PR TITLE
Startup optimization 223 upgrade step registrator tracker

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Majority of tests failed here because there is unsatisfied references and headless api is not available.

```
WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 195, name: com.liferay.portal.vulcan.impl, version: 5.0.88}
	Declarative Service {id: 498, name: com.liferay.portal.vulcan.internal.jaxrs.feature.VulcanFeature, unsatisfied references: 
		{name: _depotEntryLocalService, target: null}
		{name: _vulcanBatchEngineExportTaskResource, target: null}
		{name: _vulcanBatchEngineImportTaskResource, target: null}
```
Full log

Tested Headless with `curl -X GET -u 'test@liferay.com:test' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances`

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Still lots of failures here.

Startup issue after upgrade:
1. Import [7.3.10 database](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.3.10/data-archive/data-archive-portal-mysql.zip)
2. Run upgrade tool
3. Start Portal

Result: Portal does not finish starting. 
Does not affect all upgrade dumps and does not occur with autoUpgrade.

-------

We also have a large number of integration tests failing with
```
##
## com.liferay.document.library.permission.test.DLFileEntryPermissionCheckerTest > classMethod
##

	java.lang.UnsupportedOperationException
		at com.liferay.portal.kernel.service.PersistedModelLocalService.getBasePersistence(PersistedModelLocalService.java:44)
		at sun.reflect.GeneratedMethodAccessor1988.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
		at com.sun.proxy.$Proxy816.getBasePersistence(Unknown Source)
		at sun.reflect.GeneratedMethodAccessor1988.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:871)
		at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:710)
		at com.sun.proxy.$Proxy1055.getBasePersistence(Unknown Source)
		at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil._getBasePersistence(DataGuardTestRuleUtil.java:519)
		at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil._captureDataMap(DataGuardTestRuleUtil.java:414)
		at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil.beforeClass(DataGuardTestRuleUtil.java:132)
		at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:67)
		at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:22)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:54)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
		at java.lang.Thread.run(Thread.java:745)

```

I cannot reproduce this locally however, even running the tests in the groups like CI does. Maybe something went wrong on startup randomly?

Here is the full CI log: https://testray.liferay.com/reports/production/logs/2023-05/test-1-25/test-portal-acceptance-pullrequest(master)/825/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 I could not reproduce it either, adding a debug output to get more context.

**Comment by vicnate5** [comment]
@shuyangzhou Integration test logs with the `UnsupportedOperationException`s
https://testray.liferay.com/reports/production/logs/2023-05/test-1-31/test-portal-acceptance-pullrequest(master)/7926/modules-integration-mysql57-jdk8/2/18/jenkins-console.txt.gz?authuser=0

7.3.10 upgrade issue is resolved, but we have other upgrade tests failing, I was hoping it was 1 issues, but we have multiple.

------

6.2.10 Upgrade steps
1. Import https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip into mysql
2. Run upgrade tool
3. Start portal with `initial.system.check.enabled=true`

Result: Fails system check and portal does not start fully.

CI log https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2018/functional-upgrade-tomcat90-mysql57-jdk8/1/15/jenkins-console.txt.gz?authuser=0

------

7.1.10 Upgrade steps
1. Import https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.1.10.3/data-archive/data-archive-portal-mysql.zip into mysql
2. Run upgrade tool
3. Start portal

Result: Portal does not start fully.

CI log https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2018/functional-upgrade-tomcat90-mysql57-jdk8/1/20/jenkins-console.txt.gz?authuser=0

------

7.2.10 Upgrade steps
1. Import https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.2.10/data-archive/data-archive-portal-mysql.zip into mysql
2. Run upgrade tool
3. Start portal

Result: Portal does not start fully.

CI log https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2018/functional-upgrade-tomcat90-mysql57-jdk8/1/23/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 I need to put a hold on this. The issue is much bigger than I thought, I need to do some pre-cleanup before I can try this again.

**Pull request closed without merging**
