### PR TITLE
Lps 115438

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou recommend manual forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91515

**Pull request closed without merging**
