### PR TITLE
LPS-72541 Support reading portal configuration from environment variables

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mdelapenya there are some problems in the design:

1. Base on the ticket, the env variables are supposed to be read just once at startup time. However in the code, the env variables are read one by one at https://github.com/shuyangzhou/liferay-portal/pull/4268/commits/e35fff039065366890a87306a7e7603ac60e8ae8#diff-886d1f3b619a2041d62616b1f3ef9453R523
Please notice, ConfigurationImpl.getProperties() only loads the keys that show up in the portal.properties file. But at runtime, ConfigurationImpl.get() can be invoked with any key, which means we could load env variables that is configured after startup. Either we change the ticket description to become "we cache on the first read for each key". Or we load and cache all system env variables on startup, and stop reloading at runtime which would match the current ticket description.

2. We need a clear behavior definition for ConfigurationImpl.set(String, String).
We use this to change property value via code, which currently takes the highest priority. It out wins every configuration setup. After adding this env variable layer, that will no longer be true. If we do have an env variable to the querying key, we would ignore the property value, regardless it is from real property files or this 
ConfigurationImpl.set(String, String). This is a behavior change which I think could cause some regressions.

There are some other smaller issues too, we can talk about those after sorting out these 2 major ones.

If this needs further discussion, feel free to reach out to me via skype next week.

**Comment by mdelapenya** [comment]
So we could cache the env on Configuration initialisation, and read from that cache every time, which is not reloaded on runtime.

For 2), I would suggest that no matter the properties says, if there is a env var for that key, then the system env win.

**Comment by shuyangzhou** [comment]
@mdelapenya for 2), I don't think that is right. Just search for the ConfigurationImpl.set(String, String) usages. There are plenty of them, if we let env variable overwrites user api calls, I think most of them will break. For example, in MainServlet.checkWebSettings(String), we have a call like this:
```
PropsUtil.set(PropsKeys.SESSION_TIMEOUT, String.valueOf(timeout));
```
which is setting session timeout base on web.xml info in a forcibly way.
And another usage in VerifyProcessUtil._verifyProcess(boolean)
```
		if (ranUpgradeProcess && PropsValues.INDEX_ON_UPGRADE) {
			PropsUtil.set(PropsKeys.INDEX_ON_STARTUP, Boolean.TRUE.toString());

			PropsValues.INDEX_ON_STARTUP = true;
		}
```
which is forcing the reindex on startup regardless of what the properties says.

Fundamentally, I think we should give api calls the highest priority, that ensures code still has control over settings and ensure backward compatibility.

**Comment by mdelapenya** [comment]
I see... so besides the configurationEnvironmentCache, let's enforce api calls to have the top priority.

Makes sense? wdyt?

**Comment by shuyangzhou** [comment]
@mdelapenya if we decide to ensure 1) reading env variable exactly once during initializing and 2) keeping api calls the highest priority.
Then best solution should be doing normal initialization as before, and right after it, read through all env variables, use them to overwrite the properties we just loaded. People can only call ConfigurationImpl.set() after initialization is done. This way the api call still has the high priority. And we change from runtime pulling based exam to initialization time pushing based overwrite, which means no more fallbacks, that can also run faster.

**Comment by mdelapenya** [comment]
So basically, we must check:

1) if there is a property set by set(...) method, use that value
2) if there is an env variable representing that property, initialised once on portal startup, use that value, so changes in that env variable won't affect portal configuration
3) otherwise, use the portal* props

**Comment by shuyangzhou** [comment]
@mdelapenya that is logically right, but not using fallback checks. We should just keep one Properties/Map object inside ConfigurationImpl, just like right now.
During initialization, load the properties files as before, then load the env variables, which will overwrite the properties files values.
Then initialization is done, people has the freedom to call ConfigruationImpl.set() which is putting into the same Properties/Map object, which will overwrite previous loaded values.

In the end, we only remember the finally overwritten version of data, not multi-layers of data. That is the simplest and fastest way to support this feature.

**Pull request closed without merging**
