### PR TITLE
Startup optimization 86 search engine helper cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found in

com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest

```
Testcase: testAddDocumentsWithinInterval(com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery._getSearchEngineId(IndexableActionableDynamicQuery.java:177)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery._getSearchEngineId(IndexableActionableDynamicQuery.java:166)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.indexInterval(IndexableActionableDynamicQuery.java:131)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.addDocuments(IndexableActionableDynamicQuery.java:58)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest.testAddDocumentsWithinInterval(IndexableActionableDynamicQueryTest.java:73)
    [junit] 
    [junit] 
    [junit] Testcase: testAddDocuments(com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery._getSearchEngineId(IndexableActionableDynamicQuery.java:177)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery._getSearchEngineId(IndexableActionableDynamicQuery.java:166)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.indexInterval(IndexableActionableDynamicQuery.java:131)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.addDocuments(IndexableActionableDynamicQuery.java:58)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest.testAddDocuments(IndexableActionableDynamicQueryTest.java:60)
``` [Testray](https://testray.liferay.com/home/-/testray/case_results/1996174822?tab=history)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@Kvale1733 pushed a fix, please help me monitor the new results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124092

**Pull request closed without merging**
