### PR TITLE
[TECHNICAL SUPPORT] LPS-102817

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-102817

Service Builder finder results are not sorted consistently:
* in case you don't specify pagination parameters, sort is done in java side, in `XxxxModelImpl.compareTo(obj)` method (for example [WikiPageModelImpl.compareTo(wikiPage)](https://github.com/liferay/liferay-portal/blob/67313d14e94aa2f0d531b4e11658e03a2a65aed7/modules/apps/wiki/wiki-service/src/main/java/com/liferay/wiki/model/impl/WikiPageModelImpl.java#L1304-L1344))
* in case you specify pagination parameters, sort is done in database side

But sorting data in java side doesn't returns same results than database side:
* Database sort (MySQL or Postgresql) ignores accents (áááá = aaaa in sort time)
* Java sort doesn't ignore accents (áááá != aaaa in sort time)

So you have different order depending on the parameters you are using in finder.

Sorting large amount of data in java side, can also cause some throughput issues. It is better to rely in database side sorting as it is optimized doing that tasks.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79326

**Pull request closed without merging**
