### PR TITLE
LPS-86824 LPS-86851 LPS-86856 fix various portlet 3 CDI issues

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rotty3000 there are real failures caused by this pull, please see:
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=20,label_exp=!master/274637/testReport/

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 can you help me scan the test results? Thanks!

**Comment by rotty3000** [comment]
Hey @shuyangzhou I found another issue. I'm closing this for now to not was your time, but expect another one today.

**Comment by shuyangzhou** [comment]
Ok, thanks @rotty3000 !

**Comment by vicnate5** [comment]
@rotty3000 Can you CC me on pulls for this so I can help look for regressions?

**Comment by rotty3000** [comment]
Sure!

**Pull request closed without merging**
