### PR TITLE
LPS-131709 We don't need to normalize internal links

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-131709 We don't need to normalize internal links they might contain symbols that are not allowed in friendlyUrl

For example when we open the dialogue to upload an image or a file in a web content:
The original URL is this : /group/guest/~/control_panel/manage/-/select/image,journal/_com_liferay_journal_web_portlet_JournalPortlet_selectDocumentLibrary

The URL where it gets redirected:
/group/guest/~/control_panel/manage/-/select/image-journal/_com_liferay_journal_web_portlet_journalportlet_selectdocumentlibrary

From the original URL is converting the comma "," from `/image,journal/` to line "-" as `/image-journal/` 
As result is failing to load the dialogue correctly when passing thru I18nServlet.java 
`FriendlyURLNormalizerUtil.normalizeWithEncoding(
                                      path.substring(
                                              friendlyURLSeparatorIndex +
                                                       friendlyURLSeparator.length()))`

/cc @tinatian Please review, thanks

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@georgel-pop-lr Thanks for the fix! Could you please add test to cover different cases?

Thanks!
Tina

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr Thanks for the fix! Could you please add test to cover different cases?
> 
> Thanks!
> Tina

Hi @tinatian,

I realize that is kind of impossible to add test covers in this case as this problem is specific only for Jboss when forwarding with request dispatcher in VirtualHostFilter.java (check forwardURLString variable) only in this case Jboss is returning already an encoded getPathInfo() in I18nServlet.java, and we should not encode it again.

I pushed another solution that works in both server Tomcat and Jboss, basically I check if the path comes encoded or not by decode and compare it to original. If it does differ, original is encoded. If it doesn't differ, original isn't encoded.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10017

**Pull request closed without merging**
