### PR TITLE
Startup optimization 273 c n s p array

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 Can you take this over?

**Comment by Kvale1733** [comment]
@shuyangzhou 

1) These 3 integration tests now cause leftover data for com.liferay.portal.kernel.model.ResourcePermission. I was able to reproduce locally just by running the first one

com.liferay.roles.service.test.RoleLocalServiceSystemRolesTest
com.liferay.portal.verify.test.VerifyResourcePermissionsTest
com.liferay.portal.upgrade.test.DBUpgraderTest 

```
   [exec] 
     [exec] com.liferay.roles.service.test.RoleLocalServiceSystemRolesTest > classMethod FAILED
     [exec]     java.lang.AssertionError: com.liferay.roles.service.test.RoleLocalServiceSystemRolesTest caused leftover data for class :com.liferay.portal.kernel.model.ResourcePermission with data : [
     [exec]     	{"mvccVersion": 0, "ctCollectionId": 0, "resourcePermissionId": 2859, "companyId": 20096, "name": "com.liferay.portal.kernel.model.Role", "scope": 4, "primKey": "20104", "primKeyId": 20104, "roleId": 20104, "ownerId": 0, "actionIds": 127, "viewActionId": true} with backtrace info,
     [exec]     		Thread name : com.liferay.roles.test-executor-thread, id : 186, created : {"mvccVersion": 0, "ctCollectionId": 0, "resourcePermissionId": 2859, "companyId": 20096, "name": "com.liferay.portal.kernel.model.Role", "scope": 4, "primKey": "20104", "primKeyId": 20104, "roleId": 20104, "ownerId": 0, "actionIds": 127, "viewActionId": true} at 
     [exec]     java.lang.Exception
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil$RecordingSessionWrapper._record(DataGuardTestRuleUtil.java:731)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil$RecordingSessionWrapper.save(DataGuardTestRuleUtil.java:690)
     [exec]     	at com.liferay.portal.service.persistence.impl.ResourcePermissionPersistenceImpl.updateImpl(ResourcePermissionPersistenceImpl.java:7289)
     [exec]     	at com.liferay.portal.service.persistence.impl.ResourcePermissionPersistenceImpl.updateImpl(ResourcePermissionPersistenceImpl.java:64)
     [exec]     	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.update(BasePersistenceImpl.java:787)
     [exec]     	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._updateResourcePermission(ResourcePermissionLocalServiceImpl.java:2282)
     [exec]     	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._addResourcePermissions(ResourcePermissionLocalServiceImpl.java:1921)
     [exec]     	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.addResourcePermissions(ResourcePermissionLocalServiceImpl.java:393)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-35/test-portal-acceptance-pullrequest(master)/4475/modules-integration-mysql57-jdk8/3/22/jenkins-console.txt.gz?authuser=0)

2) Semver issue
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.service                  MINOR      25.0.0     25.0.0     25.1.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.kernel.service.ResourceLocalServiceUtil
     [exec] 		+   method     addResources(long,long,long,java.lang.String,java.lang.String[],boolean,boolean,boolean)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.portal.kernel.service.ResourceLocalServiceWrapper
     [exec] 		+   method     addResources(long,long,long,java.lang.String,java.lang.String[],boolean,boolean,boolean)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.portal.kernel.service.ResourcePermissionLocalServiceUtil
     [exec] 		+   method     addResourcePermissions(long,long,long,java.lang.String,java.lang.String[],boolean,com.liferay.portal.kernel.service.ServiceContext)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.portal.kernel.service.ResourcePermissionLocalServiceWrapper
     [exec] 		+   method     addResourcePermissions(long,long,long,java.lang.String,java.lang.String[],boolean,com.liferay.portal.kernel.service.ServiceContext)
     [exec] 			+   return     void
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-35/test-portal-acceptance-pullrequest(master)/4475/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, thanks!

**Comment by Kvale1733** [comment]
Looks like CI was reset yesterday so most tests failed to run. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139362

**Pull request closed without merging**
