### PR TITLE
LPS-66047 Fix for VerifyResourceActions

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest Rebased the changes.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
https://github.com/mbowerman/liferay-portal/pull/21

**Comment by Preston-Crary** [comment]
ci:stop

**Pull request closed without merging**
