### PR TITLE
LPS-83494 Overridden ResourceBundles

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@slnn can you check this to see if there's any performance regression?  Thanks!

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Sorry, forgot baseline.  I pushed the change and resubmitted for testing.

**Comment by slnn** [comment]
Hi @Preston-Crary 
Here are test results, no noticeable performance regression appeared:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 5266721 | 48315 | 277 | 84.2
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 48632 | 293 | 88.7

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 5266721 | 63332 | 592 | 215
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 63378 | 540 | 187

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 5266721 | 26038 | 292 | 376
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 26412 | 280 | 360

Blog

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 5266721 | 13154 | 151 | 250
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 13326 | 113 | 209

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 5266721 | 15615 | 32.4 | 68
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 15944 | 29 | 66.2

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 5266721 | 24018 | 464 | 206
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 24198 | 472 | 208

Wiki

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 5266721 | 15851 | 436 | 637
https://github.com/shuyangzhou/liferay-portal/pull/6658 | - | 15698 | 398 | 610

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6664

**Pull request closed without merging**
