### PR TITLE
LPS-X Allow multi resource bundles to overwrite the same language.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
reviewing results

**Comment by kyle-miho** [comment]
@shuyangzhou No unique failures found, however there are not many localization poshi tests run, I'll look into that seperately

**Pull request closed without merging**
