### PR TITLE
LPS-107255 Fix FR storage.size.suffix translations

### PR DESCRIPTION
**Pull request by rolandpakai**
Hey @shuyangzhou,

We need to localize the units (bytes, kbs, etc.) because in some languages like french have other names for the same unit.

Could you please check my changes and push it forward?

Thanks.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan the result, thanks!

**Comment by shuyangzhou** [comment]
@rolandpakai search with ```git grep "TextFormatter.formatStorageSize"``` you will see you missed some usages.

With this change you are moving all calls of TextFormatter.formatStorageSize to LanguageUtil.formatStorageSize.
You should :

1) Create a new TextFormatter.formatStorageSizeNumber to replace the TextFormatter.formatStorageSize, which only formats the number without adding the suffix. And use it inside you LanguageImpl.formatStorageSize.

2) Deprecated the current TextFormatter.formatStorageSize, and make sure all its usages are migrated to the new LanguageUtil.formatStorageSize.

Please make the adjustment above and resend.

**Comment by rolandpakai** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/8837

**Pull request closed without merging**
