### PR TITLE
Urlrewrite extract

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in automation results.

Regarding manual testing, the dev team for Blogs and Message boards could not provide a way to trigger the URL patterns, it seems some of these might be very old and no longer used.

What I did was check manually that the redirects can be triggered (even if it goes to a URL that doesn't exist).

Manual Testing Steps:
1. Modify urlrewrite.xml to redirect the message boards URL 
```
<to type="permanent-redirect">%{context-path}/web/guest/custom/community/forums/-/message_boards$1</to>
```
2. Start Portal and login
3. Navigate to `http://localhost:8080/web/guest/community/forums/message_boards`
3. Assert redirect to `http://localhost:8080/web/guest/custom/community/forums/-/message_boards`. This returns a "Not found" page, but the URL is as expected

These steps PASSED both before and after your change. I checked `redirect` and `permanent-redirect`.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112014

**Pull request closed without merging**
