### PR TITLE
[Bug Fix]LPS-92491

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for CI result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Hi @vicnate5,
Is the test failure here real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test broke adding a page, poshi issue, not related to this change.

**Comment by tinatian** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70645

**Pull request closed without merging**
