### PR TITLE
Chardet removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@koor4356 Please check the default suite results here when they come in.

**Comment by koor4356** [comment]
okay, thanks!

**Comment by vicnate5** [comment]
This is unfortunately still impacted by the previous regression at head this morning. Will need to re-run. I expect we will review tomorrow

**Comment by vicnate5** [comment]
ci:test

**Comment by koor4356** [comment]
@shuyangzhou @vicnate5,
This issue expects most tests LPS-144012. I am not sure if we want to rebase this PR. Otherwise no unique failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111269

**Pull request closed without merging**
