### PR TITLE
Lps 109118

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 what to do now?

**Comment by vicnate5** [comment]
@shuyangzhou I am going to fully scan and resend this, turning off any tests that failed for unrelated reasons since they are clearly not stable enough.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by vicnate5** [comment]
New PR
https://github.com/shuyangzhou/liferay-portal/pull/8960

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
