### PR TITLE
LPS-86852

### PR DESCRIPTION
**Pull request by danielreuther**
Hi Shuyang,

This PR is to fix FELIX-5974 on our side. The underlying problem is that the SCR is holding on to prototype-scoped references that would otherwise get garbage collected. This potentially leads to severe memory leaks for instance with Vaadin which requires certain components to be prototypes.

The patch also includes FELIX-5950 because it contains required logic.

The backport for 7.x will be slightly different since we're still using SCR 2.0.x there.

Thanks!

Cc @rotty3000

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please take this over.

**Comment by tinatian** [comment]
@shuyangzhou OK, got it.

**Comment by danielreuther** [comment]
@tinatian CI seems to fail because of a seemingly unrelated semantic versioning issue in PropsValues (which I'm not touching with my commits). The patch also only modifies internal (non-exported) packages of SCR so versioning shouldn't be an issue. Is there anything I can do to fix this?

**Comment by tinatian** [comment]
@danielreuther 
I do not understand why we have to patch instead of using the latest version of scr which contains the fix.

Thanks.
Tina.

**Comment by danielreuther** [comment]
@tinatian The currently released 2.1.12 doesn't contain the fix, yet. I'm actually pulling against master in order to eventually backport it to 7.0.x. For master itself I wouldn't mind if we waited for 2.1.14 to be released but I urgently need this fix in place for client on 7.0.x.

**Comment by tinatian** [comment]
@danielreuther 
2.1.14 is already released, so I just upgrade our usage. 
See https://github.com/shuyangzhou/liferay-portal/pull/7036.

Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by danielreuther** [comment]
@tinatian It was certainly not released when I created this PR. Maven Central claims it's been updated Nov 10--but I'm pretty sure that change wasn't visible yesterday. In any case, thanks for working on this!

**Pull request closed without merging**
