### PR TITLE
[SampleSQLBuilder]LPS-116679

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

We have finished the code for CT sample data generation, the logic is complex, so we would like to commit the changes step by step, meanwhile we would like to refine current code.

This pull is one of the pulls to refine the code.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @dantewang @slnn @GinsonRen

**Comment by slnn** [comment]
Hi @tinatian 

Test this pull on current head of master, the csvwriter does not work as no data be writen in the csv files, looking into this issue.


Lily

**Comment by dantewang** [comment]
Fetched

**Comment by slnn** [comment]
The problem caused by these code https://github.com/shuyangzhou/liferay-portal/blob/a1fd43f09c83b019ee15a47851f665bd65b08163/modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/CSVWriterHolder.java#L49~L53

removed the flush methd, csvfilewriter worked well.

**Comment by tinatian** [comment]
@dantewang @slnn Please fix and resend.

Why it is not working? it is same code as what was in DataFactory.
Another question is why the SampleSQLBuilderTest did not catch it?

Thanks.
Tina.





Thanks.
Tina.

**Comment by dantewang** [comment]
@dantewang Looking into the issue to find root cause... The test doesn't test content of CSV files. It just build sqls and load them into Hypersonic. The sql building runs without any issue and the writers are actually called.

**Comment by dantewang** [comment]
@tinatian Before your change, the writers used to write to csv files are `kernel.io.UnsyncBufferedWriter`. Although we override `flush()` method in these writers, the `close()` method will still write what's leftover in the buffer to the underlying writer:

```
	@Override
	public void close() throws IOException {
		if (writer == null) {
			return;
		}

		if (count > 0) {
			writer.write(buffer, 0, count);

			count = 0;
		}

		writer.flush();
		writer.close();

		writer = null;
		buffer = null;
	}
```

After your change, `CSVFileWriter` uses `petra.io.UnsyncBufferedWriter`. Its `close()` delegates to `flush()` to write leftover content to the underlying writer:

```
	@Override
	public void close() throws IOException {
		if (_writer == null) {
			return;
		}

		flush();

		_writer.close();

		_writer = null;
		_buffer = null;
	}
```

As a result, we have to avoid overriding `flush()` method if we use petra's `UnsyncBufferedWriter`.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/9247.

**Pull request closed without merging**
