### PR TITLE
LPS-X Avoid repeatedly trying to re-add default admin user. When the …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…default admin is removed, it is an user decision. It should stay being deleted, rather than magically readded back on the next bootup.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:users

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
ci:test:setup-wizard

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140544

**Pull request closed without merging**
