### PR TITLE
LPS-124887 More robust path handling to account for windows

### PR DESCRIPTION
**Pull request by mtambara**
cc @vicnate5

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Tested manually on Windows 10, resolves issue in the ticket. Tested with and without license files.

**Comment by vicnate5** [comment]
@kyle-miho

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9680

**Pull request closed without merging**
