### PR TITLE
String bundler zero copy

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@slnn I need a performance check for this pull. It is a bit complex, let's break it into 2 phases.

All tests should use G1 with `-XX:+UseStringDeduplication`.
For gc log on JDK11, make sure to log everything `-Xlog:gc*`
## Phase 1
- Use login and another GC heavy test case(Check previous VisualVM GC images to pick the most volatile test case).
- Run performance compare on JDK8 runtime.
- Run performance compare on JDK11 runtime.

So you should get 4 pairs of comparison for this phase.
Highlight the throughput difference, also upload all 8 test archives, I need to exam the gc logs.

Base on phase 1's results, we may or may not need to do phase 2.

## Phase 2
- Use all test cases.
- Run performance compare on JDK8 runtime.
- Run performance compare on JDK11 runtime.
- **On grinder side, we need to fix the total iteration**.
    - [ ] The total iteration should be large enough to allow the test reach to its stable status
    - [ ] The test archive should be captured right after all iterations are done without long delay (I think our default capturing logic is based on time rather than iteration, right? No need to do heavy refactor for this function, as long as you are not allowing the tomcat idling for too long, the gc log should still be valid.)
    - [ ] The goal is to check with same amount of work (concurrently and under pressure), what's gc difference.

Upload all archives, I need to exam the results.

This change is supposed to reduce our allocation rate which in turn reduces gc activity.

CC @tinatian @vicnate5

**Comment by slnn** [comment]
Hi @shuyangzhou 

Do we need to remove all benchmark customized settings when checking this pull?

Lily

**Comment by shuyangzhou** [comment]
@slnn no, this check needs maximum performance to push the GC to its limits to show difference. keep all original settings we used for max throughput

**Comment by slnn** [comment]
OK, got it. I will check it when env is free.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Test results for Phase1 have been updated in https://docs.google.com/spreadsheets/d/1tM5hR83Mom3Kyg-5QDinyt6BUcmHlOZ0M52yD3zXBDA/edit?usp=sharing

Regards
Lily

**Comment by shuyangzhou** [comment]
@slnn thanks! Very well organized results!
Please move to phase 2, but no need to run all test cases. Just login/DL + anther heavy and stable test case of your pick.
For the gc analyze, please add and highlight **allocation rate**.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149674

@slnn I sent out this pull. At this point we have enough data already. If the rest tests already started, please finish them to keep the data complete, otherwise no need to spend more time on this. Shift focus to g1 tuning.

Thanks!

**Pull request closed without merging**
