### PR TITLE
Deploy manager util removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
One failure here, but I think it isn't related. Rerunning test for it.

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@shuyangzhou This looks good so far, feel free to add more changes.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10456

**Pull request closed without merging**
