### PR TITLE
Startup optimization 98 cleanup bad scheduler message listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:workflow-metrics

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This breaks quite a few Workflow Metrics tests. Most of the tests have complex steps to reproduce.

The simplest steps I found to reproduce one of the issues:
1. Go to the Global Menu > Applications > Workflow > Metrics
2. View list in the UI

Expected Result:
Default workflow processes are listed:
MetricsBase

Actual Result:
No workflows are present.

I would focus re-testing on `workflow-metrics` suite, once this root issue is solved, we can see if the other issues are resolved.

**Comment by shuyangzhou** [comment]
ci:test:workflow-metrics

**Comment by vicnate5** [comment]
@anabuchmann Could you or someone else on the workflow team give us steps to reproduce the regressions here?

**Comment by vicnate5** [comment]
@shuyangzhou Workflow team will provide steps tomorrow, sorry for the delay.

**Comment by evanilson-santana** [comment]
ci:test:bundle

**Comment by lucasperj** [comment]
Hey @shuyangzhou. I have not found the bellow failures on the workflow-metrics [suite](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2042357284).

`[beanshell] 2022-11-03 00:21:43.762 WARN  [http-nio-8080-exec-10][BaseExceptionMapper:81] Problem {detail=null, status=Not Found, title=No SLA result exists with process ID {SLA_ID}, type=null}
[beanshell] com.liferay.portal.workflow.metrics.rest.internal.resource.exception.NoSuchSLAResultException: No SLA result exists with process ID 53045`

The curious thing is that it was reproduced locally without your changes for basically any test I have tried. 

The steps are pretty simple : 

- Go to Open Menu > Applications > Workflow | Process Buider
- Go to Configuration tab
- Assign Blogs to Single Approver
- Go to Open Menu > Applications > Workflow | Metrics
- Go to Single Approver Process Name
- Set a new SLA and save it
```
slaDefinitionDays = "",
slaDefinitionDescription = "SLA Description",
slaDefinitionEnd = "Process Ends: Approved",
slaDefinitionHours = "0001",
slaDefinitionName = "SLA Name",
slaDefinitionStart = "Process Begins"
```
- Add a new blog
- Go to Open Menu > Applications > Workflow | Metrics
- Go to Single Approver Process Name

**Comment by vicnate5** [comment]
@shuyangzhou Can you rebase or split this? I will just take the time to figure this out tomorrow.

**Comment by shuyangzhou** [comment]
@vicnate5 I separated the workflow commit and resend at https://github.com/shuyangzhou/liferay-portal/pull/10837

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10838

**Pull request closed without merging**
