### PR TITLE
[Technical Support] LPS-26811

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by arbetts** [comment]
@shuyangzhou there's been quite a few poshi test failures recently, do you think any of these failures are related to the pull?

**Comment by shuyangzhou** [comment]
There are too many of them. Normally there should be 1~3. I think it maybe related. Please take a look.

**Comment by arbetts** [comment]
ok I'll take a look

i think Senna has been messing with Poshi quite a bit so there might be more failures now

**Comment by arbetts** [comment]
rebase and retest

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Please rebase and resend still too many failures.

**Comment by lipusz** [comment]
@arbetts @peterborkuti Can any of you look into the test failures and resend?

**Comment by peterborkuti** [comment]
Hi, @arbetts, @lipusz 

I am working it

I will let you know about the outcome
Péter

**Comment by peterborkuti** [comment]
Hi, @arbetts, @lipusz

I continued the work here: https://github.com/giros/liferay-portal/pull/33

**Pull request closed without merging**
