### PR TITLE
[Template Security]LPS-134874

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the test results, thanks!

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou Real failures here. I reproduced locally.

Steps to Reproduce
1. Go to Documents and Media 
2. Add > File Upload
3. Upload and publish a new file
4. View the file

Error
```
ERROR [http-nio-8080-exec-6][runtime:59] Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> authTokenUtil.getToken  [in template "com.liferay.dynamic.data.mapping.service_6.0.17_CLASS_LOADER_CONTEXT_com/liferay/dynamic/data/mapping/service/dependencies/init.ftl" at line 188, column 24]
```
Full log https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/2554/functional-tomcat90-mysql57-jdk8/0/0/liferay-log.txt.gz

**Comment by shuyangzhou** [comment]
@tinatian please look into this.

**Comment by shuyangzhou** [comment]
@tinatian can you get back to this issue?

**Comment by tinatian** [comment]
Fix at https://github.com/shuyangzhou/liferay-portal/pull/10194

**Pull request closed without merging**
