### PR TITLE
LPS-X Make sure WorkflowMetricsSLAProcessMessageListener is only used…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… by Scheduler job.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:workflow-metrics

**Comment by vicnate5** [comment]
@shuyangzhou Steps to reproduce regression here:

Set portal-ext.properties
```
configuration.override.com.liferay.portal.workflow.metrics.internal.configuration.WorkflowMetricsConfiguration_checkSLADefinitionsJobInterval=I"1"
configuration.override.com.liferay.portal.workflow.metrics.internal.configuration.WorkflowMetricsConfiguration_checkSLAJobInterval=I"1"
```
1. Go to Global Menu > Applications > Workflow > Process Builder
2. Go to Configuration tab
3. Assign Blogs to Single Approver
4. Go to Global Menu > Applications > Workflow > Metrics
5. Go to Single Approver Process Name
6. Set a new SLA and save it
```
Name: SLA Name
Time Will Begin Counting When: "Process Begins"
Time Will Stop Counting When: "Process Ends: Approved"
Hours = "00:01"
```
7. Go to Site Product Menu > Blogs > Add a new blog > Submit for Publication
8. Wait 1 minute for workflow to become "Overdue"
8. Go to Global Menu > Applications > Workflow > Metrics
9. Go to Single Approver Process Name

Expected Result: Blog Entry is shown as "Overdue"
Actual Result: Nothing is shown as "Overdue"

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/10838

**Pull request closed without merging**
