### PR TITLE
LPS-93650 Migrate registry-test to arquillian bridge

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
@Preston-Crary registry tests are failing. Please resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7624

**Pull request closed without merging**
