### PR TITLE
LPS-77775 automatically add data-senna-track to head resources and add regression unit test

### PR DESCRIPTION
**Pull request by stiemannkj1**
Following instructions here to revert the revert commit and add the fix under LPS-77775: https://issues.liferay.com/browse/LPS-77775?focusedCommentId=1245270&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1245270. I also added a unit regression test.

Also, I had to make an API change for the sake of my `7.0.x` PR: https://github.com/liferay/liferay-portal-ee/pull/5202

### CODE REVIEW

**Comment by stiemannkj1** [comment]
Following instructions here to revert the revert commit and add the fix under LPS-77775: https://issues.liferay.com/browse/LPS-77775?focusedCommentId=1245270&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1245270. I also added a unit regression test.

**Comment by stiemannkj1** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by stiemannkj1** [comment]
ci:test

**Comment by stiemannkj1** [comment]
ci:test

**Comment by stiemannkj1** [comment]
ci:stop

**Comment by stiemannkj1** [comment]
ci:test

**Comment by stiemannkj1** [comment]
Re-sent here with updated commits: https://github.com/shuyangzhou/liferay-portal/pull/5777

**Pull request closed without merging**
