### PR TITLE
LPS-102671 AssetCategory treePath

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Based on Brian's origin/master to avoid conflict with AssetCategory mvcc change.

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79206

**Pull request closed without merging**
