### PR TITLE
[Performance Tuning]LPS-96289

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @vicnate5,
I am wondering if there is a functional test covering this issue: https://issues.liferay.com/browse/LPS-96341. The issue got the original pull reverted.

If not, could you please verify if we fix it in this pull?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:upgrade will catch the issue

**Comment by vicnate5** [comment]
@tinatian Tests show that the issue in https://issues.liferay.com/browse/LPS-96341 is fixed on this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74765

**Pull request closed without merging**
