### PR TITLE
[TS] LPS-138363

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-138363

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:sf:norebase

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failure not related.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
