### PR TITLE
[TS] LPS-129378 fragment bundles never reach the resolved status, so we have to check the installed one

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-129378

If you deploy a fragment bundle, it never changes to resolved state, it remains in "installed" state.

This regression is caused by the commit https://github.com/liferay/liferay-portal-ee/commit/097d72974f1c652f84ef738c3a324caf23dbee3f of https://issues.liferay.com/browse/LPS-122008

In that commit the `DirectoryWatcher.findBundlesWithFragmentsToRefresh` logic was removed because it was duplicated by the PortalFragmentBundleWatcher, but the PortalFragmentBundleWatcher doesn't consider that the fragment bundles never reach the resolved status until the host bundle is refreshed, so I have changed the existing condition from:
```
if (bundleEvent.getType() == BundleEvent.RESOLVED) {
```
to
```
if ((bundleEvent.getType() == BundleEvent.RESOLVED) ||
	((bundleEvent.getType() == BundleEvent.INSTALLED) &&
	_isFragment(bundleEvent.getBundle()))) {
```
With this new condition, the PortalFragmentBundleWatcher refresh bundles logic is executed, so the host bundle is refreshed and fragment bundle changes to "resolved"

Let me know if we can simplify this condition.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please take a look at this first, if ok, I will continue to review it, thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1067401_8205

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
