### PR TITLE
LPS-74348 ResourceBlock removal Part 2

### PR DESCRIPTION
**Pull request by Preston-Crary**
This part is preparation to move all the implementation details to ResourcePermission.  Next step is actually moving it over.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Closing old pulls, we can revisit if necessary

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6445

**Pull request closed without merging**
