### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@Preston-Crary 2 more things found in this analysis

#### 1. Issue with asset publisher upgrade from 6.2. Not database specific. Ping me if you need the dump.
```
ERROR [main][UpgradeStepRegistratorTracker:144] Failed upgrade process for module com.liferay.asset.publisher.web
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
     [java]  at [row,col {unknown-source}]: [1,283]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:127)
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:200)
     [java] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134)
     [java] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51)
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:155)
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118)
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:137)
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:86)
```
```
 Caused by: com.liferay.portal.kernel.exception.SystemException: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
     [java]  at [row,col {unknown-source}]: [1,283]
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.createPreferencesMap(PortletPreferencesFactoryImpl.java:130)
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.toPreferencesMap(PortletPreferencesFactoryImpl.java:879)
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.fromXML(PortletPreferencesFactoryImpl.java:213)
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.fromXML(PortletPreferencesFactoryImpl.java:96)
     [java] 	at com.liferay.portal.kernel.portlet.PortletPreferencesFactoryUtil.fromXML(PortletPreferencesFactoryUtil.java:59)
     [java] 	at com.liferay.asset.publisher.web.internal.upgrade.v1_0_0.UpgradePortletPreferences.upgradePreferences(UpgradePortletPreferences.java:304)
     [java] 	at com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences._updatePortletPreferenceValues(BaseUpgradePortletPreferences.java:447)
     [java] 	at com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences.updatePortletPreferences(BaseUpgradePortletPreferences.java:223)
     [java] 	at com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences.doUpgrade(BaseUpgradePortletPreferences.java:51)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 392 more
     [java] Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
     [java]  at [row,col {unknown-source}]: [1,283]
     [java] 	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:630)
     [java] 	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:467)
     [java] 	at com.ctc.wstx.sr.BasicStreamReader.readPIPrimary(BasicStreamReader.java:3919)
     [java] 	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2819)
     [java] 	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1019)
     [java] 	at com.ctc.wstx.evt.WstxEventReader.peek(WstxEventReader.java:306)
     [java] 	at com.liferay.portal.xml.StAXReaderUtil.read(StAXReaderUtil.java:39)
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.readPreference(PortletPreferencesFactoryImpl.java:806)
     [java] 	at com.liferay.portlet.PortletPreferencesFactoryImpl.createPreferencesMap(PortletPreferencesFactoryImpl.java:122)
     [java] 	... 401 more
     [java] ERROR - Failed upgrade process for module com.liferay.asset.publisher.web
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
     [java]  at [row,col {unknown-source}]: [1,283]
```
https://testray.liferay.com/reports/production/logs/test-1-22/1604946918241/test-portal-acceptance-pullrequest(master)/7489/functional-upgrade-tomcat90-mysql57-jdk8/6/23/jenkins-console.txt.gz

#### 2. Sybase 16 with search upgrade tests (multiple portal versions)
```
INFO  [main][UpgradeProcess:115] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 14465 ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.sybase.jdbc4.jdbc.SybBatchUpdateException: JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Type '65' not implemented.
     [java] 
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:156)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:119)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:180)
     [java] 	at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:337)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:152)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:144)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:124)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: com.sybase.jdbc4.jdbc.SybBatchUpdateException: JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Type '65' not implemented.
     [java] 
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:109)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:131)
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.doUpgrade(PortalUpgradeProcess.java:130)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 12 more
     [java] Caused by: com.sybase.jdbc4.jdbc.SybBatchUpdateException: JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Type '65' not implemented.
     [java] 
     [java] 	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseBatchUpdateException(ErrorMessage.java:1316)
     [java] 	at com.sybase.jdbc4.jdbc.SybStatement.batchLoop(SybStatement.java:2133)
     [java] 	at com.sybase.jdbc4.jdbc.SybStatement.sendBatch(SybStatement.java:1923)
     [java] 	at com.sybase.jdbc4.jdbc.SybStatement.executeBatch(SybStatement.java:1881)
     [java] 	at com.sybase.jdbc4.jdbc.SybStatement.executeBatch(SybStatement.java:1799)
     [java] 	at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeBatch(SybPreparedStatement.java:1832)
     [java] 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:125)
     [java] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
     [java] 	at com.liferay.portal.kernel.dao.jdbc.AutoBatchPreparedStatementUtil$BatchInvocationHandler.invoke(AutoBatchPreparedStatementUtil.java:119)
     [java] 	at com.sun.proxy.$Proxy305.executeBatch(Unknown Source)
     [java] 	at com.liferay.portal.upgrade.v7_4_x.UpgradePortletPreferences.doUpgrade(UpgradePortletPreferences.java:127)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 15 more
```

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9598

**Pull request closed without merging**
