### PR TITLE
LPS-81212 Portlet 3.0: Implement support for file upload

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: Almost all of these failures are the same as another PR that I sent earlier today for a different issue, so I assume they are unrelated. Please take a look when you have time so that @shuyangzhou can review. Thanks.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou errors look related to ModelListener exception or other issues that have already been addressed in upstream. Please review.

**Comment by shuyangzhou** [comment]
ci:retest

**Pull request closed without merging**
