### PR TITLE
COMMERCE-4880 Dispatch - Talend Java Process with unit and integration test

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Shuyang please check this one. Thank you very much!

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:stop

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9657

**Pull request closed without merging**
