### PR TITLE
Update last login

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:33675218

**Comment by shuyangzhou** [comment]
@victorhcunha please run a check for login case, thanks!

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | e039a71 | 13556 | - | 275 | 1,1,1 | 0,0,0 | 95,95,96
PR | - | 13686 | 0.9589849513 | 288 | 2,1,2 | 0,0,0 | 96,96,97


More details you can see [here](https://docs.google.com/spreadsheets/d/1e_Wu1Idijn2mWAx7Rp_IH2URFjrzinq9I1pdRygsLV4/edit?gid=744735759#gid=744735759).

**Comment by shuyangzhou** [comment]
@victorhcunha the baseline is way too high comparing to daily monitoring results. Can you check why there is such difference?

**Comment by victorhcunha** [comment]
The only relevant difference between the test configurations is that heap dump is enabled in the daily monitoring login test case.
For comparison, here is the Session Count result for the login test case without heap dump enabled: 13582 (6.77% higher than 12721 result on the same hash e039a71),

**Comment by shuyangzhou** [comment]
That does not make sense. Heap dump is a post sampling action, it can not affect the runtime sampling results.
@slnn has anything changed for heap dump collecting timing?

**Comment by slnn** [comment]
Hi @shuyangzhou 

Nothing changed the heap dump collecting timing, on the current head of the benchmark project master, the build will do and collect the head dump after collecting the results of grinder.

> That does not make sense. Heap dump is a post sampling action, it can not affect the runtime sampling results. @slnn has anything changed for heap dump collecting timing?

**Comment by shuyangzhou** [comment]
@victorhcunha please rerun on today's baseline. Please also include profiles.

**Comment by victorhcunha** [comment]
Here are the new results for login test case:

Env2 - Same baseline as today's daily monitoring
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 56d7797 | 13023 | - | 274 | 2,5,1 | 0,0,0 | 95,95,96
PR | - | 13300 | 2.127006066 | 281 | 2,2,1 | 0,0,0 | 96,95,95

Env3 - Same baseline as #11675
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | 9ff1f1d | 13503 | - | 266 | 4,2,1 | 0,0,0 | 94,94,95
PR | - | 13754 | 1.858846182 | 283 | 2,3,1 | 0,0,0 | 96,95,96

More details and the files for async profile results you can see in the same [spreadsheet](https://docs.google.com/spreadsheets/d/1e_Wu1Idijn2mWAx7Rp_IH2URFjrzinq9I1pdRygsLV4/edit?gid=744735759#gid=744735759).

**Comment by shuyangzhou** [comment]
@victorhcunha I need the profiles, not the heap dump.

**Comment by victorhcunha** [comment]
Yes, they are still in progress

**Comment by victorhcunha** [comment]
The CPU tracing profiles are available

**Comment by shuyangzhou** [comment]
@victorhcunha I need a rerun for this on current master baseline. For profile, I only need async cpu, no need to do tracing. Thanks!

**Comment by shuyangzhou** [comment]
@victorhcunha for the async cpu profile on PR, I need 2 of them. One is as normal. The other one with all probes disabled with option `probe_disable=*` https://www.yourkit.com/docs/java-profiler/latest/help/startup_options.jsp#probe_disable . This is one time only, don't persist it, we want probes by default. But I need to compare something special for this pull.

**Comment by victorhcunha** [comment]
Hi @slnn ! About the request for  `probe_disable=*` I updated the value for String profile in /home/me/dev/projects/liferay-benchmark-ee/grinder/liferay-grinder/src/main/java/com/liferay/benchmark/tools/startup/StartupProfilerUtil.java to use the login2 daily config to generate the profile with this option. But looking at the command line of the generated [snapshot](https://drive.google.com/file/d/1iDsiDNZGus2ZjZdDQ46slGpQOOEsxPCG/view?usp=sharing) I don't see the `probe_disable=*`. Was this the correct place to add this option or should I put it somewhere else?

**Comment by shuyangzhou** [comment]
@victorhcunha It should be in your tomcat/bin/startup_with_yjp.sh file

**Comment by victorhcunha** [comment]
Thanks, I got! The result is uploaded to the spreadsheet.

**Comment by shuyangzhou** [comment]
thanks @victorhcunha !

**Comment by shuyangzhou** [comment]
@victorhcunha please also run the `probe_disable=*` version for baseline next week. Thanks!

**Comment by victorhcunha** [comment]
Sure, I updated the spreadsheet with the baseline result.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155148

**Pull request closed without merging**
