### PR TITLE
LPS-X Avoid running unnecessary import background task

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by vicnate5** [comment]
@shuyangzhou Only unique failures are on the portlet TCK tests. I am re-running them, but it likely it is flakiness and not related.

**Comment by vicnate5** [comment]
Good to go

**Comment by shuyangzhou** [comment]
Thanks @vicnate5  !

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9370

**Pull request closed without merging**
