### PR TITLE
[SampleSQLBuilder]LPS-104416

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is a prepare step for adding support for change tracking.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9166

For https://github.com/shuyangzhou/liferay-portal/pull/9166/commits/3ba9044b57ab55b7e419bcd319bdf796e5f646de, send me a follow up on it, I prefer to deprecated SortedProperties if all usages can be cleanly removed, otherwise we need to fix it with unit test updated.

Thanks!

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/9168

**Pull request closed without merging**
