### PR TITLE
Lps 60923 reproduce

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Emm.... it is weird that it did not trigger the error, maybe there are other race conditions here, will dig into it.

**Comment by tinatian** [comment]
ci:retest

**Comment by tinatian** [comment]
Hi @shuyangzhou,

With this patch, I start portal in tomcat and shutdown, the error is triggered every time. I also run some integration tests which uses Arquillian, there is also the error log each time test is finished.

I have no idea why CI server tests can not catch it, do you have any clue about this?


Thanks.
Tina.

**Comment by shuyangzhou** [comment]
It can no longer rebase.

Please rebase and confirm you can still reproduce it locally, if so, resend it, I will check on it.

**Comment by tinatian** [comment]
Hi Shuyang,

With the fix of LPS-60923 merged in master, it won't be reproduced by this patch. This patch should reproduce the error of LPS-60923 every time at this specific branch. I have already tested it locally.

I rebased the code in case you are interested, please see https://github.com/shuyangzhou/liferay-portal/pull/2114

**Pull request closed without merging**
