### PR TITLE
LPS-76626 ServiceBuilder name-length-limit

### PR DESCRIPTION
**Pull request by Preston-Crary**
@Ithildir is there anything else I need to change for 78fde4a?  We want to make this configurable because other databases have limits as well.  For example mysql has a 64 character limit for table names and postgresql has a 63 character limit.  This property should be set to the smallest size alllowed for all supported databases, by default it's 30.  We may change this later since newer versions of Oracle allow 128 instead of 30.

CC @petershin

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Ithildir** [comment]
@Preston-Crary, this pull will fail since you didn't run `gradlew baseline` in `gradle-plugins-service-builder`.

**Comment by Preston-Crary** [comment]
@Ithildir, there aren't any exported packages... when I run it there's no change.

**Comment by Preston-Crary** [comment]
@Ithildir nevermind, I tried it in the wrong module.

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5533

**Pull request closed without merging**
