### PR TITLE
LPS-85007 Tomcat setup

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I tested it locally, and it works. I will trigger the ci test to verify in case I miss something.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62727

**Comment by tinatian** [comment]
@shuyangzhou The pull you are sending to brian is not the right branch. It should have 5 commits instead of 3.

Tina.

**Comment by shuyangzhou** [comment]
Weird, I must send the wrong one. Can you go ahead close mine and send yours to Brian directly. Thanks!

**Pull request closed without merging**
