### PR TITLE
LPS-86410 Unable to create a Widget Page Template with the same name as one previously deleted

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, I prefer to send you this PR. Mostly because of the last commit, since TransactionalPortalCacheHelper.java is changed. The other commits are fine from our point of view.

Thanks for the time!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please take this over, thanks!

**Comment by tinatian** [comment]
@shuyangzhou OK, got it.

**Comment by tinatian** [comment]
@jkappler 
Thanks for sending this to us, I do not think you should modify TransactionalPortalCacheHelper. TransactionalPortalCacheHelper should know nothing about the content it is going to store into the cache, and also MVCCPortalCache should not either.

You have something stored in the mvcc cache, and then you delete the model, at this time, the mvcc cache should also be updated by removing corresponding entry, later when you put NULLModel into mvcc cache, it will success.

The root problem here is why the mvcc cache is not updated by removing that entry, I am not sure if this is a wrong usage of API or missing some business logic or a bug. Is there a way to reproduce this part? if yes, could you please send me steps and I can take a look at it.

Thanks.
Tina.

**Comment by jonathanmccann** [comment]
@tinatian As per the commit message, you can use `LayoutPrototypeUADAnonymizerTest` to reproduce the behavior. Reverting the last commit and running that test should result in a test failure that exhibits the behavior described in the message.

Please let me know if you have any questions.

**Comment by tinatian** [comment]
@jkappler @jonathanmccann 

Please see https://github.com/shuyangzhou/liferay-portal/pull/7009

**Pull request closed without merging**
