### PR TITLE
LPS-61095

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou so this was the one that triggered OOM all the time.  I'm not sure why since I can't see the heap dump.  Everything seems to run fine locally.  The offending commit is the MainServlet change.

**Comment by shuyangzhou** [comment]
Ok, I will dig into it today.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34125

**Comment by shuyangzhou** [comment]
This exposed more issues, we need to revisit the dependency ordering again. Or maybe just update the test to do proper dependencies waiting.

Reopening this pull as reminder.

**Pull request closed without merging**
