### PR TITLE
[Factory Configuration]LPS-139670

### PR DESCRIPTION
**Pull request by tinatian**
Hi @achaparro @ericyanLr @vicnate5 ,
This pull patched felix configuration admin to always use "~" when generating factory configuration pid.

This pull support the file name with "~", "-" and "_" as separator of factory configuration file, thus after this pull https://issues.liferay.com/browse/LPS-137053 no longer need to be fixed.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
I will need to look at the automation here and check some things manually.

**Comment by vicnate5** [comment]
@tinatian This fails my local testing ([used CI bundle from this PR](https://files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/349/liferay-portal-bundle-tomcat.tar.gz))

**Steps to Reproduce:**
1. Using Google Chrome, Bootup portal and login to the home page
2. Go to Control Panel->System Settings->Infrastructure->Destination Worker
3. Add a new configuration and click save
4. Export the configuration you just added (will export with `_` naming under Chrome)
```
com.liferay.portal.messaging.internal.configuration.DestinationWorkerConfiguration_d264c17b-896a-4988-a780-1259c1f0195b.config
```
5. Delete configuration added in the UI
6. Add exported file to LIFRAY_HOME/osgi/configs/
7. Wait a minute for configuration to be imported and shown in the UI

**Result:** The configuration will not get imported from the .config file

If manually rename the config file to use the `~` naming, then the configuration will import successfully and show in the UI
```
com.liferay.portal.messaging.internal.configuration.DestinationWorkerConfiguration~d264c17b-896a-4988-a780-1259c1f0195b.confi
```

*Note: No regressions found in the automation results

**Comment by tinatian** [comment]
Fix and resend at https://github.com/shuyangzhou/liferay-portal/pull/10324

**Pull request closed without merging**
