### PR TITLE
Lps 111193 new

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@shuyangzhou 

1. Only one of the functional test failures is unique, but it it is likely a flake. I can test check it locally so you don't need to re-run.

2. Saw this on the integration tests a couple times, have not seen before
https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/377400/AXIS_VARIABLE=6,label_exp=!master/consoleText
```
ERROR [main][JDBCExceptionReporter:234] Duplicate entry '20021-37239-0' for key 'IX_7BF8337B'
```

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou The 1 unique functional test failure PASSED on local run, if the duplicate entry failure also looks unrelated, this can be manually forwarded.

**Pull request closed without merging**
