### PR TITLE
LPS-112913 Fallback in case illegal URI character in felix.fileinstall.filename property.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please take this over, this really looks like on saving fileinstall did not do proper escaping. We should fix it on saving rather than on reading. Even this is a limit on fileinstall side, I still want it to be fixed and carry it over to our replacement later.

**Comment by mtambara** [comment]
@shuyangzhou This is actually already fixed in master, this only shows up because the config is installed using an old fileinstall on 7.0 FP54

**Comment by shuyangzhou** [comment]
@mtambara please show @marianoalvarosaiz where the fix is at.
@marianoalvarosaiz please resend this as an upgrade process, we don't have broken code, but only broken data.

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou we need to change it inside verifyDictionary since we cannot make a proper upgrade for the same reason that the verify method was originally created in:

commit 96d8f42c72bbfe8ee9ec34019b64ceab678046e1
Author: Preston-Crary <preston.crary@liferay.com(opens in new tab)>
Date:   Wed Jun 20 18:04:18 2018 -0700    LPS-82771 Verify the Configuration_ table during startup to ensure the file name is not using absolute paths. We cannot use a normal upgrade since this is a static bundle that everything consumes.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz ok, that's fine, just put the fixing logic there, thanks!

**Comment by marianoalvarosaiz** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/9084

**Pull request closed without merging**
