### PR TITLE
LPS-X Drop upgrade inner steps support. From semantic versioning's po…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…int of view, having inner steps breaks versioning contracts, as inner steps can change without updating versions. Inner steps are not a stable version to resume upgrade from.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 the previous issue is fixed, right?

**Comment by vicnate5** [comment]
@shuyangzhou Only issue in the upgrade results is a unit test failure https://testray.liferay.com/home/-/testray/case_results/2272792222

Relevant still pending...

**Comment by vicnate5** [comment]
No additional issues found in Relevant results.

**Comment by shuyangzhou** [comment]
See https://github.com/achaparro/liferay-portal/pull/1054

**Pull request closed without merging**
