### PR TITLE
LPS-161513 Fix startup performance regression from 0bbaffd56613

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by 111Anna** [comment]
@shuyangzhou @tinatian  @dantewang  @GinsonRen, I ran this PR, the open count of prepared statement has dropped back to 700+.

Here are results for startup:

Portal Version | Git Id | Average StartupTime (ms) (without HSQL data) |Average Shutdown Time (ms) (without HSQL data) | Open File Number | ThreadCreate Count | Open count of Prepared Statement | Open Count of SQL
-- | -- | -- | -- | -- | -- | -- | -- |
Master-Head | 8d494372 | 29164.3 | 5323.3 | 1794 | 114 | 850 | 1185 |
Master-Head+PR-10821 | - | 29119 | 5335.6 | 1794 | 113 | 732 | 1179 |

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
