### PR TITLE
Startup optimization 298 upgrade info build number

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found here either.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-uniform/liferay-portal/pull/1424

**Pull request closed without merging**
