### PR TITLE
LPS-192517 Disable initial.system.check.enabled as it used to be.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@shuyangzhou If you send something soon
@zhangyan0701 can monitor the pull. Otherwise, I can look at the PR tomorrow.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found. Manual testing for https://liferay.atlassian.net/browse/LPS-192517 passed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138757

**Comment by zhangyan0701** [comment]
The changes here can fixes the issues when upgrade with upgrade client tool, but the same issues also happen during portal startup if auto-upgrade enabled and the changes here cannot fix them. 
More details please refer to: https://liferay.slack.com/archives/CLA7D1CNL/p1691043217425729?thread_ts=1691008033.128629&cid=CLA7D1CNL

**Pull request closed without merging**
