### PR TITLE
LPS-75777 Remove export packages from portal-configuration-cluster 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I have not tested this pull on CI, please wait for CI result.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:retest

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/52893

**Pull request closed without merging**
