### PR TITLE
[Bug Fix]LPS-127157 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
The root cause of this issue is:

1. ServiceConfigurationInitializer for com.liferay.style.book.service is running in one thread, and PortletTracker triggered by StyleBookPortlet is running in another thread.

2. The deployment of StyleBookPortlet will populate the resource permission for its root module resource action which defined in com.liferay.style.book.service

3. When the deployment of StyleBookPortlet runs first, the resource action defined in com.liferay.style.book.service has not been loaded yet, the corresponding module resource permission will not be added

The solution is:

Move the module resource action loading logic from ServiceConfigurationInitializer to ServiceConfigurationExtender. ServiceConfigurationExtender will be triggered synchronously when a liferay service bundle is activated on the same thread, it means, when a liferay service bundle is fully started, its resource actions are loaded for sure. Based on liferay web module will be activated after liferay service bundle by start level, this will guarantee  resource actions are loaded before portlet tracker is triggered by StyleBookPortlet

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5 and @kevhlee,
Could you please trigger the test that covers this issue if there is one?

Thanks
Tina.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:echo

**Comment by vicnate5** [comment]
@david-gutierrez-mesa I only see upgrade automation for Style Books on 7.3, and it is passing upstream. Do you have another other specific automation we can use to test this? I already triggered existing upgrade tests and echo tests. See https://issues.liferay.com/browse/LPS-127157

**Comment by tinatian** [comment]
Real failure, will resend.

**Comment by david-gutierrez-mesa** [comment]
Hi @vicnate5 style books were included in 7.3 so we don't have tests to test upgrades from 7.2 or older.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/10395

**Pull request closed without merging**
