### PR TITLE
[Deprecation]LPS-103620 modules part 5

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Cloud you please help me verify the ci result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Investigate unique poshi failure and it is a non-issue.

There is one other issue on this PR
```
1: Unneeded/incorrect Export-Package: com.liferay.portal.workflow.kaleo.forms.web.constants: ./modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/bnd.bnd (SourceCheck:BNDExportsCheck)
```

I noticed there is a dangling packageinfo at https://github.com/tinatian/liferay-portal/tree/LPS-103620/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/resources/com/liferay/portal/workflow/kaleo/forms/web/constants

**Comment by vicnate5** [comment]
@barrosdennys FYI, deprecated workflow code removal

**Comment by barrosdennys** [comment]
@inacionery FYI

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80349

**Pull request closed without merging**
