### PR TITLE
LPS-107933 Blacklist modules with null symbolicName to avoid NPEs

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-107933

Several NPE exceptions are thrown during startup in case a non-osgi jar is deployed to Liferay

This problem is caused only in case the jar file has a valid /META-INF/MANIFEST.MF file but it doesn't have any of the OSGI information entries (Bundle-SymbolicName, Bundle-Name, etc...)

So at the end we have a jar file deployed without Bundle-SymbolicName, that causes lots of NPEs

As a solution, I think we can blacklist those loaded osgi modules that are not correct.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jorgediaz-lr
Deploy a non-osgi jar is not supported, in case it is happening, it is an user mistake.
Use bundle blacklist is not a good choice, after all the bad bundle is still going through the bundle lifecycle.

We are building an unified bundle installer now, in order to get rid of FileInstall, if this is really needed, we can add the validation in the new installer. For now I don't think we should do anything for this.

CC @mtambara

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

It is true it was an user mistake (our customer deployed gradle-wrapper.jar from their workspace) but it took some days and interactions with them to discover the root cause of their exceptions.

So we need at least to add a ERROR trace somewhere, warning the customer. Is that ok for you?
Where would be the best place to add it?

About:
> We are building an unified bundle installer now, in order to get rid of FileInstall, if this is really needed, we can add the validation in the new installer.

Yes, I think we should add that to the new code, but this check should be also backported to 7.2, 7.1 and 7.0.

Thank you

**Comment by shuyangzhou** [comment]
@jorgediaz-lr after reading the ticket, I can see the complain is really at auto deployer blindly moves plain jar to osgi/modules.

So to just stop this issue, we can scan and prevent deployment at liferay's auto deployer layer. See https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/deploy/auto/AutoDeployDir.java#L122 . This way the "bad" jars won't be seen by osgi bundle installer at all. This can avoid any runtime overhead at osgi layer.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Thank you for the information, next week I will implement that solution.

Jorge

**Pull request closed without merging**
