### PR TITLE
LPS-72541 Support env vars configuration

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@mdelapenya this does not look right.
Nobody is using the ConfigurationImpl.getEnvironmentVariableName(). This method should not exist at all.

And in the _liferaySystemEnvironment preparation logic, it only removes the "LIFERAY_" prefix, it does not replace the "_" to "." and lower case it. So later in the ConfigurationImpl constructor, when it copies key/value from _liferaySystemEnvironment to _componentConfiguration, it is not overwriting anything at all.

**Comment by mdelapenya** [comment]
How are we going to represent filtered properties like foo.bar[a][b], or those with unsupported values, like `foo.bar[baz][/qux]`, in env var names? That's why I stored the env vars in the _liferaySystemEnvironment map.

If we want env vars to coexist in the componentConfiguration, then we need to define a convenient way of transforming unsupported env var characters to property keys. That's why, on first instance, I checked the key against the env var name using the transformation functions.

**Comment by mdelapenya** [comment]
Hi @shuyangzhou, any update on my last answer?

Thanks!

**Pull request closed without merging**
