### PR TITLE
LPS-72726 Pass in User to UserPortraitTag when we have the user inste…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…ad of the userId to avoid refetching the User.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
I didn't change or add any API in the pull.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49171

**Pull request closed without merging**
