### PR TITLE
Lps 130748

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@mtambara rebased on this pull, and ran the regen, it wipes out the entire portal.properties to output the LIFERAY_CONFIGURATION_OVERRIDE info, that can not be right. Please recheck.

**Pull request closed without merging**
