### PR TITLE
LPS-80511 Portlet 3.0: Implement javax.portlet.container-runtime-option in PortletTracker

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @rotty3000

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince I'm pretty sure that these failures are unrelated. The PR contains a commit that simply parses some elements from portlet.xml that had not been parsed before. Please take a look when you can and if you agree that they are unrelated, let us know so that @shuyangzhou can review. Thanks.

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR is simply collecting some container-runtime-option element info from portlet.xml and therefore has a very minimal impact on things.

Most of the failures are the same as two other PRs that I just reviewed.

One failure that is unique to this PR is "Unresolved requirement: Fragment-Host: org.apache.aries.jax.rs.whiteboard" but I can't see how that is related.

Please review when you have time. Thanks.

**Comment by jpince** [comment]
@ngriffin7a you are correct, the error in lpkg-override `org.apache.aries.jax.rs.whiteboard` is an unrelated, intermittent failure that Shuyang's team is looking into.

**Comment by ngriffin7a** [comment]
@shuyangzhou Closing this issue since it can be postponed. Will reopen in the future.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6408

**Pull request closed without merging**
