### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
I did not include the clean up of current embedded impl into this pull, only disabled EmbeddedElasticsearchConnection, will send out the clean up logic in later pulls.

If you think this pull is too big, you can ignore the commit with prefix `portal-search-elasticsearch7-impl: clustering`.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder
2.Clean up of embedded impl (will send in another pull)
3.Random java.lang.InterruptedException on shutdown (https://github.com/shuyangzhou/liferay-portal/pull/8794)
4.circuit-breaker issue shown on ci test ( LPS-104802)
5. Victor reported some manual tests failed on NPE, but I am unable to reproduce, for details, see https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit#gid=1206555946.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
Hi @shuyangzhou 
I just pushed one commit to fix log message, this will not affect any function but the log message.
@vicnate5 is using this pull to do manual tests, so I will wait for his test results to send out a new pull with the fix.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 I pushed a commit to show the bind address.

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
Fetched

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian Testing is complete on this PR.

No new issues found in the manual testing. Tested on CE version built locally since there are still known issues on DXP.

Manual Test log:
https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?ts=5e2a3128#gid=1206555946&range=E4

We should do another (smaller) round of testing DXP once https://issues.liferay.com/browse/LPS-108172 is resolved

**Upgrade Issue:**
Random post-upgrade startup issue is showing in Automation
https://testray.liferay.com/reports/production/logs/test-1-12/1580888549832/test-portal-acceptance-pullrequest(master)/2256/functional-upgrade-tomcat90-mariadb102-jdk8/4/0/jenkins-console.txt.gz

See 3 more examples here: https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=997601836&testrayRunId=997604160&errors=running

**Comment by xbrianlee** [comment]
FYI [LPS-104802](https://issues.liferay.com/browse/LPS-104802) was resolved yesterday (not reflected in the latest test run in this PR). We should do a final round of Search test analysis with all these changes together, but we can wait for [LPS-108172](https://issues.liferay.com/browse/LPS-104802).

**Comment by tinatian** [comment]
Rebase and resend at https://github.com/shuyangzhou/liferay-portal/pull/8817.

@vicnate5 I have not fixed dxp bundle issues, will update you once I have it.

Tina.

**Pull request closed without merging**
