### PR TITLE
[Sidecar]LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on https://github.com/BryanEngler/liferay-portal/pull/463.

This pull included all the features of sidecar expect an known random failure on shutdown, I will send a fix later.

Steps to use:

1. Run ant -f build-test-elasticsearch7.xml start-elasticsearch to build ES manually, will see a folder created in tomcat bundle home folder.
2. Rename the folder to elasticsearch7
3. Start portal, it is using embedded mode
4. Add config file to enable remote mode, will see logging in console
5. Go to localhost:8080, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch, Client Version: 7.3.0, Nodes: localhost (7.4.1)
6. To make sure cluster is running correctly, need to run `sudo sysctl -w vm.max_map_count=262144` first, or else ES will fail to start, this will be included in ES build process.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@tinatian All the Elasticsearch 7 functional tests failed unsatisfied references, expected?
```
Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 80, name: com.liferay.portal.search.elasticsearch7.impl, version: 2.0.0}
	Declarative Service {id: 3312, name: com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetIndexIndexRequestExecutorImpl, unsatisfied references: 
		{name: ElasticsearchClientResolver, target: null}
	}
...
```
Full log https://testray.liferay.com/reports/production/logs/test-1-8/1578043541858/test-portal-acceptance-pullrequest(master)/4588/functional-tomcat90-mysql57-jdk8/7/0/jenkins-console.txt.gz

**Comment by tinatian** [comment]
@vicnate5 No, this must be a bug, I will take a look at it and send a new pull.

Thanks.
Tina.

**Pull request closed without merging**
