### PR TITLE
LPS-81275 Portlet 3.0 TCK: PortletConfig.getContainerRuntimeOptions().get("javax.portlet.renderHeaders") does not always return null

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jpince: These failures must be unrelated. Please take a look and if you agree, let us know so that @shuyangzhou can review. Thanks.

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@ngriffin7a are you sure this change is needed?
I am pretty sure this retain will get rid of all unsupported options, https://github.com/ngriffin7a/liferay-portal/blob/df9b07ad1ae337b1903fb2a1b57a439446bb19bb/portal-impl/src/com/liferay/portlet/PortletConfigImpl.java#L122

So far we only have 2 hardcoded supported option javax.portlet.escapeXml and com.liferay.portal.portalContext. The javax.portlet.renderHeaders should be filtered out already, we should not need to do this explicit checking.

If this is really an issue, please update the ticket with reproduce steps so that I can see it alive.

**Comment by ngriffin7a** [comment]
@shuyangzhou I think it was a Portlet 3.0 TCK test that was failing. I will have to figure out which one it was, as I didn't mention it in the LPS-81275 ticket. For now, please move on to the next PR and I'll get back to you in the next few days with the TCK war that reproduces the problem.

**Comment by ngriffin7a** [comment]
@shuyangzhou You are correct, I just re-ran HeaderPortletTests_SPEC3_6_4_HeaderPortlet in the TCK and the change to PortletConfigImpl.java is not necessary. Apparently I made this change in my full-featured Portlet 3.0 branch prior to you refactoring to `keySet.retainAll(...)` in commit https://github.com/liferay/liferay-portal/commit/18eb44a312faeb7b16f445ef8504ec41351bbdbe#diff-80acf90bc9558e4f869b25fc370bb061R125

Closing this PR, and I will close the LPS-81275 as well. Good catch by you, and sorry to trouble you with an unnecessary PR.

**Pull request closed without merging**
