### PR TITLE
LPS-80949 Portlet 3.0: Portlet container must invoke the HEADER_PHASE of the portlet lifecycle

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR differs from the previous PR in that it simply contains 1 more commit (with 1 small change in RuntimePageImpl.java). All the failures unique to this PR appear to be unrelated. 

Please review when you get an opportunity. Thank you, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Please see https://github.com/ngriffin7a/liferay-portal/pull/14

**Comment by ngriffin7a** [comment]
@shuyangzhou Thanks for sending https://github.com/ngriffin7a/liferay-portal/pull/14

Your changes look good. If you can, please continue the review of this PR.

**Comment by shuyangzhou** [comment]
Ok, thanks for confirming, I will continue on it.

**Comment by shuyangzhou** [comment]
See https://github.com/slnn/liferay-portal/pull/302

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6286

**Pull request closed without merging**
