### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**
@achaparro upgrade changes are 8c418da...6db0bf5. Went ahead and moved those upgrades to 7.1.x, see 77e498fa - thanks for going over that part with me.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 are the failures real?

**Comment by achaparro** [comment]
Hi @Preston-Crary, @shuyangzhou, @vicnate5,

Regarding the upgrades moved to 7.1, UpgradeAnnouncementsPortletPreferences will fail because we use the new portletId:
https://github.com/shuyangzhou/liferay-portal/blob/77e498fa74ab7b514426241e9c1d7ce7de4bde66/portal-impl/src/com/liferay/portal/upgrade/v7_1_x/UpgradeAnnouncementsPortletPreferences.java#L85

before changing it later:
https://github.com/shuyangzhou/liferay-portal/blob/77e498fa74ab7b514426241e9c1d7ce7de4bde66/modules/apps/announcements/announcements-web/src/main/java/com/liferay/announcements/web/internal/upgrade/AnnouncementsWebUpgrade.java#L62

Can we update the upgrade queries to keep it in the same step instead of moving it to 7.1?

The others seem fine at first glance although it's hard to say it because other upgrades may depend on the current order.

**Comment by Preston-Crary** [comment]
Hi @achaparro,

I'm not sure what you mean, so I sent the pull for you to review first. Please see https://github.com/achaparro/liferay-portal/pull/751

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9565

**Pull request closed without merging**
