### PR TITLE
LPS-X Should not deploy test util jar into production code. Caused by…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… 0eb1907cbe83924f2ac203838516f2f4c9b81659

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137756

**Pull request closed without merging**
