### PR TITLE
Lps 66954 UnknownChannelHubException errors during server shutdown

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi shuyang,

I hope that you are well. :)

The issue is from EE customer ticket. Could you please review the PR when you have free time?

Regards,
Hai

**Comment by shuyangzhou** [comment]
This is not a good solution, as far as I can tell, you just want to make sure when there is no ChannelHub available for the company, making all the operations a no-op, right? Then just use the fetchChannelHub().

The _portalReady flag is weird, because it is not portal is ready or not, it is whether the ChannelHub for the company is ready.

**Comment by tinatian** [comment]
Hi @shuyangzhou 

Since the root problem is remote invocation from cluster is invoked when remote node is not ready, so I added this flag, if the name is not good enough, we can rename it.

The reason I did not use the fetch one is that, I am not sure if we still want to keep the exception be thrown at some special situation. Is it safe to swallow it for all situations? If it is safe to do that, of course the fetch one is a better solution.

Tina.

**Comment by shuyangzhou** [comment]
In this case, it can not perform anything without the channelhub, it used to be throwing an exception in that case. 

In this pull you changed to logically allowing missing channelhub and simply do nothing, then it is exactly the same as using fetch. I am only saying using fetch is a simpler solution comparing to the flag, you tell me whether we should allow missing channelhub or not? It is up to your business logic.

**Comment by tinatian** [comment]
Yes, for this case, my solution is same with the fetch one. 
The problem is I am not sure when the exception should be thrown and when should not. 
The only thing I am sure is that when portal is starting/destroying, the invocation from cluster should not be executed, right? And that's why I am doing this.

**Pull request closed without merging**
