### PR TITLE
LPS-72193 Add integration test for friendly URLs localisation update

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@pavel-savinov this pull is still not correct, you still have not answered my question. So let me ask it again.
For https://github.com/pavel-savinov/liferay-portal/blob/7f4e5814a04f90154f956dd178d8dda03fb97b38/modules/apps/foundation/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L64

`long groupId, long classNameId, long classPK, Map<String, String> urlTitleMap` combination could lead you to multiple exist FriendlyURLEntry, when that happens, what is the expected behavior?

Base on your current code, it will give up on updating, and create a new FriendlyURLEntry to hold all the translations. 
But this is not right, we have an unique index on G_C_U `create unique index IX_8AB5CAE on FriendlyURLEntryLocalization (groupId, classNameId, urlTitle[$COLUMN_LENGTH:255$]);` by giving all the urlTitles to the parameter groupId and classNameId, we may violate this unique index with some other exist FriendlyURLEntry. And you don't have any handling logic for that.

Please explain what is the expected behavior under this scenario, and please send your next pull to @Preston-Crary , he will forward it to me once this question is cleared out.

**Comment by pavel-savinov** [comment]
Hey @shuyangzhou,

Jorge is going to talk to Dave about writing the requirements, but he also asked me to answer your technical questions in this pull.

Regarding your question, it is true I didn't answer it, sorry. Instead what I did was to try to solve your concern in the code and also wrote a test to ensure that it is solved. You can find them here:
https://github.com/shuyangzhou/liferay-portal/pull/4632/commits/a99edaec82e9e4b2bf4ce47603eb1244671f4ff0

In particular, when you say that "long groupId, long classNameId, long classPK, Map<String, String> urlTitleMap combination could lead you to multiple exist FriendlyURLEntry", the tests I have linked above are explicitly testing that and proof that it cannot happen. This is prevented because addFriendlyURLEntry() has code to check if there is any existing localized entry that could conflict and solves the conflict.

Does this make sense? Is there anything else that I'm missing?

/cc @jorgeferrer

PS: I'll do as you say and send the next pulls to Preston.

**Comment by shuyangzhou** [comment]
@pavel-savinov this is mainly about the api, not just the internal details. By looking at the api, it confuses people, as it makes people think it can touch multiple entries, and there is no right way to do it. I did not go into detail about how you solved it inside the method body. As other developers most likely won't do that either. If the api is already confusing, nobody would really care how we "fixed" it internally, as they don't know how to use it in the "right" way.

**Comment by pavel-savinov** [comment]
@shuyangzhou Ok, I got it. I'll give it another try. I think that I'm able to resolve this confusion.
I'll send a pull to Preston cc-ing you and @JorgeFerrer, with a general explanation and also marks in code(commenting code lines here in GitHub) to make it as clear as possible. 
Thanks!

**Pull request closed without merging**
