### PR TITLE
LPS-75103 Portlet 2.0: Developer-defined custom portlet modes are ignored

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@shuyangzhou It is not possible to add methods to LayoutTypePortlet.java without a MINOR version increase in com.liferay.portal.kernel.model (which would break everything that uses ServiceBuilder) so the best I could do was type cast to LayoutTypePortletImpl in order to make this fix work.

**Comment by ngriffin7a** [comment]
@jpince This PR was closed prematurely due to a source-format-jdk8 problem in a source file that I didn't change. Please let me know the best way to move forward. Thanks.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@ngriffin7a BChan already fixed the error https://github.com/liferay/liferay-portal/commit/291afe30108741092c77995c85fe7e4634058844

**Comment by ngriffin7a** [comment]
@jpince Thanks

**Comment by ngriffin7a** [comment]
@jpince Please verify that these latest failures are unrelated to the commit in this PR. If you determine that to be the case, then please re-open so that Shuyang can review. Thanks.

**Comment by jpince** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince: Please verify that these failures are unlreated to the commit so that Shuyang can review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53467

**Pull request closed without merging**
