### PR TITLE
LPS-72193 FriendlyURLEntryLocalService

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou I'm not sure if we should add some additional validation to prevent having a defaultLanguageId that does not have a FriendlyURLEntryLocalization.

I'm forwarding it for now to avoid even more back-and-forth and will leave it to @pavel-savinov to add that later if it's needed.

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
@Preston-Crary Could you please take a look at these tests fails? The thing is that they are not failing in https://github.com/Preston-Crary/liferay-portal/pull/416

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4925

@pavel-savinov I also fixed your commit message for d42111a to use the correct ticket.

**Pull request closed without merging**
