### PR TITLE
Lps 52810 Use clusterNode instead of Address wherever possible

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
The change is incomplete.

There are still interface level Address usage at ClusterLink.sendUnicastMessage(Address, Message, Priority) and the ClusterLinkUtil utility methods.

And also, since we are wiping out the ClusterLink.getBindInetAddress(), we need a replacement for it. As there are logics that need an usable address before portal receives its 1st request.

Let's use the old ClusterLink.getBindInetAddress() value to initialize local ClusterNode.getPortalInetAddress() during ClusterLink/ClusterExecutor initialization. Then on the first request arrives overwrite the initial value. 

Please fix those and resend.

**Comment by shuyangzhou** [comment]
And let's try to break this pull to smaller chunks, remove one usage in each pull.

**Comment by tinatian** [comment]
I know it is incomplete. To make it complete, I need to change the relationship between clusterNode and address first,  which means I need to add the new ClusterManager logic first, and that's not we want to do first, so this is just to clean up some logic to make later changes simpler.

"As there are logics that need an usable address before portal receives its 1st request." Those who need to access portal before 1st request should configure their address by "portal.instance.inet.socket.address", we should not use the bind address of jgroups to access portal.

"Let's use the old ClusterLink.getBindInetAddress() value to initialize local ClusterNode.getPortalInetAddress() during ClusterLink/ClusterExecutor initialization.", we can't do that, because they represent differnt addresses. One is the address you bind to jgroups(configured by "cluster.link.bind.addr["cluster-link-control"), one is the address that you can access portal(confugred by "portal.instance.inet.socket.address").  Please see LPS-43608 for more deatils.

**Comment by shuyangzhou** [comment]
It is not that simple, the whole address thing we need to do it over again.
Ping me when you get online.

**Pull request closed without merging**
