### PR TITLE
LPS-84487 Avoid using ClusterExecutorUtil/MessageBusUtil/JSONFactoryUtil

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou Failures are not related.

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62251

**Pull request closed without merging**
