### PR TITLE
Bean Portlet API refactor, Spring IOC, MVC for CDI and Spring (REBASED)

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @jhinkey @sez11a @NovaBran @jonathansolorzano @peerkar

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou Master is currently not starting although it’s building correctly. I am rebuilding locally with commit 478cafc6 (recommended by colleagues in the Slack "build" channel). I will report back here with results.

**Comment by ngriffin7a** [comment]
@shuyangzhou I cherry-picked the commits from this branch on top of a `git checkout 478cafc69595d43ccda9e18dd9bc8d2eef1574e0` and it worked great. For your convenience, I pushed my "mvcbean-portlet-working-commit " branch here: https://github.com/ngriffin7a/liferay-portal/tree/mvcbean-portlet-working-commit

Seeing as how CI will be going down for several hours today, then if you have time to review this code then I recommend checking out my "mvcbean-portlet-working-commit" branch on your system.

1. Build the branch with `ant all`

2. Since the com.liferay.bean.portlet.spring.extension isn't released yet, you have to install it into your local repository:
```
cd modules/apps/bean-portlet/bean-portlet-spring-extension
LIFERAY_M2_DIR="../../../../.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0"
mvn install:install-file \
	-Dfile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.jar \
	-DgroupId=com.liferay \
	-DartifactId=com.liferay.bean.portlet.spring.extension \
	-DpomFile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.pom \
	-Dversion=2.0.0
```

3. In order to try the MVCBean portlet feature, I recommend that you get the following branch from my fork of the liferay-blade-samples repository:

https://github.com/ngriffin7a/liferay-blade-samples/tree/applicant

Then do the following:

```
#
# Job Applicant portlet that demonstrates CDI and JSP
#
cd maven/apps/applicant/applicant-mvcbean-cdi-jsp-portlet
mvn clean package
cp target/*.war $LIFERAY_HOME/deploy

#
# Job Applicant portlet that demonstrates CDI and JSP
#
cd ../applicant-mvcbean-spring-jsp-portlet
mvn clean package
cp target/*.war $LIFERAY_HOME/deploy
```

Please let me know if you have any questions. I'll try to be available on Skype for you.

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR is ready for review according to my comments in https://github.com/shuyangzhou/liferay-portal/pull/7683#issuecomment-486755123.

**Comment by shuyangzhou** [comment]
@ngriffin7a I am confused by the test instructions. why I need to use https://github.com/ngriffin7a/liferay-portal/commits/mvcbean-portlet-working-commit ?

When I tried to do 
```


cd modules/apps/bean-portlet/bean-portlet-spring-extension
LIFERAY_M2_DIR="../../../../.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0"
mvn install:install-file \
	-Dfile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.jar \
	-DgroupId=com.liferay \
	-DartifactId=com.liferay.bean.portlet.spring.extension \
	-DpomFile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.pom \
	-Dversion=2.0.0
```
On this pull, I got:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[ERROR] The specified file '/home/trunks/git/liferay-portal/.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0/com.liferay.bean.portlet.spring.extension-2.0.0.jar' not exists
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.267 s
[INFO] Finished at: 2019-05-01T14:17:00-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project standalone-pom: The specified file '/home/trunks/git/liferay-portal/.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0/com.liferay.bean.portlet.spring.extension-2.0.0.jar' not exists -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by ngriffin7a** [comment]
@shuyangzhou The mvcbean-portlet-working-commit branch is no longer needed because master has achieved stability again. There was a period of about 1/2 day when it was unstable. But if you are working with the mvcbean-portlet-working-commit then that's OK too.

I'll answer the question about `mvn install:install-file` in a moment. Standby.

**Comment by ngriffin7a** [comment]
The reason why the `mvn install:install-file` command is necessary is because the demo portlets are built with Maven which utilize with the normal $HOME/.m2/repository directory for grabbing dependencies. And the one dependency that is needed for the Spring ones is the com.liferay.bean.portlet.spring.extension-2.0.0.jar dependency because it has to live in WEB-INF/lib -- it is not an OSGi module.

But after running `ant all`, the dependencies aren't installed into the normal $HOME/.m2/repository directory.

Instead, they are installed into your $LIFERAY_PORTAL_SOURCE_HOME/.m2/repository directory.

So these commands are designed to basically copy the dependency from $LIFERAY_PORTAL_SOURCE_HOME/.m2/repository directory to the normal $HOME/.m2/repository directory.

```
cd modules/apps/bean-portlet/bean-portlet-spring-extension
LIFERAY_M2_DIR="../../../../.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0"
mvn install:install-file \
	-Dfile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.jar \
	-DgroupId=com.liferay \
	-DartifactId=com.liferay.bean.portlet.spring.extension \
	-DpomFile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-2.0.0.pom \
	-Dversion=2.0.0:
```

**Comment by ngriffin7a** [comment]
@shuyangzhou The following file should exist on your system after an `ant all`:
```
/home/trunks/git/liferay-portal/.m2/com/liferay/com.liferay.bean.portlet.spring.extension/2.0.0/com.liferay.bean.portlet.spring.extension-2.0.0.jar
```

**Comment by ngriffin7a** [comment]
@shuyangzhou Once the following dependency is released to repository.liferay.com then it will no longer be necessasry to run the `mvn install:install-file` command to build the demos.
```
<dependency>
    <groupId>com.liferay</groupId>
    <artifactId>com.liferay.bean.portlet.spring.extension</artifactId>
</dependency>
```

**Comment by shuyangzhou** [comment]
Did another ant all, still don't have that file.
Can you clean the steps and put it on the ticket? And QA can verify it first, maybe I am not doing something right.

**Comment by ngriffin7a** [comment]
@shuyangzhou I will rebase, clean out everything, and rebuild locally. Then I'll update the steps for the ticket.

**Comment by ngriffin7a** [comment]
@shuyangzhou After you run `ant all`, then if you run the following commands the com.liferay.bean.portlet.spring.extension-2.0.0.jar module will be installed into your normal $HOME/.m2/repository directory. Note that I neglected to give you the `gw clean install` command in the original instructions. Sorry about that :(

```
cd modules/apps/bean-portlet/bean-portlet-spring-extension
gw clean install
VERSION=2.0.0
LIFERAY_M2_DIR="../../../../.m2/com/liferay/com.liferay.bean.portlet.spring.extension/$VERSION"
mvn install:install-file \
	-Dfile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-$VERSION.jar \
	-DgroupId=com.liferay \
	-DartifactId=com.liferay.bean.portlet.spring.extension \
	-DpomFile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-$VERSION.pom \
	-Dversion=$VERSION
```

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/b0b10bb83d...123acb8686

**Pull request closed without merging**
