### PR TITLE
[Deprecation]LPS-105417

### PR DESCRIPTION
**Pull request by tinatian**
Will trigger ci test once it is fixed.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by kyle-miho** [comment]
No unique failures on Poshi and Integration, should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82659

**Pull request closed without merging**
