### PR TITLE
LPS-125830 With this, we want to increment the counter to that value

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@achaparro are you fixing the issue here https://github.com/shuyangzhou/liferay-portal/pull/9688 ?

**Comment by achaparro** [comment]
@shuyangzhou, oh, yeah it looks it is the same issue, we have two solutions! take the one you consider better :-)

Thanks!

**Comment by shuyangzhou** [comment]
I took Preston's version here https://github.com/shuyangzhou/liferay-portal/pull/9688, thanks!

**Pull request closed without merging**
