### PR TITLE
[Bug Fix] LPS-136637

### PR DESCRIPTION
**Pull request by yuhai**
@shuyangzhou, the pr is based on https://github.com/shuyangzhou/liferay-portal/pull/10195#issuecomment-891143897
cc @tinatian, @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1287401_353

**Comment by shuyangzhou** [comment]
ci:reevaluate:1287401_353

**Comment by shuyangzhou** [comment]
ci:reevaluate:1287401_353

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1327401_45

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105403

**Pull request closed without merging**
