### PR TITLE
[Bug Fix]LPS-106585

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou ,

I know this is not a good place to fix it, but I could not find a better one without affecting more logic. 

Currently the friendly url logic is such a mass and I am thinking of refactoring it, hopefully we can gain some performance by saving unnecessary invocations.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found in test results.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
