### PR TITLE
LPS-78194 Remove support for WSRP

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: Please take a look and if none of the failures are related to this PR then please let us know so that Shuyang can review. Thanks.

**Comment by timpak** [comment]
@ngriffin7a @jpince looks like none of the failures are related to the PR.

@shuyangzhou please review.

**Comment by ngriffin7a** [comment]
@timpak Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57442

**Pull request closed without merging**
