### PR TITLE
LPS-X Only need to callSetAttributes() when actually doing include. I…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…nline processing does not need any request attributes to be populated.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

@pyoo47 what's going on here?

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Pull request closed without merging**
