### PR TITLE
LPS-68951 UserFinderImpl.countByC_FN_MN_LN_SN_EA_S is slow in case of using database instead index and having a lot of users

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Shuyang,

This is a resent of https://github.com/brianchandotcom/liferay-portal/pull/45466. Added the logic to fix sybase failure and fixed the SB size in `doFindByC_FN_MN_LN_SN_EA_S`. Thanks!

/cc @jorgediaz-lr

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Is https://github.com/shuyangzhou/liferay-portal/pull/3558/commits/1012606e222f7d32e921c2b7efa859d7873461f2 the only difference from previous pull? @pei-jung

**Comment by pei-jung** [comment]
I added 1012606 and 2ec76ff

**Comment by shuyangzhou** [comment]
Ok, thanks @pei-jung ! I will wait until it passes CI, then forward it to Brian.

**Comment by pei-jung** [comment]
Thanks @shuyangzhou!

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45486

**Pull request closed without merging**
