### PR TITLE
Aspect j removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This looks good

Noting that there was a unique failure here https://testray.liferay.com/home/-/testray/case_results/1590700975, but the test passes locally.

**Comment by shuyangzhou** [comment]
@vicnate5 that's not related, but it is a random failure which got newly added. @tinatian please check the PortalFragmentBundleWatcherTest random failure.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111204
@vicnate5 can you make an announcement once it is merged in upstream for this change. Basically setup-testable-tomcat set the aspectj-weaver.jar into tomcat's setenv.sh, something like this:
``` CATALINA_OPTS="${CATALINA_OPTS} -javaagent:${project.dir}/lib/portal/aspectj-weaver.jar -Dorg.aspectj.weaver.loadtime.configuration=com/liferay/aspectj/aop.xml"```

For anyone who ran integration test in the old codebase, it would be pointing to ```lib/portal/aspectj-weaver.jar ```, once they rebase, the jar will be moved to ```lib/development/aspectj-weaver.jar ```. They can either update it manually, or remove it and rerun setup-testable-tomcat from build-test.xml

**Pull request closed without merging**
