### PR TITLE
LPS-77197 Increasing the length of Localized varchars

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

We need to increase the length of two fields after making them localizable. This solves a regression  bugcaused by a recent change:
https://issues.liferay.com/browse/LPS-72169

Thanks.

cc/ @ChiZelin @dantewang @marianoalvarosaiz

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
ModulesStructureTest.testScanBuildScripts fails due to commit 7a2e9cbca1a07c636cf256c2cec5f8279f040fd2
Could you take a look @mtambara?

**Comment by mtambara** [comment]
@marianoalvarosaiz Fix has been merged in master at 0ea57b73e74a5bdee29470c7af981a92a7ecb51c

**Comment by marianoalvarosaiz** [comment]
Thanks @mtambara

**Comment by achaparro** [comment]
Hi @shuyangzhou,

Did you have the chance to review this pull? We want to include these commits in the next Service Pack to solve the regression so we have just a few days to include it.

Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54970

**Pull request closed without merging**
