### PR TITLE
LPS-104711 Message Boards Tabs Inoperative on Content Page

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-104711

Previous PR was told to redirect to Core Infrastructure team: https://github.com/ealonso/liferay-portal/pull/2639#issuecomment-564985994

**Issue:**
Not all portlet tab options are properly functioning (i.e. Message Boards and Wiki). When clicking on the tab, the portlet does not render the appropriate view.

i.e. Message Board tab options ("Recent Posts", "My Posts", "Subscriptions", and "Statistics") are not functioning when the Message Board widget is added to a **Content Page**. It has been confirmed that only the "Categories" tab is highlighted, whereas if a Message Board widget is added to a **Widget Page**, all of the tab options are functioning as expected.

This issue is due to the use of the wrong portletId name so the mapping's key is inappropriately named.

The current implementation grabs the portletId name from the Portlet table, but the portlets that are used in Content Page have its own portletId names that is found in the PortletPreferences table. This causes the issue when fetching the parameters to render the tab because the mapping's portletId name does not match the portletId's name in the content page. Thus, it uses the default view since it could not find the value associated with its "portletId name" from the parameter map.

**Solution:**
My solution is to loop through the httpServletRequest parameter's mapping. If the parameter's key contains the rootPortletId but it does not contain the actual portletId, then the key needs to be replaced with the actual portletId. Otherwise, the parameter key does use the actual portletId and does not need to be replaced.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@koor4356

**Comment by koor4356** [comment]
@shuyangzhou, looks good. no unique failure.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82066

**Pull request closed without merging**
