### PR TITLE
Lps 95083

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 this is a relatively risky change, please help me watch out for the test results, thanks!
@lanceji92674957 please run a startup compare, thanks!

**Comment by lanceji92674957** [comment]
ok

**Comment by vicnate5** [comment]
@shuyangzhou No functional regressions

**Comment by vicnate5** [comment]
Going to run additional tests

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by lanceji92674957** [comment]
startup performance test result: 5-06 baseline: 116.39s, with this pull: 116.70s

**Comment by vicnate5** [comment]
@shuyangzhou Additional tests results look OK

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
