### PR TITLE
Lps 153483

### PR DESCRIPTION
**Pull request by shuyangzhou**
ci:test:sf

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, you can ignore the SF issue, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118845

**Pull request closed without merging**
