### PR TITLE
LPS-171006 OutOfMemoryError on startup when there are a lot of very large FragmentEntryLinks

### PR DESCRIPTION
**Pull request by jkappler**
Hi @shuyangzhou, first of all, thanks for your comments of the PR (https://github.com/brianchandotcom/liferay-portal/pull/129285#issuecomment-1405294955). We will try to improve based on them.

But before that, we wanted to ask about the original issue, and that is the out of memory exception that is thrown when reading the fragment entry links, before the propagation. This is the test that you asked a couple of weeks ago to Michael, where the contributor fails with an OOME on startup. In the test we create 100 pages with 100 fragments. These fragments have translations for the different locales (it's not farfetched), so the load will be high upon retrieval.

The idea that we had, was to retrieve only the ids, and then fetch the object, as you saw in the PR, this will lessen the server, but also increase the load time.

@ruben-pulido and @lfbesada are also working on this, so I want to keep them on the loop.

This was tested in a Mac with 32GB RAM. No tweaks on tomcat

Thanks for the time

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@jkappler yes, that is the original issue and the original solution Michael tried. It does avoid the oom, by fetching the object one by one basically giving the entity cache to chance to evict older ones when running out of space. But obviously this is a very slow solution.

If we can change the design to the sql update solution, we won't need to fetch anything back to portal, just do a portal side cache clearing after the update is done to avoid staled cache. That will avoid the OOM and also perform very fast.

Please send the test together with the solution, otherwise CI will suffer from the test.

**Comment by jkappler** [comment]
Will send tomorrow, thx @shuyangzhou

**Comment by jkappler** [comment]
Hi @shuyangzhou, I tested the update with DB2 and it doesn't throw any OOM Exception.

Still, talking to @lfbesada, I'm unsure if this would be the right way to go. We would be processing the editableValues and the html before rendering the fragment entry link. 

This would lead to performance issues when loading a page even if the fragment entry link is cached.

When we process a fragment entry link we would always need to do several checks:

1- Is this a contributed entry?
2- If yes, we would need to check if the HTML was changed
3- If yes, we would need to persist the new changes with the resources changed and also calculate the editable values

Would this be an acceptable solution in this case? Delegating the process times to the render of the page?

Thanks again for the time

@ruben-pulido, @ealonso

**Comment by shuyangzhou** [comment]
@jkappler since the update for DB2 works, could you check whether you can tweak the select to work on DB2 too? I did not try it, but Michael said it did not work. Maybe there is something can be tweaked.

If select can work on DB2, go with the select by DSLQuery, and you can update the out of synced entry links eagerly.

If select can not work on DB2, this update solution is the right way to go.
For ```1- Is this a contributed entry?```, you have to do this check no matter which solution you use, it should not be a concern particularly to this solution.
For ```2- If yes, we would need to check if the HTML was changed```, this only happens when you try to sync up entry and links, which is not during page rendering at all.
For ```3- If yes, we would need to persist the new changes with the resources changed and also calculate the editable values```, saving the "calculate the editable values" must happen anyway, either eagerly when the source html field is changed, or lazily on the first time rendering for that link. The net amount of overhead is the same.

For the update sql, runSQL in LocalService is right way to do it. We don't support update in DSLQuery. I hope the select on DB2 can work, then you won't need to do this runSQL call.

**Comment by jkappler** [comment]
Hi @shuyangzhou, thanks for the answer!

I tried to tweak the select the first time I went through the issue with DB2, but it didn't work at all. I'll give it another try tomorrow. If not, I'll work with the runSQL call.

Thanks again

**Pull request closed without merging**
