### PR TITLE
Lps 73024

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:close

Moved to this pull request:
https://github.com/shuyangzhou/liferay-portal/pull/4466

**Pull request closed without merging**
