### PR TITLE
Lps 127030

### PR DESCRIPTION
**Pull request by mtambara**
Running ci:test:backend for the modules-unit batch to ensure that all unit tests are fixed now

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:backend

**Comment by shuyangzhou** [comment]
@mtambara if you add the fallback case, why do you still keep the first couple fix that does the setting for "PropsUtil.setProps(new PropsImpl());" ? Those tests do not need any special override setting, right?

**Comment by shuyangzhou** [comment]
@mtambara also this is kind of introducing a security issue, the goal for the osgi override is making sure the portal properties must win once you set it. With this change, if someone manage to load ConfigurationOverridePropertiesUtil before PropsUtil is initialized, then non of the override will happen. We will have to find a different way to solve it.

**Pull request closed without merging**
