### PR TITLE
LPS-82119 Portlet 3.0: Decouple PortletURLImplWrapper, LiferayStrutsPortletURLImpl, and StrutsActionPortletURL class hierarchy from PortletURLImpl

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR too has only 1 "failure unique to this pull" which is a CounterLocalServiceTest which must be unrelated.

**This PR is a makes moves PortletURLImpl.java to the com.liferay.portlet.internal sub-package** which is a big deal from a semantic versioning / API perspective.

Please review as soon as you can, since API changes are only permitted until Monday. Thank you, Neil

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/59989

**Pull request closed without merging**
