### PR TITLE
Portal tiles plugin new

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by vicnate5** [comment]
Functional test results are OK.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
