### PR TITLE
Lps 105991

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures, LPKG tests only failed due to a known error thrown at head, otherwise they are working.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83358

**Pull request closed without merging**
