### PR TITLE
LPS-X Cleanup ServiceTracker usages in PortalImpl.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho will be checking this

**Comment by kyle-miho** [comment]
@shuyangzhou No unique failures found in the PR results

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131234

**Pull request closed without merging**
