### PR TITLE
Startup optimization 46 postpone repeated job one interval time to avoid startup storming

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
Did not get results in testray for this run, this is a known issue on CI the last week, reported and requested fix.

**Comment by shuyangzhou** [comment]
@vicnate5 do we need to rerun, or they can still gather results from previous run?

**Comment by vicnate5** [comment]
CI team isn't sure they can recover, re-running

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant:norebase

**Comment by vicnate5** [comment]
@shuyangzhou This looks good now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122054

**Pull request closed without merging**
