### PR TITLE
LPS-68512 Fixed reliance on java executable being in PATH

### PR DESCRIPTION
**Pull request by SGM3**
Fixes issue where the portal looks for the java executable in the PATH versus the one in JAVA_HOME on startup

### CODE REVIEW

**Comment by SGM3** [comment]
Was directed by Mike Han to send a PR here.

**Comment by shuyangzhou** [comment]
This is wrong, if you need a different java, you should modify the created ProcessConfig object, to assign a different path, not changing ProcessConfig's default logic.

**Comment by shuyangzhou** [comment]
And I have read the ticket, having the $JAVA_HOME/bin on $PATH is a requirement for setup. One should always do that. We have other auto diagnosing tools depend on that too, like running jps/jstack/jmap when system is acting funny. If the $JAVA_HOME/bin is not on $PATH, none of these will work either. It is a requirement, that can not be removed.

**Comment by SGM3** [comment]
Mike Han complete agreed with you on this, and I also agree, $JAVA_HOME/bin should be on the $PATH, normally.

I do not believe it is a requirement. For example, Tomcat is able to start up with no java in path while having $JAVA_HOME set (Tomcat refuses to startup without JRE_HOME or JAVA_HOME specified, regardless of what is in $PATH).

Demonstration for vanillas Tomcat in CentOS 7

    [myuser@localhost bin]$ which java
    /usr/bin/which: no java in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/myuser/.local/bin:/home/myuser/bin)
    [myuser@localhost bin]$ echo $JAVA_HOME
    /usr/java/jdk1.8.0_102
    [myuser@localhost bin]$ ./startup.sh && sleep 1 && tail -f ../logs/catalina.out
    Using CATALINA_BASE:   /home/myuser/apache-tomcat-8.0.32
    Using CATALINA_HOME:   /home/myuser/apache-tomcat-8.0.32
    Using CATALINA_TMPDIR: /home/myuser/apache-tomcat-8.0.32/temp
    Using JRE_HOME:        /usr/java/jdk1.8.0_102
    Using CLASSPATH:       /home/myuser/apache-tomcat-8.0.32/bin/bootstrap.jar:/home/myuser/apache-tomcat-8.0.32/bin/tomcat-juli.jar
    
    ...
    
    02-Dec-2016 00:35:24.787 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 2 2016 19:34:53 UTC
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-327.el7.x86_64
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
    02-Dec-2016 00:35:24.789 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk1.8.0_102/jre
    02-Dec-2016 00:35:24.790 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_102-b14
    02-Dec-2016 00:35:24.790 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
    02-Dec-2016 00:35:24.790 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/myuser/apache-tomcat-8.0.32
    02-Dec-2016 00:35:24.790 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/myuser/apache-tomcat-8.0.32
    
    ...
    
    [myuser@localhost bin]$ cat /etc/*rele*
    CentOS Linux release 7.2.1511 (Core)
    Derived from Red Hat Enterprise Linux 7.2 (Source)
    
    ...
    
    CentOS Linux release 7.2.1511 (Core)
    CentOS Linux release 7.2.1511 (Core)
    cpe:/o:centos:centos:7

The ProcessConfig initalize the value and does not consider the case whether or not JAVA_HOME is specified. I'm not aware of these diagnosis tools in Liferay you are referring too, but I can look into them too if you agree that this change is acceptable. I had discussed with Mike on whether this logic should be placed in the default constructor in `ProcessConfig.Builder` and he had convinced me to place it in the getter method as a fail-safe.

**Comment by shuyangzhou** [comment]
The bottom line is, ProcessConfig is just a data object, with no logic. We should not force detecting logic into it. The whole ProcessExecutor design supposes to stay as sample as it can. If it needs to know anything about the runtime env, it should be told so, rather than trying to detect it by itself.

**Comment by SGM3** [comment]
So instead, I should look into all references to ProcessConfig and modify how it being initialized? Mike had mentioned to me he would rather have this change contained, that why I targeted the ProcessConfig object versus it's callee.

If we do not do either change, we leave room for a (potentially) mal-configured server to run Tomcat with one version of Java and then have Liferay fork/start process with another version (for example if JAVA_HOME points to the latest version of 8 and the one in path points at one with known security issues). Are we in agreement the way an application server like Tomcat relies on finding the java executable through JAVA_HOME, the Liferay application should do the same?

**Comment by shuyangzhou** [comment]
No, it is designed to allow the forked jvm to be on a different jdk as portal is running. There are features rely on that. That's why the java executable is changable.

To me, it does not matter how appserver is doing to find the java executable, we are not required to follow that. It has been assumed that PATH must have JAVA_HOME/bin when ProcessExecutor was designed, as it needs a default java executable.

It is ok to change that assumption, but there are many things depend on that, and simply change the default logic inside ProcessConfig won't cover all cases.

So unless there is a strong reason we must do this, I'd rather blame this as a broken server configuration. As this is not something new we are asking for, it is the requirement we ask for since the beginning of ProcessExecutor which can be traced back to 6.1 or 5.2, which I can not really remember.

What is stopping the customer to simply add the JAVA_HOME/bin to PATH?

**Comment by SGM3** [comment]
"...[Simply changing] the default logic inside ProcessConfig won't cover all cases." We could make sure the callee of the ProcessConfig constructor passes in a explicit path to the Java runtime. If this doesn't solve this issue, can I ask why is that? From my [admittedly limited] knowledge of the Liferay application, we do no rely on any external frameworks that require JAVA_HOME/bin to be located in PATH.

I had found this short snippet from a blog, I cannot say it's 100% credible, but it outlines my feelings when working with a Java Application, as I consider Liferay to be.

[Why do you need a JAVA_HOME environment variable](http://www.gunnalag.com/2011/03/30/why-do-you-need-java_home-environment-variable/)

I may be wrong, but most commonly used Java tools/application seems to utilize JAVA_HOME to grab all java runtime environment binaries unless explicitly modify it's scripts to do otherwise (Ant, Maven, Tomcat, JBoss, ElasticSearch). Explicitly pre-pending JAVA_HOME/bin in Path does solve the issue, unless we explicitly add it to our startup sequence, this cannot be guaranteed. It does not prevent a user from mistaken having another runtime on the Path on the off chance that they do not either add it Path or append the runtime when there is another runtime in Path. This might be user error, but it seems like its a detectable/preventable error if we change the requirement to solely use JAVA_HOME instead of PATH.

If this coverage of the user error is sufficient, we can discuss the level of effort are we looking at if we were to change the assumption for having the java binaries to be located in JAVA_HOME vs in PATH? ProcessConfig only has 48 direct points of usage based on a quick search in liferay-portal-ee.

**Comment by shuyangzhou** [comment]
JAVA_HOME is not a standard thing, although many people/products follow it. On the other hand PATH is an OS thing which is more like a standard. When I say it is not covering everything, I meant there are other usage of PATH without using ProcessConfig. When we invoke jps/jstack/jmap, we just do it directly, assuming they are on the PATH, if they are not, everything will just break.

One thing to keep in mind is, the goal of ProcessExecutor is to allow portal to execute any java process in a similar manner of executing a Runnable. There is not assumption of what the java process is doing, or even where it is running. For Fabric we actually remote the java process to a different machine. And we should not make the assumption that the remote machine has the JAVA_HOME at all.

As a matter of fact, there are known issues of assuming JAVA_HOME is configured. For example, when using ant sshexec to run commond on remote machine, ant automatically wipes out all user configured env variables. Which means there is for sure no JAVA_HOME, but PATH is an OS env variable, which will be preserved. And that will be the only way that we can have a java to invoke.

This is really just a configuration problem on the customer side, just have them fix their PATH, then we can avoid all the troubles and keep things simple.

**Comment by SGM3** [comment]
Should we look into have a warning log in the case of not having JAVA_HOME/bin explicitly on the PATH? 

The user error case seems a likely scenario to me, and feel like that aspect should be addressed.

**Comment by shuyangzhou** [comment]
Sure, we can do that. You can add a check into StartupAction to assert Java can be found in PATH.

**Comment by shuyangzhou** [comment]
Hmm, I think StartupAction is too late. By that time the lpkg indexer has already failed. Put it somewhere in PortalContextLoaderListener or InitUtil.

**Comment by SGM3** [comment]
Minhchau Dang has put further input into the ticket. He proposed we look at the JVM property, `java.home` to reference the java runtime for the local executioner.

If this is not an acceptable approach, he also proposed that the we add logic to our startup script in the example configuration to explicitly check for the existence of the JAVA_HOME environment variable, and prepend JAVA_HOME/bin to PATH upon finding its existence (scripts found in tools/server).

**Comment by holatuwol** [comment]
Adding JAVA_HOME/bin to the PATH:

https://github.com/SGM3/liferay-portal/pull/1

**Pull request closed without merging**
