### PR TITLE
LPS-95829 Reuse context objects in DM web jsps

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
@vicnate5 when this is done testing can you check any functional test failures?

Thank you!

**Comment by vicnate5** [comment]
ci:test:documents

**Comment by vicnate5** [comment]
@koor4356 please review for regressions

**Comment by koor4356** [comment]
These functional tests failure are known test fixes - LRQA-48825

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73481

**Pull request closed without merging**
