### PR TITLE
Lps 138126

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@kyle-miho Please watch this PR and check the results. This fixes a blocker for hot fixes and fix packs so it is urgent (https://issues.liferay.com/browse/LRP-1459)

I will be out the rest of the day.

**Comment by tinatian** [comment]
@kyle-miho Could you please scan the test result?

Tina

**Comment by kyle-miho** [comment]
@tinatian PR is good to go, failures are unrelated

**Comment by shuyangzhou** [comment]
Merged on release repo side, thanks!

**Pull request closed without merging**
