### PR TITLE
Lps 158859

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Regressions here.

#### 1. AutoUpgrade (upgrade on startup) is not completing.
Steps to Reproduce: 
1. Import [mysql dump file](https://github.com/liferay/liferay-qa-portal-legacy-ee/raw/master/7.4.13/data-archive/data-archive-portal-mysql.zip)
1. Enable autoUpgrade `upgrade.database.auto.run=true`
1. Start tomcat to begin upgrade on startup. Wait for full startup.

Result:
`WARN  [main][MainServlet:407] Required upgrades in modules are pending. Run the upgrade process or type upgrade:checkAll in the Gogo shell to get more information.`

gogo shell:
```
g! upgrade:checkAll
There are upgrade processes available for com.liferay.client.extension.service from 2.1.0 to 3.4.0:
        2.1.0 to 2.2.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_2_0.RemoteAppEntryUpgradeProcess
        2.2.0 to 2.3.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_3_0.RemoteAppEntryUpgradeProcess
        2.3.0 to 2.4.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_4_0.RemoteAppEntryUpgradeProcess
        2.4.0 to 2.5.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_5_0.RemoteAppEntryUpgradeProcess
        2.5.0 to 3.0.0.step-1 (REQUIRED): com.liferay.client.extension.internal.upgrade.v3_0_0.ClassNamesUpgradeProcess
        3.0.0.step-1 to 3.0.0: com.liferay.client.extension.internal.upgrade.v3_0_0.ClientExtensionEntryUpgradeProcess
        3.0.0 to 3.1.0.step-1 (REQUIRED): com.liferay.client.extension.internal.upgrade.v3_1_0.util.ClientExtensionEntryRelTable$1
        3.1.0.step-1 to 3.1.0: com.liferay.client.extension.internal.upgrade.v3_1_0.ClientExtensionEntryUpgradeProcess
        3.1.0 to 3.2.0 (REQUIRED): com.liferay.portal.kernel.upgrade.CTModelUpgradeProcess
        3.2.0 to 3.3.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.registry.ClientExtensionUpgradeStepRegistrator$1
        3.3.0 to 3.4.0 (REQUIRED): com.liferay.portal.upgrade.step.util.UpgradeStepFactory$1
```

#### 2. PostgreSQL upgrade failure using upgrade tool
Steps to Reproduce: 
1. Download [postgreSQL dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/raw/master/7.4.13/data-archive/data-archive-portal-postgresql.zip)
1. `docker run -p 5432:5432 --name psql-docker -e POSTGRES_DB=lportal -d postgres:12.1`
1. Unzip the psql dump
1. `docker cp postgresql.sql psql-docker:/`
1. `docker exec -it psql-docker bash`
1. `psql -U postgres -d lportal < postgresql.sql`
1. exit
1. Navigate to tomcat bundle `tools/portal-tools-db-upgrade-client`
1. Set portal-upgrade-database.properties
```
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.password=
jdbc.default.url=jdbc:postgresql://0.0.0.0:5432/lportal
jdbc.default.username=postgres
```
1. `./db_upgrade.sh`
 
 Result:
 ```
Completed Liferay core upgrade process in 64 seconds
Checking to see if all upgrades have completed... your upgrades have failed, have not started, or are still running.
Connecting to Gogo shell...

Type "help" to get available upgrade and verify commands.
Type "help {command}" to get additional information about the command. For example, "help upgrade:list".
Enter "exit" or "quit" to exit.
g! upgrade:check
There are upgrade processes available for com.liferay.client.extension.service from 2.1.0 to 3.4.0
g! upgrade:checkAll
There are upgrade processes available for com.liferay.client.extension.service from 2.1.0 to 3.4.0:
        2.1.0 to 2.2.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_2_0.RemoteAppEntryUpgradeProcess
        2.2.0 to 2.3.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_3_0.RemoteAppEntryUpgradeProcess
        2.3.0 to 2.4.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_4_0.RemoteAppEntryUpgradeProcess
        2.4.0 to 2.5.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.v2_5_0.RemoteAppEntryUpgradeProcess
        2.5.0 to 3.0.0.step-1 (REQUIRED): com.liferay.client.extension.internal.upgrade.v3_0_0.ClassNamesUpgradeProcess
        3.0.0.step-1 to 3.0.0: com.liferay.client.extension.internal.upgrade.v3_0_0.ClientExtensionEntryUpgradeProcess
        3.0.0 to 3.1.0.step-1 (REQUIRED): com.liferay.client.extension.internal.upgrade.v3_1_0.util.ClientExtensionEntryRelTable$1
        3.1.0.step-1 to 3.1.0: com.liferay.client.extension.internal.upgrade.v3_1_0.ClientExtensionEntryUpgradeProcess
        3.1.0 to 3.2.0 (REQUIRED): com.liferay.portal.kernel.upgrade.CTModelUpgradeProcess
        3.2.0 to 3.3.0 (REQUIRED): com.liferay.client.extension.internal.upgrade.registry.ClientExtensionUpgradeStepRegistrator$1
        3.3.0 to 3.4.0 (REQUIRED): com.liferay.portal.upgrade.step.util.UpgradeStepFactory$1
```

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results again, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found in new results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121096

**Pull request closed without merging**
