### PR TITLE
[TECHNICAL SUPPORT] LPS-114288 Change predefined keys of TemplateNode to avoid overriding by child's names

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-114288

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@tinatian please take this over, thanks!

**Comment by tinatian** [comment]
@shuyangzhou OK

**Comment by tinatian** [comment]
Hi @rodrigopaulino,

This change will make the API confusing, the two invocations below should return same value, but now it will return different values.
$field.name (return child template node named "name" now)
$field.getName (return the name of current template node).

Please fix this by removing this line https://github.com/liferay/liferay-portal/blob/d1080610c7faee83cb7876a4e0203a83588e43f1/portal-kernel/src/com/liferay/portal/kernel/templateparser/TemplateNode.java#L77. 

We should not put child template node into the internal map, just like we did not put sibling template nodes into internal map.

Please also add unit/integration test to cover this.

I am going to close this pull, please resend to me.


Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
