### PR TITLE
LPS-92749 "asyncSupported" flag set to true in @ServeResourceMethod should override such flag set at portlet configuration level, according to Portlet Spec 3.0 28.2.14 and annotation JavaDocs

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou 

**UPDATE:** I added a commit that fixes a NPE.

This is a fix for LPS-92749 from @dantewang -- I did not make any changes. The test failures from ngriffin7a#37 seem unrelated to me, especially since this is a very isolated change that would only affect Portlet 3.0 Async functionality.

/cc @tinatian @vicnate5

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@vicnate5 Please invoke whatever CI testing you feel is necessary, given that all I did was put a null check around a block of Dante's code.

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
CI isn't going to help much here, it is why I am working on the portlet 3.0 demo tests.

I applied the first commit to my bundle, solves the issue in the ticket. Unfortunately, the AsyncPortlet test has further issues.

**Comment by ngriffin7a** [comment]
@vicnate5 The important part is that we pass 100% of the Async TCK tests. The selenium tests that you are referring to are for a demo, and the tests were written assuming that Pluto's execution of the portlet is correct. However, that may or may not be the case. Demo test failures will need to be examined closely to see which behavior is correct -- Pluto or Liferay.

**Comment by vicnate5** [comment]
Running the tests here https://github.com/vicnate5/liferay-portal/pull/1147

**Comment by ngriffin7a** [comment]
@vicnate5 Is everything all clear (from a testing perspective) for @shuyangzhou to review this PR? Thanks.

**Comment by vicnate5** [comment]
@shuyangzhou This is ready for review.

TCK tests passed (minus a known flaky tests, passed on retest)
Error on Async Demo and Chat Room Demo resolved. Demo tests fail for unrelated issues.
@ngriffin7a

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70325

**Pull request closed without merging**
