### PR TITLE
LPS-108614 2

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @slnn,

please check to see if this resolves the regression from https://github.com/shuyangzhou/liferay-portal/pull/8856#issuecomment-586167274

Thank you

**Comment by Preston-Crary** [comment]
ci:test

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results:

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Comare to BaseLine1 （%） | Comare to BaseLine2 （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine1 | ae5eeff | 20301 | 324 | 130 | - | - | 713 | 0 | 5978578060K | 2410558K | 0K
BaseLine2 | ae5eeff | 19639 | 335 | 132 | - | - | 694 | 0 | 5819248255K | 2365567K | 0K
PR | - | 20152 | 322 | 129 | -0.7339539924 | 2.612149295 | 706 | 0 | 5919884979K | 2383201K | 0K
PR | - | 19475 | 333 | 130 | -0.8350730689 | -3.359468043 | 685 | 0 | 5743773845K | 2347026K | 0K


MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Comare to BaseLine1 （%） | Comare to BaseLine2 （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine1 | ae5eeff | 8738 | 178 | 279 | - | - | 658 | 1 | 5512187670K | 7393713K | 2406587K
BaseLine2 | ae5eeff | 8592 | 202 | 287 | - | - | 651 | 1 | 5453645476K | 7216020K | 2390203K
PR | - | 8755 | 164 | 267 | 0.1945525292 | 1.897113594 | 663 | 1 | 5554243290K | 7225174K | 2370220K
PR | - | 8613 | 175 | 273 | 0.2444134078 | -1.621930326 | 654 | 1 | 5478822776K | 7170885K | 2457816K

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Comare to BaseLine1 （%） | Comare to BaseLine2 （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine1 | ae5eeff | 9479 | 187 | 409 | - | - | 554 | 1 | 4641141091K | 6039499K | 2189773K
BaseLine2 | ae5eeff | 9161 | 209 | 443 | - | - | 541 | 1 | 4532103489K | 5963139K | 2209779K
PR | - | 9393 | 187 | 417 | -0.9072686992 | 2.532474621 | 547 | 1 | 4582911876K | 5486889K | 2202241K
PR | - | 9286 | 200 | 437 | -2.036079755 | 1.36447986 | 543 | 1 | 4548865218K | 5973227K | 2226592K


Regards
Lily

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/9344

**Pull request closed without merging**
