### PR TITLE
LPS-75244 During the ACTION_PHASE, public render parameter values are set once, then appended again (regression caused by LPS-72742)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince: Please determine whether or not the failures are related to this PR. If the failures are unrelated, please re-open so that Shuyang can review. Thanks.

**Comment by jpince** [comment]
@Ithildir is this an issue at head? doesn't look like BaseChartTag.java has been changed recently
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-taglib/frontend-taglib-chart/src/main/java/com/liferay/frontend/taglib/chart/servlet/taglib/soy/base/BaseChartTag.java:18: error: cannot find symbol
     [exec] import com.liferay.frontend.taglib.chart.internal.NPMResolverProvider;
     [exec]                                                  ^
     [exec]   symbol:   class NPMResolverProvider
     [exec]   location: package com.liferay.frontend.taglib.chart.internal
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-taglib/frontend-taglib-chart/src/main/java/com/liferay/frontend/taglib/chart/servlet/taglib/soy/base/BaseChartTag.java:48: error: cannot find symbol
     [exec] 		NPMResolver npmResolver = NPMResolverProvider.getNPMResolver();
     [exec] 		                          ^
     [exec]   symbol:   variable NPMResolverProvider
     [exec]   location: class BaseChartTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-taglib/frontend-taglib-chart/src/main/java/com/liferay/frontend/taglib/chart/servlet/taglib/soy/base/BaseChartTag.java:88: error: cannot find symbol
     [exec] 		NPMResolver npmResolver = NPMResolverProvider.getNPMResolver();
     [exec] 		                          ^
     [exec]   symbol:   variable NPMResolverProvider
     [exec]   location: class BaseChartTag
```

**Comment by Ithildir** [comment]
Hi @jpince, I got the same error on https://github.com/brianchandotcom/liferay-portal/pull/53286#issuecomment-347365138. I didn't change on the build side today... looking into it.

**Comment by Ithildir** [comment]
@jpince, I pushed https://github.com/liferay/liferay-portal/commit/0176e04bbb40ee5cb44d6cb09c7b9bf732b3d56d to fix the compile error.

**Comment by jpince** [comment]
ci:retest

-- 
Jason Pince
Lead Test Engineer


Liferay Inc. | 1400 Montefino Avenue, Diamond Bar, CA 91765 USA |
877-543-3729 <(877)%20543-3729>
_____________________________________________________________________

*Confidentiality Notice:* This e-mail message, including any attachments,
is for the sole use of the intended recipient(s) and may contain
confidential and privileged information. Any unauthorized review, use,
copying, disclosure or distribution is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy
all copies of the original message.

**Comment by jpince** [comment]
@Ithildir thank you!

@ngriffin7a @shuyangzhou no unique test failures, please review

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53324

**Pull request closed without merging**
