### PR TITLE
LPS-X Move DefaultSearchEngineConfigurator to portal-search module an…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…d OSGify it.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No unique failures, but we should run the search suite

**Comment by vicnate5** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in search suite.

**Comment by shuyangzhou** [comment]
ci:test:upgrade

@vicnate5 let's run upgrade too, just in case.

**Comment by shuyangzhou** [comment]
@vicnate5 can you take a look? That seems a massive amount of failures.

**Comment by vicnate5** [comment]
@shuyangzhou Failure rate for all the upgrade tests was 19%. There are some known issues at head and this test run did not include the fix for upgrading scheduler (so most of the 6.2 upgrade tests had expected issues). None of the failures were related to this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105999

**Pull request closed without merging**
