### PR TITLE
[TECHNICAL SUPPORT] LPS-55106 Too long PortletPreferences XML can cause OutOfMemoryError

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @shuyangzhou 

I fixed the remaining 2 broken test cases. Please review my changes.

Regards,
Vilmos

### CODE REVIEW

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
Hi @shuyangzhou ,

Based on the results of https://github.com/shuyangzhou/liferay-portal/pull/1193 I think, these errors are not related to my modifications.

Is there anything, I can do, to get rid of these failed tests?

Regards,
Vilmos

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Hmm, the threshold should not be used inside BaseMessageDigestCacheKeyGenerator, and it should not be a general threshold for all cache keys.

It will be very confusing if JavaSHA1CacheKeyGenerator sometimes return the same input content as key, sometimes return SHA1 hashed value.

The CacheKeyGenerator should just do its own job, without worry about any limitation. It is PortletPreferencesFactoryImpl in this case needs a special threshold.

Please refactor to make the threshold only for PortletPreferencesFactoryImpl.

**Pull request closed without merging**
