### PR TITLE
Axis removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, this is the last piece of axis removal. thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. All the unique failures here I could not reproduce locally (including [StagingImplTest](https://testray.liferay.com/home/-/testray/case_results/1616581169))

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113775

**Pull request closed without merging**
