### PR TITLE
[TECHNICAL-SUPPORT] LPS-60082

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
This errors might be valid though.

**Comment by shuyangzhou** [comment]
ci:retest sorry for the delay, just needs to make sure it is still working, then I will review it.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/32188

**Pull request closed without merging**
