### PR TITLE
[Sidecar]LPS-106592-LPS-103577 | master

### PR DESCRIPTION
**Pull request by vicnate5**
This pull is based on #8799.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian

**Comment by vicnate5** [comment]
Bundle download: https://files.liferay.com/private/bundles/test-1-9/jobs/test-portal-acceptance-pullrequest(master)/builds/2711/liferay-portal-bundle-tomcat.tar.gz

**Comment by vicnate5** [comment]
@tinatian Based on the previous test results and manual testing on the bundle, this one has a regression on startup.

```
2020-02-05 00:45:32.911 WARN  [main][SidecarElasticsearchConnectionManager:82] Liferay is configured to use Elasticsearch engine running in a child process of current process named as sidecar. Do NOT use sidecar in production. Sidecar is useful for development and demonstration purposes. Refer to the documentation for details on the limitations of sidecar. Remote Elasticsearch connections can be configured in the Control Panel.
2020-02-05 00:45:33.222 INFO  [main][Sidecar:129] Starting sidecar
2020-02-05 00:45:34.409 INFO  [main][Sidecar:627] Sidecar properties : {bootstrap.memory_lock=false,bootstrap.system_call_filter=false,cluster.initial_master_nodes=liferay-d13226a0-f37c-1151-196f-b03a16f2f86c,cluster.name=LiferayElasticsearchCluster,cluster.routing.allocation.disk.threshold_enabled=false,discovery.seed_hosts=172.16.21.22,http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/,http.cors.enabled=true,network.host=172.16.21.22,node.data=true,node.ingest=true,node.master=true,node.name=liferay-d13226a0-f37c-1151-196f-b03a16f2f86c,node.store.allow_mmap=false,path.data=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/data/elasticsearch7/indices,path.logs=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/logs,path.repo=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/data/elasticsearch7/repo}
2020-02-05 00:45:40.801 INFO  [com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarMainProcessCallable@6fe2f6a0[-Xms1g -Xmx1g -XX:+AlwaysPreTouch -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.distribution.flavor=default -Des.distribution.type=tar -Des.path.conf=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/tomcat-9.0.17/temp/20200205244534173AHETBROY/config -Des.path.home=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/elasticsearch7 -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dio.netty.allocator.type=unpooled -Dio.netty.allocator.numDirectArenas=0 -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/tomcat-9.0.17/temp/20200205244534173AHETBROY -Djava.security.policy=jar:file:/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/osgi/state/org.eclipse.osgi/178/0/bundleFile!/META-INF/sidecar/security.policy -Djna.nosys=true]-][Sidecar:201] Started sidecar
...
2020-02-05 00:45:58.990 WARN  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][SidecarElasticsearchConnectionManager:82] Liferay is configured to use Elasticsearch engine running in a child process of current process named as sidecar. Do NOT use sidecar in production. Sidecar is useful for development and demonstration purposes. Refer to the documentation for details on the limitations of sidecar. Remote Elasticsearch connections can be configured in the Control Panel.
2020-02-05 00:45:58.996 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][Sidecar:129] Starting sidecar
2020-02-05 00:45:59.045 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][Sidecar:627] Sidecar properties : {bootstrap.memory_lock=false,bootstrap.system_call_filter=false,cluster.initial_master_nodes=liferay-d13226a0-f37c-1151-196f-b03a16f2f86c,cluster.name=LiferayElasticsearchCluster,cluster.routing.allocation.disk.threshold_enabled=false,discovery.seed_hosts=172.16.21.22,http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/,http.cors.enabled=true,network.host=172.16.21.22,node.data=true,node.ingest=true,node.master=true,node.name=liferay-d13226a0-f37c-1151-196f-b03a16f2f86c,node.store.allow_mmap=false,path.data=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/data/elasticsearch7/indices,path.logs=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/logs,path.repo=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/data/elasticsearch7/repo}
...
2020-02-05 00:46:07.932 ERROR [Finalizer][Sidecar:205] Unable to start elasticsearch server
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.liferay.portal.search.elasticsearch7.internal.sidecar.Sidecar.lambda$start$2(Sidecar.java:198)
	at com.liferay.petra.concurrent.DefaultNoticeableFuture$OnceFutureListener.complete(DefaultNoticeableFuture.java:111)
	at com.liferay.petra.concurrent.DefaultNoticeableFuture.done(DefaultNoticeableFuture.java:85)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.cancel(FutureTask.java:180)
	at com.liferay.petra.concurrent.AsyncBroker$1.finalize(AsyncBroker.java:40)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
2020-02-05 00:46:07.934 INFO  [fileinstall-/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/osgi/war][BaseAutoDeployListener:43] Copying themes for /Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/tomcat-9.0.17/temp/20200205244607541XZUBXSIO/admin-theme.war
2020-02-05 00:46:07.991 INFO  [fileinstall-/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/osgi/war][BaseDeployer:871] Deploying admin-theme.war
2020-02-05 00:46:08.130 INFO  [main][UpgradeProcess:93] Upgrading com.liferay.knowledge.base.web.internal.upgrade.v1_1_0.UpgradePortletPreferences
2020-02-05 00:46:08.131 INFO  [main][LoggingTimer:83] Starting com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences
2020-02-05 00:46:08.133 INFO  [main][LoggingTimer:43] Completed com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences in 2 ms
2020-02-05 00:46:08.134 INFO  [main][UpgradeProcess:107] Completed upgrade process com.liferay.knowledge.base.web.internal.upgrade.v1_1_0.UpgradePortletPreferences in 4 ms
2020-02-05 00:46:08.150 INFO  [main][UpgradeProcess:93] Upgrading com.liferay.knowledge.base.web.internal.upgrade.v1_2_0.UpgradePortletPreferences
2020-02-05 00:46:08.151 INFO  [main][LoggingTimer:83] Starting com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences
2020-02-05 00:46:08.153 INFO  [main][LoggingTimer:43] Completed com.liferay.portal.kernel.upgrade.BaseUpgradePortletPreferences#updatePortletPreferences in 2 ms
2020-02-05 00:46:08.154 INFO  [main][UpgradeProcess:107] Completed upgrade process com.liferay.knowledge.base.web.internal.upgrade.v1_2_0.UpgradePortletPreferences in 4 ms
2020-02-05 00:46:08.199 INFO  [main][UpgradeProcess:93] Upgrading com.liferay.portal.reports.engine.console.internal.upgrade.ReportsServiceUpgrade$1
2020-02-05 00:46:08.202 INFO  [main][UpgradeProcess:107] Completed upgrade process com.liferay.portal.reports.engine.console.internal.upgrade.ReportsServiceUpgrade$1 in 3 ms
Exception in thread "com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarMainProcessCallable@772ebf92[-Xms1g -Xmx1g -XX:+AlwaysPreTouch -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.distribution.flavor=default -Des.distribution.type=tar -Des.path.conf=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/tomcat-9.0.17/temp/20200205244559034EOBWZMPZ/config -Des.path.home=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/elasticsearch7 -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dio.netty.allocator.type=unpooled -Dio.netty.allocator.numDirectArenas=0 -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/tomcat-9.0.17/temp/20200205244559034EOBWZMPZ -Djava.security.policy=jar:file:/Users/vicnate5/bundles/ee_release/temp-cluster-2/bundles/osgi/state/org.eclipse.osgi/178/0/bundleFile!/META-INF/sidecar/security.policy -Djna.nosys=true]-" java.lang.RuntimeException: Sidecar process is not started
	at com.liferay.portal.search.elasticsearch7.internal.connection.SidecarElasticsearchConnectionManager$RestartFutureListener.complete(SidecarElasticsearchConnectionManager.java:171)
	at com.liferay.petra.concurrent.DefaultNoticeableFuture$OnceFutureListener.complete(DefaultNoticeableFuture.java:111)
	at com.liferay.petra.concurrent.DefaultNoticeableFuture.done(DefaultNoticeableFuture.java:85)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.set(FutureTask.java:233)
	at com.liferay.petra.concurrent.DefaultNoticeableFuture.set(DefaultNoticeableFuture.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/8805

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
