### PR TITLE
Commons file upload removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Seems to be the major issue here is on uploading files over a small size limit. Seeing this across different components.

Cannot upload larger files (mp4 or high resolution image)
1. Go to Documents & Media > Add > File Upload > Select File
2. Upload [this mp4 file](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/Document_1.mp4) or [high res image](url)

"Error: Please enter content with valid content size no larger than 256 KB." 
The UI states "Upload documents no larger than 100 MB." and `data.limit.dl.storage.max.size=0`

I could not upload this file as an attachment to message board either. 

I also think this is preventing Import of site LAR files (Publishing > Import)
1. Go to Product Menu > Publishing > Export
2. Export a site
3. Download LAR file
4. Create a new site
5. Go to New Site > Publishing > Import
6. Attempt to upload the LAR file (my LAR file on a blank site is 490kb)

**Pull request closed without merging**
