### PR TITLE
TCK3 LPS-76630

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou 
This pull tries to fix the following 4 test cases in Portlet 3.0 TCK:

V2RequestTests_PortletRequest_ApiAction_getAuthType1
V2RequestTests_PortletRequest_ApiEvent_getAuthType1
V2RequestTests_PortletRequest_ApiRender_getAuthType1
V2RequestTests_PortletRequest_ApiResource_getAuthType1

However, it will fail 3 test cases in old TCK, all with the name GetAuthTypeWithoutProtectionTest.

For PortletRequest.getAuthType(), the 3.0 TCK expects the return value to be not null, while the old TCK expects null.

As discussed in the email thread, the method should not return null when user has logged in. And Neil suggests to either ignore the ones in old TCK, or make the related old TCK test cases being executed without logging in.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2018年2月13日周二
19:03写道：

**Comment by shuyangzhou** [comment]
@dantewang see https://github.com/liferay/liferay-portal/blob/master/build-test-tck.xml#L117, modify that to get their wars excluded. Hopefully there are not too many other tests in those war. Please resend this pull with that, and tell me is there any other tests in those wars.

**Comment by dantewang** [comment]
@shuyangzhou The failing test cases are in 3 war files together with about 56 other test cases. Ignoring the war files will cause all the test cases in these wars to fail, see https://github.com/dantewang/liferay-portal/pull/588#issuecomment-365497848

**Comment by shuyangzhou** [comment]
@dantewang then we have to figure some way to ignore those specify failures from junit result level, we can not let CI stay in broken state.

**Comment by dantewang** [comment]
@shuyangzhou It seems individual test cases can be disabled from the TCK by modifying tck/bin/ts.jtx. Will try modifying the file from ant.

**Pull request closed without merging**
