### PR TITLE
LPS-120586 Prevent publishing with missing parents

### PR DESCRIPTION
**Pull request by Preston-Crary**
@suilin @xbrianlee this pull includes fixes all the "missing requirement conflict" issues from https://github.com/shuyangzhou/liferay-portal/pull/9460#issuecomment-698279819, thanks for catching these ones so quickly.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:change-list

**Comment by suilin** [comment]
Please ignore ci:test:change-list results, it failed due to Jenkins flaky issue.

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@Preston-Crary please rebase and resend, it is conflicting with my servicetracker opening changes.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9467

**Pull request closed without merging**
