### PR TITLE
Startup optimization 258 aop service resolver

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Just regression in aop test [com.liferay.portal.aop.test.AopServiceManagerTest](https://testray.liferay.com/reports/production/logs/2023-06/test-1-38/test-portal-acceptance-pullrequest(master)/7888/modules-integration-mysql57-jdk8/3/13/com.liferay.portal.aop.test.AopServiceManagerTest.txt.gz?authuser=0)

Reproduced locally.
Testray https://testray.liferay.com/home/-/testray/case_results/2345502365

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Pull request closed without merging**
