### PR TITLE
LPS-77387

### PR DESCRIPTION
**Pull request by jcampoy**
Hi @shuyangzhou ,

[LPS-77387](https://issues.liferay.com/browse/LPS-77387) is caused by an [issue](https://issues.liferay.com/browse/LPS-74948) that only affects to WebSphere, so, I am limiting the original fix to this server.

Best regards,
Jose

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@dantewang please take this over.

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Hi @dantewang, @shuyangzhou ,
we need to move forward with a solution for this issue because is affecting a lot of users in 6.2 and 7, and we need to include it in a fix-pack as soon as possible.
Could you take a look and resend it if you are right with the fix?
Thanks!!

**Comment by dantewang** [comment]
@jcampoy @shuyangzhou 

Sorry for the delay.

I was busy last few days and was just able to get my Websphere + Liferay env running again, so it may still need some time for the fix on Websphere or for a complete fix that applies to all app servers.

Maybe we can merge this one as a temp workaround for now for users who don't use Websphere.

**Comment by jcampoy** [comment]
thank you for the response @dantewang !

we have already sent it as workaround for users reporting it, however other users are upgrading their portal and finding this regression and we need a final solution to include it in a official update/fixpack, so, we will wait for you review :) thanks!

**Comment by dantewang** [comment]
@jcampoy See https://github.com/shuyangzhou/liferay-portal/pull/5655

**Comment by jcampoy** [comment]
Thanks @dantewang !!! we are going to test this code in previous branches as well, including tomcat and webshere servers 

Cheers!!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54972

**Pull request closed without merging**
