### PR TITLE
[Bug Fix]LPS-135889

### PR DESCRIPTION
**Pull request by tinatian**
FYI @@pavel-savinov

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @JavierMoral,

Could you please take a look at it? They are trying to fix the same issue that you fixed here https://github.com/liferay-echo/liferay-portal/pull/5238.

Regards,
Eudaldo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 Can you scan this? Lots of failures to start portal here.

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
I could reproduce the startup failure locally.

Results:

1. It took more than 30 minutes for server to startup. 
```
21-Jul-2021 04:19:18.831 信息 [main] org.apache.catalina.startup.Catalina.load 服务器在[2500]毫秒内初始化                                  
21-Jul-2021 04:51:58.411 信息 [main] org.apache.catalina.startup.Catalina.start [1959574]毫秒后服务器启动
```
2. A lot of Declarative Service Unsatisfied warnings in portal log. 
3. Many error messages of com.liferay.portal.kernel.events.ActionException: java.lang.NullPointerException.
4. Portal is not accessible.

I attached the full portal log: 
[liferay.2021-07-21.log](https://github.com/shuyangzhou/liferay-portal/files/6852966/liferay.2021-07-21.log)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Pull request closed without merging**
