### PR TITLE
Lps 93752

### PR DESCRIPTION
**Pull request by pcalvoLr**
Hey @shuyangzhou , can you check this pr?

Thanks!

Regards

### CODE REVIEW

**Comment by pcalvoLr** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by pcalvoLr** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by pcalvoLr** [comment]
Hi @shuyangzhou 

 Could you please review this pr?

Regards

**Comment by vicnate5** [comment]
@shuyangzhou functional test failures not related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72523

**Pull request closed without merging**
