### PR TITLE
LPS-86616 WIP Potentially inaccurate validator

### PR DESCRIPTION
**Pull request by stsquared99**
Hi Shuyang, I am sending this preliminary PR for your consideration, to confirm if this should be opened as a separate bug ticket.
The gist of it is that a domain is not an IP address, and our validators should reflect that. This is according to the RFCs already referenced in the validator. Could you please confirm if this is a bug and see if this makes sense? If so, I will file and send the proper fix for it.

The current ticket (likely won't fix) simply revealed this potential bug, just using as a placeholder now, I will open a proper one once we confirm.
Thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please look into this.
I remember we did something with security team before involving domain/ip/url validation.
I think we should set a goal for the expected behavior first, before we jump into some inconsistent solutions.

**Comment by tinatian** [comment]
Hi @stsquared99 @shuyangzhou ,
I think in our system, "domain" means "host"  which will be a real domain name, ipv4 address or ipv6 address.

I will try to do some refactoring and make the API more clear so that we won't have this kind of misunderstanding. Will put this into my task list.

I am wondering if you have any deadline about the bug ticket you are working on. If yes, is it possible that you go without my refactoring? Since it may take a while for me to work on this.

Thanks.
Tina.

**Comment by stsquared99** [comment]
@tinatian Thanks for getting back! So based on our system, should we allow ipv6 addresses here?

screen shot 2018-10-23 at 12 42 57 pm

I can make any needed change before you refactor, it shouldn't be a problem.
Thanks!

**Comment by stsquared99** [comment]
@tinatian @shuyangzhou 
I tested the change allowing IPv6 addresses as virtual hosts. However, when I navigate to the virtual instance, it is not detected. It still shows the default Liferay instance. I tried this with several IPs. Are we sure that this is actually supported? I don't want to fix our bug only to reveal a bug on your end. Can you please advise?
Thanks!

**Comment by tinatian** [comment]
Hi @stsquared99 
First, I do not know what you changed and how you tested it, so I can not give you detailed advises on what you should do.

It is possible that we did not support IPV6 as virtual host ip correctly, if we do have a bug on this part, I think it should be part of your fix to current bug. Or you create another bug ticket if you want, and fix that first then your current bug.

This is not "fix our bug only to reveal a bug", as long as it is a real bug, we are improving our product.

Tina.

**Comment by stsquared99** [comment]
@tinatian
Sounds good, that makes sense to me. Thanks

**Pull request closed without merging**
