### PR TITLE
LPS-121352 AopServiceManager should use the default transaction handler to avoid reactivation during shutdown

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
Test results look clear to me. @vicnate5 please confirm that?

**Comment by vicnate5** [comment]
@Preston-Crary There is one unique failure but it is likely a flaky issue. The UI form builder did not render in one of the tests but the other Forms tests passed.

**Comment by vicnate5** [comment]
I am triggering a full test run on this since it is a low level change. Is this urgent?

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou @Preston-Crary Looks good. No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
