### PR TITLE
LPS-85997

### PR DESCRIPTION
**Pull request by topolik**
Hi Shuyang,

I upgraded tomcat directly to the fresh new 9.0.17, now JSPs compile.

Tests run here: https://github.com/topolik/liferay-portal/pull/727

/cc @david-truong @xbrianlee

Thanks.

### CODE REVIEW

**Comment by xbrianlee** [comment]
FYI @vicnate5

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Scanned this pull, no functional test regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70936

**Pull request closed without merging**
