### PR TITLE
COMMERCE-2475 Dispatch framework - Talend

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek 
1) What is this https://github.com/shuyangzhou/liferay-portal/blob/d01e296ea4ba3a66ae2bd78446df7d0a6985e95e/modules/apps/dispatch/dispatch-web/src/main/java/com/liferay/dispatch/web/internal/Izbrisime.java ?
2) Why you need to turn this off https://github.com/shuyangzhou/liferay-portal/pull/9448/files#diff-dad88a84ad6cecb2a7d3d1967145b22eR2 ?
3) For https://github.com/shuyangzhou/liferay-portal/pull/9448/files#diff-9b2d72a78d1a6c78f8c8df1971c1d973R95, please switch to use https://github.com/liferay/liferay-portal/blob/master/modules/core/petra/petra-process/src/main/java/com/liferay/petra/process/ProcessUtil.java, there are example usages in codebase for you to follow.

Please solve the above issues and resend.

**Comment by matijapetanjek** [comment]
@shuyangzhou Well, point 1 is a real source of shame, my test class got committed.
 I've resent the PR!

**Pull request closed without merging**
