### PR TITLE
LPS-107933 Don't deploy jar file in case it isn't a valid module.

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-107933

Code changes:
- **First commit:** https://github.com/shuyangzhou/liferay-portal/commit/9c3743d0327df6e28d331fa4d690909a64942f3d - I have implemented the solution suggested here https://github.com/shuyangzhou/liferay-portal/pull/8788#issuecomment-580938801
- **Second and third commit:** https://github.com/shuyangzhou/liferay-portal/commit/8d96b71a6fd6cf7b8aa401a69c9ea65dc3a4478f and https://github.com/shuyangzhou/liferay-portal/commit/b15883e11b9958b0e962109a39dd3360694e1931 - There are some people that deploys files directly to `osgi/modules`, I am adding a ERROR trace and avoiding some NPE just in case someone does that.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jorgediaz-lr I removed those commits for NPEs. Those NPEs need to happen. We are using the symbolic name and version as unique key for bundles. By doing the NPE prevention, it will be possible to have duplicated keys, which will break the logic in some really weird way.

With the AutoDeployer and BundleStartStopLogger changes, customers should already have enough clues for what went wrong and fix their user mistakes.

And we will completely prevent the "bad" bundle from being installed in the new installer, so later version won't have those NPEs anymore.

See https://github.com/brianchandotcom/liferay-portal/pull/84095

CC @mtambara

**Pull request closed without merging**
