### PR TITLE
Lps 155940

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, you can ignore the SF issue, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou One unique failure in [com.liferay.portal.library.LibraryReferenceTest](https://testray.liferay.com/home/-/testray/case_results/1877086288). Probably not worth re-running all the tests after fixing this. If you want to re-run automation, only run relevant as it will run this test.
```
Testcase: testLibDependencyJarsInVersionsExt(com.liferay.portal.library.LibraryReferenceTest):	FAILED
Wrong version for lib/portal/jaxb-runtime.jar in lib/versions-ext.xml expected:<2.3.1[.LIFERAY-PATCHED-1]> but was:<2.3.1[]>
junit.framework.AssertionFailedError: Wrong version for lib/portal/jaxb-runtime.jar in lib/versions-ext.xml expected:<2.3.1[.LIFERAY-PATCHED-1]> but was:<2.3.1[]>
	at com.liferay.portal.library.LibraryReferenceTest.testLibDependencyJarsInVersionsExt(LibraryReferenceTest.java:158)
```

**Comment by shuyangzhou** [comment]
Thanks, updated the version to fix the unit test.

See https://github.com/brianchandotcom/liferay-portal/pull/118838

**Pull request closed without merging**
