### PR TITLE
LPS-119805 Search in database instead of index as the latter may unnecessary filter the results based on permission

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @shuyangzhou 

Could you please review this pull request?

See: https://github.com/shuyangzhou/liferay-portal/pull/9500#issuecomment-708537675

Thank you and best regards,
István

### CODE REVIEW

**Comment by drewbrokke** [comment]
@IstvanD thank you for this! Would it be possible to also include the test cases?

**Comment by IstvanD** [comment]
@drewbrokke sure. I added the test cases.

**Comment by drewbrokke** [comment]
@IstvanD Thank you!

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9512

**Pull request closed without merging**
