### PR TITLE
LPS-84138 Cache Reload

### PR DESCRIPTION
**Pull request by tinatian**
@tomwang2011, could you please run startup time test with this pull?

@slnn @dantewang Could you please verify the performance of our test cases with this pull?

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by slnn** [comment]
Hi @tinatian,

Here are test results, no noticeable performance regression appeared

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 6d30aff | 48139 | 284 | 87.1
PR-6662 | - | 48199 | 278 | 84.9

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 6d30aff | 62607 | 550 | 190
PR-6662 | - | 63250 | 548 | 189

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 6d30aff | 26164 | 295 | 380
PR-6662 | - | 25836 | 308 | 383

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 6d30aff | 13224 | 209 | 291
PR-6662 | - | 13144 | 146 | 243

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 6d30aff | 15861 | 21.1 | 60.4
PR-6662 | - | 15635 | 30.2 | 67.9

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 6d30aff | 24521 | 492 | 215
PR-6662 | - | 24514 | 487 | 214

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 6d30aff | 15580 | 409 | 600
PR-6662 | - | 15413 | 446 | 641

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/d4829d32dd...34ff8259e2

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/d4829d32dd...34ff8259e2

**Pull request closed without merging**
