### PR TITLE
[Log4j]LPS-126477

### PR DESCRIPTION
**Pull request by tinatian**
FYI @michaelhashimoto

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@michaelhashimoto Could you please scan the test result? Are those unique failures related?

Thanks.
Tina

**Comment by michaelhashimoto** [comment]
@tinatian @shuyangzhou - I reviewed the results and found that we are still able to identify liferay errors.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
