### PR TITLE
LPS-100999 DL and CTDocumentServlet

### PR DESCRIPTION
**Pull request by Preston-Crary**
Some of the challenge with this was checking permissions from the download Servlet and preventing introducing a vulnerable way to download any Blob field in the system.  This is why I'm using ctEntryId instead of classNameId, classPK.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
