### PR TITLE
Registery api integration test

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 Please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by kyle-miho** [comment]
@vicnate5 i got it

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:backend
Running

**Comment by kyle-miho** [comment]
@shuyangzhou this PR should be good, all of the failures seem to be most likely unrelated (already upstream or a random failure)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105703

**Pull request closed without merging**
