### PR TITLE
Lps 124571

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Custom test for this issue running at https://github.com/vicnate5/liferay-portal/pull/1687

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Looks like real test failures here

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
