### PR TITLE
Lps 185647 redo

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
ci:test:object

**Comment by vicnate5** [comment]
@shuyangzhou 
Executed Manual Testing following the steps in https://liferay.atlassian.net/browse/LPS-185647

Not Reproducible on this PR using bundle downloaded from https://github.com/shuyangzhou/liferay-portal/pull/11121#issuecomment-1624371067

Reproduced on master at `5363ba79d6f5607b99bc803ceb6c7b50ff779058`

@timpak Could Objects team automate this scenario?

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Pull request closed without merging**
