### PR TITLE
LPS-68951 Decoupling countByC_FN_MN_LN_SN_EA_S from doFindByC_FN_MN_LN_SN_EA_S

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Shuyang,

Per your request, this is the first part of https://issues.liferay.com/browse/LPS-68951, which removes dependency on  doFindByC_FN_MN_LN_SN_EA_S from countByC_FN_MN_LN_SN_EA_S. Will send the actual fix in the next pull. Thanks!

/cc @jorgediaz-lr

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
Hi @pei-jung 

You have missed this commit: https://github.com/shuyangzhou/liferay-portal/pull/3480/commits/eab18baf648c1af33950415b1d643921205094c9

Without that, the `SELECT COUNT(userId) AS COUNT_VALUE FROM ( ..... )` doesn't work for Sybase.

This approach is similar to `UserFinderImpl.countByGroups` added in LPS-57748: https://github.com/brianchandotcom/liferay-portal/pull/30280

**Comment by pei-jung** [comment]
Hi @jorgediaz-lr 

I intentionally left that commit out. Shuyang asked to have the db related changes to be sent in a separate pr so it's easier for him to review. I'll send the fix after this pr is merged. Thanks!

@shuyangzhou did you get a chance to take a look at this? Let me know if you have any questions. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45466
Much cleaner :)

**Pull request closed without merging**
