### PR TITLE
Lps 79534 MBMessageLocalServiceTest fix

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57108

**Comment by tomwang2011** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57108

**Pull request closed without merging**
