### PR TITLE
[TS] LPS-139889

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @shuyangzhou ,

This PR is to fix two issues: [LPS-139889](https://issues.liferay.com/browse/LPS-139889) and [LPS-141083](https://issues.liferay.com/browse/LPS-141083)

To summarize the issues:
- LPS-139889: 
  - Copying multiple fragment jars to the deploy folder, results in `frameworkWiring.refreshBundles(hostBundles)` being called multiple times ([PortalFragmentBundleWatcher.java#L134](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/portal/portal-fragment-bundle-watcher/src/main/java/com/liferay/portal/fragment/bundle/watcher/internal/PortalFragmentBundleWatcher.java#L134))
- LPS-141083: 
  - If multiple fragments for the same Fragment Host are deployed, and one of the fragments has a missing dependency, this results in the Fragment Host getting refreshed continuously
  - This is due to the fragment with the missing dependency, since it will always remain in the INSTALLED state ([PortalFragmentBundleWatcher.java#L116](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/portal/portal-fragment-bundle-watcher/src/main/java/com/liferay/portal/fragment/bundle/watcher/internal/PortalFragmentBundleWatcher.java#L116))

To summarize the proposed fix:
- Use a scheduled job to handle the refresh, to only allow one refresh to occur at a time
  - This reduces the number of calls to `frameworkWiring.refreshBundles(hostBundles)`
  - **Note:** The 3 seconds for the scheduled job is arbitrary
- Only consider refreshing the Fragment Host if the Fragment being evaluated is not missing requirements
  - This should resolve the continuous refresh issue, caused by the fragment with missing dependencies
  - I think this also avoids attempting to refresh the Fragment Host, if it's not resolved?
  - **Note:** The use of **_frameworkWiring.findProviders** was something I randomly encountered when trying to find a way to verify if a module is missing dependencies. Hopefully this does what I think it does; from my testing it is working as expected.

Please let me know if you have any questions.
Thanks!

/cc @nikolettabuza

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
**Update**
Added an additional commit to set `_refreshingBundles = false` on activate.

This helps avoid a possible edge case, where **_refreshingBundles** has a value of **true** before the scheduled job has a chance to execute a refresh.

**Comment by ericyanLr** [comment]
@shuyangzhou gotcha, I'll work on adding the integration tests to the PR.

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

As requested, I have added tests to help highlight some issues of the current Portal Fragment Bundle Watcher.

The two main tests that help illustrate the issues mentioned on this ticket would be:
- testDeployMultipleFragmentsWithDependencies2
  - Demonstrates the refresh loop
- testDeployMultipleFragmentsAndUnrelatedBundlesSimultaneously
  - Demonstrates unnecessary refreshes when deploying a mix of bundles
    - This can lead to a large number of module refreshes, if the Fragment Host is a dependency for many other bundles (e.g. asset-taglib)

**Note:** The tests are very expensive and can be better optimized, but they should serve to reproduce the mentioned issues.

Please let us know if you have any questions.
Thanks!

**Comment by shuyangzhou** [comment]
@ericyanLr cleanly on your pull, ant all and then run the test, it fails with:
```
com.liferay.portal.fragment.bundle.watcher.test.PortalFragmentBundleWatcherTest > testDeployFragmentWithDependency FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.failNotEquals(Assert.java:835)
    	at org.junit.Assert.assertEquals(Assert.java:647)
    	at org.junit.Assert.assertEquals(Assert.java:633)
    	at com.liferay.portal.fragment.bundle.watcher.test.PortalFragmentBundleWatcherTest.testDeployFragmentWithDependency(PortalFragmentBundleWatcherTest.java:224)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:748)
```
Also the test should not write files to PropsValues.MODULE_FRAMEWORK_MODULES_DIR and there should not be CountDownLatch waiting for bundle installed and uninstalled. You are in the test, which has BundleContext, it should just call BundleContext.installBundle() and Bundle.uninstall(). Those methods are blocked until the bundle's state is fully transited.
Please adjust and resend.

**Pull request closed without merging**
