### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by timpak** [comment]
Nevermind, it looks like your PR wasn't affected by it. I'll look at the failures once it's done.

**Comment by ngriffin7a** [comment]
@timpak I looked at the "writeReleases" failure again, and I can't see how its related the key line is

```[exec] Adding release information from /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar into /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-sample-sql-builder/classes/com/liferay/portal/tools/sample/sql/builder/dependencies/releases.txt```

And the javax.inject dependency is not something that I introduced with this PR. Is this failure unique to this PR?

**Comment by ngriffin7a** [comment]
@shuyangzhou It might be the case that the "writeReleases" failure is caused by a transitive dependency? For example:
```
[INFO] \- javax.portlet:portlet-api:jar:3.0.0:compile
[INFO]    \- javax.enterprise:cdi-api:jar:1.2:compile
[INFO]       +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO]       +- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO]       \- javax.inject:javax.inject:jar:1:compile```

Is there a way we can specify an OSGi-friendly version of the jar?

/cc @timpak

**Comment by ngriffin7a** [comment]
@shuyangzhou: Is there a way we can specify an OSGi-friendly version of the jar?

/cc @timpak

**Comment by ngriffin7a** [comment]
@timpak: I fixed the sample-servicebuilder-portlet edit_foo.jsp problem in a PR to bchan: brianchandotcom/liferay-plugins#5420 and he merged it right away.

Regardless, the test failed again in this PR which makes me think that Brian's merge was not fetched by CI?

If it was using my fix, the JSP code would have a cast to `(PortletURL)` like this:
```_jspx_th_aui_005fform_005f0.setAction( (PortletURL) renderResponse.createActionURL() );```

**Comment by timpak** [comment]
@ngriffin7a maybe the git-commit wasn't updated so it's still pointing to an older commit?

I looked the results. The SF error is caused by a different commit so we can ignore that. I can't figure out why the semantic versioning test batch is being aborted, though. Unfortunately, I'm not very familiar with it :(

**Comment by ngriffin7a** [comment]
@timpak Brian updated git-commit-plugins for me.

@shuyangzhou Andrea showed me how to disable the transitive dependencies for portlet-api-3.0.0.jar

See: https://github.com/shuyangzhou/liferay-portal/pull/6085

**Pull request closed without merging**
