### PR TITLE
LPS-135504 portal-lang

### PR DESCRIPTION
**Pull request by Preston-Crary**
@jhinkey see c5cddc81355afa1444640a01847a112d1c68d118...ad2d54beeec01ddfb620312e53f65c73e84775e8 for how to customize portal language keys. Service ranking bnd property allows multiple customizations for the same key - highest ranking wins. Once all the other portal modules move their properties into portal-lang this will mean customers automatically customize those modules using this customization.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by jhinkey** [comment]
@Preston-Crary - I want to make sure I understand how it works. If I want to override one language key in a translation, for example, can I specify just that one language key in a Language properties file for that translation and set a higher service ranking in my modules's bnd.bnd?

**Comment by Preston-Crary** [comment]
> If I want to override one language key in a translation, for example, can I specify just that one language key in a Language properties file for that translation and set a higher service ranking in my modules's bnd.bnd?

That's exactly how it works.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10173

**Pull request closed without merging**
