### PR TITLE
[ResourceAction]LPS-112056 part 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dantewang Could you please check what happened?

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian I guess the `NoSuchResourceActionException` of `com_liferay_account_admin_web_internal_portlet_AccountEntriesAdminPortlet#ACCESS_IN_CONTROL_PANEL` is caused by https://github.com/shuyangzhou/liferay-portal/pull/9184/commits/26c3df591745d5d80f261b19efdb5ab2440a1c4e

There are chances that the bag is created before portlet model is created, even if it's created on demand instead of reading from file. Then `ACCESS_IN_CONTROL_PANEL` will be missing from the bag.

I'll verify it later.

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
