### PR TITLE
Thread context class loader util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou 

Unit test compile issues

com.liferay.portal.bootstrap.FrameworkRestartTest
```
> Task :core:portal-bootstrap-test:compileTestJava
/opt/dev/projects/github/liferay-portal/modules/core/portal-bootstrap-test/src/test/java/com/liferay/portal/bootstrap/FrameworkRestartTest.java:9: error: package com.liferay.petra.lang does not exist
import com.liferay.petra.lang.SafeCloseable;
                             ^
/opt/dev/projects/github/liferay-portal/modules/core/portal-bootstrap-test/src/test/java/com/liferay/portal/bootstrap/FrameworkRestartTest.java:10: error: package com.liferay.petra.lang does not exist
import com.liferay.petra.lang.ThreadContextClassLoaderUtil;
                             ^
/opt/dev/projects/github/liferay-portal/modules/core/portal-bootstrap-test/src/test/java/com/liferay/portal/bootstrap/FrameworkRestartTest.java:200: error: cannot find symbol
                try (SafeCloseable safeCloseable = ThreadContextClassLoaderUtil.swap(
                     ^
  symbol:   class SafeCloseable
  location: class com.liferay.portal.bootstrap.FrameworkRestartTest
/opt/dev/projects/github/liferay-portal/modules/core/portal-bootstrap-test/src/test/java/com/liferay/portal/bootstrap/FrameworkRestartTest.java:200: error: cannot find symbol
                try (SafeCloseable safeCloseable = ThreadContextClassLoaderUtil.swap(
                                                   ^
  symbol:   variable ThreadContextClassLoaderUtil
  location: class com.liferay.portal.bootstrap.FrameworkRestartTest
```

`gw :apps:static:portal-k8s-agent:portal-k8s-agent-test`
```
> Task :apps:static:portal-k8s-agent:portal-k8s-agent-test:compileTestIntegrationJava FAILED
/opt/dev/projects/github/liferay-portal/modules/apps/static/portal-k8s-agent/portal-k8s-agent-test/src/testIntegration/java/com/liferay/portal/k8s/agent/internal/test/AgentPortalK8sConfigMapModifierTest.java:112: error: cannot find symbol
                                        try (SafeCloseable safeCloseable =
                                             ^
  symbol: class SafeCloseable
/opt/dev/projects/github/liferay-portal/modules/apps/static/portal-k8s-agent/portal-k8s-agent-test/src/testIntegration/java/com/liferay/portal/k8s/agent/internal/test/AgentPortalK8sConfigMapModifierTest.java:113: error: cannot find symbol
                                                        ThreadContextClassLoaderUtil.swap(
                                                        ^
  symbol: variable ThreadContextClassLoaderUtil
2 errors
```

Central Requirements failure
```
    [junit] Running com.liferay.portal.modules.ModulesStructureTest
    [junit] Testsuite: com.liferay.portal.modules.ModulesStructureTest
    [junit] Loading file:/opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit/system-ext.properties
    [junit] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.662 sec
    [junit] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.662 sec
    [junit] 
    [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Redundant dependency detected in modules/dxp/apps/saml/saml-opensaml-integration/build.gradle expected:<compileOnly project(":core:petra:petra-lang")> but was:<testImplementation project(":core:petra:petra-lang")>
    [junit] junit.framework.AssertionFailedError: Redundant dependency detected in modules/dxp/apps/saml/saml-opensaml-integration/build.gradle expected:<compileOnly project(":core:petra:petra-lang")> but was:<testImplementation project(":core:petra:petra-lang")>
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1509)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:59)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:396)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:370)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:368)
 ```

Semver issue
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/core/petra/petra-lang] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.petra.lang                             MINOR      1.3.0      1.3.0      1.4.0      VERSION INCREASE REQUIRED
     [exec]     	+   class      com.liferay.petra.lang.ThreadContextClassLoaderUtil
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     swap(java.lang.ClassLoader)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.petra.lang.SafeCloseable
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.2.0
 ```

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Unit test failing
```
[beanshell]      [exec] com.liferay.petra.process.local.LocalProcessExecutorTest > classMethod FAILED
[beanshell]      [exec]     java.lang.AssertionError: com.liferay.petra.process.local.LocalProcessLauncher is not fully covered
[beanshell]      [exec]         at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
[beanshell]      [exec]         at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:66)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:110)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:75)
[beanshell]      [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[beanshell]      [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[beanshell]      [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
[beanshell]      [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
[beanshell]      [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
[beanshell]      [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
[beanshell]      [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
https://testray.liferay.com/reports/production/logs/2023-11/test-1-37/test-portal-acceptance-pullrequest(master)/15585/modules-unit-jdk8/0/8/jenkins-console.txt.gz?authuser=0

Probably not worth re-running all tests after fixing a unit test.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144528

**Pull request closed without merging**
