### PR TITLE
[License Bug Fix]LPS-121470

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This should fix all these race condition issues:
https://issues.liferay.com/browse/LPS-121470
https://issues.liferay.com/browse/LPS-121428
https://issues.liferay.com/browse/LPS-121255

FYI @vicnate5 @mtambara

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Could you please verify the unique failure here?

Thanks
Tina.

**Comment by vicnate5** [comment]
@tinatian The only unique failure here is due a known race condition at head: https://issues.liferay.com/browse/LPS-121715

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou Failure is also at head. Recommend manual forward.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/94894

**Pull request closed without merging**
