### PR TITLE
Lps 74610 simple socks proxy

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by brianwulbern** [comment]
@shuyangzhou can you guys get to this one soon?  We [turned off a grip of functional tests](https://issues.liferay.com/browse/LRQA-33966) that depend on this socks proxy, and are hoping we can turn them back on again.  Thanks!

cc @michaelhashimoto @tomwang2011

**Comment by tomwang2011** [comment]
@brianwulbern can you send me a pull with the functional tests affected turned back on so we can test them against the simple proxy to make sure everything works? Thanks!

**Comment by brianwulbern** [comment]
@tomwang2011 yeah, I'll send you one soon.

**Comment by brianwulbern** [comment]
@tomwang2011 see the pull here: https://github.com/tomwang2011/liferay-portal/pull/427

**Pull request closed without merging**
