### PR TITLE
Startup optimization 334 lazy session factory

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou So most (not all) of the clustering tests failed to finish booting portal here, there is similar occurrences upstream, but it isn't as common. I unfortunately could not reproduce locally yet after a few attempts.

Examples from this PR:
https://testray.liferay.com/home/-/testray/case_results/2455387874
https://testray.liferay.com/home/-/testray/case_results/2455387838

Upstream example: 
https://testray.liferay.com/home/-/testray/case_results/2454102621

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 I am rerunning the pull to see if this shutdown hanging is really more often on this pull. Please help me monitor the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

In the new relevant tests, there are about 30% of the Clustering tests failed because portal was shutdown during the startup.

Example test:
[LocalFile.ClusteringLink#CustomizeChannelNames](https://testray.liferay.com/home/-/testray/case_results/2455625397)

cc @dantewang

**Comment by dantewang** [comment]
According to @zhangyan0701, 8 failed in a recent upstream run. 9 is not a significantly higher number.

**Comment by vicnate5** [comment]
@shuyangzhou Yea, the number has gone down on the recent PR, so we can just address this separately from this PR.

No regressions found on this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143581

**Pull request closed without merging**
