### PR TITLE
LPS-79629 Unregister ClassLoaderPool after ServletContextPool when undeploying portlets

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for CI result.

cc @igorbeslic This is what I talked about in comments of https://issues.liferay.com/browse/CLDSVCS-3269

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by samuelkong** [comment]
@tinatian 
Have you sent a new pull for this?

**Comment by tinatian** [comment]
Hi @samuelkong,
Will work on this soon, I saw support create a ticket for it :https://issues.liferay.com/browse/LPS-84130, if you guys are working on same customer

Tina.

**Comment by samuelkong** [comment]
@tinatian 
Doesn't look like one of our ticket. Adding @zsigmondrab

**Pull request closed without merging**
