### PR TITLE
LPS-X Do the read protection before "addOrUpdate" service call to avo…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…id unnecessary reindexing.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Pull request closed without merging**
