### PR TITLE
[Bug Fix]LPS-131929 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 Is this safe to go?

**Comment by vicnate5** [comment]
@shuyangzhou Yea, test failures not related.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !
See https://github.com/brianchandotcom/liferay-portal/pull/103773

**Pull request closed without merging**
