### PR TITLE
Startup optimization 246 service registry read write lock 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 this should be a slightly better version comparing to https://github.com/shuyangzhou/liferay-portal/pull/11090 , it should perform a bit better and without bring back the deadlock regression. If this passes the first round of testing, we may want to run some more heavier tests to prove it is stable.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. No unique failures, all the console log errors are present upstream too.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No issues found here. This should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135794

**Pull request closed without merging**
