### PR TITLE
Gzip2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian this one is good to go, once you confirm there is no other regression, I will send it out to Brian.

**Comment by tinatian** [comment]
OK, test it now.

**Comment by tinatian** [comment]
@shuyangzhou  It failed the following test:
                set content to 0, grab writer and write something out.

The reason is:  
we have another BufferCacheServletResponse wrap our GzipResponse, so that when we grab a writer, we can not get the EmptyGZipBufferedOutputStream in GzipResponse.

The result from browser is : 
Content-Encoding:gzip
Content-Length:34
Content-Type:
Date:Sat, 03 Jun 2017 02:58:30 GMT
Server:Apache-Coyote/1.1
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1

**Comment by shuyangzhou** [comment]
@tinatian can you send me a pull with your debugging helper code? And explain to me what do you do with it?

**Comment by tinatian** [comment]
Sure, see https://github.com/shuyangzhou/liferay-portal/pull/4396

**Comment by shuyangzhou** [comment]
@tinatian I sent this Brian already, and having QA to run their full regression tests.

**Comment by tinatian** [comment]
OK, I saw your comments. If we only focus on gzip filter, it is doing what it is supposed to do.

Tina

**Pull request closed without merging**
