### PR TITLE
Startup optimization 264 system check

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou just unit test failure: https://testray.liferay.com/home/-/testray/case_results/2398165996
`cd portal-kernel ; ant test-class -Dtest.class=ServiceProxyFactoryTest`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138690

**Pull request closed without merging**
