### PR TITLE
Struts model temp

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@koor4356 can you help me scan the failures? Any functional ones are real?

**Comment by koor4356** [comment]
Hey @shuyangzhou, portal smoke upgrade issues should be fixed now according to Brian Lee. The only issue may be "PortalSmoke#Smoke" which is only failing in weblogic. It looks like a WebLogic issue or test fix base on the screenshot. But setting up Weblogic may take more time since I haven't done it for a long time.

**Comment by shuyangzhou** [comment]
Ok, thanks @koor4356 . I will retest it again to confirm, can you watch on this pull for the new results?

**Comment by shuyangzhou** [comment]
ci:test

**Comment by koor4356** [comment]
@shuyangzhou I will do, thank you.

**Comment by koor4356** [comment]
@shuyangzhou, functional test failures are not caused by this pull request. They were already failing base on each test history on testray.

**Comment by shuyangzhou** [comment]
Sweet, thanks @koor4356 !

**Pull request closed without merging**
