### PR TITLE
LPS-86667 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://github.com/shuyangzhou/liferay-portal/pull/8527

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:dlstore

**Comment by vicnate5** [comment]
ci:test:dlstore

**Comment by vicnate5** [comment]
ci:test:dlstore

**Comment by vicnate5** [comment]
ci:test:dlstore

**Comment by vicnate5** [comment]
@shuyangzhou This looks good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81074

**Pull request closed without merging**
