### PR TITLE
LPS-45260 Prevent forbidden portlets’ JS and CSS files in page footer

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @shuyangzhou, I'm sending this over in case the extra permission check causes some kind of perf regression or you think this could be better done somewhere else.

@dantewang, @slnn, could you run perf tests against this PR with the current baseline to make sure it doesn't degrade?

Thanks!

/cc @izaera

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by shuyangzhou** [comment]
CC @Preston-Crary

**Comment by shuyangzhou** [comment]
@slnn please get the numbers first, then we will take a close look.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Here are test results for all test cases:[https://docs.google.com/spreadsheets/d/1kmthy0J2vlBYD2R1CXPRrDM1rq5_B-n-wvpt0VX8wdY/edit?usp=sharing](url)

**Comment by shuyangzhou** [comment]
All deltas are within noise range, except webcontent.
@slnn please rerun the webcontent test to be sure there is a real regression. And if so, please generate profile snapshots for it. And @jbalsas please try to fix the web content regression on your side first. If you get into trouble, we can take it over. Overall this diff is small, we can take it, but we want to fix it for web content first.

**Comment by slnn** [comment]
Hi @shuyangzhou ngzhou @jbalsas ,
I rerun test for web content on the PR, please see test result in:https://docs.google.com/spreadsheets/d/1kmthy0J2vlBYD2R1CXPRrDM1rq5_B-n-wvpt0VX8wdY/edit?usp=sharing
From test results, the session count of web content still has a slight drop on this PR, from the cpu tracing profile, the cpu time also be increaseed on this PR.

The Profile please see:https://mega.nz/#F!g0FTSYyb!C4FqSwI03cM2xoyxlXCVyA

**Comment by shuyangzhou** [comment]
@jbalsas please take a look at the webcontent regression.

**Comment by jbalsas** [comment]
Hey @shuyangzhou, @slnn, thanks for the data. I briefly discussed it this morning with @izaera, and from our end, we don't think we can apply any improvement, as we couldn't see an easy path to reuse the permissions check to make sure we don't need to repeat them.

I assume, since we weren't checking permissions before and now we do, it's almost impossible to avoid the performance hit unless this gets optimized somewhere deep down...

**Comment by izaera** [comment]
Just to add some more information in case it is valuable for finding an optimization, the original check was in `com.liferay.portlet.SecurityPortletContainerWrapper#check(HttpServletRequest,Portlet)`, line 202, the last line of the method.

I first thought that I could reuse that check by setting its result inside the request in `com.liferay.portlet.SecurityPortletContainerWrapper#render(HttpServletRequest,HttpServletResponse,Portlet)`, inside the `catch(PrincipalException)` but that's not possible because the request is isolated and it's not the original one, so I stopped exploring that path and decided to duplicate the check.

If you can think of any other way to reuse that check it would lead to a performance increase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/54973

**Pull request closed without merging**
