### PR TITLE
LPS-93658 Migrate portal-remote-soap-extender-test to use arquillian bridge

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
Will resend after fixing the log assertion failures.

**Comment by Preston-Crary** [comment]
Wrong test, will look into the oauth2-test failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72570

**Pull request closed without merging**
