### PR TITLE
LPS-69227

### PR DESCRIPTION
**Pull request by danielkocsis**
Hey @shuyangzhou,

Brian asked me to send you this change because he has concerns regarding its performance. I also share his doubts, but unfortunately I can't see more things we could optimize without changing the business needs. The only thing I can think of is to make it non-blocking via sending it to the background, but I am not sure about this option. The other way would be to change the nature of the solution from a one-time process to a series of small lazy checks, but the original problem occurred because we already have many small hacks at places where we need those, but we would have to implement one more of these and we wanted to resolve the issue in a more robust, generic way. 

What do you think?

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @shuyangzhou,

did you have the chance to check this? 

cc'ing: @cleydyr

**Comment by shuyangzhou** [comment]
@danielkocsis sorry, I did not have time for this, and probably won't have time for it anytime soon either.

@tinatian please take it over to see what this is about, thanks!

**Comment by danielkocsis** [comment]
No problem @shuyangzhou and thank you @tinatian for helping with this

**Comment by tinatian** [comment]
Sure, I will take a look at it.

**Comment by tinatian** [comment]
Hi @danielkocsis,

I am trying to reproduce the original problem you want to fix, but unable to change the default language, not sure if there is something wrong with ui part on current master. 

Could you please check if you have same problem on head of master? 

By the way, do you have another way to reproduce it?


Thanks.
Tina.

**Comment by danielkocsis** [comment]
Hey @tinatian,


first I tried to follow the steps from the ticket and successfully reproduced the issue at http://master.liferay.org.es/

Than, I built a portal locally, from the source code already contained the fixes, and I was not able to reproduce the issue, but I was able to change the default language. 

I followed these steps:
Launch a portal;

1. Go to Control Panel, Instance Settings, Miscellaneous, Display Settings;
2. Configure any language other than English as Default Language;
3. Go to Site Settings, Publishing, Staging;
4. Enable Local Live staging.

Daniel

**Comment by danielkocsis** [comment]
However, as far as I know via setting the `company.default.locale=en_US` portal property to something else, you can also modify this setting.

**Comment by tinatian** [comment]
@danielkocsis Please see my changes here : https://github.com/danielkocsis/liferay-portal/pull/613


Tina.

**Pull request closed without merging**
