### PR TITLE
[ResourceAction]LPS-112055 rebase and SF

### PR DESCRIPTION
**Pull request by dantewang**
Rebased https://github.com/shuyangzhou/liferay-portal/pull/9087 and fixed an SF issue according to https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/exception_check.markdown  cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by vicnate5** [comment]
Test results fully reviewed on https://github.com/shuyangzhou/liferay-portal/pull/9087#issuecomment-631926839 and compared to results here as well., no regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
