### PR TITLE
[TS] LPS-122640

### PR DESCRIPTION
**Pull request by balazssk**
Hi @shuyangzhou ,

Can you please review?
https://issues.liferay.com/browse/LPS-122640

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @shuyangzhou ,
Can you please check this?
Thanks

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
