### PR TITLE
Lps 69644 Add snapshot class

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

I resent this pull since the old one (https://github.com/shuyangzhou/liferay-portal/pull/3576) is closed.

Tina.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tomwang2011 have you tested this yet?

**Comment by tomwang2011** [comment]
@shuyangzhou I tested the old pull https://github.com/shuyangzhou/liferay-portal/pull/3576, I will test this new one now.

**Comment by tinatian** [comment]
@tomwang2011 nothing is changed compared with the old one https://github.com/shuyangzhou/liferay-portal/pull/3576, no need to test it. I resent only because it was closed somehow by CI

**Comment by tomwang2011** [comment]
@tinatian @shuyangzhou the results of the old pull is at: smb://172.16.0.30/benchmark/2016/TestPulls-Tina/12-16-16-LPS-69644

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45867

**Pull request closed without merging**
