### PR TITLE
LPS-X All service getting and unregistering must happen before system…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… bundle shutdown.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128063

**Pull request closed without merging**
