### PR TITLE
LPS-56115 Fix SampleSQLBuilder classpath

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @shuyangzhou
This fix doesn't require LPS-56174.

Without LPS-56174, we need to refer to the `service` and `api` jar of each module explicitly, and put them before `project.classpath`.

If we have the bug stated in LPS-56174 fixed, we can move `<path refid="project.classpath" />` to the top of the path list, and keep using things like `com.liferay.wiki.*.jar`.

**Comment by dantewang** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
I would prefer to do the LPS-56174 way, waiting @tinatian to resend the rebase of it. Tina you saw I closed it and asked for rebase, right?

**Comment by tinatian** [comment]
@dantewang  LPS-56174 is ready, you and resend this pull now.

Tina.

**Pull request closed without merging**
