### PR TITLE
Lps 81336 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@michaelhashimoto @pyoo47 can you guys take care this issue?
We are counting on CI to be working, especially these days right before release. Otherwise everything will be blocked.

CC @brianchandotcom

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
@shuyangzhou @michaelhashimoto @brianchandotcom I've backed out the change that was causing the problem for now. It will take some deeper investigation to find and fix the real problem. My retest appears to be working fine now.

**Comment by shuyangzhou** [comment]
Thanks @pyoo47 ! Can we stage testing Jenkins changes before bring it online whenever we can? We need to avoid ci down time before release.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@pyoo47 @shuyangzhou @arboliveira - I'm sorry.. I didn't test this against a full `ci:test`.  I only tested it against `ci:test:relevant`, `ci:test:sf` & the release tester i was trying to make fixes against.  I'll test it against `ci:test` in the future.

**Comment by michaelhashimoto** [comment]
Peter had already reverted my changes, but here's a fix for the current issue:
https://github.com/pyoo47/liferay-portal/pull/672

**Pull request closed without merging**
