### PR TITLE
Logical Partitioning: Company provider

### PR DESCRIPTION
**Pull request by migue**
Hey Shuyang,<br> @brianchandotcom asked me to send you the pull so you can review the tests part (he already reviewed the other parts but we should merged everything together. Let me know if there is something I can help /cc @cgongas (the original pull was this https://github.com/brianchandotcom/liferay-portal/pull/33118)

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Waiting for the new pull to fix issues in master first.

**Comment by migue** [comment]
The code is not really in master :)

**Comment by shuyangzhou** [comment]
What is not in master?

**Comment by shuyangzhou** [comment]
Ah, I did not see this one https://github.com/liferay/liferay-portal/commit/6ba4d1bf3be9f2c614dbbde34af949a5e47ad813

You are right, master is ok now, that's better, then please just resend with the proper companyId usage.

**Pull request closed without merging**
