### PR TITLE
LPS-84374 Transacctional Portal Cache

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou  Failures reported by CI are not related to this pull.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63586

**Pull request closed without merging**
