### PR TITLE
LPS-56462

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
On those onBeforeUpdate(), shouldn't we clear by the getOriginalXXX() ?

**Comment by Preston-Crary** [comment]
Yes, I'll resend.

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/1422

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/27726

**Pull request closed without merging**
