### PR TITLE
Lps 183421 redo

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @david-truong @vicnate5

**Comment by david-truong** [comment]
@xbrianlee can you help review these results

**Comment by xbrianlee** [comment]
@david-truong The test results above look good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137057

**Pull request closed without merging**
