### PR TITLE
[ResourceAction]LPS-112056

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Unique Headless failures https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/272665/#showFailuresLink

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
Fixed headless at https://github.com/tinatian/liferay-portal/pull/1862

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
