### PR TITLE
LPD-X Since there is no finders include loginDate/loginIP/lastLoginDa…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…te/lastLoginIP/failedLoginAttempts, don't bother to update finder cache.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@victorhcunha please run a login check for this pull, thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:17288224

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:report:17521230

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 703bbd3 | 10627 | - | 268 | 2,3,2 | 95,91,94
PR | - | 11063 | 4.102757128 | 277 | 2,2,2 | 94,93,94

More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1xwqQLBtpgiRRqHETyycas-7NRcveN3lO2_NIFiCef2g/edit#gid=0)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151405

**Pull request closed without merging**
