### PR TITLE
[Bug Fix]LPS-122653

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@slnn please run a startup compare for this pull, thanks!

**Comment by slnn** [comment]
Hi @/GinsonRen

Could you test this one and update the results to shuyang?

Lily

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the result:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 486468c17 | 47694 | 22,195 | 22,278 | 22,210 | 21,962 | 22,291 | 22,234
PR-9607 | - | 44632 | 21,996 | 22,057 | 22,103 | 21,877 | 21,928 | 22,013

/cc @slnn

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
