### PR TITLE
Startup optimization 68 optimize fragment entry link local service impl get fragment entry links to use cache

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 Can you check this one?

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Pull request closed without merging**
