### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on #8794.

Steps to test:

1.Run ant all
2.Start portal, login and go to control panel->configuration->search, will see Search Engine Vendor: Elasticsearch (Embedded), Client Version: 7.3.0, Nodes: LiferayElasticsearchCluster: [liferay (7.3.0)]

To test cluster,
Just enable cluster by setting "cluster.link.enabled=true"

Known issues:
1.Dumping log4j.properties into temp folder

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
@vicnate5 I made this change as you suggested, but tests still failed.
https://github.com/shuyangzhou/liferay-portal/pull/8799/commits/eac83ff5f74d1a523d573f80e47623c3884f6a63

**Comment by vicnate5** [comment]
@tinatian The log4j update worked, but then the poshi error checker also needed to ignore.

Resent with fix: https://github.com/shuyangzhou/liferay-portal/pull/8802

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
