### PR TITLE
LPS-96652 Avoid ExceptionInInitializerError in child process

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
CI test failures seem to be unrelated to my changes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74376

**Pull request closed without merging**
