### PR TITLE
LPS-71736

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by holatuwol** [comment]
Should be addressed with https://github.com/liferay/liferay-portal/commit/958b3210e90ed5010cbe0836a27a00548c35f002#diff-9c829df27b5b093eb082c7fc7587f7d7

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:stop

@holatuwol quite the opposite, that is the commit that caused the compile failure.

**Comment by shuyangzhou** [comment]
ci:retest

I have fixed it in upstream https://github.com/liferay/liferay-portal/commit/395fdc5700c9c6c64a703a391833b7f7ea876351

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by holatuwol** [comment]
Meh, for some reason I thought that commit was after my pull request, but a quick timestamp check reveals that I was wrong.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48172

**Pull request closed without merging**
