### PR TITLE
[Bug Fix]LPS-129717

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:smoke

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go, the 1 test failure is unrelated. New automation test confirms this issue is fixed.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100304

**Pull request closed without merging**
