### PR TITLE
Upgrade dm 14

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Master-private run: https://github.com/vicnate5/liferay-portal-ee/pull/314

**Comment by shuyangzhou** [comment]
@slnn please run a startup compare on your side, this cuts 5~6s for me. Let's see how much it gets on your side.

**Comment by vicnate5** [comment]
ci:test:clustering

Pretty sure the cluster failure is a random issue we have seen before at head. Just making sure.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

It cuts about 6s on myside, here are test results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 70f2da4 | 49482 | 26567.4 | 24639 | 34658 | 24617 | 24361 | 24562
PR | - | 39166 | 19720.8 | 19158 | 19129 | 20185 | 20222 | 19910

**Comment by shuyangzhou** [comment]
Great, now we just wait it clears ee side ci, then roll it out.

**Comment by slnn** [comment]
@shuyangzhou, update my typo, it cuts 4.8s on myside.

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/78700

**Pull request closed without merging**
