### PR TITLE
[Bug Fix]LPS-105126 Sybase

### PR DESCRIPTION
**Pull request by tinatian**
FYI @SamZiemer

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @vicnate5,
Do we have an upgrade test covering this? Which ci test should I run in this case?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
FYI @dantewang, please use "ci:test:upgrade" to include tests for upgrade.

**Comment by tinatian** [comment]
Hi @vicnate5 ,
According to the test result, there is no functional upgrade test for sybase. Is there something wrong with sybase test batch or we did not have it at all?

Tina

**Comment by vicnate5** [comment]
@tinatian Functional upgrade tests were disabled on the test level because of https://issues.liferay.com/browse/LPS-95571. Since the issues related to this are getting fixed, it should be safe to turn on now.

Resent https://github.com/shuyangzhou/liferay-portal/pull/8589

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
