### PR TITLE
Lps 94365

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:backend-hypersonic

**Comment by shuyangzhou** [comment]
@mtambara

**Comment by mtambara** [comment]
@shuyangzhou The ArquillianTest is failing. Is the client side test class loading still happening?

**Comment by shuyangzhou** [comment]
It is still here https://github.com/shuyangzhou/liferay-portal/blob/0c48053e823b01f614f11e70f93e0189ccd03fca/modules/test/arquillian-extension-junit-bridge/src/main/java/com/liferay/arquillian/extension/junit/bridge/junit/Arquillian.java#L97
It must be something else failing them.

Any other real failures?

**Comment by mtambara** [comment]
I think that's the only one

**Comment by shuyangzhou** [comment]
OK, I can take care of them later tonight. This pull must be finished to unblock the release process tomorrow.

**Pull request closed without merging**
