### PR TITLE
[Deprecation]LPS-104910

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@koor4356 Please analyze.

**Comment by koor4356** [comment]
ci:bundle

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@shuyangzhou, Look goods.  No unique issues except conflicting files. Thanks!

**Comment by shuyangzhou** [comment]
@tinatian rebase failure, please resend.

**Comment by tinatian** [comment]
Hi @dantewang 
Rebase failure, please resent directly to shuyang and cc me.

Thanks.
Tina.

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
