### PR TITLE
Lps 73353 Clean up cobertura + Jacoco support

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull contains the clean up step and jacoco support.
I have sent you a separate pull just for clean up step, please see https://github.com/shuyangzhou/liferay-portal/pull/4547.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:retest

**Comment by tinatian** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by tinatian** [comment]
The compile error caused by commit 5f54f01370992097a440c319c0bf7345edf13afa, a commit from Andrea

**Pull request closed without merging**
