### PR TITLE
LPS-111972 Remove TrueZip library

### PR DESCRIPTION
**Pull request by vendeltoreki**
(resending https://github.com/shuyangzhou/liferay-portal/pull/9177 with fixed SF)

Hi @shuyangzhou ,

As suggested in https://github.com/shuyangzhou/liferay-portal/pull/9153 , I removed all references I could find to TrueZip ( schlichtherle.io ). I tested this change with the case of [LPS-111972](https://issues.liferay.com/browse/LPS-111972) again, and it seemed to be working.

Please review my changes.

Thanks,
Vendel

cc: @holatuwol , @ericyanLr

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/9182

**Comment by vicnate5** [comment]
ci:close

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/90455
@vendeltoreki from the commit log you can see, your initial version has many problems, including even the unit test you modified failed. Not to mention many integration test failures.

And the solution you did, does not work, as staging code requires the random access behavior. Meaning they need to be able to repeatedly writing into the same zip file with the same ZipWriterImpl, which means ZipOuputStream is a wrong solution, as it can only do sequential output. Also they need to be able to see latest zip file content with the same ZipReaderImpl, even when there is a modification after you opened the ZipReaderImpl, which means a cache ZipFile is a wrong solution too.

Fundamentally, staging code did not unwise choose on the behaviors, which is very bad in terms of performance. But we are not changing staging code logic here in this ticket, so we have to honor it by forcing ZipReaderImpl/ZipWriterImpl providing what they need.

**Pull request closed without merging**
