### PR TITLE
[ResourceAction]LPS-112055

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by tinatian** [comment]
@vicnate5 Could you please check the test results?

Thanks
Tina.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:close

**Comment by vicnate5** [comment]
No regressions found

**Pull request closed without merging**
