### PR TITLE
LPS-X Force equinox to resolve bundle by the caller thread to avoid u…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…nnecessary resolver threads creation.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
looking at results now

**Comment by kyle-miho** [comment]
@shuyangzhou no unique failures found, PR is good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132075

**Pull request closed without merging**
