### PR TITLE
Theme settings

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tomwang2011 run a diff please

### CODE REVIEW

**Comment by shuyangzhou** [comment]
cI:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by tomwang2011** [comment]
Hi @shuyangzhou the results are in: smb://172.16.0.30/benchmark/2016/TestPulls-Shuyang/12-19-16-ThemeSettings

**Comment by shuyangzhou** [comment]
ci:retest

**Pull request closed without merging**
