### PR TITLE
[7.4-only] LPS-122191 Removes unnecessary FlashMagicBytes checks 

### PR DESCRIPTION
**Pull request by izaera**
This is the continuation of https://github.com/liferay-appsec/liferay-portal/pull/143

---

Based on the analysis done at [Analyze security relevance of FlashMagicBytes check](https://issues.liferay.com/browse/LPS-121737)):

> DXP uses a FlashMagicBytesUtil to check verify if some files are Adobe Flash movies (regardless of their extension). This was added for securtiy reasons to protect from CSRF attack using uploaded flash files

From @topolik:

> [...] this would be relevant as long as we support browsers that supports flash. Once all supported browsers discard flash we can remove. Thanks.

All browsers in our possible compatibility matrix for 7.4 will have dropped Flash by the time we release as per their roadmaps:

- [Chrome](https://www.chromium.org/flash-roadmap#TOC-Flash-Player-blocked-as-out-of-date-Target:-All-Chrome-versions---Jan-2021-): Flash Player blocked as "out of date" (Target: All Chrome versions - Jan 2021)
- [Firefox](https://developer.mozilla.org/en-US/docs/Plugins/Roadmap): In January 2021, Firefox 85 will completely remove Flash support. Adobe will stop shipping security updates for Flash at the end of 2020.
- [Safari](https://www.techspot.com/news/83681-apple-completely-remove-flash-support-next-version-safari.html): Apple just released the latest Safari Technology preview. It comes with many changes, most notably the removal of support for Adobe Flash.

Based on this, I think it's safe to remove the `FlashMagicBytes` checks.

The solution:

- `FlashMagicBytesUtil` uses a `PushbackInputStream` to read the first bytes of an `InputStream` and then simply rewinds it and provides means to access it. That means that when removing the usage, we can simply use the original `InputStream` to keep the same behaviour.
- To avoid a major kernel breaking change, we're simply deprecating both `FlashMagicBytesUtil` and `FlashMagicBytesUtilTest` instead of deleting them.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Hey @shuyangzhou . Sorry for the mess with the CI...

I'm sending you this PR so that you can review the last two commits, which affect the backend infrastructure. You can look at the preceding commits at your will, but it is mostly frontend infra stuff.

Given that all of the rest has been accepted by the security team, once those two commits are clear, this can be forwarded to Brian for merge.

CCing @jbalsas and @topolik in case they want to add something before this is forwarded to master.

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9544

**Pull request closed without merging**
