### PR TITLE
[Deprecation]LPS-103617 modules part 4

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Cloud you please help me verify the ci result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian failures not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80348

**Pull request closed without merging**
