### PR TITLE
LPS-99387 CTEntryLocalService

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by Preston-Crary** [comment]
The StaleObjectStateException is from BackgroundTask, not caused by these changes.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76771

**Pull request closed without merging**
