### PR TITLE
Lps 185647 redo 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@susanchen3 please help me check the CI results, and manually retest [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) and [LPS-185647](https://liferay.atlassian.net/browse/LPS-185647) on Monday.

I will be out on Monday, if there is any real issues, please comment me the steps. I will look into it Tuesday.
Thanks!

**Comment by vicnate5** [comment]
@susanchen3 See manual steps defined in https://github.com/shuyangzhou/liferay-portal/pull/11124#issuecomment-1626082826.

**Comment by vicnate5** [comment]
@shuyangzhou,  @achaparro would like to review this on Tuesday before we merge.

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
There seems to be a connection issue. I was able to reproduce it running an integration test locally.
1. Without starting portal, run `ant -f build-test-local.xml run-integration-test -Dtest.class=com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest`

[Full log](https://gist.githubusercontent.com/susanchen3/81ada7f0b42355c42b013956d8455583/raw/90ec8dcb4fcd174180941246f5c865e1e0d7d9db/gistfile1.txt)
```
     [exec] 2023-07-10 21:33:47.144 ERROR [com.liferay.object.rest.test-executor-thread][SqlExceptionHelper:142] Connection is closed
     [exec] 2023-07-10 21:33:47,145 com.liferay.object.rest.test-executor-thread ERROR An exception occurred processing Appender XtKcYae1 org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.AssertionError: {level=ERROR, loggerName=org.hibernate.engine.jdbc.spi.SqlExceptionHelper, message=Connection is closed
     [exec] 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
     [exec] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
     [exec] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:388)
     [exec] 	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
     [exec] 	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:153)
     [exec] 	at org.jboss.logging.Log4j2Logger.doLog(Log4j2Logger.java:54)
     [exec] 	at org.jboss.logging.Logger.error(Logger.java:1518)
```


----

Commerce integration tests are failing too.
1. Without starting portal, run `ant -f build-test-local.xml run-integration-test -Dtest.class=com.liferay.commerce.product.change.tracking.test.CPDefinitionLinkTableReferenceDefinitionTest`

[Full log](https://gist.githubusercontent.com/susanchen3/afeee0e1aac5b9e55a6bce28ac57fe54/raw/7374fa6890b1c2e0a29768c7d9f6cb745b3fdbe8/gistfile1.txt)
```
[exec] com.liferay.commerce.product.change.tracking.test.CPDefinitionLinkTableReferenceDefinitionTest > testDiscardCTEntry FAILED
     [exec]     java.util.ConcurrentModificationException
     [exec]     	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
     [exec]     	at java.util.ArrayList$Itr.next(ArrayList.java:861)
     [exec]     	at com.liferay.portal.spring.hibernate.LastSessionRecorderUtil.syncLastSessionState(LastSessionRecorderUtil.java:54)
     [exec]     	at com.liferay.portal.spring.hibernate.LastSessionRecorderUtil$1.doCreated(LastSessionRecorderUtil.java:43)
     [exec]     	at com.liferay.portal.kernel.transaction.NewTransactionLifecycleListener.created(NewTransactionLifecycleListener.java:39)
     [exec]     	at com.liferay.portal.kernel.transaction.TransactionLifecycleManager.fireTransactionCreatedEvent(TransactionLifecycleManager.java:51)
     [exec]     	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.start(DefaultTransactionExecutor.java:144)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:64)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)

```


----


There also seems to be a race condition startup error. I was only able to reproduce it once locally.
1. Add `include-and-override=portal-liferay-online.properties` to portal-ext.properties
3. Start portal

[Full log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-25/test-portal-acceptance-pullrequest(master)/1825/functional-tomcat90-mysql57-chrome100-jdk8/2/7/liferay-log.txt.gz?authuser=0)
```
2023-07-08 09:26:18.589 ERROR [main][BatchingBatch:139] HHH000315: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update LayoutSet set mvccVersion=?, modifiedDate=?, logoId=? where layoutSetId=? and mvccVersion=?], SQL: update LayoutSet set mvccVersion=?, modifiedDate=?, logoId=? where layoutSetId=? and mvccVersion=?
2023-07-08 09:26:18.607 ERROR [main][DependencyManagerSyncImpl:57] Unable to sync callable
org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update LayoutSet set mvccVersion=?, modifiedDate=?, logoId=? where layoutSetId=? and mvccVersion=?; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update LayoutSet set mvccVersion=?, modifiedDate=?, logoId=? where layoutSetId=? and mvccVersion=?
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:287) ~[spring-orm.jar:5.2.24.RELEASE]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:804) ~[spring-orm.jar:5.2.24.RELEASE]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:639) ~[spring-orm.jar:5.2.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx.jar:5.2.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx.jar:5.2.24.RELEASE]
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.commit(DefaultTransactionExecutor.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:77) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy124.updateLogo(Unknown Source) ~[?:?]
```

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/11128
@susanchen3 please rerun the manual tests and check CI results on the new pull.

**Pull request closed without merging**
