### PR TITLE
Pushdown osgi core

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@shuyangzhou multiple issues here.

#### 1. Wildlfy/Jboss cannot start
```
  [waitfor] [0m[31m19:56:14,680 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 91) MSC000001: Failed to start service jboss.deployment.unit."ROOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: URI scheme is not "file"
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
  [waitfor] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  [waitfor] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  [waitfor] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
  [waitfor] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
  [waitfor] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
  [waitfor] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
  [waitfor] 	at java.lang.Thread.run(Thread.java:745)
  [waitfor] 	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
  [waitfor] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: URI scheme is not "file"
  [waitfor] 	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
  [waitfor] 	... 8 more
  [waitfor] Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: URI scheme is not "file"
  [waitfor] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:273)
  [waitfor] 	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
  [waitfor] 	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
  [waitfor] 	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
  [waitfor] 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
  [waitfor] 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  [waitfor] 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  [waitfor] 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  [waitfor] 	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
  [waitfor] 	... 10 more
  [waitfor] Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
  [waitfor] 	at java.io.File.<init>(File.java:421)
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._buildFrameworkProperties(ModuleFrameworkImpl.java:724)
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.initFramework(ModuleFrameworkImpl.java:271)
  [waitfor] 	at com.liferay.portal.module.framework.ModuleFrameworkUtil.initFramework(ModuleFrameworkUtil.java:67)
  [waitfor] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:261)
  [waitfor] 	... 21 more
  ```
https://testray.liferay.com/reports/production/logs/2021-05/test-1-22/test-portal-acceptance-pullrequest(master)/8163/functional-wildfly140-mariadb102-jdk8/0/15/jenkins-console.txt.gz


#### 2. Websphere cannot start
```
  [waitfor] 2021-05-17 19:58:52.732 ERROR [server.startup : 0][ModuleFrameworkImpl:650] org.osgi.framework.BundleException: Extension bundle fragments cannot specify an Import-Package header: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/static/org.apache.aries.spifly.dynamic.framework.extension.jar?protocol=jar&static=true
  [waitfor] org.osgi.framework.BundleException: Extension bundle fragments cannot specify an Import-Package header: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/static/org.apache.aries.spifly.dynamic.framework.extension.jar?protocol=jar&static=true
  [waitfor] 	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.validateExtension(BaseStorage.java:1049) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.processExtension(BaseStorage.java:1030) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.internal.baseadaptor.BundleInstall.commit(BundleInstall.java:122) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.Framework.installWorkerPrivileged(Framework.java:970) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:845) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:1) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at java.security.AccessController.doPrivileged(AccessController.java:696) ~[?:1.8.0]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.Framework.installWorker(Framework.java:904) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.Framework.installBundle(Framework.java:840) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:137) ~[org.eclipse.osgi_.jar:?]
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._addBundle(ModuleFrameworkImpl.java:647) [com.liferay.portal.bootstrap.jar:?]
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._installInitialBundle(ModuleFrameworkImpl.java:1330) [com.liferay.portal.bootstrap.jar:?]
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1710) [com.liferay.portal.bootstrap.jar:?]
  [waitfor] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:402) [com.liferay.portal.bootstrap.jar:?]
  [waitfor] 	at com.liferay.portal.module.framework.ModuleFrameworkUtil.startFramework(ModuleFrameworkUtil.java:95) [portal-impl.jar:?]
  [waitfor] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:324) [portal-impl.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:1834) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:442) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719) [com.ibm.ws.webcontainer.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1248) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1516) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:704) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1098) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:800) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2317) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5466) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5682) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2322) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:985) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:524) [com.ibm.ws.runtime.jar:?]
  [waitfor] 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) [com.ibm.ws.runtime.jar:?]
```
https://testray.liferay.com/reports/production/logs/2021-05/test-1-22/test-portal-acceptance-pullrequest(master)/8163/functional-websphere90-mysql57-jdk8/0/15/jenkins-console.txt.gz

#### 3. Weblogic start failure
```
  [waitfor] Caused By: java.lang.NoSuchMethodError: org.osgi.framework.Version.valueOf(Ljava/lang/String;)Lorg/osgi/framework/Version;
  [waitfor] 	at org.eclipse.osgi.storage.Storage.<init>(Storage.java:163)
  [waitfor] 	at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:151)
  [waitfor] 	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:69)
  [waitfor] 	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
  [waitfor] 	at org.eclipse.osgi.launch.EquinoxFactory.newFramework(EquinoxFactory.java:24)
  [waitfor] 	Truncated. see log file for complete stacktrace
```
https://testray.liferay.com/reports/production/logs/2021-05/test-1-22/test-portal-acceptance-pullrequest(master)/8163/functional-weblogic122-mysql57-jdk8/0/15/jenkins-console.txt.gz

#### 4. Upgrade errors even on Tomcat
```
     [java] java.lang.NullPointerException: null
     [java] 	at com.liferay.portal.kernel.util.FileUtil.deltree(FileUtil.java:130) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JSPServletFactoryImpl$JspFragmentBundleTrackerCustomizer._deleteJSPServletClasses(JSPServletFactoryImpl.java:169) ~[?:?]
     [java] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JSPServletFactoryImpl$JspFragmentBundleTrackerCustomizer.addingBundle(JSPServletFactoryImpl.java:120) ~[?:?]
     [java] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JSPServletFactoryImpl$JspFragmentBundleTrackerCustomizer.addingBundle(JSPServletFactoryImpl.java:82) ~[?:?]
     [java] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:746) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:538) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:484) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1028) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1409) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
     [java] 2021-05-17 21:51:43.997 ERROR [Start Level: Equinox Container: a9ef0322-c755-4d49-9a97-3e18efb3e6a9][FileSystemStoreRegister:93] bundle com.liferay.portal.store.file.system:6.0.2 (188)[com.liferay.portal.store.file.system.FileSystemStoreRegister(381)] : The activate method has thrown an exception 
     [java] java.lang.NullPointerException: null
```

https://testray.liferay.com/reports/production/logs/2021-05/test-1-13/test-portal-acceptance-pullrequest(master)/5953/functional-upgrade-tomcat90-mysql57-jdk8/4/14/jenkins-console.txt.gz

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou 

**Wildfly/Jboss starts fully, but has an error still**
```
ERROR [Framework Event Dispatcher: Equinox Container: af47283b-8c1c-42de-a089-b5ba7117cad6][Framework:93] FrameworkEvent ERROR 
org.osgi.framework.BundleException: Cannot support framework extension bundles without a public addURL(URL) method on the framework class loader: org.apache.aries.spifly.dynamic.framework.extension_1.2.3.LIFERAY-PATCHED-1 [53]
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent0(FrameworkExtensionInstaller.java:116) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent(FrameworkExtensionInstaller.java:91) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.SystemBundleLoader$SystemModuleClassLoader.loadFragments(SystemBundleLoader.java:131) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.SystemBundleLoader.loadClassLoaderFragments(SystemBundleLoader.java:113) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.loadFragments(BundleLoader.java:306) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleWiring.loadFragments(ModuleWiring.java:273) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:737) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:538) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:484) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:474) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.resolveBundles(ModuleContainer.java:1340) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1815) ~[com.liferay.portal.bootstrap.jar:?]
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:400) ~[com.liferay.portal.bootstrap.jar:?]
	at com.liferay.portal.module.framework.ModuleFrameworkUtil.startFramework(ModuleFrameworkUtil.java:95) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:324) ~[portal-impl.jar:?]
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) ~[?:?]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250) ~[undertow-servlet-2.0.13.Final.jar!/:2.0.13.Final]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96) ~[?:?]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487) ~[?:?]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
	at org.jboss.threads.JBossThread.run(JBossThread.java:485) ~[?:?]
```
https://testray.liferay.com/reports/production/logs/2021-05/test-1-21/test-portal-acceptance-pullrequest(master)/8057/functional-wildfly140-mariadb102-jdk8/0/15/liferay-log.txt.gz

**Weblogic log**: https://testray.liferay.com/reports/production/logs/2021-05/test-1-21/test-portal-acceptance-pullrequest(master)/8057/functional-weblogic122-mysql57-jdk8/0/15/jenkins-console.txt.gz

**Websphere log**: https://testray.liferay.com/reports/production/logs/2021-05/test-1-21/test-portal-acceptance-pullrequest(master)/8057/functional-websphere90-mysql57-jdk8/0/15/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
@kyle-miho Please help Shuyang review these results tomorrow if needed. See my comments above for the known issues.

**Pull request closed without merging**
