### PR TITLE
Lps 116452 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this, and if good, please run the staging test, thanks!

**Comment by vicnate5** [comment]
ci;test:staging

**Comment by vicnate5** [comment]
ci:test:staging

**Comment by vicnate5** [comment]
@shuyangzhou looks good

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 , I made a followup change here https://github.com/shuyangzhou/liferay-portal/pull/9260 , can you monitor that one too? thanks!

**Pull request closed without merging**
