### PR TITLE
[Deprecation]LPS-104837

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @kyle-miho,
Please help us scan the test result.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
Poshi test failures upstream already or flakey & unrelated. Looking through backend results

**Comment by kyle-miho** [comment]
ci:test:4af31cffb4ba796bc7707431292bb348b28638d1

**Comment by tinatian** [comment]
ci:reopen

**Comment by zhangyan0701** [comment]
Test failures are unrelated. 

The modules integration and unit test failures were fixed in LRCI-863.
source-format failure was fixed in LRQA-54587.
Others are failed in upstream as well.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82565

**Pull request closed without merging**
