### PR TITLE
[TECHNICAL-SUPPORT] LPS-81758

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:retest:relevant

**Comment by SamZiemer** [comment]
ci:retest

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62334

**Pull request closed without merging**
