### PR TITLE
Startup optimization 242 initial upgrade step

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, I am trying to switch to a different direction to do the initial table creation thing and this is trying out for the most important part. If it is clear, I will move on to the rest parts. Thanks!

**Comment by vicnate5** [comment]
We still have lots of unique failures here:

#### 1. Verify processes run on restart

Steps to reproduce
1. Start portal on a fresh DB
2. Assert VerifyProcess runs
3. Shutdown and restart portal

Expected: No verify process runs
Actual: Verify processes run

#### 2. Upgrade of 6.2 dump with multiple companies fails on certain databases (PSQL, Oracle, DB2, SQL Server)

Steps for PostgreSQL
1. Download [psql dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-virtual-instances-postgresql.zip)
2. Import dump into PSQL - [instructions](https://liferay.atlassian.net/wiki/spaces/QA/pages/2168031601/PostgreSQL+Database)
3. Run upgrade tool
4. Start portal

```
ERROR [main][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into Region (mvccVersion, uuid_, defaultLanguageId, companyId, userId, userName, createDate, modifiedDate, countryId, active_, name, position, regionCode, lastPublishDate, regionId) values (0, '9c5f71c0-3842-0fa9-4d31-2a553a01c6a4', NULL, 10845, 10848, NULL, '2023-05-26 06:25:18.703+00', '2023-05-26 06:25:18.703+00', 18954, 'TRUE', 'Kayseri', 0.0, '38.0', NULL, 19001) was aborted: ERROR: duplicate key value violates unique constraint "region_pkey"
  Detail: Key (regionid)=(19001) already exists.  Call getNextException to see other errors in the batch.], SQL: insert into Region (mvccVersion, uuid_, defaultLanguageId, companyId, userId, userName, createDate, modifiedDate, countryId, active_, name, position, regionCode, lastPublishDate, regionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-05-26 06:25:18.719 ERROR [main][SqlExceptionHelper:142] Batch entry 0 insert into Region (mvccVersion, uuid_, defaultLanguageId, companyId, userId, userName, createDate, modifiedDate, countryId, active_, name, position, regionCode, lastPublishDate, regionId) values (0, '9c5f71c0-3842-0fa9-4d31-2a553a01c6a4', NULL, 10845, 10848, NULL, '2023-05-26 06:25:18.703+00', '2023-05-26 06:25:18.703+00', 18954, 'TRUE', 'Kayseri', 0.0, '38.0', NULL, 19001) was aborted: ERROR: duplicate key value violates unique constraint "region_pkey"
  Detail: Key (regionid)=(19001) already exists.  Call getNextException to see other errors in the batch.
2023-05-26 06:25:18.720 ERROR [main][SqlExceptionHelper:142] ERROR: duplicate key value violates unique constraint "region_pkey"
  Detail: Key (regionid)=(19001) already exists.
2023-05-26 06:25:18.734 ERROR [main][SqlExceptionHelper:142] ERROR: current transaction is aborted, commands ignored until end of transaction block
2023-05-26 06:25:18.735 ERROR [main][PortalAddressOSGiCommands:126] null
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:649) ~[portal-kernel.jar:?]
	at com.liferay.portal.service.persistence.impl.CountryLocalizationPersistenceImpl.findByCountryId(CountryLocalizationPersistenceImpl.java:241) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.CountryLocalizationPersistenceImpl.findByCountryId(CountryLocalizationPersistenceImpl.java:137) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.CountryLocalizationPersistenceImpl.findByCountryId(CountryLocalizationPersistenceImpl.java:96) ~[portal-impl.jar:?]
	at com.liferay.portal.service.base.CountryLocalServiceBaseImpl.updateCountryLocalizations(CountryLocalServiceBaseImpl.java:547) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.CountryLocalServiceImpl.updateCountryLocalizations(CountryLocalServiceImpl.java:296) ~[portal-impl.jar:?]
	at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:79) ~[?:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy208.updateCountryLocalizations(Unknown Source) ~[?:?]
	at com.liferay.address.internal.osgi.commands.PortalAddressOSGiCommands.populateCompanyCountries(PortalAddressOSGiCommands.java:120) ~[?:?]
	at com.liferay.address.internal.portal.instance.lifecycle.PortalInstanceLifecycleListenerImpl.portalInstanceRegistered(PortalInstanceLifecycleListenerImpl.java:42) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$registerCompany$1(PortalInstanceLifecycleListenerManagerImpl.java:199) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl._runIfNeeded(PortalInstanceLifecycleListenerManagerImpl.java:304) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:183) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$null$1(PortalInstanceLifecycleListenerManagerImpl.java:430) ~[?:?]
	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:36) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28) ~[portal-kernel.jar:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$addingService$2(PortalInstanceLifecycleListenerManagerImpl.java:423) ~[?:?]
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:498) [portal-impl.jar:?]
```

#### 3. Group of integration tests failing with `UnsupportedOperationException`
Example https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11780/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz

#### 4. Upgrade tests failure `com.liferay.portal.upgrade.test.UpgradeLogAppenderUpgradeClientTest > testModuleUpgrades FAILED`
https://testray.liferay.com/home/-/testray/case_results/2320829747 - Reproduced locally

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/11080

**Pull request closed without merging**
