### PR TITLE
LPS-116086 Initialize theme display first, we reuse it in the service context creation

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by jpince** [comment]
@vicnate5 @shuyangzhou already passed testing here: https://github.com/liferay-echo/liferay-portal/pull/1311

**Comment by shuyangzhou** [comment]
@rotty3000 this is undoing your change at https://github.com/liferay/liferay-portal/commit/6bb2cb53
I could not find out what the original issue is, so having no way to verify it.

**Comment by brianchandotcom** [comment]
@jpince @rotty3000 @pavel-savinov chicken and egg https://github.com/brianchandotcom/liferay-portal/pull/77410#issuecomment-524964769

**Comment by rotty3000** [comment]
Had I added a test when @brianchandotcom asked you'd know one way or the other. but now if all remaining tests are green I feel you should do what you need to do. Sorry for putting you in the position of doubt.

**Comment by vicnate5** [comment]
@shuyangzhou 
Additional testing performed on https://github.com/shuyangzhou/liferay-portal/pull/9216

No regressions found.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou Failure are unrelated, this can be manually forwarded.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/90798

**Pull request closed without merging**
