### PR TITLE
LPS-59770 Improve database connection handling for 7.0 Upgrades

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Can this be reviewed or not?
ci:retest

**Comment by Preston-Crary** [comment]
I think so, the test that is failing was one of the ones I updated see 0ab8b92e087e6f68a5848609aa50f00378988224.  It was passing before I rebased it and I did not change it during the rebase.

**Comment by Preston-Crary** [comment]
I will investigate the test failure and resend when it's resolved.

**Comment by Preston-Crary** [comment]
There was a null pointer exception that was being swallowed, I've resent the pull here:
https://github.com/shuyangzhou/liferay-portal/pull/2038

**Pull request closed without merging**
