### PR TITLE
LPS-110474 Track all occurrences of include-and-override, assuming it can be an array spread over different files. It can be useful later as in PropsHelperUtil

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz I don't think this change is needed. You are not using the portal-developer.properties in the recommended way. It is supposed to be supplied as "external-properties" via jvm system properties, rather than modifying "include-and-override", I don't think we recommend this to be modifiable. Please confirm with doc team, if we ever documented "include-and-override" is suggested to be changed/overwrite, the PropsHelperUtil solution will need to be revised.

**Comment by shuyangzhou** [comment]
ugh, just search the public document for this, it seems in later version we switch to this "include-and-override" solution, I was not aware of it. I think we will need to try to see if there is a way to exam the properties overwriting. The point is, if some other property requires something like this in the future, we can not add another workaround per property.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz I am taking your solution, see https://github.com/brianchandotcom/liferay-portal/pull/86510, "include-and-override" is special enough to get a special treatment.

**Pull request closed without merging**
