### PR TITLE
Startup optimization 238 initial table creator latest

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
Some upgrade integration test failures should be related:
1. Below tests failed with error: `com.liferay.portal.kernel.upgrade.UpgradeException: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction`:

- [com.liferay.portal.upgrade.v7_0_0.test.UpgradeLayoutTest](https://testray.liferay.com/home/-/testray/case_results/2408245406)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4237/modules-integration-mysql57-jdk8/1/0/jenkins-console.txt.gz?authuser=0

- [com.liferay.portal.upgrade.v7_0_0.test.UpgradeResourcePermissionTest](https://testray.liferay.com/home/-/testray/case_results/2408245409)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4237/modules-integration-mysql57-jdk8/1/0/jenkins-console.txt.gz?authuser=0

2. [com.liferay.portal.upgrade.test.UpgradeCompanyIdTest](https://testray.liferay.com/home/-/testray/case_results/2408277025)
`Failed tests: classMethod, testUpgradeNullValues`
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4238/modules-integration-db2111-jdk8/0/3/jenkins-console.txt.gz?authuser=0

3. [com.liferay.portal.upgrade.test.UpgradeLogAppenderUpgradeClientTest](https://testray.liferay.com/home/-/testray/case_results/2408277353)
`Failed tests: testDatabaseTablesCounts, testGetDLStorageSizeInGb`
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4238/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

And a semantic versioning issue:
```
     [exec] > Task :apps:static:portal:portal-upgrade-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.upgrade.release                 MINOR      3.0.0      3.0.0      3.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.portal.upgrade.release.ReleasePublisher
     [exec] 		+   access     abstract
     [exec] 		+   method     publish(com.liferay.portal.kernel.model.Release,boolean)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     unpublish(com.liferay.portal.kernel.model.Release)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 13.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.upgrade.api-13.0.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.upgrade.api/13.0.1/de01acae410eb3e6c969236e9611e8a773dd5112/com.liferay.portal.upgrade.api-13.0.1.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4237/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@shuyangzhou Functional failures here

## 1 
[PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/home/-/testray/case_results/2409007926)

Steps:
1. Import [6.2 Dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip)
2. Run upgrade tool (no error during upgrade)
3. Start portal against the upgraded database

```
WARN  [SystemExecutorServiceUtil-12-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][PortalInstanceLifecycleListenerManagerImpl:195] Unable to register portal instance {"mvccVersion": 0, "companyId": 10155, "userId": 0, "userName": "", "createDate": "Tue Jun 12 00:00:00 GMT 2018", "modifiedDate": "Tue Jun 12 00:00:00 GMT 2018", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
com.liferay.portal.kernel.workflow.WorkflowException: com.liferay.portal.kernel.exception.DuplicateRoleException: Role already exists with name Account Administrator
	at com.liferay.portal.workflow.kaleo.runtime.internal.DefaultWorkflowEngineImpl.deployWorkflowDefinition(DefaultWorkflowEngineImpl.java:173) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
```
CI Log https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13891/functional-upgrade-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0


## 2

[OSGIConfiguration#CanCreateVirtualInstanceViaConfig](https://testray.liferay.com/home/-/testray/case_results/2409007586)

1. Create file in osgi/configs: `com.liferay.portal.instances.internal.configuration.PortalInstancesConfiguration~www.able.com.config`
```
mx="www.able.com"
virtualHostname="www.able.com"
```
2. Start portal

Expected Result: New virtual instance created on startup without errror

Actual Result: Startup error
```
ERROR [main][TransactionCommitCallbackUtil:37] Unable to execute transaction commit callback
java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-30815-workflow-metrics-processes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-30815-workflow-metrics-processes]]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[?:?]
```
CI log https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13891/functional-tomcat90-mysql57-chrome100-jdk8/12/12/liferay-log.txt.gz?authuser=0


## 3
Possible race, I could not reproduce locally, but happened on some of the tests:
```
Failed upgrade process for module com.liferay.journal.service
```
See log https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13892/functional-upgrade-tomcat90-postgresql144-jdk8/0/24/jenkins-console.txt.gz?authuser=0

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
OSGi config test is now passing
https://testray.liferay.com/home/-/testray/case_results/2410925781

I can still reproduce the 6.2 upgrade error, first 1 above.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@zhangyan0701 can you check the new results here when they come in, all the regressions sound now be resolved.

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
There was a regression caused many upgrade tests fail, the revert commits just got merged, so re-trigger upgrade test here.

**Comment by shuyangzhou** [comment]
@zhangyan0701 how is the new result?

**Comment by zhangyan0701** [comment]
@shuyangzhou Sorry for the delay, I have been checking the results today. There are some upgrade functional tests failed with different errors, but the errors not occurring regularly, they are not occurring on a particular database or a particular upgrade version. So more like race condition.

**Here are the errors:**
1. Some upgrade failed with error:
```
2023-08-24 17:56:55.595 INFO  [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][UpgradeProcess:136] Failed upgrade process com.liferay.dynamic.data.mapping.internal.upgrade.v5_3_3.BrowserSnifferTemplateUpgradeProcess in 53 ms
2023-08-24 17:56:55.605 ERROR [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][UpgradeStepRegistratorTracker:178] Failed upgrade process for module com.liferay.dynamic.data.mapping.service
com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.FragmentEntry' doesn't exist
```
Example failed test: [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive625](https://testray.liferay.com/home/-/testray/case_results/2412278316)
Full console log: 
https://testray.liferay.com/reports/production/logs/2023-08/test-1-31/test-portal-acceptance-pullrequest(master)/9218/functional-upgrade-tomcat90-mysql57-jdk8/2/16/jenkins-console.txt.gz?authuser=0

2. Upgrade from portal version 70106 failed with error:
```
[beanshell] 2023-08-24 17:45:11.206 ERROR [SystemExecutorServiceUtil-2-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][PortletTracker:430] Portlet com_liferay_dynamic_data_mapping_form_web_portlet_DDMFormPortlet from com.liferay.dynamic.data.mapping.form.web_4.0.149 [930] failed to initialize
[beanshell] com.liferay.portal.kernel.exception.PortalException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.ResourcePermissionImpl#1311]
```
Example failed test: [LocalFile.PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade70106](https://testray.liferay.com/home/-/testray/case_results/2412278271)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-31/test-portal-acceptance-pullrequest(master)/9218/functional-upgrade-tomcat90-mysql57-jdk8/2/5/jenkins-console.txt.gz?authuser=0

3. Some upgrade tests that from 62 version failed with error:
```
2023-08-24 18:06:31.688 INFO  [SystemExecutorServiceUtil-8-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][UpgradeProcess:136] Failed upgrade process com.liferay.journal.internal.upgrade.v4_4_3.JournalArticleLayoutClassedModelUsageUpgradeProcess in 5 ms
2023-08-24 18:06:31.692 ERROR [SystemExecutorServiceUtil-8-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][UpgradeStepRegistratorTracker:178] Failed upgrade process for module com.liferay.journal.service
com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.LayoutClassedModelUsage' doesn't exist
```
Example failed test: [LocalFile.PortalConfigurationUpgrade#ViewPortalConfigurationAfterUpgrade625](https://testray.liferay.com/home/-/testray/case_results/2412278233)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-31/test-portal-acceptance-pullrequest(master)/9218/functional-upgrade-tomcat90-mysql57-jdk8/1/9/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
@zhangyan0701 The new commits should have 1 and 3 fixed. 2 should not be related to this change.
But if 2 is becoming more frequent, I can still look into it as a separate issue. For now let's rerun to see whether 1 and 3 are fixed, and there could be more cases like 1 and 3, we need to run a few more round to expose them all.

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@kvale1733 please help me check the latest upgrade batch results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Regressions found

1) Number 2 that summer reported still happens. It fails consistently on this PR for all databases. For example
https://testray.liferay.com/home/-/testray/case_results/2412998730?tab=result



2) I saw number 3 from summer also. See https://testray.liferay.com/home/-/testray/case_results/2412998729?tab=result
Which uses this db dump:
https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.15/data-archive/data-archive-portlets-permissions-mysql.zip

I wasn't able to reproduce locally. It only failed on MySQL 5.7 and not Oracle or DB2. Which it also ran on. The test Summer saw it on passed. This looks flakey.

3) This one seemed to be present in the previous runs too but was missed. I was able to reproduce locally

Steps to reproduce:

i. Add the following to tomcat/bin/setenv.sh
```
CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.ssl=false"
```
ii. Add the following to portal-ext.properties
```
upgrade.database.auto.run=true
```
iii. Startup a clean bundle using the following command
```
ant -f modules/apps/portal/portal-upgrade-test/src/testFunctional/ant/util/build-test-upgrade-manager.xml start-app-server-check-mbean-attributes
```
iv. Check the contents of the generated mbean-attributes-output.txt file in source dir

Expected Content:
```
Type: no upgrade
Result: success
```


2.

Actual Content:
```
Type: no upgrade
Result: unresolved
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
@shuyangzhou 

1. The number 2 issue in my previous comment https://github.com/shuyangzhou/liferay-portal/pull/11186#issuecomment-1692882249 is still happening. Example test: https://testray.liferay.com/home/-/testray/case_results/2413430313
2. The number 3 issue that Kevin reported here https://github.com/shuyangzhou/liferay-portal/pull/11186#issuecomment-1694021431 is still happening.
3. UpgradeException occurs during portal startup when database partitioning is enabled or with liferay online properties.
Different tests have different errors:
```
[beanshell] 2023-08-26 17:11:23.792 ERROR [SystemExecutorServiceUtil-8-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LiferayServiceExtender:103] null
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.notification.service_1.0.60 [596] has invalid content in tables.sql:
```
Example: https://testray.liferay.com/home/-/testray/case_results/2413429938

```
[beanshell] 2023-08-26 17:09:10.448 ERROR [main][ModuleApplicationContextExtender:73] null
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.portal.tools.service.builder.test.service_1.0.0 [125] has invalid content in tables.sql:
```
Example: https://testray.liferay.com/home/-/testray/case_results/2413429870

```
[beanshell] 2023-08-26 17:11:19.458 ERROR [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LiferayServiceExtender:103] null
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.commerce.currency.service_4.0.45 [521] has invalid content in tables.sql:
```
Example: https://testray.liferay.com/home/-/testray/case_results/2413430021

```
[beanshell] 2023-08-26 17:11:41.759 ERROR [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LiferayServiceExtender:103] null
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.commerce.wish.list.service_4.0.47 [580] has invalid content in tables.sql:
```
Example: https://testray.liferay.com/home/-/testray/case_results/2413429858

```
[beanshell] 2023-08-26 17:13:28.698 ERROR [SystemExecutorServiceUtil-4-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LiferayServiceExtender:103] null
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.portal.reports.engine.console.service_8.0.42 [306] has invalid content in tables.sql:
```
Example: https://testray.liferay.com/home/-/testray/case_results/2413429867

4. Auto upgrade from 61,62,71,73 failed with errors, this happens on multiple database types.
```
[beanshell] 2023-08-26 17:34:03.620 INFO  [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LoggingTimer:74] Starting com.liferay.portal.kernel.upgrade.BasePortletIdUpgradeProcess#upgradeInstanceablePortletIds
[beanshell] 2023-08-26 17:34:03.638 WARN  [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][BasePortletIdUpgradeProcess:499] null
[beanshell] java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20099-com_liferay_template_web_internal_portlet_TemplatePortlet-' for key 'IX_A9FF4B2C'
```
OR
```
[beanshell] 2023-08-26 17:34:03.443 INFO  [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][LoggingTimer:74] Starting com.liferay.portal.kernel.upgrade.BasePortletIdUpgradeProcess#upgradeInstanceablePortletIds
[beanshell] 2023-08-26 17:34:03.467 WARN  [SystemExecutorServiceUtil-11-com.liferay.portal.spring.extender.internal.LiferayServiceExtender-BundleTrackerOpener][BasePortletIdUpgradeProcess:499] null
[beanshell] java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '20099-com_liferay_configuration_admin_web_portlet_InstanceSettin' for key 'IX_12B5E51D'
```
Some tests have both errors, some tests have one of them.

Example:
[LocalFile.PortalSmokeAutoUpgrade#ViewPortalSmokeArchiveAutoUpgrade7110](https://testray.liferay.com/home/-/testray/case_results/2413430281)

**Pull request closed without merging**
