### PR TITLE
LPS-67565

### PR DESCRIPTION
**Pull request by topolik**
Hi @shuyangzhou @dantewang,

resending https://github.com/shuyangzhou/liferay-portal/pull/8012.

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:sf

**Comment by topolik** [comment]
ci:test:tck

**Comment by shuyangzhou** [comment]
ci:test

**Comment by topolik** [comment]
Hi @dantewang, the test failed again. Please do you know where/how shoud I fix it? Can I test it locally to see where it fails? Thanks.

**Comment by dantewang** [comment]
@topolik You can search `V3RenderStateTests_SPEC1_12_RenderState_getPortletMode2` in https://github.com/liferay/portals-pluto/tree/tck3/portlet-tck_3.0 for the test code to see if you have it covered.

I'm not sure how to run it now in master but I think @stiemannkj1 may be able to help.

**Comment by stiemannkj1** [comment]
@ngriffin7a, @vicnate5 do you remember how to run the TCK locally? I haven't done it in forever.

**Comment by ngriffin7a** [comment]
@topolik You can run the Portlet 3.0 TCK locally in Liferay by doing the following:
- `git clone https://github.com/apache/portals-pluto.git`
- `mvn -P liferay clean install`
- `cp portlet-tck_3.0/V3RenderStateTests/target/*.war $LIFERAY_HOME/deploy`
- Add the V3RenderState TCK test portlets to a portal page (they are in the "undefined" category)
- Click on the button/link associated with the failing test

**Comment by vicnate5** [comment]
In case you need it, the steps to run all the automated TCK tests locally can be found on this ticket https://issues.liferay.com/browse/LPS-93469

**Comment by topolik** [comment]
Thank you guys!!! @dantewang @stiemannkj1 @ngriffin7a @vicnate5

**Comment by shuyangzhou** [comment]
@topolik please resend after your solve the problem, thanks!

**Pull request closed without merging**
