### PR TITLE
LPS-143575 Possible duplicate entries when using addOrUpdate methods

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@amosfong the relevant test did not run in the previous invocation, and there is conflict now. Please resend and rerun the tests. I have reviewed the pull, as long as it is cleared by CI, it is good to go. Thanks!

**Comment by amosfong** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/10560

**Pull request closed without merging**
