### PR TITLE
LPS-X Centralize portal release reading for better caching.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

There are many tests failed because NPE error occurred when portal connect to database.
```
[beanshell] 2023-09-02 20:49:19.867 INFO  [main][DialectDetector:144] Using dialect org.hibernate.dialect.MySQL57Dialect for MySQL 5.7
[beanshell] 2023-09-02 20:49:19.964 ERROR [main][PortalContextLoaderListener:70] null
[beanshell] java.lang.NullPointerException: null
```
Example console log: 
https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3054/functional-tomcat90-mysql57-chrome100-jdk8/0/22/jenkins-console.txt.gz?authuser=0

On CI, before starting portal, the sql scripts in `/portal-source/sql/create` folder is executed. I could reproduce the error locally with `/portal-source/sql/create/create-mysql.sql`.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
@shuyangzhou 

Issues found:

1. Test com.liferay.portal.upgrade.test.DBUpgraderTest failed with error:
`testUpgradeWithFailureDoesNotSupportRetry: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.Shard' doesn't exist`

This is happening on all database types.

Full Jenkins console on MySQL:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3085/modules-integration-mysql57-jdk8/3/17/jenkins-console.txt.gz?authuser=0

2. Functional test [LocalFile.UpgradeReport#ErrorsLogged](https://testray.liferay.com/home/-/testray/case_results/2418519194) failed.

Reproduce steps:
- Import database [dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip).
- Execute sql statement: `ALTER TABLE Release_ DROP servletContextName;`
- Add property `upgrade.report.enabled=true` into `liferay.home/tools/portal-tools-db-upgrade-client/portal-upgrade-ext.properties` file.
- Run upgrade client tool.
- Check upgrade report file `liferay.home/tools/portal-tools-db-upgrade-client/reports/upgrade_report.info`.

Result:
On master head, there is an error: `1 occurrences of the following event: Unknown column 'servletContextName' in 'where clause'`.
This error is changed to `1 occurrences of the following event: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'servletContextName' in 'where clause'` here.

If this is expected, the test will need to be updated by changing the error message to the new one, like this, https://github.com/zhangyan0701/liferay-portal/pull/546/commits/7124da7920c535b1b88610280b977c63226e91fb.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
