### PR TITLE
Lps 73562

### PR DESCRIPTION
**Pull request by mtambara**
@Preston-Crary

Found another listener that needs to check if the bundle is uninstalled. Also discovered another race condition between WebBundleInstaller and WabGenerator

### CODE REVIEW

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by mtambara** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/51202

**Pull request closed without merging**
