### PR TITLE
[TS] Added Test - LPS-116316 ServletContext.getRequestDispatcher requires that the path start with a slash

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @shuyangzhou ,

previous PR: https://github.com/shuyangzhou/liferay-portal/pull/9221

This previous PR has been committed, this PR adds a test.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
Force-pushed to rebase changes.

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
