### PR TITLE
[TS] LPS-117384

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-117384

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 I think this is not related, but please double check, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Not related. Pulled this test.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91547

**Pull request closed without merging**
