### PR TITLE
[Bug Fix]LPS-83505

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is a fix pack release blocker, and I did not find a better way to fix without changing the interface.

I will add unit test for it later.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian is the sybase test failure real?

**Comment by tinatian** [comment]
I don’t think so, tthe test process blocked,tests don’t run at all, we can run one more time to verify

**Comment by tinatian** [comment]
ci:test

**Comment by jpince** [comment]
@shuyangzhou 2nd run looks fine, and Tina's fix also passed all sybase + workflow tests in my branch, see https://github.com/jpince/liferay-portal/pull/60#issuecomment-406447642

**Comment by shuyangzhou** [comment]
@tinatian will resend without major version bump

**Pull request closed without merging**
