### PR TITLE
Update last login

### PR DESCRIPTION
**Pull request by shuyangzhou**
x

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@victorhcunha please run a check for login case.

Pay attention to tomcat output, to make sure no errors. And compare ES/DB cpu/network usages difference.

**Comment by vicnate5** [comment]
ci:test:users

**Comment by vicnate5** [comment]
ci:report:79761706

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
In the first round I got a lot of errors like this in the portal log:

```
05-Sep-2024 14:41:46.490 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [23893] milliseconds
2024-09-05 14:49:48.615 ERROR [http-nio-8080-exec-55][UserLocalServiceImpl:1512] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.UserImpl#28903]
com.liferay.portal.kernel.dao.orm.ORMException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.UserImpl#28903]
	at com.liferay.portal.dao.orm.hibernate.ExceptionTranslator.translate(ExceptionTranslator.java:30) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.orm.hibernate.SessionImpl.apply(SessionImpl.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.lambda$null$3(UserLocalServiceImpl.java:1500) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:71) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:30) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:19) ~[portal-kernel.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.lambda$afterPropertiesSet$4(UserLocalServiceImpl.java:1492) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.util.BatchProcessor._flush(BatchProcessor.java:90) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.BatchProcessor.add(BatchProcessor.java:42) [portal-kernel.jar:?]
	at com.liferay.portal.service.impl.UserLocalServiceImpl.updateLastLogin(UserLocalServiceImpl.java:5008) [portal-impl.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor2462.invoke(Unknown Source) ~[?:?]
```

I put this result in the [spreadsheet](https://docs.google.com/spreadsheets/d/1e_Wu1Idijn2mWAx7Rp_IH2URFjrzinq9I1pdRygsLV4/edit?gid=0#gid=0), but I will run it again to see if the error messages remain.

**Comment by victorhcunha** [comment]
I got these error messages when trying to rebuilt db for the login test case using this PR:

```
2024-09-05 18:22:46.288 ERROR [com.liferay.users.admin.internal.search.UserLastLoginDateCallback-1][BulkDocumentRequestExecutorImpl:48] failure in bulk execution:_[0]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_371], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_371]: document missing]]]_[1]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_351], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_351]: document missing]]]_[2]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_373], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_373]: document missing]]]_[3]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_331], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_331]: document missing]]]_[4]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_353], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_353]: document missing]]]_[5]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_375], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_375]: document missing]]]_[6]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_311], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_311]: document missing]]]_[7]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_333], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_333]: document missing]]]_[8]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_355], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_355]: document missing]]]_[9]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_377], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_377]: document missing]]]_[10]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_313], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_313]: document missing]]]_[11]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_335], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_335]: document missing]]]_[12]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_357], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_357]: document missing]]]_[13]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_337], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_337]: document missing]]]_[14]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_315], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_315]: document missing]]]_[15]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_359], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_359]: document missing]]]_[16]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_317], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_317]: document missing]]]_[17]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_339], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_339]: document missing]]]_[18]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_319], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_319]: document missing]]]_[19]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_361], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_361]: document missing]]]_[20]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_341], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_341]: document missing]]]_[21]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_363], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_363]: document missing]]]_[22]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_321], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_321]: document missing]]]_[23]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_343], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_343]: document missing]]]_[24]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_365], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_365]: document missing]]]_[25]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_301], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_301]: document missing]]]_[26]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_323], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_323]: document missing]]]_[27]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_345], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_345]: document missing]]]_[28]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_367], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_367]: document missing]]]_[29]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_325], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_325]: document missing]]]_[30]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_303], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_303]: document missing]]]_[31]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_347], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_347]: document missing]]]_[32]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_369], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_369]: document missing]]]_[33]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_327], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_327]: document missing]]]_[34]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_305], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_305]: document missing]]]_[35]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_349], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_349]: document missing]]]_[36]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_329], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_329]: document missing]]]_[37]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_307], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_307]: document missing]]]_[38]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_309], message [[liferay-253/ranBxJJ-SsazK38j3qJmbA][[liferay-253][0]] ElasticsearchException[Elasticsearch exception [type=document_missing_exception, reason=[_doc][com.liferay.portal.kernel.model.User_PORTLET_309]: document missing]]] [Sanitized]
2024-09-05 18:22:46.289 ERROR [com.liferay.users.admin.internal.search.UserLastLoginDateCallback-1][ElasticsearchIndexWriter:311] Bulk partial update failed
```

I uploaded the result zip file [here](https://drive.google.com/file/d/1wE3Govll8Xk5EaS2EtQgz7XJDMhuvyIH/view?usp=sharing)

**Comment by shuyangzhou** [comment]
I have to table this change. Elasticsearch is lacking the support of only doing partial document update if it exists. As a result, the batched partial updates will see "document_missing_exception" upon flushing if the documents were deleted before the flushing. It is functionally fine, as those "delayed" partial updates are no longer needed anyway (since the original doc is gone), but it is not acceptable to have this large amount of error log.

I think it is possible to do this type of "partial update if exist" by painless script, but the script content needs to be dynamically generated based on incoming partial document, this is going to be quite painful to do.

@vicnate5 based on the current test results, if we do this right, even a 10% of improvement for login case is possible. 

Can you find out the use cases of update last login for search? If we can find other way to support the use case, we may still gain this improvement without dealing with the painful "painless" script.

**Comment by vicnate5** [comment]
@shuyangzhou Ticket to use for this https://liferay.atlassian.net/browse/LPD-36010

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:users

**Comment by shuyangzhou** [comment]
ci:report:10839618

**Comment by shuyangzhou** [comment]
ci:report:10866992

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results.

@victorhcunha please rerun the previous performance test.

Also there is a newer version at https://github.com/shuyangzhou/liferay-portal/pull/11631 which should have better search indexing performance. We need to check both pulls to compare the difference.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
On the first run of the login test case on this pr, I got several error messages like this in the portal:
```
2024-09-13 12:25:36.190 ERROR [http-nio-8080-exec-1][MainServlet:524] org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [ctx._source.lastLoginDate="20240904235437";ctx._source.lastLoginDate_sortable=1725494077595L;ctx._source.modified="20240904235437";ctx._source.modified_sortable=1725494077533L] using lang [painless]]]; nested: ElasticsearchException[Elasticsearch exception [type=circuit_breaking_exception, reason=[script] Too many dynamic script compilations within, max: [150/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]];
java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [ctx._source.lastLoginDate="20240904235437";ctx._source.lastLoginDate_sortable=1725494077595L;ctx._source.modified="20240904235437";ctx._source.modified_sortable=1725494077533L] using lang [painless]]]; nested: ElasticsearchException[Elasticsearch exception [type=circuit_breaking_exception, reason=[script] Too many dynamic script compilations within, max: [150/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]];
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.updateByQuery(RestHighLevelClient.java:708) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.document.UpdateByQueryDocumentRequestExecutorImpl.getBulkByScrollResponse(UpdateByQueryDocumentRequestExecutorImpl.java:131) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.document.UpdateByQueryDocumentRequestExecutorImpl.execute(UpdateByQueryDocumentRequestExecutorImpl.java:46) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.document.ElasticsearchDocumentRequestExecutor.executeDocumentRequest(ElasticsearchDocumentRequestExecutor.java:77) ~[?:?]
	at com.liferay.portal.search.engine.adapter.document.UpdateByQueryDocumentRequest.accept(UpdateByQueryDocumentRequest.java:53) ~[?:?]
	at com.liferay.portal.search.engine.adapter.document.UpdateByQueryDocumentRequest.accept(UpdateByQueryDocumentRequest.java:16) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:72) ~[?:?]
	at com.liferay.users.admin.internal.search.UserLastLoginDateCallback._flush(UserLastLoginDateCallback.java:100) ~[?:?]
	at com.liferay.portal.kernel.util.BatchProcessor._flush(BatchProcessor.java:90) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.BatchProcessor.add(BatchProcessor.java:42) ~[portal-kernel.jar:?]
	at com.liferay.users.admin.internal.search.UserLastLoginDateCallback.reindex(UserLastLoginDateCallback.java:56) ~[?:?]
	at com.liferay.portal.search.IndexableAdvice._reindex(IndexableAdvice.java:175) ~[portal-impl.jar:?]
	at com.liferay.portal.search.IndexableAdvice.afterReturning(IndexableAdvice.java:98) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:57) ~[portal-kernel.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy106.updateLastLogin(Unknown Source) ~[?:?]
```


I uploaded the [spreadsheet](https://docs.google.com/spreadsheets/d/1e_Wu1Idijn2mWAx7Rp_IH2URFjrzinq9I1pdRygsLV4/edit?gid=250738277#gid=250738277) with the results and files.
The Login test case on the PR2 is current in progress.

**Comment by shuyangzhou** [comment]
ok, I did not know ES has a meter/limit for script compilation rate. I will have to store the compiled script on the server ahead of time. PR2 should have the same issue, but let's see whether the bulk request is making it less severe.

**Comment by victorhcunha** [comment]
For PR2 I received several error messages like these:
```
2024-09-13 13:30:18.155 ERROR [http-nio-8080-exec-41][BulkDocumentRequestExecutorImpl:48] failure in bulk execution:_[151]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_145123], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to execute script]]; nested: ElasticsearchException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [if (ctx._source.uid == null) {ctx.op = "noop"} else {ctx._source.lastLoginDate="20240904235408";ctx._source.lastLoginDate_sortable=1725494048430L;ctx._source.modified="20240904235408";ctx._source.modified_sortable=1725494048351L}] using lang [painless]]]; nested: ElasticsearchException[Elasticsearch exception [type=circuit_breaking_exception, reason=[script] Too many dynamic script compilations within, max: [150/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]];]_[152]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_106311], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to execute script]]; nested: ElasticsearchException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [if (ctx._source.uid == null) {ctx.op = "noop"} else {ctx._source.lastLoginDate="20240904235256";ctx._source.lastLoginDate_sortable=1725493976325L;ctx._source.modified="20240904235256";ctx._source.modified_sortable=1725493976239L}] using lang [painless]]]; nested: ElasticsearchException[Elasticsearch exception [type=circuit_breaking_exception, reason=[script] Too many dynamic script compilations within, max: [150/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]];]_[153]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_141525], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to execute script]]; nested: ElasticsearchException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [if (ctx._source.uid == null) {ctx.op = "noop"} else {ctx._source.lastLoginDate="20240904235401";ctx._source.lastLoginDate_sortable=1725494041961L;ctx._source.modified="20240904235401";ctx._source.modified_sortable=1725494041875L}] using lang [painless]]]; nested: ElasticsearchException[Elasticsearch exception [type=circuit_breaking_exception, reason=[script] Too many dynamic script compilations within, max: [150/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting]];]_[154]: index [liferay-253], type [_doc], id [com.liferay.portal.kernel.model.User_PORTLET_34447], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to execute script]]; nested: ElasticsearchException[Elasticsearch exception [type=general_script_exception, reason=Failed to compile inline script [if (ctx._source.uid == null) {ctx.op = "noop"} else {ctx._source.lastLoginDate="20240904235026";ctx._source.
```
I uploaded the spreadsheet with the results

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/11634

**Pull request closed without merging**
