### PR TITLE
LRQA-69213 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-137110

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Ran failing integration test locally
> Task :test:module-configuration-localization-test:testIntegration

com.liferay.module.configuration.localization.test.ModuleConfigurationLocalizationTest > testConfigurationLocalization STARTED

com.liferay.module.configuration.localization.test.ModuleConfigurationLocalizationTest > testConfigurationLocalization PASSED

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105402

**Pull request closed without merging**
