### PR TITLE
LPS-72541 Support env vars configuration

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Follow up conversation: https://github.com/shuyangzhou/liferay-portal/pull/4268

**Comment by shuyangzhou** [comment]
@mdelapenya see my last comment at https://github.com/shuyangzhou/liferay-portal/pull/4268#issuecomment-301834668

We should not have the layered _configurationModifiedCache, _configurationEnvironmentCache and _componentConfiguration. Every overwrite should be saved into the ComponentProperties.

**Comment by mdelapenya** [comment]
But the _componentConfiguration was already present. We have been using it for years. Do you want me to remove it?

**Comment by shuyangzhou** [comment]
@mdelapenya no, I meant to save every override into _componentConfiguration, rather than adding the _configurationModifiedCache and _configurationEnvironmentCache

**Pull request closed without merging**
