### PR TITLE
Startup optimization 306 lazy aop service

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results once they are in, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found. 

Steps to reproduce: 
1. Startup with "initial.system.check.enabled=true" in portal-ext
2. Login
3. Shutdown
4. Startup again (don't delete anything)

Results: Unsatisfied references at startup
```
 [waitfor] 2023-10-16 21:29:53.941 INFO  [main][DependencyManagerSyncUtil:36] Available checkers: [Declarative Service Unsatisfied Component System Checker, Spring Extender Unavailable Component System Checker, Pending Upgrade System Checker, Declarative Service Soft Circular Dependency System Checker]
     [exec]       [waitfor] 2023-10-16 21:29:53.942 INFO  [main][DependencyManagerSyncUtil:62] Running "Declarative Service Unsatisfied Component System Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
     [exec]       [waitfor] 2023-10-16 21:30:05.980 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component System Checker check result: 
     [exec]       [waitfor] Bundle {id: 92, name: com.liferay.portal.workflow.kaleo.designer.web, version: 5.0.118}
     [exec]       [waitfor] 	Declarative Service {id: 6955, name: com.liferay.portal.workflow.kaleo.designer.web.internal.verify.KaleoDesignerWebVerifyProcess, unsatisfied references: 
     [exec]       [waitfor] 		{name: _kaleoDefinitionVersionLocalService, target: null}
     [exec]       [waitfor] 	}
     [exec]       [waitfor] 	Declarative Service {id: 6954, name: com.liferay.portal.workflow.kaleo.designer.web.internal.upgrade.registry.KaleoDesignerWebUpgradeStepRegistrator, unsatisfied references: 
     [exec]       [waitfor] 		{name: _kaleoDefinitionLocalService, target: null}
     [exec]       [waitfor] 		{name: _kaleoDefinitionVersionLocalService, target: null}
     [exec]       [waitfor] 	}
     [exec]       [waitfor] 	Declarative Service {id: 6946, name: com.liferay.portal.workflow.kaleo.designer.web.internal.portlet.action.UnpublishKaleoDefinitionVersionMVCActionCommand, unsatisfied references: 
     [exec]       [waitfor] 		{name: kaleoDefinitionVersionLocalService, target: null}
     [exec]       [waitfor] 		{name: workflowDefinitionManager, target: null}
     [exec]       [waitfor] 	}
     [exec]       [waitfor] 	Declarative Service {id: 6941, name: com.liferay.portal.workflow.kaleo.designer.web.internal.portlet.KaleoDesignerPortlet, unsatisfied references: 
     [exec]       [waitfor] 		{name: _kaleoDefinitionVersionLocalService, target: null}
     [exec]       [waitfor] 	}
     [exec]       [waitfor] 	Declarative Service {id: 6939, name: com.liferay.portal.workflow.kaleo.designer.web.internal.application.list.KaleoDesignerPanelApp, unsatisfied references: 
     [exec]       [waitfor] 		{name: _portlet, target: (javax.portlet.name=com_liferay_portal_workflow_kaleo_designer_web_portlet_KaleoDesignerPortlet)}
     [exec]       [waitfor] 	}
     [exec]       [waitfor] 	Declarative Service {id: 6952, name: com.liferay.portal.workflow.kaleo.designer.web
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-37/test-portal-acceptance-pullrequest(master)/15021/functional-tomcat90-mysql57-jdk8/2/3/jenkins-console.txt.gz?authuser=0)
 
 
 I still checked service builder on backwards compatibility and found now issues on 7.0-7.3

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@shuyangzhou 

The relevant keeps running, seems CI is stuck.

But I manually tests the regression that found by Kevin,  and I could still reproduce it locally. The issue also failed a functional test: [LocalFile.DatabasePartitioning#NewCompanyStillAccessibleAfterRestart](https://testray.liferay.com/home/-/testray/case_results/2442183537).

Here is the full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-37/test-portal-acceptance-pullrequest(master)/15024/functional-tomcat90-mysql57-jdk8/1/7/jenkins-console.txt.gz?authuser=0

**Comment by zhangyan0701** [comment]
New issues found from relevant tests:

1. Some integration tests failed with error:
`java.lang.NoSuchFieldException: No field on null with name _service`

Example test:
[com.liferay.dynamic.data.mapping.util.FieldsToDDMFormValuesConverterTest](https://testray.liferay.com/home/-/testray/case_results/2442196319)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7926/modules-unit-jdk8/0/6/jenkins-console.txt.gz?authuser=0

[com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest](https://testray.liferay.com/home/-/testray/case_results/2442196575)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7926/modules-unit-jdk8/0/6/jenkins-console.txt.gz?authuser=0

2. Test [com.liferay.portal.aop.test.AopServiceManagerTest](https://testray.liferay.com/home/-/testray/case_results/2442195383) failed:

```
[beanshell]      [exec] com.liferay.portal.aop.test.AopServiceManagerTest > testAopServiceFactory FAILED
[beanshell]      [exec]     java.lang.AssertionError: expected not same
```
```
[beanshell]      [exec] com.liferay.portal.aop.test.AopServiceManagerTest > testInvalidAopServiceFactory FAILED
[beanshell]      [exec]     java.lang.AssertionError: Thread Thread[Framework Event Dispatcher: Equinox Container: 6d649baa-866e-4fb7-91e5-59a2c2974865,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.Events.Framework, message=FrameworkEvent ERROR
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/11271

**Pull request closed without merging**
