### PR TITLE
Startup optimization 269 initial request sync util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. Just a semver issue

```
  [exec] > Task :apps:portal:portal-instance-lifecycle-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.instance.lifecycle              MINOR      3.0.0      3.0.0      3.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.portal.instance.lifecycle.InitialRequestPortalInstanceLifecycleListener
     [exec] 		+   access     abstract
     [exec] 		+   extends    com.liferay.portal.instance.lifecycle.BasePortalInstanceLifecycleListener
     [exec] 		+   implements com.liferay.portal.instance.lifecycle.PortalInstanceLifecycleListener
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     activate(org.osgi.framework.BundleContext)
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     doPortalInstanceRegistered(long)
     [exec] 			+   access     abstract
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     getClassLoader()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.ClassLoader
     [exec] 		+   method     getLastModifiedTime()
     [exec] 			+   return     long
     [exec] 		+   method     getName()
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     portalInstancePreregistered(com.liferay.portal.kernel.model.Company)
     [exec] 			+   return     void
     [exec] 		+   method     portalInstancePreunregistered(com.liferay.portal.kernel.model.Company)
     [exec] 			+   return     void
     [exec] 		+   method     portalInstanceRegistered(com.liferay.portal.kernel.model.Company)
     [exec] 			+   return     void
     [exec] 		+   method     portalInstanceUnregistered(com.liferay.portal.kernel.model.Company)
     [exec] 			+   return     void
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 5.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.instance.lifecycle.api-5.0.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.instance.lifecycle.api/5.0.1/51eebd6c1386047cdb78fecb0991208873b42a75/com.liferay.portal.instance.lifecycle.api-5.0.1.jar
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-34/test-portal-acceptance-pullrequest(master)/4534/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138954

**Pull request closed without merging**
