### PR TITLE
LPS-99075 Add proxy path to latest path

### PR DESCRIPTION
**Pull request by martamedio**
Hey @shuyangzhou 👋 

We need your help, we've reviewing this issue related to proxies configuration during login: https://issues.liferay.com/browse/LPS-99075

When the user signs in the process that is followed during the login ends up [recovering the main path of the Portal and launches the redirection](https://github.com/liferay/liferay-portal/blob/master/modules/apps/login/login-web/src/main/java/com/liferay/login/web/internal/portlet/action/LoginMVCActionCommand.java#L244), in this specific case to `/liferay/c` (_/PROXY_PATH/MainServlet_)

The problem we have detected is that, when the [GET request to MainServlet](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/internal/servlet/MainServlet.java#L202) is processed, t[he lastPath is recovered](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/struts/PortalRequestProcessor.java#L144) and it is not taking into account the proxy path that can be configured in the portal.

We don't think it's directly related to the _LoginPortlet_, it seems a problem related to the recovery of the last path. (I think) I've added the [necessary change that fixes this issue](https://github.com/shuyangzhou/liferay-portal/pull/8092/commits/482ede7da9d9692de2f215e9f3d01322a458321c), but as it's a core infra component, we'd like you to check that we're doing it correctly.

Thank you!

cc/ @csierra

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@tinatian can you look into this, thanks!

**Comment by tinatian** [comment]
OK, I will

**Comment by tinatian** [comment]
Hi @martamedio ,
Please see https://github.com/martamedio/liferay-portal/pull/97, it should be a regression bug caused by some change earlier, could you please verify if it works? 

Thanks.
Tina.

**Comment by martamedio** [comment]
Thanks! See: https://github.com/brianchandotcom/liferay-portal/pull/76674

**Pull request closed without merging**
