### PR TITLE
LPS-116452 Do path check shortcut before XStream serialization, witho…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ut this we were acutally serializing many duplcated objects.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:staging

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull once it is done. If good, please forward, thanks!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
could unique failures here, need to test locally.

**Comment by vicnate5** [comment]
Tests passing on local re-run

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
