### PR TITLE
LPS-110482

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please take a look at the failing test, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou See log https://testray.liferay.com/reports/production/logs/test-1-23/1585241683034/test-portal-acceptance-pullrequest%28master%29/5725/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz

IndexNotFound again, this was run against master hash `e4a8566ba9add6f6093029581845d16c831b6934`

**Comment by shuyangzhou** [comment]
@vicnate5 the line number shows this is without my fix from yesterday. Is Brian's origin still not merged to upstream yet?

**Comment by vicnate5** [comment]
Brian's origin has 128 commits pending to sync. It has been blocked since 4:30pm yesterday.

**Comment by stian-sigvartsen** [comment]
@Preston-Crary As I mentioned before I was going to raise a follow-up regression ticket for this, but maybe this new test I have now created is useful in this broader review. This test passes on 7.1.x . i.e. prior to LPS-96525.

Please see Preston-Crary/liferay-portal/pull/1003

/cc @shuyangzhou

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
