### PR TITLE
LPS-122025 Store SegmentsIds in the Session Cache

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

We have executed the SignIn performance test with 100 segments, and the result shows a very important regression, you can check the result in the table below:

| Portal Version |Git Id | Session Count | Mean Time of Login | Portal CPU Usage (%) | DB CPU Usage (%) | Session count changes(%) |
|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|BaseLine|e1efdfd9|39050|262|96,96,96|0,0,0| |
|Segment(100 segments)|e1efdfd9|1936|34200|60,60,60|28,28,28| -95.04225352 |

You can find the full results [here](https://docs.google.com/spreadsheets/d/163CDSA1SIyLgdcKCBJvSHe5PhEDWt7iyHdu9p-FMsos/edit?usp=sharing)

Also, you can download the profile from [here](https://drive.google.com/drive/folders/1-5uMisKcmk7DIT3dr1KHWMYZWOw31UZG?usp=sharing).

**Proposed solution**

Cache the segmentsEntryIds in the user session, so we won't recalculate the segments over and over again. 

After providing this solution, we still have a really big regression, but the meantime has significantly decreased

| Portal Version |Git Id | Session Count | Mean Time of Login | Portal CPU Usage (%) | DB CPU Usage (%) | Session count changes(%) |
|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|BaseLine|e1efdfd9|39050|262|96,96,96|0,0,0| |
|Segment(100 segments)|e1efdfd9|1936|34200|60,60,60|28,28,28| -95.04225352 |
|Segment(100 segments)|e1efdfd9|3463|246|49,49,49|25,25,25| -91.1318822 |

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relervant

**Comment by cgoncas** [comment]
Hey @shuyangzhou!!

If you have some time, we will love that you take a look into this pull.

Thanks!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@cgoncas https://github.com/shuyangzhou/liferay-portal/pull/9496 should significantly improve the performance in this case. Please wait until it is merged to rerun the test.
But on top of that, don't use stream, especially not parallel stream, that will only make things worse here. The primary problem here is throughput, not individual request's response time. Using parallel stream hurts throughput a lot. The root problem is the ridiculous amount of db hit for Group table querying. We must eliminate that first, then test again to see whether there is anything else you need to work on to improve. Hold off on the cache too, not until we see the new result, we don't really know what is really needed.

@slnn please watch out for that pull, and rerun this test, the db activity should go back to normal after warm up, if not, we will have to re-exam and deal with that first. Please provide that info to @cgoncas once you have it.

**Comment by cgoncas** [comment]
Hey @shuyangzhou and @slnn.

In master we have mitigated the group query problem with the pull https://github.com/brianchandotcom/liferay-portal/pull/94915#event-3862191509:

With both (this pull and https://github.com/brianchandotcom/liferay-portal/pull/94915) solutions our main problem is still the query:

`SELECT segmentsen0_.segmentsEntryRelId AS segments1_572_, segmentsen0_.mvccVersion AS mvccVers2_572_, segmentsen0_.ctCollectionId AS ctCollec3_572_, segmentsen0_.groupId AS groupId572_, segmentsen0_.companyId AS companyId572_, segmentsen0_.userId AS userId572_, segmentsen0_.userName AS userName572_, segmentsen0_.createDate AS createDate572_, segmentsen0_.modifiedDate AS modified9_572_, segmentsen0_.segmentsEntryId AS segment10_572_, segmentsen0_.classNameId AS classNa11_572_, segmentsen0_.classPK AS classPK572_ FROM SegmentsEntryRel segmentsen0_ WHERE (segmentsen0_.segmentsEntryId = ?) AND (segmentsen0_.classNameId = ?) AND (segmentsen0_.classPK = ?) AND segmentsen0_.ctCollectionId = 0 <Open> 103 3 31
`

The performance tests results are:


| Portal Version |Git Id | Session Count | Mean Time of Login | Portal CPU Usage (%) | DB CPU Usage (%) | Session count changes(%) |
|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|BaseLine|e1efdfd9|39050|262|96,96,96|0,0,0| |
|Segment(100 segments)|e1efdfd9|1936|34200|60,60,60|28,28,28| -95.04225352 |
|Segment(100 segments)|e1efdfd9|6740|220|31,35,35|21,25,24| -82.74007682 |

You can find the result [here](https://docs.google.com/spreadsheets/d/163CDSA1SIyLgdcKCBJvSHe5PhEDWt7iyHdu9p-FMsos/edit) (test 10).

You can find the profile [here](https://drive.google.com/drive/folders/1-5uMisKcmk7DIT3dr1KHWMYZWOw31UZG?usp=sharing).

Thank you very much for the review :).

**Comment by shuyangzhou** [comment]
@cgoncas have you looked into why there are so many this SegmentsEntryRel queries? It is a plain persistence query, it is cache enabled, after warmup it should not constantly hit db.
What's your expected cache retain size for this query? Is it very large? Please provide an estimated cache entry count after fully warmed up based on your example data set.
@slnn I assume you did not tweak the cache size for this query, right? If so, base @cgoncas 's estimation tune the cache then rerun this test.

The first goal is, with proper settings, after warmup we should retain the near zero db activities for login test case. This can not change, login is too important to be sacrificed.
After this, base on whether you are happy with the result, we decide what to do next.

**Comment by slnn** [comment]
Hi @shuyangzhou 

For all of the tests about segments, I did not make any changes about the cache size, I used the configs for daily monitor performance tests. I will rerun test with this pull base @cgoncas 's estimation tune the cache

Lily

**Comment by cgoncas** [comment]
Hey @shuyangzhou @slnn !!

Sorry, Monday was a Spanish National Holiday.

We have so many SegmentsEntryRel queries because, without the SessionCache, the parameter SegmentsWebKeys.SEGMENTS_ENTRY_IDS is set in every HttpServletRequest (we run the code in the com.liferay.segments.internal.events.SegmentsServicePreAction and the com.liferay.segments.internal.security.permission.contributor.SegmentsEntryRoleContributor)

Screenshot 2020-10-14 at 12 56 19

Avoiding the Group query makes things go really good, but without the cache, the average time is still really big.

Thanks!!

**Pull request closed without merging**
