### PR TITLE
LPS-X Defer ServiceTracker opening until DesiredItemSelectorReturnTyp…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…esJSONDeserializerTransformer is needed

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
Some tests failed with NPE error like below:
```
	java.lang.NullPointerException
		at com.liferay.item.selector.web.internal.util.ItemSelectorCriterionSerializerImpl._createDesiredItemSelectorReturnTypesJSONDeserializerTransformer(ItemSelectorCriterionSerializerImpl.java:154)
		at com.liferay.petra.concurrent.DCLSingleton.getSingleton(DCLSingleton.java:39)
		at com.liferay.item.selector.web.internal.util.ItemSelectorCriterionSerializerImpl.deserialize(ItemSelectorCriterionSerializerImpl.java:66)
```
Failed tests:
[com.liferay.item.selector.web.internal.ItemSelectorImplTest](https://testray.liferay.com/home/-/testray/case_results/2453016591)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7140/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

[com.liferay.item.selector.web.internal.util.ItemSelectorCriterionSerializerImplTest](https://testray.liferay.com/home/-/testray/case_results/2453016595)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7140/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:item-selector

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143404

**Pull request closed without merging**
