### PR TITLE
Startup optimization 238 initial table creator new

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Lots of integration tests failures here with
```
     [exec] com.liferay.portal.dao.db.test.DBTest > classMethod FAILED
     [exec]     java.lang.UnsupportedOperationException
     [exec]     	at com.liferay.portal.kernel.service.PersistedModelLocalService.getBasePersistence(PersistedModelLocalService.java:44)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
     [exec]     	at com.sun.proxy.$Proxy907.getBasePersistence(Unknown Source)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:871)
     [exec]     	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:710)
     [exec]     	at com.sun.proxy.$Proxy1049.getBasePersistence(Unknown Source)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil._getBasePersistence(DataGuardTestRuleUtil.java:519)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil._captureDataMap(DataGuardTestRuleUtil.java:414)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRuleUtil.beforeClass(DataGuardTestRuleUtil.java:132)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:67)
     [exec]     	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.beforeClass(DataGuardTestRule.java:22)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:54)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```
But I cannot reproduce locally, even with the same test groupings. [Example log ](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11601/modules-integration-oracle193-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by vicnate5** [comment]
Will watch https://github.com/shuyangzhou/liferay-portal/pull/11067 now

**Pull request closed without merging**
