### PR TITLE
Ant removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou One unique test failure: https://testray.liferay.com/home/-/testray/case_results/1590276940. Also occured on https://github.com/shuyangzhou/liferay-portal/pull/10486

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! Looking into it now

**Pull request closed without merging**
