### PR TITLE
[TS] LPS-129450

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @shuyangzhou ,

Can you help review this fix?

**Notes from @nikolettabuza**
> this is the new PR for [LPS-129450](https://issues.liferay.com/browse/LPS-129450).
> 
> There are two commits to run the relevant tests successfully.
> 
> The changes include the fix for Bug 562440: https://github.com/eclipse/rt.equinox.bundles/commit/81083c1d65abe31c8c5ec8fe866ebee96980a84d
> 
> The `org.eclipse.equinox.http.servlet` library was generated from https://github.com/rotty3000/rt.equinox.bundles/commit/5a0a668bc0ae5bf879d799c6eaa443cbf0a83055 to include all necessary commits.
> 
> Thanks,
> N

For additional details regarding the usage of the commit hash instead of pull, please see: [LPS-129450#comment-2458271](https://issues.liferay.com/browse/LPS-129450?focusedCommentId=2458271&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2458271)

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@ericyanLr and @nikolettabuza for some history reasons that we were not making third-party patch modules for this. But considering how many commits this has diverged from the baseline, this approach is not maintainable anymore. Can you create a third-party module for it, and dump all diverged commits as patches?

**Comment by nikolettabuza** [comment]
Hi @shuyangzhou,
considering that this issue is high priority and has been delayed for a while now, is it possible to merge it to provide the fix first and take care of other issues separately?
Thank you

**Comment by shuyangzhou** [comment]
@nikolettabuza It can not be merged like this. If you need to push it, the jars needs to be uploaded by @CAustin582 , I don't have permission to do it.

**Comment by nikolettabuza** [comment]
@shuyangzhou,
I followed this pattern:
https://github.com/brianchandotcom/liferay-portal/pull/87202

As I saw in that case, the PR was simply forwarded. The commit with the `TEMPORARY` label was dropped (https://github.com/brianchandotcom/liferay-portal/compare/afcb92c2e1...1d7cee184c) and the .jar files uploaded.

**Comment by shuyangzhou** [comment]
Please send the jars to @CAustin582 to upload, once uploaded he will give a coordinate to use for the dependency.

**Comment by shuyangzhou** [comment]
@ericyanLr @nikolettabuza any update on this?
Please either send the jars to @CAustin582 for uploading or convert this to 3rd party patch.

**Comment by CAustin582** [comment]
@shuyangzhou The jars should now be available from our public Nexus repository group

**Comment by shuyangzhou** [comment]
Thanks @CAustin582 !
@nikolettabuza please resend with proper dependency.

**Pull request closed without merging**
