### PR TITLE
[Bug] LPS-86410

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
cc @jkappler @jonathanmccann

**Comment by shuyangzhou** [comment]
@tinatian on this commit https://github.com/shuyangzhou/liferay-portal/pull/7009/commits/b4bfb5e81edd5da1db46b79074bfe4da728a3465 , without the fix, the new test is still passing. Please recheck.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64835

**Pull request closed without merging**
