### PR TITLE
[Bug Fix]LPS-137857

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
@vicnate5 Are the failures real?

Tina

**Comment by vicnate5** [comment]
@tinatian The failures are unrelated. I fixed the tests and ran them all locally against this change and all tests passed. Will push the test fixes to avoid this problem next time.

**Comment by shuyangzhou** [comment]
Merged on the release repo side.

**Pull request closed without merging**
