### PR TITLE
Bndlib 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Not sure if matters but there's already a [Version](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/plugin/Version.java) class.

**Comment by shuyangzhou** [comment]
I know, it is a very buggy class. I am trying to avoid it.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Pull request closed without merging**
