### PR TITLE
Commons chain removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by vicnate5** [comment]
@koor4356 Can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@shuyangzhou 
They are warnings and errors occurring on DB 11.1. I am not sure if it is related to this PR. Can you take a look? If this is not related, then the PR is good to go. Thanks!

**Warning**
`WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELD, DRIVER=4.24.92: create index IX_5378BAAD on DDMField (companyId, fieldType, ctCollectionId);
     [java] 2022-01-06 22:30:21.920 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_582EBFF1 on DDMField (storageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.923 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELD, DRIVER=4.24.92: create index IX_582EBFF1 on DDMField (storageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.923 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create unique index IX_1BB20E75 on DDMField (storageId, instanceId, ctCollectionId);
     [java] 2022-01-06 22:30:21.926 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELD, DRIVER=4.24.92: create unique index IX_1BB20E75 on DDMField (storageId, instanceId, ctCollectionId);
     [java] 2022-01-06 22:30:21.926 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_5C0B8AE5 on DDMField (structureVersionId, ctCollectionId);
     [java] 2022-01-06 22:30:21.929 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELD, DRIVER=4.24.92: create index IX_5C0B8AE5 on DDMField (structureVersionId, ctCollectionId);
     [java] 2022-01-06 22:30:21.929 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_52703248 on DDMFieldAttribute (attributeName, smallAttributeValue, ctCollectionId);
     [java] 2022-01-06 22:30:21.932 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELDATTRIBUTE, DRIVER=4.24.92: create index IX_52703248 on DDMFieldAttribute (attributeName, smallAttributeValue, ctCollectionId);
     [java] 2022-01-06 22:30:21.933 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create unique index IX_22EEBF0C on DDMFieldAttribute (fieldId, attributeName, languageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.935 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELDATTRIBUTE, DRIVER=4.24.92: create unique index IX_22EEBF0C on DDMFieldAttribute (fieldId, attributeName, languageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.936 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_EC62446F on DDMFieldAttribute (storageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.939 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELDATTRIBUTE, DRIVER=4.24.92: create index IX_EC62446F on DDMFieldAttribute (storageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.939 INFO  [Portal Dependency Manager Component Executor--1][BaseDB:102] create index IX_1E90C536 on DDMFieldAttribute (storageId, languageId, ctCollectionId);
     [java] 2022-01-06 22:30:21.943 WARN  [Portal Dependency Manager Component Executor--1][BaseDB:110] DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.DDMFIELDATTRIBUTE, DRIVER=4.24.92: create index IX_1E90C536 on DDMFieldAttribute (storageId, languageId, ctCollectionId);`

**Error**
` create unique index IX_943E0A56 on CommerceSubscriptionEntry (uuid_[$COLUMN_LENGTH:75$], groupId);
     [java] 	at com.liferay.portal.spring.extender.internal.upgrade.InitialUpgradeExtender$InitialUpgradeStep.upgrade(InitialUpgradeExtender.java:240) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) ~[?:?]
     [java] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:364) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:350) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:209) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.map.PropertyServiceReferenceMapper.map(PropertyServiceReferenceMapper.java:50) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:241) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:229) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.apache.felix.dm.impl.ComponentImpl.registerService(ComponentImpl.java:1566) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1235) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1337) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.ComponentImpl.lambda$handleEvent$6(ComponentImpl.java:565) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182) ~[?:?]
     [java] 	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165) ~[?:?]
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
     [java] 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]`

https://testray.liferay.com/reports/production/logs/2022-01/test-1-32/test-portal-acceptance-pullrequest(master)/1910/functional-tomcat90-db2111-jdk8/0/14/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
@kyle-miho is this is the same DB2 errors you saw on the release run?

**Comment by shuyangzhou** [comment]
This change has nothing to do with DBs, it can not be related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111979

**Pull request closed without merging**
