### PR TITLE
[Bug Fix]LPS-131251

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@tinatian why https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-service/src/main/java/com/liferay/dynamic/data/lists/model/impl/DDLRecordSetCacheModel.java#L227 isn't enough for the CacheField population?

**Comment by tinatian** [comment]
@shuyangzhou The problem is the result object in collection result is not loaded from entity cache, it is loaded from hibernate session cache, thus it did not have the value for cache field

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
