### PR TITLE
LPS-129058 Move JournalArticle content to DDMField tables

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou @Preston-Crary This breaks a staging tests that imports a previously generated LAR

@JoyceWang08211 Can you regen the [LAR](https://github.com/liferay/liferay-portal/tree/master/portal-web/test/functional/com/liferay/portalweb/dependencies/HR_WebContent_master.lar) based on this branch?
````
ERROR [liferay/background_task-8][BackgroundTaskMessageListener:182] Unable to execute background task
com.liferay.exportimport.kernel.lar.PortletDataException: No such field com.liferay.journal.model.impl.JournalArticleImpl._content
---- Debugging information ----
message             : No such field com.liferay.journal.model.impl.JournalArticleImpl._content
field               : _content
class               : com.liferay.journal.model.impl.JournalArticleImpl
required-type       : com.liferay.journal.model.impl.JournalArticleImpl
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /JournalArticle/_content
line number         : 23
version             : 1.4.16
````

**Comment by JoyceWang08211** [comment]
Sure, I'll regenerate the LAR asap. @vicnate5

**Comment by JoyceWang08211** [comment]
LPS-130676 occurs when publish the new lar file. Please see details in LPS-130886. 
I pushed the new lar file to Preston-Crary for fixing this issue.
@Preston-Crary @vicnate5

**Comment by Preston-Crary** [comment]
@JoyceWang08211 , can we disable that test since we found it's not caused by these changes?

**Comment by JoyceWang08211** [comment]
@Preston-Crary Sure, we can quarantine this test due to LPS-130915.

**Comment by JoyceWang08211** [comment]
Quarantine the failing test and resolve the conflict, send to Shuyang:
Send to Shuyang:
https://github.com/shuyangzhou/liferay-portal/pull/9977

**Comment by Preston-Crary** [comment]
Thanks @JoyceWang08211

**Pull request closed without merging**
