### PR TITLE
Lps 138126 basic registry impl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 Please help me check the test results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho Please check the results here

**Comment by kyle-miho** [comment]
@shuyangzhou nothing seems related, pull should be good to go

**Comment by shuyangzhou** [comment]
Thanks @kyle-miho 

See https://github.com/brianchandotcom/liferay-portal/pull/106783

**Pull request closed without merging**
