### PR TITLE
LPS-X Fix circular dependencies "NPMRegistryImpl -> list of NPMRegist…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ryUpdatesListener -> JSResolveModulesServlet -> BrowserModulesResolver -> NPMRegistryImpl"

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
release build failed to fully startup here, re-running

**Comment by vicnate5** [comment]
@shuyangzhou Should be good since second run passed

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123575

**Pull request closed without merging**
