### PR TITLE
[TS] LPS-124209

### PR DESCRIPTION
**Pull request by jonathanmccann**
As per https://github.com/brianchandotcom/liferay-portal/pull/96466#issuecomment-736598652

This also includes an additional check to make sure the values are valid. Let me know if you see any potential issues with that (https://github.com/shuyangzhou/liferay-portal/pull/9646/commits/5be8e80ba995cc8e1eb234d9dafc4009fc936c2a).

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@shuyangzhou Can this one still be forwarded to Brian? It seems all the tests have passed now.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
