### PR TITLE
Lps 60225

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Ithildir another build hanging https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPBookmarks%23EditFolder,label_exp=!master/13139//console

**Comment by Ithildir** [comment]
@shuyangzhou: I'm trying the code that should print the thread dump after 1 hour, we'll see... https://github.com/Ithildir/liferay-portal/pull/124

**Comment by shuyangzhou** [comment]
Great :)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/31853

**Pull request closed without merging**
