### PR TITLE
Lps 138126 com.liferay.registry.collections

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found on previous test runs https://github.com/shuyangzhou/liferay-portal/pull/10282 aside from the known issues with `JournalArticleStagedModelDataHandlerTest` and `ManifestSummaryTest`

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please let me if this is good to go, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 can you take a look?

**Comment by vicnate5** [comment]
Looking at this now

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go.

**Comment by shuyangzhou** [comment]
ci:forward

Thanks @vicnate5 !

**Comment by zhangyan0701** [comment]
> Looking at this now

Thanks @vicnate5 !

And sorry for missing your mention!

**Pull request closed without merging**
