### PR TITLE
[SF] LPD-8724 Create SF rule to check input streams from URL objects

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-8724>

@shuyangzhou, this is a SF check to cover this issue: <https://github.com/brianchandotcom/liferay-portal/pull/143943>.

Tested here: <https://github.com/liferay-core-infra/liferay-portal/pull/6187>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147077

**Pull request closed without merging**
