### PR TITLE
LPS-X Avoid unnecessary put contention. When you have instanceble por…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…tlet on the page with PRP, this can become a global sync point.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 This was already merged by BChan, but can you check the results here?

**Comment by zhangyan0701** [comment]
No regression found.

**Comment by shuyangzhou** [comment]
Thanks @zhangyan0701 !

**Pull request closed without merging**
