### PR TITLE
Startup optimization 345 eclipse.bundle.set tccl

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Error here starting search in a cluster node (Remote ES)

```
ERROR [SystemExecutorServiceUtil-3][ROOT:47] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.100 (464)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(1547)] : The activate method has thrown an exception
java.lang.IllegalArgumentException: no raw transformer found for class class org.elasticsearch.core.TimeValue
	at org.elasticsearch.xcontent.XContentBuilder.humanReadableField(XContentBuilder.java:1035) ~[?:?]
	at org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse.toXContent(ClusterHealthResponse.java:356) ~[?:?]
	at org.elasticsearch.common.Strings.toString(Strings.java:854) ~[?:?]
	at org.elasticsearch.common.Strings.toString(Strings.java:839) ~[?:?]
	at org.elasticsearch.common.Strings.toString(Strings.java:811) ~[?:?]
	at org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse.toString(ClusterHealthResponse.java:332) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl.execute(HealthClusterRequestExecutorImpl.java:48) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.executeClusterRequest(ElasticsearchClusterRequestExecutor.java:44) ~[?:?]
	at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:31) ~[?:?]
	at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:13) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.execute(ElasticsearchClusterRequestExecutor.java:37) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:60) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine._waitForYellowStatus(ElasticsearchSearchEngine.java:468) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.initialize(ElasticsearchSearchEngine.java:147) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.activate(ElasticsearchSearchEngine.java:272) ~[?:?]
```

**Comment by shuyangzhou** [comment]
@vicnate5 can you get me the steps? Thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 never mind, I know what is going on, rerunning with fix, thanks!

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@shuyangzhou Still have an issue on startup with remote ES.

Steps to Reproduce:
1. Startup remote ES node with `ant -f build-test-elasticsearch7.xml start-elasticsearch`
2. Start portal

```
ERROR [SystemExecutorServiceUtil-10][ROOT:47] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.100 (200)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(248)] : The activate method has thrown an exception
java.lang.IllegalArgumentException: no raw transformer found for class class org.elasticsearch.core.TimeValue
        at org.elasticsearch.xcontent.XContentBuilder.humanReadableField(XContentBuilder.java:1035) ~[?:?]
        at org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse.toXContent(ClusterHealthResponse.java:356) ~[?:?]
        at org.elasticsearch.common.Strings.toString(Strings.java:854) ~[?:?]
        at org.elasticsearch.common.Strings.toString(Strings.java:839) ~[?:?]
        at org.elasticsearch.common.Strings.toString(Strings.java:811) ~[?:?]
        at org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse.toString(ClusterHealthResponse.java:332) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.HealthClusterRequestExecutorImpl.execute(HealthClusterRequestExecutorImpl.java:48) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.executeClusterRequest(ElasticsearchClusterRequestExecutor.java:44) ~[?:?]
        at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:31) ~[?:?]
        at com.liferay.portal.search.engine.adapter.cluster.HealthClusterRequest.accept(HealthClusterRequest.java:13) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.ElasticsearchClusterRequestExecutor.execute(ElasticsearchClusterRequestExecutor.java:37) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:60) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine._waitForYellowStatus(ElasticsearchSearchEngine.java:468) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.initialize(ElasticsearchSearchEngine.java:147) ~[?:?]
        at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.activate(ElasticsearchSearchEngine.java:268) ~[?:?]
```

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@shuyangzhou Issue is fixed, no other regressions here.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144176

**Pull request closed without merging**
