### PR TITLE
 LPS-112857 BasePersistence.dslQuery() Part 2

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Covered by CTEntryLocalServiceTest.

**Comment by Preston-Crary** [comment]
One thing I wasn't sure about is if we want to add getTable() to BasePersistence. It's more API but we're already having this API as soon as dslQuery(DSLQuery) is added.

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Rebased and ran baseline.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Resolved conflict with DL changes.

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Fixed semantic versioning failure.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88372

**Pull request closed without merging**
