### PR TITLE
LPS-75948 Portlet 3.0: Detect portlet spec version found in the portlet.xml descriptor

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: When you get an opportunity, please review the CI failures in this PR. If you determine them to be unrelated, please re-open this PR so that Shuyang can review.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@ngriffin7a unrelated. @shuyangzhou please review!

**Comment by ngriffin7a** [comment]
Thanks @jpince ! :)

**Comment by ngriffin7a** [comment]
@shuyangzhou I'm closing this PR because I will refactor it to change PortletApp.java instead! :)

**Pull request closed without merging**
