### PR TITLE
LPS-X Cache resource action configuration processing state to avoid r…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…epeatly processing.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in these results. Gonna check the JSF demos to be safe.

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by shuyangzhou** [comment]
@vicnate5 @tinatian I am adding the "-ext.xml" support as a separate support in my cache solution. If we end up truly dropping the "-ext.xml" we can just revert the last commit. This way I can proceed with this pull without waiting.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
No issues on the initial JSF results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133992

**Pull request closed without merging**
