### PR TITLE
[TECHNICAL-SUPPORT] LPS-101652 Alternate URL of the default page

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @shuyangzhou ,

I applied the same check for default pages that we have already for the non-default ones in
[PortalImpl._getAlternateURLs(..)](https://github.com/liferay/liferay-portal/blob/0fbfcb74c480e825dd49325ff0897ad33dcccaf4/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L8443): when the locale is the default, don't append localization into the URL.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
Test failures not related

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79725

**Pull request closed without merging**
