### PR TITLE
LPS-156466 Make PortletTrack ServiceTracker opening transactional in …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…order to merge company creation txs.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou I was able to test with a smaller 50 company database. This branch has a regression in the time it takes to make localhost:8080 available.

Steps used to test:
1. Import [50 company database](https://drive.google.com/file/d/1d5jgf-93kuikkrbmxQkBdK1xGm8kuXk6/view?usp=sharing) into MySQL
1. Set `browser.launcher.url=http://localhost:8080` (default)
1. Start portal and timer
1. Wait for browser to auto launch once Portal is available
1. Stop timer once browser launches

On my machine there is a significant difference between Master and this branch 

(minutes and seconds)
| Test | Master  | This Branch |
| --- | ------------- | ------------- |
| 1 | 3:04 | 6:14 |
| 2 | 3:06 | 15:00+ canceled test  |
| 3 | 3:21 | 6:29  |

CC @ericyanLr

**Pull request closed without merging**
