### PR TITLE
Commerce 2475 Move Data Integration Admin to liferay-portal repository master branch

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@matijapetanjek 
```
     [exec] \$ liferay-npm-scripts check
     [exec] apps/dispatch/dispatch-web/src/main/resources/META-INF/resources/process/buttons.jsp: BAD
     [exec] apps/dispatch/dispatch-web/src/main/resources/META-INF/resources/process/details.jsp: BAD
     [exec] apps/dispatch/dispatch-web/src/main/resources/META-INF/resources/process_log_toolbar.jsp: BAD
     [exec] apps/dispatch/dispatch-web/src/main/resources/META-INF/resources/process_toolbar.jsp: BAD
     [exec] Prettier checked 12 files, 4 files have problems
```
looks like real failures from this pull, please fix and resend, make sure you can pass SF check locally before sending to save the turn around time.

**Pull request closed without merging**
