### PR TITLE
[Deprecation]LPS-104829

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@koor4356

**Comment by koor4356** [comment]
@shuyangzhou, look goods. No unique failure to this pr. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81897

**Pull request closed without merging**
