### PR TITLE
System bundle util

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results. This change is not completed yet, I am just checking at a mid-point to make sure nothing is too off. Thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check these results?

**Comment by kyle-miho** [comment]
@shuyangzhou failures seem to be unrelated, already upstream, or a jenkins issue, ill re-run the upgrade batch to confirm, but there doesnt seem to be any regressions in this first midpoint run

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Pull request closed without merging**
