### PR TITLE
LPS-105384 TEMPORARY CACHE

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
@ngriffin7a @vicnate5

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Possible unique issue on Project Template tests
https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284866/

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@shuyangzhou Test results are good on fresh run. This is ready.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83231

**Pull request closed without merging**
