### PR TITLE
[TECHNICAL-SUPPORT] LPS-83494 Some resource bundles cannot be overriden 2

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by jcampoy** [comment]
Hi @shuyangzhou 
as I said some days ago, we need to go ahead with any kind of fix because this issue is blocking some projects upgrading to DXP.
Could you please take a look as soon as possible and resend to brian if all it's ok? 
Thanks in advance.
Jose.

**Comment by shuyangzhou** [comment]
I need some change to be done by @Preston-Crary . Close this, preston will resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6740

**Pull request closed without merging**
