### PR TITLE
LPS-138796

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@rotty3000 why all Reference usages are GREEDY ? Most of them do not even have more than 1 provider.

**Comment by rotty3000** [comment]
This makes is easier to integrate and to test. Some of the tests make use of this feature to avoid unnecessarily complex configuration control.

**Comment by rotty3000** [comment]
in other words, I just need to deploy a service with a higher service.ranking and it will take over. I don't have to do anything else.

**Comment by rotty3000** [comment]
if you prefer I can limit it to the ones I need to mock, but I saw no problem with doing them all for better integration. I will make the change.

**Comment by shuyangzhou** [comment]
It is ok, I have already started making changes to the pull, I can take care of it, you don't need to change it, thanks @rotty3000 !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110340

**Pull request closed without merging**
