### PR TITLE
LPS-110200 Baseline

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn can you do a full compare between this pull and master for ant all? This should not change jvm count, just running baseline in parallel. I don't see noticeable difference locally. But machines with large CPU number might see a difference.
We should compare, average total execution time difference. GC difference, and metaspace difference, or anything you can find.

**Comment by slnn** [comment]
OK, got it

**Comment by GinsonRen** [comment]
Hi @shuyangzhou 

There is the result on qa1-console:

Portal Version | Git Id | GradleWorkerMain | soy-2017-04-23-SoyToIncrementalDomSrcCompiler.jar | GradleWrapperMain | GradleDaemon | Launcher | Total Pids | Total count of full GC | MetaSpace Size that before last full GC | MetaSpace Size that after last full GC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 6451cec1b67ab4dcd790f52593cb3a897d65b7a0 | 20 | 12 | 22 | 1 | 1 | 56 | 2 | 216182K | 216182K
PR | - | 20 | 12 | 22 | 1 | 1 | 56 | 3 | 162702K | 153333K

For the qa1-console machine information:


Items | Info
-- | --
CPU | Intel(R) Core(TM) i7-4790 CPU 4C8T @ 3.60GHz
Memory | 32GB
OS | Xubuntu 18.04
Kernel | 4.15.0-58-generic
JDK | 1.8.0_172

/cc @slnn

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results on my laptop and nportal2:

Laptop:

Portal Version | Git Id | GradleWorkerMain | soy-2017-04-23-SoyToIncrementalDomSrcCompiler.jar | GradleWrapperMain | GradleDaemon | Launcher | Total Pids | Total count of full GC | MetaSpace Size that before last full GC | MetaSpace Size that after last full GC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 6451cec1 | 24 | 12 | 20 | 1 | 1 | 58 | 2 | 217048K | 217048K
PR | - | 24 | 12 | 22 | 1 | 1 | 60 | 2 | 89358K | 89355K


nportal2:

Portal Version | Git Id | GradleWorkerMain | soy-2017-04-23-SoyToIncrementalDomSrcCompiler.jar | GradleWrapperMain | GradleDaemon | Launcher | Total Pids | Total count of full GC | MetaSpace Size that before last full GC | MetaSpace Size that after last full GC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 6451cec1 | 33 | 12 | 22 | 1 | 1 | 69 | 3 | 254383K | 254383K
PR | - | 33 | 12 | 22 | 1 | 1 | 69 | 4 | 131290K | 131290K

Laptop machine info:



Device | Info
-- | --
CPU | Intel i7-9850H 6C12T @ 2.60GHz Turbo 4.6GHz
Memory | 64GB(32GB x 2, DDR4 2667MT/s)
Storage | NVME SSD 1TB
OS | Xubuntu 18.04
Kernel | 4.15.0-58-generic
JDK | 1.8.0_151
Disabled services | none

 
nportal2 machine info:


Device | Info
-- | --
CPU | Dual Xeon E5 2643 v4 @ 3.4GHz, 6C 12T each, 12C 24T in total
Memory | 64GB ECC Memory (16GB x 4, DDR4 2400MHz)
Storage | Dual 10K RPM SAS HDD, Raid 0
OS | CentOS 7.6.1810
Kernel | 3.10.0-957.12.1.el7.x86_64
JDK | 1.8.0_65
Disabled services | auditd, crond, firewalld, lvm2-monitor, postfix, rsyslog, sysstat

**Comment by slnn** [comment]
From these test results on different machines, we can see a diff on GC.

**Comment by shuyangzhou** [comment]
So this pr is making one more full gc? I need to see the gc logs.
And how about the total execution time difference?

**Comment by slnn** [comment]
Hi @shuyangzhou

Update comment about the total ant all time, from test results in qa1 console and nportal2, this pull reduced a bit on the time of ant all .

Detail test results zip please see:

https://mega.nz/#F!JgUlXCYA!pggUrEJCCwf28Fadu7QEzg


For test results of my laptop, when I rechecked the ant all output, ant all failed with this pull(I'm sorry that do not notice this yesterday), I rechecked it today, it may did not caused by this pull as I reproduced it on master. Maybe some problems with my local env, please see test resuts on nportal2 and qa1 console.

Lily

**Comment by shuyangzhou** [comment]
@slnn your failure is npm failure, try to wipe out all your "node_modules", then it should be fine.

@petershin this is a good change, please rebase and send it to brian, thanks!

**Comment by petershin** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/86257

**Pull request closed without merging**
