### PR TITLE
LPS-106976 use provide capability when other module langagues are needed so that there's no need to override every specific module sharing a key.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull's results, thanks!

**Comment by kyle-miho** [comment]
failures are unrelated, pull should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83281

**Pull request closed without merging**
