### PR TITLE
LPS-63235 fix cacheable portlets

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @shuyangzhou 

I don't fully understand the consequences of this change, so I really need you to review it :)

This is by @juangon 

Hi @juliocamarero. It turns out after https://issues.liferay.com/browse/LPS-57330 (where embedded portlets are checked for cacheability too) all Guest pages were NOT cached, as some of the embedded portlets did not have this option enabled.

Please, can you check that Product navigation user personal bar and product menu web can be enabled without any problem of showing stale data to users? My checks had been successful until now.

@eduardolundgren @marcellustavares I've removed layout cacheability for the DDL/DDM portlets as it wasn't working actually due to this bug, and would show stale data after this fix.

After you finish the work, can you send to @shuyangzhou so he can review the second and third commit?

/cc @adolfopa

Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:stop

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juangon** [comment]
hi @shuyangzhou. I've added 304 checks for cache too (here https://github.com/shuyangzhou/liferay-portal/pull/2831/commits/e3299f46fd7cfec5d3788d566dd9899a62e06361) because for some resources like /o/dynamic-data-mapping-form-renderer/css/main.css it was returned like this. If we don't add  the check here, that resource will never be added to cache.

Thanks!

**Comment by juangon** [comment]
@alee8888 please can you check why these tests are failing? For example, I've checked adding a document from control panel (I guess that's what CPDocumentsandmedia#AddDocument is about) but seems working fine.

**Comment by juangon** [comment]
ci:retest

**Comment by alee8888** [comment]
@juangon 
All the functional tests are actually failing at the same location; after clicking the 'Sign In' link on the user personal bar, the following xpath is no longer visible:

```
//div[contains(@class,'modal-dialog')]//div[contains(@class,'modal-body')]
```

It could be due to stale data as we do run up to 3 functional testcases on the same bundle (with each functional test running on it's own virtual instance). You can navigate to a html report (with screenshots by following these steps. I do apologize that the navigation within Jenkins is a bit unrefined:

1. For CPDocumentsandmedia#AddDocument, click on 'Poshi Report'.
2. Click into the 'CPCustomfields#EditCustomFieldUserBoolean' folder.
3. Click on index.html.
4. An html report will open up. To go directly to the error, click on the button that has a triangle with an exclamation mark in it.

**Comment by shuyangzhou** [comment]
@juliocamarero @juangon please fix and resend

**Pull request closed without merging**
