### PR TITLE
Lps 89456 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by anthony-chu** [comment]
@tinatian @shuyangzhou 

A `MySQLSyntaxErrorException` is thrown when attempting to publish deleted pages as a non-admin user.

**Steps to reproduce:**

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException
MySQL 8.0 - Staging

1. add community site
	- disable template propagation for pages
1. activate local live staging
	- enable page versioning
1. create new user
1. create a new site role: "Staging Admin"
	- Site Administration > Build > Pages > Site pages > General Permissions > All
	- Site Administration > Build > Pages > Site Pages > Resource Permissions > Site > All
	- Site Administration > Build > Pages > Site Pages > Resource Permissions > Page > All
	- Site Administration > Build > Pages > Site Pages > Resource Permissions > Page Variation > All
	- Site Administration > Build > Pages > Site Pages > Resource Permissions > Permissions > Site Pages Variation > All
1. navigate to staged site
1. assign user as member of staged site
1. give new user "Staging Admin" role
1. log in as the new user
1. navigate to staged site
1. add a new site page variation
	- copy from Main Variation
1. delete wiki page
1. navigate to Publishing > Staging
1. create a new publication

**Expected result:** User navigates to custom publication page successfully
**Actual result:** Navigating to custom publication page throws `MySQLSyntaxErrorException`:
```
2019-02-05 17:21:09.232 ERROR [http-nio-8080-exec-2][JDBCExceptionReporter:234] Unknown column 'layout.system' in 'where clause'
2019-02-05 17:21:09.322 ERROR [http-nio-8080-exec-2][IncludeTag:128] Current URL /group/community-site-staging/~/control_panel/manage?p_p_id=com_liferay_staging_processes_web_portlet_StagingProcessesPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_staging_processes_web_portlet_StagingProcessesPortlet_mvcRenderCommandName=publishLayouts&_com_liferay_staging_processes_web_portlet_StagingProcessesPortlet_cmd=publish_to_live&_com_liferay_staging_processes_web_portlet_StagingProcessesPortlet_groupId=38128&_com_liferay_staging_processes_web_portlet_StagingProcessesPortlet_privateLayout=false&p_p_auth=btMmVRfg generates exception: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'layout.system' in 'where clause'
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:1953)
        at org.hibernate.loader.Loader.doQuery(Loader.java:802)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
        at org.hibernate.loader.Loader.doList(Loader.java:2542)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
        at org.hibernate.loader.Loader.list(Loader.java:2271)
        at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:316)
        at org.hibernate.impl.SessionImpl.listCustomQuery(SessionImpl.java:1842)
```

**Comment by tinatian** [comment]
Hi @anthony-chu 
Where can I see the full error log?

**Comment by anthony-chu** [comment]
You can find the full error log here:

https://testray.liferay.com/reports/production/logs/test-1-13/1549307288075/test-portal-acceptance-pullrequest(master)/2148/functional-tomcat90-mysql57-jdk8/32/0/jenkins-console.txt.gz

**Comment by tinatian** [comment]
Hi @anthony-chu,

Did you reproduce it locally by the steps you listed above?

**Comment by anthony-chu** [comment]
@tinatian yes, i was able to manually reproduce using the above steps.

**Pull request closed without merging**
