### PR TITLE
LPS-101590 Remove pageCount column from LayoutSet

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by Preston-Crary** [comment]
@slnn please check this for performance regressions. Login and Journal test cases should be enough.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results on Login and WebContent:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | a20141d | 47182 | 273 | 80.7
PR-8263 | - | 47544 | 263 | 76.2

WebContent:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | a20141d | 60260 | 633 | 226
PR-8263 | - | 60055 | 492 | 151

Regards
Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/78575

**Pull request closed without merging**
