### PR TITLE
LPS-92677

### PR DESCRIPTION
**Pull request by jonathanmccann**
@shuyangzhou 

Please let me know your thoughts on these changes. I wasn't sure if there was a more elegant way to write https://github.com/shuyangzhou/liferay-portal/commit/0c2caa754076eef6d3872025ab2c28fd57dbed95#diff-afcd6a343881a50ebb6a12bb6d68b008R4391. The first entity it encounters is the `companyId` and the second entity contains the first column of the composite primary key. If anything else is unclear please let me know.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please resend with the changes we talked about, thanks!

**Comment by jonathanmccann** [comment]
https://github.com/Preston-Crary/liferay-portal/pull/724

**Pull request closed without merging**
