### PR TITLE
LPS-85903 Portlet 3.0: Public render parameters that are set in the ACTION_PHASE or EVENT_PHASE must be preserved when action-url-redirect=true

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou The small changes in the 1 commit for this PR will only execute when a portlet does an opt-in for Portlet 3.0 -- since all of our out-of-the-box portlets are V2, these failures must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63685

**Pull request closed without merging**
