### PR TITLE
LPS-130426 Check the type of exception and log level to either print exception message, print full stack trace or rethrow exception

### PR DESCRIPTION
**Pull request by dacousalr**
This is a follow-up of LPS-129244 (https://github.com/shuyangzhou/liferay-portal/pull/9862)

There would be a method left, com.liferay.portal.kernel.servlet.ServletResponseUtil._write, not checked by _checkSocketException method so stack traces could be printed at WARN level.

Could you please review?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100746

**Pull request closed without merging**
