### PR TITLE
LPS-78940 VersionService

### PR DESCRIPTION
**Pull request by Preston-Crary**
For some reason I'm not able to generate a jacoco report, I get the following:
```
/portal(LPS-78940)$generate-code-coverage-report -Dclass.names=VersionedEntryLocalServiceBaseImpl

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
Buildfile: /repos/trunk/portal/build.xml
   [delete] Deleting: /repos/trunk/portal/null1743930423.properties

generate-code-coverage-report:
   [delete] Deleting directory /repos/trunk/portal/jacoco/html-report
    [mkdir] Created dir: /repos/trunk/portal/jacoco/html-report
[get-file-set] Apr 16, 2018 11:54:17 AM com.liferay.util.ant.GetFileSetTask execute
[get-file-set] WARNING: No class files found for: [VersionedEntryLocalServiceBaseImpl]
[jacoco:report] Loading execution data file /repos/trunk/portal/jacoco/liferay-jacoco.exec

BUILD FAILED
/repos/trunk/portal/build-common.xml:1982: The following error occurred while executing this line:
/repos/trunk/portal/build-common.xml:883: Reference get.file.set.class.set not found.
```

I'm able to generate reports for other classes though and was able to generate one for this class about two weeks ago.  Did we make any changes to jacoco in the last couple weeks?

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@slnn

**Comment by slnn** [comment]
Hi @Preston-Crary,

I will check it.

Lily

**Comment by slnn** [comment]
Hi @Preston-Crary,

The root cause is the GetFileSetTask will skip scan the path which contains "tools".

The fix in https://github.com/dantewang/liferay-portal/pull/649 should fix the issue that you encountered.

Lily

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
See https://issues.liferay.com/browse/LPS-73353, for how to run Jacoco

**Comment by Preston-Crary** [comment]
Updated to have full test coverage.  Thanks @slnn !

**Comment by Preston-Crary** [comment]
Removed both usages of isNew() and confirmed tests are still green.

**Comment by Preston-Crary** [comment]
Updated the method name. Reduced duplication by calling populateVersionModel().  Removed all RandomTestUtil usages.

**Comment by Preston-Crary** [comment]
Updated parameter names and local variables to match the interfaces parameter names.

**Comment by Preston-Crary** [comment]
Fixed a bug where deleteDraft had a hardcoded return value.

**Comment by Preston-Crary** [comment]
Updated assert to have the correct expected value and double checked the others.

**Comment by Preston-Crary** [comment]
Added 67ae0c1 and rebased pull on top of those changes.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57435

**Pull request closed without merging**
