### PR TITLE
LPS-108204

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @shuyangzhou, 

Thir pr extends the solution in LPS-104812 to allow for nontrivial context and proxy paths. 

I tried setting the constant `_pathModulePrefix` in the constructor but at that momento Portal(Util) is not available yet.

Thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull, thanks!

**Comment by kyle-miho** [comment]
no unique functional or integration failures pull should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84339

**Pull request closed without merging**
