### PR TITLE
Lps 117611

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failures are flaky tests, not related. Recommend manual forward.

**Comment by vicnate5** [comment]
Contacted Echo team about their tests

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91797

**Pull request closed without merging**
