### PR TITLE
LPD-20793 Postpone remote portlet deployment checking to first reques…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…t serving.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou There is an issue here starting the portal with Database Partitioning, though it does not affect every test that uses db partion.

Example: https://testray.liferay.com/home/-/testray/case_results/2552317660

```
 ERROR [http-nio-8080-exec-3][BundleSiteInitializer:661] Someone may be trying to circumvent the permission checker: {companyId=94304394171713, name=com.liferay.document.library, primKey=com.liferay.document.library, scope=4}
java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=94304394171713, name=com.liferay.document.library, primKey=com.liferay.document.library, scope=4}
	at com.liferay.portal.security.permission.AdvancedPermissionChecker._hasUserPermissionImpl(AdvancedPermissionChecker.java:1312) ~[portal-impl.jar:?]
	at com.liferay.portal.security.permission.AdvancedPermissionChecker._hasPermissionImpl(AdvancedPermissionChecker.java:1268) ~[portal-impl.jar:?]
	at com.liferay.portal.security.permission.AdvancedPermissionChecker.hasPermission(AdvancedPermissionChecker.java:233) ~[portal-impl.jar:?]
	at com.liferay.portal.security.permission.BasePermissionChecker.hasPermission(BasePermissionChecker.java:80) ~[portal-impl.jar:?]
	at com.liferay.portal.security.permission.StagingPermissionChecker.hasPermission(StagingPermissionChecker.java:111) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.security.permission.wrapper.PermissionCheckerWrapper.hasPermission(PermissionCheckerWrapper.java:92) ~[portal-kernel.jar:?]
	at com.liferay.users.admin.internal.security.permission.wrapper.ServiceAccountUserPermissionCheckerWrapper.lambda$hasPermission$0(ServiceAccountUserPermissionCheckerWrapper.java:40) ~[?:?]
	at com.liferay.users.admin.internal.security.permission.wrapper.ServiceAccountUserPermissionCheckerWrapper._hasPermission(ServiceAccountUserPermissionCheckerWrapper.java:74) ~[?:?]
	at com.liferay.users.admin.internal.security.permission.wrapper.ServiceAccountUserPermissionCheckerWrapper.hasPermission(ServiceAccountUserPermissionCheckerWrapper.java:38) ~[?:?]
	at com.liferay.portal.kernel.security.permission.wrapper.PermissionCheckerWrapper.hasPermission(PermissionCheckerWrapper.java:92) ~[portal-kernel.jar:?]
	at com.liferay.on.demand.admin.internal.security.permission.wrapper.OnDemandAdminPermissionCheckerWrapper.lambda$hasPermission$0(OnDemandAdminPermissionCheckerWrapper.java:42) ~[?:?]
	at com.liferay.on.demand.admin.internal.security.permission.wrapper.OnDemandAdminPermissionCheckerWrapper._hasPermission(OnDemandAdminPermissionCheckerWrapper.java:76) ~[?:?]
	at com.liferay.on.demand.admin.internal.security.permission.wrapper.OnDemandAdminPermissionCheckerWrapper.hasPermission(OnDemandAdminPermissionCheckerWrapper.java:40) ~[?:?]
	at com.liferay.portal.kernel.security.permission.wrapper.PermissionCheckerWrapper.hasPermission(PermissionCheckerWrapper.java:92) ~[portal-kernel.jar:?]
	at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper.lambda$hasPermission$0(DepotPermissionCheckerWrapper.java:62) ~[?:?]
	at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper._hasPermission(DepotPermissionCheckerWrapper.java:200) ~[?:?]
	at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper.hasPermission(DepotPermissionCheckerWrapper.java:60) ~[?:?]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission._contains(DefaultPortletResourcePermission.java:130) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.internal.security.permission.resource.DefaultPortletResourcePermission.lambda$contains$1(DefaultPortletResourcePermission.java:102) ~[portal-kernel.jar:?]
```

Also fails on startup after upgrading a partitioned database
https://testray.liferay.com/reports/production/logs/2024-03/test-1-34/test-portal-acceptance-pullrequest(master)/5968/functional-upgrade-tomcat90-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0

Dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13.u33/data-archive/data-archive-portal-partition-mysql.zip

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:report:2552444846

**Comment by vicnate5** [comment]
@achaparro workaround for resource permissions issue. Can you review the test results?

**Comment by vicnate5** [comment]
@tinatian @dantewang please revert this change after https://liferay.atlassian.net/browse/LPD-20946

**Comment by vicnate5** [comment]
FYI @javalosjr96

**Comment by achaparro** [comment]
Looks good to me @vicnate5

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148368

**Pull request closed without merging**
