### PR TITLE
LPS-112984 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this one too, thanks!

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz The DS collecting is still here https://github.com/shuyangzhou/liferay-portal/pull/9133/commits/e9ce188298f4511a60fa16fb753ad56b72ebc850#diff-6e5108f6beab9bc5cdddfb10f0c8bcf2R328 . Did you send a wrong branch?

Please remove and resend.

**Pull request closed without merging**
