### PR TITLE
LPS-112770 Avoid race condition. ReindexSingleIndexerBackgroundTaskExecutor indirectly depends on BackgroundTaskManagerImpl (through IndexWriterHelperImpl). BackgroundTaskMessageListener is constructed and started in BackgroundTaskManagerImpl activate, so it can use ReindexSingleIndexerBackgroundTaskExecutor before all its dependencies are satisfied.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by lipusz** [comment]
@arboliveira Fyi :point_up:

**Comment by lipusz** [comment]
ci:test:sf:norebase

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:search:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by brookedalton** [comment]
Multiple NullPointerExceptions on startup when adding index.on.startup=true to portal-ext.properties`2020-05-01 19:47:12.838 ERROR [liferay/background_task-4][ReindexSingleIndexerBackgroundTaskExecutor:107] java.lang.NullPointerException
java.lang.NullPointerException
	at com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor.reindex(ReindexSingleIndexerBackgroundTaskExecutor.java:101)
	at com.liferay.portal.search.internal.background.task.ReindexBackgroundTaskExecutor.execute(ReindexBackgroundTaskExecutor.java:54)
	at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:62)
	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:41)
	at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:72)
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:136)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Pull request closed without merging**
