### PR TITLE
[Bug Fix]LPS-121770-LPS-121537

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is based on https://github.com/shuyangzhou/liferay-portal/pull/9482.

FYI @marianoalvarosaiz @jorgediaz-lr

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
Will rebase and resend

**Pull request closed without merging**
