### PR TITLE
LPS-108239 DB Partition Implementation

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

In this pull I have done:
- Refactor add and check company methods
- Remove the use command from the public interface
- DB Integration tests

Finally, we don't need to open a new transaction inside the service. This approach is simpler and the transaction one was problematic because the first transaction created the new company but the second transaction can't see it so we have issues since we execute different verifications over the company record in this transaction.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/achaparro/liferay-portal/pull/495

**Pull request closed without merging**
