### PR TITLE
LPS-129271 Close S3Object as a callback when the InputStream is closed.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou I got the configuration needed to get S3 working at head.

PASSED Manual testing with steps in both
https://issues.liferay.com/browse/LPS-127589
https://issues.liferay.com/browse/LPS-129271

This is good to go. 

Pursuing automation of S3 with Lima team.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
