### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@topolik see f69752f01b3e5852d6d27d85a9dc258d974fa4ad. There's a lot of requirements already so this is the closest I can get to API/SPI. Everything in impl packages are SPI. Everything else is API.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8730

**Pull request closed without merging**
