### PR TITLE
[MessageBus]LPS-102995

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help scan the result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Unique failure: `com.liferay.headless.admin.user.resource.v1_0.test.SegmentUserResourceTest.testGetSegmentUserAccountsPage`
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335265/AXIS_VARIABLE=14,label_exp=!master/testReport/junit/com.liferay.headless.admin.user.resource.v1_0.test/SegmentUserResourceTest/testGetSegmentUserAccountsPage/

I don't understand how this could be related, but it is not occurring at head on the same hash. It failed on all databases on this PR.

Remaining test failures are unrelated.

**Comment by tinatian** [comment]
Thanks @vicnate5 ! I will take a look at it.

Tina

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/71f07ab922...921037d5b8

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/8555

**Pull request closed without merging**
