### PR TITLE
[Bug Fix]LPS-91534

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for ci result.

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
Test failures are not related to this pull.

Tina.

**Comment by shuyangzhou** [comment]
View just my changes: https://github.com/shuyangzhou/liferay-portal/compare/tinatian:53d7d90cf9...5c6c547736
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/61dc058de6...5c6c547736

**Pull request closed without merging**
