### PR TITLE
LPS-64211

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Although this is a harmless change, but I don't see why it is needed.

One can always argue about we don't have enough logging in all places, but obviously we can not add logging everywhere.

Unless there is a valid reason for the logging, I don't think we should do it.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

For support team it is very useful be able to trace which functionality is executing

For example: I was doing some Staging activation testing and it spend 30 minutes inside callback code  (the full staging activation was 6 hours)

````
00:55:39,214 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:50] Number of callbacks to be executed: 34581
00:55:39,214 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:59] Executing callback 0: com.liferay.portlet.messageboards.util.MBUtil$4
00:55:39,226 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:50] Number of callbacks to be executed: 0
00:55:39,226 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:59] Executing callback 1: com.liferay.portlet.messageboards.util.MBUtil$4
00:55:39,231 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:50] Number of callbacks to be executed: 0
00:55:39,231 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:59] Executing callback 2: com.liferay.portlet.messageboards.util.MBUtil$4
00:55:39,235 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:50] Number of callbacks to be executed: 0
00:55:39,236 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:59] Executing callback 3: com.liferay.portlet.messageboards.util.MBUtil$4
....

**Comment by shuyangzhou** [comment]
So this is for performance monitoring purpose?
There are much better ways to do it than adding the loggings. Just do a profile.

And if this is trying to solve monitoring performance issue on customer side, which means no easy way to setup profile. It will be a lot better to monitor at a higher level, like at service level. Lower level loggings like this can become very excessive.

And even with these logging, it does not really help on figure out which tx did what callbacks, and what exactly the callback was doing, as most of them are anonymous inner classes.

**Comment by jorgediaz-lr** [comment]
The idea was to be able to trace easily when a very long process is executing a lot of callbacks (for example Staging). 
With that we can easily ask to a customer to activate a trace in its production environment.

What do you think about leaving only first debug trace?
````
00:55:39,214 DEBUG [liferay/background_task-2][TransactionCommitCallbackUtil:50] Number of callbacks to be executed: 34581

Thank you

**Comment by shuyangzhou** [comment]
I get what you want, but knowing how many callbacks are invoked during the process won't really help. You still won't know whether it is the root of the slowness or not.

Even you can confirm it is the slowness, still there is not enough inner detail info can point out any direction for the solutions.

**Comment by jorgediaz-lr** [comment]
Perhaps that traces gives not enough detail, but for Support team any logging trace is useful, as some times we are blind without any clue about which code was being executed before customer error.

I can't give you more reasons.

**Comment by shuyangzhou** [comment]
I totally get the pain about lacking info to trace the problems on support team.

Just adding logging everywhere won't be the solution, and adding this particular logging won't help on this particular issue either.

What we need is a more general solution that fits most cases.

For now, the beat way is probably just do a quick profile, if this reproducable locally, or the customer is ok to profile on their side.

**Comment by shuyangzhou** [comment]
Sorry @jorgediaz-lr, I am closing this.

If it turns really necessary, we need to find a better way to monitor. Adding more logs won't be the solution.

**Pull request closed without merging**
