### PR TITLE
LPS-83736

### PR DESCRIPTION
**Pull request by jonathanmccann**
@shuyangzhou Please let me know if you have any questions or would like to pursue a different solution.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@shuyangzhou I've updated the pull to remove the duplicated calls to normalize. Please let me know if I missed anything else.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@jonathanmccann are you still in office? If so, please come over to go through the changes, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62202

**Pull request closed without merging**
