### PR TITLE
Lps 199955

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@shuyangzhou Just 2 cluster startup failures here

https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8241/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8241/functional-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
no issues in relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:clustering

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me watch over the test runs. Please see @vicnate5 's previous comments, we are trying to fix cluster startup races. It could show as NPEs or search engine activation failures (due to missing sidecar registration), or maybe there are more other wild cases.

**Comment by zhangyan0701** [comment]
@shuyangzhou 

There is no startup failures in the new Clustering tests.

But a compile error in search integration tests:
```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionFixture.java:54: error: constructor Sidecar in class com.liferay.portal.search.elasticsearch7.internal.sidecar.Sidecar cannot be applied to given types;
[beanshell]      [exec] 		Sidecar sidecar = new Sidecar(
[beanshell]      [exec] 		                  ^
[beanshell]      [exec]   required: com.liferay.portal.search.elasticsearch7.internal.configuration.ElasticsearchConfigurationWrapper,com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchInstancePaths,com.liferay.petra.process.ProcessExecutor,com.liferay.portal.search.elasticsearch7.internal.sidecar.ProcessExecutorPaths,com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager
[beanshell]      [exec]   found: com.liferay.portal.kernel.cluster.ClusterExecutor,com.liferay.portal.search.elasticsearch7.internal.configuration.ElasticsearchConfigurationWrapper,com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchInstancePaths,com.liferay.petra.process.local.LocalProcessExecutor,()->_TMP_P[...]tor"),com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarManager
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] Note: Some input files use or override a deprecated API.
[beanshell]      [exec] Note: Recompile with -Xlint:deprecation for details.
[beanshell]      [exec] Note: Some input files use unchecked or unsafe operations.
[beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
[beanshell]      [exec] 1 error
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-25/test-portal-acceptance-pullrequest(master)/4210/modules-unit-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:search

Appended a fix commit for search test compile.

**Comment by vicnate5** [comment]
No regressions in newest results

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/143651

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
