### PR TITLE
LPS-130118 Push down persistence.jar

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@koor4356 Please scan all these results for regressions

**Comment by koor4356** [comment]
@tinatian  "semantic versioning" is unique to this PR. 
The other results look fine. But no result for the upgrade yet.

**Comment by koor4356** [comment]
Upgrade results look fine except "semantic versioning" issue. Thanks!

**Comment by tinatian** [comment]
Will fix and resend.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
Results look fine, Thank you.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
