### PR TITLE
LPS-81657

### PR DESCRIPTION
**Pull request by Preston-Crary**
Please see https://github.com/Preston-Crary/liferay-portal/pull/538#issue-192545154 for more information.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn please run a regression test

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou ,

Here are test results on Login, the PR caused 7.5% drop on session count

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | 4cbd19d | 16844 | 235 | 58.1
PR-6281 | - | 15572 | 271 | 68.1

**Comment by shuyangzhou** [comment]
@holatuwol this is too large for us to bring in. Please work with Lily to find out what is causing it and fix it. Thanks!

**Pull request closed without merging**
