### PR TITLE
LPS-86824 bug fixes in bean portlet extension

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rotty3000 Following the steps from https://issues.liferay.com/browse/LPS-86824 , on deployment, I got this:
```
2019-01-03 19:08:57.915 ERROR [Aries CCR Thread][com_liferay_faces_demo_jsf_cdi_applicant_portlet:97] CCR Failure in container activator open on org.apache.aries.cdi.container.internal.container.ContainerBootstrap@54ac72d0 
java.lang.RuntimeException: Service class com.sun.faces.application.view.ViewScopeExtension didn't implement the required interface
	at org.jboss.weld.util.ServiceLoader.loadClass(ServiceLoader.java:231)
	at org.jboss.weld.util.ServiceLoader.loadService(ServiceLoader.java:211)
	at org.jboss.weld.util.ServiceLoader.loadServiceFile(ServiceLoader.java:185)
	at org.jboss.weld.util.ServiceLoader.reload(ServiceLoader.java:165)
	at org.jboss.weld.util.ServiceLoader.iterator(ServiceLoader.java:289)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.apache.aries.cdi.container.internal.container.ContainerBootstrap.open(ContainerBootstrap.java:113)
	at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:658)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
Is it a problem?

And with this pull, https://issues.liferay.com/browse/LPS-86851 can deploy fine.
But the V3URLTests_RenderURL_setParameterB7 and V3URLTests_ActionURL_setParameterB7 are failing. Are they known issues? Or caused by this fix? @ngriffin7a you may want to check on this to be sure.

And @ngriffin7a can you review all 3 tickets' steps to make sure they are clear and doable(make sure all test wars are uploaded), I will make a few changes once this pull is confirmed to be good, I will need reliable ways to test my changes. Thanks!

**Comment by rotty3000** [comment]
@shuyangzhou I believe you needed to fix a few things in the WAR that was provided in https://issues.liferay.com/browse/LPS-86824 before it would work.

Anyhow, I need to rebase, and I reorganized some changes. Will resend.

**Pull request closed without merging**
