### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@slnn can you run a performance regression on this with the same conditions as this: https://github.com/shuyangzhou/liferay-portal/pull/8249#issuecomment-531355958

Thanks!

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @mtambara ,

Here are test results on Login and Blog, I can still see a regression.

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper | 44c1be7 | 48115 | 263 | 79.4 |  
PR-8274 (disable tag pool both tomcat and liferay jasper) | - | 46725 | 284 | 86.2 | -2.888911982
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-8274 (enable tag pool both tomcat and liferay jasper) | - | 44206 | 276 | 83.7 | -2.604212567
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-8274 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44039 | 283 | 85.6 | -3.467701278

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper | 44c1be7 | 15314 | 55 | 136 |  
PR-8274 (disable tag pool both tomcat and liferay jasper) | - | 14962 | 165 | 228 | -2.298550346
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-8274 (enable tag pool both tomcat and liferay jasper) | - | 14857 | 481 | 419 | -2.442707991
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-8274 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 14546 | 655 | 492 | -4.80989464


Regards
Lily

**Pull request closed without merging**
