### PR TITLE
Lps 66596 Fix long command issue of UpgradeClient

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/20515ee243...68c0f615d1

**Comment by tinatian** [comment]
@shuyangzhou The classpath issue we talked about exists in current code, I mean without our change, if you run db upgrade client in another folder which does not contain the jar, it will fail caused by unable to find the right class. Do you want to fix this issue first? and then we go back to the long command issue?

Tina

**Comment by shuyangzhou** [comment]
Just fix it within the same pull, but as the first commit.

**Comment by tinatian** [comment]
OK, I will let Dante know.

Tina.

**Pull request closed without merging**
