### PR TITLE
LPS-76927 Tracking every small upgrade process in Core with a unique SchemaVersion and simplifying the release process

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @robertoDiaz, @csierra

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@achaparro please look into those failures, they seem to be unique to this pull.

**Comment by achaparro** [comment]
Hi @shuyangzhou,

I am not sure that they are related to my changes. For example take a look at:
https://github.com/brianchandotcom/liferay-portal/pull/56608

The same tests are failing there.

I was testing this pull yesterday and today against the CI to verify that.

Anyways, I Will double check tomorrow.

Good evening.

**Comment by shuyangzhou** [comment]
@achaparro you have a lot of ConfiguratorExtensionTest failures that I don't see from other pulls.

**Comment by achaparro** [comment]
Ok, i will analyze It tomorrow.

I will let you know. Thanks @shuyangzhou

**Pull request closed without merging**
