### PR TITLE
Portlet tracker

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@slnn please run a startup compare for this pull, thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou 

Compared with baseline (portal version:5d72a282a5938134ef91491fd9b539a1c3f4d472), this pull reduced the average startup time from 25364.6 ms to 23871.4ms.

Regards
Lily

**Pull request closed without merging**
