### PR TITLE
LPS-X Decouple ElasticsearchConnectionManager from ClusterExecutor

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me watch over this pull, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

Search integration tests failed due to compile errors:
```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManagerTest.java:72: error: method activate in class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager cannot be applied to given types;
[beanshell]      [exec] 		elasticsearchConnectionManager.activate();
[beanshell]      [exec] 		                              ^
[beanshell]      [exec]   required: org.osgi.framework.BundleContext
[beanshell]      [exec]   found: no arguments
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManagerTest.java:104: error: method activate in class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager cannot be applied to given types;
[beanshell]      [exec] 		elasticsearchConnectionManager.activate();
[beanshell]      [exec] 		                              ^
[beanshell]      [exec]   required: org.osgi.framework.BundleContext
[beanshell]      [exec]   found: no arguments
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManagerTest.java:142: error: method activate in class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager cannot be applied to given types;
[beanshell]      [exec] 		elasticsearchConnectionManager.activate();
[beanshell]      [exec] 		                              ^
[beanshell]      [exec]   required: org.osgi.framework.BundleContext
[beanshell]      [exec]   found: no arguments
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManagerTest.java:597: error: method activate in class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager cannot be applied to given types;
[beanshell]      [exec] 		elasticsearchConnectionManager.activate();
[beanshell]      [exec] 		                              ^
[beanshell]      [exec]   required: org.osgi.framework.BundleContext
[beanshell]      [exec]   found: no arguments
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] Note: Some input files use or override a deprecated API.
[beanshell]      [exec] Note: Recompile with -Xlint:deprecation for details.
[beanshell]      [exec] Note: Some input files use unchecked or unsafe operations.
[beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
[beanshell]      [exec] 4 errors
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-12/test-1-38/test-portal-acceptance-pullrequest(master)/9923/modules-unit-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regression here on CI with Elasticserach cross cluster replication.
https://testray.liferay.com/home/-/testray/case_results/2473647067

It is consistently happening on CI for, but when I run the automation test locally, I cannot reproduce consistently. It might be some race.

I believe these are the manual steps to reproduce:
1. Startup remote ES nodes with CCR enabled `ant -f build-test-elasticsearch7.xml start-elasticsearch -Delasticsearch.ccr.enabled=true -Delasticsearch.multiple.connections=true`
2. Start portal and login
3. Go to Control Panel > System Settings > Search > Cross-Cluster Replication
4. Enable "Read from Local Clusters"
5. Under "Local Cluster Configurations" add
```
localhost:8080,localcluster
```
6. Save
7. Go to Web Content
8. Add a new basic web content with title "WC Title"
9. (optional) Go to home page and use Search bar to search for "WC" and check the article is returned
10. Shutdown first ES cluster node `ant -f build-test-elasticsearch7.xml stop-elasticsearch -Delasticsearch.bundle.number=1`
11. Go to home page and use Search bar to search for "WC"

CI result: Search result is not returned.

Since CI can start searching quickly after the shutdown, might happen more easily. But I have no examples of the issue outside of this PR.

**Comment by BryanEngler** [comment]
@xbrianlee @shuyangzhou @vicnate5

i tested this solution and it works.

@xbrianlee for the test i think it would be enough to just assert the READ labels on the connections page(s), instead of shutting down ES servers and then performing searches (which seems to be unreliable)... but we need 3 ES clusters. 

ES1 - a cluster which should show the WRITE label on the connections page for both LR1 (ie localhost:8080) and LR2 (ie localhost:8081)
ES2 - a cluster which should show the READ label on the connections page for LR1 
ES3 - a cluster which should show the READ label on the connections page for LR2 

also, to make sure the replication works, i think we can just ping ES2 and ES3 directly to see if the indexes exist. i think that would be enough, no need to create documents and shut down/run searches.

**Comment by shuyangzhou** [comment]
@BryanEngler could I just send this out and leave the test fixing to you to work on later? I need this to unblock some of my other work.

**Comment by BryanEngler** [comment]
@shuyangzhou ya thats fine with me, i think we should be able to handle the tests pretty quickly

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145342

**Pull request closed without merging**
