### PR TITLE
Lps 118542

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the test results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The test failures here can be seen elsewhere on other very recent pulls. They are not unique to this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/98116

**Pull request closed without merging**
