### PR TITLE
Startup optimization 199 remove depot workflow handler wrapper

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:help

**Comment by shuyangzhou** [comment]
ci:test:depot

**Comment by shuyangzhou** [comment]
ci:test:workflow

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. The unique failures here are also happening when I run the tests against master head.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132583

**Pull request closed without merging**
