### PR TITLE
LPS-56075 Poor database performance while building search queries

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Rebased, minor conflicts.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased conflicts.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by istvansajtos** [comment]
@Preston-Crary, unfortunately this fix failed for the steps described on [LPP-20374](https://issues.liferay.com/browse/LPP-20374). (More specifically, facet count indicates there is a Wiki Page even if user has no view permission on it.)

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Pull request closed without merging**
