### PR TITLE
Startup optimization 308 parallel aop service manager

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @zhangyan0701

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the new results, thanks!

**Comment by zhangyan0701** [comment]
No unique failures in this pull. 

Will check the results of https://github.com/shuyangzhou/liferay-portal/pull/11247 when they come in.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142135
Thanks @zhangyan0701 I am sending out this one first.

**Pull request closed without merging**
