### PR TITLE
[TECHNICAL-SUPPORT] LPS-86407

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Hi @slnn,

can you test 75dbc33 against all the performance tests for any noticeable regressions?

@holatuwol please run the tests we talked about and let me know what you find and we'll make a choice from there.

Thanks!

**Comment by Preston-Crary** [comment]
ci:close

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @Preston-Crary 
No noticeable regression appeared with the commit https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac0
 
Here are test results:

Login:


Portal Version | Session Count | MeanTime of Login | MeanTime of Log Out
-- | -- | -- | --
BaseLine | 46878 | 276 | 81.7
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 47463 | 289 | 85.4

Web Content:

Portal Version | Session Count | MeanTime of Login | MeanTime of View Page
-- | -- | -- | --
BaseLine | 62073 | 562 | 194
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 62022 | 565 | 196

MessageBoard:

Portal Version | Session Count | MeanTime of Login | MeanTime of Add MB Thread
-- | -- | -- | --
BaseLine | 15379 | 69.5 | 92.8
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 15831 | 33.2 | 70.8

Blog:

Portal Version | Session Count | MeanTime of Login | MeanTime of Add Blog Entry
-- | -- | -- | --
BaseLine | 12278 | 294 | 359
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 12427 | 99.8 | 215

Document Library:


Portal Version | Session Count | MeanTime of Login | MeanTime of Add DL File
-- | -- | -- | --
BaseLine | 25437 | 415 | 479
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 25098 | 325 | 397


Wiki:

Portal Version | Session Count | MeanTime of Login | MeanTime of Add Wiki Page
-- | -- | -- | --
BaseLine | 16542 | 381 | 588
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 16499 | 381 | 574

AssetPublisher:

Portal Version | Session Count | MeanTime of Login | MeanTime of View Page With Filter
-- | -- | -- | --
BaseLine | 24960 | 492 | 220
https://github.com/shuyangzhou/liferay-portal/commit/75dbc33142e66aa70fe1d7f46f85bac4ba099ac | 24549 | 480 | 224

**Pull request closed without merging**
