### PR TITLE
Lps 133053

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:help

**Comment by vicnate5** [comment]
ci:reevaluate

**Comment by vicnate5** [comment]
@shuyangzhou All the failures here are also in upstream.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/102781

**Pull request closed without merging**
