### PR TITLE
[Audit Log Support]LPS-133670

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on startup.

Thanks.
Tina.

**Comment by tinatian** [comment]
FYI @epgarcia @zsigmondrab  @stian-sigvartsen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
@tinatian Here is the result:

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | e06bc300 | 44658 | 23257 | 23199 | 22442 | 23237 | 22760 | 22979 | -
PR-10049 | - | 45283 | 22829 | 22708 | 22937 | 22541 | 22785 | 22760 | -0.95%

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@tinatian please rebase and resend

**Pull request closed without merging**
