### PR TITLE
Startup optimization 263 remove dependency manager thread pool sync upgrade

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the new runs, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou new unique failure found: https://gist.github.com/kyle-miho/366d5850ef73d9673f69032004fe101f
`[beanshell] 2023-07-29 03:21:49.862 ERROR [http-nio-8080-exec-7][AuthVerifierFilter:53] graphql.AssertException: type AccountGroup not found in schema
[beanshell] graphql.AssertException: type AccountGroup not found in schema`
This can be found in some integration headless tests such as : com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest
com.liferay.headless.admin.user.resource.v1_0.test.PhoneResourceTest
com.liferay.headless.admin.user.resource.v1_0.test.OrganizationResourceTest

Double checking locally now, but letting you know in advance

**Comment by kyle-miho** [comment]
@shuyangzhou pr is good now, no unique failures found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138615

**Pull request closed without merging**
