### PR TITLE
[TS] LPS-131890 Move the log debug traces outside isSessionErrorException to avoid losing it in case a children clase redefines the method without the trace

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-131890

The LiferayPortlet.processAction method has a `try...catch` that handles the PortletException thrown by the called action method.

Inside the `isSessionErrorException(cause)` there is a **debug trace** that you can enable in order to get more information about the exception that is being handled in the catch block.

The problem with `isSessionErrorException(cause)` is it is redefined by most of the children classes of LiferayPortlet, and they don't print the information about the exception (for example, see [com.liferay.layout.admin.web.internal.portlet.GroupPagesPortlet](https://github.com/shuyangzhou/liferay-portal/blob/baeb22ef08cc78f015d2ef0cc6aa6d965991a216/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/portlet/GroupPagesPortlet.java#L224-L252) )

To avoid this, I think we should move the _log.debug trace from the isSessionErrorException method to the processAction, so the exception will be always printed in the DEBUG mode even if the isSessionErrorException is redefined in a child class.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
