### PR TITLE
[Hibernate Upgrade]LPS-133997

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

As hibernate 5 depends on javax persistence api 2.2, we need to upgrade to 2.2.1

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@tinatian this conflicts with your previous netty pull, please rebase and resend.

**Pull request closed without merging**
