### PR TITLE
LPS-72877

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@dantewang please verify whether this will cause any TCK issues, thanks!

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by dantewang** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
@shuyangzhou See https://github.com/dantewang/liferay-portal/pull/587, the result is identical with the current TCK3 result.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55364

**Pull request closed without merging**
