### PR TITLE
[TS] LPS-113218

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-113218

Hi Shuyang,
  I am sending a continuation of the fix from LPS-113218.  I've found that after the fix, the issue is still reproducible with asset-specific context attributes like [$BLOGS_ENTRY_URL$] and in other areas of the portal.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9086

**Pull request closed without merging**
