### PR TITLE
[Deprecation]LPS-105389

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

CI is having trouble now, will trigger the test once it is fixed.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by kyle-miho** [comment]
No unique failures for poshi and integration, should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82661

**Pull request closed without merging**
