### PR TITLE
Ac export optimization 5

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:forward:force

**Comment by vicnate5** [comment]
Manually forwarded and fixed the rebase error
https://github.com/brianchandotcom/liferay-portal/pull/145620

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
