### PR TITLE
Lps 90703

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Once we have test results, this is a high priority fix that is blocking our 7.2 Alpha build.

**Comment by mtambara** [comment]
@shuyangzhou All the lpkg tests have passed, the remaining failures don't seem related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68276

**Pull request closed without merging**
