### PR TITLE
LPS-X Ensure single state tracking. When tracking multiple states wit…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…h conditional collecting, an unqualified bundle would come many times for each tracking state, wasting time to recheck it multiple times.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Integration test regressions. I reproduced locally.
1. https://testray.liferay.com/home/-/testray/case_results/2273752859
2. https://testray.liferay.com/home/-/testray/case_results/2273752662

Also, the lpkg-controller test is failing. It is difficult to setup locally since you will need to convert all the jars to LPKGs.

Manual steps would be:
1. cd modules
2. ant build-app-lpkg-all -Dapp.server.parent.dir=${project.dir}/bundles -Dliferay.home=${liferay.home} -Dosgi.dir=${app.server.parent.dir}/osgi
3. Run `LPKGControllerTest` integration test
4. Start Portal
5. Run `LPKGControllerVerifyTest` integration test

```
com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
    java.lang.AssertionError: expected:<1> but was:<32>
            at org.junit.Assert.fail(Assert.java:89)
            at org.junit.Assert.failNotEquals(Assert.java:835)
            at org.junit.Assert.assertEquals(Assert.java:647)
            at org.junit.Assert.assertEquals(Assert.java:633)
            at com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest.testLPKGController(LPKGControllerVerifyTest.java:103)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
            at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
            at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
            at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
            at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
            at java.lang.Thread.run(Thread.java:750)

```

It fails on this last step here
```
// WAB should uninstall when wrapper is uninstalled

warWrapperBundle.uninstall();

Assert.assertEquals(Bundle.UNINSTALLED, warWrapperBundle.getState());
Assert.assertEquals(Bundle.UNINSTALLED, warBundle.getState());
```

The full log https://testray.liferay.com/reports/production/logs/2023-04/test-1-38/test-portal-acceptance-pullrequest(master)/7375/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou still a failure in [https://testray.liferay.com/home/-/testray/case_results/2275281411](https://testray.liferay.com/home/-/testray/case_results/2275281411). 

Rest of the issues are resolved. No new issues found.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133751

**Pull request closed without merging**
