### PR TITLE
[TECHNICAL SUPPORT] LPS-91059

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-91059

Same pull than https://github.com/shuyangzhou/liferay-portal/pull/7415 but I am also fixing `DLFileEntrySearchTest.testSearchTikaRawMetadata` test.

That test was searching the word "Word", but that word is not contained in test file "OSX_Test.docx" (see https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-test/src/testIntegration/resources/com/liferay/document/library/search/test/dependencies/OSX_Test.docx )

The test was working before *tika.xml* change because of the docx **FileUtil.extractText** bug:

- Before solving LPS-91059, extracted text is incorrect, as it is returning docx metadata as part of the content:
> [Content_Types].xml\n            \n\n\n\n_rels/.rels\n     \n\n\n\nword/_rels/document.xml.rels\n      \n\n\n\nword/document.xml\n     LIFERAY ®   Enterprise. Open Source.    For Life.    \n\n\n\nword/theme/theme1.xml\n                                                                                                                                                                                                                                \n\n\n\ndocProps/thumbnail.jpeg\n\n\nword/settings.xml\n                                     \n\n\n\nword/fontTable.xml\n                         \n\n\n\nword/webSettings.xml\n   \n\n\n\ndocProps/core.xml\n      Alexander Chow 1 2010-04-07T14:31:00Z 2010-04-07T14:32:00Z\n\n\n\nword/styles.xml\n                                                                                                                                                                           \n\n\n\ndocProps/app.xml\n  Normal.dotm 1 1 0 0 Microsoft Macintosh Word 0 1 1 false false 0 false false 12.0000

- After solving LPS-91059, extracted text is correct:
> LIFERAY ®\nEnterprise. Open Source. For Life."

But testSearchTikaRawMetadata starts failing as "Word" word is not returned by FileUtil.extractTest anymore.

In order to solve this false positive, I have changed the test word to "Enterprise", see commit https://github.com/shuyangzhou/liferay-portal/pull/7459/commits/3c81e7ce80ae092fd9e85c57e366fae778815196

Thank you

/cc @arboliveira

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69390

**Pull request closed without merging**
