### PR TITLE
[BlockingCache]LPS-115687

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 There is no unique failure for ci:test:relevant, could you please scan ci:test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
Manually Forwarded. This should have been auto-forwarded since there was no unique failures, but there is an issue that CI team is working on.
https://github.com/brianchandotcom/liferay-portal/pull/90374

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
