### PR TITLE
LPS-80949 Portlet 3.0: Only dispatch to header_portlet.jsp if a portlet implements HeaderPortlet

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou This PR falls short of a "streamlined way to process headers and renders by a single shot" that you mentioned in https://github.com/slnn/liferay-portal/pull/302 but it does improve performance by only dispatching to header_portlet.jsp if a portlet implements `HeaderPortlet`. Also note that it reverts commit https://github.com/ngriffin7a/liferay-portal/commit/64cb4c8772ae8b4dbdffd7593d06acc757e1a42f

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@ngriffin7a the tck failures are real, right?

**Comment by ngriffin7a** [comment]
@shuyangzhou I will investigate the TCK failures right now.

**Comment by ngriffin7a** [comment]
c:close

**Comment by ngriffin7a** [comment]
ci:close

**Comment by ngriffin7a** [comment]
@shuyangzhou The TCK failures were real. I neglected to move a `try {...} catch {...}` block from header_portlet.jsp to RuntimePageImpl.java -- new PR here: https://github.com/shuyangzhou/liferay-portal/pull/6461

**Pull request closed without merging**
