### PR TITLE
LPS-90074 Basic GraphQL support

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Had to change some of the curl commands to exclude Date types and rename some things, change parameters.

Query.getWorkflowLog():
```
curl 'http://localhost:8080/o/headless-workflow-graphql/v1_0' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-binary '{"query":"query {\n getWorkflowLog(workflow_45_log_45_id: 1){\n auditPerson\n commentLog\n id\n person\n previousPerson\n previousState\n state\n type\n }\n getWorkflowTask ( workflow_45_task_45_id: 1 ){\n completed\n definitionName\n description\n id\n name\n transitions\n }\n}","variables":{}}'
```

Mutation.postWorkflowTaskAssignToMe():
```
curl 'http://localhost:8080/o/headless-workflow-graphql/v1_0' -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"query": "mutation($id:Long) { postWorkflowTaskAssignToMe(workflow_45_task_45_id:$id) { id  } }", "variables": {"id": 1}}'
```

Query.getRoleWorkflowTasksPage() with page:
```
curl 'http://localhost:8080/o/headless-workflow-graphql/v1_0' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-binary '{"query":"\nquery {\n getRoleWorkflowTasksPage(role_45_id: 20105, per_page:10, page:1){\n completed\n definitionName\n description\n id\n name\n }\n}\n\n","variables":{}}}' --compressed
```

**Comment by Preston-Crary** [comment]
@petershin and @inacionery Thanks for all your help on this, wouldn't have gotten this far nearly as quickly without both of your help.

@inacionery I left out the date change since that's something you can do on your end.  I'm planning on adding support for complex input types in the future, the per_page and page params is a workaround until that is in place.

**Comment by Preston-Crary** [comment]
Schema is this one:

```
curl 'http://localhost:8080/o/headless-workflow-graphql/v1_0/schema.json'
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68083

**Comment by inacionery** [comment]
@Preston-Crary thank you!

**Pull request closed without merging**
