### PR TITLE
Startup optimization 281 object definition c s

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:objects

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by 111Anna** [comment]
@shuyangzhou Here are test results on CE and DXP.

CE:
Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker|Prepared Statement Query
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--
Baseline | f1b5b5344 |19114.3 | - | 2590.3 | - | 1483 | 91 | 98 | 855|5515|32|147
Baseline + PR-11194 | - | 19201 | -0.45% | 2574.3 | 0.62% |  1483|  91| 98 | 855|5518|33|147

DXP:
Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker|Prepared Statement Query
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--
Baseline | f1b5b5344 |20512| - | 3041.3| - | 1608 | 91 | 104 | 931|5959|33|104
Baseline + PR-11194 | - | 20483.6 | 0.14% | 3021.6| 0.65% | 1604|96 | 126 |931 |5962|33|104

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139582

**Pull request closed without merging**
