### PR TITLE
LPS-70451 Portal lib jars

### PR DESCRIPTION
**Pull request by tomwang2011**
Hi Shuyang, this set are the jars that has some basic changes mostly `Iterator while loop` to `for loop` changes and adding in more classes into the jar.

Please let this CI to finish to check if these new jars would break any tests.

Thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47775

**Pull request closed without merging**
