### PR TITLE
LPS-148703 Debug upgrade startup

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Has not happened yet, will run a few more times

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou no luck yet. I also don't see the error on upstream since we disabled the concurrent startup. I am gonna try to get it with concurrent startup back on.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou got one!
https://testray.liferay.com/reports/production/logs/2022-03/test-1-26/test-portal-acceptance-pullrequest(master)/2045/functional-upgrade-tomcat90-postgresql134-jdk8/0/7/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
@vicnate5 somehow the debug output did not print anything, I don't get how that could happen... moving this to https://github.com/shuyangzhou/liferay-portal/pull/10583 with more aggressive printing, please help me watch on the new pull.

**Pull request closed without merging**
