### PR TITLE
LPS-86435 Cannot use wrapper pattern for sharing since we need the logic in the middle of other checks

### PR DESCRIPTION
**Pull request by Preston-Crary**
@4lejandrito see my updated commit message for 0a1244d2d6745627d7b10b2a1031b643ef9a65f9, I tested this and reconfirmed the behavior.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@hhuijser can we allow Optional + Greedy with or without Dynamic? 4cc35e4 is an example of where it's useful to not have Dynamic in this case.

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by 4lejandrito** [comment]
Thanks @Preston-Crary

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73270

**Pull request closed without merging**
