### PR TITLE
Lps 143575

### PR DESCRIPTION
**Pull request by amosfong**
previous pull https://github.com/shuyangzhou/liferay-portal/pull/10536

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@stsquared99 this file https://github.com/shuyangzhou/liferay-portal/pull/10552/commits/6aebddf59d17b4ca1ae0de648362065b29e12339#diff-089e9e61b5e2416b0f6aca711ef4dd3f5b8691f5a93b6ec39454946f590c1f08 should not be committed
please fix the commit and resend.

**Comment by stsquared99** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/10556

**Pull request closed without merging**
