### PR TITLE
LPS-124678 Fix range overflow when inserting hundreds of rows using the same counter update. See batchCounter in PortletPreferencesLocalServiceImpl.

### PR DESCRIPTION
**Pull request by Preston-Crary**
Size variable seems weird for the _obtainIncrement() method.  I'm not sure if it's really being used.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Preston-Crary** [comment]
@vicnate5 can you check the commerce poshi test failure against upstream?

**Comment by vicnate5** [comment]
@Preston-Crary Test failure also consistently in upstream, not sure why this is reported as unique.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
