### PR TITLE
LPS-68837 Fix sample SQL builder

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/f6b9118822...efed59b794

**Comment by dantewang** [comment]
Hi @shuyangzhou, this commit can't be found in upstream, could you take a look?

**Comment by Preston-Crary** [comment]
Hi @dantewang,

there's still some work that I need to do on this, we want to make this change more flexible.  If you need to use the sample SQL builder you can cherry pick this commit for now.

Hope this helps

**Comment by dantewang** [comment]
Thanks! @Preston-Crary

**Pull request closed without merging**
