### PR TITLE
Aop final

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by Preston-Crary** [comment]
DDMFormFieldTypeSettingsEvaluatorTest is passing locally.

**Comment by shuyangzhou** [comment]
Is this from us https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/181010/ ?

**Comment by mtambara** [comment]
I see it failing in the upstream monitor https://test-1-19.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/31150/testReport/com.liferay.project.templates/ProjectTemplatesTest/testCompareGradlePluginVersions/

**Comment by shuyangzhou** [comment]
ok, that's good, thanks @Preston-Crary @mtambara !

**Comment by shuyangzhou** [comment]
ok, I am really leaving now, please watch out for the results, thanks guys!

**Comment by Preston-Crary** [comment]
The functional test failure is real.  I'm looking into it now.

Just go to control bar > liferay > build > page fragments and you'll see the exception.  Confirmed it's not an issue in upstream.

**Comment by Preston-Crary** [comment]
ServiceBuilder test is failing but only for WARs.

**Comment by shuyangzhou** [comment]
But it shouldn't, are they going through a different sb invocation path?

**Comment by Preston-Crary** [comment]
Not sure, the functional test failure is a race condition. So I'm not so sure it's not failing on upstream now.

**Comment by Preston-Crary** [comment]
I'll focus on the functional test failure and ask peter if he can look into the SB failure.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7091

**Comment by Preston-Crary** [comment]
Looking into the SB failure now.

**Comment by Preston-Crary** [comment]
SB failure looks like it's related to the portal/tools/sdk/build-common-plugin.xml file. But I'm not sure how this file is being created.

**Comment by Preston-Crary** [comment]
https://github.com/liferay/liferay-plugins/blob/7.0.x/build-common-plugin.xml#L73-L108

**Comment by shuyangzhou** [comment]
Are we still checking in the SDK.zip in master? It used to be an ant target extracting the zip from sdk repo, then manually copy and check into portal repo

**Comment by shuyangzhou** [comment]
https://github.com/shuyangzhou/liferay-portal/blob/master/build-common.xml#L1464

Seems like we are downloading a released version?
If Brain is still in office, ask him for details. And the worst case is we need to fake a release of it. Just like faking other grade caches. Peter might know something about it too. We don't have to fix it, if it is too complex, as a real release will automatically fix it. But at least making sure we have no other failures after your race condition fix. Sorry, I am having very bad phone reception, I can look into it tonight.

**Comment by Preston-Crary** [comment]
Asked peter about it and looked into the ant targets he said maybe Chas would know - Chas doesn't seem to be in the office.  I think the easiest solution is to just leave out the 3 portlet-spring.xml files from the regenerate util we have a real release.

Brian said if it's the only failure he'll just make a real release with the changes.  I think the only thing needed is https://github.com/Preston-Crary/liferay-plugins-ee/pull/10/commits/5b6b6a584a89c5543512fce974219f3255d6dad4, but haven't been able to fake the release in order to test it.

**Pull request closed without merging**
