### PR TITLE
[Deprecation]LPS-104836

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the results, thanks!

**Comment by vicnate5** [comment]
@koor4356

**Comment by koor4356** [comment]
@tinatian @shuyangzhou, "com.liferay.journal.trash.test.JournalArticleTrashHandlerTest fails." It looks related to this pull request. It passes on one and fails the other. Can you take a look?

https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363343/

**Comment by tinatian** [comment]
@dantewang @yuhai Please check if JournalArticleTrashHandlerTest failures are related.

Thanks.
Tina

**Comment by vicnate5** [comment]
Since this was inconsistent, running a couple more times so we have more data

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian @yuhai @dantewang @koor4356 This looks good actually, the Journal tests did not fail again, likely this is related to known index test flakiness at head.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81995

**Pull request closed without merging**
