### PR TITLE
LPS-121714 Service builder should remove duplicate unique indexes

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @shuyangzhou,

Removing duplicate finders looks a bit tricky since it's not always clear to me which one should be removed and timing seems bad for major version changes.  So for now just cleaning up the indexes, some unique indexes got left behind from changing constraints, those needed to be removed manually first in 28becca.  I'm not sure if we need upgrades for all of these or if we can wait until the automatic index cleanup is run by future upgrades.  All these changes only work for unique indexes because otherwise there are issues with ranged comparators (unique has to be `==`), see d267df9a.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou, @Preston-Crary why did we implemented this? From a constraint point of view it makes sense, but from an index one they aren't redundant.

For example we've removed:
` create unique index IX_9B44D13C on JournalArticleLocalization (companyId, articlePK, languageId[$COLUMN_LENGTH:75$], ctCollectionId);` because we already have  `create unique index IX_5593D868 on JournalArticleLocalization (articlePK, languageId[$COLUMN_LENGTH:75$], ctCollectionId);` but that implies not using the index when someone wants to filter only by _companyId_ and _articlePK_.

/cc @achaparro

**Comment by Preston-Crary** [comment]
@marianoalvarosaiz if an index is needed for companyId, articlePK - add it separately.  It shouldn't be a unique index if that's the reason.

**Comment by marianoalvarosaiz** [comment]
@Preston-Crary the reason is that order in index matters, and removing a simple index like the following one:

` create unique index IX_6B9E4A66 on DLOpenerFileEntryReference (referenceType[$COLUMN_LENGTH:75$], fileEntryId); `

You're creating creating a performance regression in every method that uses: _DLOpenerFileEntryReferencePersistenceImpl.findByR_F(String referenceType, long fileEntryId)_ because now we're performing a FULL SCAN with that finder.

This is just an example, but with this implementation we're open to generate performance regressions when defining finders that aren't going to be backed up by database indexes.

**Comment by Preston-Crary** [comment]
> You're creating creating a performance regression in every method that uses: DLOpenerFileEntryReferencePersistenceImpl.findByR_F(String referenceType, long fileEntryId) because now we're performing a FULL SCAN with that finder.

Here's the mysql explain for that query:
```
mysql> explain select dlOpenerFileEntryReferenceId from DLOpenerFileEntryReference where referenceType = 'abc' and fileEntryId = 11;
+----+-------------+----------------------------+------------+-------+---------------+-------------+---------+-------+------+----------+-------+
| id | select_type | table                      | partitions | type  | possible_keys | key         | key_len | ref   | rows | filtered | Extra |
+----+-------------+----------------------------+------------+-------+---------------+-------------+---------+-------+------+----------+-------+
|  1 | SIMPLE      | DLOpenerFileEntryReference | NULL       | const | IX_54148667   | IX_54148667 | 9       | const |    1 |   100.00 | NULL  |
+----+-------------+----------------------------+------------+-------+---------------+-------------+---------+-------+------+----------+-------
```

**Comment by marianoalvarosaiz** [comment]
Sorry for the delay, I was on vacation.

Unique index keys can be null. Try the following:

```
INSERT INTO DLOpenerFileEntryReference(dlOpenerFileEntryReferenceId, groupId, companyId, userId, userName, createDate, modifiedDate, referenceKey, referenceType, fileEntryId, type_)  VALUES 
	(1,1,1,1,'userName1',NULL,NULL,'1key','1type',1,1),
	(2,1,1,1,'userName1',NULL,NULL,'1key','1type',2,2),
	(3,1,1,1,'userName1',NULL,NULL,'1key','1type',NULL,3),
	(4,1,1,1,'userName1',NULL,NULL,'1key','1type',NULL,4),
	(5,1,1,1,'userName1',NULL,NULL,'1key','2type',NULL,4),
	(6,1,1,1,'userName1',NULL,NULL,'1key','3type',NULL,4);
```

Now execute the explain plan in mysql:
```
mysql> explain select dlOpenerFileEntryReferenceId from DLOpenerFileEntryReference where referenceType = '1type' and fileEntryId is null;
+----+-------------+----------------------------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table                      | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+----------------------------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | DLOpenerFileEntryReference | NULL       | ALL  | IX_54148667   | NULL | NULL    | NULL |    6 |    16.67 | Using where |
+----+-------------+----------------------------+------------+------+---------------+------+---------+------+------+----------+-------------+
```

I know that by API we don't allow nulls in `DLOpenerFileEntryReferencePersistenceImpl.findByR_F(String referenceType, long fileEntryId)` or even in the insertion, but it was just an example of what could happen:

Assume a custom development like the previous one with _fileEntryId_ being a String. We could have the previous all access situation. We could have it also if the customer decides to use that filter in a custom sql.

**Pull request closed without merging**
