### PR TITLE
LPS-97974,LPS-97975 Remove LayoutVersion and LayoutSetVersion

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Fixed rebase conflict

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75860

**Pull request closed without merging**
