### PR TITLE
LPS-147607 MimeResponseImpl.reset() does clear response output and header properties as required by the Portlet 3.0 Javadoc

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:test:tck

**Comment by ngriffin7a** [comment]
@shuyangzhou I don't think that `MimeResponse.reset()` is actually called anywhere in the codebase, except for InvokerPortletImpl.java during handling of unexpected failures/exceptions:

```
➤ git grep -i "response.*reset" | egrep -v -i "preset|servlet|resetuser|tck|springmimeeesponsebean"
portal-impl/src/com/liferay/portlet/internal/InvokerPortletImpl.java:			stateAwareResponseImpl.reset();
```

Because of that, I can't see how any of the failures reported by `ci:test` are related to this PR. It passes the TCK, which is the only relevant suite of tests. And one of the reasons why this problem was never identified until now is because the TCK doesn't test the `MimeResponse.reset()` method sufficiently.

I think that this would be a very easy PR for you to review. Only a small handful of lines added.

Thanks in advance,

Neil

**Comment by shuyangzhou** [comment]
@ngriffin7a can you add an unit test for this to assert the behavior in order to prevent future regression?

**Comment by ngriffin7a** [comment]
@shuyangzhou I wrote a test for the [JSR 378](https://jcp.org/en/jsr/detail?id=378) TCK that will ensure against regression. Will that suffice? I don't have time in my schedule right now to write a JUnit test.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113675
The tck test is enough, thanks @ngriffin7a !

**Pull request closed without merging**
