### PR TITLE
LPS-X Delay ServiceLatch service ungetting after openOn Runnable invo…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…cation to avoid unnecessay non-immediate component deactivate/re-activate during dependencies collecting.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Pull request closed without merging**
