### PR TITLE
LPS-79274 PortletFilter.getInitParameterNames() contains names that are not init-params (see also LRDOCS-5097)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: When you get a chance, please take a look at these failures and if none are caused by the commit in this PR, let us know so that Shuyang can review. Thanks.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@ngriffin7a I'll take a look after lunch. I think it's ok, just want to check on the Websphere failure

**Comment by jpince** [comment]
@shuyangzhou  this pull looks good, please review

weblogic failure #1 - unrelated
```
     [exec] <Mar 30, 2018 5:40:58 PM GMT> <Error> <osgi.logging.com_liferay_apio_architect_application> <BEA-000000> <FrameworkEvent ERROR 
     [exec] java.lang.IllegalStateException: The service has been unregistered
```
retest - weblogic passed

**Comment by ngriffin7a** [comment]
Thanks @jpince !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56800

**Pull request closed without merging**
