### PR TITLE
LPS-X Pull out Depot Role description verifying logic into a VerifyPr…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ocess to avoid repeated startup time verifying.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this is clean, right?

**Comment by vicnate5** [comment]
@shuyangzhou Yea, depot tests ran and no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128780

**Pull request closed without merging**
