### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@vicnate5 looks okay to me, can you double check.  Only new changes are for asset tags.

**Comment by vicnate5** [comment]
@Preston-Crary The Segments service and Blogs service failures are not occurring at head
https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/344640/#showFailuresLink

**Comment by vicnate5** [comment]
Also, Wildfly and Jboss does not startup
```
ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.module.service."deployment.ROOT.war".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.ROOT.war".main: WFLYSRV0179: Failed to load module: deployment.ROOT.war
 	at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:116)
 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: org.jboss.modules.ModuleLoadException: Error loading module from /opt/dev/projects/github/liferay-portal/bundles/wildfly-16.0.0/modules/com/liferay/portal/main/module.xml
 	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:339)
 	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:295)
 	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:256)
 	at org.jboss.modules.LocalModuleFinder.parseModuleXmlFile(LocalModuleFinder.java:250)
 	at org.jboss.modules.LocalModuleFinder.lambda$findModule$1(LocalModuleFinder.java:195)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:195)
 	at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:693)
 	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:686)
 	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:496)
 	at org.jboss.modules.DelegatingModuleLoader.preloadModule(DelegatingModuleLoader.java:57)
 	at org.jboss.modules.ModuleLoader.preloadExportedModule(ModuleLoader.java:411)
 	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:452)
 	at org.jboss.as.server.moduleservice.ServiceModuleLoader.preloadModule(ServiceModuleLoader.java:144)
 	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:397)
 	at org.jboss.modules.Module.addPaths(Module.java:1252)
 	at org.jboss.modules.Module.link(Module.java:1622)
 	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
 	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:296)
 	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:280)
 	at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:93)
 	... 8 more
 Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add resource root 'com.liferay.petra.sql-dsl.jar' at path 'com.liferay.petra.sql-dsl.jar' (position: END_TAG seen ...t.jar" />\n\t\t<resource-root path="com.liferay.petra.sql-dsl.jar" />... @14:57) caused by: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/wildfly-16.0.0/modules/com/liferay/portal/main/com.liferay.petra.sql-dsl.jar (No such file or directory)
 	at org.jboss.modules.xml.ModuleXmlParser.parseResourceRoot(ModuleXmlParser.java:1131)
 	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:945)
 	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:710)
 	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:471)
 	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:337)
 	... 28 more
 Caused by: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/wildfly-16.0.0/modules/com/liferay/portal/main/com.liferay.petra.sql-dsl.jar (No such file or directory)
 	at java.util.zip.ZipFile.open(Native Method)
 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
 	at java.util.jar.JarFile.<init>(JarFile.java:166)
 	at java.util.jar.JarFile.<init>(JarFile.java:145)
 	at org.jboss.modules.xml.JDKSpecific.getJarFile(JDKSpecific.java:33)
 	at org.jboss.modules.xml.ModuleXmlParser$DefaultResourceRootFactory.createResourceLoader(ModuleXmlParser.java:1628)
 	at org.jboss.modules.LocalModuleFinder.lambda$new$0(LocalModuleFinder.java:103)
 	at org.jboss.modules.xml.ModuleXmlParser.parseResourceRoot(ModuleXmlParser.java:1129)
 	... 32 more
``` 


https://testray.liferay.com/reports/production/logs/test-1-2/1579565027056/test-portal-acceptance-pullrequest(master)/5644/functional-smoke-wildfly160-mariadb102-jdk8/0/0/jenkins-console.txt.gz

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
@vicnate5 okay thanks

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8759

**Pull request closed without merging**
