### PR TITLE
Bsf removal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho Can you check this this morning?

**Comment by kyle-miho** [comment]
failures are unrelated @shuyangzhou

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111978

**Pull request closed without merging**
