### PR TITLE
LPS-60355 Lower severity and not fail tests

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
this comes from https://github.com/brianchandotcom/liferay-portal/pull/34116#issuecomment-170182615

**Comment by shuyangzhou** [comment]
@dantewang @slnn please run a performance check on this first, thanks!

**Comment by slnn** [comment]
ok, got it

**Comment by csierra** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Please see the email @slnn sent.

**Comment by csierra** [comment]
Hi all, 

I don't have any email from @slnn... 

anyhow... this is not a new feature, this is a bug fix. I would rather focus on having a correct behavior and then try to optimize. If the current behavior in master is not correct, how can we know we can have a correct behavior that's more performant?

**Comment by shuyangzhou** [comment]
I resent the email to you, it was sent to a wrong address.

I am not rejecting your fix, only asking for an effort to make it better first. You know your changes better than anyone, so you should get a better change to make it better. Otherwise this is be just another 12% performance dropping bomb dropped on my team.

Please at least try to make a difference, and you have the performance test env in Spain, you should be able spin this up quickly.

Thanks

**Comment by csierra** [comment]
Hey Shuyang, 

I will try my best. Do you have any clues an what might be causing the performance regression? 

Bests.

**Comment by shuyangzhou** [comment]
Sorry, I have not read your change yet. I am heavily loaded now. If you got stuck, I can try to help sometime later this week.

In the mean time, it will be the best if you can use the benchmark env in spain. However if for some reason you can not get it working, feel free to ping back to @dantewang @slnn for profiles and more test runs.

**Comment by csierra** [comment]
thank you Shuyang... 

it is ok... I will try to find it out...

Thanks

**Pull request closed without merging**
