### PR TITLE
[Bug Fix]LPS-127348

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Is there any other test I need to run for this change?

Thanks
Tina.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou This is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105527

**Pull request closed without merging**
