### PR TITLE
LPS-X Always save scanned annotated classes to avoid restart bundle r…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…esource listing.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me to check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145350

**Pull request closed without merging**
