### PR TITLE
LPS-119897 Multiple Upload causes StaleObjectStateException when buffered increment is disabled for DLFolderEntry

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @shuyangzhou 

Could you please review this pull request?

`AopInvocationHandler._createAopMethodInvocation` iterates over all `chainableMethodAdvices`. `BufferedIncrementAdvice` is one of them, but when **buffered.increment.enabled[DLFolderEntry]=false**, no method context will be created for any of DLFolderEntry's methods, thus `BufferedIncrementAdvice` will be skipped.
However, before iterating over the `chainableMethodAdvices`, a `transactionAttributeAdapter` is created for the method, as transactions are enabled for `DLFolderLocalServiceImpl.updateLastPostDate()`, and `nextChainableMethodAdvice` will be `transactionInterceptor`.
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/spring/aop/AopInvocationHandler.java#L94-L104

And `transactionInterceptor` calls `DLFolderLocalServiceImpl.updateLastPostDate()`.

By preventing `BufferedIncrementAdvice` to return **null** when `bufferedIncrementProcessor == null ` (https://github.com/shuyangzhou/liferay-portal/commit/53a417f7ecfb9678a0d28adbc1b90e788f8fe303#diff-b5b16c8182c15afb2119d4557055be8aL61-L64) we ensure that nextChainableMethodAdvice will be `BufferedIncrementAdvice`.

By returning `nullResult` when `bufferedIncrementProcessor == null`, `DLFolderLocalServiceImpl.updateLastPostDate()` wont be called by `BufferedIncrementAdvice.invoke()`.
https://github.com/shuyangzhou/liferay-portal/commit/53a417f7ecfb9678a0d28adbc1b90e788f8fe303#diff-b5b16c8182c15afb2119d4557055be8aR75

This is a similar approach that is in 7.1.x.
https://github.com/liferay/liferay-portal-ee/blob/7.1.x/portal-impl/src/com/liferay/portal/increment/BufferedIncrementAdvice.java#L61-L63

Thank you and best regards,
István

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@IstvanD this is wrong. By disabling ```buffered.increment.enabled[DLFolderEntry]=false```, it means to skip the buffered increment behavior, which means the service method will be called in place by the caller thread, rather than the buffered increment thread. This is on purpose. You can not just throw away the update when disabling buffered increment. The update must happen, the only difference is where does it happen and how it is performed.

The StaleObjectStateException means there are some updates that are not performed against the last version of the entries. This generally means some code holds out of date copies of the models. Or there are some real concurrent updates against the same entry. You need to find out how did that happen and correct the logic.

**Comment by ericyanLr** [comment]
Hi @shuyangzhou, 

Based on the portal properties description, it sounds like the update method is expected to be thrown away when disabling the buffered increment [(portal.properties#L6052-L6056):](https://github.com/liferay/liferay-portal/blob/7.3.4-ga5/portal-impl/src/portal.properties#L6052-L6056)
```
# Disabling buffered increment logic will result in the service methods
# annotated with the @BufferedIncrement annotation being skipped. Only do
# this if you want to completely disable the view counters.
```

From our testing, this behavior is still observed in 71x.

However, this behavior changed in 72x/master due to:
- Ticket: [LPS-86406 - Centralize AOP control and registration allowing new MethodInterceptors to be easily globally applied](https://issues.liferay.com/browse/LPS-86406)
- Commit: https://github.com/liferay/liferay-portal/commit/60caf265edfab1e14d6b2de1c20ac9f3b3cabccd

Looking at [LPS-86406](https://issues.liferay.com/browse/LPS-86406), the goal of this ticket wasn't to change the logic of BufferedIncrementAdvice. However, it introduced this change in behavior, where the annotated service methods are no longer being skipped.

With that in mind, this sounds like a regression bug, which this PR is trying to fix.

Can you help confirm the expected behavior of setting `buffered.increment.enabled`?
Thanks!

**Comment by shuyangzhou** [comment]
Ouch... That's indeed a mismatch between the description and the behavior. But the behavior is right, the description needs to be updated. Skipping the target service call will have some unexpected side affect.

@Preston-Crary can you update the description to match up the behavior?
@IstvanD and @ericyanLr please find out why the StaleObjectStateException is happening.

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9403 for an updated description.

**Comment by ericyanLr** [comment]
Hi @shuyangzhou ,

**In regards to:**
> Skipping the target service call will have some unexpected side affect.

Can you help elaborate more on this concern?

Looking at [LPS-86406](https://issues.liferay.com/browse/LPS-86406), the logic change made to BufferedIncrementAdvice, did not seem intentional. 

And if so, doesn't that mean this unintentional change has already introduced an unexpected side effect?

**Comment by shuyangzhou** [comment]
@ericyanLr we can not just skip the service call. Sometimes it is just doing a timestamp update in the service method, then it is kind of harmless. But other times we are updating some more meaningful values. Skipping the service call might cause unexpected behavior. What will actually happen is depending on what does the service method do.

The change from LPS-86406 was indeed not on purpose, but it is the right thing to do. The old behavior was wrong. It was like that because some implementation limits, but after LPS-86406 we can just do the right thing. The portal.properties was not updated accordingly, that was a mistake. @Preston-Crary sent out the update to that already.

We should stick with the current behavior, don't try to go back.

**Comment by ericyanLr** [comment]
@shuyangzhou, gotcha, thanks for the explanation. 

We'll work on resolving this on the DL side for this specific use-case.

**Pull request closed without merging**
