### PR TITLE
LPS-72079 Avoid going through WikiPageResourceLocalService in WikiPageLocalService for method going directly to the persistence

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48521

**Pull request closed without merging**
