### PR TITLE
LPS-X Refactor ModelListenerRegistrationUtil to use ServiceTrackerMap…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… and sort ModelListeners by class name.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou a few hundred integration tests failing here due to 
```
##
## com.liferay.fragment.service.test.FragmentCompositionServiceTest > testUpdateFragmentCollectionId
##

	java.lang.ClassCastException: com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl cannot be cast to java.util.Map
		at com.liferay.portal.test.rule.PersistenceTestRule.beforeMethod(PersistenceTestRule.java:63)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:94)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
		at com.liferay.portal.test.rule.TransactionalTestRule$1.lambda$evaluate$0(TransactionalTestRule.java:125)
		at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:36)
		at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39)
		at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28)
		at com.liferay.portal.test.rule.TransactionalTestRule$1.evaluate(TransactionalTestRule.java:120)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
		at java.lang.Thread.run(Thread.java:745)

```

Full log https://testray.liferay.com/reports/production/logs/2023-06/test-1-39/test-portal-acceptance-pullrequest(master)/5369/modules-integration-mysql57-jdk8/2/0/jenkins-console.txt.gz?authuser=0

I can reproduce locally.

Most of the integration tests failures here are this issue
https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2351305006&testrayCaseTypeId=60250099&testrayRunId=2351305173

For re-runs, just use relevant since it is already picking up thousands of tests.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Integration tests failures on latest results
1. https://testray.liferay.com/home/-/testray/case_results/2353796214 
2. https://testray.liferay.com/home/-/testray/case_results/2353795050 
3. https://testray.liferay.com/home/-/testray/case_results/2353794716
4. https://testray.liferay.com/home/-/testray/case_results/2353794308

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
CI results didn't import yet, asked CI team for help.

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136588

**Pull request closed without merging**
