### PR TITLE
Lps 143953 3

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou The removal is causing an issue with building releases in https://github.com/liferay/liferay-release-tool-ee

This class is using it https://github.com/liferay/liferay-release-tool-ee/blob/039c58d46e06376757eea2f5ac6be758a14bc784/ext/7.4.x/ext-impl/src/com/liferay/portal/ee/tools/ClassEncryptorBuilder.java#L30
```
compile:
     [echo] March 2, 2022 at 05:36 PM
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/modules/core/portal-compat/petra/util-java-compat/classes
 [proguard] ProGuard, version 5.2
 [proguard] ProGuard is released under the GNU General Public License. You therefore
 [proguard] must ensure that programs that link to it (net.sf.antcontrib.logic, ...)
 [proguard] carry the GNU General Public License as well. Alternatively, you can
 [proguard] apply for an exception with the author of ProGuard.
 [proguard] Reading program directory [/opt/dev/projects/github/liferay-portal/portal-impl/classes] (filtered)
 [proguard] Reading library jar [/opt/java/jdk1.8.0_121-x64/jre/lib/jce.jar]
 [proguard] Reading library jar [/opt/java/jdk1.8.0_121-x64/jre/lib/rt.jar]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/lib/development/servlet-api.jar]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/lib/portal/commons-io.jar]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/tmp/lib-pre/com.liferay.petra.encryptor.jar]
 [proguard] Reading library jar [/opt/dev/projects/github/liferay-portal/tmp/lib-pre/com.liferay.petra.string.jar]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/portal-impl/classes] (filtered)
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/portal-kernel/classes]
 [proguard] Reading library directory [/opt/dev/projects/github/liferay-portal/util-java/classes]
 [proguard] Preparing output directory [/opt/dev/projects/github/liferay-portal/portal-impl/obfuscated-classes]
 [proguard]   Copying resources from program directory [/opt/dev/projects/github/liferay-portal/portal-impl/classes] (filtered)
     [move] Moving 24 files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [mkdir] Created dir: /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/ext-impl/classes
    [javac] /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/build-release-license.xml:120: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/ext-impl/classes
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/ext-impl/classes
     [copy] Copied 7 empty directories to 5 empty directories under /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/ext-impl/classes
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.propertiesException in thread "main" java.lang.NoClassDefFoundError: org/apache/tools/ant/DirectoryScanner
     [java] 
     [java] 	at com.liferay.portal.ee.tools.ClassEncryptorBuilder._encryptClasses(Unknown Source)
     [java] 	at com.liferay.portal.ee.tools.ClassEncryptorBuilder.<init>(Unknown Source)
     [java] 	at com.liferay.portal.ee.tools.ClassEncryptorBuilder.main(Unknown Source)
     [java] Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.DirectoryScanner
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	... 3 more
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6694: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6728: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:9752: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release-slim.xml:44: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/build-release-license.xml:140: Java returned: 1
```
https://testray.liferay.com/reports/production/logs/2022-03/test-1-27/test-portal-acceptance-pullrequest(master)/2023/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by vicnate5** [comment]
No other issues found in test results.

**Comment by shuyangzhou** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@shuyangzhou After the merge of the fix on the release side, then this is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114169

**Pull request closed without merging**
