### PR TITLE
LPS-41758 This isn't really a bug but people tend to think it looks l…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…ike one. Only append to the ID when the value is not null. Only run JS.getSafeName() on the unsafe values.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Not sure but this might affect functional tests since it's changes ID generation.

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58423

**Pull request closed without merging**
