### PR TITLE
Lps 127840

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This is good, the failure here is a flaky failure at head, I see it on a few other pulls.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/99628

**Pull request closed without merging**
