### PR TITLE
[Bug Fix]LPS-132645 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @ericyanLr @mtambara

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou No unique failures here

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/102267

**Pull request closed without merging**
