### PR TITLE
LPS-88547 Cache configuration

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
Please resend after solving the thread context classloader question.

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/7232

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66413

**Pull request closed without merging**
