### PR TITLE
[Bug Fix]LPS-111208

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

According to Yuxing, the usage in elasticsearch modules will be addressed in another ticket for search team to handle/review.

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
