### PR TITLE
[Deprecation]LPS-104241

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Cloud you please help scan the result?

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian Tests had an indexing issue for UserGroups. I am going to check manually, it could be random. No other issues seen in the tests.

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou Cannot reproduce the User Group issue. This should be good to go.

**Comment by vicnate5** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/8577

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
