### PR TITLE
Startup optimization 318 elasticsearch search engine activation

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
I got this same WARN during re-index and this ERROR when navigating through the portal

```
2023-10-16 15:27:29.937 ERROR [liferay/scheduler_dispatch-4][ParallelDestination:50] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.portal.workflow.metrics.internal.scheduler.WorkflowMetricsSLADefinitionTransformerSchedulerJobConfiguration, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@729d628, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.portal.workflow.metrics.internal.scheduler.WorkflowMetricsSLADefinitionTransformerSchedulerJobConfiguration}}
com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-26/test-portal-acceptance-pullrequest(master)/11524/functional-tomcat90-mysql57-jdk8/3/2/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@catarineaguiar appended a fix commit, please try again, thanks!

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the results, I think @catarineaguiar is already off for the day. Thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found in functional test [Elasticsearch7#SwitchSidecarToRemote](https://testray.liferay.com/home/-/testray/case_results/2441878022?tab=result)

**Steps to reproduce**
1. Start portal
2. In source directory run "ant -f build-test-elasticsearch7.xml start-elasticsearch" to switch to remote elasticsearch
3. Go to Control Panel > Search > Index Options
4. Reindex all search indexes
5. Go to home page and try searching in the search widget

Expected results: The reindex is successfull and searching works
Actual results: The reindex fails. As a result, searching does not work and a temporarily unavailable error appears when trying to use the search widget. 

```
[beanshell] 2023-10-16 19:40:43.122 ERROR [default-20][BulkDocumentRequestExecutorImpl:48] failure in bulk execution:
[beanshell] [1]: index [liferay-0], type [_doc], id [com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.site.navigation.menu.web.internal.configuration.SiteNavigationMenuWebTemplateConfiguration], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=pipeline with id [timestamp] does not exist]]]
[beanshell] 2023-10-16 19:40:43.123 ERROR [liferay/background_task-2][SearchEngineInitializer:252] Error encountered while reindexing
[beanshell] java.util.concurrent.ExecutionException: com.liferay.portal.kernel.search.SearchException: com.liferay.portal.kernel.exception.SystemException: Update failed
[beanshell] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
[beanshell] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer._reindex(SearchEngineInitializer.java:229) [bundleFile:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:70) [bundleFile:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:66) [bundleFile:?]
[beanshell] 	at com.liferay.portal.search.internal.background.task.ReindexPortalBackgroundTaskExecutor.reindex(ReindexPortalBackgroundTaskExecutor.java:70) [bundleFile:?]
[beanshell] 	at com.liferay.portal.search.internal.background.task.BaseReindexBackgroundTaskExecutor.execute(BaseReindexBackgroundTaskExecutor.java:45) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:32) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:63) [bundleFile:?]
[beanshell] 	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:115) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:39) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:25) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:65) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:47) [bundleFile:?]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
[beanshell] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[beanshell] Caused by: com.liferay.portal.kernel.search.SearchException: com.liferay.portal.kernel.exception.SystemException: Update failed
[beanshell] 	at com.liferay.portal.kernel.search.BaseIndexer.reindex(BaseIndexer.java:462) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:89) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:209) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:193) ~[?:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
[beanshell] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
[beanshell] 	... 3 more
[beanshell] Caused by: com.liferay.portal.kernel.exception.SystemException: Update failed
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexWriter.updateDocument(ElasticsearchIndexWriter.java:351) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.IndexWriterHelperImpl.updateDocument(IndexWriterHelperImpl.java:501) ~[?:?]
[beanshell] 	at com.liferay.configuration.admin.web.internal.search.ConfigurationModelIndexer.doReindex(ConfigurationModelIndexer.java:358) ~[?:?]
[beanshell] 	at com.liferay.configuration.admin.web.internal.search.ConfigurationModelIndexer.doReindex(ConfigurationModelIndexer.java:375) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.search.BaseIndexer.reindex(BaseIndexer.java:456) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:89) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:209) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:193) ~[?:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
[beanshell] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
[beanshell] 	... 3 more
[beanshell] 2023-10-16 19:40:43.136 INFO  [liferay/background_task-2][SearchEngineInitializer:255] Reindexing failed
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-29/test-portal-acceptance-pullrequest(master)/8403/functional-tomcat90-mysql57-jdk8/3/2/jenkins-console.txt.gz?authuser=0)

Note: Looking at a passing [run](https://testray.liferay.com/home/-/testray/case_results/2442062800) it looks like all the errors that appear before reindexing are expected. Searching should not work until after the reindex. The regression here is that the re-index fails so search does not work.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143081

**Pull request closed without merging**
