### PR TITLE
Lps 128860 5

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:reevaluate:1197401_8517

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@achaparro is this pull incomplete? How is this can be used for anything real https://github.com/shuyangzhou/liferay-portal/pull/10136/commits/fd5b9e02f308479d461429584cec9454482ee77d#diff-0cc31e20c7435b0bb5a700efbf64e8728d1867e4216fd2d8f616df6fe619d0dcR48 ?

**Comment by achaparro** [comment]
Hi @shuyangzhou,

No, this pull only contains the registration and API of the upgrade report. We will add the implementation once this is approved.

**Comment by SamZiemer** [comment]
Hi @shuyangzhou, based on Alberto's answer, is this sufficient to continue with this pull request?

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
