### PR TITLE
Lps 116495

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:test:analytics-cloud

**Comment by vicnate5** [comment]
ci:test:tango-analytics-cloud

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
The relevant failures are due Brian Chan's publishing today (Same as https://github.com/drewbrokke/liferay-portal/pull/1171#issuecomment-692363029)

We will need to rerun this.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou This is ready for forward.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 manual forward?

**Comment by vicnate5** [comment]
@shuyangzhou Yea...It should have forwarded cuz there was nothing unique. But go ahead and manually forward.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/94268

**Pull request closed without merging**
