### PR TITLE
[License]LPS-121001 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @vicnate5, 
Please verify this change,  make sure it not break any existed test.

Please also add new test cases to test when you removed enterprise license module for a dxp release build, you should not see commerce on UI, please note you will see the commerce related modules installed and activated from gogoshell, but all the commerce features are not working cause corresponding components are not enabled.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant failures due to BChan publishing

**Comment by vicnate5** [comment]
@tinatian 
PASSED Manual Testing

Test Results at: 
https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit#gid=1668987283&range=AR2

New test added to Test Plan and executed for this ticket: https://docs.google.com/document/d/1Xt2NGuPcdCHmnnJ8hzdnmvzzq2aA18VRbTXTxocW_q4/edit?ts=5f0c9488#heading=h.pw8poat6tchm

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Pull request closed without merging**
