### PR TITLE
LPS-80164 Portlet 3.0: Expose API for custom portlet modes

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak: Please review these failures and if they are unrelated let us know so that Shuyang can review. Thanks.

**Comment by timpak** [comment]
hey @ngriffin7a the failures look unrelated to your changes.

@shuyangzhou please review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57844

**Pull request closed without merging**
