### PR TITLE
LPS-160225 Switch back to Serializer/Deserializer for raw data type e…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ncoding/decoding to avoid increasing of file read/write count.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122139

**Pull request closed without merging**
