### PR TITLE
[Log4j]LPS-127067

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please help scan the results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you scan for regressions?

**Comment by tinatian** [comment]
Resent at https://github.com/shuyangzhou/liferay-portal/pull/9807.
@zhangyan0701 Please scan the results of the new pull once it is finished.
@yuhai @dantewang Please rebase your pull based on this.

Thanks.
Tina.

**Pull request closed without merging**
