### PR TITLE
Embedded potal web all

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, this pull has all the fixes we have so far.

**Comment by vicnate5** [comment]
@shuyangzhou Looks good. There is a [real semver issue](https://testray.liferay.com/reports/production/logs/2021-07/test-1-14/test-portal-acceptance-pullrequest(master)/8408/modules-semantic-versioning-jdk8/0/8/jenkins-console.txt.gz) on the gradle plugins, but no regressions found in these test results

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! Pushed a rebased fix for the semantic versioning issue.

@GinsonRen @slnn I need a startup regression and runtime regression for login and some other test case that you see fit, thanks!

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the startup regression test result, and I will update the runtime result later since the main evn was quite busy recently.

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 880952a2e | 44741 | 22641 | 22831 | 22626 | 22442 | 22852 | 22678.4 | -
PR-10148 | - | 44657 | 22894 | 22678 | 22999 | 22700 | 22763 | 22806.8 | 0.57%

**Comment by slnn** [comment]
Hi @GinsonRen 

I have updated benchmark project for runtime test in https://github.com/slnn/liferay-benchmark-ee/pull/160

**Comment by shuyangzhou** [comment]
@GinsonRen @slnn any update on the runtime performance testing? I need this out soon.

**Comment by shuyangzhou** [comment]
Forwarding at https://github.com/shuyangzhou/liferay-portal/pull/10160 , if there is any runtime performance issue, let's revisit it later.

**Pull request closed without merging**
