### PR TITLE
Revert "LPS-96736 Adding support for clay dropdown items"

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
cc @4lejandrito @adolfopa

**Comment by 4lejandrito** [comment]
I would suggest to try https://github.com/4lejandrito/liferay-portal/pull/281 and see if it fixes the regression before reverting the whole thing.

**Comment by dantewang** [comment]
Hi @shuyangzhou,

@4lejandrito will provide a pull to disable the things added to Blog by LPS-96736, please see the email thread. I will close this revert pull for now.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74827.

**Pull request closed without merging**
