### PR TITLE
LPS-62450 Sitemap.xml performance

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased, minor conflicts.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Rebased conflicts.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/37088

**Pull request closed without merging**
