### PR TITLE
LPS-85610 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LPS-85610, tested on 7.1.x at https://github.com/vicnate5/liferay-portal-ee/pull/133

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 in module.framework.properties.org.osgi.framework.bootdelegation it has "javax.xml.bind", and in portal bootstrap, we added a bunch "javax.xml.bind." packages. That looks duplicated to me.
If javax.xml.bind is moved out of jdk, then it should not be part of the bootdelegation anymore. Please confirm, if so, please remove it and retest, thanks!

**Comment by anthony-chu** [comment]
@shuyangzhou thanks for the clarification. i was able to start up the bundle without `javax.xml.bind` in bootdelegation.

**Comment by anthony-chu** [comment]
ci:close

**Comment by anthony-chu** [comment]
Resent without `javax.xml.bind` here: https://github.com/shuyangzhou/liferay-portal/pull/6913

**Pull request closed without merging**
