### PR TITLE
LRQA-69881 Implement required method in interface to prevent compile error but since we don't need to use it we can have it return null

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-69881
Caused by added method to BaseModel: https://github.com/liferay/liferay-portal/commit/32dee3b6c516b8c3b69eafcd75994c67a6202dde#diff-18a13260b232a1b0748ca57de33b3c441e166e9d6a38d503839532c2ed2dad5d
I had it return null instead of a UnsupportedOperationException to match the rest of the methods implemented in the class

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by kyle-miho** [comment]
@shuyangzhou failure unrelated, change only made to integration test

**Comment by kyle-miho** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@kyle-miho please resend, you can directly send it out to Brian for this pull.

**Pull request closed without merging**
