### PR TITLE
LPS-91248 DS asset-category-property-service

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Tests passed on https://github.com/Preston-Crary/liferay-portal/pull/697

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68732

**Pull request closed without merging**
