### PR TITLE
LPS-128094 Add "Liferay-Enterprise-App" header to war wrapper bundle …

### PR DESCRIPTION
**Pull request by mtambara**
…to be processed by license app

@vicnate5

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou I manually tested this, this is good to go.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
