### PR TITLE
[Bug Fix]LPS-137041

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Please review all the test results here when they come in

Previous issue that should be fixed in this PR: https://github.com/shuyangzhou/liferay-portal/pull/10209#issuecomment-897895282

**Comment by vicnate5** [comment]
ci:test

**Comment by koor4356** [comment]
Okay

**Comment by koor4356** [comment]
@vicnate5,  for the following tests failures,  I am seeing only those on this PR. But I am not clearly sure if they are actually caused by this PR. 
- https://testray.liferay.com/home/-/testray/case_results/1553099892?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518348753%2Fview%3FtestrayCaseId%3D1518348753%26cur%3D1%26delta%3D200%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc%26resetCur%3Dfalse
- https://testray.liferay.com/home/-/testray/case_results/1553100447?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518350118%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1518350118%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
- https://testray.liferay.com/home/-/testray/case_results/1553100464?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518344869%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1518344869%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
- https://testray.liferay.com/home/-/testray/case_results/1553100433?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1553097761%26testrayRunId%3D1553097889%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by vicnate5** [comment]
@shuyangzhou This is good to go

@koor4356 The failures you found are all due to an CI issue where the MySQL connection was lost.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/105598

**Pull request closed without merging**
