### PR TITLE
Startup optimization 64 hibernate hbm

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 if this passes ci test, please arrange a windows testing. Just need to confirm after ant all, it can bootup 2 times. First time with empty osgi/state, second time with previous osgi/state. Thanks!

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
@shuyangzhou Unique failure in [com.liferay.counter.test.CounterLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1977807210). I reproduced locally.

```
com.liferay.counter.test.CounterLocalServiceTest > testConcurrentIncrement FAILED
    java.util.concurrent.ExecutionException: com.liferay.petra.process.ProcessException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.reflect.UndeclaredThrowableException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.counter.test.CounterLocalServiceTest.testConcurrentIncrement(CounterLocalServiceTest.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: com.liferay.petra.process.ProcessException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.reflect.UndeclaredThrowableException
        at com.liferay.counter.test.CounterLocalServiceTest$IncrementProcessCallable.call(CounterLocalServiceTest.java:256)
        at com.liferay.counter.test.CounterLocalServiceTest$IncrementProcessCallable.call(CounterLocalServiceTest.java:213)
        at com.liferay.petra.process.local.LocalProcessLauncher.main(LocalProcessLauncher.java:135)
    Caused by: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.reflect.UndeclaredThrowableException
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.processException(CounterFinderImpl.java:300)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl._obtainIncrement(CounterFinderImpl.java:410)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.createCounterRegister(CounterFinderImpl.java:226)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.createCounterRegister(CounterFinderImpl.java:189)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.getCounterRegister(CounterFinderImpl.java:249)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.increment(CounterFinderImpl.java:101)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl.increment(CounterFinderImpl.java:92)
        at com.liferay.counter.service.impl.CounterLocalServiceImpl.increment(CounterLocalServiceImpl.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy44.increment(Unknown Source)
        at com.liferay.counter.kernel.service.CounterLocalServiceUtil.increment(CounterLocalServiceUtil.java:56)
        at com.liferay.counter.test.CounterLocalServiceTest$IncrementProcessCallable.call(CounterLocalServiceTest.java:252)
        ... 2 more
    Caused by: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.reflect.UndeclaredThrowableException
        at com.liferay.portal.dao.orm.hibernate.ExceptionTranslator.translate(ExceptionTranslator.java:39)
        at com.liferay.portal.dao.orm.hibernate.SessionImpl.get(SessionImpl.java:311)
        at com.liferay.counter.service.persistence.impl.CounterFinderImpl._obtainIncrement(CounterFinderImpl.java:388)
        ... 19 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy40.locateEntityPersister(Unknown Source)
        at org.hibernate.internal.SessionImpl.locateEntityPersister(SessionImpl.java:3024)
        at org.hibernate.internal.SessionImpl.access$1800(SessionImpl.java:202)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.<init>(SessionImpl.java:2720)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.<init>(SessionImpl.java:2703)
        at org.hibernate.internal.SessionImpl.byId(SessionImpl.java:1185)
        at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1165)
        at com.liferay.portal.dao.orm.hibernate.SessionImpl.get(SessionImpl.java:308)
        ... 20 more
    Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.kernel.util.ProxyUtil$DelegateInvocationHandler.invoke(ProxyUtil.java:245)
        ... 28 more
    Caused by: org.hibernate.UnknownEntityTypeException: Unable to locate persister: com.liferay.counter.model.impl.CounterImpl
        at org.hibernate.metamodel.internal.MetamodelImpl.locateEntityPersister(MetamodelImpl.java:727)
        ... 33 more
        ```

**Comment by vicnate5** [comment]
@shuyangzhou Windows startup failure https://gist.github.com/vicnate5/aefe499ec0a1c8ba634f9a2217c7563d

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:smoke

**Comment by shuyangzhou** [comment]
@vicnate5 pushed a potential fix, please try again. Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This looks good now. Manual Testing passed on Windows.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123198

Thanks @vicnate5 !

**Pull request closed without merging**
