### PR TITLE
Embedded jasper optimize

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Sorry @GinsonRen use this rebased version, the previous one has a gradle cache rebase issue, you might see jsp precompile failures.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevent

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the result:

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | bc957de24ad | 29241 | 564 | 173 | -
PR-10100 | - | 28275 | 790 | 249 | -3.30%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | bc957de24ad | 16641 | 38.9 | 124 | -
PR-10100 | - | 16631 | 44.9 | 144 | -0.06%

The baseline and this pull both rebase on [Preston's pull ](https://github.com/GinsonRen/liferay-portal/pull/575) to fix the regression on message board.

CPU tracing profiles please check [here](https://drive.google.com/drive/folders/1lcVLx-_jUg8teCRkatDKaxnbmmqM3wKz?usp=sharing).

**Comment by shuyangzhou** [comment]
Thanks @GinsonRen , I will look into it.

@vicnate5 please help me check the results, if good I will be focusing on performance. Also please see https://github.com/shuyangzhou/liferay-portal/pull/10100/commits/ca1f07317462d03f7b0d220dd05071225c7e9988 I made the ibm-web-ext.xml change, and it seems to be working.

**Comment by vicnate5** [comment]
@shuyangzhou Only 1 issue found in all the test results

Unique failure with taglib
Compile failure
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:69: error: cannot access IncludeTag
     [exec] 		groupSelectorTag.doEndTag();
     [exec] 		                ^
     [exec]   class file for com.liferay.taglib.util.IncludeTag not found
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:89: error: cannot find symbol
     [exec] 		groupSelectorTag.doEndTag();
     [exec] 		                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:96: error: cannot find symbol
     [exec] 		groupSelectorTag.doEndTag();
     [exec] 		                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:123: error: cannot find symbol
     [exec] 		groupSelectorTag.doEndTag();
     [exec] 		                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:133: error: cannot find symbol
     [exec] 			groupSelectorTag.doEndTag();
     [exec] 			                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:158: error: cannot find symbol
     [exec] 		groupSelectorTag.doEndTag();
     [exec] 		                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/item-selector/item-selector-test/src/testIntegration/java/com/liferay/item/selector/test/taglib/test/GroupSelectorTagTest.java:181: error: cannot find symbol
     [exec] 			groupSelectorTag.doEndTag();
     [exec] 			                ^
     [exec]   symbol:   method doEndTag()
     [exec]   location: variable groupSelectorTag of type GroupSelectorTag
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 7 errors
     [exec] 
     [exec] > Task :apps:item-selector:item-selector-test:compileTestIntegrationJava FAILED
```
Full log https://testray.liferay.com/reports/production/logs/2021-06/test-1-25/test-portal-acceptance-pullrequest(master)/1414/modules-compile-jdk8/0/0/jenkins-console.txt.gz

Should be reproducible with `gw  :apps:item-selector:item-selector-test:compileTestIntegrationJava`

Similar Unit test failure
https://testray.liferay.com/home/-/testray/case_results/1540526926

We probably don't need to re-run all the testing after fixing this. This is showing to be stable overall.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 ! I will take care of that.

**Comment by vicnate5** [comment]
Since I saw no regressions, we can move forward with the Websphere change for now and monitor upstream. I need to figure out what is wrong with Websphere upgrades upstream first.

**Comment by shuyangzhou** [comment]
@GinsonRen for every parameter here https://github.com/shuyangzhou/liferay-benchmark-ee/blob/master/portal/presets/common/conf/web.xml#L233-L264 , convert them as portal-ext.properties like this https://github.com/shuyangzhou/liferay-portal/pull/10100/commits/17b061b578c1631538bc24aef3482ae9c2a0bb73#diff-e652d04e2647ab1ad8d34df89282488f6088a1b238474173afcca9b01484eb63R7615 in your testing portal-ext.properties, otherwise this is not a fair comparing.

@tinatian I thought we stop doing the trimSpaces see https://github.com/shuyangzhou/liferay-benchmark-ee/blob/master/portal/presets/common/conf/web.xml#L250 ?

**Comment by tinatian** [comment]
@shuyangzhou So do you want to stop doing it? If I remember right, it may have problems if we stop doing it. @dantewang could you please confirm?

Thanks.
Tina

**Comment by shuyangzhou** [comment]
@tinatian trimming breaks some html js stuff, making some UI unusable, right? I assume it still breaks something, if not, then we should keep it, otherwise we should remove it from default.

**Comment by shuyangzhou** [comment]
@GinsonRen but for your comparing, use identical settings, just to make sure we are comparing the same thing.

**Comment by shuyangzhou** [comment]
@GinsonRen any update?

**Comment by dantewang** [comment]
@shuyangzhou Sorry, forgot to update that Ginson took second dose of COVID
vaccine yesterday so she was off today due to side effect.

Shuyang Zhou ***@***.***> 于 2021年6月17日周四 22:40写道：

**Comment by shuyangzhou** [comment]
oh, OK. I will clean up this pull to get it ready to send out soon. We can deal with the regression later if there is still any. I bet the trimspace makes a difference here, hope that's all the difference about.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10105

**Comment by GinsonRen** [comment]
@shuyangzhou Here is the new result:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | bc957de24ad | 29241 | 564 | 173 | -
PR-10100 | - | 29856 | 456 | 138 | 2.10%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | bc957de24ad | 16641 | 38.9 | 124 | -
PR-10100 | - | 16645 | 38.5 | 121 | 0.02%

**Comment by shuyangzhou** [comment]
Thanks @GinsonRen !

**Pull request closed without merging**
