### PR TITLE
[Deprecation]LPS-103621 modules part 6

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This is the last part for the first round of deprecation removal.

Next, we are going to remove usages of deprecation first, then remove deprecation.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Cloud you please help me verify the ci result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian failures not related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80351

**Pull request closed without merging**
