### PR TITLE
[TECHNICAL_SUPPORT] LPS-62652 CacheModel doesn't consider primitive wrapper fields of an entity when generated with ServiceBuilder

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-62652

Hi Shuyang,

Here's Ádám's comment:

> An if an entity has a field with primitive wrappers (to have nullable values in db) then the ...CacheModel of that entity is generated wrong.
> 
> The fix is quite similar to how we check if the primary key is a primitivewrapper in the same file:
> <#if entity.hasPrimitivePK(false)>

Cheers,
Tibor

/cc @adamnagy

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/35377

**Comment by lipusz** [comment]
Thank you, Shuyang for thinking about a better fix.👍

On Tue, Feb 2, 2016 at 7:28 PM, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 1 hour 14 minutes 39 seconds
> Base Branch:
>
> Branch Name: master
> <https://github.com/liferay/liferay-portal/tree/master>
> Branch GIT ID: 94edc28e8ea76f865ce8a3b3cbd308c10406f0b6
> <https://github.com/liferay/liferay-portal/commit/94edc28e8ea76f865ce8a3b3cbd308c10406f0b6>
> Job Summary:
>
>    - *test-portal-acceptance-pullrequest(master)
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/999/>*
>    - test-portal-acceptance-pullrequest-batch(master)/compile-jsp
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21547/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-hypersonic/0
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21743/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/0
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14445/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/1
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13014/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/2
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16877/>
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/3
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17454/>*
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/4
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13047/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/5
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13251/>
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/6
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13154/>*
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/7
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21553/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/8
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14660/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/24925/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-mysql
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/24926/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-postgresql
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21747/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-functional/poshi-runner/0
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13049/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic
>    <https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/20610/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13017/>
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21556/>*
>    - test-portal-acceptance-pullrequest-batch(master)/modules-unit
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21750/>
>    - test-portal-acceptance-pullrequest-batch(master)/plugins-compile
>    <https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10911/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13050/>
>    - test-portal-acceptance-pullrequest-batch(master)/ruby-sass-compiler
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16880/>
>    - test-portal-acceptance-pullrequest-batch(master)/service-builder
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14448/>
>    - test-portal-acceptance-pullrequest-batch(master)/tck
>    <https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10912/>
>    - test-portal-acceptance-pullrequest-batch(master)/unit
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14450/>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/2145/>
>
> For more details click here
> <https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/999/jenkins-report.html>
> .
> ------------------------------
> Failed Jobs:
>
>    1. test-portal-acceptance-pullrequest(master)
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/999/> Job
>    Results:
>
>    23 Jobs Passed.
>    4 Jobs Failed.
>
>    Completed with the status of FAILURE.
>
>    2.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/3
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/17454/> Job
>    Results:
>
>    49 Tests Passed.
>    1 Test Failed.
>    1. PoshiRunner.test[CPUsersandorganizations#AddMember]
>       <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPUsersandorganizations%23AddMember,label_exp=!master/17454//testReport/com.liferay.poshi.runner/PoshiRunner/test_CPUsersandorganizations_AddMember_>
>       - Poshi Report
>       <https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/999/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPUsersandorganizations%23AddMember,label_exp=!master/functional-tomcat-mysql/3/index.html>
>       - Poshi Summary
>       <https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/999/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPUsersandorganizations%23AddMember,label_exp=!master/functional-tomcat-mysql/3/summary.html>
>       - Console Output
>    3.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/6
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13154/> Job
>    Results:
>
>    49 Tests Passed.
>    1 Test Failed.
>    1. PoshiRunner.test[PGDocumentsandmedia#AddDocument]
>       <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGDocumentsandmedia%23AddDocument,label_exp=!master/13154//testReport/com.liferay.poshi.runner/PoshiRunner/test_PGDocumentsandmedia_AddDocument_>
>       - Poshi Report
>       <https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/999/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGDocumentsandmedia%23AddDocument,label_exp=!master/functional-tomcat-mysql/6/index.html>
>       - Poshi Summary
>       <https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/999/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGDocumentsandmedia%23AddDocument,label_exp=!master/functional-tomcat-mysql/6/summary.html>
>       - Console Output
>       <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VA%20RIABLE=PGDocumentsandmedia%23AddDocument,label_exp=!master/13154//console>
>    4.
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21556/> Job
>    Results:
>
>    4261 Tests Passed.
>    2 Tests Failed.
>    1. FolderStagedModelDataHandlerTest.testCleanStagedModelDataHandler
>       <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/21556//testReport/com.liferay.document.library.lar.test/FolderStagedModelDataHandlerTest/testCleanStagedModelDataHandler>
>       2. PortalLogAssertorTest.testScanXMLLog
>       <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/21556//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shuyangzhou/liferay-portal/pull/2388#issuecomment-178741279>
> .
>



-- 

*Tibor LIPUSZ*

Sr. Software Engineer, Team Lead
SME of Search & Security
Subscription Services, EMEA


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Pull request closed without merging**
