### PR TITLE
LPS-85870 PortletRequestDispatcher.forward(RenderRequest,RenderResponse) does not forward to resources such as plain HTML document files

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou These failures did not occur the first time I ran CI testing. They only appeared in a retest, so they must be unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63682

**Pull request closed without merging**
