### PR TITLE
[BugFix]LPS-119013

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please verify the failures?
For this one DLFileVersionTest.testUpdateFileEntryType, I did not see it in the test result of another pull with exactly same code https://github.com/shuyangzhou/liferay-portal/pull/9338.

Tina.

**Comment by vicnate5** [comment]
@tinatian failures also in upstream, this can be manually forwarded.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9342

**Pull request closed without merging**
