### PR TITLE
Startup optimization 109 lazy service tracker collection

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@shuyangzhou Regressions here

### MB Discussion Render Errors

I think most test failures are related to this, since we have a multiple features (DL, Web Content, MB) that use this component.

Steps to Reproduce with DL:
1. Go to Content & Data > Documents and Media
2. Open the default "tree" image
```
ERROR [http-nio-8080-exec-1][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_document_library_web_portlet_DLAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_document_library_web_portlet_DLAdminPortlet_mvcRenderCommandName=%2Fdocument_library%2Fview_file_entry&_com_liferay_document_library_web_portlet_DLAdminPortlet_redirect=http%3A%2F%2F192.168.254.13%3A8080%2Fgroup%2Fguest%2F%7E%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_document_library_web_portlet_DLAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26p_p_auth%3DUHKQHD7J&_com_liferay_document_library_web_portlet_DLAdminPortlet_fileEntryId=43761&p_p_auth=UHKQHD7J generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.liferay.message.boards.service.permission.MBDiscussionPermission.contains(MBDiscussionPermission.java:80) ~[?:?]
        at com.liferay.message.boards.comment.internal.MBDiscussionPermissionImpl.hasViewPermission(MBDiscussionPermissionImpl.java:81) ~[?:?]
        at com.liferay.comment.taglib.internal.context.DefaultCommentSectionDisplayContext.hasViewPermission(DefaultCommentSectionDisplayContext.java:89) ~[bundleFile:?]
        at com.liferay.comment.taglib.internal.context.DefaultCommentSectionDisplayContext.isDiscussionVisible(DefaultCommentSectionDisplayContext.java:64) ~[bundleFile:?]
        at org.apache.jsp.discussion.page_jsp._jspService(page_jsp:300) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.68]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.68]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.68]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.68]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
        at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
 ```
 
 Steps to Reproduce with Comments
1. Edit home page
2. Add Page Comments widget
3. Publish and go back to home page 
 ```
 ERROR [http-nio-8080-exec-3][IncludeTag:128] Current URL /web/guest/home generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.liferay.message.boards.service.permission.MBDiscussionPermission.contains(MBDiscussionPermission.java:80) ~[?:?]
        at com.liferay.message.boards.comment.internal.MBDiscussionPermissionImpl.hasViewPermission(MBDiscussionPermissionImpl.java:81) ~[?:?]
        at com.liferay.comment.taglib.internal.context.DefaultCommentSectionDisplayContext.hasViewPermission(DefaultCommentSectionDisplayContext.java:89) ~[bundleFile:?]
        at com.liferay.comment.taglib.internal.context.DefaultCommentSectionDisplayContext.isDiscussionVisible(DefaultCommentSectionDisplayContext.java:64) ~[bundleFile:?]
        at org.apache.jsp.discussion.page_jsp._jspService(page_jsp:300) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.68]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.68]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.68]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.68]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
        at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
```
 

### Backend Tests
1. [MBDiscussionPermissionImplTest](https://testray.liferay.com/home/-/testray/case_results/2111764707)
2. https://testray.liferay.com/home/-/testray/case_results/2111764457
3. https://testray.liferay.com/home/-/testray/case_results/2111764366
4. https://testray.liferay.com/home/-/testray/case_results/2111764924

**Pull request closed without merging**
