### PR TITLE
[Bug Fix]LPS-122896-LPS-121537

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @@marianoalvarosaiz @jorgediaz-lr

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
Rebase and resend at https://github.com/shuyangzhou/liferay-portal/pull/9564

**Pull request closed without merging**
