### PR TITLE
LPS-67509 FriendlyURLNormalizerImpl

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
The BaseUpgradePortletIdTest failure is the known opensocial one. 
The DocumentLibraryConvertProcessTest is known hot_deploy one.

Looking into the functional failures.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/157

**Pull request closed without merging**
