### PR TITLE
LPS-75799 FriendlyURL for unavailable language does not redirect to default language

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@pavel-savinov the integration test failure in FriendlyURLServletTest.testGetRedirectWithI18nPath is real. Please fix and resend.

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/5323

**Pull request closed without merging**
