### PR TITLE
[Deprecation]LPS-106315

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
This pull based on LPS-106167 (https://github.com/shuyangzhou/liferay-portal/pull/8678).

cc @hhuijser We need this to be in soon, to fix it quickly, I hardcode the fix for IdentifiableOSGiServiceUtil, please review and fix it in more proper way.

FYI @topolik  

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Test results look good

**Comment by hhuijser** [comment]
@tinatian, if this is the only exception, I don't mind your hardcoded fix.
If we anticipate other exception cases, I can make it configurable.
Let me know.

**Comment by shuyangzhou** [comment]
Talked to @tinatian, please resend with changes.

**Comment by yuhai** [comment]
Hi Shuyang, we change a part fix. I will close the PR and resend it.
cc @dantewang, cc@tinatian

**Comment by yuhai** [comment]
ci:close

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1674

**Pull request closed without merging**
