### PR TITLE
LPS-X Cache and reuse jsql parsed results.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 the results look clean, do you think we need more test for it? Do we have a CT suite?

**Comment by vicnate5** [comment]
ci:test:publications

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122253

**Pull request closed without merging**
