### PR TITLE
[Blog Tuning]LPS-97259

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:blogs

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please check the results?

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian Failures are not related to this PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74993

**Pull request closed without merging**
