### PR TITLE
[Startup Tuning]LPS-98464

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@shuyangzhou The original code does not consider the master will be changed either. I will try to fix this in another ticket, but this one should be equal to the old one.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/76073

**Pull request closed without merging**
