### PR TITLE
pull-request-149617

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@rotty3000 https://github.com/brianchandotcom/liferay-portal/pull/149617/commits/8f2d56ee783e384a2df4fbe0319ef02b4528e715 is not the right solution. I can see you are trying to avoid some company creation race condition on startup. There are many different options to do this, depending on the case. But delaying an user configured time can not be the solution, you simply don't know how long is enough, or how long is too wasteful. Time waiting is generally bad, can rarely be the right thing to do.

The thing confused me is, there are 4 tickets in your pull, it is hard for me to correlate what caused what.

Can you break your change to different pulls, to make sure you only solve one problem at a time? You can decide the order, once we get a focus on the company creation race, I can explain to you what options we have to avoid race for different cases.

**Comment by rotty3000** [comment]
you can close this PR.

**Comment by rotty3000** [comment]
only the portal instance code was relative to you. I'm going to skip it for now and move on with the rest.

**Comment by rotty3000** [comment]
if you want context of the issue, please see https://liferay.atlassian.net/issues/LPD-23789

**Comment by shuyangzhou** [comment]
The error stack shows the failure happened on a db partition setup. But the ticket does not say anything about db partition.

Do you know is this a db partition only problem?

**Comment by shuyangzhou** [comment]
The error stack also shows `upgrade.database.auto.run` is on. This is not a normal startup sequence for sure.

Not saying this should break, but at least please make it clear under what setup this race happens.

If it requires either db partition or auto upgrade, or even both, then it is an upgrade issue.
If it can happen on normal setup without db partition and auto upgrade, then we need to see the stack traces from it.

CC @achaparro

**Comment by rotty3000** [comment]
It does not matter if DB partitioning is enabled. I tested this.

**Comment by rotty3000** [comment]
No note that this is an intermittent failure. It does not occur every time (even when starting with a clean database each time.)

**Comment by shuyangzhou** [comment]
can you get an error stack with db partition and auto upgrade disabled? that will clear a lot noise.

**Comment by shuyangzhou** [comment]
yeah, I know. exactly because it is a race condition we need to know which part of the system is contributing to it. rather than using some kind of workaround to cover it.

**Comment by rotty3000** [comment]
I'll get a stacktrace as soon as I can get back to this. There was no upgrade involved.

**Comment by rotty3000** [comment]
hey @shuyangzhou I recognized that I overlooked some details. Thanks for your input, it was helpful.

**Comment by shuyangzhou** [comment]
you are welcome, let me know if you find out what happened.

**Pull request closed without merging**
