### PR TITLE
LPS-73049

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @shuyangzhou,

Attached is an update for http://issues.liferay.com/browse/LPS-73049.  I saw you made some commits for this previously, so I just wanted to pass it through another pair of eyes for backend changes.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@jonmak08 not sure why this came to me, I don't recall I changed something for this before. But that's fine, if you want a double check.

@holatuwol @dustinryerson the change actually looks confusing to me, the ticket does not say anything about what the issue is. And the commit https://github.com/shuyangzhou/liferay-portal/pull/4568/commits/4fe03235b89e69e75d174ed038537482a16f18da here seems to contain structure refactor + functional changes. Whenever we do something like this, always separate the structure refactor from the functional changes, otherwise it is not easy to see what you are really changing. Please break the commit into smaller pieces and resend, thanks!

**Comment by jonmak08** [comment]
Thanks for the quick review @shuyangzhou!

I just looked at the commit history for the files and saw that you had made changes to both of them before, so I thought maybe you would be a good candidate to review these backend changes.

**Comment by shuyangzhou** [comment]
@jonmak08 that's fine, I just want to make sure I was not involved before for this ticket.

**Comment by holatuwol** [comment]
ci:reopen

**Pull request closed without merging**
