### PR TITLE
[TS] LPS-108120

### PR DESCRIPTION
**Pull request by ericyanLr**
/cc @NorbertKocsis

Hi @shuyangzhou ,

**Main Issue**
Liferay fields that have a SQL type of CLOB, utilize the String type.
An example of this is Journal's Content field: [JournalArticleModelImpl.java#L91](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleModelImpl.java#L91).

The issue occurs when there is a large content entry. Our cacheModel currently utilizes readUTF/writeUTF, which ends up throwing a UTFDataFormatException (occurs when length > 65535 bytes).

**Proposed Fix**
If a String column type has a SQL type CLOB, use readObject/writeObject instead.

**Note: Service Builder - ant build-services**
Running ant build-services resulted in changes to other class files that weren't *CacheModel.java

This also led to an additional semver commit for journal-api.

Feel free to let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please check this, CI seems fighting with the regen in this pull.

**Comment by vicnate5** [comment]
A lot of changes on Service Builder generation:
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262310/AXIS_VARIABLE=0,label_exp=!master/consoleText

Otherwise this looks good.

**Comment by vicnate5** [comment]
@ericyanLr I am looking into why the SB test fails on CI, but can you rebase and regen this branch? There were other SB changes at head yesterday so I cannot rebase cleanly.

**Comment by ericyanLr** [comment]
Hey @vicnate5 ,

I rebased and re-ran `ant build-services`, there's a lot less files this time.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Failed again, getting help from CI team.

**Comment by vicnate5** [comment]
CI needs to send a fix https://issues.liferay.com/browse/LRCI-1097

**Comment by vicnate5** [comment]
Manually re-triggered with unmerged CI fix.

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@shuyangzhou Service builder test now passing with the CI fix. This should be good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86211

**Pull request closed without merging**
