### PR TITLE
[Bug Fix]LPS-90633

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
cc @anthony-chu

**Comment by anthony-chu** [comment]
The only unique functional failure here is Search#SearchDifferentScopesViaSearchWidget; however, this seems to be a flaky test, so we can ignore it.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68145

**Pull request closed without merging**
