### PR TITLE
[Help Link]LPS-135336

### PR DESCRIPTION
**Pull request by tinatian**
Hi @shuyangzhou @jhinkey,
This includes all the required help links expect the setup wizard one, as the code is in portal-web and unable to see the new taglib, we will figure out a way to do it in a separate pull as we may need to provide a general solution for future usages like it.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
FYI @jhinkey

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
