### PR TITLE
LPS-80401 AwaitServiceInvocationHandler not unwrapping the InvocationTargetException

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @sergiogonzalez 

@shuyangzhou see https://github.com/Preston-Crary/liferay-portal/pull/523#issue-187178537

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58354

**Pull request closed without merging**
