### PR TITLE
[TECHNICAL-SUPPORT] LPS-71009

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Is there any update on this pull request?

**Comment by shuyangzhou** [comment]
@jonathanmccann Have you tried to just interrupt the hanging thread? Does that thread response to interruption?

**Comment by jonathanmccann** [comment]
Yes, I did try that initially to avoid using the System.exit but it still hung.

**Comment by shuyangzhou** [comment]
@jonathanmccann ok, that's fine, then I will take it in as it is.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47546

**Pull request closed without merging**
