### PR TITLE
[TECHNICAL-SUPPORT] LPS-78517

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-78517

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Hi @shuyangzhou ,
Each time I retested this PR failures are different, so I think those failures are not related to these commits.
Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56197

**Pull request closed without merging**
