### PR TITLE
LPS-X MailServiceImpl should only notify MessageBus when the current …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ongoing tx is successfully committed. This is to fix the "PortalPreferencesPersistenceImpl.fetchByO_O(long, int, boolean) with parameters (40912,1) yields a result set with more than 1 result. This violates the logical unique restriction. There is no order guarantee on which result is returned by this finder." warning during company creation.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 this affects all tests that send out emails. Please run additional tests that you see fit, thanks!

**Comment by vicnate5** [comment]
Targeted testing at https://github.com/vicnate5/liferay-portal/pull/2060

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. All functional tests that send emails are passing.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118940

**Pull request closed without merging**
