### PR TITLE
LPS-86235

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @shuyangzhou 

There are several portlets that are non deployable but has property set to PreferencesUniquePerLayout=true(the default value), MDRPortlet is one of them.

This commit explicitly set it to false.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 is there any additional tests we need to run?

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
Resent with test fix https://github.com/shuyangzhou/liferay-portal/pull/9231

**Pull request closed without merging**
