### PR TITLE
LPS-100525 Create MappingTables Change Tracking support

### PR DESCRIPTION
**Pull request by stsquared99**
cc @preston-crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@Preston-Crary @stsquared99 Issue with Sample SQL builder
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/352813/AXIS_VARIABLE=4,label_exp=!master/consoleText

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8733

**Pull request closed without merging**
