### PR TITLE
[Log4j]LPS-125550 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@tinatian I think https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/437790//testReport/com.liferay.portal.osgi.web.wab.generator.internal.processor/WabProcessorTest/testClassicThemeWab is caused by your war update. Can you take a look?

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@shuyangzhou @tinatian The path inside the war is not correct (e.g. the `css` dir: `/css` in old war vs `/class-them.autodeployed/css` in the updated war). I directly modified the war to move them to the root, see https://github.com/dantewang/liferay-portal/pull/1945/commits/dff8301865ffadf01e0d02e5062346e9d6926036

**Comment by shuyangzhou** [comment]
Thanks @dantewang !

**Comment by dantewang** [comment]
Pull based on #9872 running ci: https://github.com/dantewang/liferay-portal/pull/1945

**Pull request closed without merging**
