### PR TITLE
Lps 177837

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Expected headless tests ran here.

FYI @magjed4289

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133399

**Pull request closed without merging**
