### PR TITLE
[Deprecation]LPS-104401

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test results look good. 

3 Data source integration tests failed on Hypersonic database.
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339312/#showFailuresLink

However, these only failed on this database, and look unrelated to the changes. Likely a flaky test.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81663

**Pull request closed without merging**
