### PR TITLE
Startup optimization 89 searchengine

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:search

**Comment by shuyangzhou** [comment]
@vicnate5 I have pushed to fix the semantic versioning issue in search api/spi, please help me check for other regressions, thanks!

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?

**Comment by Kvale1733** [comment]
@shuyangzhou Regressions found:

1) Lots of integration tests failed or were aborted due to unresolved requirement in startup
```
j[beanshell] 2022-10-11 02:47:50.860 ERROR [main][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.product.service [854]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.commerce.service.impl
```
[Testray Example](https://testray.liferay.com/home/-/testray/case_results/2003390490?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2003370968%26testrayRunId%3D2003376184%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

2)
com.liferay.portal.search.elasticsearch7.internal.ElasticsearchEngineConfiguratorTest
```
 [exec] com.liferay.portal.search.elasticsearch7.internal.ElasticsearchEngineConfiguratorTest > testDestroyMustNotCreateDestinationsAgain FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _searchEngineHelper
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
```
[Testray](https://testray.liferay.com/home/-/testray/case_results/2003216116l)

**Comment by shuyangzhou** [comment]
@Kvale1733 are you sure the first failure is caused by this pull? It looks very unrelated.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
@Kvale1733 @vicnate5 just force pushed fix for ElasticsearchEngineConfiguratorTest

**Comment by shuyangzhou** [comment]
@vicnate5 in the previous bundle https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/4971/liferay-portal-bundle-tomcat.tar.gz I checked the "com.liferay.commerce.product.service.jar" it actually has these imports "com.liferay.commerce.service.impl,com.liferay.commerce.service.persistence.impl". However the code does not use those packages at all.

And local build did not have this weird imports. I can not find any recent change to commerce.product.service module that is messing with those packages either.

This looks like some build race condition which bnd includes some wild packages.

**Comment by shuyangzhou** [comment]
ci:test:bundle

Must be my force push broke the bundling build you triggered.

**Comment by shuyangzhou** [comment]
ci:test:relevant

Rerun the relevant to be safe

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 we have got 3 new tomcat zips, https://files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/970/liferay-portal-bundle-tomcat.tar.gz (from ci bundle) and https://files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/975/liferay-portal-bundle-tomcat.tar.gz (from the last finished ci relevant). In these 2 build, the com.liferay.commerce.product.service.jar does not have the bad imports.

But in the failed ci relevant https://files.liferay.com/private/bundles/test-1-39/jobs/test-portal-acceptance-pullrequest(master)/builds/971/liferay-portal-bundle-tomcat.tar.gz, that jar has the bad imports.

This is some kind of build race condition.

**Comment by Kvale1733** [comment]
Yup found the same issue in this PR: https://github.com/liferay-core-infra/liferay-portal/pull/1990#issuecomment-1276228389. Checking the new results.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124478

**Pull request closed without merging**
