### PR TITLE
[log4j]LPS-127261

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1172004_7194

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
