### PR TITLE
LPS-X Refactor InvokerFilterContainerImpl to use ServiceTrackerMap.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 this is another portal-impl only change which could affect all portlet filter usages. What other tests would be necessary to run?

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by vicnate5** [comment]
@shuyangzhou Integration regression here: https://testray.liferay.com/home/-/testray/case_results/2258096694

Caught by relevant.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 is it good now?

**Comment by vicnate5** [comment]
@shuyangzhou Looks good now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132923

**Pull request closed without merging**
