### PR TITLE
[License]LPS-122557

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Hi @vicnate5, is the unique failure real?

Tina

**Comment by vicnate5** [comment]
ci:test:cluster-license

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@tinatian The errors look unrelated to your changes, I want to run the cluster tests too, so I will also re-run the regular license tests.

**Comment by vicnate5** [comment]
ci:test:workflow

**Comment by vicnate5** [comment]
@tinatian This passed regression testing. I ran the failing tests locally after fixing the override for the time limit:

I resent your PR with the change needed for the tests:
https://github.com/shuyangzhou/liferay-release-tool-ee/pull/44

Is the full shutdown logic still pending?

**Comment by tinatian** [comment]
@vicnate5 Yes, I plan to send out the auto shutdown part today.

Tina.

**Comment by shuyangzhou** [comment]
Merged on release repo side, thanks!

**Pull request closed without merging**
