### PR TITLE
LPS-111193 Automatically cleanup leftover deployed portlets

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:backend

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
Fix https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366665/AXIS_VARIABLE=1,label_exp=!master/testReport/com.liferay.application.list.my.account.permissions.test/PanelAppMyAccountPermissionsTest/testPermissionsAddedForAllCompaniesFromNewPanelApp/

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
