### PR TITLE
Startup optimization 106 indexer registry

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@shuyangzhou Regressions found

1)  com.liferay.search.experiences.service.test.SXPElementLocalServiceTest > testUpdateSXPElement
```
 [exec] com.liferay.search.experiences.service.test.SXPElementLocalServiceTest > testUpdateSXPElement FAILED
     [exec]     com.liferay.search.experiences.exception.DuplicateSXPElementExternalReferenceCodeException: Duplicate sxp element with external reference code EYXCm5JF
     [exec]     	at com.liferay.search.experiences.service.persistence.impl.SXPElementPersistenceImpl.updateImpl(SXPElementPersistenceImpl.java:6307)
     [exec]     	at com.liferay.search.experiences.service.persistence.impl.SXPElementPersistenceImpl.updateImpl(SXPElementPersistenceImpl.java:88)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-39/test-portal-acceptance-pullrequest(master)/2078/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0)

2) Unsatisfied References when restarting portal. To reproduce Just start the portal. Stop portal (do not clean anything). Then restart portal.
```
[parallel] 2022-12-02 15:45:25.539 INFO  [main][SystemCheckOSGiCommands:123] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
     [exec]      [parallel] 2022-12-02 15:45:25.539 INFO  [main][SystemCheckOSGiCommands:111] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
     [exec]      [parallel] 2022-12-02 15:45:39.581 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
     [exec]      [parallel] Bundle {id: 525, name: com.liferay.document.library.video, version: 1.0.49}
     [exec]      [parallel] 	Declarative Service {id: 7586, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoStatusMVCResourceCommand, unsatisfied references: 
     [exec]      [parallel] 		{name: _videoProcessor, target: null}
     [exec]      [parallel] 	}
     [exec]      [parallel] 	Declarative Service {id: 7585, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoMVCRenderCommand, unsatisfied references: 
     [exec]      [parallel] 		{name: _videoProcessor, target: null}
     [exec]      [parallel] 	}
     [exec]      [parallel] 	Declarative Service {id: 7588, name: com.liferay.document.library.video.internal.preview.DLVideoDLPreviewRendererProvider, unsatisfied references: 
     [exec]      [parallel] 		{name: _videoProcessor, target: null}
     [exec]      [parallel] 	}
     [exec]      [parallel] Bundle {id: 946, name: com.liferay.document.library.preview.audio, version: 3.0.16}
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-39/test-portal-acceptance-pullrequest(master)/2078/functional-tomcat90-mysql57-jdk8/2/0/jenkins-console.txt.gz?authuser=0)

3) Semver error 
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/alloy/alloy-mvc] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.alloy.mvc                              MINOR      3.1.0      3.1.0      3.2.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.alloy.mvc.BaseAlloyControllerImpl
     [exec]     		+   field      indexerServiceRegistration
     [exec]     			+   access     protected
     [exec]     			+   return     org.osgi.framework.ServiceRegistration
     [exec]     	<   class      com.liferay.alloy.mvc.MockAlloyControllerImpl
     [exec]     		+   field      indexerServiceRegistration
     [exec]     			+   access     protected
     [exec]     			+   return     org.osgi.framework.ServiceRegistration
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.1.0
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-39/test-portal-acceptance-pullrequest(master)/2078/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@shuyangzhou Actually I removed the integration test failure. Looks like that's not unique to this PR.

**Pull request closed without merging**
