### PR TITLE
LPS-75359

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
I didn't try to run all the tests, most likely a lot of them will fail 😞

I'll keep working on them tomorrow, if you want!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
Hi @shuyangzhou!
I already sent https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/465 to fix the unit tests on `dynamic-data-mapping`. When it's merged, `modules-unit-jdk8` shouldn't fail anymore.

**Comment by shuyangzhou** [comment]
Awesome @Ithildir !
@tomwang2011 please send me your lpkg fixes on top of @Ithildir 's latest changes.

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
Working on these new failures...

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
Hi @shuyangzhou! I think we're almost there with this pull, I only got 12 unit test failures (mostly Whip complaining, or some weird assert errors). Do you want to take care of them, or should I keep working on it once I have more time?

**Comment by shuyangzhou** [comment]
Thanks @Ithildir ! I can take it over from here, thanks for fixing all those failures.

**Comment by shuyangzhou** [comment]
@Ithildir there are too many rebase failures. Can you rebase it, just to make sure I am not breaking your fixes. Than I will work on the unit test failures. Thanks!

**Comment by shuyangzhou** [comment]
Sorry, my bad, I was on your old version of branch. The current one just have one rebase failure, which is easy to fix. I can work on the unit test failures now.

**Comment by Ithildir** [comment]
Sent to https://github.com/shuyangzhou/liferay-portal/pull/5206.

**Pull request closed without merging**
