### PR TITLE
[SampleSQLBuilder]LPS-91612

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang @slnn 

Please update the description on the corresponding ticket.

Thanks.
Tina

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/b4d64e7c84...f452a22c48

**Comment by slnn** [comment]
Hi @tinatian,

Description of the ticket has been updated.

**Pull request closed without merging**
