### PR TITLE
COMMERCE-1067 - headless-batch-engine-impl - Update BatchEngineImportTaskExecutorImpl with parameters

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ivicac that UnsafeTriFunction is a bit too hard to read, when it was UnsafeBiFunction, it was still worthy to use it to avoid a new type. Now I think we new type is much readable comparing to this UnsafeTriFunction with 5 generic types. Can you find a reasonable name for it and make it an interface type?

**Comment by ivicac** [comment]
ci:test

**Comment by ivicac** [comment]
@shuyangzhou, unfortunately, I followed pattern naming even though I disliked it. I renamed it to BatchEngineTaskItemResourceDelegateCreator

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80770

When can we add back the integration tests?

**Comment by ivicac** [comment]
@shuyangzhou it is here https://github.com/shuyangzhou/liferay-portal/pull/8497

**Pull request closed without merging**
