### PR TITLE
LPS-63988 ScriptData should generate camelCase variables

### PR DESCRIPTION
**Pull request by Preston-Crary**
cc @jbalsas @brunobasto

### CODE REVIEW

**Comment by jbalsas** [comment]
LGTM, thanks a lot @Preston-Crary!

**Comment by shuyangzhou** [comment]
Hey @jbalsas, @Preston-Crary explained to me you need the var name to be camel case. Just to confirm with you. How do you want to handle the very 1st letter? Always lower case as we normally do for variable/method naming? Or always upper case as we normally do for class naming?

They are both valid camcel case according to https://en.wikipedia.org/wiki/CamelCase "Camel case may start with a capital or, especially in programming languages, with a lowercase letter."

Anyway, there is some logic wrong in this pull, I talked to @Preston-Crary to have him fixing it and resend, but need you to clear out what do you expect for the 1st letter.

Thanks!

**Comment by jbalsas** [comment]
Hey @shuyangzhou, @Preston-Crary, thanks for looking into this!

We are generating variables, so the first letter should be lowerCase. In the [documentation](https://github.com/mwilliams2014/liferay-docs/blob/LRDOCS-1852-L7JS/develop/tutorials/articles/javascript/02-using-modules-in-your-portlets.markdown) for `<aui:script require="...">` you can see the use case as it was designed.

**Comment by shuyangzhou** [comment]
Ok, thanks for clarifying it, we will make it lower case the 1st letter.

**Comment by Preston-Crary** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/2716

**Pull request closed without merging**
