### PR TITLE
Startup optimization 251 bundle loader concurrency 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
More aggressive version at https://github.com/shuyangzhou/liferay-portal/pull/11098

**Pull request closed without merging**
