### PR TITLE
LPS-69532 Fix gradle dependency

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/46393

**Comment by shuyangzhou** [comment]
See the explanation at https://github.com/brianchandotcom/liferay-portal/pull/46393/commits/f8a9c91dd21d6e99f527b9b5e52333846dc18e6a

**Comment by inacionery** [comment]
@shuyangzhou, thanks so much!!

**Pull request closed without merging**
