### PR TITLE
COMMERCE-5475 Dispatch - Talend Java Process - we need error code out of callable in Future - please review if this is good approach

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Shuyang please check this one. Thank you very much!

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@igorbeslic real test failure, please fix and resend.

**Comment by igorbeslic** [comment]
@matijapetanjek please can you take look. It may be consequence of my refactoring on the top of your work

**Pull request closed without merging**
