### PR TITLE
[TECHNICAL SUPPORT] LPS-97591 Avoid ignoring exceptions thrown from Elasticsearch initialization thread

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This issue was caused by this commit: https://github.com/liferay/liferay-portal/commit/243dd9dc6bcb85558a58fe3fd261e931d81ecf05

Elasticsearch initialization was moved to a thread. With the new code, in case of any initialization error, we are ignoring the exception from child thread and startup continues with several ERRORs and WARNs

/cc @arboliveira

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

Did you have the chance to review this PR?

Test failure in **LocalFile.Search#SearchWithModifiedFacet** seems to be unrelated to my changes, as it also failed in following PR: https://github.com/BryanEngler/liferay-portal/pull/373/#issuecomment-507276385

Thank you,
Jorge

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75246

**Pull request closed without merging**
