### PR TITLE
LPS-83992 Implement CDI requirements in Async

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou This PR contains one commit by Leon and six commits by me that help to implement CDI requirements with Portlet 3.0 Async.

/cc @dantewang @ChiZelin @vsingleton @rotty3000 @stiemannkj1 @vicnate5

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ngriffin7a please check skype messages and ping me back when you are available, thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou I refactored with `ConcurrentLinkedDeque` and got it working! :)

I'll send a follow-up PR tomorrow.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6957

**Pull request closed without merging**
