### PR TITLE
LPS-81861 Portlet 3.0: Refactor portlet request parameter handling and portlet URL generation (require 3.0 opt-in)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou I contacted @jpince about the two smoke test failures and he said they fail intermittently. In addition, I saw LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive612 in https://github.com/shuyangzhou/liferay-portal/pull/6598 which is totally unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
@ngriffin7a rebase failure, please resend, thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou Fixing now, standby...

**Comment by ngriffin7a** [comment]
@shuyangzhou Rebased. I incorporated the null check from https://github.com/liferay/liferay-portal/commit/318c807b2d0e62871f6a0312f55336cd69b24105

Please review, thanks! 

(Note that I don't think it's worth running ci_test again unless you disagree)

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6624

**Pull request closed without merging**
