### PR TITLE
LPS-74937 Jacoco report for single class

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou Usage is shown in description https://issues.liferay.com/browse/LPS-74937

### CODE REVIEW

**Comment by shuyangzhou** [comment]
When using it, I got this:
```
zsyxc@zsyxc-Precision-5520 /home/trunks/git/liferay-portal/portal-impl $ ant generate-code-coverage-report -Dclass.names=FileImplTest
Buildfile: /home/trunks/git/liferay-portal/portal-impl/build.xml

generate-code-coverage-report:
   [delete] Deleting directory /home/trunks/git/liferay-portal/jacoco/html-report
    [mkdir] Created dir: /home/trunks/git/liferay-portal/jacoco/html-report

BUILD FAILED
/home/trunks/git/liferay-portal/build-common.xml:1666: java.lang.StringIndexOutOfBoundsException: String index out of range: -30
	at java.lang.String.substring(String.java:1967)
	at com.liferay.util.ant.GetFileSetTask.execute(GetFileSetTask.java:87)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 1 second

```
Please fix and resend.

**Comment by slnn** [comment]
Hi @shuyangzhou 

The parameter for -Dclass.names should be class name instead of test class name.

For example, ant generate-code-coverage-report -Dclass.names=FileImpl when FileImplTest had been finished.
 Resend please see https://github.com/shuyangzhou/liferay-portal/pull/5350

**Comment by shuyangzhou** [comment]
@slnn in case of a wrong user input value, it should fail with some complains, rather than a StringIndexOutOfBoundsException. This is not user friendly, and most likely other people will just be like me, thinking it is a bug in the system, rather than a wrong input.

**Comment by slnn** [comment]
OK, will do it and resend.
Thanks!

**Pull request closed without merging**
