### PR TITLE
LPS-121784 Site members is wrong in My Dashboard when we enter as a non admin user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121784](https://issues.liferay.com/browse/LPS-121784).

Hey @shuyangzhou, will you please look over this change? This is a first attempt so please let me know if I'm missing something. Thanks!

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@drewbrokke can you talk to @IstvanD to explain what is broken for you? If possible we should fix it in the new way. Using the "magic" 999 limit is too hacky. We have many arrayable finders, we don't want this style of solution whenever we run into this issue.

@IstvanD please preserve @drewbrokke 's tests, adjust the new finders to pass them. I don't know this piece of business logic, you guys have the best shots to make it work. If for some reason that can not be done, we can schedule a meeting for all of us to talk about it.

**Comment by drewbrokke** [comment]
@IstvanD the cause I identified for this issue is that the indexer-based approach for doing the search count on each group is permission checked, whereas the DB query was not permission checked. If there's an easy way to disable permission checking on the indexer queries then we can just do that.

**Comment by IstvanD** [comment]
Hi @drewbrokke I sorry that my solution caused these regressions. I'm about to fix it.

**Comment by IstvanD** [comment]
@drewbrokke @shuyangzhou https://github.com/shuyangzhou/liferay-portal/pull/9509

**Pull request closed without merging**
