### PR TITLE
LPS-61952 Upgrade

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Fix for the other tests that are failing:
https://github.com/shuyangzhou/liferay-portal/pull/2550

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/35927

**Pull request closed without merging**
