### PR TITLE
Startup optimization 328 template manager

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

Issue found: test [com.liferay.portal.kernel.template.TemplateManagerUtilTest](https://testray.liferay.com/home/-/testray/case_results/2445927806) failed with error:
```
##
## com.liferay.portal.kernel.template.TemplateManagerUtilTest > testHasTemplateManager
##

	junit.framework.AssertionFailedError: TEST_TEMPLATE_MANAGER_NAME not found
		at com.liferay.portal.kernel.template.TemplateManagerUtilTest.testHasTemplateManager(TemplateManagerUtilTest.java:89)


##
## com.liferay.portal.kernel.template.TemplateManagerUtilTest > testGetTemplateManagerName
##

	junit.framework.AssertionFailedError: [test]
		at com.liferay.portal.kernel.template.TemplateManagerUtilTest.testGetTemplateManagerName(TemplateManagerUtilTest.java:82)


##
## com.liferay.portal.kernel.template.TemplateManagerUtilTest > testGetTemplateManager
##

	junit.framework.AssertionFailedError: expected same:<null> was not:<null>
		at com.liferay.portal.kernel.template.TemplateManagerUtilTest.testGetTemplateManager(TemplateManagerUtilTest.java:71)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3970/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142723

**Pull request closed without merging**
