### PR TITLE
[TS] LPS-75089 Avoid wildfly shutdown errors in PortletTracker and TemplateHandlerRegistryImpl

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-75089

Avoid shutdown errors in some wildfly setups at PortletTracker and TemplateHandlerRegistryImpl classes:

- In `PortletTracker.removedService` there is a call to _companyLocalService.getCompanies(); that fails during shutdown. We can avoid this issue, calling _portal.getCompanyIds(); instead
- In `TemplateHandlerRegistryImpl.removeTemplateHandler` there is a call to _portal.getClassNameId(className); that fails during shutdown. We can avoid this issue, storing classNameId during TemplateHandlerRegistryImpl.addTemplateHandler logic.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@jorgediaz-lr I have doubts on this change. Please help me understand the problem here:
1) Is this wildfly problem or jndi problem?
2) Won't this happen to all db accessing during shutdown? If so, fix these 2 is not going to be enough, sooner or later we will get a lot more similar problem.

We basically have to find a way to ensure portal shutdown happens before datasource deactivation.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

The problem is produced in Wildfly, only in case you configure the database using JNDI. 

Application server succesfully stops but the customer is complaining that lots of ERROR traces are written to log file (353 lines)

**Comment by shuyangzhou** [comment]
@jorgediaz-lr this is not the right fix, we need to understand why the datasource got destroyed before portal shutdown completes. If we just fix it this way, we will see similar problems in the future, and not all db accesses can be avoid from shutdown logic. We need a way to make sure portal shutdown completes before the jndi datasource got teared down.

@tinatian please take this over and do some digging.

@vicnate5 we need ci coverage on jndi datasource for all appservers, can you have someone to build up tests for that?

**Comment by vicnate5** [comment]
@shuyangzhou We have some old jndi test setup scripts, but nothing is calling it anymore. I can get the test coverage added for each app server.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by vicnate5** [comment]
Test ticket https://issues.liferay.com/browse/LRQA-56272

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou @tinatian

@dantewang found this wildfly issue related to JNDI problems during shutdown: 
- https://issues.redhat.com/browse/WFLY-944?focusedCommentId=12997258&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12997258

The workaround is to add a **resource-ref** to JDNI resource in Liferay ROOT.war. It can applied to jboss-web.xml or web.xml files.
In my opinion for our Enterprise customers, it is better to apply this change to **jboss-web.xml** because web.xml modifications are overwritten everytime they install a fixpack. (_jboss-web.xml is not overwritten because it remains unmodified since Liferay 6.1_)

Let me know you want me to update official documentation https://portal.liferay.dev/docs/7-2/deploy/-/knowledge_base/d/installing-product-on-wildfly#database-configuration or you want to try another thing.

For now, I will send this workaround to my customer.

Thank you

**Comment by shuyangzhou** [comment]
Yes, just add this to doc. It is not a liferay issue, since it has a workaround, just let customers do that.

**Comment by jorgediaz-lr** [comment]
Documentation update sent to https://github.com/jhinkey/liferay-docs/pull/493

**Pull request closed without merging**
