### PR TITLE
LPS-83801

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou from https://github.com/brianchandotcom/liferay-portal/pull/62230

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn @tomwang2011 run a full performance regression tests for both runtime and startup time.
@tinatian you will want to check this too.

**Comment by tinatian** [comment]
@shuyangzhou OK, got it.

**Comment by slnn** [comment]
Hi @shuyangzhou 

I can see 3.3% performance regression on Login, here are test results:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | cd184cd | 48520 | 277 | 83.2
PR-6644 | - | 46927 | 272 | 81.5


Test results for other test cases is on the way.


Lily

**Comment by shuyangzhou** [comment]
@topolik @csierra base on the results, we can not merge it in without eliminating the regression first. If you guys want to work on it, please go ahead and feel free to send lily pulls to reverify. Otherwise we can take care of it too, just base on our current work load, it may take a while to get on to this.

**Comment by csierra** [comment]
@shuyangzhou we will give it another thought and send Lily to reverify. 

Thx.

**Comment by csierra** [comment]
please see https://github.com/slnn/liferay-portal/pull/324

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62602

**Pull request closed without merging**
