### PR TITLE
Lps 52580 Cluster refactor

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
This should be a good time to allow us to do some design refactor.
For example,
1) There is no point to keep the ClusterManager.isShortcutLocalMethod(), I don't see when will we ever want to turn it off.
2) Let's get rid off the ClusterManager.isEnabled(), by creating a dummy impl of ClusterManager which does nop for all methods. On Spring init, if it is enabled, wireup the real impl, otherwise put in the dummy one.

And a lot of other details, we can get further discuss after this round of refactor.

And what's the plan of removing ClusterLink and ClusterExecutor? let's start to add that part in so that we can get the full picture of the end result.

**Comment by shuyangzhou** [comment]
And for all the removal changes, let's pull them ahead, so that they can be merged in earlies to reduce the over all noise.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/23356, I removed the shortcut local method support.

**Comment by tinatian** [comment]
I am going to remove cluster link and executor after I apply ClusterManager to all current usages.

For the application of ClusterManager, I have done most, but some small parts left. I will try to finish it up as soon as possible. Then I will send a pull request with the removal part.

By the way, I will be on the filght to Dalian on the morning of Tuesday.

Tina.

**Comment by shuyangzhou** [comment]
Let's pull up the clean up changes first, then send me all changes as a whole to let me see the entire picture. Then decide how to break it into pieces that are easier to take in.

**Comment by tinatian** [comment]
OK, got it.

**Pull request closed without merging**
