### PR TITLE
LPS-106397 DSL

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
For Expression.as(String) I'm still returning an Alias.  Not sure if we should return expression, make Alias an interface or move Alias into API package.

**Comment by Preston-Crary** [comment]
Same thing for OrderByExpression.

**Comment by Preston-Crary** [comment]
Pushed a fix for InlineSQLHelperImplTest.

**Comment by vicnate5** [comment]
@Preston-Crary some issues to see here

Service Builder changes
https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328617/AXIS_VARIABLE=0,label_exp=!master/consoleText

Wildfly/Jboss Startup
https://testray.liferay.com/reports/production/logs/test-1-8/1579113959084/test-portal-acceptance-pullrequest(master)/4682/functional-smoke-wildfly160-mariadb102-jdk8/0/0/jenkins-console.txt.gz
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/351239/AXIS_VARIABLE=0,label_exp=!master/consoleText

Library unit tests
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/352803/

SF
`modules/apps/portal-security/portal-security-permission-impl/src/main/java/com/liferay/portal/security/permission/internal/InlineSQLHelperImpl.java`
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/298914/AXIS_VARIABLE=0,label_exp=!master/console

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8734

**Pull request closed without merging**
