### PR TITLE
LPS-73640 Keep dependencies to a minimum

### PR DESCRIPTION
**Pull request by csierra**
hey @shuyangzhou, 
please consider keeping the dependencies for service tracker collections to a minimum. This will favor reusability in other OSGi environments since less bundles need to be downloaded and installed in runtimes. 
We are only using petra for one string concatenation so maybe we can just use `StringBuilder` for that. 

Thanks in advance. 

/cc @ahdezma

### CODE REVIEW

**Comment by csierra** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@csierra I am not really against this change, after all it is very small and simple.
But this is against the purpose of extracting petra. We did that in order to make them reusable. And they are small standalone bundle/lib jars. In the long run, no one can stay clean on dependencies, it is going to inevitably happen.
Is there a real reason behind this? other that this is less "clean"?
For the long run and also for system wide usages applying, I think we should embrace dependencies, as long as they are clean petra ones.

**Comment by csierra** [comment]
hey @shuyangzhou, 
yes, I agree. It is just that this library (service tracker collections) is intented to be used in _"OSGi only runtimes"_. In those scenarios it might be more difficult to justify to have to add two dependency jars just to concat a string. 
In the long term I fully agree we might have to add dependencies, but I would still try to keep those to a minimum whenever possible.

Thx!

**Comment by shuyangzhou** [comment]
@csierra see https://github.com/brianchandotcom/liferay-portal/pull/53848. I let this one in for now. If later it adds in more "petra" like api usages, we will add back the petra dependencies to avoid the duplicated code and ensure the performance. If it stays clean like this, we will just leave it as it is.

**Pull request closed without merging**
