### PR TITLE
[TS] LPS-128193 Prioritize classes provided from the bundle itself, over classes provided from it's module dependencies

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @shuyangzhou ,

As discussed:
- QA has added the smoke test: [LRQA-65299](https://issues.liferay.com/browse/LRQA-65299) and the test has been committed
- The proposed fix is to: prioritize classes provided from the bundle itself, over it's module dependencies
- No need to worry about duplicate classes, since only the first matching class would be used 
  - (this is what normally happens anyways when 2 different versions of the same jar are provided in the classpath)

Please let us know if you have any questions.
Thanks!

/cc @georgel-pop-lr @vicnate5

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:poshi

**Comment by georgel-pop-lr** [comment]
> s know if you have any questions.
> Thanks!

Hi @ericyanLr,

Good to see already a proposed solution in place, please let me know if this solution could already be sent to our client or needs to be reviewed first.

I guess the tests related changes in LRQA-65299 are not needed in the patch.

Regards.

**Comment by shuyangzhou** [comment]
@vicnate5 is this good to go?

**Comment by vicnate5** [comment]
@shuyangzhou The new test did not run here. Running at https://github.com/vicnate5/liferay-portal/pull/1659

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 , I will wait for your results then.

**Comment by vicnate5** [comment]
@shuyangzhou Test passed. This is good to go.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
