### PR TITLE
Upgrade dm 7

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@shuyangzhou Hypersonic Startup issue still occurring on most recent results: https://testray.liferay.com/reports/production/logs/test-1-2/1568473250667/test-portal-acceptance-pullrequest(master)/5040/functional-tomcat90-hypersonic20-jdk8/5/0/jenkins-console.txt.gz

**Pull request closed without merging**
