### PR TITLE
LPS-104365 Since Javascript files, like soy AutoFields, depend on ResourceBundle keys, they must be updated once a new overriding ResourceBundle gets deployed.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz this can not be a right solution. LanguageResources is tracking ResourceBundle as services. If there are other users who care the ResourceBundle changes, they should track them in the same way. What's the point to have LanguageResources re-fire out the notification?

**Comment by marianoalvarosaiz** [comment]
I just wanted to reduce duplicated code and avoid tracking same services in different places. I've changed that, see https://github.com/shuyangzhou/liferay-portal/pull/8547

**Pull request closed without merging**
