### PR TITLE
Lps 129336

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-129336

Notes from @brianikim:
>Straightforward issue here. We are updating xstream to 1.4.16 due to the security issues reported in LPS-129336.
>
>Sincerely,
>Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the test results, thanks!

**Comment by brianikim** [comment]
Hello @shuyangzhou and @vicnate5

Let me know if there are any issues with the PR.

Sincerely,
Brian Kim

**Comment by vicnate5** [comment]
@shuyangzhou Only issues here are CI related. Going to try to forward again since I expect the issues should be cleared up now.

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
