### PR TITLE
LPS-83992 Portlet 3.0: Develop the bean portlet CDI portable extension (basic structure)

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou The bean portlet CDI portable extension is about 4,000 lines of Java source. In order to keep the review process manageable, this is an initial PR that contains only the basic structure of the module. Note that until the OSGi+CDI Spec is finished by Ray, developers will be required to include this module and weld-servlet.jar in WEB-INF/lib.

Once this PR is merged I will send subsequent commits that are designed to be more easily reviewed. For example, the implementation of `@PortletRequestScoped`, `@PortletSessionScoped`, and `@PortletRenderStateScoped` will be in a single commit.

/cc @gamerson @jhinkey @sez11a @vsingleton @rotty3000

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou This PR contains one commit that is an entirely new module under liferay-portal/modules/util. The failures listed here must be unrelated.

Please review when you can, thanks.

**Comment by shuyangzhou** [comment]
@ngriffin7a should this module be inside util? Don't we want to eventually release with it?

**Comment by ngriffin7a** [comment]
@shuyangzhou Two things have to happen before this module can be released in $LIFERAY_HOME/osgi/modules:
1. The OSGi+CDI Spec has to be finished
2. Ray has to make it possible to put weld-osgi-bundle.jar in $LIFERAY_HOME/osgi/modules instead of including weld-servlet.jar in WEB-INF/lib.

But there is no definitive timeline for that to happen. I put this module under util because developers have to include it in WEB-INF/lib alongside weld-servlet.jar for now. If you think it belongs in a different directory, please feel free to move it in a code review commit or tell me where you would like it to live and I'll send another PR.

**Comment by shuyangzhou** [comment]
@ngriffin7a just treat it as a normal module, but remove its build trigger to make it not part of all, until you think it is ready. Put it into any location that makes sense for its final status. util is not the right place, it will never be part of the release build if keeping it here.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6542

**Pull request closed without merging**
