### PR TITLE
Startup optimization 263 remove dependency manager thread pool

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou I think this breaks an upgrade process for older liferay versions, it happened for 6.2 uniquely on the version i saw.
https://gist.github.com/kyle-miho/501eabba71df549a78ee6e919d82ea1c
     [java] 2023-07-28 07:19:16.029 ERROR [SystemExecutorServiceUtil-9-com.liferay.portal.spring.extender.internal.configuration.ServiceConfigurationInitializer-com.liferay.change.tracking.service][UpgradeStepRegistratorTracker:178] Failed upgrade process for module com.liferay.journal.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.LayoutClassedModelUsage' doesn't exist
     
 Im going to try and reproduce locally with this PR

**Comment by kyle-miho** [comment]
Was not able to reproduce the upgrade issue locally after multiple tries, looking into the rest of the results for unique failures, there are a lot to look through

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Comment by kyle-miho** [comment]
Potential unique failure here: UpgradeEnhancement#RemoveModulesWithSchemaVersionChange

**Comment by kyle-miho** [comment]
@shuyangzhou  I was able to reproduce this issue, 
[data-archive-portal-mysql (4).zip](https://github.com/shuyangzhou/liferay-portal/files/12202577/data-archive-portal-mysql.4.zip)
Steps: 
1) Import attached DB to mysql
2) run ./db_upgrade.sh tool in tools/portal-tools-db-upgrade-client
3) Fill in tomcat parameterse
4) Wait for Upgrade to finish
5) Check recent upgrade log, you will see this exception `java.sql.SQLSyntaxErrorException: Table 'lportal.LayoutClassedModelUsage' doesn't exist`

**Comment by shuyangzhou** [comment]
@kyle-miho is it failing stable or random?

**Comment by shuyangzhou** [comment]
Brought back the sync upgrade execution behavior here https://github.com/shuyangzhou/liferay-portal/pull/11153

**Pull request closed without merging**
