### PR TITLE
LPS-X Lazy SXPElement loading

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@kyle-miho please help me check the results, thanks!

**Comment by kyle-miho** [comment]
@shuyangzhou failures unrelated, PR good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132260

**Pull request closed without merging**
