### PR TITLE
LPS-52665

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Shuyang,

Without also setting the web portal directory, using an unexploded war still won't function properly since it cannot find any of the CSS files. It looks like you removed it in one of your commits, but I wasn't sure if that was on purpose or not.

Let me know if you have any questions. Thanks.

**Comment by shuyangzhou** [comment]
Are you sure it is broken? It is duplicated with PropsUtil's constructor, that's why I removed it.

**Comment by jonathanmccann** [comment]
Yes, PropsUtil is hit before PortalContextLoaderListener.contextInitialized (due to the public static final boolean) so the web directory is using the incorrect portal lib directory in PropsUtil. This is why we had to do interesting things in order to make all of this work properly.

**Comment by shuyangzhou** [comment]
What "public static final boolean" do you mean? PropsUtil is loaded correctly for me locally.

Please make it clear that who is pre-initializing PropsUtil. Paste me the call stack to its initialization.

If someone is actually doing this, we still can not have the duplicated logic in both PropsUtil and PortalContextLoaderListener. We will have to move it completely to PortalContextLoaderListener.

**Comment by jonathanmccann** [comment]
Sorry Shuyang, you are correct. I was working off of 6.2.10 where there was:

```java
public static final boolean CACHE_CLEAR_ON_CONTEXT_INITIALIZATION =
		GetterUtil.getBoolean(
			PropsUtil.get("cache.clear.on.context.initialization"));
```

in PortalContextLoaderListener which was initializing PropsUtil first.

**Pull request closed without merging**
