### PR TITLE
LPS-87808 Update tests

### PR DESCRIPTION
**Pull request by inacionery**
Hi @shuyangzhou,

We have a concurrency problem in the workflow walkers causing a database key persistence error. The problem is occurring because of this change https://github.com/liferay/liferay-portal/commit/4d3c2e127b006970d1609266969914fe27ae7c0c. I did a workaround to try to fix this issue, but I believe it might generate some performance bottlenecks.

I've updated this test https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-test/src/testIntegration/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/test/WorkflowTaskManagerImplTest.java#L265 to cover this case. 

Could you please help with that?

Thx!

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara please take this over, thanks!

**Comment by mtambara** [comment]
ci:close

**Comment by mtambara** [comment]
See https://github.com/inacionery/liferay-portal/pull/154

**Pull request closed without merging**
