### PR TITLE
[Bug Fix]LPS-135290

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on start up and benchmark tests.

FYI @dantewang
Thanks.
Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by GinsonRen** [comment]
@tinatian Here is the startup diff result, runtime result may need more time since main env quite busy recently.

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | dacf93bb | 45264 | 23724 | 23724 | 24259 | 23368 | 23461 | 23707.2 | -
PR-10189 | - | 45301 | 23261 | 23578 | 23535 | 23653 | 23473 | 23500 | -0.87%

**Pull request closed without merging**
