### PR TITLE
LPS-83631 Fix autocomplete DDM regression

### PR DESCRIPTION
**Pull request by Preston-Crary**
Please wait for the tests to pass.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by vicnate5** [comment]
CC @rafaprax @pedroqueiroz

**Comment by vicnate5** [comment]
@shuyangzhou Can you prioritize this review? This is a blocker for Fix Pack 1.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61586

**Pull request closed without merging**
