### PR TITLE
LPS-118655

### PR DESCRIPTION
**Pull request by attilabakay**
hi @shuyangzhou,

Based on [this](https://github.com/brianchandotcom/liferay-portal/pull/92651) I modified the test case. Could you forward it again?
previous pulls: #9323 #9330

https://issues.liferay.com/browse/LPS-118655

Best,
Attila

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failure not unique, also in upstream. This can be forwarded.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/92716

**Pull request closed without merging**
