### PR TITLE
LPS-68289 Fix search writer destination interrupt and remove IdempotentRetryAssert

### PR DESCRIPTION
**Pull request by Preston-Crary**
Depends on and includes https://github.com/shuyangzhou/liferay-portal/pull/3287

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:reopen please?

**Comment by Preston-Crary** [comment]
@michaelhashimoto I thought reopen meant that it would stay open no matter what failed?  Is this intended?

**Comment by michaelhashimoto** [comment]
@Preston-Crary - That's only for test failures.  This is an branch validation error.

It will only stay open if it:
1. It is sent to yourself.
2. It has a special comment with the following attribute.
<pre>auto-close="false"</pre>

You should be making these changes in the '[com-liferay-journal](https://github.com/liferay/com-liferay-journal)' repository.

<em><strong auto-close="false">Do Not Auto-close this pull request.</strong></em>

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
@Preston-Crary - Actually it won't work for now, the only place we check for the auto-close comment is during the test execution.

Can you potentially just test it by sending a pull request to yourself?

**Comment by Preston-Crary** [comment]
Sent a pull to myself to see if it will fail https://github.com/Preston-Crary/liferay-portal/pull/195

**Pull request closed without merging**
