### PR TITLE
[MessageBus]LPS-102995

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Still seeing SegmentUserResourceTest failed, looking into it.

Tina

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @shuyangzhou @vicnate5 ,
The SegmentUserResourceTest failure is not related to my change, but caused by RenderFragmentEntryStrutsActionTest, please see LPS-104788.

It was not shown because these two tests were in different test groups, and my pull added a new integration test, and causing them happen to be in same group, then error comes up.

Tina

**Comment by vicnate5** [comment]
@tinatian @shuyangzhou New results look good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81287

**Pull request closed without merging**
