### PR TITLE
COMMERCE-2475 - Dispatch framework

### PR DESCRIPTION
**Pull request by matijapetanjek**
Attaching comment from last PR: 

> Hi @shuyangzhou I have added new changes on top of the old ones from the first PR. After discussing with @igorbeslic, we have renamed DispatchTrigger -> DispatchTask, this entity should represents a task that will be executed according to cronExpression by Liferay scheduler engine. 
I have extracted startDate and endDate fields to be transient to avoid duplicated data in DB and reuse existing values from Triggers table.
 Unfortunately I didn't find a way to read cronExpression value using LR scheduler api, that is the only reason why there is a cronExpression column in DispatchTask. The only example I found of reading [cronExpression value from trigger](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java#L544) is not applicable for our case and [Liferay Trigger interface](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/scheduler/Trigger.java) doesn't expose that value. Is there maybe another way to fetch cronExpression other than store it in DispatchTask table?

Here is the new PR with my updates rebased on top of yours.

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@matijapetanjek I disagree with the renaming from trigger to task. We on purposely pick the name trigger about one year ago. The entity only enclose the info about when and how a job is going to be executed. The entity is not the job itself, therefore it is not a task. Please drop the renaming parts and resend.

CC @tinatian

**Comment by igorbeslic** [comment]
Hi @tinatian can you check Matia's question in description of PR - about ability to obtain cronExpression
Thank you!!!!

**Pull request closed without merging**
