### PR TITLE
LPS-81218 Portlet 3.0: Enhance API of LiferayPortletResponse and PortletURLFactory for MimeResponse.Copy

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
c:reopen

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@jpince: The POSHI failures are the same unrelated ModelListener failures from the other day. Also, not sure why the "modules-integration-db..." tests aborted. They would also seem totally unrelated since this PR is concerned with construction of PortletURLs. Please take a look when you can and let us know so that @shuyangzhou can review. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58762

**Pull request closed without merging**
