### PR TITLE
[ResourceAction]LPS-112054

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Only real failure here is the baseline for `microblogs-api` and `oauth-api`
https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/354696/AXIS_VARIABLE=0,label_exp=!master/consoleText

No regressions found. 

Blockers on Relevant look like flaky tests as they have randomly failed before.

**Comment by tinatian** [comment]
@dantewang Please take a look at the real failures on Victor's comment

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
