### PR TITLE
Startup optimization 308 parallel aop service manager

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@zhangyan0701 can you watch this PR and review the results?

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 pushed a fix for the random post upgrade startup races. Should only affect the upgrade run within relevant. No need to rerun startup batch(I assume it does not contain any upgrade logic).

**Comment by shuyangzhou** [comment]
Rerunning at https://github.com/shuyangzhou/liferay-portal/pull/11244

**Pull request closed without merging**
