### PR TITLE
LPS-114352 Amazon S3 connector doesn't work with region eu-north-1

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @shuyangzhou 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 do we have any AWS test cases to run for this?

**Comment by vicnate5** [comment]
@shuyangzhou We have a test, it will need to be executed manually since we do not have this automated.

@zhangyan0701 can you execute [this test](https://docs.google.com/document/d/1aO5jEhQmkwhDFNxBxbQlQzmbh-GOord5s0CPSONmMz4/edit#heading=h.4pu4qkftyumm) on this PR? The instructions are old, but hopefully enough to configure. 

If you see any problems, test also against master head (to confirm this change as the cause)

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Manual testing passed on local. Document Library successfully connected to S3 bucket in the eu-north-1 region.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
