### PR TITLE
LPS-188500 Break dependency circle created from LPS-185081. ExportImp…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ortServiceConfigurationModelListener is collected by ConfigurationPersistenceManager which made it considered part of CM, and it depends on ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl which consumes CM code creating a dependency circle.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Locally ran `Object#CanViewObjectAfterRestart` since this test originally caught the regression. It is now passing.

**Pull request closed without merging**
