### PR TITLE
Mime types cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@shuyangzhou Real failures in integration tests:
[com.liferay.document.library.search.test.DLFileEntrySearchTest](https://testray.liferay.com/reports/production/logs/2022-02/test-1-26/test-portal-acceptance-pullrequest(master)/1663/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
com.liferay.document.library.search.test.DLFileEntrySearchLegacyDDMIndexFieldsTest

Only need to re-run document suite after these are fixed, the rest is good.

**Comment by shuyangzhou** [comment]
ci:test:document

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@zhangyan0701 Can you confirm the issue above is fixed now?

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Pushed a new commit which only affect a few clean module, sf and relevant should be enough to cover the new change.

**Comment by zhangyan0701** [comment]
The issue above was fixed. No other issue found.

**Comment by vicnate5** [comment]
@shuyangzhou This should be good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113302

**Pull request closed without merging**
