### PR TITLE
LPS-139970 support DLStore OSGi services

### PR DESCRIPTION
**Pull request by rotty3000**
Signed-off-by: Raymond Augé <raymond.auge@liferay.com>

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1277401_393

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by rotty3000** [comment]
also @vicnate5 could you refresh my memory on how to run a suite like `dl-store` locally? I'd like to verify it myself as well.

**Comment by vicnate5** [comment]
@rotty3000 The test suite is a combination of backend tests, functional tests, and tests configured to run against a real AWS S3 store account.

The backend tests would be the only ones easy to run locally. Uses these globs to search for tests to run
```
**/change-tracking-store-test/**/*Test.java,\
**/portal-store/**/*Test.java
```
https://github.com/liferay/liferay-portal/blob/94afffbbf3eea2f2ef0dbbd9fe34d2959f30e71b/test.properties#L2497-L2499

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/107996

**Pull request closed without merging**
