### PR TITLE
COMMERCE-7203 Apply MVCC to commerce-products

### PR DESCRIPTION
**Pull request by ctang3**
Continuing from https://github.com/Preston-Crary/liferay-portal/pull/1526

https://issues.liferay.com/browse/COMMERCE-7203

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by kyle-miho** [comment]
Semantic versioning issue due to buildService in commerce-product-api, some packages need to be incremented like com.liferay.commerce.product.model
Also failures in these integration tests are likely unique as they are passing at head
com.liferay.commerce.subscription.test.CommerceSubscriptionEntryTest > testOverrideCPInstanceSubscriptionInfoAllEnabled
com.liferay.commerce.subscription.test.CommerceSubscriptionEntryTest > testOverrideCPInstanceSubscriptionInfoDefinitionEnabled

**Comment by shuyangzhou** [comment]
@ctang3 please fix and resend.

**Comment by ctang3** [comment]
Fixed, please see https://github.com/shuyangzhou/liferay-portal/pull/10444

**Pull request closed without merging**
