### PR TITLE
[Multi-company Integration test]LPS-135920

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
To use the company data generation integration test, please do:
1 Add the following properties to portal-ext.properties:
sample.data.company.count=xxx
sample.data.user.per.company.count=xxx
sample.data.output.dir=output
2. Modify `@DataGuard(scope = DataGuard.Scope.CLASS)` to `@DataGuard(scope = DataGuard.Scope.NONE)`
3. Run the integration test

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks
Tina.

**Comment by vicnate5** [comment]
@tinatian Test failures not related. The specific tests added in this PR passed https://testray.liferay.com/home/-/testray/case_results/1549613162

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10191

**Pull request closed without merging**
