### PR TITLE
Startup optimization 219 opensaml

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:saml

**Comment by vicnate5** [comment]
@gaborlovasdotcom @JoyceWang08211 risky change for openSaml. I triggered the SAML suite, anything else we should test?

**Comment by shuyangzhou** [comment]
Sorry, missed one usage apply. Updated and rerunning.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by JoyceWang08211** [comment]
> @gaborlovasdotcom @JoyceWang08211 risky change for openSaml. I triggered the SAML suite, anything else we should test?

Hi @vicnate5, SAML suite is good enough to cover the relevant changes.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by vicnate5** [comment]
@Kvale1733 can you check the results here?

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found. SAML metatdata url is invalid. This is affecting most SAML tests.

Steps to reproduce:
1.Go to Control Panel > SAML Admin
4. Change role to Identity Provider
5. Add samlidp as Entity Id and save
6. Create Certificate with Liferay as the common name and samlidp as Key Password and Save
7. Click enabled checkbox and save
8. Go to http://localhost:8080/c/portal/saml/metadata

Expected Results: Can view the saml metadata
Actual Results: The user is taken to home page. The following error appears in the console
```
[beanshell] 2023-04-20 14:46:28.484 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="500", msg="", uri=/c/portal/saml/metadata}
[beanshell] javax.servlet.ServletException: Servlet execution threw an exception
[beanshell] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:216) ~[catalina.jar:9.0.73]
[beanshell] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.73]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-25/test-portal-acceptance-pullrequest(master)/576/functional-tomcat90-mysql57-jdk8/1/13/jenkins-console.txt.gz?authuser=0)

The working metadata looks like this
Expected

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by gaborlovasdotcom** [comment]
I requested developer review also from @stian-sigvartsen, @oliverkecskemety

**Comment by stian-sigvartsen** [comment]
Hi @shuyangzhou . Was DBMetadataResolver required prior to 0c7e229b753317f801924044aa8ee2f1b4c1c5bd ?

**Comment by shuyangzhou** [comment]
@stian-sigvartsen yes, see https://github.com/shuyangzhou/liferay-portal/commit/0c7e229b753317f801924044aa8ee2f1b4c1c5bd#diff-ecf67dcb7691a09c216ce0934b43826246894eb183ee98d4f20e8f74b60c198bL467 MetadataManagerImpl won't activate without it.

**Comment by stian-sigvartsen** [comment]
@shuyangzhou Thanks! What about if a customer blacklists the `DBMetadataResolver` component and provides their own `MetadataResolver` service though?

**Comment by shuyangzhou** [comment]
If that's a real thing that needs support, it is better to be via an explicit configuration. If we always assume using blacklist to swap an mandatory service is expected. then no service can be considered mandatory anymore. This kind of structure happens everywhere in the system, not just opensaml.

**Comment by stian-sigvartsen** [comment]
The only other thing is there is a functional change in 641ee161a94fe59d52cbc2a64f37a95e9d620257 . 

@gaborlovasdotcom if you are testing this please can you check the UX for these cases:

**Scenario 1**
1. The DXP SAML SP is configured without an encryption certificate. 
2. Start DXP
3. Check for noise in the log

**Scenario 2**
1. The DXP SAML SP is configured with an encryption certificate, then IDP is connected and receives that certificate via metadata. For stable testing I would upload the generated metadata XML at `/c/saml/metadata` manually into the IDP's connection to it.
2. Remove the encryption certificate from the DXP SAML SP.
3. Attempt a SAML SSO from DXP
4. Check log for noise

**Scenario 3**
Try the reverse of scenario 2. i.e. replace words "with" with "without" and "remove" with "add" in steps 1 & 2 respectively.

If you would prefer if I test this just let me know, but these might be good scenarios for QA to test independent of this PR even.

**Comment by Kvale1733** [comment]
@shuyangzhou One of the failing tests is a regression and not a flakey issue. SSO does not fail when algorithms mismatch.

Steps to reproduce:
1. Add www.able.com to hosts file (if not already there)
2. Startup two separate bundles with separate databases on separate ports (8080  and 9090)

- On both bundles add config com.liferay.saml.opensaml.integration.internal.bootstrap.SecurityConfigurationBootstrap.config.
- On the first bundle (8080) add the following to the config file
```
blacklisted.algorithms = ["http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", "http://www.w3.org/2001/04/xmldsig-more#rsa-sha384", "http://www.w3.org/2001/04/xmldsig-more#rsa-sha512", "http://www.w3.org/2001/04/xmlenc#sha256", "http://www.w3.org/2001/04/xmldsig-more#sha384", "http://www.w3.org/2001/04/xmlenc#sha512"]
```

- On the second bundle (9090) add the following content to the config
```
blacklisted.algorithms = ["http://www.w3.org/2000/09/xmldsig#rsa-sha1", "http://www.w3.org/2000/09/xmldsig#sha1"]
```

3. Sign in on localhost:8080 and go to Control Panel > SAML Admin
4. Set SAMLE Role as Identity Provider and set samlidp as Entity ID
5. Click Save
6. Click create certificate
7. Add "Liferay" as common name and set "samlidp" as Key Password
8. Click Save
9. Click Enabled Checkbox and save
10. Sign in to www.able.com:9090
11. Go to Control Panel > SAML Admin
12. Set SAML role to Service Provider and set "samlsp" as Entity ID
13. Click Save
14. Under "Certificates and Private Key" click Create Certificate
15. Add "Liferay" as common name and set "samlsp" as Key Password
16. Click Save
17. Go to Identity Provider Connections tab
18. Click Add Identity Provider
19. Add "samlidp" as Name and Entity ID
20. Click Enabled Checkbox
21. Add "http://localhost:8080/c/portal/saml/metadata" as Metadata URL
22. Click Save
23. Go back to General tab
24. Click Enabled checkbox and Save
25. Sign back into localhost:8080
26. Go to Control Panel > SAML Admin
27. Click Service Provider Connections tab
28. Click Add Service Provider
29. Add "samlsp" as Name and Entity ID
30. Click Enabled Checkbox
31. Add "http://www.able.com:9080/c/portal/saml/metadata" as Metadata URL
32. Add "emailAddress" for Name Identifier Attribute Name
33. Click Save
34. Go to http://www.able.com:9080/c/portal/saml/metadata
35. Verify "http://www.w3.org/2000/09/xmldsig#rsa-sha1" is not present in the metadata

Expected Results: "http://www.w3.org/2000/09/xmldsig#rsa-sha1" Is not present in the HTML source text
Actual Results: The above text is present in the HTML source text

**Comment by stian-sigvartsen** [comment]
@shuyangzhou That's an interesting point. The way the registrator is alerting the admin to the mis-configuraiton may not be ideal and too noisy. We should review this against other code for the correct pattern.

But I think we should log such errors at configuration time (or startup) rather than during a SSO attempt. Because otherwise it becomes less likely that we catch a regression early via the log scanner or locally during dev.

Also I am not quite sure about the correctness of failing all SSO attempts and showing a generic error to users when there is an issue with decrypting one or more assertions. At the moment we just log an error for that and continue with the SSO processing.

Is there a big performance gain achieved with the commit? 
Wondering if maybe we could consider it separately so not to hold things up.

**Comment by shuyangzhou** [comment]
@stian-sigvartsen the whole point of this change is to lazy the opensaml activation until used. We can not let any thing run during startup. Otherwise this thing becomes pointless. the overhead came from 2 sources, the opensaml bootstrap itself and our component activation logic.
We are moving the whole system to the direction of lazy activation.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the new results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No more regressions.

**Comment by shuyangzhou** [comment]
Thanks @Kvale1733 !

@stian-sigvartsen @gaborlovasdotcom @JoyceWang08211 anything else you guys need to check? Can I proceed with this pull?

**Comment by gaborlovasdotcom** [comment]
LGTM @shuyangzhou

**Comment by stian-sigvartsen** [comment]
Hi @shuyangzhou . It sounds like the benefits of moving to a fully lazy loaded system outweigh customization capabilities we get via OSGi. So I'm happy to go ahead generally but please can you address the behavioural change?

> Also I am not quite sure about the correctness of failing all SSO attempts and showing a generic error to users when there is an issue with configuring the Decryptor. At the moment we just log an error for that and continue with the SSO processing.

It looks all that is needed is some exception handling in `WebSsoProfileImpl`. Then you should be able to preserve the logging also, with the only difference being that they will happen at SSO time.

**Comment by shuyangzhou** [comment]
@stian-sigvartsen added a new commit to log on failing to create Decrypter.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by shuyangzhou** [comment]
@Kvale1733 please check the new results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions. Results look good.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133862

**Pull request closed without merging**
