### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull includes the support for clustering, sidecar is also disabled in this pull.

Known issue:
Random error when shutting down master node when cluster is enabled, example of errors:https://gist.github.com/tinatian/60184861dcdf7265f4b161d88e6dcffc and https://gist.github.com/tinatian/7a04bb4fd6435fe5825139842b5b65a7.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
Enable sidecar and run ci test here : https://github.com/vicnate5/liferay-portal/pull/1414

**Comment by tinatian** [comment]
@joshchong Please scan the test results.

Thanks.
Tina

**Comment by joshchong** [comment]
Hey @tinatian there are a few [unique es7 modules-unit failures in the search-es7 suite](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/306228/). Can you take a look?

There are also a good amount of unique modules-integration failures in the `search-solr` suite, but it's possible they are flukes so I can rerun them separately.

**Comment by tinatian** [comment]
Fix unit test and simplify enable/disable sidecar, resend at https://github.com/shuyangzhou/liferay-portal/pull/8873.

Tina

**Pull request closed without merging**
