### PR TITLE
LPS-X We call CompanyLocalService.getCompanies() many times during st…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…artup, stick to the same method call to reuse cache.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122445

**Pull request closed without merging**
