### PR TITLE
Lps 187404 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 this is for https://issues.liferay.com/browse/LRQA-81065 , please help me watch it, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136519

**Pull request closed without merging**
