### PR TITLE
LPS-75948 Portlet 3.0: Detect portlet spec version found in the portlet.xml descriptor

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince or @timpack: Please take a look and if none of the failures are related to this PR then please let us know so that Shuyang can review. Thanks.

**Comment by jpince** [comment]
@timpak

**Comment by timpak** [comment]
@ngriffin7a @jpince the failures aren't related to the PR.

@shuyangzhou please review.

**Comment by ngriffin7a** [comment]
@timpak Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/57445

**Pull request closed without merging**
