### PR TITLE
LPS-141847

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz I did not realize the ticket is saying setting global tx isolation level to serializable. In this case any nested tx will fail to launch, not just DefaultActionableDynamicQuery. And we have a lot of new tx launching logic in the codebase. They will all fail in the same way.

The global tx isolation level should not be set to serializable, at least not without a major customization or very limited usages in portal.

What's the reason for anyone to make it globally serializable?

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou this is their reply: https://issues.liferay.com/browse/LPP-42861?focusedCommentId=2566355&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2566355

Even if we could take a look to their specific MB use case and fix without making global tx serializable, if we don't want to fix the DefaultActionableDynamicQuery and assume that the portal cannot work with tx serializable, maybe we should document it.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz Lost of updates is a common issue, and should be addressed with proper MVCC usage. Forcing portal to be globally serialized on tx is a no go. It has too heavy impact to the system to break functions, not even talking about the performance impact.
The support for serialization isolation level is necessary, since in some weird case, we might need to force a specific tx to be serialized. As for the global setting, it is there mainly to keep the setting has a complete values. Also in case of heavy customization, where most of out of box functions are wiped, this could still work.
But in practice, we only recommend repeatable read and read committed.
@jhinkey do we have docs for this? If not, please add it.

@marianoalvarosaiz please collect more details from the customer, their issue about MB needs to be fixed in MB, not changing global setting for tx isolation level.

**Comment by jhinkey** [comment]
@shuyangzhou Regarding this comment:

> [a global serialized setting can be used] in case of heavy customization, where most of out of box functions are wiped...

What do you mean by _[wiping] out of box functions_? Do you mean using DXP in a mostly "headless" manner?

**Pull request closed without merging**
