### PR TITLE
[TS] LPS-110895

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPP-36834
https://issues.liferay.com/browse/LPS-110895

From @wanderlast:

> In LPS-110213, an implementation of the file moving feature was re-added to the portal. This involves a call to retrieve all file versions, retrieving each file based on the version labels retrieved and adding them to their new location. The old files are subsequently deleted.
> 
> While this works for Simple File Store (SFS), Advanced File System Store (AFS) is currently broken. This is due to the call in getFileVersions(long, long, String). Previously, the call used the same method in FileSystemStore since no overriding method implementation was made in AdvancedFileSystemStore. However, this method of retrieving file versions is incorrect for AFS. In SFS, the versions are stored as the file name (e.g. "1.0") so simply retrieving the file name as a version label is valid. However, the file naming scheme for AFS is much more complex (e.g. "1_1.0.afsh") and using that as a version label results in a file name of "1_1_1.0.afsh.afsh" since the full file name is incorrectly used for the version label. This therefore causes a failure to retrieve any file since the file names returned are all incorrect.
> 
> The fix is implementing getFileVersions(long, long, String)  in AdvancedFileSystemStore. The implementation iterates through all of the fileNames retrieved by FileSystemStore's implementation and then removes the non-version related information.
> 
> Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the failure.

**Comment by vicnate5** [comment]
Test failure is an unrelated bug
Fix is here: https://github.com/brianchandotcom/liferay-portal/pull/87061

**Comment by ChrisKian** [comment]
Forwarded here: https://github.com/tinatian/liferay-portal/pull/1757

**Pull request closed without merging**
