### PR TITLE
Lps 122041

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@slnn please run a data point for this pull, thanks!

**Comment by slnn** [comment]
Update test result for startup in this doc:https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit?usp=sharing

**Comment by shuyangzhou** [comment]
@slnn can you check the profile result? This change should introduce a new thread named ```LiferayServiceExtender.class.getName() + "-BundleTrackerOpener"```. But the monitoring result did not show a thread count increase.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by slnn** [comment]
Hi @shuyangzhou 

Do you mean this:
PR-9495

**Comment by shuyangzhou** [comment]
@slnn yes, that's the one. Locally I see about one second level of saving. But it is understandable that this kind of async saving varies depending on the concurrent ability of the machine. I was just wondering why this pull and the baseline show the same number of thread creations. I was expecting one more count of thread in this pull.

**Comment by slnn** [comment]
I will compare the profiles about the baseline and the pull to see if I can find some clues

**Comment by slnn** [comment]
Hi @shuyangzhou 

This pull introduced a new thread named LiferayServiceExtender.class.getName() + "-BundleTrackerOpener". But the thread count did not be increased because this pull reduced a thread named like PromiseFactory,pool-2-thread-*, please see these screenshots:

Baseline:
Baseline-create-thread

This pull:
PR-9495-create-thread

**Comment by shuyangzhou** [comment]
Ok, thanks @slnn ! Not sure why it went away, the change has nothing to do with that thread. But it does not really matter, you don't need to look into any further.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
