### PR TITLE
Lps 127030 test

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mtambara can you check the unit test failures? Seems from this pull.

**Comment by mtambara** [comment]
@shuyangzhou The AuthVerifier test is failing in master, The CompanyIndex test looks like it's caused by a recent change but hidden in master by the failures this pull fixes

**Comment by shuyangzhou** [comment]
@vicnate5 please confirm, if this pull is clear. We should notify search team to cleanup the failing unit tests.

**Comment by vicnate5** [comment]
The `CompanyIndexFactoryTest` has been failing since Jan 27th due to this issue this pull fixes, I don't have a way of knowing if there was another regression on the test in the last couple weeks.
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest > classMethod FAILED
     [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.configuration.persistence.ConfigurationOverridePropertiesUtil
     [exec]         at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._overrideMap(ConfigurableUtil.java:245)
     [exec]         at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil.createConfigurable(ConfigurableUtil.java:60)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionFixture$1.<init>(ElasticsearchConnectionFixture.java:61)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionFixture.createElasticsearchConnection(ElasticsearchConnectionFixture.java:57)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionFixture.createNode(ElasticsearchConnectionFixture.java:100)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchFixture$ElasticsearchConnectionFixtureSingleton.start(ElasticsearchFixture.java:154)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchFixture.setUp(ElasticsearchFixture.java:113)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest.setUpClass(CompanyIndexFactoryTest.java:71)```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/98611
Those are real search test failures, should be handled by search team.

**Pull request closed without merging**
