### PR TITLE
LPS-62918 revert the change: holding response in tags causes extension of response lifecycle, which results in much heavier old generation GC

### PR DESCRIPTION
**Pull request by dantewang**
It was added for future usage and I didn't find anyone using it. However the old gen GC on MB is much heavier.

### CODE REVIEW

**Comment by dantewang** [comment]
cc @juliocamarero

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/36426

**Pull request closed without merging**
