### PR TITLE
LPS-129722 Use Objects.equals() in getColumnBitmask() and clear model caches when updating order by columns

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@Preston-Crary Looks good, no unique failures found.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9918

**Pull request closed without merging**
