### PR TITLE
LPS-101084 Apply view count service to AssetEntry

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@kyle-miho please help me scan this pull's result, thanks!

**Comment by kyle-miho** [comment]
Still looking, there seem to be some integration tests failing due to this pull, possibly 1 functional test

**Comment by kyle-miho** [comment]
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/276363/#showFailuresLink
@shuyangzhou there may be a lot of Journal*SearchTest regressions caused by this pull
JournalArticleSearchTest.testSearchBaseModel
JournalArticleSearchTest.testSearchBaseModelWithDelete
JournalFolderSearchTest.testSearchMixedPhraseKeywords, etc.

**Comment by vicnate5** [comment]
@kyle-miho are these specific to a database?
I do not see the same failures on MySQL https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/286057/#showFailuresLink

**Comment by kyle-miho** [comment]
@vicnate5 specific to db2

**Comment by shuyangzhou** [comment]
Those are real search tests, right? This pull could only affect DB search.

**Comment by vicnate5** [comment]
Also still seeing unsatisfied references on startup post-upgrade from 7.1. 
Seen on DB2 and PostgreSQL
https://testray.liferay.com/reports/production/logs/test-1-14/1571675549936/test-portal-acceptance-pullrequest(master)/4980/functional-upgrade-tomcat90-db2111-jdk8/3/0/liferay-log.txt.gz
https://testray.liferay.com/reports/production/logs/test-1-14/1571675549936/test-portal-acceptance-pullrequest(master)/4980/functional-upgrade-tomcat90-postgresql10-jdk8/3/0/liferay-log.txt.gz

**Comment by shuyangzhou** [comment]
@stsquared99 please look into these.

**Comment by stsquared99** [comment]
Will resend

**Comment by stsquared99** [comment]
Resent here: https://github.com/shuyangzhou/liferay-portal/pull/8416

**Pull request closed without merging**
