### PR TITLE
[Bug Fix]LPS-124002

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@GinsonRen Please run a diff.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian I will run this tonight and update the results tomorrow morning.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by GinsonRen** [comment]
@tinatian  Here is the result:
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 37,717 | 297 | 83.1 | -
PR-9643 | - | 38200 | 266 | 78.9 | 1.28%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 51,014 | 566 | 174 | -
PR-9643 | - | 50952 | 641 | 205 | -0.12%


MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 16240 | 805 | 698 | -
PR-9643 | - | 16041 | 752 | 706 | -1.23%


Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 13,715 | 194 | 268 | -
PR-9643 | - | 14048 | 108 | 190 | 2.43%


DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 24,824 | 244 | 306 | -
PR-9643 | - | 24705 | 240 | 303 | -0.48%


Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 14243 | 235 | 444 | -
PR-9643 | - | 14029 | 230 | 525 | -1.50%


AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 19,666 | 389 | 195 | -
PR-9643 | - | 19490 | 420 | 207 | -0.89%

**Pull request closed without merging**
