### PR TITLE
Lps 143202

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@shuyangzhou While there are no regressions found here, note that the Search Experiences integration tests failing to run
```
     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:search-experiences:search-experiences-rest-test:testIntegration'.
     [exec] > Please create marker file /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-api/.lfrbuild-portal
```
https://testray.liferay.com/reports/production/logs/2021-12/test-1-26/test-portal-acceptance-pullrequest(master)/1028/modules-integration-mysql57-jdk8/0/18/jenkins-console.txt.gz

FYI @joshchong

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111076

**Pull request closed without merging**
