### PR TITLE
[Bug Fix] LPS-80663

### PR DESCRIPTION
**Pull request by tinatian**
cc @dsanz
I think this change should also fix the dead lock you are talking about. Please feel free to let me know if you have any question about it.

Thanks.
Tina.

### CODE REVIEW

**Comment by dsanz** [comment]
Hi @tinatian, @yuhai,

I think this can work regarding the wait/notify mechanism. But there is an important thing to consider: before this fix, the getNotificationEvents() was synchronized, which means that the **entire method** was locked by a thread.

As a result, not only the wait/notify worked, also the rest of the logic was syncrhonized. That is why I said that my previous fix kept the locking semantics of existing code: I decoupled the wait/notify (which now are implemented by coundown latch) from the getNotificationEvents() locking requirements.

Current fix breaks the semantics of the synchronization for getNotificationEvents(), as now several threads can enter getNotificationEvents() at the same time. I don't know the effects of this when several polledr/receive requests come to the server. If we can guarantee absence of problems derived from this, then I'm fine with the fix. I'm not sure if we're testing this specific thing.

Now that the object-level lock is not used, a possibility to keep semantics would be to make getNotificationEvents() synchronized again.

Does this make sense to you @tinatian ?
Best

**Comment by tinatian** [comment]
@dsanz 
Yes, you are right, the fix changed the logic, but I think the change should be safe.

I checked the history change log of this, this SynchronousPollerChannelListener is here to make sure we get a notification when there is notification event available. The old way is to have a "_complete" class attribute to do this, and to make sure "_complete" is safe to read/write by multi thread, all methods touched it have to be protected by "synchronized". I think that's why we have getNotificationEvents() be protected by "synchronized". 

Also, this SynchronousPollerChannelListener would be generated by each thread, and register to channel as a listener. getNotificationEvents() will only be invoked by current thread, and the listener related methods will be invoked by other threads. The whole point here is to protect this, and my change can do it. I did not see any reason we have to keep an object-level lock. 

Any question, please feel free to let me know.

Thanks.
Tina.

**Comment by dsanz** [comment]
Hi @tinatian ,it()

I agree, my guess was that one too, so the synchonization is there just to allow wait()/notify() mechanism to work, and there is no need to protect the entire method. According to @yuhai tests, this also avoided the deadlock so I'd say we can move forward with this.

Thanks for tour time.
Daniel

**Comment by dsanz** [comment]
Hi @tinatian ,

there is an additional thing which SynchronousChannelPortletListener must consider, which was not there before. Now, because of how countdownlatch works, getNotificationEvents() can only be called once per each SynchronousChannelPortletListener object. 

This turns out to be the case (only poller servlet calls it and it creates a new object each time), but, if someone changed it and reused the object amongst calls (for instance by caching them), then the solution will work only in the first call, unless we use cyclicbarrier to reset the counter after getNotificationEvents().

I'm not sure if this will happen but I believe this shall be known to the developers. Hopefully the code is clear enough.

Best

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58949

**Pull request closed without merging**
