### PR TITLE
LPS-70284 PortletConfigImpl.getResourceBundle

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest Rebased the changes.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/46998

**Pull request closed without merging**
