### PR TITLE
[Bug Fix]LPS-91534

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

Please wait for ci result.

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72113

**Pull request closed without merging**
