### PR TITLE
LPS-80892 Portlet 3.0: Implement HeaderRequest and HeaderResponse

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou I squashed all your code review commits into one, and added two more commits that address the two concerns you mentioned. Thanks for all the help!

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou There were no build failures or SF failures. Since this PR contains only 4 new Java source files the other failures must be unrelated. Please review when you can. Thanks!

**Comment by shuyangzhou** [comment]
@ngriffin7a is this needed to be Boolean rather than boolean? 	https://github.com/ngriffin7a/liferay-portal/blob/7f4078a649c969901d9f163c80c43eaaf3d99ca6/portal-impl/src/com/liferay/portlet/HeaderResponseImpl.java#L122 Do you really care null/true/false values? I don't see usages of it, so I need to ask to be sure.

**Comment by ngriffin7a** [comment]
@shuyangzhou I simply copied the entire method from RenderResponse.java

**Comment by shuyangzhou** [comment]
@ngriffin7a that is not a good source to copy, just some bad leftover code, I will take care both of them.

**Comment by ngriffin7a** [comment]
@shuyangzhou OK thanks for taking care of that.

**Comment by shuyangzhou** [comment]
@ngriffin7a actually do we expect an usage of that for HeaderResponse? Isn't that a render only thing?

**Comment by ngriffin7a** [comment]
@shuyangzhou Checking, standby...

**Comment by ngriffin7a** [comment]
@shuyangzhou In the next PR that I send (after this one is merged), I have refactored render_portlet.jsp to the following:
```
boolean renderHeaders = (Boolean)request.getAttribute(WebKeys.RENDER_HEADERS);

if (renderHeaders) {
	headerRequestImpl = HeaderRequestFactory.create(request, portlet, invokerPortlet, portletCtx, windowState, portletMode, portletPreferences, plid);
	portletRequest = headerRequestImpl;
	headerResponseImpl = HeaderResponseFactory.create(headerRequestImpl, bufferCacheServletResponse);
	mimeResponse = headerResponseImpl;
	headerRequestImpl.defineObjects(portletConfig, headerResponseImpl);
	responseContentType = headerRequestImpl.getResponseContentType();

	if (stateMin) {
		headerResponseImpl.setUseDefaultTemplate(true);
	}
}
else {
	renderRequestImpl = RenderRequestFactory.create(request, portlet, invokerPortlet, portletCtx, windowState, portletMode, portletPreferences, plid);
	portletRequest = renderRequestImpl;
	renderResponseImpl = RenderResponseFactory.create(renderRequestImpl, bufferCacheServletResponse);
	mimeResponse = renderResponseImpl;
	renderRequestImpl.defineObjects(portletConfig, renderResponseImpl);
	responseContentType = renderRequestImpl.getResponseContentType();

	if (stateMin) {
		renderResponseImpl.setUseDefaultTemplate(true);
	}
}
```
Basically, the `HEADER_PHASE` has to be able to do *everything* that the `RENDER_PHASE` can do. A good justification/example of this is the JSF portlet bridge, which runs the JSF lifecycle in the `HEADER_PHASE` and saves all the output to a HeaderRequest attribute that gets retrieved in the `RENDER_PHASE` so that it can be written to `RenderResponse.getWriter()`.

For that reason, I simply copied the renderRequestImpl code in render_portlet.jsp and did the same thing for headerResponseImpl.

If you think that was unnecessary then that's fine. I was just trying to stay consistent with the code.

**Comment by ngriffin7a** [comment]
@shuyangzhou Yes, we will have a non-null usage of that method in a subsequent PR.

**Comment by shuyangzhou** [comment]
@ngriffin7a I am not really familiar with the header pharse. But if it is really doing what the name says, it is only responsing with headers, no bodies. Then there would be no use of template, as they is meant for portlet content renderring which will end up as bodies. But without really seeing the whole thing, it is not easy for me to understand this. If you think this might be needed, I can keep it but converting Boolean to boolean in both cases. Let me know whether you want to keep it for header phase.

**Comment by shuyangzhou** [comment]
@ngriffin7a I will leave the _addDependencyToHead() null version as it is for now. Once you confirm what do you want for the getUseDefaultTemplate(), I will finish up the review for this pull, then send it out.

**Comment by ngriffin7a** [comment]
@shuyangzhou Go ahead and take it out. If it turns out to be necessary in the future I can put it back in.

**Comment by ngriffin7a** [comment]
@shuyangzhou When I wrote "take it out" the "it" referred to `getUseDefaultTemplate()` not `_addDependencyToHead()`

**Comment by shuyangzhou** [comment]
@ngriffin7a yes, I won't remove the null version part for _addDependencyToHead(). I will remove getUseDefaultTemplate(), as I don't see how it could be used. You always add it back later, if it turns out otherwise.
One last thing, do you expect an usage for https://github.com/ngriffin7a/liferay-portal/blob/7f4078a649c969901d9f163c80c43eaaf3d99ca6/portal-impl/src/com/liferay/portlet/HeaderResponseImpl.java#L118 ? I know the setTitle is a must do. But do we expect a getTitle() usage for HeaderResponse, as what we have for RenderResponse?

**Comment by ngriffin7a** [comment]
@shuyangzhou I just checked the code in my next PR and I don't see any usage of calling `getTitle` so you can remove `getTitle` for now. I can add it back if I need it.

**Comment by shuyangzhou** [comment]
Sure, I will go with that, thanks for the confirming @ngriffin7a !

**Comment by ngriffin7a** [comment]
@shuyangzhou Thanks so much for the thorough code review! :)

**Comment by shuyangzhou** [comment]
@ngriffin7a no problem. Sorry for the delay, we have been distracted by CI and other stuff a lot these days.

**Pull request closed without merging**
