### PR TITLE
LPS-63730 Extract synch logic to a component

### PR DESCRIPTION
**Pull request by csierra**
/cc @brianchandotcom (was copied in the former pull)

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@csierra I don't like the jdk8 simulating solution. We are technically on jdk8 already, just not to the point to allow people use jdk8 api yet.

Adding the Consumer and the ValueSynchronizer will just end up removing them very soon, however with semantic versioning, we can never remove them, but only deprecating them, so the end result will be adding 2 deprecated classes which is obviously not a good thing to do.

And as you can see, the new Consumer interface you added went into kernel.util package, which has been provider locked down by many modules. Bumping up even for a minor version will cause a lot of cascaded updates. And as a matter of fact, we are trying to move as many things as possible out of kernel.util package, we should not add new stuff into that dumping place.

I force pushed on https://github.com/csierra/liferay-portal/pull/221 that should solve the race condition. Please check again.

We need to keep this an ad-hoc solution for PortletImpl, rather than promote it into a general solution. By the time we truely move on to JDK8, things will get a lot easier and cleaner, without raising any dependency issues.

**Comment by csierra** [comment]
I knew I knew we would not use this JDK 8 simulation yet... I just wanted to show you my idea to this. 

Since we can easily abstract this out to a new component why don't just we leave it as it and not merge PortalImpl maps now? Once we have the support for Java 8 it will become a straightforward thing to do...

**Comment by shuyangzhou** [comment]
Yes, we can do that, but with same drawback, adding a module knowing that will be removed in a couple weeks, only easing the semantic versioning.

Have you checked the update on https://github.com/csierra/liferay-portal/pull/221? It added a double check to prevent the concurrent remove race condition. If that works, I would stay with that solution. All changes stay within exist files, by the time we move to jdk8, all we will need to do is method logic refactoring. No module or interface removal is needed.

**Comment by csierra** [comment]
yes... I was checking it now.

**Pull request closed without merging**
