### PR TITLE
Html impl.escape

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn please run a diff on DL for me, although this should affect other test cases too.

**Comment by slnn** [comment]
Hi @shuyangzhou,

Here are test results on Main env:

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL FIle
-- | -- | -- | -- | --
BaseLine | db1f457 | 24038 | 381 | 453
PR-7836 | - | 23873 | 509 | 548

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | db1f457 | 43410 | 297 | 89.8
PR-7836 | - | 43804 | 297 | 90.4


Lily

**Comment by vicnate5** [comment]
@shuyangzhou Functional test failures look unrelated.

One of the servers had a broken UI, haven't seen this before, but it it was only 1 server.
before0

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73868

**Pull request closed without merging**
