### PR TITLE
[API Change]LPS-93847 and LPS-92343 Template engine API

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull depends on Matt's pull : https://github.com/shuyangzhou/liferay-portal/pull/7593.

Please wait for CI result.

You can review and commit the changes for each ticket separately, I put it together cause they are all about template engine api refactoring.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
FYI @dantewang @yuhai

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
retesting due to bug at head that is now resolved

**Comment by koor4356** [comment]
ci:bundle

**Comment by tinatian** [comment]
Resend at https://github.com/shuyangzhou/liferay-portal/pull/7602

**Pull request closed without merging**
