### PR TITLE
LPS-75848 ResourceURLs with cacheability=FULL incorrectly contain the current render parameters, portlet mode, and window state of the portlet

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jpince: When you get a chance, I'd appreciate it if you could verify that these failures are unrelated to this PR. Thanks.

**Comment by jpince** [comment]
@ngriffin7a looks good

**Comment by ngriffin7a** [comment]
Thanks @jpince -- @shuyangzhou looks like this one is ready for review as well.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53225

**Pull request closed without merging**
