### PR TITLE
[Bug Fix]LPS-119524

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou 
This is to fix the "cache-enabled" attribute not working for 7.2.x and previous versions, it was a long time existed issue which caused by LPS-89637 9f2bd5c378d2763fc99732f1ca7c19bda7f135e7.

FYI @ericyanLr 

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
