### PR TITLE
Startup optimization 352 scr log service enabled logger

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me watch over the test results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou No regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144724

**Pull request closed without merging**
