### PR TITLE
LPS-83992 Implement methods in BeanPortletExtension and add a minimal number of supporting classes/interfaces

### PR DESCRIPTION
**Pull request by ngriffin7a**
@shuyangzhou I tried to keep this PR as small as possible -- it adds about 25 classes, but they have minimal content and there are still 30 more classes to come in subsequent PRs.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou The commit in this PR is limited to the bean-portlet-cdi-extension. It passes SF and it builds. Therefore I think all other failures are unrelated.

Please review when you get an opportunity. Thanks, Neil

**Comment by ngriffin7a** [comment]
@shuyangzhou Do you have time in your schedule this week to review this PR? I have subsequent commits to send that are roadblocked by this PR. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62284

**Pull request closed without merging**
