### PR TITLE
[TS] LPS-97164 portal-impl: Avoid unwanted side effects from request headers

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-97164

Hi @shuyangzhou ,

The goal of this fix is to make sure that the **If-Modified-Since** date header does not prevent content from being retrieved, when using **AggregateFilter**. Currently, the header can cause the request to return a 304 response, which results in blank content.

We noticed that this is already handled by [RequestDispatcherUtil.java#L48-L52](https://github.com/liferay/liferay-portal/blob/7.2.0-ga1/portal-kernel/src/com/liferay/portal/kernel/servlet/RequestDispatcherUtil.java#L48-L52), and so we decided to use this util class.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
**Note:** Force pushed to remove unnecessary logic with bufferCacheServletResponse, which is already being managed by the RequestDispatcherUtil.

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:test

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75429

**Pull request closed without merging**
