### PR TITLE
Lps 72002

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/21428129ff...a3d29cf7b5

**Comment by mtambara** [comment]
ci:stop

**Comment by jpince** [comment]
@kmaria fix to resolve the exportimport failure. I assume it was forwarded to BChan, not sure if it was merged

**Comment by mtambara** [comment]
@jpince @kmaria There was a problem with this fix, I sent a new one here: https://github.com/shuyangzhou/liferay-portal/pull/4265

**Pull request closed without merging**
