### PR TITLE
LPS-x transactional cache 

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull passed the test @mtambara  wrote.

I have not fixed the unit tests, so you will see the unit test failed.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @slnn,
Could you please keep an eye on the ci test result of this pull, if there are not real failures except the unit tests, run a performance diff with this pull.

cc @dantewang

Thanks.
Tina.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi Tina,

For the CI failure, except failure of sematic versioning and the failure of unit test, other failure should not be caused by this pull.
1> The source formatter failed by this file /modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/edit_layout_page_template_entry.jsp.
2> The plugins compile failure because File "/WEB-INF/tld/struts-tiles.tld" not found in sample-struts-portlet.
3> Other functional test failure also appeared on other PR.

Here are test results:
Login:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Log Out
-- | -- | -- | -- | --
BaseLine | e304213 | 47049 | 283 | 84.8
PR-6793 | - | 47948 | 281 | 85.2

WebContent:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page
-- | -- | -- | -- | --
BaseLine | e304213 | 61630 | 617 | 219
PR-6793 | - | 62970 | 562 | 196

MB:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add MB Thread
-- | -- | -- | -- | --
BaseLine | e304213 | 15480 | 35.4 | 71.8
PR-6793 | - | 15725 | 26.1 | 62.6

Blog:


Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | e304213 | 12467 | 85 | 190
PR-6793 | - | 12355 | 148 | 250

DL:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add DL File
-- | -- | -- | -- | --
BaseLine | e304213 | 26507 | 336 | 404
PR-6793 | - | 26287 | 253 | 361

AssetPublisher:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page With Filter
-- | -- | -- | -- | --
BaseLine | e304213 | 24858 | 470 | 205
PR-6793 | - | 25194 | 479 | 210

Wiki:

Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | e304213 | 16515 | 373 | 576
PR-6793 | - | 16910 | 386 | 594

**Pull request closed without merging**
