### PR TITLE
LPS-84114 The value of "javax.portlet.version" is shared with all OSGi bundle portlet applications

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou "This pull contains no unique failures."

Please review when you get an opportunity. Thanks, Neil

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61900

**Comment by shuyangzhou** [comment]
Sorry, see https://github.com/brianchandotcom/liferay-portal/pull/61906

**Pull request closed without merging**
