### PR TITLE
Lps 86406 7

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@lanceji92674957 run a startup performance check please.
@slnn please do a runtime performance regression check as well. Let's do login and one other complex test case by your choice.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 3c6a98e | 46437 | 268 | 80.4
https://github.com/shuyangzhou/liferay-portal/pull/7193 | - | 46589 | 285 | 86.1

Wiki

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add WIki Page
-- | -- | -- | -- | --
BaseLine | 3c6a98e | 16338 | 411 | 609
https://github.com/shuyangzhou/liferay-portal/pull/7193 | - | 15894 | 386 | 584


Lily

**Comment by lanceji92674957** [comment]
Startup performance test:
Baseline: 42.13, LPS-86406: 42.65

**Comment by shuyangzhou** [comment]
Thanks guys! I will take this hit for now, we can get it back some where else later.

**Pull request closed without merging**
