### PR TITLE
LPS-X For tags who do not set attributes at all, there is no need to …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…clean them.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou Test failures not related. Note that there was higher than normal occurrences of https://issues.liferay.com/browse/LPS-86378 (occurred 5 times)

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

@mtambara please look into https://issues.liferay.com/browse/LPS-86378

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73815

**Pull request closed without merging**
