### PR TITLE
[TECHNICAL SUPPORT] LPS-97410 Add jai-imageio-core and jai-imageio-jpeg2000 libraries

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:stop:sf

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74992

**Pull request closed without merging**
