### PR TITLE
LPS-78194 Remove support for WSRP

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:sf

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@timpak Please let me know if any of these failures are caused my my commits. Thanks.

**Comment by timpak** [comment]
@ngriffin7a there's a build failure at head that's causing this

**Comment by ngriffin7a** [comment]
@timpak The failure was caused  by a broken class named UpgradeLayoutTest.java being added to master moments after I sent the PR. See: https://github.com/liferay/liferay-portal/commit/76431da7316b8510dfba44493da86d0eed5b2574

I rebased locally and tests are compiling now. I will retest in CI.

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou "This pull contains no unique failures" reported by CI. Please review, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58139

**Pull request closed without merging**
