### PR TITLE
LPS-62458 Improve performance and exception messages of StringParserF…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…ragment constructor

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Hmmm, I think there's an off by one error.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
Fixed it.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/35382

**Pull request closed without merging**
