### PR TITLE
LPS-107255 Fix FR storage.size.suffix translations

### PR DESCRIPTION
**Pull request by rolandpakai**
Hey @shuyangzhou,

We need to localize the units (bytes, kbs, etc.) because in some languages like french they have other names for the same unit.

Could you please check my changes and push it forward?

Thanks.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@rolandpakai this solution is not right. TextFormatter is heavily used outside portal, by tools. It needs to stay stateless, it can not use LanguageUtil, because LanguageUtil has a state of LanguageImpl which is injected via Spring. Tools don't have the luxury of spring usage.

Since there is no usage apply in this pull, I can not tell for sure where exactly you need this for. But most like you should be able to make TextFormatter format the number in the way you want without appending the suffix, then from the caller you can append the properly localized suffix yourself.

Please resend with the solution above if it is appropriate, or show me exactly where you need to apply this for, then I can understand this better to provide you a different solution.

**Comment by rolandpakai** [comment]
Hi @shuyangzhou 

i updated the LPS-107255 description. Could you please check it?

Thanks, Roland

**Comment by shuyangzhou** [comment]
@rolandpakai ok, just do what I suggested above, make a new version of formatStorageSize which does not append the suffix, just formatting the number. Then do the suffix localization from the caller, don't keep this logic inside TextFormatter, then you will be fine.

**Comment by rolandpakai** [comment]
Hi @shuyangzhou 
i resent here: https://github.com/shuyangzhou/liferay-portal/pull/8810

But i implemented an other soulutin in the LanguageUtil.

Please review it.

Thanks, Roland

**Pull request closed without merging**
