### PR TITLE
[Resource Action]LPS-122988

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a startup diff.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Result please check [here](https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit#gid=0&range=C3114:C3119).

**Comment by tinatian** [comment]
@shuyangzhou Result @GinsonRen provided shows no regression on startup.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
