### PR TITLE
LPS-157660 Avoid unnecessary DLFileEntryModelResourcePermissionRegist…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…rar reactivating during startup

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Regressions here

1. com.liferay.sharing.document.library.internal.test.DLFileEntrySharingTest integration test hangs during execution. The following is repeatedly printed in [Liferay logs](https://testray.liferay.com/reports/production/logs/2022-07/test-1-27/test-portal-acceptance-pullrequest(master)/3912/modules-integration-mysql57-jdk8/3/12/jenkins-console.txt.gz?authuser=0):
`Waiting for service com.liferay.portal.security.permission.contributor.PermissionSQLContributor model.class.name=com.liferay.document.library.kernel.model.DLFileEntry for field com.liferay.sharing.document.library.internal.test.DLFileEntrySharingTest._permissionSQLContributor`
2. com.liferay.sharing.search.internal.test.SharingEntrySearchDLTest integration test fails
`com.liferay.sharing.search.internal.test.SharingEntrySearchDLTest > testUserCanSearchSharedPrivateDocument FAILED
    java.lang.AssertionError: {docs={}, length=0, query=null] expected:<1> but was:<0>` [testray](https://testray.liferay.com/home/-/testray/case_results/1897648938?tab=history)
3. Functional failure in DMSharing tests. 
Steps to Reproduce
     1. Set portal-ext properties to make new user testing easier
     ```
     company.security.strangers.verify=false
     login.secure.forgot.password=false
     passwords.default.policy.change.required=false
     ```
     2. Create a new user and set the Password
     3. Still as the admin user, Go to Liferay DXP > Documents and Media
     4. Go to Add a new Document
     5. Upload a new Document
     6. Set Permissions to Viewable by "Owner" only
     7. Publish the Document
     8. Go to the Document options > Share
     9. Share the document with the newly created user in step 2
     10. Login to the new user
     11. Go to User avatar menu > Shared Content
     12. Click on the Shared document title
     
     Expected Result:
     Document preview is available
     
     Actual Result
     User cannot see document shared with them

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results again, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Document sharing broken in a new way now

Steps to Reproduce:
1. Go to Documents and Media
1. Go to ellipse menu for the default tree.png image
1. Select "Share"

Share portlet does not render
```
ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
java.lang.NullPointerException: null
        at com.liferay.osgi.service.tracker.collections.internal.ServiceTrackerUtil.createServiceTracker(ServiceTrackerUtil.java:40) ~[com.liferay.osgi.service.tracker.collections.jar:?]
        at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl.<init>(ServiceTrackerMapImpl.java:56) ~[com.liferay.osgi.service.tracker.collections.jar:?]
        at com.liferay.osgi.service.tracker.collections.map.ServiceTrackerMapFactory.openSingleValueMap(ServiceTrackerMapFactory.java:152) ~[com.liferay.osgi.service.tracker.collections.jar:?]
        at com.liferay.sharing.internal.security.permission.SharingPermissionImpl._getServiceTrackerMap(SharingPermissionImpl.java:246) ~[?:?]
        at com.liferay.sharing.internal.security.permission.SharingPermissionImpl.contains(SharingPermissionImpl.java:124) ~[?:?]
        at com.liferay.sharing.web.internal.helper.SharingHelper.getSharingEntryPermissionDisplays(SharingHelper.java:74) ~[?:?]
        at com.liferay.sharing.web.internal.portlet.action.ViewMVCRenderCommand.render(ViewMVCRenderCommand.java:75) ~[?:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:282) ~[portal-kernel.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:113) ~[portal-kernel.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
        at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:568) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:658) ~[portal-impl.jar:?]
 ```
 
 Also reproducible in Blogs, add a blog and try to Share.
 
Failing Integration test [com.liferay.sharing.service.test.SharingEntryServiceTest](https://testray.liferay.com/home/-/testray/case_results/1900091507)

**Comment by shuyangzhou** [comment]
@vicnate5 sorry, that was a stupid mistake, I must lose a bit of code during rebasing. Pushed and re-testing

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 any real failures in the new runs?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120193

**Pull request closed without merging**
