### PR TITLE
[Session Replicate]LPS-135570

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@tinatian ```java.lang.AssertionError: com.liferay.portal.web.internal.session.replication.SessionReplicationHttpSessionWrapper is not fully covered``` is real, please fix and resend.

**Pull request closed without merging**
