### PR TITLE
COMMERCE-1067 - batch-engine-service - Update build.gradle

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@ivicac can you describe what additional cleanup you are trying to add?

**Comment by ivicac** [comment]
@shuyangzhou in xls file value is trimmed like in csv,  in xls and csv files, blank("") value is set to null and in csv files I added support for having commas inside string values, something like .....,"finally, you can put comma character",.....

**Comment by shuyangzhou** [comment]
@ivicac I think this is a questionable behavior change. If we must support comma in value, then the value must be quoted, then we will need to support quote in value with escape too. Not even mention single quote and double quote like issues.

Do we have to support this? If so, can it just be an unicode escaped comma?

Basically we need to draw a clear line to separate what are supported and what are not. Otherwise overtime, the parsing logic could get really complex.

**Comment by ivicac** [comment]
@shuyangzhou ok, to make things simpler, for now, I will remove that specific support. Customers can use unicode escaped comma, or as I will add anyway support for different delimiters besides comma, they can go that route, too. I am gonna force push this branch with changes.

Thx

**Comment by ivicac** [comment]
@shuyangzhou force pushed this branch

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@ivicac can the delimiter be more than 1 char? Or it is always expected to be a single char, just different system may choose different char?

**Comment by ivicac** [comment]
@shuyangzhou usually one char, but nothing prevents user to use more chars. You are asking because of StringUtil.split method?

**Comment by ivicac** [comment]
and it only relates to csv files....

**Comment by shuyangzhou** [comment]
@ivicac I am only trying to see whether it can be changed to a single char split which will be faster than string split. So you want to keep the ability to split by a real multi-chars string?

**Comment by ivicac** [comment]
@shuyangzhou if it is going to be much faster then change it to single char

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79317

**Pull request closed without merging**
