### PR TITLE
[Bug Fix]LPS-79546

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Looks good

**Comment by shuyangzhou** [comment]
See https://issues.liferay.com/browse/LPS-79546

**Pull request closed without merging**
