### PR TITLE
[Registry]LPS-138126 9 27

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:license

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions in the test results

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/107876

**Pull request closed without merging**
