### PR TITLE
LPS-199010 Postpone AnalyticsCloudPortalInstanceLifecycleListener and…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… AddSalesforceConnectorPortalInstanceLifecycleListener to avoid startup time race condition

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found. 

And the error in https://liferay.atlassian.net/browse/LPS-199493 didn't happen here.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142484

**Pull request closed without merging**
