### PR TITLE
Lps 54048 As a developer, I would like to make cluster channel handle its address.

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
I don't see how this is much different from the previous solution.

This is basically just pull out the mutable part into a new class ClusterNodeStatus.

The interesting part is, ClusterNodeStatus is only used by ClusterExecutorImpl and ClusterRequestReceiver (not really an usage, but only using its type to decide which ClusterExecutorImpl method to call). And ClusterNodeStatus's content is just ClusterNode + Addresses.

So why do we have to use an isolated class to contain this info? We can just pass ClusterRequest into ClusterExecutorImpl from ClusterRequestReceiver, and inside ClusterExecutorImpl to inspect into the payload to decide what to do. That way we don't need ClusterNodeStatus, at least not as an isolated standalone class. It is very confusing to have that class, as no one should or could use it.

Please refine the design and resend.

**Comment by tinatian** [comment]
Why we have to use an isolated class? 
The root reason is we need to pass both clusternode and addresses to another node in cluster, while we can send only one object by jgroups API.

Then we have two choices here:
1) Send an object like ObjectValuePair<ClusterNode, Addresses> to combine two things together
2) Create an new class to contain all the info, and is what I am doing.

Basically 1) and 2) is same, I choose 2) because I can put some the logic in a new class, then ClusterExecutorImpl would not be too messy.

Yes,  ClusterNodeStatus is only used by ClusterExecutorImpl and ClusterRequestReceiver, it is the implementation details, and no one else should see it and use it. That what it is supposed to be.

**Comment by shuyangzhou** [comment]
It should just be inner class inside ClusterExecutorImpl, ClusterRequestReceiver (or anyone else) does not need to know about it.

**Comment by tinatian** [comment]
Right, that would be more reasonable. I will send you a new PR.

**Pull request closed without merging**
