### PR TITLE
LPS-53037 Do not use OS specific ServletContext#getRealPath

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Hi @shuyangzhou,

I've found that JSP hooks on Windows are not applied anymore after LPS-52665 is committed to master.

In PortalContextLoaderListener#contextInitialized the _portalLibDir_ is determined by invoking _ServletContext.getRealPath(String s)_ which returns the real file system path, but the file separator is "/" for UNIX, "\" for Windows so in _WebDirDetector#getRootDir_ the _libDir_ will be like "C:\tomcat-master\apache-tomcat-7.0.42\webapps\ROOT\WEB-INF\lib/" and it not ends with "/WEB-INF/lib/" which causes that the portal web directory will be set to a wrong directory.
- Could you please review my fix?

Thank you,
Zoltán

### CODE REVIEW

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/23492, it should fix your issue.

**Comment by ZoltanTakacs** [comment]
Yes, it would solve this issue, nonetheless the "Portal lib directory" would still contain inconsistent file separators. Doesn't it? :) the last char would be forward slash if I'm correct.

**Comment by shuyangzhou** [comment]
Well, it is, but it won't bother anyone, windows will handle the "mixed" style correctly. After all we can not prevent people from calling getRealPath(), and it will already create a "mixed" style file separators on windows. Even we get this one, there are still a lot of others, it is kind of pointless to make it consistent here.

**Comment by ZoltanTakacs** [comment]
I see, thank you for the explanation.

**Pull request closed without merging**
