### PR TITLE
[TECHNICAL SUPPORT] LPS-153646 Pages with accented names exclude their names from their canonical URL

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @shuyangzhou ,

[LPS-153646](https://issues.liferay.com/browse/LPS-153646)

we made sure to pass groupFriendlyUrl as lowercase in https://github.com/brianchandotcom/liferay-portal/pull/104513/commits/1acbb68e1b3a49c5011abf8351a0106ea938d232 . I made sure we are checking against a lower case layoutFriendlyUrl.

Please review my changes,
Thanks

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou This looks good, No regressions found here or on another testing I ran at https://github.com/vicnate5/liferay-portal/pull/2053

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
