### PR TITLE
[TS] LPS-120596

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-120596

Hi @shuyangzhou,

**Notes from @holatuwol:**

> Not updating the compileInclude dependencies, because they aren't the ones being invoked by Apache Tika.

**Additional Notes**
Liferay currently has a dependency on Tika 1.24.1

Looking at tika-parsers:1.24.1, it has a dependency on commons-codec:1.13

- Reference: https://github.com/apache/tika/blob/1.24.1/tika-parsers/pom.xml#L43

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
