### PR TITLE
LPS-X Defer opensaml initialization until first usage comes.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by shuyangzhou** [comment]
@zhangyan0701 please help me check the results, thanks!

**Comment by zhangyan0701** [comment]
@shuyangzhou 

NPE error in some saml integration tests.

Examples:
[com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest](https://testray.liferay.com/home/-/testray/case_results/2445812634)
[com.liferay.saml.opensaml.integration.internal.util.SamlUtilTest](https://testray.liferay.com/home/-/testray/case_results/2445812638)
[com.liferay.saml.opensaml.integration.internal.credential.CredentialResolverTest](https://testray.liferay.com/home/-/testray/case_results/2445812596)

Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-33/test-portal-acceptance-pullrequest(master)/4520/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:saml

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

FYI @gaborlovasdotcom

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142684

**Pull request closed without merging**
