### PR TITLE
LPS-66010 Pull up fetchByPrimaryKey from generated PersistenceImpls to BasePersistenceImpl

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
I don't know what this is. Please rebase and resend, hope it will go away.

**Comment by Preston-Crary** [comment]
This is a bug with the CI when it tries to rebase.  Not sure what caused this to happen, I've seem a few of these today on pulls waiting on Brian.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/3042

**Pull request closed without merging**
