### PR TITLE
Bean Portlet API refactor, Spring IOC, MVC for CDI and Spring (fixed GAV for the JAX-RS API)

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@shuyangzhou This is the same PR as https://github.com/shuyangzhou/liferay-portal/pull/7623 but with a fixed GAV for the JAX-RS API. Running CI tests just in case...

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by ngriffin7a** [comment]
@shuyangzhou I think that the failures reported by CI are unrelated. All of the commits in this pull request are limited to the modules/apps/bean-portlet directory and the Portlet 3.0 TCK tests are passing.

Please review at your earliest convenience. Thanks, Neil

**Comment by shuyangzhou** [comment]
@ngriffin7a please rebase and resend, and can you show me some usages, so that I can debug it?

**Comment by ngriffin7a** [comment]
@shuyangzhou Yes I'll rebase first thing tomorrow morning. I have full-featured demos that exercise every feature and maven archetypes for starter projects. I'll provide all that to you tomorrow.

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7683

**Pull request closed without merging**
