### PR TITLE
[Log4j]LPS-127067 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please verify if those unique failures real?

Thanks.
Tina

**Comment by vicnate5** [comment]
@kyle-miho please scan this morning

**Comment by shuyangzhou** [comment]
@tinatian are we going to use the new com.liferay.portal.kernel.log.Level somewhere else other than tests and server-admin-web? I don't want to add an new enum unless it is really going to be used for production. Both current usages can be pushed down to their own scopes.

**Comment by kyle-miho** [comment]
@shuyangzhou @tinatian pull should be good, these failures are happening in other pulls/upstream as well

**Comment by shuyangzhou** [comment]
See my skype message. Please push down the "Level" to lower scopes.

**Pull request closed without merging**
