### PR TITLE
LPS-167678 Escape portal hbm cache files' name to make it portable wh…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…en changing liferay_home

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125824

**Pull request closed without merging**
