### PR TITLE
Lps 148703

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@shuyangzhou Caught here
https://testray.liferay.com/reports/production/logs/2022-03/test-1-35/test-portal-acceptance-pullrequest(master)/951/functional-upgrade-tomcat90-postgresql134-jdk8/0/5/jenkins-console.txt.gz?authuser=0

**Comment by shuyangzhou** [comment]
That's a good catch! See fix at https://github.com/shuyangzhou/liferay-portal/pull/10584 , running a few time to make sure it is fixed. Thanks @vicnate5 !

**Pull request closed without merging**
