### PR TITLE
LPS-85174 Improve performance of portlet default permission initialization

### PR DESCRIPTION
**Pull request by Preston-Crary**
From my measurements this should save around 1/4 of a second during startup.  @tomwang2011 is going to comment on this pull once he gets a chance to run it against the baseline.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by tomwang2011** [comment]
This pull shows about 0.6 seconds of speed up compare to baseline, result is the average over 4 runs, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62954

**Pull request closed without merging**
