### PR TITLE
Lps 130600

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the result, also there was a full run at https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8022/jenkins-report.html . I don't think this could break anything, since we are not using hibernate annotation at all. But since the results are there, better to be safe. Thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Looks good, I checked the results here and also the full run at https://github.com/shuyangzhou/liferay-portal/pull/9939#issuecomment-819403486

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100783

**Pull request closed without merging**
