### PR TITLE
Lps 200501

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me monitor this pull and manually test https://liferay.atlassian.net/browse/LPS-200501 , thanks!

**Comment by vicnate5** [comment]
@susanchen3 can you trigger a suite to run the test you added for this?

**Comment by susanchen3** [comment]
@vicnate5 the test passed [LocalFile.OSGIConfiguration#CanCreatePartitionedVirtualInstanceViaConfig](https://testray.liferay.com/home/-/testray/case_results/2451521249)

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

Automation for [LPS-200501](https://liferay.atlassian.net/browse/LPS-200501) issue passed https://testray.liferay.com/home/-/testray/case_results/2451521249 @susanchen3

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143159

**Pull request closed without merging**
