### PR TITLE
LPS-171006 Fix OOM during Fragment Module Activation

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-171006](https://issues.liferay.com/browse/LPS-171006)
See just my changes: https://github.com/shuyangzhou/liferay-portal/compare/6a7ca947dab8bf259e70e7852959d1f45a54a675...mbowerman:LPS-171006

I'm not too sure if this was the type of test you wanted. It seems that the activation gets called when running the line:
```
serviceRegistration = _getServiceRegistration(testFragmentCollectionContributor);
```

I tried testing with the following parameters:
```
int fragmentEntryLinkSize = 3000;
int fragmentEntryLinksCount = 100000;

-Xms2560m -Xmx2560m -XX:MaxNewSize=1536m -XX:MaxMetaspaceSize=768m -XX:MetaspaceSize=768m -XX:NewSize=1536m -XX:SurvivorRatio=7 
```

With these parameters, I reproduced an OOM; however, the OOM occurred _before_ the activation method was called, while we were still adding the FragmentEntryLinks. It appears that the DataGuardTestRule retains all the added FragmentEntryLinks in memory, leading to the OOM occurring while they are being added. So I don't know if there's a good way to test whether the OOM will occur during the activation.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mbowerman you need to disable DataGuard in this case. ```@DataGuard(scope = DataGuard.Scope.NONE)```. And this better goes to a dedicate test class.

Also you have to re-activate the component before getting the service, then call any get method from FragmentCollectionContributorRegistryImpl to make sure the service tracker map is truly opening.

Please fix the behavior and resend.

**Comment by mbowerman** [comment]
Hi @shuyangzhou,

I'm very confused about how to re-activate the component properly. I tried including lines like these before registering the service:
```
		Class<?> clazz = _fragmentCollectionContributorRegistry.getClass();

		ComponentDescriptionDTO componentDescriptionDTO =
			_serviceComponentRuntime.getComponentDescriptionDTO(
				FrameworkUtil.getBundle(clazz), clazz.getName());

		Promise<Void> promise = _serviceComponentRuntime.disableComponent(
			componentDescriptionDTO);

		promise.getValue();

		promise = _serviceComponentRuntime.enableComponent(
			componentDescriptionDTO);

		promise.getValue();
```

However, if I include these lines, then the service does not seem to get registered to the serviceTrackerMap, even though the `FragmentCollectionContributorRegistryImpl.activate` method is called when re-enabling the component. I don't understand why later when we try to register the service, it doesnt get registered to the serviceTrackerMap.

If I don't include the above lines, then the service DOES successfully get registered to the serviceTrackerMap, and the test runs successfully.

**Comment by shuyangzhou** [comment]
The code you show only re-activate the FragmentCollectionContributorRegistryImpl, you need to also "call any get method from FragmentCollectionContributorRegistryImpl" in order to trigger the ServiceTrackerMap to truly open.

ServiceTracker collections are lazy, not until the first call to it, it does not really open its ServiceTracker.

**Comment by mbowerman** [comment]
Hi @shuyangzhou,

Here is the test as I have it now: https://github.com/mbowerman/liferay-portal/blob/effac5f9025cd6b8f037ca4a21f8ae126ed0b0ce/modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/contributor/test/FragmentCollectionContributorRegistryTest.java

I tried adding the following line afterwards to force the ServiceTrackerMap to open, but it didn't seem to work:
```
_fragmentCollectionContributorRegistry.getFragmentEntries();
```

It fails at [this Assert](https://github.com/mbowerman/liferay-portal/blob/effac5f9025cd6b8f037ca4a21f8ae126ed0b0ce/modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/contributor/test/FragmentCollectionContributorRegistryTest.java#L146-L149), indicating that the ServiceTrackerMap did not get populated.

If I remove [these lines](https://github.com/mbowerman/liferay-portal/blob/effac5f9025cd6b8f037ca4a21f8ae126ed0b0ce/modules/apps/fragment/fragment-test/src/testIntegration/java/com/liferay/fragment/contributor/test/FragmentCollectionContributorRegistryTest.java#L115-L131), then the test passes.

**Comment by shuyangzhou** [comment]
Your call to ```_fragmentCollectionContributorRegistry.getFragmentEntries();``` is against the old _fragmentCollectionContributorRegistry, not the new one. You need to re-get that service after re-activate the component.

**Comment by mbowerman** [comment]
Thanks @shuyangzhou, the test is working now, so I re-sent the pull request here: https://github.com/shuyangzhou/liferay-portal/pull/10896

**Pull request closed without merging**
