### PR TITLE
Lps 109121

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@slnn is there a reason we don't just move it back to clean?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85839
I am dropping the auto stop for now, so make sure your monitor script does an explicit "gw --stop" before running

**Comment by slnn** [comment]
I do not move it back to clean becaue the Mac Issue, Peter fixed the Mac issue by running more times setup-sdk, if we only run one time setup-sdk and at the same time to fix the Mac issue, compile is a good choice.

**Pull request closed without merging**
