### PR TITLE
COMMERCE-7816 mvcc for commerce-wish-list-service

### PR DESCRIPTION
**Pull request by ctang3**
https://issues.liferay.com/browse/COMMERCE-7816

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1027401_910

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou Failures not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110083

**Pull request closed without merging**
