### PR TITLE
LPS-154708 Update logger settings

### PR DESCRIPTION
**Pull request by shuyangzhou**
ci:test:sf

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@shuyangzhou no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118614

**Pull request closed without merging**
