### PR TITLE
[License]LPS-126664

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
FYI @vicnate5

**Comment by tinatian** [comment]
ci:test:license

**Comment by vicnate5** [comment]
@kyle-miho Could you do manual testing on this today?
https://issues.liferay.com/browse/LRQA-64576

**Comment by shuyangzhou** [comment]
Any updates @kyle-miho ?

**Comment by kyle-miho** [comment]
@shuyangzhou This pr fixes the License problems, should be good to go, passed manual testing

**Comment by shuyangzhou** [comment]
Merged on license repo side, thanks!

**Pull request closed without merging**
