### PR TITLE
LPS-X Merge InitialUpgradeExtender into LiferayServiceExtender to avo…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…id creating InitialUpgradeStep as DM component.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@shuyangzhou There are system check failures at startup
```
[beanshell] 2022-12-10 01:06:46.232 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 130, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}
[beanshell] 	Declarative Service {id: 227, name: com.liferay.portal.tools.service.builder.test.change.tracking.spi.reference.CacheMissEntryTableReferenceDefinition, unsatisfied references: 
[beanshell] 		{name: _cacheMissEntryPersistence, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 270, name: com.liferay.portal.tools.service.builder.test.uad, version: 1.0.0}
[beanshell] 	Declarative Service {id: 551, name: com.liferay.portal.tools.service.builder.test.uad.exporter.UADPartialEntryUADExporter, unsatisfied references: 
[beanshell] 		{name: uadPartialEntryLocalService, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 550, name: com.liferay.portal.tools.service.builder.test.uad.display.UADPartialEntryUADDisplay, unsatisfied references: 
[beanshell] 		{name: uadPartialEntryLocalService, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 549, name: com.liferay.portal.tools.service.builder.test.uad.anonymizer.UADPartialEntryUADAnonymizer, unsatisfied references: 
[beanshell] 		{name: uadPartialEntryLocalService, target: null}
[beanshell] 	}
[beanshell] 2022-12-10 01:06:46.232 INFO  [main][SystemCheckOSGiCommands:111] Running "Spring Extender Unavailable Component Checker". You can run this by itself with command "dm na" in gogo shell.
[beanshell] 2022-12-10 01:06:46.234 WARN  [main][SystemCheckOSGiCommands:134] Spring Extender Unavailable Component Checker check result: 
[beanshell] Bundle {id: 130, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
[beanshell] 	Component with ID 1 is unavailable due to missing required dependencies:
[beanshell] 		service dependency [com.liferay.portal.kernel.model.Release (&(release.bundle.symbolic.name=com.liferay.portal.tools.service.builder.test.service)(&(release.schema.version>=1.0.0)(!(release.schema.version>=2.0.0)))(|(!(release.state=*))(release.state=0)))]
[beanshell] Bundle {id: 130, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
[beanshell] 	Component with ID 102 is unavailable due to missing required dependencies:
[beanshell] 		service dependency [com.liferay.portal.kernel.model.Release (&(release.bundle.symbolic.name=com.liferay.portal.tools.service.builder.test.service)(&(release.schema.version>=1.0.0)(!(release.schema.version>=2.0.0)))(|(!(release.state=*))(release.state=0)))]
[beanshell] 		service dependency [com.liferay.portal.kernel.configuration.Configuration (&(origin.bundle.symbolic.name=com.liferay.portal.tools.service.builder.test.service)(name=service))]
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-30/test-portal-acceptance-pullrequest(master)/5711/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@Kvale1733 please help me check the new results, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found in relevant.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127606

**Pull request closed without merging**
