### PR TITLE
Aop fix npe

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@Preston-Crary @mtambara  this pull should cover all, except the SB versioning thing.
Still need to wait to confirm the NPE fix.

**Comment by Preston-Crary** [comment]
@shuyangzhou here's the SB versioning part https://github.com/shuyangzhou/liferay-portal/pull/7084

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
