### PR TITLE
LPS-107917 UserGroupRole

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan this pull, thanks!

**Comment by Preston-Crary** [comment]
Fixed the baseline failure.

**Comment by Preston-Crary** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me scan the pull, thanks

**Comment by vicnate5** [comment]
@Preston-Crary Regressions here:

**Functional**:
1. Navigate to Control Panel > Users > Roles > Site Roles
```
ERROR [http-nio-8080-exec-3][BasePersistenceImpl:440] Caught unexpected exception
     [exec] org.hibernate.QueryException: could not resolve property: primaryKey.userId of: com.liferay.portal.model.impl.UserGroupRoleImpl
     [exec] 	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:81)
     [exec] 	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:75)
     [exec] 	at org.hibernate.persister.entity.AbstractEntityPersister.toType(AbstractEntityPersister.java:1465)
     [exec] 	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getType(CriteriaQueryTranslator.java:547)
     [exec] 	at org.hibernate.criterion.AggregateProjection.getTypes(AggregateProjection.java:64)
     [exec] 	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getProjectedTypes(CriteriaQueryTranslator.java:362)
     [exec] 	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:100)
     [exec] 	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:82)
     [exec] 	at org.hibernate.loader.criteria.CriteriaLoader.<init>(CriteriaLoader.java:92)
     [exec] 	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1697)
     [exec] 	at org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:347)
     [exec] 	at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:140)
     [exec] 	at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:126)
     [exec] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.findWithDynamicQuery(BasePersistenceImpl.java:328)
     [exec] 	at com.liferay.portal.service.base.UserGroupRoleLocalServiceBaseImpl.dynamicQuery(UserGroupRoleLocalServiceBaseImpl.java:146)
```
Full log: https://testray.liferay.com/reports/production/logs/test-1-15/1580855742617/test-portal-acceptance-pullrequest(master)/2121/functional-tomcat90-mysql57-jdk8/76/1/jenkins-console.txt.gz

**Integration:**
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356885/AXIS_VARIABLE=38,label_exp=!master/testReport/junit/com.liferay.roles.service.test/RoleLocalServiceTest/testGetAssigneesTotalOrganizationRole/
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356885/AXIS_VARIABLE=38,label_exp=!master/testReport/junit/com.liferay.roles.service.test/RoleLocalServiceTest/testGetAssigneesTotalSiteRole/

**Comment by vicnate5** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8809

**Pull request closed without merging**
