### PR TITLE
LPS-192508 Move HSQL shutdown to right before destroying datasource. …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…Service deactivation during shutdown might still need to access db, for example, com.liferay.fragment.renderer.react.internal.model.listener.FragmentEntryLinkModelListener.deactivate(). We need to keep the database alive until we don't need datasource anymore.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @Kvale1733

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found. The error didn't appear here.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139495

**Pull request closed without merging**
