### PR TITLE
Startup optimization 303 sxp blueprint feature flag listener

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
@xbrianlee we are expecting this impacts feature flags for LPS-193551 and LPS-129412. I only see a test for LPS-129412 (triggered search test suite). Anything we can do to check LPS-193551?

**Comment by xbrianlee** [comment]
@vicnate5 The functional test using the FF for [LPS-193551](https://liferay.atlassian.net/browse/LPS-193551) is in our backlog. Functionality would have to be verified by manually testing the steps in [LPS-194956](https://liferay.atlassian.net/browse/LPS-194956) (under the heading "With a Custom Web Content Structure").

**Comment by vicnate5** [comment]
@shuyangzhou The feature flag for LPS-129412 breaks here. The Blueprint does not get registered as a Collection Provider until the server restarts.

Steps to Reproduce:
1. Set property `feature.flag.LPS-129412=true`
1. Start server
1. Go to Global Menu > Applications > Blueprints
1. Add new blueprint > Give Title
1. Save
1. Go to default site Home page
1. Edit the page (pencil icon)
1. Add a "Collection Display" fragment
1. In right sidebar click on "Select Collection"
1. Go to Collection Providers tab

Expected: the blueprint you created is present
Actual: the new blueprint is missing

Workaround: restart the server and now the blueprint collection provider is present.

**Comment by catarineaguiar** [comment]
This same failure happens with feature.flag.LPS-193551

> @shuyangzhou The feature flag for LPS-129412 breaks here. The Blueprint does not get registered as a Collection Provider until the server restarts.
> 
> Steps to Reproduce:
> 
> 1. Set property `feature.flag.LPS-129412=true`
> 2. Start server
> 3. Go to Global Menu > Applications > Blueprints
> 4. Add new blueprint > Give Title
> 5. Save
> 6. Go to default site Home page
> 7. Edit the page (pencil icon)
> 8. Add a "Collection Display" fragment
> 9. In right sidebar click on "Select Collection"
> 10. Go to Collection Providers tab
> 
> Expected: the blueprint you created is present Actual: the new blueprint is missing
> 
> Workaround: restart the server and now the blueprint collection provider is present.

**Comment by shuyangzhou** [comment]
@vicnate5 @catarineaguiar I appended a fix commit, it should work now, please retest. No need to rerun CI, it is a simple fix.

**Comment by catarineaguiar** [comment]
both worked now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141973

**Pull request closed without merging**
