### PR TITLE
LPS-108991 LocalCacheKey

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Hi @slnn,

please check this for performance regressions.

Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 44536 | 269 | 79.2 | -
PR | - | 44510 | 275 | 82.8 | -0.05837973774

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 56216 | 572 | 177 | -
PR | - | 56542 | 539 | 161 | 0.5799060766

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 17735 | 66.7 | 104 | -
PR | - | 17809 | 30.5 | 78 | 0.4172540175

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 14864 | 430 | 418 | -
PR | - | 14513 | 504 | 444 | -2.361410118
PR | - | 14866 | 508 | 447 | 0.01345532831

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 26352 | 197 | 266 | -
PR | - | 26486 | 168 | 243 | 0.5085003036

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a387bf2 | 15237 | 252 | 462 | -
PR | - | 15253 | 258 | 472 | 0.1050075474


Regards
Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85115

**Pull request closed without merging**
