### PR TITLE
LPS-110454 - portal-vulcan-impl - Update VulcanBatchEngineImportTaskResourceImpl

### PR DESCRIPTION
**Pull request by ivicac**
Hi Shuyang,
this PR again changes Batch. It adds the ability to define multiple delegates per item class. There are real use cases for it in Commerce.

Best regards

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test

**Comment by vicnate5** [comment]
@kyle-miho can you scan this?

**Comment by kyle-miho** [comment]
starting scan now

**Comment by kyle-miho** [comment]
@ivicac I think theres an SF issue with this pull, functional failures seem unrelated, checking integration results right now

**Comment by kyle-miho** [comment]
Integration tests did not reveal anything unique, pull should be good minus sf issues

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86571

**Pull request closed without merging**
