### PR TITLE
Lps 82333

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
View total diff: https://github.com/shuyangzhou/liferay-portal/compare/cc89e09424...9e23116c35

**Comment by zsoltbalogh** [comment]
@shuyangzhou, it seems that the PR for this issue was not forwarded or something weird happened. I also couldn't check the total diff you have linked above. Just mentioning you as it would be great if this issue would be fixed before the release and I don't want to lose it on a simple administration issue (if that's the case). Thank you!

**Comment by shuyangzhou** [comment]
The pull is resent at https://github.com/shuyangzhou/liferay-portal/pull/6369

**Pull request closed without merging**
