### PR TITLE
[Bug Fix]LPS-140103

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:license

**Comment by vicnate5** [comment]
Testing with CCR change at https://github.com/vicnate5/liferay-portal/pull/1852

**Comment by vicnate5** [comment]
@tinatian This is causing system:check failure on the release bundle. Occurring here and with the other changes in https://github.com/vicnate5/liferay-portal/pull/1852
```
 [parallel] 2021-10-01 00:10:55.772 WARN  [main][SystemCheckOSGiCommands:137] Declarative Service Unsatisfied Component Checker check result: 
 [parallel] Bundle {id: 1366, name: com.liferay.marketplace.service, version: 7.0.7}
 [parallel] 	Declarative Service {id: 3505, name: com.liferay.marketplace.internal.lpkg.deployer.LPKGDeployerRegistrar, unsatisfied references: 
 [parallel] 		{name: Release, target: (&(release.bundle.symbolic.name=com.liferay.marketplace.service)(release.schema.version=2.0.2))}
 [parallel] 	}
 ```

**Comment by vicnate5** [comment]
@tinatian Doesn't require release bundle, can check with `ant all` and `module.framework.properties.initial.system.check.enabled=true`

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
Testing with CCR change at https://github.com/tinatian/liferay-portal/pull/2413

**Comment by shuyangzhou** [comment]
Is this good to go?

**Pull request closed without merging**
