### PR TITLE
Lps 130140

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
Hi @shuyangzhou,

Is this solution ready to be given to our client in a patch?

Regards.

**Comment by shuyangzhou** [comment]
@georgel-pop-lr once it passes CI, yes.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100745

**Pull request closed without merging**
