### PR TITLE
LPS-95208

### PR DESCRIPTION
**Pull request by brianikim**
Hello @shuyangzhou ,

Resending from https://github.com/shuyangzhou/liferay-portal/pull/7739 to include the integration tests requested by @Preston-Crary

Requested comment by @Preston-Crary:

> @brianikim can you add tests for LPS-93973 and LPS-95208 to FriendlyURLServletTest (one for impersonated user and one for this ticket)? These changes are not very clear without debugging and looking through the history of the code, we need test coverage to ensure this continues to work.

- Test for impersonated user is not necessary to be included here because LPS-86545 (https://github.com/liferay/liferay-portal/commit/44dbaef320852a8e93a07d7421bfdb9fa534dc25) already handles testing for that use-case.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @shuyangzhou ,

Please let me know if you have any questions regarding the integration tests and the fix.

Sincerely,
Brian Kim

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianikim/liferay-portal/pull/26

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
