### PR TITLE
Support tomcat

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@zhangyan0701 Can you review the results here? We had some issues with the first runs, CI team tried to save the results that they could save.

**Comment by zhangyan0701** [comment]
No related failures found.

Most of the failures are happening on upstream.

Test batch portal-renamed-tomcat-in-path-jdk8 only failed in this PR, but passed in https://github.com/shuyangzhou/liferay-portal/pull/10012, should be a fluke.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10015

**Pull request closed without merging**
