### PR TITLE
LPS-X Disable log4j2's attempt to run in webapp mode which always fai…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…l for liferay anyway, since we don't bundle log4j-web jar.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135627

**Pull request closed without merging**
