### PR TITLE
LPS-75075 Replacing the proxy object with its delegate on the .equals call

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by tinatian** [comment]
Hi @4lejandrito, 

Please see https://github.com/shuyangzhou/liferay-portal/pull/4967.

I redo the changes you made, please feel free to let me know if you have any question about these changes.


Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/51989

**Pull request closed without merging**
