### PR TITLE
Json web service cleanup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by kenjiheigel** [comment]
DO NOT RUN CI TESTS ON THIS PULL.

In summary, the json api changes in this pull create a huge response line that gets printed out to System.out, which freezes the Jenkins JVM. We're adding a failsafe on the Poshi side to truncate such responses, but it won't be in until tomorrow. Additionally, I debugged the error a little bit, and here's how to reproduce. @shuyangzhou @ vicnate5

1. Download the [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/2485/liferay-portal-bundle-tomcat.tar.gz) linked in the comment [above](https://github.com/shuyangzhou/liferay-portal/pull/10591#issuecomment-1075152198) 
2. Extract the tarball: `tar -xvf liferay-portal-bundle-tomcat.tar.gz`
3. Remove or comment out this section in the portal-ext.properties in that bundle: 
```
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.default.username=root
jdbc.default.password=
```
4. Once portal is up, run (this curl gets run by Poshi for most functional tests): 
```
curl -X GET -u 'test@liferay.com:test' http://localhost:8080/api/jsonws/company/get-company-by-virtual-host/virtual-host/localhost
```

Then, huge response. The previous response was 360 chars. The new one is 300K+ chars. Here's the output comparison: 
https://gist.github.com/kenjiheigel/d73bc3cb4ef2e4db3f5e13a1354e8b3b

**Comment by shuyangzhou** [comment]
Thanks @kenjiheigel ! I will try it locally.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115696

**Pull request closed without merging**
