### PR TITLE
LPS-97083 Implement QuerySQLTransformerImpl

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
We can leave out 0a88bc6 for now if you want to avoid adding BeanModel / ChangeTrackedModel until the service builder part is ready.

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@slnn can you test run this with all the performance tests?

Thanks!

**Comment by slnn** [comment]
OK, will update results when I got them.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
There's some real test failures, will look into resolving them.

**Comment by slnn** [comment]
Here are performance test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 26edf86 | 45783 | 256 | 76.6
PR-8049 | - | 45876 | 260 | 78.4

Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 26edf86 | 57769 | 536 | 161
PR-8049 | - | 57782 | 495 | 150

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 26edf86 | 17761 | 26.3 | 72.5
PR-8049 | - | 17696 | 23.7 | 67.8

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 26edf86 | 15258 | 76.6 | 157
PR-8049 | - | 15259 | 64.2 | 145

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL FIle
-- | -- | -- | -- | --
BaseLine | 26edf86 | 26025 | 218 | 307
PR-8049 | - | 26990 | 198 | 280


Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 26edf86 | 15113 | 265 | 473
PR-8049 | - | 15033 | 227 | 441

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter
-- | -- | -- | -- | --
BaseLine | 26edf86 | 27127 | 426 | 173
PR-8049 | - | 27135 | 455 | 183


Regards
Lily

**Pull request closed without merging**
