### PR TITLE
[TECHNICAL-SUPPORT] LPS-111972 Replace TrueZip classes in ZipReader

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @shuyangzhou ,

This fix solves an issue described in [LPS-111972](https://issues.liferay.com/browse/LPS-111972). A similar commit had been already [added](https://github.com/liferay/liferay-portal/commit/90202f92e708c50383303de2651147657e911826) and [reverted](https://github.com/liferay/liferay-portal/commit/26f3eecec6377b24673b416785b0f25b8254af7a) under [LPS-76668](https://issues.liferay.com/browse/LPS-76668) in the past.
See details in [comment on PTR-1709](https://issues.liferay.com/browse/PTR-1709?focusedCommentId=2173309&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2173309).

cc: @holatuwol , @ericyanLr

Please review the changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vendeltoreki @holatuwol can we go even further to remove the TrueZip lib from codebase? Having writer using it, but reader is not, this looks odd.

**Comment by shuyangzhou** [comment]
A bit thinking on this after read through the code, we should just wipe out TrueZip for good. This kind of partial switch might bring in more confusion in the future. Please resend with a complete cleanup, thanks!

**Pull request closed without merging**
