### PR TITLE
LPS-X DBInfo does not have to be a singleton per datasource, allow po…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ssible wasted instances for better concurrency.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

Only unique failure was in a unit test https://testray.liferay.com/home/-/testray/case_results/2422418656 but it passes locally.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140569

**Pull request closed without merging**
