### PR TITLE
[TS] LPS-116316 ServletContext.getRequestDispatcher requires that the path start with a slash

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-116316

Notes from @holatuwol :

> According to the javadocs:
> 
> > The pathname must begin with a "/" and is interpreted as relative to the current context root.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
