### PR TITLE
LPS-108614

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@slnn please run this for performance regressions.  Mostly looking at memory usage.  I think journal and MB tests should be good enough.

**Comment by Preston-Crary** [comment]
ci:test

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results:

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | ae5eeff | 20316 | 333 | 134 | - | 714 | 0 | 5987009656K | 2375192K | 0K
PR | - | 20120 | 324 | 130 | -0.9647568419 | 705 | 0 | 5911657417K | 2224795K | 0K

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | ae5eeff | 8727 | 178 | 277 | - | 663 | 1 | 5554195978K | 7362320K | 2336764K
PR | - | 8635 | 172 | 276 | -1.05419961 | 658 | 1 | 5512517762K | 7066872K | 2422095K

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%） | Eden Space GC count | Old Gen GC count | Total Memory collected from eden space GC | Total Memory promoted from eden space GC | Total Memory collected from old gen CMS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | ae5eeff | 9327 | 222 | 438 | - | 547 | 1 | 4582463757K | 5985408K | 2187037K
PR | - | 9081 | 192 | 409 | -2.637504021 | 533 | 1 | 4465295199K | 5680636K | 2219355K

Regards
Lily

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8861

**Pull request closed without merging**
