### PR TITLE
LPS-77743 After PortletSession.invalidate() is called PortletRequest.getPortletSession(false) does not return null

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@jpince: Please take a look when you can and if all is well, let @shuyangzhou know so that he can review. Thanks.

**Comment by jpince** [comment]
@brianchiu can you please review the test results of this pull? Let Shuyang
know if there are no unique errors, thanks!

-- 
Jason Pince
Lead Test Engineer


Liferay Inc. | 1400 Montefino Avenue, Diamond Bar, CA 91765 USA |
877-543-3729 <(877)%20543-3729>
_____________________________________________________________________

*Confidentiality Notice:* This e-mail message, including any attachments,
is for the sole use of the intended recipient(s) and may contain
confidential and privileged information. Any unauthorized review, use,
copying, disclosure or distribution is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy
all copies of the original message.

**Comment by brianchiu** [comment]
@ngriffin7a @shuyangzhou 
There are no unique failures. The functional failure got fixed earlier today, and the central-requirements failure is happening across the board. Shuyang, you can review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55084

**Pull request closed without merging**
