### PR TITLE
LPS-75652 Avoid to use LocaleThreadLocal when it's not needed. Upgrades are failing because of this.

### PR DESCRIPTION
**Pull request by achaparro**
Hi @shuyangzhou,

When the locale is inherited from the company we don't need to use LocaleThreadLocal. Doing this we avoid to set DefaultLocale in LocaleThreadLocal anytime we need to get the siteDefaultLocale during upgrades or other processes.
    
We are applying the same rule than here: LPS-70669 https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L967

I have also added some tests to prove the error.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
Failed tests seem to not be related

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Hi @shuyangzhou,

They seem common error in CI.

Thanks.

**Comment by Preston-Crary** [comment]
ci:close

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5286

**Pull request closed without merging**
