### PR TITLE
Spring bean portlets, MVCBean portlets for CDI and Spring

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@shuyangzhou I eliminated much of the generics and went with a more straightforward design. Your code review commits have been cherry-picked on top of the new design.

Also, I verified that the following instructions work on my local system:

1. Build the branch with `ant all`

2. Since the com.liferay.bean.portlet.spring.extension isn't released yet, you have to install it into your local repository:
```
cd modules/apps/bean-portlet/bean-portlet-spring-extension
gw clean install
VERSION=2.0.0
LIFERAY_M2_DIR="../../../../.m2/com/liferay/com.liferay.bean.portlet.spring.extension/$VERSION"
mvn install:install-file \
	-Dfile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-$VERSION.jar \
	-DgroupId=com.liferay \
	-DartifactId=com.liferay.bean.portlet.spring.extension \
	-DpomFile=$LIFERAY_M2_DIR/com.liferay.bean.portlet.spring.extension-$VERSION.pom \
	-Dversion=$VERSION
```

3. In order to try the MVCBean portlet feature, I recommend that you get the following branch from my fork of the liferay-blade-samples repository:

https://github.com/ngriffin7a/liferay-blade-samples/tree/applicant

Then do the following:

```
#
# Job Applicant portlet that demonstrates CDI and JSP
#
cd maven/apps/applicant/applicant-mvcbean-cdi-jsp-portlet
mvn -P liferay clean package
cp target/*.war $LIFERAY_HOME/deploy

#
# Job Applicant portlet that demonstrates Spring and JSP
#
cd ../applicant-mvcbean-spring-jsp-portlet
mvn clean package
cp target/*.war $LIFERAY_HOME/deploy
```

Please let me know if you have any questions. I'll try to be available on Skype for you. Thanks!

**Comment by ngriffin7a** [comment]
ci:stop

**Comment by ngriffin7a** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
See https://github.com/ngriffin7a/liferay-portal/pull/63

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7804

**Pull request closed without merging**
