### PR TITLE
[TECHNICAL-SUPPORT] LPS-78513

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-78513

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Hi @shuyangzhou ,
I think this errors are not related with my change (only this commit https://github.com/shuyangzhou/liferay-portal/pull/5804/commits/eb72f061ffd055cfe504e59444771fb1319831b1). I tried to rebase in order to get better successful jobs but it seems that master has other errors.
Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56195

**Pull request closed without merging**
