### PR TITLE
LPS-X Refactor OpenIdConnectProviderManagedServiceFactory to do lazy …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…OAuthClientEntry pulling for each company on querying

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oidc

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139421

**Pull request closed without merging**
