### PR TITLE
LPS-130105 Use FriendlyURLNormalizerUtil#normalizeWithEncoding to ens…

### PR DESCRIPTION
**Pull request by tinatian**
…ure we always get the correct encoded friendly url

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Just started reviewing :)

**Comment by georgel-pop-lr** [comment]
> …ure we always get the correct encoded friendly url

Hi @tinatian,

I did some manual tests and now seems that all the cases are working.

Regards.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:reevaluate:1037401_9550

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou @tinatian Regression on this PR with Right to Left rendering

Steps to Reproduce:
1. Login to localhost:8080
2. Modify URL to access homepage in AR locale (`http://localhost:8080/ar/web/guest/home`)
3. Open product menu and attempt to navigate to any site admin portlet
BugResult

**Comment by tinatian** [comment]
@vicnate5 I can not reproduce it locally, could you please verify?

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian The screenshot is from my local machine after compiling this branch.

The test on CI is also consistently failing. The automated test steps are slight different, they go to Create a new Web Content, and on the Web Content creation form, the test will then add the `ar` locale to the URL and then see a similar error page.

Here is a video of me reproducing locally using Chrome latest:
RTLRender

**Comment by tinatian** [comment]
Fix and resent at https://github.com/shuyangzhou/liferay-portal/pull/9993.

**Pull request closed without merging**
