### PR TITLE
Lps 61123 Dummy cluster link

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Have you made sure when you deploy the real one, the dummy one will be swapped out dynamically?

**Comment by tinatian** [comment]
No, it won't. We want it to be switched dynamically, right? While, the old way is to stop the dummy one manually.

**Comment by shuyangzhou** [comment]
Better to be dynamically, just drop in the real one's jar, then it will automatically kick out the dummy one.

**Comment by tinatian** [comment]
If we want it to be dynamical, I think there are two options:

Option 1, do it at bundle level, stop installing the dummy bundle dynamically. Since we are using felix file install, this might be done to put the dummy one in a special folder or set a special install level. You said we were going to do the same dummy thing for other services, then this should be done for these dummy ones.

Option 2, do it at service level, dynamically replace the cluster related services(like ClusterLink, ClusterExecutor). If we do this, then we need to handle: a) dummy services are registered before real services; b) dummy services are registered after real services.  It would be easy for b) since we can just check if we need to register the dummy services or not, but for a) there will be potential issues since the services depend on cluster services might use cluster features before the real services are available.

By the way, I am wondering if we really need to make it dynamical. In the end, only the dummy ones are left in CE, and the real ones are in EE, in what kind of situation we would put them together?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/33225

**Pull request closed without merging**
