### PR TITLE
LPS-122233 Fix issue with caching document library when using S3Store after re-indexing

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-122233

The issue here was that a copy of the S3 Store document library was being stored in the temp folder each time a re-indexing occurred.
To solve the issue I created the method getTempFileAsStream() in S3Store.java to handle creation of the input file stream with AutoDeleteFileInputStream which will delete the files when the input stream closes.
Unfortunately, I can't bypass the cache as requested because the file needs to be accessed for re-indexing to be completed.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@noornajj this is way too aggressive. This is only for DLFileEntry reindexing, right?
You can try 2 different directions.
1) Add a post index operation to explicitly wipe out the cache files.
2) Add a thread local to https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/search/spi/model/index/contributor/DLFileEntryModelIndexerWriterContributor.java#L55, then read it from S3Store, so that you know this is for indexing only, no need to cache.
Either way, this should not be a massive change.

**Pull request closed without merging**
