### PR TITLE
Configuration override

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@shuyangzhou Real test failures here https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/317187/testReport/com.liferay.frontend.taglib.form.navigator.internal.configuration/RetrieverWhenNeitherACategoryNorAContextAreSpecifiedInTheConfigTest/testDoesNotContainValuesForANonemptyCategory/

**Comment by shuyangzhou** [comment]
@vicnate5 it is an unit test failure, not important, I will fix it shortly. Any other failures?

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@vicnate5 pushed a fix to the failed unit test.

**Pull request closed without merging**
