### PR TITLE
Dcl singleton

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@shuyangzhou Regressions found in backend tests, I can reproduce locally.

1. https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500665/testReport/com.liferay.portal.upgrade.test/WabBuildAutoUpgradeTest/testBuildAutoUpgrade/
2. https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380809/testReport/com.liferay.portal.upgrade.test/ModuleBuildAutoUpgradeTest/testBuildAutoUpgrade/
3. https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/407867/testReport/com.liferay.exportimport.test/ExportedMissingReferenceBackwardCompatbilityExportImportTest/testBackwardCompatibility/
4. https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/407867/testReport/com.liferay.exportimport.test/ExportedMissingReferenceExportImportTest/testMissingDummy/

These unit tests also failed:
https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/404412/testReport/

I reproduced with `com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverterTest`

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 pushed fixes, they are all evil reflection issues. You just never know who is secretly peeking your internal stuff...

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the new results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho will be checking this, please see previous issues in comments above.

**Comment by kyle-miho** [comment]
Previously mentioned regressions are fixed, there are a lot of new unique failures I am double checking though

**Comment by kyle-miho** [comment]
@shuyangzhou I encountered this unique failure
```
 [exec] com.liferay.bookmarks.trash.test.BookmarksEntryTrashHandlerTest > testTrashBaseModelAndParentAndDeleteGroupTrashEntries FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.IllegalArgumentException: java.lang.ClassCastException@4fe56890
     [exec]     	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:649)
     [exec]     	at com.liferay.bookmarks.service.persistence.impl.BookmarksFolderPersistenceImpl.updateImpl(BookmarksFolderPersistenceImpl.java:7055)
```
In a large amount of the unique failures, it will take too long to check every single test, but I will list some examples:
com.liferay.bookmarks.search.test.BookmarksEntryMultiLanguageSearchTest
com.liferay.bookmarks.trash.test.BookmarksEntryTrashHandlerTest
com.liferay.bookmarks.notifications.test.BookmarksUserNotificationTest

Testing this locally now as well

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@shuyangzhou Failures mentioned above are not reproducable locally, nor are reproduceable in the latest run, leading me to believe it was a race condition in CI that occured. No unique failures found

However, Semantic Version increment is required in
```
com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/core/petra/petra-concurrent] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.petra.concurrent                       MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131273

**Pull request closed without merging**
